### ISSUE TITLE
Encore plus tordu - Piptaptherum

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#10]
[Originally posted on GoogleCode (id 340) on 2011-04-08]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

<b>What data are incorrect or missing?</b>
Piptatherum racemosum Ricker ex Hitchcock

<b>What data are you expecting instead?</b>
Piptatherum racemosum (Sm.) Eaton     Man. Bot. (ed. 5) 351 1829 

Par ailleurs, le nom suivant est invalide
**Piptatherum racemosum (Sm.) Barkworth Phytologia 74(1): 19. 1993.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-27 20:45Z]

J'ai averti IPNI
