### ISSUE TITLE
inappropriate common names

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1000]
[Originally posted on GoogleCode (id 668) on 2011-08-10]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8831

<b>What data are incorrect or missing?</b>
common names: 
Neumann's cinquefoil
potentille de Neumann 
potentille printanière 

<b>What data are you expecting instead?</b>
These should be deleted.
add alpine cinquefoil as a synonym

<b>If applicable, please provide an authoritative source.</b>
Potentilla crantzii was at one time synonymized with Potentilla neumanniana, but this name is now in synonymy under P. verna.  The common names (in Fr. &amp; Eng) Neumann's cinquefoil referred to this taxon only when P. crantzii was considered a synonym of P. neumanniana.  I recommend you move these two names over to N. verna.
You also list spring cinquefoil and potentille printanière , which probably apply for Potentilla verna, so should be listed there.

I also recommend you add alpine cinquefoil as another English common name (syn), which I assume refers to the synonym Potentilla alpestris.   CalPhotos and GRIN use this common name too: http://calphotos.berkeley.edu/cgi/img_query?stat=BROWSE&amp;query_src=photos_flora_com&amp;where-genre=Plant&amp;where-namesoup=Alpine+Cinquefoil&amp;rel-namesoup=matchphrase&amp;title_tag=Alpine+Cinquefoil

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-11 21:01Z]

Following an exchange with Marc and Marylin, the change was made.

Marylin: however, spring cinquefoil is used in both crantzii and verna, one has syn, the other as accepted. Anything to do there? (not necessarily)

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2011-08-11 21:10Z]

yes best to remove spring cinquefoil from P. crantzii and use it only with P.. verna

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-12 13:19Z]

Correction made.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-02-09 16:39Z]

The vernacular's Neumann's cinquefoil and potentille de Neumann are still iisted for Potentilla verna.  In Sojark's untangling of the relationship between P. verna, P. neumanniana, and P. crantzii, he descsribes swith from P. verna (with a P. cramtzii type) to P. crantzii, then P. neumanniana, which has a type that is actually a nybrid.

 "Since 1980, P. neumannianana Rchb. 1832 has been taken up by some authors, but the only possible type for that is a hybrid between  P. heptaphylla L. and  P. incana Gaertn."

With the end being a new conserved type for P. verna, clearly separating it from P. crantzii and P. neumanniana.  So, for the short while that P. neumanniana was the accepted name for P. verna, the vernaculars in question were used, but no longer belong in synonymy, other than through a misinterpretation.  You may disagree, but I think it only confuses the nomenclature more when inapproriately applied synonyms  are retained. 

See:  Soják, J. 2009. (1892) Proposal to conserve the name Potentilla verna (Rosaceae) with a conserved type. Taxon 58(2): 652-653.
<http://docserver.ingentaconnect.com/deliver/connect/iapt/00400262/v58n2/s33.pdf?expires=1391964416&id=77143519&titleid=6069&accname=Guest+User&checksum=F1AFF3188C76F68023BB87F2D4F0C080> 
Brummitt, R.K. 2011. Report on the Nomenclature Committee for Vascular Plants: 63.Taxon 60(4): 1202-1210. 
<http://docserver.ingentaconnect.com/deliver/connect/iapt/00400262/v60n4/s25.pdf?expires=1391964750&id=77143545&titleid=6069&accname=Guest+User&checksum=04D3ACC3E182FC7A8FCC26488B28D53A>

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-03-02 17:23Z]

I saw this old issue appear on my natureserve.ca email address just recently (make sure if you see the natureserve.ca email address to switch over to the gmail address please).
Also this issue was labelled as 'fixed', I relabelled as 'started', however I really don't know what is needed yet for switching around vernaculars with the synonymy. Until the synonymy is changed or the FNA publication available for knowing where the P. neumanniana (and corresponding vernaculars) should be placed.
Luc?

**Comment by brouille** [comment]
Neumann vernaculars removed from P. verna
this closes this issue
