### ISSUE TITLE
status of E. chamissonis var. aquatile

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1003]
[Originally posted on GoogleCode (id 690) on 2011-08-19]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5270

<b>What data are incorrect or missing?</b>
Eriophorum chamissonis var. aquatile is listed as a synonym of Eriophorum chamissonis

<b>What data are you expecting instead?</b>
not sure, but in Gray's Manual, E. chamissonis var. aquatile is listed as occurring in shallow pools in nNfld. (and nEurope), but E. chamissonis is rejected from all provinces except BC, so should this synonym be moved to another species, possibly listed as: E. chamissonis var. aquatile sensu Fernald = syn. of: E. russeolum subsp. russeolulm, or perhaps a hybrid of E. russeolum x some white-bristled spp., since Fernald describes it as having paler bristles.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-22 17:30Z]

I must verify that. It is a very valid point.
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-29 19:01Z]

Here is the comment by Jacques Cayouette (2011-08-29):
"Pour cet Eriophorum chamissonis aquatile, je n’ai pas de données sur ce taxon. Je ne sais pas qui aurait mis ça en synonymie, mais je peux vérifier. C’est pas mal certain que c’est associé à E. russeolum prob. subsp. russeolum mais je ne suis pas impressionné par les caractères donnés par Fernald. Faudrait voir le type. En attendant, tu peux le laisser en synonymie de russeolum russeolum. La pâleur des épillets peut dépendre de bien des facteurs."

Currently, I will place in syn. or russeolum russeolum.

The rest is research and will not be done soon.
