### ISSUE TITLE
authorities of synonym reversed

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1004]
[Originally posted on GoogleCode (id 694) on 2011-08-20]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5273

<b>What data are incorrect or missing?</b>
Eriophorum chamissonis var. albidum auct. non (Fernald) F. Nylander 

<b>What data are you expecting instead?</b>
Eriophorum chamissonis var. albidum auct. non (F. Nylander)Fernald  

<b>If applicable, please provide an authoritative source.</b>
IPNI; you do provide the correct basionym author - F.Nylander, in the the other entry

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-22 17:27Z]

blooper
