### ISSUE TITLE
parents of hybrid subsp.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1006]
[Originally posted on GoogleCode (id 696) on 2011-08-20]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5284

<b>What data are incorrect or missing?</b>
parents of E. xmedium subsp. medium and subsp. album are both given as the same: E. russeolum subsp. russeolum x E. scheuchzeri subsp. scheuchzeri

<b>What data are you expecting instead?</b>
E. russeolum subsp. leiocarpum x E. scheuchzeri subsp. scheuchzeri

If both subsp. have the same parents, they should be the same species (hybrid).

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-22 17:23Z]

Sue

According to J. Cayouette, the morphology of the two entities differs even though they have the same parent. It may be that the female parent differs, etc. This is why we maintained the two here.

It is not only nomenclature here, but biology also.
