### ISSUE TITLE
Synonyme à ajouter: Betula × caerulea

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#101]
[Originally posted on GoogleCode (id 2063) on 2014-01-26]

Selon FNA:
The blue birches ( Betula × caerulea Blanchard) have been variously considered to represent a true species or a hybrid between B . papyrifera Marshall and B . populifolia Marshall (T. C. Brayshaw 1966) or B . papyrifera and the big blue birch B . caerulea-grandis (M. L. Fernald 1922). Both B . × caerulea and B . caerulea-grandis have been shown in more recent experimental studies to be of hybrid origin between B . cordifolia Regel and B . populifolia (A. G. Guerriero et al. 1970; W. F. Grant and B. K. Thompson 1975; P. E. DeHond and C. S. Campbell 1989). Individuals of these hybrids combine characteristics of the parents, the infructescence scales and leaves somewhat resembling those of B . populifolia , and the habit and exfoliating reddish bark that of B . cordifolia .

**Comment by brouille** [comment]
Betula ×caerulea ajouté en syn de Betula ×caerulea-grandis
