### ISSUE TITLE
missing common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1011]
[Originally posted on GoogleCode (id 705) on 2011-08-23]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5685

<b>What data are incorrect or missing?</b>
no English common name provided

<b>What data are you expecting instead?</b>
We had Blake's milk vetch listed in our NF checklist, presumably based on the synonym: Astragalus blakei Eggl., which we had included in our checklist

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-26 13:15Z]

Marilyn

A missing English vernacular

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2011-09-22 14:16Z]

added Blake's milk-vetch, thanks
