### ISSUE TITLE
mistake in listing of two subspecies; incorrect 2nd subspecies entry name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1012]
[Originally posted on GoogleCode (id 706) on 2011-08-23]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4791  (see subsp. listed)
and 
http://data.canadensys.net/vascan/taxon/4790

<b>What data are incorrect or missing?</b>
Under Carex brunnescens, instead of the two subspecies, 
subsp. sphaerostachya and subsp. brunnescens,
C. brunnescens subsp. brunnescens is replaced by: Carex canescens var. brunnescens (Persoon) W.D.J. Koch

<b>What data are you expecting instead?</b>
Carex brunnescens (Persoon) Poiret subsp. brunnescens should be listed as the typical subspecies and 
Carex canescens var. brunnescens (Persoon) W.D.J. Koch should be listed as a synonym of C. br. subsp. brunnescens

<b>If applicable, please provide an authoritative source.</b>
Tropicos, FNA

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-26 13:13Z]

What a blooper
