### ISSUE TITLE
common name issue for Elatine americana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1016]
[Originally posted on GoogleCode (id 735) on 2011-09-04]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5465

<b>What data are incorrect or missing?</b>
élatine à trois étamines

<b>What data are you expecting instead?</b>
élatine d'Amérique

<b>If applicable, please provide an authoritative source.</b>
If Elatine triandra Schkuhr is distinct (European) species, whose name was misapplied to the NAm species, I don't think the common name for the European species should still be retained for the 
North American sp. We used élatine d'Amérique for the French common name in the Can. Forest Service (Plant Hardiness Zone dB) website [though I just realized that the accented vowels all turned to 'i's on my browser display, so will have to have that fixed on my end].

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-09-04 19:47Z]

Also, if longstemmed waterwort was previously associated with Elatine triandra, I suggest the accepted English common name should be American waterwort.  That is what the other web-based taxonomic dBs are using.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-09 12:48Z]

Marc and Marilyn

Je vous réfère ce problème.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-09-09 13:22Z]

I agree. I added the accepted French name "élatine d'Amérique" in the database, and I retained "élatine à trois étamines" as a synonym since it has been used in the past for North American material.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2011-09-22 14:13Z]

agree - fixed
