### ISSUE TITLE
confusion over accepted rank/authorities

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1027]
[Originally posted on GoogleCode (id 748) on 2011-09-06]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9829

<b>What data are incorrect or missing?</b>
Kalmia microphylla var. occidentalis (Small) Roy L. Taylor &amp; MacBryde
Kalmia microphylla var. occidentalis (Small) J.E. Ebinger

<b>What data are you expecting instead?</b>
If you're recognizing varieties for Kalmia microphylla, you should list Kalmia microphylla var. occidentalis (Small) Ebinger (no initials needed). (BTW, John Ebinger was my advisor for my M.Sc.)
Taylor &amp; MacBryde authored the subsp.:
Kalmia microphylla subsp. occidentalis (Small) Roy L. Taylor &amp; MacBryde

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-09 12:22Z]

I cannot correct this currently due to a technical problem to be solved
