### ISSUE TITLE
typo in synonym epithet and authority abbreviation

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1029]
[Originally posted on GoogleCode (id 750) on 2011-09-07]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5543

<b>What data are incorrect or missing?</b>
Pleuricospora longipetatla T.J. Howell

<b>What data are you expecting instead?</b>
Pleuricospora longipetala Howell

<b>If applicable, please provide an authoritative source.</b>
Tropicos,IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-09 12:16Z]

also corrected sp. epithet
