### ISSUE TITLE
Carex ×subreducta Lepage

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#103]
[Originally posted on GoogleCode (id 2065) on 2014-01-26]

Salut

Un ajout
Selon Plants.USDA.gov
Carex ×subreducta Lepage [subspathacea × bigelowii]	
Ontario, Québec, Labrador, Groenland

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-27 14:47Z]

problème taxonomique - note que ce nom provient du vieux VASCAN

à peine discuté par Cayouette & Catling 92, qui mentionnent un article in prep. de Cayouette - il me faut vérifier ce qu'il en est

Luc
