### ISSUE TITLE
missing synonym?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1037]
[Originally posted on GoogleCode (id 774) on 2011-09-17]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
 http://data.canadensys.net/vascan/taxon/5569

<b>What data are incorrect or missing?</b>
Vaccinium ashei J.M.Rehde  

<b>What data are you expecting instead?</b>
Add: Vaccinium ashei J.M.Rehde as a synonym, if accurate

<b>If applicable, please provide an authoritative source.</b>
Vaccinium ashei is considered a synonym of V. virgatum, which is synonymized in VASCAN under V. corymbosum.  In the Plant Hardiness Zone Database, there are several reports of Vaccinium ashei (rabbiteye blueberry), so it would be good to add this name as a synonym.  While FNA doesn't list it, they give a reference to a full list of synonyms for V. corymbosum:
Vander Kloet, S. P. 1980. The taxonomy of the highbush blueberry, Vaccinium corymbosum. Canad. J. Bot. 58: 1187-1201. 
Vander Kloet, S. P. 1980b. Erratum: The taxonomy of the highbush blueberry, Vacciniumcorymbosum. Canad. J. Bot. 58: 2028-2029.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-09-17 17:56Z]

I see you've listed Polycodium ashei Harbison as a synonym of V. stramineum, so I I'm not sure if Vaccinium ashei J.M.Reade should be placed in synonymy with V. stramineum or V. corymbosum. 
However, Tropcis treates them as two distinct taxa:
http://www.tropicos.org/Name/50333440
Polycodium ashei was replace by Vacc. harbisonii, since Vaccinium ashei J.M.Reade alreasy exised in Vaccium.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-07 19:13Z]

Polycodium ashei Harbison is not a syn of V. corymbosum nor related to V. ashei j.M. Reade
