### ISSUE TITLE
Ajout de synonyme

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#104]
[Originally posted on GoogleCode (id 2066) on 2014-01-26]

Chenopodium berlandieri Moq. var. boscianum (Moq.) Wahl 

pour le nom suivant: Chenopodium standleyanum

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-27 14:41Z]

Fred

Il n'est pas aisé d'ajouter un synonyme sans source crédible, d'autant que l'auteur FNA ne mentionne pas standlyeanum sous boscianum. Ajouter un synonymes sans savoir si cela modifie le concept taxonomique utilisé est risqué.

Quelle source aurais tu pour cela?

Luc

**Comment by brouille** [comment]
@FredCoursol 
http://www.tropicos.org/Name/7200828 : l'espèce est acc pour la Fl. Missouri
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242415443 : acc à titre de var. de berlandieri
Je ne vois pas comment l'ajouter comme syn de standleyanum
Luc
