### ISSUE TITLE
authorities of species name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1046]
[Originally posted on GoogleCode (id 804) on 2011-10-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6495

<b>What data are incorrect or missing?</b>
Wolffia borealis (Engelmann) E. Landolt &amp; O. Wildi

<b>What data are you expecting instead?</b>
Wolffia borealis (Engelmann) Landolt &amp; Wildi

However, FNA, GRIN, and Tropicos just have Landolt; perhaps the paper is published by Landolt &amp; Wildi, but the authority for this name is just Landolt (or vice-versa).  I think you may need to see the original article to be sure.  Ber. Geobot. Inst. ETH Stiftung Rubel. 44:137. 1977. 

<b>If applicable, please provide an authoritative source.</b>
IPNI authors, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-27 14:27Z]

The name was not validly published. 

Gandhi et al. are preparing a publication to validate the name.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-27 12:52Z]

Wolffia	borealis (Engelm.) Landolt & Wildi ex Gandhi, Wiersema & Brouillet
