### ISSUE TITLE
Chenopodium berlandieri var. zschackei

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#105]
[Originally posted on GoogleCode (id 2067) on 2014-01-26]

La carte de FNA mentionne cette variété pour l'ouest du Québec (Baie James jusqu'à Montréal).
Le Québec est absent dans VASCAN

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-27 14:57Z]

J'ajoute cela avec trépidation: aucune source québécoise ne mentionne cela. As tu vérifié l'herbier?

Luc
