### ISSUE TITLE
Chenopodium glaucum Linnaeus var. glaucum

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#106]
[Originally posted on GoogleCode (id 2068) on 2014-01-26]

Salut

Pourquoi toutes les provinces qui entourent le Québec affiche introduit alors que le Québec affiche indigène.
Mystère!

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 18:17Z]

il y a ambiguité sur le statut du taxon ds FNA. À résoudre

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 19:32Z]

Note que les provinces maritimes sont misses comme indigène. Il n'est donc pas correct the dire que toutes les provinces entourant le QC ont introduit. La partie maritime du Québec est continue avec les Maritimes. Le ms FNA ne le traite pas comme introduit.

Il est possible que certaines populations de l'ouest du QC soient des introductions mais que des populations maritimes soient indigènes.

Je n'ai donc une donnée pour changer le statut présentement

Luc
