### ISSUE TITLE
status of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1062]
[Originally posted on GoogleCode (id 837) on 2011-10-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4761

<b>What data are incorrect or missing?</b>
Carex atratiformis var. raymondii (Calder) Porsild

<b>What data are you expecting instead?</b>
This combination was not found in Tropicos, IPNI, nor FNA; is it valid?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-11-01 20:45Z]

name removed, same authorities as subsp. - error in entry
