### ISSUE TITLE
authority abbreviation of species & common name question

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1064]
[Originally posted on GoogleCode (id 839) on 2011-11-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9690

<b>What data are incorrect or missing?</b>
Carex billingsii (O.W. Knight) C.D. Kirschbaum

<b>What data are you expecting instead?</b>
Carex billingsii (O.W. Knight) Kirschbaum

also, the 2nd English common name, Billing's three-seeded bog sedge has the apostrophe misplaced.  This an error made in NHIC and other publications, but since the plant is named after Mr. Billings, not Mr. Billing, as the epithet implies, it should be corrected here.

<b>If applicable, please provide an authoritative source.</b>
IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-11-01 20:36Z]

Fixed both the authority and the English vernacular. The two names were not coherent with each other anyway.

I am copying Marilyn so she knows. Correction done.
