### ISSUE TITLE
Ajout de synonyme à Circaea x sterilis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#107]
[Originally posted on GoogleCode (id 2069) on 2014-01-26]

Circaea × intermedia in eastern North America with particular reference to Ontario. Erich Haber, 1977. 
Canadian Journal of Botany, 1977, 55:2919-2935.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 18:21Z]

je ne suis pas certain que je peux car le taxon, décrit d'Europe pro sp, pourrait avoir un parent différent. Sans quoi le nom de Boufford serait invalide.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-25 16:26Z]

Circeae x sterilis est C. canadensis x C. alpina

C. x intermedia est C. lutetiana x C. alpina

À l'époque où Haber publiait, 1977, on utilisait lutetiana pour canadensis en Amérique du Nord, d'où l'utilisation du nom intermedia pour l'hybride. Or lutetiana est européen et donc intermedia ne s'applique pas en AN.

Je ne peux ajouter le synonyme que si j'ajoute auct. non Ehrh., puisque c'est une application sensu et non stricte.

Luc

Luc
