### ISSUE TITLE
inappropriate accepted common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1070]
[Originally posted on GoogleCode (id 884) on 2011-12-15]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7196

<b>What data are incorrect or missing?</b>
Scotch pine

<b>What data are you expecting instead?</b>
Scots pine as accepted English common name

<b>If applicable, please provide an authoritative source.</b>
Scotch is an alcoholic drink, not a common name for Scottish (in this case Scots) plants.  I know it's in FNA and non-technical websites, but it's continued use is inappropriate and considered inoffensive to Scottish people.

Note what GRIN says about 'Scotch pine' (Source: Trees US [but this adjective is best avoided, may cause offence in Scotland]) 

See: 
http://www.conifers.org/pi/Pinus_sylvestris.php
http://www.treesforlife.org.uk/tfl.scpine.html
http://na.fs.fed.us/fhp/invasive_plants/weeds/scots-pine.pdf

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-12-15 19:21Z]

Sue: I believe you are correct. I am transferring the issue to Marilyn.

Marilyn: please address the issue raised by Sue. Thanks.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-31 13:42Z]

have changed to accepted name of Scots pine, however Scotch pine is well used, as you know. Plus it's not offensive - that is one person's opinion only
