### ISSUE TITLE
common name issue for Rubus parviflorus

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1072]
[Originally posted on GoogleCode (id 887) on 2011-12-17]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8942

<b>What data are incorrect or missing?</b>
sparseflowered thimbleberry

<b>What data are you expecting instead?</b>
[just] thimbleberry as the preferred or accepted name

<b>If applicable, please provide an authoritative source.</b>
This plant is know simply as thimbleberry throughout North America.  The flowers are not very sparse, with up to 15 large flowers possible on each stem, though few bloom simultaneously.  Fernald (Gray's Manual) notes that the epithet parviflorus means small-flowered, but that this is a mis-nomer; I expect spare-flowered has similar origins, but it also is not accurate.  This plant is very common in my area and is anything but sparse-flowered (see first image on my NOPD link).

See:
&lt;http://www.botany.hawaii.edu/faculty/carr/ofp/rub_par.htm&gt; 
&lt;http://www.uwgb.edu/biodiversity/herbarium/shrubs/rubpar01.htm&gt; 
&lt;http://web.ewu.edu/ewflora/Rosaceae/Rubus%20parviflorus.html&gt; 
&lt;http://www.pnwflowers.com/flower/rubus-parviflorus&gt; 
&lt;http://science.halleyhosting.com/nature/gorge/5petal/rose/rubus/thim.htm&gt; 
&lt;http://dendro.cnre.vt.edu/dendrology/syllabus/factsheet.cfm?ID=252&gt; 
&lt;http://montana.plant-life.org/species/rubus_parvi.htm&gt; 
&lt;http://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Rubus+parviflorus&gt; 
&lt;http://wisplants.uwsp.edu/scripts/detail.asp?SpCode=RUBPAR&gt; 
&lt;http://www.paghat.com/thimbleberry.html&gt; 
&lt;http://cahedb.wsu.edu/nativePlant/scripts/webDisplayPlant.asp?ID=nv044&gt; 
&lt;http://www.calflora.org/cgi-bin/species_query.cgi?where-calrecnum=7200&gt; 
&lt;http://bolt.lakeheadu.ca/~borfor/shrubs/shrub41.htm&gt; 
&lt;http://plants.usda.gov/java/profile?symbol=RUPA&gt; 
&lt;http://www.laspilitas.com/nature-of-california/plants/rubus-parviflorus&gt; 
&lt;http://www.northernontarioflora.ca/description.cfm?speciesid=1003131&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-12-19 19:08Z]

Sue

I am referring this to Marilyn.


Marilyn

Could you please consider this comment from Sue? Thanks.
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-02-02 13:24Z]

fixed
