### ISSUE TITLE
typo in French common name?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1075]
[Originally posted on GoogleCode (id 890) on 2011-12-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4737

<b>What data are incorrect or missing?</b>
carex à gaine tronquée

<b>What data are you expecting instead?</b>
carex à graine tronquée

<b>If applicable, please provide an authoritative source.</b>
I'm not sure, but this (gaine) seems to be a typo.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-06 13:59Z]

Sue, gaine is equivalent to sheath (leaf base wrapping the stem). It is correct as is.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-01-16 16:19Z]

Thanks Luc, I'll fix my list.
