### ISSUE TITLE
typo in authority abbreviation of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1078]
[Originally posted on GoogleCode (id 893) on 2011-12-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4795

<b>What data are incorrect or missing?</b>
Carex hartmannii A. Cajander

<b>What data are you expecting instead?</b>
Carex hartmannii Cajander  (1935)

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI; IPNI authors has:
•	A.Cajander - Aimo Aarno Antero Cajander 1908- 
•	Cajander - Aimo Kaarlo Cajander 1879-1943

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-05 21:53Z]

hartmanii also has a single n...
