### ISSUE TITLE
incorrect parenthetical author in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1079]
[Originally posted on GoogleCode (id 894) on 2011-12-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4797

<b>What data are incorrect or missing?</b>
Carex subloliacea (Fernald) E.P. Bicknell

<b>What data are you expecting instead?</b>
Carex subloliacea (Laestadius) E.P. Bicknell

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-05 21:51Z]

FNA is erroneous
