### ISSUE TITLE
Ajout de synonyme: Datura metel

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#108]
[Originally posted on GoogleCode (id 2070) on 2014-01-26]

Il faudrait l'ajouter à Datura inoxia.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:48Z]

IL y a ici un petit foullis taxonomique à vérifier

**Comment by brouille** [comment]
Selon le ms FNA, Datura metel n'est pas un syn de D. innoxia ms une sp distincte
LB
