### ISSUE TITLE
typo in authority abbreviation of synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1080]
[Originally posted on GoogleCode (id 895) on 2011-12-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>
<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4804

<b>What data are incorrect or missing?</b>
Carex arctogena H. Smith
Carex capitata subsp. arctogena (H. Smith) Böcher

<b>What data are you expecting instead?</b>
Carex arctogena Harry Smith (1940)
Carex capitata subsp. arctogena (Harry Smith) Hiitonen (1944), non (Harry Smith) Böcher (1952), nec (Harry Smith) Böcher ex Á.Löve et al. (1971)

<b>If applicable, please provide an authoritative source.</b>
IPNI &amp; Tropicos; Tropicos should list the Bocher and Love et al combinations as illegimate.

IPNI authors has:
Harry Sm. - Karl August Harald (`Harry') Smith 1889-1971
H.Smith stands for Henry smith
H.Sm. - Henry Smith 1786-1868

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-05 21:49Z]

Note that the Böcher name is a later homonym and thus illegitimate - it is based on the same basionym - this is not noted in TROPICOS or IPNI, but is now so noted in VASCAN
