### ISSUE TITLE
placement of synonym under wrong subsp?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1083]
[Originally posted on GoogleCode (id 898) on 2011-12-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4833

<b>What data are incorrect or missing?</b>
Carex debilis var. intercursa Fernald

<b>What data are you expecting instead?</b>
delete Carex debilis var. intercursa Fernald; this should be with var. debilis (US only range)

<b>If applicable, please provide an authoritative source.</b>
Unfortunately, FNA lists var. intercursa Fernald for both var. debilis and var. rudgei, an obvious mistake.  But referring to Gray's Manual, Fernald describes var. intercursa as with perigynia 5-9 mm long and midrib evanescent below the scale tip - traits that fit with FNA's key for var. debilis, not var. rudgei, which has perigynia 5-6.2 mm long and acute to short-awned pistillate scales. It seems from Fernald descriptions in Gray's that var. pubera should also be moved to var. debilis.  You may have to check with the author of this Carex section for clarification.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-06 19:54Z]

Plant List places var. intercursa as a synonym of var. debilis, as you are suggesting; likewise for var. pubera. I will therefore correct the mistake in VASCA and remove those varieties from the synonyms, as we do not have this var. in Canada.
