### ISSUE TITLE
common names for this entry

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1085]
[Originally posted on GoogleCode (id 900) on 2011-12-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9835

<b>What data are incorrect or missing?</b>
none given

<b>What data are you expecting instead?</b>
En: distant sedge
Fr: carex à épis distants, laîche à épis distants

<b>If applicable, please provide an authoritative source.</b>
&lt;http://www.plant-identification.co.uk/skye/cyperaceae/carex-distans.htm&gt; 
&lt;http://www.habitas.org.uk/flora/species.asp?item=2413&gt; 
&lt;http://www.tela-botanica.org/nn13660&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-05 21:32Z]

This is a new species for Canada and I had forgotten to request Marc and Marilyn to provide vernaculars. Thanks for the suggestions.

Marc and Marilyn: please add vernacular for this new report. Thanks.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-01-05 22:07Z]

I entered the available French names for this species. Thank you Susan.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:27Z]

completed
