### ISSUE TITLE
Synonyme à ajouter: Erigeron acris subsp. politus

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#109]
[Originally posted on GoogleCode (id 2071) on 2014-01-26]

Salut

Si j'ai bien compris, tous ce que nous avions sous ssp. politus est revenu sous ssp. kamtschaticus.  Alors, pourquoi ssp. politus n'est pas dans les synonymes?  Idem avec Erigeron politus?

FNA mentionne:

Erigeron angulosus Gaudin, E. asteroides Andrzejowski ex Besser, E. droebachiensis O. F. Mueller ex Retzius, E. elongatus Ledebour, and E. politus Fries, names previously used for the widespread American plants of var. kamtschaticus, refer to Eurasian endemics (summary in G. L. Nesom 2004e). E. Hultén (1968) restricted the name var. kamtschaticus to a single North American collection made at &quot;Junction Firth R. and Mancha Creek on the Alaska-Yukon boundary in August 1961,&quot; treating all others of the species in North America as subsp. politus. Entire-leaved plants apparently are the common form of the species even in the Kamtschatka area, and var. kamtschaticus appears to be correct at varietal rank for the North American plants. Erigeron kamtschaticus has been treated as a species separate from E. acris in other recent literature. Circumscription and rank of E. acris and closely related taxa are in need of study.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:47Z]

Il me faut vérifier car parfois des noms ne peuvent être mis en synonymie à cause de leur sens premier

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-09 13:34Z]

Le nom politus réfère a un taxon qui n'est PAS en Amérique du Nord

si je l'ajoute, il me faudra ajouter auct. non

Luc

**Comment by brouille** [comment]
Le paragraphe cité plus haut débute ainsi: Erigeron angulosus Gaudin, E. asteroides Andrzejowski ex Besser, E. droebachiensis O. F. Mueller ex Retzius, E. elongatus Ledebour, and E. politus Fries, names previously used for the widespread American plants of var. kamtschaticus, refer to Eurasian endemics (summary in G. L. Nesom 2004e)

Donc à moins qu'il y ait eu un grand usage de politus au CAnada, je ne peux le mettre en syn de kamtchat.

Luc
