### ISSUE TITLE
Hieracium ×fassettii Lepage

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#110]
[Originally posted on GoogleCode (id 2072) on 2014-01-27]

Salut

Il s'agit d'un synonyme de Hieracium ×fernaldii Lepage.
Cependant, Hieracium ×fassettii Lepage a été décrite une année avant l'autre.  Cependant, un des parents de Hieracium ×fassettii a été réduit en synonymie (Hieracium kalmii X scabrum) pour devenir (Hieracium scabrum X umbellatum)qui sont les parents de Hieracium x fernaldii.
Qui a priorité dans ce cas?
 
Hieracium × fassettii Lepage -- Naturaliste Canad. 87: 94, fig. 9. 1960 (GCI) 
Hieracium × fernaldii Lepage -- Naturaliste Canad. 88: 46, fig. 3. 1961 (GCI)

**Comment by FredCoursol** [comment]
[Originally posted on GoogleCode on 2014-01-27 11:56Z]

J'oubliais.  Peut importe la priorité, il faut ajouter le Québec dans la répartition car le spécimen type de Hieracium x fassetti a été décrit pour le Québec.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:46Z]

à valider
L

**Comment by brouille** [comment]
H. x fassetti acc
H. x fernaldii syn
