### ISSUE TITLE
synonym errors

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1104]
[Originally posted on GoogleCode (id 923) on 2012-01-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4976

<b>What data are incorrect or missing?</b>
Carex norvegica var. inferalpina (Wahlenberg) Nylander
Carex halleri var. inferalpina Wahlenberg
Carex anagare 

<b>What data are you expecting instead?</b>
Carex norvegica var. inferalpina (Wahlenberg) B.Boivin
Carex alpina var. inferalpina Wahlenberg - which you also have included. I can't find any combination of this taxon in C. halleri.
Carex angarae 

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos, FNA

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-01-14 14:08Z]

Note that in FNA, C. angarae is misspelled C. angare.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-16 15:27Z]

added homotypic syns from TROPICOS
removed the halleri syn
