### ISSUE TITLE
consistent disagreement of Holm authority in FNA vs. Tropicos and IPNI

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1106]
[Originally posted on GoogleCode (id 925) on 2012-01-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4978

<b>What data are incorrect or missing?</b>
Carex physochlaena Holm

<b>What data are you expecting instead?</b>
see note below:

<b>If applicable, please provide an authoritative source.</b>
FNA lists T.Holm, but IPNI and Tropicos have Holm.  But the dates seem to better fit with Holm.  The same situation occurs in Carex acutina var. petrophila Holm; Carex rhomboidea Holm, Carex dives Holm, Carex warmingii Holm, Carex lugens Holm, Carex consimilis Holm, Carex cyclocarpa Holm, Carex cryptantha Holm, Carex neurochlaena Holm, Carex vulgaris var. limnophila Holm, Carex vulgaris var. lipocarpa Holm   C. verecunda Holm, Carex microchaeta Holm; Carex scirpoidea var. stenochalaena Holm; Carex scopulorum Holm; C. brachypoda Holm, C. prionophylla Holm, C. chimaphila Holm, C. spectabilis var. superba Holm (FNA: all T.Holm)

I think the problem in FNA stems from the fact that both Holms have Theodor in their name.  IPNI authors uses these abbreviastions:
Holm: Herman Theodor Holm
T.Holm: Theodor Holm

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-16 15:16Z]

Sue

Thanks for this. I will inform FNA nomenclatural editors and let them handle it.

I will correct all T. Holm that are inappropriate here.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-17 13:58Z]

All T. Holm mentioned in list have been corrected to Holm.

There may be remaining ones (ignoring spectabilis var. superba, which may or may not exist)
