### ISSUE TITLE
Ajout d'un hybride: Hieracium ×grohii Lepage

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#111]
[Originally posted on GoogleCode (id 2073) on 2014-01-27]

Salut

Hieracium ×grohii Lepage
Naturaliste Canad. 87: 100, fig. 12. 1960 

Parents selon IPNI: Hieracium canadense X lachenalii

Pas trouvé encore l'équivalent moderne qui serait Hieracium umbellatum X vulgatum

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:45Z]

Pas besoin d'équivalent moderne car les noms sont synonymes. Les noms des parents changent, c'est tout.
Mais il me faut vérifier

**Comment by brouille** [comment]
ajouté avec certaines craintes relatives à la synonymie de lachenalii et vulgatum
LB
