### ISSUE TITLE
partentage of hybrid

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1117]
[Originally posted on GoogleCode (id 936) on 2012-01-15]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5180

<b>What data are incorrect or missing?</b>
Carex rostrata X Carex saxatilis 

<b>What data are you expecting instead?</b>
Carex saxatilis X Carex utriculata

<b>If applicable, please provide an authoritative source.</b>
FNA (at end of C. saxatilis description), USDA

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-16 14:35Z]

I have to check the litterature to be sure. The worse is that there is another hybrid reported with this parentage.

So it is likely you are right.

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-01-16 20:56Z]

I'm not sure, but this may be the same entry, but an un-named version of the X:
http://data.canadensys.net/vascan/taxon/5060

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-03 18:05Z]

second entry removed - it had been entered separately to deal with a hybrid with a non-recognized var. of one parent - happens it is the same taxon

I have a nagging doubt, however: there also can be hybrids of saxatilis with rostrata (fide FNA - but not in Ford et al. 93) - it could be that the second entry, now removed, was a rostrata hybrid - will have to check further
