### ISSUE TITLE
Neottia vs Listera

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#112]
[Originally posted on GoogleCode (id 2076) on 2014-01-27]

Salut

Sous Neottia, il n'y a pas de répartition.
Sous Listera, on retrouve les mêmes noms que sous Neottia.  Les deux sont acceptés.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:44Z]

Tout a été tranféré et Listera effacé.

Luc
