### ISSUE TITLE
authority of variety; taxonomic status of taxon

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1120]
[Originally posted on GoogleCode (id 939) on 2012-01-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9844

<b>What data are incorrect or missing?</b>
Carex rariflora var. androgyna (Wahlenberg) Smith

<b>What data are you expecting instead?</b>
Carex rariflora var. androgyna A.E.Porsild

<b>If applicable, please provide an authoritative source.</b>
Tropicos &amp; PanArctic Flora
http://www.nhm.uio.no/english/research/infrastructure/paf/3309048
Note: in the above webpage, PAF says that Porsild's var. androgyna is an abberent form not worthy of taxonomic status.  Has this var. proved to be valid?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-16 21:43Z]

androgyna was maintained tentatively due to the fact it was listed by COSEWIC for NWT - this needs to be investigated

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-17 13:29Z]

following emails with B. Bennett, COSEWIC, and Bruce Ford, I am putting var. androgyna in syn. of C. rariflora, and transferring all data from var. rariflora to the sp., the var. becoming a syn
