### ISSUE TITLE
authority abbreviation for species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1121]
[Originally posted on GoogleCode (id 940) on 2012-01-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5052

<b>What data are incorrect or missing?</b>
Carex recta W. Boott

<b>What data are you expecting instead?</b>
Carex recta Boott

<b>If applicable, please provide an authoritative source.</b>
Tropicos, FNA, IPNI
Also, I noticed that FNA has different authorities listed for each of the combinations with C. kattegatensis.  FNA and Tropicos list C. kattegatensis Fr. ex Lindm., but provides no date or lit information. I assume that FNA should be corrected too.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-16 21:40Z]

fixed Boott

I have to check for the second issue.

**Comment by brouille** [comment]
FNA, TROPICOS and IPNI all cite Fr. ex Nyman, as does POWO.
FNA is correct for authorities of the two names, one of which is the basionym [unranked]
No correction is required
Luc
