### ISSUE TITLE
Ajout d'un synonyme: Puccinellia distans subsp. borealis (Holmb.) W.E. Hughes 

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#113]
[Originally posted on GoogleCode (id 2077) on 2014-01-27]

Selon TROPICOS &amp; Soreng et al 2003.

Puccinellia distans subsp. borealis (Holmb.) W.E. Hughes est un synonyme de Puccinellia nutkaensis (J. Presl) Fernald &amp; Weath.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:27Z]

J'ai ajouté le nom, mais il serait bon de me justifier l'ajout d'un synonyme: ce nom a-t-il été utilisé au Canada, entre autres?

Luc
