### ISSUE TITLE
Erreur d'orthographie potentielle ou réelle?

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#114]
[Originally posted on GoogleCode (id 2079) on 2014-01-28]

Salut

On parle de l'île Spitsbergen dans le Svalbard (avec un i).

Qu'est-ce que l'on fait avec le nouveau nom Coptidium ×spitsbergense?  Est-ce qu'il devrait prendre le &quot;e&quot; au lieu du &quot;i&quot;?

Ranunculus ×spetsbergensis (Nathorst) Hadač dans VASCAN
Ranunculus pallasii var. spetsbergensis Nathorst dans VASCAN

J'ai été voir la publication originale et l'auteur a utilisé Ranunculus pallasii var. spetsbergensis Nathorst  (C'est l'erreur orthographique du départ).

Plusieurs sites utilisent une ortographie différente
Ranunculus spitsbergensis Hadač fide IPNI &amp; TROPICOS
Ranunculus × spetsbergensis  (Nath.) Hadač fide TROPICOS

J'ai contacté TROPICOS pour leur mentionner l'erreur dans le premier cas.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:23Z]

il faut valider

**Comment by brouille** [comment]
spitsbergensis est utilisé généralement
rien à modifier
LB
