### ISSUE TITLE
status of subspecies

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1147]
[Originally posted on GoogleCode (id 966) on 2012-01-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5265

<b>What data are incorrect or missing?</b>
Since subsp. triste has been elevated to species status, is there a reason to keep subsp. angustifolium?  I can find no other subsp. in the US database, but maybe in Eurasia?

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-23 14:31Z]

The taxonomy of Eriophorum is messy and not completely resolved here. I tried to have a specialist help, but there has been no time. 

For later.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-20 20:35Z]

There is still a Eriophorum angustifolium subsp. komarovii (V.N.Vassil.) Vorosch. fide Plant List that I do not know whether it is a distinct sp. or a subsp.

Plant List, however, keeps triste as a subsp., which tells a lot about its taxonomy...

For the time being, I will leave the subsp.
