### ISSUE TITLE
incorrect Scandinavian letter used in authority name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1148]
[Originally posted on GoogleCode (id 967) on 2012-01-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5268

<b>What data are incorrect or missing?</b>
Eriophorum vaginatum var. opacum Bjørnstrom
Eriophorum opacum (Bjørnstrom) Fernald

<b>What data are you expecting instead?</b>
Eriophorum vaginatum var. opacum Björnström 
Eriophorum opacum (Björnström ) Fernald

<b>If applicable, please provide an authoritative source.</b>
IPNI &amp; IPNI authors
•  Björnstr. - Fredrik Johan Björnström 1833-1889 

FNA and Tropicos use the wrong Scandinavian letter.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-23 14:30Z]

Stictly speaking, these letters can be interchanged. But I will correct orthography to conform with IPNI
