### ISSUE TITLE
parentage of Eriophorum x porsildii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1149]
[Originally posted on GoogleCode (id 968) on 2012-01-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5287

<b>What data are incorrect or missing?</b>
Eriophorum chamissonis C.A. Meyer.
X
Eriophorum vaginatum subsp. spissum (Fernald) Hultén. 

<b>What data are you expecting instead?</b>
Eriophorum russeolum Fries {?subsp?}
x
Eriophorum vaginatum subsp. spissum (Fernald) Hultén. 

<b>If applicable, please provide an authoritative source.</b>
Since this hybrid is described from Ontario, E. chamissonis cannot be one of the parents.  It must be one of the 2 subsp. of E. russeolum that was misIDed as E. chamissonis.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 15:32Z]

You are right about this issue.

The combination you suggests is E. x pylaieeanum, however

It so happens that WCSP (the only source to formally treat this correctly) treats porsildii as a syn. of the above - this is what I will do.

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-13 19:31Z]

OK,  But I think you've 1 too many 'e's in the name below.   Shouldn't 
it be E. x pylaieanum?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 20:29Z]

Sue

This is what is in VASCAN. I did not change that.

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-13 20:40Z]

Well, the original question still seems to apply.  How can E. chamissonis be listed as one of the parents of an Ontario hybrid when E. chamissonis only occurs in BC?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 20:44Z]

If you go to VASCAN under pylaieanum, chamissonis is NOT mentioned, at least
as I am staring at it.

What chamissonis are you talking about? Also, it is possible that vaginatum
or spissum were described as subsp. of chamissonis at one time, which would
explain the usage.

But it is not currently in VASCAN (or I cannot see it).

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-13 20:58Z]

I was looking at: E. x porsildii (the link above for issue 968), not E. 
pylaieanum.  The range for E. xporsildii shows Ontario only and the 
subsp. for chamissonis is not listed.  I agree, in that it was probably 
named at a time when the taxonomy of these species had not been 
finalized, but the parents and range listed here for E. xporsildii don't 
make coincide.   Doesn't this show up on your list?


  /Eriophorum �porsildii/ Raymond

/Eriophorum �porsildii/ Raymond 
<http://data.canadensys.net/vascan/taxon/5287> is an *accepted species* 
name.


    Hybrid parents

/Eriophorum chamissonis/ C.A. Meyer 
<http://data.canadensys.net/vascan/taxon/5270>.

/Eriophorum vaginatum/ subsp. /spissum/ (Fernald) Hult�n 
<http://data.canadensys.net/vascan/taxon/5280>.


    Vernacular names

  * linaigrette de Porsild
    <http://data.canadensys.net/vascan/vernacular/10665> McMurray &
    Lehela, 1999

Porsild's cottongrass <http://data.canadensys.net/vascan/vernacular/10666>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 21:01Z]

Sue

I will simply remove the parents I forgot to remove - they should not be
there.

Luc
