### ISSUE TITLE
Salix ×gaspensis C.K. Schneider

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#115]
[Originally posted on GoogleCode (id 2080) on 2014-01-28]

Salut

Erreur dans VASCAN
Salix ×gaspensis C.K. Schneider
il manque un &quot;e&quot; et le nom doit être Salix ×gaspeensis C.K. Schneider
J'ai vérifié la publication originale et le double &quot;ee&quot; est présent dans gaspeensis

Argus utilise Salix x gaspeensis
http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=242445666

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:22Z]

Je ne peux valider l'orthographe dans IPNI ou TROPICOS car le nom n'y est pas. Il me faut vérifier. Il pourrait s'agir d'une faute typographique... ou être correct. Je n'ai pas la réf. de Schneider pour valider.
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-13 14:27Z]

Trouvé gaspeensis dans TROPICOS - corrigé

Luc
