### ISSUE TITLE
Mt. Albert goldenrod

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#116]
[Originally posted on GoogleCode (id 2081) on 2014-01-28]

Salut

Ce nom anglais est présent à 2 endroits dont une mention avec Solidago simplex var. simplex qui n'est pas présent au Québec.  Bizarre d'avoir un nom anglais qui désigne un emplacement au Québec alors qu'elle est absente....

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:18Z]

I am transferring the issue to Marilyn

Marilyn: this vernacular is applied to both Solidago chlorolepis (where appropriate) and to S. simplex (species) and var. simplex, where it is inappropriate (see Fred Coursol's comment above)

Please remove where misapplied, if you agree

Thanks

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-02-04 17:47Z]

Fixed. Many thanks for sending this correction, greatly appreciated!
