### ISSUE TITLE
incorrect parent in x; objection to common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1163]
[Originally posted on GoogleCode (id 982) on 2012-01-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6192

<b>What data are incorrect or missing?</b>
Iris setosa Pallas  X  Iris versicolor Linnaeus. 

<b>What data are you expecting instead?</b>
Iris hookeri Penny X Iris versicolor Linnaeus

<b>If applicable, please provide an authoritative source.</b>
Since we don't have Iris setosa in Nfld, this can't be the parentage; however, in FNA Anderson described the cross as with I. setosa var. canadensis, which is now I. hookeri.

See FNA, under I. versicolor: E. Anderson (1936) showed rather conclusively that Iris versicolor arose as an amphidiploid between I. virginica (n = 35) and I. hookeri (I. setosa var. canadensis) (n = 19). Back-cross hybrids have been produced both ways: I. virginica × I. versicolor producing Iris ×robusta E. S. Anderson, and I. versicolor × I. hookeri producing I. ×sancti-cyri J. Rousseau. 

Also, I think it's an insult to call this iris the sanctimonious iris.  Sounds like ITIS got that name from a poor computerized translation service.  Wasn't the taxon named for the community of Saint-Cyr in Quebec?  Why not call it Saint-Cyr's iris.  That's the name I'm going to use in the Plant Hardiness Zone and NOPD databases, as well as our new checklist.  If you have a copy of Rousseau's original article, it might show the origin of the name.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-23 13:38Z]

The error stems from changes in taxonomy. The status of I. hookeri as a distinct species has been debated and at times, it has been recognized as a var./subsp. of setosa. The hybrid name had not been changed from early data entry.

English vernaculars have yet to be validated. I will transmit your point to Marilyn. ITIS vernaculars were obtained from Kartesz, which often were poor choices. Normally hybrids are not named unless common.
Marilyn, I do not believe this vernacular is appropriate either.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-01-24 21:58Z]

I believe the French name "iris de Saint-Cyr" is correct as it stands.

Marc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-01-26 20:34Z]

Yes, the French common name is fine as is.   Would the proper English 
counterpart to this name be with or without a hyphen?

Also, I checked Scoggan and he indicates that the type location of this 
hybrid is Anticosti Island, so another option for an English common name 
could be Anticosti sedge.

Thanks, Sue.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:27Z]

completed
