### ISSUE TITLE
question about hybrid status

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1164]
[Originally posted on GoogleCode (id 983) on 2012-01-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6177

<b>What data are incorrect or missing?</b>
Iris germanica Linnaeus

<b>What data are you expecting instead?</b>
Iris ×germanica Linnaeus  (I. pallida x I. variegata)

<b>If applicable, please provide an authoritative source.</b>
GRIN: http://www.ars-grin.gov/cgi-bin/npgs/html/tax_search.pl
FNA also discusses the hybrid origin of this species, but does not show it as a hybrid.  I'm not sure which is correct.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-23 13:32Z]

Hybrid origin and F1 hybrid are obviously different though related concepts. I will have to check.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-11 20:46Z]

hybrid status added but I cannot add both parents since one is not in the flora - I added only pallida
