### ISSUE TITLE
Viola ×melissifolia Greene [septentrionalis × sororia]

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#117]
[Originally posted on GoogleCode (id 2082) on 2014-01-28]

Salut

J'ai trouvé cette violette dans PLANTS.USDA.GOV

On mentionne Terre-Neuve, Ile-du-Prince-Edouard et Nouveau-Brunswick et la source est VASCAN.

On ne la mentionne pas dans VASCAN.  Un ajout?

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:15Z]

Pas nécessairement - il pourrait y avoir eu un rectificatif à cause du ms FNA. J'attends de voir la version finale.
Luc

**Comment by brouille** [comment]
selon certaines source, c'est plutôt cucullata x sororia (= x bissellii, un syn ultérieur)
LB
