### ISSUE TITLE
question about authority in synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1174]
[Originally posted on GoogleCode (id 994) on 2012-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6836

<b>What data are incorrect or missing?</b>
Cymbidium pulchellum Swartz
Cathea pulchella Salisbury

<b>What data are you expecting instead?</b>
Cymbidium pulchellum (Salisb.) Swartz
Cathea pulchella (Salisb.) Salisbury 
[(1812)- based on Limodorum pulchellum Salisb. (1796) ]

<b>If applicable, please provide an authoritative source.</b>
I know the 'pulchella' name is considered superfluous, but wouldn't the later combinations, all based on Limodorum pulchellum Salisb., still retain the basionym?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-24 15:12Z]

FNA has Salisbury, but neither TROPICOS nor IPNI. TROPICOS does not provide much information on homotypic synonyms in this case, and IPNI use replaced synonym. I do not know the rule. Will have to ask.

**Comment by brouille** [comment]
I added (Salisbury) to the names but there is still some reservation because of the nom. superfl. nature of the Salisb. basionym
