### ISSUE TITLE
authority of synonym; placement of 2nd synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1176]
[Originally posted on GoogleCode (id 996) on 2012-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6838

<b>What data are incorrect or missing?</b>
Calypso borealis Salisbury
Cypripedium bulbosum Linnaeus

<b>What data are you expecting instead?</b>
Calypso borealis (Swartz) Salisbury - basionym Cymbidium boreale Swartz
Cypripedium bulbosum Linnaeus - should this name be in synonymy under the species name (or Eurasian subsp. bulbosa), rather than the North American variety&gt;

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-24 15:24Z]

I am removing Cypripedium bulbosum to the sp.
