### ISSUE TITLE
question about accepted common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1178]
[Originally posted on GoogleCode (id 998) on 2012-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6842

<b>What data are incorrect or missing?</b>
long-bracted frog orchid

<b>What data are you expecting instead?</b>
frog orchid

<b>If applicable, please provide an authoritative source.</b>
In Gray's manual, the name long-bracted or bracted [green orchis] is used only for var. breacteata, while the species. H. virids is named frog orchis.  Similarly, Luer uses frog orchid for the species, but long-bracted [orchid] only for var. bracteata, which is in synonymy, but does not represent the entire species. I think frog orchid should be the accepted English common name and long-bracted frog orchid listed as a common name synonym.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-24 18:07Z]

Marilyn: could you please deal with this issue?

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:15Z]

changed to frog orchid, however synonym long-bracted frog orchid is of equal usage in Canada
