### ISSUE TITLE
Ptelea trifoliata

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#118]
[Originally posted on GoogleCode (id 2094) on 2014-02-01]

L'indigénat de cette plante est plus que douteuse.

Voici le commentaire de Jacques Labrecque lors de la dernière réunion du COSEPAC: C'est une plante rare au Canada mais d'après moi elle n'est pas indigène au Québec. Dans les récoltes on note souvent les observations :naturalisé, jardin, etc. De plus, deux des récolteurs, le fr. Euphrosin-Joseph et le Fr. Cléonique-Joseph, étaient responsables des jardins des frères de l'instruction chrétienne à Laprairie et Pointe du Lac. Pour Oka on mentionne un parc ou &quot;introduit le long de la clôture&quot; etc. Il ne semble pas y avoir de récolte récente dans un habitat clairement indigène et je rejoins donc Rousseau (1974) en considérant le Ptelea d'indigénat douteux ou échappé de culture.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-06 21:12Z]

Il y a un danger tout de même: je t'ai donné le cas de l'Eurybia divaricata, rejeté par Boivin pcq récolté à Rougement, chez les pères...
Rousseau 74 ne cite pas tous les spécimens existants, en passant.
Scoggan 78 le considère introduit au Québec ms indigène dans le sud ontarien.

Le plus troublant est le manque de récolte indigène récente.

Ça vacille.

**Comment by brouille** [comment]
changé le statut à introduit
