### ISSUE TITLE
missing common name?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1189]
[Originally posted on GoogleCode (id 1010) on 2012-01-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6913
http://data.canadensys.net/vascan/taxon/6915

<b>What data are incorrect or missing?</b>
missing French common name under var. flava

<b>What data are you expecting instead?</b>
platanthère à gorge tuberculée

<b>If applicable, please provide an authoritative source.</b>
You have this name listed for var. herbiola: 
platanthère à gorge tuberculée variété petite-herbe
but not for the species.  Should it be added to the var. flava entry also?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-27 18:30Z]

Je vais laisser Marc prendre soin du vernaculaire manquant.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-01-30 22:28Z]

The name « platanthère à gorge tuberculée variété petite-herbe » is only a synonym, and I cannot find a source for « platanthère à gorge tuberculée » at the species level. It is usually not advisable to coin new synonyms. However, I did enter the accepted name "platanthère jaune" which was missing at the species level.
