### ISSUE TITLE
Autorité- Oxytropis sericea

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#119]
[Originally posted on GoogleCode (id 2109) on 2014-02-04]

Salut

Oxytropis sericea Nuttall
Oxytropis sericea Torrey &amp; A. Gray selon ThePlantList

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-06 21:27Z]

Ni TROPICOS ni IPNI n'ont les autorités de PL - fishy, non?

**Comment by brouille** [comment]
@FredCoursol 
Nuttall est correct fide Gandhi
Luc
