### ISSUE TITLE
another synonym 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1195]
[Originally posted on GoogleCode (id 1016) on 2012-01-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6928

<b>What data are incorrect or missing?</b>
This is correct: Platanthera hyperborea var. viridiflora (Chamisso) Kitamura
... but since Luer's name is more commonly known and Kitamura's name is not in Tropicos or IPNI, you might want to add it as a synonym (isonym).  Here is the link I found to Kitamura's name:
http://bean.bio.chiba-u.jp/bgplants/ylist_detail_disp.php?pass=25100
<b>What data are you expecting instead?</b>

Platanthera hyperborea (Linnaeus) Lindley var. purpurascens (Rydberg) Luer 1975, nom. illeg. isonym, non (Rydberg) Kitamura 1966

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-27 20:04Z]

I do not understand why you expect var. purpurascens instead of var. viridiflora 

I added the later homonym as nom. illeg.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-01-27 22:26Z]

My mistake, I copied the wrong line (above var. viridflora); should have read:
Platanthera hyperborea (Linnaeus) Lindley var. viridiflora (Chamisso) Luer 1975, nom. illeg. isonym, non (Chammiso) Kitamura 1966
