### ISSUE TITLE
status of hybrid; also = P. huronensis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1196]
[Originally posted on GoogleCode (id 1017) on 2012-01-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6932

<b>What data are incorrect or missing?</b>
Platanthera ×media (Rydberg) Luer (without the basionym)
is listed as a synonym of P. huronensis, along with all the other combinations and basionym.  

<b>What data are you expecting instead?</b>
Platanthera ×media (Rydberg) Luer placed as a synonym of P. huronensis, or all related entries moved to this entry.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-27 20:05Z]

This is an issue that needs to be solved - whther or not it is a syn. or a hybrid of the two taxa mentioned - the name is twice in VASCAN
I cannot do it now

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-28 13:26Z]

Names placed in syn
The records attributed to P. x media in various provinces, if based on hybrid P. dilatata x P. aquilonis, need to be dealt with, however, if not already handled. 

Also, ascertaining whether huronensis hybridizes w/ other spp in Canada would be useful
