### ISSUE TITLE
question of priority for species combination - Soó or Soják

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1198]
[Originally posted on GoogleCode (id 1019) on 2012-01-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6936

<b>What data are incorrect or missing?</b>
Was it determined which combintation has priority?
Pseudorchis straminea (Fernald) Soó (1972) or Soják (1972)?

<b>What data are you expecting instead?</b>
? The Panarctic Flora notes: The combination Pseudorchis straminea was published independently the same year by Soó, Monogr. Icon. Orch. Europ. 2, Nachtr.: XII (1972) and by Soják, Cas. Nár. Mus., Odd. Prir. 141: 63 (1972). We have not found out which publication has priority.

<b>If applicable, please provide an authoritative source.</b>
See: http://www.nhm.uio.no/english/research/infrastructure/paf/270902

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-27 20:08Z]

Thanks for raising this. I do not know and will have to ask. If they did not succeed in the Panarctic Fl., I wonder who will.

**Comment by brouille** [comment]
All databases now show only Sojak
LB
