### ISSUE TITLE
Autorité de Cornus nuttallii 

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#120]
[Originally posted on GoogleCode (id 2110) on 2014-02-04]

Salut

TROPICOS a les deux autorités suivantes.

Cornus nuttallii Audubon	Ornithol. Biogr. 4: 482	1838
Cornus nuttallii Audubon ex Torr. &amp; A. Gray	Fl. N. Amer. 1: 652	1840

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-25 16:15Z]

Le ms FNA a seulement Audubon. Je vais conserver Audubon pour l'instant, jusqu'aux corrections nomenclaturales de Gandhi.

Luc
