### ISSUE TITLE
authorities of synonyms and typo in 1 synonym var.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1204]
[Originally posted on GoogleCode (id 1026) on 2012-01-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6276

<b>What data are incorrect or missing?</b>
Juncus effusus var. pacificus Fernald
Juncus effusus var. compactus Lejeune
Juncus effusus var. dicipiens (typo also in FNA)

<b>What data are you expecting instead?</b>
Juncus effusus var. pacificus Fernald &amp; Wiegand
Juncus effusus var. compactus Lejeune &amp; Courtois
Juncus effusus var. decipiens 

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI; For var. compactus, Tropicos has Lejeunne &amp; Coutr., which is a mistake.  If you click on the publication in that entry, the authors are listed as Lejeune, A.L.S. &amp; R.J. Courtois

See also: :  &lt;http://www.biologie.uni-ulm.de/cgi-bin/query_all/details.pl?id=74720&amp;stufe=A&amp;typ=PFL&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-30 14:15Z]

TROPICOS has a typo on Courtois indeed - IPNI does not list source and is incorrect
