### ISSUE TITLE
confusion over authority of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1208]
[Originally posted on GoogleCode (id 1030) on 2012-01-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6311

<b>What data are incorrect or missing?</b>
Juncus trifidus subsp. monanthos (Jacquin) Ascherson &amp; Graebner (1904)

<b>What data are you expecting instead?</b>
Juncus trifidus subsp. monanthos (Jacquin) K. Richter (1890)

<b>If applicable, please provide an authoritative source.</b>
Tropicos lists the K.Richter combination as illeg., but provides no date for Ascherson &amp; Graebner; IPNI does not mention any subspecific combination of J. monanthos Jacq.  The French Synonyomique database lists both K. Richter and Ascherson &amp; Graebner, but according to them, K. Richter is earlier and there is no reason to assume it is an illegitimate name.  See: 
Scroll down to Juncus trifidus subsp. monanthos:
http://www2.dijon.inra.fr/flore-france/ja-jz.htm#J  

see also:http://www.bgbm.org/IOPI/GPC/PTaxonDetail.asp?RIDentifier=365#

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-30 15:13Z]

The French site, however, does state "ead. comb." after the name and gives 1890, while the date for a comb. by Bluff & Fingerh. (not Asch. & Graeb.) is 1825! So there is grounds to make the Richter comb illegitimate.
And the IOPI site provides yet an earlier comb. for the latter, by Oeder, in 1821

This is a mess that needs more clarification

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-01-30 20:17Z]

Hi Luc,

The subspecies combinations listed in the French site are:
*subsp*. monanthos (Jacq.) K.Richter (1890);
*subsp*. monanthos (Jacq.) Ascherson & Graebner (1904).
The ead. comb. refers to the latter combination since it is listed after 
the semicolon.
...while the only varietal combination they list is:
*var*. monanthos (Jacq.) Bluff & Fingerh. (1825)

_IOPI has_

*subsp*. monanthos (Jacq.) K.Richter (1890), nom. illeg.
*subsp*. monanthus (Jacq.) Ascherson & Graebner, nom. illeg.
from the notes at the bottom of the entry re: K. RIchter's name, it 
looks like the illeg. status may be due to this name being considered a 
synonym?
*"*Type*:*T: [Austria] in summis jugis Schneeberg, & in ejusdem 
praecipitio Sawgrube; syn: P; icon in N.J.Jacquin, Enum. Stirp. Vindob. 
tab. 4, fig. 1; syn."
However, I don't see a reason why Asherson and Graebner's name would 
also be considered illeg., unless K. Richter's name is accepted.

*var*. monanthos (Jacq.) Oefer (1821) - so looks like this is OK for 
var. rank.
*var*. monanthos (Jacq.) Bluff & Fingerh. (1825), nom. illeg.

**Comment by brouille** [comment]
This is all moot because infrasp. monanthos is a synonym of the European Oreojuncus monanthos. I am therefore removing the names from synonymy of O. trifidus.
LB
