### ISSUE TITLE
question about J.Gay in or ex Laharpe

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1212]
[Originally posted on GoogleCode (id 1035) on 2012-01-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6264

<b>What data are incorrect or missing?</b>
Juncus canadensis J. Gay ex Laharpe

<b>What data are you expecting instead?</b>
?Juncus canadensis J. Gay 

<b>If applicable, please provide an authoritative source.</b>
Tropicos has J.Gay in Laharpe - but they seem to be the only ones; 
IPNI, FNA, and GRIN have j.Gay ex Laharpe

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-31 13:27Z]

I have more confidence in IPNI than TROPICOS on in and ex - Luc
