### ISSUE TITLE
homonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1213]
[Originally posted on GoogleCode (id 1037) on 2012-01-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6307

<b>What data are incorrect or missing?</b>
Juncus fluitans Michaux
Juncus verticillatus Pursh

<b>What data are you expecting instead?</b>
Juncus fluitans Michaux., nom. illeg. hom., non Lamarck
Juncus verticillatus Pursh, nom. illeg. hom., non Persoon

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 12:33Z]

J. verticillatus Pursh is not in TROPICOS or IPNI - needs checking
J. fluitans done

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-17 15:50Z]

Juncus verticillatus Pers. [non Pursh] syn de J. bulbosus in TelaBotanica

I am removing the name from VASCAN
