### ISSUE TITLE
Placement of genus 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1217]
[Originally posted on GoogleCode (id 1043) on 2012-02-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/1369

<b>What data are incorrect or missing?</b>
The genus Lophiola is place in the Haemodoraceae here...

<b>What data are you expecting instead?</b>
... but APG has includes in the Nartheciaceae. 

<b>If applicable, please provide an authoritative source.</b>
APG website

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 17:16Z]

Haemodoraceae was from FNA.

You are correct that APG places it in Nartheciaceae, in a different order!

Luc
