### ISSUE TITLE
Bouteloua or Buchloë? 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1231]
[Originally posted on GoogleCode (id 1057) on 2012-02-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7485

<b>What data are incorrect or missing?</b>
Bouteloua dactyloides (Nuttall) Columbus

<b>What data are you expecting instead?</b>
Mary Barkworth has this under the name Buchloë dactyloides (Nutt.) Engelm. in FNA

<b>If applicable, please provide an authoritative source.</b>
http://www.herbarium.usu.edu/treatments/Buchloe.htm#Buchloe_dactyloides

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-06 21:30Z]

But the Catalogue of New World Grasses, which I find sometimes a bit more current for generic attributions, places the taxon as I did. It is a more recent reference, too.
