### ISSUE TITLE
Potentilla pensylvanica Linnaeus var. atrovirens (Rydberg) Th. Wolf.

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#124]
[Originally posted on GoogleCode (id 2128) on 2014-02-13]

Salut

Il manque ce synonyme dans VASCAN.
Ce nom vient de Rousseau, C.  Géographie floristique du Québec-Labrador.
Il y a même une carte avec un seul point à Nominingue.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-25 16:11Z]

Il y a un problème avec ce nom. Je ne peux l'ajouter tel quel. Il faut investiguer.
Luc

**Comment by brouille** [comment]
ajouté
