### ISSUE TITLE
authorities of synonyms; validity of species?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1248]
[Originally posted on GoogleCode (id 1084) on 2012-02-11]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9629

<b>What data are incorrect or missing?</b>
Calamagrostis cinnoides (Muhlenberg) Bartworth
Deyeuxia nuttaliana Vasey
Agrostis glauca Muhlenberg

<b>What data are you expecting instead?</b>
Calamagrostis cinnoides (Muhlenberg) W.P.C.Barton
Deyeuxia nuttaliana (Steudel) Vasey
Agrostis glauca Muhlenberg, nom. inval., pro syn.

<b>If applicable, please provide an authoritative source.</b>
There is no Bartworth in IPNI authors; Tropicos, although Tropicos, IPNI, and The Plant List say that W.P.C.Barton's name is illegitimate, and a syn. of C. canadensis.  Barkworth does not post an online treatment for Calamagrostis, which may mean it is under review?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-15 14:51Z]

correction to nuttalliana (l missing)

Agrostis glauca Muhl. is accepted - it is the other combs. that are illeg. fide Tropicos
