### ISSUE TITLE
authorities of several synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1256]
[Originally posted on GoogleCode (id 1092) on 2012-02-12]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7502

<b>What data are incorrect or missing?</b>
a) Calamagrostis neglecta (Ehrhart) Gaertner, Meyer &amp; Scherbius nom. illeg.

b) Calamagrostis borealis Laestadius
   C. stricta subsp. stricta var. borealis (Laestadius) Hartman
   C. neglecta var. borealis (Laestadius) Richter
   C. neglecta subsp. borealis (Laestadius) Á. Löve &amp; D. Löve

c) Calamagrostis groenlandica (Schrank) Druce
d) Calamagrostis laxiflora Kearney
e) Calamagrostis micrantha var. sierrae Jones
f) Calamagrostis neglecta subsp. stricta (Timm) Tzelev [typo]
g) Deyeuxia neglecta var. wrightii Kearney
h) Deyeuxia borealis Vasey ex Macoun
i) Calamagrostis neglecta subsp. groenlandica (Scharnk - typo) Matuszkiewicz

<b>What data are you expecting instead?</b>
a) Calamagrostis neglecta (Ehrhart) G.Gaertner, Meyer &amp; Scherbius nom. illeg.

b) Calamagrostis borealis C. Laestadius
   C. stricta subsp. stricta var. borealis (C. Laestadius) Hartman
   C. neglecta var. borealis (C. Laestadius) Kearney
   C. neglecta subsp. borealis (C. Laestadius) Selander

c) Calamagrostis groenlandica (Schrank) Kunth [Druce made the varietal combination in Calam. neglecta]
d) Calamagrostis laxiflora Kearney, nom. illeg. hom., non Phil.
e) Calamagrostis micrantha var. sierrae M.E.Jones
f) Calamagrostis neglecta subsp. stricta (Timm) Tzvelev
g) Calamagrostis neglecta var. wrightii Kearney
h) Deyeuxia borealis Macoun, nom. inval.
i) Calamagrostis neglecta subsp. groenlandica (Schrank) Matuszkiewicz

<b>If applicable, please provide an authoritative source.</b>
a) It should be G. Gaertner, not P.Gaertner, as given in Tropicos.
See IPNI entry for C. neglecta: [&quot;Abbreviation G.Gaertn. used because of information from S. Dressler that he was known as Gottfried Gaertner during his lifetime. According to a Walloonian custom the name Philipp, his father's name, was added after death. Another possible explanation is from Dr K.P. Buttler who points out that the death notice in Flora, 1826(1): 32 states: &quot;...starb zu Hanau Hr. Dr. Phil. Gottfried Gartner.&quot; where 'Phil.' may have been interpreted as Philipp.&quot;]  This latter explanation sounds more logical, Dr. Phil. meant to represent Ph.D.  
In IPNI authors,there is no P. Gaertner, only Gottfried Gaertner.

    A.Gaertn. - Alwin Gaertner fl. 1954

    C.F.Gaertn. - Carl (Karl) Friedrich von Gaertner 1772-1850

    G.Gaertn. - Gottfried Gaertner 1754-1825

    Gaertn. - Joseph Gaertner 1732-1791

b) IPNI author has: 

    C.Laest. - Carl Petter Laestadius 1835-1920 

    Laest. - Lars Levi Laestadius 1800-1861 

c-i) Tropicos, IPNI, some but not all in both

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-17 13:41Z]

b) C. neglecta subsp. borealis : IPNI has the Löve and both citations are 1950 - I will wait before correcting because I do not know which is earliest among the two - not in both databases at the same time
