### ISSUE TITLE
Toxicodendron radicans - port de l'espèce

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#126]
[Originally posted on GoogleCode (id 2130) on 2014-02-13]

Salut

Tu as inversé les ports des Toxicodendron radicans.

Var. Rydbergii: Arbuste
Var. radicans: Liane

Rousseau, Marie-Victorin et Gray's manual s'entendent....

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-13 16:55Z]

Le traitement de FNA dit:
var. radicans: shrub or liana
var. rydbergii: shrub

alors?

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-13 16:56Z]

J'ai corrigé.
