### ISSUE TITLE
authorities of synonyms & 1 typo

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1260]
[Originally posted on GoogleCode (id 1096) on 2012-02-12]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7571

<b>What data are incorrect or missing?</b>
Distichlis spicata var. stricta (Torrey) Bettle [typo]
Distichlis stricta (Torrey) Greene

<b>What data are you expecting instead?</b>
Distichlis spicata var. stricta (Torrey) Scribner 1894, non Torrey) Beetle 1943
Distichlis stricta (Torrey) Rydberg

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-15 14:24Z]

the Grass Manual (FNA Grasses) is full of incorrect authorities, it seems
