### ISSUE TITLE
erroneous entry from Tropicos

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1264]
[Originally posted on GoogleCode (id 1100) on 2012-02-12]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7546

<b>What data are incorrect or missing?</b>
Steinchisma cupreum var. lindheimeri (Nash) Lelong

<b>What data are you expecting instead?</b>
delete this entry

<b>If applicable, please provide an authoritative source.</b>
Tropicos says this is an erroneous entry.  See:
http://www.tropicos.org/Name/100366758

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-13 19:51Z]

Thanks. I do not always open the entry when making additions. This will teach me.
