### ISSUE TITLE
placement of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1269]
[Originally posted on GoogleCode (id 1105) on 2012-02-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7553

<b>What data are incorrect or missing?</b>
Panicum nitidum Lamarck

<b>What data are you expecting instead?</b>
Panicum nitidum Lamarck is the basionym of Dichanthelium dichotomum subsp./var. nitidum in CNWG and Tropicos, recognized as a distinct taxon from the seUS.  Has this whole taxon been synonymized under subsp. dichotomum?

<b>If applicable, please provide an authoritative source.</b>
FNA treats all subspecific taxa as subsp.; however, CNWG has a mishmash of varieties and subspecies.  Am not sure what is going on there.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-20 20:55Z]

Panicum nitidum removed from VASCAN; the taxon is not even in Canada
I guess this is an entry from an early phase of the FNA 25 ms and has not been properly reexamined later
FNA 25 does not even give synonyms in Dichanthelium (even basionyms), which is pretty poor - so even the source is erroneous
