### ISSUE TITLE
Elymus virginicus var. jenkensii Bowden

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#127]
[Originally posted on GoogleCode (id 2132) on 2014-02-17]

Salut

Un synonyme à ajouter pour Elymus curvatus selon TROPICOS
Ce nom vient de Grasses of Ontario

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-25 14:31Z]

ajouté: il est mis en synonymie ds NWG, donc c'est OK pour moi car c'est le concept suivi par VASCAN (malgré FNA)
