### ISSUE TITLE
authority of synonym; question of placement

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1272]
[Originally posted on GoogleCode (id 1108) on 2012-02-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7561

<b>What data are incorrect or missing?</b>
Panicum ovale (Nash) Lelong

<b>What data are you expecting instead?</b>
Panicum ovale Elliott [there is no combination with (Nash) Lelong]
shouldn't this taxon be a synonym of Dichanthelium ovale (Elliott) Gould &amp; C.A.Clark

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI, CNWG

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-13 14:48Z]

The synonymy in FNA 24 was not wholly coherent. I will have to revisit attribution.

Anyway, CMWG differs so dramatically here that something needs fixing.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-21 18:46Z]

Panicum ovale (Nash) Lelong: this is not the species but the subspecies - the wrong rank was attributed to the taxon, which hides the subsp.

I requested the change in the database (I cannot change it in the back-end) from David Shorthouse
