### ISSUE TITLE
genus of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1273]
[Originally posted on GoogleCode (id 1109) on 2012-02-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7563

<b>What data are incorrect or missing?</b>
Panicularia ovale var. villosum (A. Gray) Lelong

<b>What data are you expecting instead?</b>
Panicum ovale var. villosum (A. Gray) Lelong

<b>If applicable, please provide an authoritative source.</b>
Tropicos, CNWG; there is no Panicularia ovale, but there is a Panicum ovale var. villosum.
Also, I noticed that CNWG has this subsp. of D. ovale as a synonym of Dichanthelium acuminatum var. acuminatum. Is this new, or just incorrect?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-13 14:39Z]

There are possibly differences of taxon concept between FNA and CNWG; it seems that they included the whole subsp. into D. a. subsp. a.

I cannot judge such matter. Dichanthelium is a mess anyway. I will leave as is for now, with Grass Manual as source, however good or bad.
