### ISSUE TITLE
authorities of 1 synonym; typo in authority of species author; placement of 2 synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1274]
[Originally posted on GoogleCode (id 1110) on 2012-02-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7530
http://data.canadensys.net/vascan/taxon/7531

<b>What data are incorrect or missing?</b>
a) Deschampsia cespitosa (Linnaeus) Paliso [typo] de Beauvois subsp. cespitosa

b) Deschampsia cespitosa subsp. parviflora (Thuillier) K. Richter

c) Deschampsia cespitosa var. arctica Vasey
   Deschampsia cespitosa var. maritima Vasey

<b>What data are you expecting instead?</b>
a) Deschampsia cespitosa (Linnaeus) Palisot de Beauvois subsp. cespitosa
   also, for the Species entry: should also be as above

b) Deschampsia cespitosa subsp. parviflora (Thuillier) Dumortier (1824), non (Thuillier) K. Richter (1890)

c) Deschampsia cespitosa var. arctica Vasey
   and 
Deschampsia cespitosa var. maritima Vasey - both listed as synonyms of subsp. beringensis in CNWG and Tropicos

<b>If applicable, please provide an authoritative source.</b>
Tropicos and CNWG
Re: subsp. parviflora; Tropicos indicates that Dumortier (1824) is probably earlier, but the rank of subsp. has not been verified.
See: http://www.tropicos.org/Name/50077165
HWR, the French Index Synonymique has this entry under D. cespitosa:
[subsp.] parviflora (Thuill.) Dumort. [1824, Obs. Gram. Fl. Belg. : 120] ; ead. comb. K. Richter [1890, Pl. Eur., 1 : 56] ; ead. comb. Jáv. &amp; Soó [1951, Magyar Noven. Kezik. : 949] 2n = 26, 28 + Ga 6

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-13 14:31Z]

I am keeping K. Richter for this entry currently, until the issue as to the rank of the Dumortier name is cleared. There is uncertainty there, even in the French index.

I erased the accepted homonym accepted taxon, which is not recognized in the Grasses Manual (electronic) or in CNWG
