### ISSUE TITLE
authorities of species & status

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1275]
[Originally posted on GoogleCode (id 1111) on 2012-02-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7533

<b>What data are incorrect or missing?</b>
Deschampsia cespitosa subsp. parviflora (Thuillier) Jávorka &amp; Soó

<b>What data are you expecting instead?</b>
Deschampsia cespitosa (L.) P.Beauv. subsp. parviflora (Thuillier) K.Richter (or Dumortier's combination, discussed earlier) are the only subsp. parviflora entries that I can find, but you have this entry as a synonym of D. cespitosa subsp. cespitosa.

<b>If applicable, please provide an authoritative source.</b>
Tropicos, CNWG, IPNI, FNA.

FNA writes: &quot;Many cultivars of Deschampsia cespitosa subsp. cespitosa have been developed. At one time, the most frequently cultivated plants were distinguished by their combination of large (20–40 cm) panicles and small (2.5–4 mm) spikelets, and were called D. cespitosa var. parviflora (Thuill.) Coss. &amp; Germ. or D. cespitosa subsp. parviflora (Thuill.) K. Richt. Such plants are treated here as one part of the spectrum of variation in subsp. cespitosa.&quot;

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-02-14 00:14Z]

A couple more links I found that use (Thuiller) Dumortier as the subsp. authority.
	<http://inpn.mnhn.fr/espece/cd_nom/133795> 
	<http://www.tela-botanica.org/nt6766>  

Also Deschampsia cespitosa subsp. parviflora (Thuillier) Jávorka & Soó was published in 1951 (in French Index Synon.), so is a much later homonym that either Dumortier's (1824) or K. Richter's (1890) names.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-15 14:10Z]

this has been fixed before I saw your entry. I removed the subsp. parviflora accepted entry and corrected the other one
