### ISSUE TITLE
Juncus bufonius var. halophilus

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#128]
[Originally posted on GoogleCode (id 2137) on 2014-02-22]

Salut

Pourquoi retenir cette variété alors que FNA  et la flore du Québec nordique de Payette ne la retiennent pas?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-23 19:53Z]

Pcq le sp�cialiste mondial le fait.
Luc

Le 14-02-22 18:26, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :
