### ISSUE TITLE
misplacement of var. authorities 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1283]
[Originally posted on GoogleCode (id 1121) on 2012-02-15]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2442

<b>What data are incorrect or missing?</b>
Sambucus racemosa subsp. pubens (Michaux) Trautvetter &amp; C.A. Meyer var. pubens

<b>What data are you expecting instead?</b>
Sambucus racemosa subsp. pubens var. pubens (Michaux) Trautvetter &amp; C.A. Meyer 

<b>If applicable, please provide an authoritative source.</b>
the subsp. author is given in the previous Vascan entry, this is just a misplacement

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-15 13:49Z]

Fide Code: authorities are placed last when non autonymic - the fact that we use tetranomial does not change that. 
Correct

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-02-26 00:08Z]

I don't think you understood my point.
Species: Sambucus racemosa Linnaeus - no problem
Subsp.:  Sambucus racemosa subsp. pubens (Michaux) Hultén (1937) - no problem
Variety: Sambucus racemosa subsp. pubens (Michaux) Trautvetter & C.A.Meyer var. pubens
- the vareity entry should be: 
Sambucus racemosa subsp. pubens var. pubens (Michx.) Trautvetter & C.A.Meyer (1856)  See: IPNI

This is not an autonym, since Trautv. & C.A.Meyer's varietal name preceeded Hulten's subspecies name. The varietal authors names are correct, but incorrectly placed AFTER the subspecies name, rather than AFTER the VARIETAL name.
