### ISSUE TITLE
Question about synonymy of misapplied name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1289]
[Originally posted on GoogleCode (id 1130) on 2012-02-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8634

<b>What data are incorrect or missing?</b>
Qeustion - Potentilla anserina subsp. groenlandica was listed in our NF checklist as present in Labrador: Coastal arctic and subarctic w and eNA, wEurope, and eAsia; N to n-most Lab.; hal.
However, it has been excluded here.  I assume the new FNA treatment has shown this to be exclusively European, so under what subsp. should the synonymy be listed?

<b>What data are you expecting instead?</b>
? Potentilla anserina subsp. groenlandica auct. non Tratt. listed as a syn. of subsp. egedii?  If not, to which taxa had this name been misapplied?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-19 21:10Z]

Part of the issue here is that names are not available in Anserina and the taxonomy provided in the FNA Potentilla ms was unclear. I have to check against the new version.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-03 15:38Z]

VASCAN has been fixed, insofar as doable (I would prefer to place it in Anserina, but a few subsp. names are still missing there).

subsp. egedei is now a syn. of subsp. groenlandica
This explains the report of this taxon in Labr.
the name is not misapplied
