### ISSUE TITLE
Arabidopsis lyrata 

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#129]
[Originally posted on GoogleCode (id 2139) on 2014-02-28]

Salut

L'espèce est introduite au Québec.
Sabourin dans son guide des crucifères mentionnent que l'espèce n'est rapporté au Québec que le long des voies ferrées de Saint-Henri (Montréal) fide Brisson, 1960.

Comme indigénat, je trouve le tout plus que douteux quand on regarde le reste de la répartition (loin en Ontario).

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-04 16:32Z]

Svp, donner des références précises. Me mentionner simplement Sabourin ne me précise pas quel travail. J'imagine ses Crucifères du Québec.

Je vérifie car la Flore laurentienne (ajouts de Rouleau) semble indiquer un indigénat (par abstention de commentaire).

Corrigé.
