### ISSUE TITLE
status of Salix myrtillifolia in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1290]
[Originally posted on GoogleCode (id 1131) on 2012-02-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9130

<b>What data are incorrect or missing?</b>
Salix myrtillifolia is listed as excluded from Nfld.

<b>What data are you expecting instead?</b>
Salix myrtillifolia listed as present in Nfld.

We had this information in our 2000 checkist:
Classified as rare in Nfld., Salix myrtillifolia was known from only two locations on the Great Northern Peninsula; it was relocated in 1991 by Bouchard et al. on the Port au Choix Peninsula (Bouchard et al., 1992).  

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-19 21:13Z]

The FNA ms by Argus does not report this sp for QC and NF. I am not sure why, now that I think on it, because it does not make sense. Could be an error.

I will check with George.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-03 17:21Z]

Here is the statement by Argus in FNA:
"Specimens attributed to this species from the Gaspe Peninsula, Quebec, and the Northern Peninsula, Newfoundland, all have evidence of leaf glaucescence and are S. ballii. See 57. S. pseudomyrsinites and 58. S. ballii for more description."

Indeed, all the material at MT has been revised to ballii or other spp., and only specimens recorded form other herbaria are still ballii in the database. They may have been revised by Argus there.

The entry in VASCAN shows this ref.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-05-03 17:25Z]

Thanks for the clarification, Luc. Will adjust our NL records too.  - Sue.
