### ISSUE TITLE
status of Lycopodium hickeyi in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1291]
[Originally posted on GoogleCode (id 1132) on 2012-02-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6597

<b>What data are incorrect or missing?</b>
?presence of Lycopodium hickeyi in Nfld.

<b>What data are you expecting instead?</b>
In our checklist we had this information:
&quot;Though Lycopodium hickeyi is often reported from Nfld. and Labrador, NF vouchers (at MT and NFM) indicate that all specimens are L. dendroideum; which agrees with the distribution in Cody and Britton (1989), but contradicts that in FNA vol 2. (1993).  It is noted that NF specimens in more exposed locations often vary a bit in the direction of L. hickeyi, but are still distinctly L. dendroideum. NF reports of Lycopodium obscurum are referred to Lycopodium dendroideum also.&quot;

Have new specimens surfaced that show this is actually in Nfld.?
<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-20 13:26Z]

In the back end, I have it as excluded. I do not know why it is showing as native, unless I made the change recently (possible but unlikely). We will have to check the next time I compile data, in about a week.

Luc
