### ISSUE TITLE
incorrect capitalization of epithet in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1296]
[Originally posted on GoogleCode (id 1147) on 2012-02-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7592

<b>What data are incorrect or missing?</b>
Elymus Sitanion Schultes nom. illeg.

<b>What data are you expecting instead?</b>
Elymus sitanion (with lower case 's') Schultes nom. illeg.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-26 18:46Z]

This has been done already. I wonder whether you did not send it twice

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-02-26 23:56Z]

Sorry, Luc.  I didn't have these listed on my records as being sent.
