### ISSUE TITLE
authorities of species; incomplete or misplaced synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1303]
[Originally posted on GoogleCode (id 1154) on 2012-02-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7613

<b>What data are incorrect or missing?</b>
Elymus striatus Willdenow
Elymus arkansanus Scribner &amp; Ball

<b>What data are you expecting instead?</b>
Elymus striatus Willdenow var. villosus (Muhlenberg ex Willdenow) A.Gray; 
since Elymus striatus Willd. is a synonym of Elymus virginicus var. virginicus in Tropicos.
Elymus arkansanus Scribner &amp; C.R.Ball

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-26 20:51Z]

You are correct concerning E. striatus - this is in the CNWG (not TROPICOS per se)
But Elymus villosus has a homotypic syn E. striatus var. villosus indeed
