### ISSUE TITLE
Question about range

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1306]
[Originally posted on GoogleCode (id 1157) on 2012-02-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7625

<b>What data are incorrect or missing?</b>
Elymus ×yukonensis is shown to occur in BC, but not YK

<b>What data are you expecting instead?</b>
Was there ever a YK distribution also?  Why did Scribner &amp; Merrill call it E. ×yukonensis if it wasn't found in the Yukon? Cody doesn't include it in his Flora either.  I don't expect you to add YK, just curious as to why it was named for a place it doesn't occur.  

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-26 20:57Z]

There is no dot in FNA for Yukon and I have no other sources. The name could have been for the river, not the territory.
