### ISSUE TITLE
Sparganium glomeratum  - mention douteuse à éliminer?

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#131]
[Originally posted on GoogleCode (id 2141) on 2014-03-01]

Salut

FNA mentionne l'espèce pour le Québec
Idem avec le CDPNQ pour une mention dans les environs de Mingan.
N'a pas été aperçu depuis cette récolte.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-04 16:18Z]

Cette mention, qui a été reprise dans le mémoire de L.-P. Hébert, est erronée: il n'y a pas de spécimen confirmé de cette sp. au Québec.

Je l'ai conservé douteuse car personne ne semble vouloir confirmer ou infirmer cette mention.

À valider à MT.

Luc

**Comment by brouille** [comment]
Je l'ai finalement exclude pour manque de documentation
