### ISSUE TITLE
authorities of species, hybrid parents, and synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1322]
[Originally posted on GoogleCode (id 1174) on 2012-02-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8136

<b>What data are incorrect or missing?</b>
Fallopia ×bohemica (J. Chrtek &amp; A. Chrtkova) J.P. Bailey
parent: F. japonica (M. Houttuyn) L.-P. Ronse-Decraene var. japonica. 
parent: F. sachalinensis (F. Schmidt ex Maximowicz) L.-P. Ronse-Decraene. 
Syn: Polygonum ×bohemicum (J. Chrtek &amp; A. Chrtkova) P.F. Zika &amp; A.L. Jacobson
Syn: Reynoutria ×bohemica J. Chrtek &amp; A. Chrtkova

<b>What data are you expecting instead?</b>
Fallopia ×bohemica (Chrtek &amp; Chrtkova) J.P. Bailey
parent: F. japonica (Houttuyn) Ronse-Decraene var. japonica. 
parent: F. sachalinensis (F. Schmidt ex Maximowicz) Ronse-Decraene. 
Syn: Polygonum ×bohemicum (Chrtek &amp; Chrtkova) Zika &amp; Jacobson
Syn: Reynoutria ×bohemica Chrtek &amp; Chrtkova

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-26 21:24Z]

The parents are linked to the species entry, which is now corrected- it will be automatic
