### ISSUE TITLE
Puccinellia maritima

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#133]
[Originally posted on GoogleCode (id 2145) on 2014-03-06]

Salut

Pourquoi la mention douteuse pour cette espèce?

La carte de FNA montre un point en Gaspésie (Baie des Chaleurs) et il y aurait un vieux spécimen de Little Metis à Acadia.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-17 19:19Z]

Fred

ES tu si convaincu par le point en GAspésie? Ce pourrait-il que ce soit au NB?

Luc

**Comment by brouille** [comment]
ajouté QC fide FNA - introduite
