### ISSUE TITLE
authorities of species, basionym addition

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1339]
[Originally posted on GoogleCode (id 1191) on 2012-02-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7697

<b>What data are incorrect or missing?</b>
Glyceria elata (Nash ex Rydberg) M.E. Jones

<b>What data are you expecting instead?</b>
Glyceria elata (Nash) M.E. Jones
basionym: Panicularia elata Nash 

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-27 20:08Z]

added basionym and homotypic syns
