### ISSUE TITLE
authorities of species/var.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1340]
[Originally posted on GoogleCode (id 1192) on 2012-02-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7700
http://data.canadensys.net/vascan/taxon/7699

<b>What data are incorrect or missing?</b>
Glyceria grandis S. Watson ex A. Gray 
Glyceria grandis S. Watson ex A. Gray var. grandis

<b>What data are you expecting instead?</b>
Glyceria grandis S. Watson 
Glyceria grandis S. Watson var. grandis

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-27 20:13Z]

added homotypic syns
