### ISSUE TITLE
Botrychium boreale - espèce à retirer du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#135]
[Originally posted on GoogleCode (id 2149) on 2014-03-11]

Salut

Jacques Labrecque mentionne que Farrar a réidentifié le spécimen de Marcel Blondeau à Botrychium pinnatum.

Espèce absente au Québec et au CANADA.  Espèce présente seulement au Groenland selon J. Labrecque

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-17 19:09Z]

Je te ferai remarquer que c'est à la suggestion de J. Labrecque que je l'avais ajouté au QC. Maintenant je l'enlève en citant Labrecque à nouveau, j'imagine. Mauvaise dét.

Je dois le conserver comme exclus car il avait été dans VASCAN, sans pourtant être cité ds la lit.

Luc
