### ISSUE TITLE
Oxybasis glauca subsp. glauca

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#136]
[Originally posted on GoogleCode (id 2151) on 2014-03-13]

Salut

La ssp. glauca serait introduite selon FNA.  Dans le commentaire avant la clé des sous-espèces, l'auteur mentionne: However, several entities are well delimited geographically. The native North American taxon is recognized here as a separate variety.

Marie-Victorin mentionne qu'elle est naturalisée d'Europe. Idem avec Claude Lavoie.  Même VASCAN a plusieurs provinces entourant le Québec comme introduite, à l'exception des 3 maritimes.  D'ailleurs, elles devraient aussi être mentionnées comme introduites.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-17 19:05Z]

FNA ne précise pas quel taxon est introduit. Je ne vois pas le symbole I à la var. glaucum, par ex., ni le mot introduit dans le "distribution statement", malgré la phrase qui dit que la var. indigène est séparée.

Le problème est que les Maritimes sont considérées indigènes et cela aussi pourrait être erronée. Je dois vérifier toutes ces flores.

Luc
