### ISSUE TITLE
incorrect epithet in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1362]
[Originally posted on GoogleCode (id 1224) on 2012-03-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7779

<b>What data are incorrect or missing?</b>
Vilfa filiformis Thurber ex S. Watson

<b>What data are you expecting instead?</b>
Vilfa gracillima Thurber ex S. Watson

<b>If applicable, please provide an authoritative source.</b>
There is no V. filiformis in Tropicos, CNWG, or IPNI.  But Vilfa gracillima Thurb. ex S.Watson is the basionym of Sprobolus gracillima, which you've got listed as a syn. too.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-27 20:44Z]

When I entered the data, there was such a name. It was probably corrected since.
