### ISSUE TITLE
typo in epithet of synonym; abbreviation of authority in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1364]
[Originally posted on GoogleCode (id 1226) on 2012-03-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7785

<b>What data are incorrect or missing?</b>
Vilfa racemosa (Michaux) P. Beauvois
Polypogon racemosum [typo] ...

<b>What data are you expecting instead?</b>
Vilfa racemosa (Michaux) Palisot de Beauvois
Polypogon racemosus ...

<b>If applicable, please provide an authoritative source.</b>
Tropicos, CNWG, and IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-27 20:49Z]

check source

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-28 12:39Z]

sources added
