### ISSUE TITLE
authorities of synonym; typo in Hooker

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1365]
[Originally posted on GoogleCode (id 1227) on 2012-03-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7786

<b>What data are incorrect or missing?</b>
Muhlenbergia aspericaulis Nees ex Trinius
Sporobolus aspericaulis (Nees ex Trinius) Scribner
Vilfa depauperata Torrey ex hooker

<b>What data are you expecting instead?</b>
Muhlenbergia aspericaulis Nees ex Trinius, nom. inval. (pro syn.)
Sporobolus aspericaulis Scribner [since Nees ex Trin. in a nom. inval.]
Vilfa depauperata Torrey ex Hooker

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-28 12:43Z]

sources added
