### ISSUE TITLE
typo in genus of synonym; authority abbrev. in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1367]
[Originally posted on GoogleCode (id 1229) on 2012-03-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7788

<b>What data are incorrect or missing?</b>
Podosaemum soboliferum ...
Achnatherum soboliferum (Muhlenberg ex Willdenow) P. Beauvois

<b>What data are you expecting instead?</b>
Podosemum soboliferum ...

Also, for Achnatherum soboliferum  P. Beauvois
Achnatherum soboliferum (Muhlenberg ex Willdenow) Palisot de Beauvois, unless you've decided to switch to just P. Beauvois

<b>If applicable, please provide an authoritative source.</b>
Tropicos, CNWG; Podosemum is the accepted spelling, according to Tropicos.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-28 12:46Z]

source added
