### ISSUE TITLE
basionym is an illeg. homonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1368]
[Originally posted on GoogleCode (id 1230) on 2012-03-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7789

<b>What data are incorrect or missing?</b>
Agrostis sylvatica Torrey

<b>What data are you expecting instead?</b>
Agrostis sylvatica Torrey, nom. illeg. hom., non Hudson

<b>If applicable, please provide an authoritative source.</b>
Tropicos, CNWG
Since Torrey's names is in Agrostis, is it still available for use as the basionym of Muhlenbergia sylvatica?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-28 12:48Z]

Yes, it could be - depends on priority, etc.
