### ISSUE TITLE
Crataegus scabrida var. asperifolia (Sargent) Kruschke

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#137]
[Originally posted on GoogleCode (id 2152) on 2014-03-14]

Salut

variété à ajouter au Québec. 4 occurrences au Québec selon étiquette annotation de Phipps 2010.

Fred

**Comment by brouille** [comment]
Curieusement, il ne l'a pas incluse dans la répartition du taxon ds FNA9
