### ISSUE TITLE
common name mistake

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1373]
[Originally posted on GoogleCode (id 1235) on 2012-03-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7796

<b>What data are incorrect or missing?</b>
rough mountain rice - source: Canadian Forest Service, 2007

<b>What data are you expecting instead?</b>
roughleaf mountain rice is what we actually have in the PHZDb

<b>If applicable, please provide an authoritative source.</b>
PHZDb (Canadian Forest Service)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-28 12:59Z]

Marilyn
Could you please deal with this issue? Thanks
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 12:39Z]

Marilyn: any news on this?

Tx
L

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:00Z]

fixed, my mistake with reference previously used
