### ISSUE TITLE
authority of species; misplaced synonym, typo in authority of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1377]
[Originally posted on GoogleCode (id 1239) on 2012-03-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7814

<b>What data are incorrect or missing?</b>
a) Pascopyrum smithii (Rydberg) Á. Löve
b) Agropyron smithii var. molle (Scribner &amp; Smith) Jones
c) Elytrigia dasystachia (Hooker) Á. Löve &amp; D. Löve

<b>What data are you expecting instead?</b>
a) Pascopyrum smithii (Rydberg) Barkworth &amp; D.R.Dewey
b) Agropyron smithii var. molle (Scribner &amp; J.G. Smith) M.E.Jones
c) Delete Elytrigia dasystachia; this name is a synonym of Elymus lanceolatus subsp. lanceolatus

<b>If applicable, please provide an authoritative source.</b>
a) Tropicos, CNWG, IPNI. Áskell Löve's name Pascopyrum smithii (Taxon 29 (1):168) is invalid, since the genus was not validly published and lacked a basionym ref., Art. 33.3 ICBN. Barkworth and D.R.Dewey have the valid publication.  
b) Tropicos; other entries in your list
c) CNWG

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-28 13:15Z]

Elytrigia dasystachia moved to Elymus lanceolatus subsp. lanc.
sources added & syns
