### ISSUE TITLE
authorities of subspecies

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1385]
[Originally posted on GoogleCode (id 1248) on 2012-03-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7848

<b>What data are incorrect or missing?</b>
Poa arctica subsp. caespitans (Simmons ex Nannfeldt) Nannfeldt

<b>What data are you expecting instead?</b>
Poa arctica subsp. caespitans Simmons ex Nannfeldt  {1940)
Poa arctica var. caespitans (Simmons ex Nannfeldt) Nannfeldt {1945)

<b>If applicable, please provide an authoritative source.</b>
Tropicos, CNWG; IPNI just has Nannfeldt, but the 1940 publication date and details are the same as Simmons ex Nanfeldt 1940.  In 1945, Nannfeldt published the variety, which you could add.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-29 12:40Z]

added var as syn
