### ISSUE TITLE
authorities of specie & synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1387]
[Originally posted on GoogleCode (id 1250) on 2012-03-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7850

<b>What data are incorrect or missing?</b>
Poa arctica subsp. lanata (Scribner &amp; Merrill) R.J. Soreng
Poa malacantha var. lanata (Roshevitz) Tzvelev

<b>What data are you expecting instead?</b>
Poa arctica subsp. lanata (Scribner &amp; Merrill) Soreng
Delete: Poa malacantha var. lanata (Roshevitz) Tzvelev - could not find this combination

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI, IPNI authors
The 2nd name was not listed in either Tropicos or IPNI, also, the wrong basionym authority was listed for lanata, so I'm not sure what it should be.  But you don't list this var. of lanata: Poa arctica R.Br. var. lanata (Scribner &amp; Merrill) B.Boivin.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-29 12:44Z]

malacantha var. lanata: I will wait to suppress this name because it was in Grass Manual - not all names are in TRO and IPNI, unfortunately - verification is needed

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-03-29 14:38Z]

The Plant List includes this entry: Poa malacantha var. vivipara (Roshev.) Tzvelev, which has the same authorities as given in your entry for var. lanata. If there is a Poa malacantha var. lanata, the parenthetical author should be (Scribner & Merrill), not Roshev.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-21 19:00Z]

Gras Manual kept no syn. exc. malacantha (sp.)
Poa arctica subsp. lanata corrected
removed P. malacantha var. lanata - it does not seem to exist
