### ISSUE TITLE
authority abbreviation of species & subsp.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1388]
[Originally posted on GoogleCode (id 1251) on 2012-03-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7868
http://data.canadensys.net/vascan/taxon/7867

<b>What data are incorrect or missing?</b>
Poa glauca M. Vahl
Poa glauca M. Vahl subsp. glauca

<b>What data are you expecting instead?</b>
Poa glauca Vahl
Poa glauca Vahl subsp. glauca

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI, INPI Authors. 

M.Vahl is used for another Martin Vahl who was born 120 yrs.later.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-30 12:25Z]

added syns
