### ISSUE TITLE
authorities of species and subsp.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1389]
[Originally posted on GoogleCode (id 1252) on 2012-03-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7869

<b>What data are incorrect or missing?</b>
Poa glauca subsp. rupicola (Nash ex Rydberg) W.A. Weber
Poa rupicola Nash ex Rydberg

<b>What data are you expecting instead?</b>
Poa glauca subsp. rupicola (Nash) W.A. Weber
Poa rupicola Nash 

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-30 12:27Z]

added autonym var.
