### ISSUE TITLE
status of 2 synonyms - nom. inval.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1391]
[Originally posted on GoogleCode (id 1255) on 2012-03-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7889

<b>What data are incorrect or missing?</b>
Poa serotina Ehrhart 
Poa triflora Gilibert

<b>What data are you expecting instead?</b>
Poa serotina Ehrhart mon. inval. [nom. nud.]  {1791}
or Poa serotina Ehrhart ex Hoffman {1800)
Poa triflora Gilibert, nom. inval.

<b>If applicable, please provide an authoritative source.</b>

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-03-30 12:28Z]

Sources: Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-30 12:35Z]

Poa serotina Ehrhart ex Hoffman 1800 is valid so I changed it to that - same taxon
