### ISSUE TITLE
authorities of synonyms, placement of var. alaskana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1399]
[Originally posted on GoogleCode (id 1264) on 2012-03-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7929

<b>What data are incorrect or missing?</b>
a) Puccinellia paupercula (Holmberg) Fernald &amp; Weatherby p.p.
b) Puccinellia langeana (Berlin) T. Sørensen
c) Puccinellia paupercula var. alaskana (Scribner &amp; Merrill) Fernald

<b>What data are you expecting instead?</b>
a) Puccinellia paupercula (Holm) Fernald &amp; Weatherby; 
   and add Glyceria paupercula Holm.
b) Puccinellia langeana (Berlin) T.J. Sørensen
c) P. paupercula var. alaskana should be moved to synonymy under P. pumila.

<b>If applicable, please provide an authoritative source.</b>
a) Tropicos &amp; IPNI: The basionym author is Holm, not Holmberg. Consider adding the basionym of this name: Glyceria paupercula Holm. Also, CNWG has direct synonymy, rather than partial link to P. tenella subsp. langeana; is the p.p. still valid? 
b) Tropicos &amp; IPNI authors
c) FNA – included in P. pumila: &quot;Puccinellia alaskana Scribn. &amp; Merr., here included in P. pumila, was considered a subspecies of P. langeana (Berlin) T.J. Sørensen ex Hultén [= P. tenella] by T.J.Sørensen (1953), but more closely resembles P. pumila.&quot;  Also, P. alaskana is already listed in VASCAN as a synonym of P. pumila.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-20 12:59Z]

Authority corrected
Synonyms sorted according to CNWG

Note that in the FNA discussion of P. pumila, it is mentioned that P. alaskana could be a distinct sp. I have to verify whether Laurie published on this before her untimely death
