### ISSUE TITLE
Dichanthelium acuminatum subsp. implicatum - ajout pour le Québec

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#140]
[Originally posted on GoogleCode (id 2156) on 2014-03-18]

Salut

Au moins 50 occurrences dans l'herbier MT 
de Amos à Val-Cartier en passant par Nominingue,etc.

Identifié par DOre, Marie-Victorin,etc.....

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-24 18:23Z]

déjà inscrit comme native fide Dore & McNeill
