### ISSUE TITLE
authorities of synonyms, typo in var. of synonym 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1407]
[Originally posted on GoogleCode (id 1272) on 2012-03-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7955

<b>What data are incorrect or missing?</b>
a) Chrysopogon nutans var. avenaceum [&lt;typo] (Michaux) Trelease ex Branner &amp; Coville
b) Andropogon ciliatus Elliott
c) Poranthera ciliata (Elliott) Rafinesque ex B.D. Jackson

<b>What data are you expecting instead?</b>
a) Chrysopogon nutans var. avenaceus (Michaux) Trelease ex Branner &amp; Coville
b) Andropogon ciliatus Elliott (1816), nom. illeg. hom. [non Thunb. ex A.Murray (1784).
c) Poranthera ciliata (Elliott) Rafinesque ex B.D. Jackson, nom. inval., pro syn.

<b>If applicable, please provide an authoritative source.</b>
a) should be avenaceus – see Tropicos: as &quot;avenaceum&quot;, but the generic name is masculine, re: ICBN Art. 62.1(a).
There is also a question about the authors: 
IPNI has Trelease in Branner &amp; Coville, while MBG has Trelease ex Branner &amp; Coville.  Not sure which is correct; but look at Issue 1265; the same situation MAY apply, in which case it should be just Branner &amp; Coville.
b) see Tropicos
c) see IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-21 19:10Z]

a) corrected
b) corrected
c) corrected
