### ISSUE TITLE
authority of basionym and its combinations

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1409]
[Originally posted on GoogleCode (id 1274) on 2012-04-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7958

<b>What data are incorrect or missing?</b>
Sorghum bicolor subsp. ×drummondii (Nees ex Steudel) de Wet ex Davidse
Andropogon drummondii Nees ex Steudel
Sorghum bicolor var. drummondii (Nees ex Steudel) Mohlenbrock
Sorghum ×drummondii (Nees ex Steudel) Millspaugh &amp; Chase
Sorghum vulgare var. drummondii (Nees ex Steudel) Hackel ex Chiovenda

<b>What data are you expecting instead?</b>
Sorghum bicolor subsp. ×drummondii (Steudel) de Wet ex Davidse
Andropogon drummondii Steudel
Sorghum bicolor var. drummondii (Steudel) Mohlenbrock
Sorghum ×drummondii (Steudel) Millspaugh &amp; Chase
Sorghum vulgare var. drummondii (Steudel) Hackel ex Chiovenda

<b>If applicable, please provide an authoritative source.</b>
GRIN uses just Steudel as the basionym author; their comment: &quot;published as &quot;A. drummondii Nees (mpt. sub Sorghum)&quot;, a reference to Sorghum drummondii Nees, MS., and not an ascription of A. drummondii to Nees.&quot;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 12:52Z]

a) Steudel ok but IPNI has de Wet vs de Wet ex Davidse in TROPICOS - I am going with IPNI here, since it is also what FNA25 did and this was checked by Gandhi, I presume
b-e: OK
