### ISSUE TITLE
Pycnanthemum verticillatum - à retirer du Québec

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#141]
[Originally posted on GoogleCode (id 2158) on 2014-03-18]

Salut

Tous les spécimens mentionnés dans l'explorateur de VASCAN sont erronés.  Ils étaient tous dans la chemise de P. virginianum avec une étiquette d'annotation à P. virginianum.  

Stuart mentionne sur la chemise de P. verticillatum qu'il faudrait vérifier les spécimens à QFA, mais il mentionne que selon lui, tous les spécimens du Québec sont des P. virginianum.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-19 13:16Z]

est-ce que tu veux dire les 2 variétés? L'une était indiquée indigène, l'autre introduite (var. pilosum)
ou bien seulement la var. verticillatum?

Sois précis svp.
