### ISSUE TITLE
Pedicularis capitata - absent du Québec selon J. Labrecque

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#142]
[Originally posted on GoogleCode (id 2161) on 2014-03-22]

Salut

Le seul spécimen identifié à P. capitata est situé sur une île au Nunavut (pas au Québec).

Aucun spécimen à MT.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-24 18:17Z]

J'apprécierais une réf. car je dois exclure le point.

Dois-je citer la FNQL encore non publiée dans ce cas?

Luc
