### ISSUE TITLE
error in basionym of synonym, also nom. illeg. superfl.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1427]
[Originally posted on GoogleCode (id 1294) on 2012-04-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7934

<b>What data are incorrect or missing?</b>
Puccinellia airoides (Nuttall) S. Watson &amp; J.M. Coulter

<b>What data are you expecting instead?</b>
Puccinellia airoides S. Watson &amp; J.M. Coulter, nom. illeg. superfl.
This name replaced Poa airoides, an illeg. homonym,

<b>If applicable, please provide an authoritative source.</b>
Tropicos: http://www.tropicos.org/Name/25517945

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-04-10 13:59Z]

added nomenclatural syns
