### ISSUE TITLE
question about capitalization

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1429]
[Originally posted on GoogleCode (id 1296) on 2012-04-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8025
http://data.canadensys.net/vascan/taxon/8030

<b>What data are incorrect or missing?</b>
riz sauvage du sud
zizanie aquatique du sud
riz sauvage du nord
zizanie des marais du nord

<b>What data are you expecting instead?</b>
riz sauvage du Sud
zizanie aquatique du Sud
riz sauvage du Nord
zizanie des marais du Nord

<b>If applicable, please provide an authoritative source.</b>
Since French common names with Ouest et Est are capitalized, shouldn't those with Sud et Nord also be capitalized?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-04-09 19:04Z]

Marc

svp répondre à ceci et corriger au besoin

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-05-01 20:52Z]

Yes, we chose to capitalize those words in accepted names. However, these French names are only given as synonyms, and it seems advisable to stick to the exact spelling used in the publication given as a source.

No change is here warranted.
