### ISSUE TITLE
 Woodsia oregana var. lyallii (Hook.) B. Boivin

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#144]
[Originally posted on GoogleCode (id 2164) on 2014-03-23]

Salut

Synonyme à ajouter pour Woodsia scopulina.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-24 18:27Z]

Nous avions négligé les syn. de FNA ss sp. lors de l'entrée initiale
