### ISSUE TITLE
typos in authority of species and synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1442]
[Originally posted on GoogleCode (id 1311) on 2012-04-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8342

<b>What data are incorrect or missing?</b>
Stuckenia vaginata (Turczaninow) J. Holub
Coleogeton vaginata (Turczaninow) Les &amp; Haynes

<b>What data are you expecting instead?</b>
Stuckenia vaginata (Turczaninow) Holub
Coleogeton vaginata (Turczaninow) Les &amp; R.R.Haynes

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-04-09 19:22Z]

C. vaginatus corrected
