### ISSUE TITLE
authorities of species; spelling of synonym epithet

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1446]
[Originally posted on GoogleCode (id 1315) on 2012-04-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9342

<b>What data are incorrect or missing?</b>
a) Smilax ecirrhata S. Watson
b) Coprosmanthus herbaceous [&lt;typo?] var. ecirratus Engelmann ex Kunth

<b>What data are you expecting instead?</b>
a) Smilax ecirrhata (Engelm. ex Kunth) S. Watson
b) Coprosmanthus herbaceus var. ecirratus Engelmann ex Kunth

<b>If applicable, please provide an authoritative source.</b>
a) Tropicos have Smilax ecirrhata S.Watson, but IPNI has Smilax ecirrata (Engelm. ex Kunth) S.Watson, as ecirrhata.  They add these 
remarks: Remarks: Reference to the basionym lacking; Vienna Code Art. 33.3 applies. In ed. 7 (p. 295. 1908) and ed. 8 (p. 449. 1950), &quot;S. ecirrhata (Engelm.) S. Wats.&quot; was treated as a new combination.

b) FNA and IPNI spell the specific epithet as: herbaceus, but Tropicos uses herbaceous. I'm not sure which is correct, but I had &quot;herbaceus&quot; listed before.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-04-16 12:30Z]

all ecirrata or -tus corrected to IPNI spelling
herbaceus: herbaceous is English, not Latin
