### ISSUE TITLE
rank of synonym; authorities of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1448]
[Originally posted on GoogleCode (id 1317) on 2012-04-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9345

<b>What data are incorrect or missing?</b>
Nemexia herbacea var. melica A. Nelson
Nemexia tenuis Small
Smilax herbacea var. lasioneuron A. de Candolle

<b>What data are you expecting instead?</b>
Nemexia herbacea subsp. melica A. Nelson
Nemexia tenuis (Small) Small
Smilax herbacea var. lasioneuron (Hooker) A. de Candolle

<b>If applicable, please provide an authoritative source.</b>
FNA, Tropicos or IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-04-16 12:39Z]

Peter

Taxon 21372 Nemexia herbacea var. melica A. Nelson
Rang needs to be changed from var. to subsp.

Thanks
Luc

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-04-16 14:59Z]

Done. Taxon 21372 is now Nemexia herbacea subsp. melica
