### ISSUE TITLE
Eriocaulon rollandii

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#145]
[Originally posted on GoogleCode (id 2165) on 2014-03-24]

Copie d'un message entre Marcel Blondeau et Jacques Labrecque

Bonjour Marcel
 
J'espère que tu vas bien. Non je ne suis pas en chômage, c'est plutôt le contraire...
 
En effet, l'E. rollandii me semblait un synonyme de E. aquaticum. Le seul caractère qui le relie à parkeri est sa petite taille. Il y a d'ailleurs un commentaire qui va en ce sens dans le rapport de situation rédigé par Frédéric Coursol en 1999 (p. 8):
 
Dans la flore du Canada, Scoggan (1978) reconnaît l’Eriocaulon parkeri. Il inclut dans ce taxon un autre ériocaulon de petite taille, l’Eriocaulon rollandii, position rejetée par Moldenke (1979). Le traitement de Scoggan (1978), qui entraînera par la suite une certaine confusion chez les auteurs américains, se défend mal. En effet, l’Eriocaulon rollandii, qui fut décrit par Rousseau en 1957 à partir d'un spécimen de la région du Lac Mistassini, présente plus de similitude sur le plan morphologique avec l'Eriocaulon aquaticum (sub E. septangulare), de l'aveu même de l'auteur. C'est sans doute ce qui amène Lepage (1974) à le reléguer au rang de forme de l'Eriocaulon aquaticum (sub E. septangulare).

 
Donc, à mon avis tu as bien raison de mettre en doute l'info de Vascan. Je mets d'ailleurs Frédéric Coursol en copie pour qu'il aborde le sujet avec Luc.
 
Est-ce que le printemps est arrivé à Montréal? Ici c'est comme en janvier....
 
Bon printemps et au plaisir de se voir en personne bientôt!
 
Ton tout dévoué Jacques
 
Jacques Labrecque, botaniste 
Ministère du Développement durable, 
de l'Environnement, de la Faune et des Parcs 
Direction du patrimoine écologique et des parcs
Édifice Marie-Guyart, 4e étage boîte 21 
675, boul. René-Lévesque-Est 
Québec (Québec), G1R 5V7 
Tél: (418) 521-3907 poste 4789 
Courriel: jacques.labrecque@mddefp.gouv.qc.ca

 

Avis de confidentialité :
Le présent courriel peut contenir des renseignements confidentiels et ne s’adresse qu’au destinataire.  Si ce courriel vous est parvenu par mégarde, vous êtes priés de le supprimer et de m’aviser aussitôt.  Merci!

 
 
 
 
 
 
 
 
-----Message d'origine-----
De : Marcel Blondeau [mailto:marcel_blondeau@videotron.ca] 
Envoyé : 23 mars 2014 14:16
À : Labrecque, Jacques; Norman.Dignard@mrn.gouv.qc.ca
Objet : Eriocaulon rollandii

Bonjour Jacques

J'espère que tu vas bien et que tu n'es pas en chômage. Alors, je viens te déranger avec une colle.

Le site VASCAN englobe Eriocaulon rollandii Rousseau dans E. parkeri (cf. VASCAN)

Si le type d'E. rollandii (Rousseau J. 1957) est  basé sur la récolte de  J. Rousseau et E. Rouleau 1425, 1944 ?

Comment concilier le fait que Eriocaulon parkeri est une plante d'estuaire et que la récolte vient du lac Mistassini ?
Si c'est le cas, la fusion ne devrait-elle  se faire plutôt avec E. aquaticum (E. septangulare) ???

Peux-tu m'aider à trouver où est l'erreur?

Saluts amicaux

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-24 17:46Z]

LA seule raison pour laquelle le nom est où il est, est que WCSP (Plant List) le plaçait là. C'est évidemment une erreur de ma part d'avoir suivi cela. Je n'ai pas fait attention à la localité type.

Cependant, y a-t-il une réf. à citer ( Lepage 74 dont on ne me donne pas la réf.?)

Quand on propose un changement, svp fournir une référence à citer.
