### ISSUE TITLE
rank of synonym; authority abbreviation of 2nd synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1460]
[Originally posted on GoogleCode (id 1331) on 2012-05-07]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4503

<b>What data are incorrect or missing?</b>
Chenopodium pratericola subsp. dessicatum (A. Nelson) Aellen
Chenopodium pratericola var. oblongifolium (S. Watson) H.A. Wahl

<b>What data are you expecting instead?</b>
Chenopodium pratericola var. dessicatum (A. Nelson) Aellen
Chenopodium pratericola var. oblongifolium (S. Watson) Wahl

<b>If applicable, please provide an authoritative source.</b>
Tropicos;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-13 12:50Z]

Peter:

Could you please change the "rang" for the followingn name:
Chenopodium pratericola "subsp." dessicatum (A. Nelson) Aellen
http://data.canadensys.net/vascan/taxon/14712
to "var." dessicatum (same authorities)

Thanks
Luc
