### ISSUE TITLE
incorrect rank for synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1463]
[Originally posted on GoogleCode (id 1334) on 2012-05-07]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4516

<b>What data are incorrect or missing?</b>
Chenopodium macrospermum var. halophilum (Philippi) Aellen

<b>What data are you expecting instead?</b>
Chenopodium macrospermum subsp. halophilum (Philippi) Aellen
AND/OR
Chenopodium macrospermum var. halophilum (Philippi) Standley

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-13 12:57Z]

Peter
Please change the rang of the following:
http://data.canadensys.net/vascan/taxon/22230
Chenopodium macrospermum "var." halophilum (Philippi) Aellen
to "subsp." halophilum (same authorities)
Thanks
Luc

I added the var. with proper authorities (this is done so as not to change the number)
