### ISSUE TITLE
no English common name for Rhus copallinum and var.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1464]
[Originally posted on GoogleCode (id 1335) on 2012-05-08]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2519
http://data.canadensys.net/vascan/taxon/23680

<b>What data are incorrect or missing?</b>
no common English names given

<b>What data are you expecting instead?</b>
winged sumac, shining sumac

<b>If applicable, please provide an authoritative source.</b>
&lt;http://www.duke.edu/~cwcook/trees/rhco.html&gt; 
&lt;http://delawarewildflowers.org/plant.php?id=1677&gt; 
&lt;http://www.uwgb.edu/biodiversity/herbarium/shrubs/rhucop01.htm&gt; 
&lt;http://www.cas.vanderbilt.edu/bioimages/species/rhcol2.htm&gt; 
&lt;http://plants.usda.gov/java/profile?symbol=RHCO&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-13 12:58Z]

Marilyn

Please make the correction suggested.

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:14Z]

english vernaculars entered
