### ISSUE TITLE
authorties of synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1467]
[Originally posted on GoogleCode (id 1338) on 2012-05-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2616

<b>What data are incorrect or missing?</b>
a) Musineon divaricatum var. hookeri (Torrey &amp; A. Gray) Nuttall
b) Musineon hookeri Torrey &amp; A. Gray

<b>What data are you expecting instead?</b>
a) Musineon divaricatum var. hookeri Torrey &amp; A. Gray  [..as Musineum]
or 
Musineon divaricatum var. hookeri (Torrey &amp; A. Gray) Mathias; see below
b) Musineon hookeri (Torrey &amp; A. Gray) Nutt.

<b>If applicable, please provide an authoritative source.</b>
IPNI; Nuttall was the author of the species M. divaricatum, and of M. hookeri, but not M.d. var. hookeri.
IPNI records: Musineon divaricatum var. hookeri Torr. &amp; A.Gray, [originally published] as Musineum divaricatum, which would make Mathias's combination an isonym, unless IPNI's interpretation is not supported by the code.  You may need to check with someone who knows the code better.  However, Nuttall's combination, Musineon hookeri, was apparently origainally published as Musineum hookeri, according to MBG.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-27 12:19Z]

I interpret var. hookeri Mathias as a later homonym - there is no obvious reason why not. IPNI makes no judgement in this case on the status of the name, so one cannot deduce that it is accepted over the T. & G. name.
