### ISSUE TITLE
Eriophorum triste - douteux

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#147]
[Originally posted on GoogleCode (id 2170) on 2014-03-28]

Salut

Rien à QFA
Rien à MT
Pour la flore du Québec nordique, 4 spécimens au Nunavut sur l'ile Akpatok dans la baie d'Ungava.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-24 18:57Z]

exclu car non documenté au Québec (prés. au Nunavut)
