### ISSUE TITLE
confusion over placement of subsp. millefolium and subsp. pannonica

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1472]
[Originally posted on GoogleCode (id 1344) on 2012-05-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2768

<b>What data are incorrect or missing?</b>
Confusion over subspecies status:
Listed as synonyms under the species: Achillea millefolium are:
Achillea millefolium Linnaeus subsp. millefolium
Achillea millefolium subsp. pannonica (Scheele) Hayek
Achillea pannonica Scheele

So, Achillea lanulosa is no longer recognized at the species level?

yet listed as subspecies or varieties under A. millefolium are:
Subspecies Achillea millefolium subsp. lanulosa
Variety	Achillea millefolium subsp. lanulosa var. lanulosa
Variety	Achillea millefolium subsp. lanulosa var. megacephala

<b>What data are you expecting instead?</b>
Not sure; why isn't Achillea millefolium subsp. millefolium listed as a subspecies rather than a synonym of the species?  Is subsp. pannonica a synonym or subsp. of Achillea millefolium?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-16 12:41Z]

Sue

We have already discussed this: lanulosa needs to be fixed, I have found combinations for the Sask var., but there are still things that need validation

I do not want to keep all this under the introduced millefolium

This is a second report.

Luc
