### ISSUE TITLE
spelling of synonym name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1474]
[Originally posted on GoogleCode (id 1346) on 2012-05-15]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2846

<b>What data are incorrect or missing?</b>
Dendranthema arcticum subsp. polare (Hultén) Heywood

<b>What data are you expecting instead?</b>
Dendranthema arctica subsp. polaris (Hultén) Heywood

<b>If applicable, please provide an authoritative source.</b>
IPNI uses this spelling; Tropicos uses arcticum and polare.  See previous issue - 1345.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-07-02 12:38Z]

PanArctic Flora, GRIN, Plant List all use arcticum subsp. polare, as do FNA and TROPICOS
The FNA entry was verified by K. Gandhi, but apparently there was no conciliation with IPNI.

Request to Gandhi.
