### ISSUE TITLE
Corispermum pallasii - éphémère

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#148]
[Originally posted on GoogleCode (id 2171) on 2014-03-28]

Salut

Aucun spécimen à MT, seulement 2 à QFA (ville de Québec).
Pas d'autres infos sur les spécimens de Québec, mais probablement une introduction éphémère dans le port.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-24 18:56Z]

exclue - éphémère (et pas de récolte récente)

Luc
