### ISSUE TITLE
typos in spelling of authorities in synonym; nom. illeg.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1485]
[Originally posted on GoogleCode (id 1358) on 2012-05-17]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2913

<b>What data are incorrect or missing?</b>
Artemisia tridentata subsp. xericensis Winward ex R. Rosentreter &amp; R. Kelsey 
Artemisia angustifolia (A. Gray) Rydberg

<b>What data are you expecting instead?</b>
Artemisia tridentata subsp. xericensis Winward ex Rosentreter &amp; R.G.Kelsey 
Artemisia angustifolia (A. Gray) Rydberg, nom. illeg.  
[hom., non S.F.Gray]

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-18 19:23Z]

TROPICOS has R. Rosentreter & R.G. Kelsey

Where did you take (A.Gray) Rydb. nom. illeg.? Both IPNI and TROPICOS have Gray
FNA appears incorrect

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-05-20 18:27Z]

a) IPNI Authors: there is only one Rosentreter, so no initials are necessary  
   Rosentr. - Roger Rosentreter fl. 1991

b) From the French Index Synonymique: 

Artemisia angustifolia S.F. Gray [1821, Nat. Arr. Brit. Pl., 2 : 450] º A. abrotanum 
http://www2.dijon.inra.fr/flore-france/arh-arz.htm

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-22 13:10Z]

Concerning A. angustifolia: I was wondering where the authorities (A.Gray) Rydb. came from, since they are reported neither in IPNI nor TROPICOS, nor the Index synonymique, for that matter.

My point: the name does not appear to exist with these authorities. I am removing it. I cannot determine where the FNA author took the (illeg.) name at all!

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-05-22 13:52Z]

Yes, you're right to delete it.  I got the name Artemisia angustifolia (A.Gray) Rydb. from FNA, but cannot find it anywhere else.  Looking again, I see the basionym of this name, Artemisia tridentata var. angustifolia A.Gray, occurs in IPNI and Tropicos, but I think the FNA author made a mistake assuming the name Artemisia angusta Rydb. was based on A.Gray's A. tridentata var. angustifolia. According to Tropicos, Artemisia angusta was described by Rydberg to REPLACE A. tridentata var. angustifolia A.Gray.

See the 2nd IPNI entry under Artemisia angusta Rydb.; it gives the Original data as A. tridentata, var. angustifolia, A.Gray, which is often how they list basionyms, but so this could be misinterpreted.
