### ISSUE TITLE
Astragalus robbinsii var. minor - à retirer des espèces du Québec selon P. Morisset

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#149]
[Originally posted on GoogleCode (id 2172) on 2014-03-29]

Re-bonjour Frédéric,

J'ai vérifié mes notes et je ne crois pas que la variété minor soit présente au Québec. 

Si sa présence au Québec (selon la carte actuelle de Vascan) s'appuie sur des récoltes ou des observations, récentes ou non, je ne les ai pas vues ou lues.

Au plaisir,

Pierre

———————————————————
Pierre Morisset
304, avenue De Gaspé Ouest
Saint-Jean-Port-Joli (Québec) G0R 3G0
Tél.: 418·598·6972

**Comment by brouille** [comment]
taxon retiré du Québec - il n'y avait aucune source
