### ISSUE TITLE
authority abbreviation of 2 subspecies and 1 synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1491]
[Originally posted on GoogleCode (id 1364) on 2012-05-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2983
http://data.canadensys.net/vascan/taxon/2985

<b>What data are incorrect or missing?</b>
Chrysothamnus viscidiflorus subsp. lanceolatus (Nuttall) H.M. Hall &amp; F.E. Clements
Chrysothamnus viscidiflorus subsp. elegans (Greene) H.M. Hall &amp; F.E. Clements
--
Chrysothamnus viscidiflorus subsp. puberulus (D.C. Eaton) H.M. Hall &amp; F.E. Clements

<b>What data are you expecting instead?</b>
Chrysothamnus viscidiflorus subsp. lanceolatus (Nuttall) H.M. Hall &amp; Clements
Chrysothamnus viscidiflorus subsp. elegans (Greene) H.M. Hall &amp;  Clements
--
Chrysothamnus viscidiflorus subsp. puberulus (D.C. Eaton) H.M. Hall &amp; Clements

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-23 12:24Z]

added syns to taxa
