### ISSUE TITLE
incorrect authorities for variety and synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1492]
[Originally posted on GoogleCode (id 1365) on 2012-05-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3050

<b>What data are incorrect or missing?</b>
Dieteria canescens var. incana (Pursh) Nuttall
Machaeranthera canescens var. incana (Lindley) D.R. Morgan &amp; R.L. Hartman

<b>What data are you expecting instead?</b>
Dieteria canescens(Pursh) Nuttall var. incana (Lindl.) D.R.Morgan &amp; R.L.Hartman
Machaeranthera canescens var. incana (Lindley) A.Gray

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-23 12:31Z]

syns added
