### ISSUE TITLE
repetition of var.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1494]
[Originally posted on GoogleCode (id 1367) on 2012-05-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3069

<b>What data are incorrect or missing?</b>
Ericameria nauseosa (Pallas ex Pursh) G.L. Nesom &amp; G.I. Baird subsp. nauseosa var. nauseosa

<b>What data are you expecting instead?</b>
Ericameria nauseosa (Pallas ex Pursh) G.L. Nesom &amp; G.I. Baird subsp. nauseosa, since this taxon is var. nauseosa, is there any reason to repeat the var. here?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-23 12:41Z]

removed the var.; added the autonymic subsp.
added syns
