### ISSUE TITLE
authority abbeviation of species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1495]
[Originally posted on GoogleCode (id 1371) on 2012-06-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3668

<b>What data are incorrect or missing?</b>
Berberis ×ottawaensis C. Schneider

<b>What data are you expecting instead?</b>
Berberis ×ottawaensis C.K. Schneider

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI authors: there is another C.Schneider.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-21 12:24Z]

corrected also ottawaensis to ottawensis
