### ISSUE TITLE
status of Tripleurospermum maritimum subspecies in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1497]
[Originally posted on GoogleCode (id 1373) on 2012-06-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3642

<b>What data are incorrect or missing?</b>
Tripleurospermum maritimum subsp. phaeocephalum not present in NL

<b>What data are you expecting instead?</b>
?present in Nfld.

<b>If applicable, please provide an authoritative source.</b>
Our NL checklist. We had this subsp. as present in w/ne and e Nfld., but had subsp. maritimum in Appendix I as erroneously listed from NL. 
If this is based on a recent examination of the specimens, could you provide me with a reference?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-21 12:40Z]

I just checked FNA and it seems wrong to me. I do not know how I got the distribution wrong for Nfld. I am pretty sure that it is phaeocephalum that is present and native, and maritimum erroneous, as is the case in most e Canada (where it is introduced). Eventually, I will check specimens again...

I am correcting.

Luc
