### ISSUE TITLE
authority of synonym, suggested synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1498]
[Originally posted on GoogleCode (id 1374) on 2012-06-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2671

<b>What data are incorrect or missing?</b>
Ilex verticillata var. fastigiata (Bicknell) Fernald

<b>What data are you expecting instead?</b>
Ilex verticillata var. fastigiata (E.P.Bicknell) Fernald
and you might want to add the basionym of this name: Ilex fastigiata E.P.Bicknell
and the basionym of the entry: Prinos verticillatus L.

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-21 12:45Z]

basio added
