### ISSUE TITLE
spelling of var.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1499]
[Originally posted on GoogleCode (id 1375) on 2012-06-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3094

<b>What data are incorrect or missing?</b>
Erigeron pulchellus var. unalaschkensis de Candolle

<b>What data are you expecting instead?</b>
?Erigeron pulchellus var. unalaschkense de Candolle

<b>If applicable, please provide an authoritative source.</b>
Tropicos spells the var as unalaschkense, but IPNI uses unalaschkensis.  I'm not sure which is correct.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-21 12:47Z]

unalaschkensis because it is masculine
