### ISSUE TITLE
typo in authority abbreviation of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1508]
[Originally posted on GoogleCode (id 1387) on 2012-06-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2849

<b>What data are incorrect or missing?</b>
Arctium lappa var. tomentosum (P. Miller) A. Gray

<b>What data are you expecting instead?</b>
Arctium lappa var. tomentosum (Miller) A. Gray

<b>If applicable, please provide an authoritative source.</b>
IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-21 13:19Z]

in fact, IPNI has (Lamarck) A. Gray - the basionym being Lappa tomentosa Lam.
