### ISSUE TITLE
Euphorbia nutans - indigénat douteux

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#151]
[Originally posted on GoogleCode (id 2174) on 2014-03-29]

Salut

Seulement 3 mentions à MT (échangeur Turcot, Saint-Lambert et Saint-Jérôme).  Les mentions sont toujours associées aux voies ferrées.  De mémoire, 2 récoltes ont été faites par Stuart.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-24 18:54Z]

Statut: introduit
