### ISSUE TITLE
suggested synonym for Hieracium robinsonii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1510]
[Originally posted on GoogleCode (id 1390) on 2012-06-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3233

<b>What data are incorrect or missing?</b>
missing synonym: Hieracium ungavense Lepage

<b>What data are you expecting instead?</b>
Suggest you add Hieracum ungavense Lepage.

<b>If applicable, please provide an authoritative source.</b>
USDA and ITIS list this as a syn. of Hieracium robinsonii.  IPNI lists H. ungavense, but does not give any synonymy. 
Tropicos does not include it, and they have a mistake in the authors of H. robinsonii (Zahl, instead of Zahn) Fernald.  Zahl was a phycologist according to IPNI authors.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 12:06Z]

The type needs to be examined before synonymizing ungavense and robinsonii. I am not fully convinced.
