### ISSUE TITLE
status of H. robinsonii in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1512]
[Originally posted on GoogleCode (id 1392) on 2012-06-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3233

<b>What data are incorrect or missing?</b>
Hieracium robinsonii extirpated in Nfld.

<b>What data are you expecting instead?</b>
I'd cetainly want to check John Maunder's specimens, but he posts 2 sets of recent pix on his digital flora tentatively ID'ed as H. robinsonii.

<b>If applicable, please provide an authoritative source.</b>
http://www.digitalnaturalhistory.com/genus_hieracium_index.htm#hieraciumsabaudum

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 13:05Z]

He needs to confirm his determination. Nonetheless I will change the status until someone declares it extirpated or not definitely.

Luc
