### ISSUE TITLE
status of Lactuca biennis in Labrador

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1513]
[Originally posted on GoogleCode (id 1393) on 2012-06-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3262

<b>What data are incorrect or missing?</b>
status of Lactuca biennis in LB

<b>What data are you expecting instead?</b>
Scoggan lists this from central Lab., and Day shows 1 dot near GB, but are these reports verfied?  Have there been any herbarium specimens or recent collections from LB?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 13:10Z]

From the Rouleau compilation (now databased):
Wetmore 103076 Kenemich River 1921 (CAN)
Gillett & Findley 5769 Goose Bay 1950 (DAO)

I know of no later report. Given the latest date, the species should be excluded. I am doing so.

Luc
