### ISSUE TITLE
Status of Taraxacum laurentianum in Labrador

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1516]
[Originally posted on GoogleCode (id 1396) on 2012-06-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3614

<b>What data are incorrect or missing?</b>
Taraxacum laurentianum not listed for Labrador

<b>What data are you expecting instead?</b>
present in Labrador

<b>If applicable, please provide an authoritative source.</b>
I don't have the first collection data yet, but I imagine it is from Claudia's year in L'Anse-Amour.  John Maunder shows 4 sets of pix from L'Anse-Amour from 2002 and 2003.  I'll check with Claudia for details.
http://www.digitalnaturalhistory.com/genus_taraxacum_index.htm#taraxacumcflaurentianum

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 13:15Z]

Photos are not sufficient to identify this species, I must see a specimen. People may confuse it with ceratophorum.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-06-22 19:53Z]

Claudia is in the field, but can check her records for us soon.  If she has a specimen, I'll ask her to send it to Stu.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 18:52Z]

I added it as uncertain. It does need confirmation. But at least it is there. If there is a specimen, I would like to see it.

Luc
