### ISSUE TITLE
synonym a nom. illeg. hom.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1517]
[Originally posted on GoogleCode (id 1397) on 2012-06-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3781

<b>What data are incorrect or missing?</b>
Lappula myosotis Moench

<b>What data are you expecting instead?</b>
Lappula myosotis Moench, nom. illeg. hom. [1794, non Wolf 1777]

<b>If applicable, please provide an authoritative source.</b>
Tropicos has V.Wolf, but there is no V.Wolf; IPNI has Wolf, and if you track the publication (Gen. Pl. 1777), it's Nathaneal M. von Wolf, whose IPNI author's abbreviation is just Wolf.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 13:18Z]

I need to verify with people, just in case something is fishy. TRO seems to accept the Moench name despite the earlier Wolf name

**Comment by brouille** [comment]
According to POWO, the Wolf epithet was not intended to be an epithet and therefore it has not priority and the Moench name is not illegitimate

**Comment by sjmeades** [comment]
Thanks for these,  Luc.

 

I had one question a while back that you may not have noticed.  Cuscuta gronovii is listed as native in Nfld. in VASCAN, but there is only one record that I know of, and that record is recent (2006+: see John Maunder’s photos of C. gronovii from Gambo saltmarsh.  https://www.digitalnaturalhistory.com/flora_convolvulaceae_index.htm#cuscutagronovii

 

Are there other records of this species from Nfld.?  If not, why is this considered native?  It could easily have been introduced by birds.  Given it’s limited range, it seems unlikely to me that it’s native.

 

There’s an article on Cuscuta species in the Can. J. of Plant Science that includes Cuscuta gronovii:

https://core.ac.uk/download/pdf/143689369.pdf

[Costea M, Tardif FJ. The biology of Canadian weeds. 133. Cuscuta campestris Yunck., C. gronovii Willd. ex Schult., C. umbrosa Beyr. ex Hook., C. epithymum (L.) L. and C. epilinum Weihe. Can J Pl Sci. 2006 86: 293–316]

 

There’s a distribution page on page 300 for C. gronovii and there are no distribution dots in Nfld. for this species.

 

There are 2 articles referenced in Olszewski et al (2020) article on Cuscuta seeds that discuss long-distance dispersal via bird endozoochory:

 

Costea M, Stefanović S, Garcı´a MA, De La Cruz S, Casazza ML, Green AJ. Waterfowl endozoochory: An overlooked long-distance dispersal mode for Cuscuta (dodder). Am J Bot. 2016; 103: 957–962. https://doi.org/10.3732/ajb.1500507 PMID: 27208362 

 

Costea M, El Miari H, Laczko´ L, Fekete R, Molna´r AV, Lovas-Kiss A´, et al. The effect of gut passage by waterbirds on the seed coat and pericarp of diaspores lacking “external flesh”: Evidence for widespread adaptation to endozoochory in angiosperms. PLoS One. 2019; 14(12)

 

As there is only 1 record that I know of, and VASCAN classified it as native, it is in our list of candidate species for protection in the SSAC committee, but I think it should be listed as introduced in our NL checklist, which would remove it from SSAC’s list of candidate species for protection.  Do you have records that show it could be native?  

 

Thanks, Sue.
