### ISSUE TITLE
Koeleria macrantha - 1 seul point au Québec et dans FNA pour le Québec

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#152]
[Originally posted on GoogleCode (id 2175) on 2014-03-29]

Salut

Koeleria macrantha - 1 seul point au Québec et dans FNA pour le Québec.
Saint-Jérôme au lac Saint-Jean......  pas réputé pour être un haut lieu de diversité.....
Lavoie mentionne 1877 dans son document et il considère cette graminée comme introduite.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-24 18:53Z]

Koeleria macrantha se trouve seulement ds le SW (et W) de Ont.
SElon ces données et la donnée plus haut, je l'exclue du Québec (ancien rapport, non localisée depuis)

Luc
