### ISSUE TITLE
error in spelling of var.; authority of var.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1522]
[Originally posted on GoogleCode (id 1435) on 2012-10-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4193

<b>What data are incorrect or missing?</b>
Celtis occidentalis var. goergiana (Small) Ahles

<b>What data are you expecting instead?</b>
Celtis occidentalis var. georgiana (Small) H.E.Ahles

<b>If applicable, please provide an authoritative source.</b>
IPNI, MBG

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-17 16:03Z]

The original data in FNA is also erroneous in this.
Added missing refs. to syns.
Luc
