### ISSUE TITLE
spelling of common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1524]
[Originally posted on GoogleCode (id 1437) on 2012-10-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4179

<b>What data are incorrect or missing?</b>
few-flowered heterodon

<b>What data are you expecting instead?</b>
few-flowered heterocodon

<b>If applicable, please provide an authoritative source.</b>
See  http://calphotos.berkeley.edu/ 
http://calphotos.berkeley.edu/cgi/img_query?query_src=photos_index&amp;where-lifeform=Plant--annual%2Fperennial+%28149186%29&amp;rel-taxon=begins+with&amp;where-taxon=Heterocodon&amp;rel-namesoup=matchphrase&amp;where-namesoup=&amp;rel-location=matchphrase&amp;where-location=&amp;rel-county=eq&amp;where-county=any&amp;rel-state=eq&amp;where-state=any&amp;rel-country=eq&amp;where-country=any&amp;where-collectn=any&amp;rel-photographer=contains&amp;where-photographer=&amp;rel-kwid=equals&amp;where-kwid=&amp;max_rows=24

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-17 19:22Z]

Sue

No need to provide sources when it is typos like here. The other names were OK, which is proof enough

L
