### ISSUE TITLE
validity of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1527]
[Originally posted on GoogleCode (id 1440) on 2012-10-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

<b>What data are incorrect or missing?</b>
Diervilla canadensis Bartram

<b>What data are you expecting instead?</b>
possibly delete, as I can't find a valid publication for this.
It was originally listed as Diarvilla lonicera in Bartram's 1785 list, but does not seem to have a description, only the name.  See links below.  Willdenow's 1806 name looks like the earliest legitimately published name, but you may have a different reference.

<b>If applicable, please provide an authoritative source.</b>
Brooklyn Bot. Garden (Steven Glenn)
http://nymf.bbg.org/profile_species_tech.asp?id=307

See original Bartram list: 
http://gwpapers.virginia.edu/documents/bartram/index.html

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-17 20:07Z]

Bartram name removed
