### ISSUE TITLE
Hylotelephium spectabile

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#153]
[Originally posted on GoogleCode (id 2186) on 2014-05-04]

Bonjour Luc

Ajout: Hylotelephium spectabile pour le Québec

On voit fréquemment l'orpin d'automne qui persiste près des lieux d'habitations anciens.  On m'a encore envoyé une photo aujourd'hui et les personnes me mentionnent que cela ne peut pas être Hylotelephium spectabile car il n'est pas dans la liste de VASCAN.

Je sais, il n'y a pas de spécimen d'herbier, mais la plante subsiste comme Scilla siberica.

Frédéric

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-16 14:04Z]

Frédéric

C,est un ajout complet à VASCAN. Il serait bon d'avoir une source. Ajouter sans source est un peu imprudent, même si je le fais, présentement comme éphémère car je ne sais rien de sa persistence.

Il serait bon d'obtenir des spécimens et de déterminer dans quelle mesure la persistence après culture subsiste à long terme.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-16 14:07Z]

Marc et Marilyn:

Fred Coursol a ajouté Hylotelephium spectabile à la liste des plantes du Québec (voir ci-haut).

La plante n'est pas ds FNA ms est citée dans PLANTS.

Il faut ajouter les vernaculaires.

In USDA Plants, English vernacular is "showy stonecrop"

Merci
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-05-20 15:30Z]

English vernaculars added

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-06-04 12:09Z]

Frédéric,

Je ne trouve aucun nom français pour cette plante dans les sources que je consulte habituellement, mais tu l'appelles « orpin d'automne » dans ton message, et je constate que ce nom est répandu sur internet, principalement dans des sites commerciaux. Il conviendrait tout à fait pour VasCan, mais aurais-tu une source en particulier à me proposer pour ce nom?
Merci,
Marc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-06-25 20:27Z]

En attendant la réponse de Frédéric, j'ai utilisé le nom « orpin d'automne » en citant Fred lui-même comme source.
