### ISSUE TITLE
authorities and names of synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1535]
[Originally posted on GoogleCode (id 1448) on 2012-10-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9456

<b>What data are incorrect or missing?</b>
Fedia olitoria Vahl
Valeriana olitoria Linnaeus

<b>What data are you expecting instead?</b>
Fedia olitoria (L.) Gaertner (1790) non (L.) Vahl (1805)
Valeriana locusta L. var. olitoria Linnaeus
or Valeriana olitoria (L.) Willdenow {1787_

<b>If applicable, please provide an authoritative source.</b>
the French Index Synonymique lists Gaertner (1790) as the author of Fedia olitoria; Tropicos has Vahl in 1805, with the basionym author:(L.).
Tropicos and the Index Synonymique list Valeriana locusta var. olitoria L. (1753), while IPNI lists Willdenow as the author of Valeriana olitoria.

**Comment by brouille** [comment]
corrections made
LB
