### ISSUE TITLE
Nénufar 

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#154]
[Originally posted on GoogleCode (id 2187) on 2014-05-05]

Bonjour

http://www.gqmnf.org/NouvelleOrthographe_FaussesRumeurs.html

Voir la section sur le nénufar.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-05-06 17:01Z]

Même si l'orthographe « nénuphar » demeure correcte en soi, il faut penser aux jeunes. Je crois donc que les arguments de l'OLFQ sont convaincants et qu'il serait approprié d'utiliser « nénufar » comme orthographe des noms acceptés et de retenir comme synonymes les noms comportant l'orthographe « nénuphar » en vogue au 20e siècle. Cependant, il faudra faire une vérification des sources pour ne pas attribuer la graphie « nénufar » à Marie-Victorin. Je vais ressortir avec plaisir mes flores de Provancher et de Moyen! C'est drôle de se tourner vers le passé pour aménager l'avenir.

Merci Frédéric.

À suivre.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-05-07 13:15Z]

Suite...

Provancher (1862) et Moyen (1885) utilisaient déjà « nénuphar ». J'ai fait d'autres vérifications à l'aide de Google, et il semble bien que le nom « nénuphar » était le plus répandu, pratiquement le seul utilisé, pour toute la période 1814-2014. Je pense que le Dictionnaire de l'Académie n'a fait que reconnaître cet usage en 1936, et non l'introduire comme semble indiquer les défenseurs de la réforme orthographique. Il y a des tas d'exemples de mots qui s'écrivent sans égard à leur étymologie, ou selon une étymologie fictive. Dans le contexte de VasCan, je pense qu'il faut respecter l'usage actuel et écrire « nénuphar ». D'ailleurs, on trouve l'orthographe « nénufar » presque uniquement dans des textes portant sur... la réforme de l'orthographe. Même Fleurbec, pourtant à l'affut de toute nouveauté surprenante, s'en tient à l'orthographe qu'il faut maintenant qualifier de classique. Peut-être dans dix ou vingt ans pourrons-nous constater que l'usage a changé. Je suis en faveur de la réforme de l'orthographe de 1990, mais il faut admettre que 24 ans plus tard elle n'a pas encore su s'imposer, surtout en France. J'ai tout de même introduit dans VasCan des doublons en « nénufar », à titre de synonymes, pour tous les noms acceptés.

Merci encore. N'hésite jamais à me faire part de tes préoccupations ou suggestions.

Marc
