### ISSUE TITLE
incorrect authorities for synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1540]
[Originally posted on GoogleCode (id 1455) on 2012-10-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4254

<b>What data are incorrect or missing?</b>
Cerastium alpinum subsp. squalidum (Raymond) Hultén
Cerastium squalidum Raymond

<b>What data are you expecting instead?</b>
Cerastium alpinum subsp. squalidum (Ramond) Hultén
Cerastium squalidum Ramond  {1825}

<b>If applicable, please provide an authoritative source.</b>
See IPNI; FNA and Tropicos are incorrect here. Raymond was not born when this species was described.
IPNI authors:
Ramond 1753-1827
Raymond 1915-1972

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-19 18:41Z]

This is amusing. The error came from FNA, and TROPICOS was incorrect indeed. IPNI did not have the subsp. but had var. and sp.

Added var. to syn.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 13:39Z]

IPNI has now added the subsp. after our intervention, with the authorities suggested above.
