### ISSUE TITLE
two synonyms are later homonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1544]
[Originally posted on GoogleCode (id 1460) on 2012-10-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4273

<b>What data are incorrect or missing?</b>
Cerastium beeringianum Schischkin
Cerastium serpyllifolium Bieberstein ex Seringe

<b>What data are you expecting instead?</b>
Cerastium beeringianum Schischkin, nom. illeg. hom., non Cham. &amp; Schltdl.
Cerastium serpyllifolium Bieberstein ex Seringe, nom. illeg. hom., non Willdenow

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 13:45Z]

The Schiskin name in not in TRO or IPNI - needs checking
neither databases identify the Bieb. ex Ser. name as illeg., but it obviously is from the dates

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-07-25 15:35Z]

I am removing C. beeringianum Schischkin - I cannot find it and it is suspicious given other synonyms like Cerastium gorodkovianum Schischkin
