### ISSUE TITLE
typo in writing subsp. synonym 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1545]
[Originally posted on GoogleCode (id 1461) on 2012-10-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4272

<b>What data are incorrect or missing?</b>
Cerastium pumilum subsp. glandulosum (Fries) Jalas

<b>What data are you expecting instead?</b>
Cerastium pumilum subsp. glutinosum(Fries) Jalas

<b>If applicable, please provide an authoritative source.</b>
You've got the right basionym (Cerastium glutinosum Fries), I think this was just a typo.  There is no subsp. glandulosum in C. pumilum.
See Tropicos or IPNI.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 13:47Z]

typo indeed - FNA is also correct
