### ISSUE TITLE
spelling of synonym; missing basionym author in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1548]
[Originally posted on GoogleCode (id 1464) on 2012-10-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4259

<b>What data are incorrect or missing?</b>
Cerastium buffumae A. Nelson
Cerastium alpinum var. beeringianum Regel

<b>What data are you expecting instead?</b>
? Cerastium buffumiae A. Nelson
Cerastium alpinum var. beeringianum (Chamisso &amp; Schlechtendal) Regel

<b>If applicable, please provide an authoritative source.</b>
FNA and Tropcios spell it buffumiae, while IPNI has buffumae.  Can't tell which is correct.  I don't have a copy of Nelson's publication.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 13:58Z]

buffumiae vs buffumae : will need to check with IPNI and TRO; FNA may or may not need correction
var. beeringianum: FNA is incorrect - corrected in VASCAN

**Comment by brouille** [comment]
buffumiae is correct and in VASCAN now
