### ISSUE TITLE
Anaphalis margaritacea var. margaritacea

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#155]
[Originally posted on GoogleCode (id 2189) on 2014-05-14]

Salut

Si la variété &quot;var. yedoensis (Franch. &amp; Sav.) Ohwi&quot; est accepté par PlantList (TICA) alors on doit ajouter var. margaritacea à notre taxon.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-16 13:57Z]

la taxonomie de Anaphalis est en flux. Certains ne reconnaissent aucune var., d'autres plusieurs

Je n'ai pas vu d'étude concluante, donc je m'abstiendrai pour l'instant

Luc
