### ISSUE TITLE
incorrect rank for synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1551]
[Originally posted on GoogleCode (id 1467) on 2012-10-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4317

<b>What data are incorrect or missing?</b>
Arenaria rossii var. columbiana (Raup) Maguire

<b>What data are you expecting instead?</b>
Arenaria rossii subsp. columbiana (Raup) Maguire

<b>If applicable, please provide an authoritative source.</b>
Tropicos; you had two entries with Arenaria rossii var columbiana, one with Raup, which is correct, and this one, which should be subsp.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 17:22Z]

technical problem with changing rank - it will have to be done later

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-10 17:54Z]

Christian:
Pourrais tu svp modifier le statut du taxon 
22413  Arenaria rossii var. columbiana (Raup) Maguire

de var. à subsp. 

svp
Merci
Luc

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2013-07-10 15:10Z]

http://data.canadensys.net/vascan/taxon/22413
