### ISSUE TITLE
typo in authority of species & combinations

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1555]
[Originally posted on GoogleCode (id 1471) on 2012-10-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4335 
and http://data.canadensys.net/vascan/taxon/4334

<b>What data are incorrect or missing?</b>
Moenchia erecta (Linnaeus) P. Gaertner, B. Meyer &amp; Scherbius 
Moenchia erecta (Linnaeus) P. Gaertner, B. Meyer &amp; Scherbius subsp. erecta
Moenchia erecta (Linnaeus) P. Gaertner, B. Meyer &amp; Scherbius var. erecta

<b>What data are you expecting instead?</b>
Authorities should all be G. Gaertner, B.Meyer, &amp; Scherbius

<b>If applicable, please provide an authoritative source.</b>
see IPNI and IPNI authors. Note that Tropicos, FNA, and the Plant List are all incorrect for this name.
 
Gottfried's Gartner's first name was not Philip; that was a historical error when someone misinterpreted his first name as Philip; we have dealt with this before with other combinations - see Issues 11 and 1092.

See IPNI entry for Calamagrostis neglecta: [&quot;Abbreviation G.Gaertn. used because of information from S. Dressler that he was known as Gottfried Gaertner during his lifetime. According to a Walloonian custom the name Philipp, his father's name, was added after death. Another possible explanation is from Dr K.P. Buttler who points out that the death notice in Flora, 1826(1): 32 states: &quot;...starb zu Hanau Hr. Dr. Phil. Gottfried Gartner.&quot; where 'Phil.' may have been interpreted as Philipp.&quot;]  This latter explanation sounds more logical, Dr. Phil. meant to represent Ph.D.
  
In IPNI authors,there is no P. Gaertner, only Gottfried Gaertner.
    A.Gaertn. - Alwin Gaertner fl. 1954
    C.F.Gaertn. - Carl (Karl) Friedrich von Gaertner 1772-1850
    G.Gaertn. - Gottfried Gaertner 1754-1825
    Gaertn. - Joseph Gaertner 1732-1791

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 17:34Z]

Not all corrections to authors have been made because I cannot search on this.
