### ISSUE TITLE
incorrect spelling for author of species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1556]
[Originally posted on GoogleCode (id 1472) on 2012-10-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4260

<b>What data are incorrect or missing?</b>
Cerastium bialynickii Tolm

<b>What data are you expecting instead?</b>
Cerastium bialynickii Tolmatchew

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 19:05Z]

abbrev. was not completed and period had been removed...
