### ISSUE TITLE
questionable synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1557]
[Originally posted on GoogleCode (id 1473) on 2012-10-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4338

<b>What data are incorrect or missing?</b>
Moenchia erecta var. paleacea Fernald

<b>What data are you expecting instead?</b>
Is this a valid name?  If not, delete.

<b>If applicable, please provide an authoritative source.</b>
I can't find this species anywhere.  It's not in Tropicos, IPNI, or FNA.
If it does exist, the citation is incomplete, as Fernald described this species in 1936 as Paronychia fastigiata var. paleacea, which you also list here.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 19:08Z]

As I do not know where such a name may have come from (and as it is likely to be simply a mistake based on the Paronychia), I am removing it
