### ISSUE TITLE
Incorrect genus and authority abbreviation in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1559]
[Originally posted on GoogleCode (id 1475) on 2012-10-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4355

<b>What data are incorrect or missing?</b>
Sagina saginoides var. nivalis A.E. Lindblom

<b>What data are you expecting instead?</b>
Spergula saginoides var. nivalis Lindblom

<b>If applicable, please provide an authoritative source.</b>
Tropicos and IPNI authors
I can't find a combination of var. nivalis with Sagina saginoides.
[IPNI was down]

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 19:10Z]

probably a bad cut and paste in initial database - it is indeed Spergula
