### ISSUE TITLE
authority of species and subsp.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1560]
[Originally posted on GoogleCode (id 1476) on 2012-10-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4349
http://data.canadensys.net/vascan/taxon/4348

<b>What data are incorrect or missing?</b>
Sagina decumbens (S. Elliott) Torrey &amp; A. Gray
Sagina decumbens (S. Elliott) Torrey &amp; A. Gray subsp. decumbens

<b>What data are you expecting instead?</b>
Sagina decumbens (Elliott) Torrey &amp; A. Gray
Sagina decumbens (Elliott) Torrey &amp; A. Gray subsp. decumbens

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-22 19:12Z]

remains of when initials were added - slowly we will get them out

I unfortunately cannot search on authorities in the VASCAN editor
