### ISSUE TITLE
authority of synonym; illeg. homonym not noted.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1564]
[Originally posted on GoogleCode (id 1480) on 2012-10-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4389

<b>What data are incorrect or missing?</b>
Silene pratensis (Rafinesque) Grenier &amp; Godron
Silene alba (Miller) E.H.L. Krause

<b>What data are you expecting instead?</b>
Silene pratensis (Rafinesque) Godron [in Grenier &amp; Godron]
Silene alba (Miller) E.H.L. Krause, nom. illeg. hom., [1901, non Muhl. ex Rohrb. (1868)

<b>If applicable, please provide an authoritative source.</b>
IPNI lists both Godron and Grenier &amp; Godron, Tropicos has Grenier &amp; Godron; 
GRIN and French Index Synonymique have Godr.  From I.S.:
&quot;Silene pratensis (Rafn) Godron in Gren. &amp; Godron [1847, Fl. Fr., 1 : 116] = S. latifolia subsp. alba &quot;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-24 18:51Z]

S. partensis: Another one I will have to ask about

S. alba: I am not sure the name is illeg. bec. the Muhl. name is superfluous... have to ask

**Comment by brouille** [comment]
Silene pratensis (Rafinesque) Godron
Silene alba (Miller) E.H.L. Krause nom. illeg. [see E+M] [but other sources are not clear]
