### ISSUE TITLE
typos in epithet of species and synonym; authority of synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1567]
[Originally posted on GoogleCode (id 1483) on 2012-10-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4400

<b>What data are incorrect or missing?</b>
a) Silene sorensensis (B. Boivin) Bocquet (delete the next to last 
   's' here and in the next)
   Lychnis sorensensis B. Boivin

b) Lychnis triflora R. Brown ex Sommerfelt 
   Melandrium triflorum (R. Brown ex Sommerfelt) J. Vahl
   Lychnis affinis var. triflora (R. Brown ex Sommerfelt) Hart
   Agrostemma triflorum (R. Brown ex Sommerfelt) Fries
   Wahlbergella triflora (R. Brown ex Sommerfelt) Fries

<b>What data are you expecting instead?</b>
a) Silene sorensenis (B. Boivin) Bocquet  
   Lychnis sorensenis B. Boivin

b) Lychnis triflora R. Brown
   Melandrium triflorum (R. Brown) J. Vahl
   Lychnis affinis var. triflora (R. Brown) Hart
   Agrostemma triflorum (R. Brown) G.Don
   Wahlbergella triflora (R. Brown) Fries

<b>If applicable, please provide an authoritative source.</b>
MBG, and IPNI has most, though sometimes does not list basionym.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-24 18:59Z]

a) done

b) done
