### ISSUE TITLE
typo in common English name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1572]
[Originally posted on GoogleCode (id 1488) on 2012-10-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4410

<b>What data are incorrect or missing?</b>
William's catchfly

<b>What data are you expecting instead?</b>
Williams's catchfly

<b>If applicable, please provide an authoritative source.</b>
This species is names after a Williams, not a William, so the apostrophe goes after the 1st S.  FNA includes two 's's.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-24 19:07Z]

only single s needed, technically - but Manuals of Style may differ on this
