### ISSUE TITLE
typo in spelling of synonym genus

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1573]
[Originally posted on GoogleCode (id 1489) on 2012-10-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4382

<b>What data are incorrect or missing?</b>
Coronceria flos-cuculi (Linnaeus) A. Braun

<b>What data are you expecting instead?</b>
Coronaria flos-cuculi (Linnaeus) A. Braun

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-24 19:15Z]

added further synonymns from TROPICOS
