### ISSUE TITLE
typo in variety name; spelling and authority of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1576]
[Originally posted on GoogleCode (id 1492) on 2012-10-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4354

<b>What data are incorrect or missing?</b>
a) Sagina crassicaulis var. littoralis (Hultén) Hultén
   Sagina littoralis Hultén

b) Sagina maxima var. litorea (Mackenzie) Hara

<b>What data are you expecting instead?</b>
a) Sagina crassicaulis var. litoralis (Hultén) Hultén
   Sagina litoralis Hultén

b) Sagina maxima var. littorea (Makino) H.Hara

<b>If applicable, please provide an authoritative source.</b>
a) mbg, fna, tropicos
b) mbg; I know you don't list forma, but the basionym  of this name is Sagina maxima forma littorea Makino, which was published in
the Bot. Mag. (Tokyo) [in Tropicos].  I don't think Mackenzie published in a Japanese journal.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-25 19:24Z]

Changes made

I am uncertain as to the status of M. maxima var. littorea - Plant List places it in syn of S. maxima - I have no ref for it being syn to where I put it... it might be best to remove it. Will think on it.
