### ISSUE TITLE
incorrect basionym author for species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1594]
[Originally posted on GoogleCode (id 1511) on 2012-10-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4615
http://data.canadensys.net/vascan/taxon/9871

<b>What data are incorrect or missing?</b>
Calystegia silvatica (Kitamura) Grisebach
Calystegia silvatica (Kitamura) Grisebach subsp. silvatica

<b>What data are you expecting instead?</b>
Calystegia silvatica (Kitaibel) Grisebach
Calystegia silvatica (Kitaibel) Grisebach subsp. silvatica
basionym is: Convolvulus Kitaibel

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-10-26 19:26Z]

That should read: basionylm is Convolvulus silvaticus Kitaibel

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-29 13:03Z]

basionym added
