### ISSUE TITLE
missing synonym?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1599]
[Originally posted on GoogleCode (id 1516) on 2012-10-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4655

<b>What data are incorrect or missing?</b>
missing: Cornus × lepagei Gervais &amp; Blondeau

<b>What data are you expecting instead?</b>
?add: Cornus × lepagei Gervais &amp; Blondeau
IPNI give the parents as C. canadensis subsp pristina x C. suecica, from Quebec (and eCan), so should this be a syn of C. x intermedia or does it belong elsewhere?

<b>If applicable, please provide an authoritative source.</b>
See IPNI entry under Cornus x lepagei Gervais &amp; Blondeau (2003)
Type location: Nunavik, environs d'Umiujaq

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-29 13:16Z]

Gervais and Blondeau apparently believed in distinguishing subspp. in C. canadensis; it is possible that intermedia is subsp. canadensis x suecica, which then would be distinct from subsp. pristina x suecica 

I do not know enough currently to tell whether the two subspp. are distinct or not.

You are right in raising the issue, but I cannot deal with it immediately, pending more knowledge of the parentages and ultimate taxonomy.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-14 12:50Z]

I decided to not recognize subspp. within canadensis for the time being and thus to place this entity in synonymy as you suggest

If the taxonomy in FNA differs, we will revisit this

Luc
