### ISSUE TITLE
Cardamine dentata

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#16]
[Originally posted on GoogleCode (id 582) on 2011-07-18]

Salut

Pas officiellement dans FNA.  Voir Cardamine pratensis.
Que fait-on?

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-20 14:29Z]

Fred

J'ai suivi la recommendation de mon collègue de B.C. sur ce point en distinguant les deux entités. Note la discussion dans FNA.

Alors je conserve comme tel.
