### ISSUE TITLE
Vitis labruscana L.H. Bailey

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#160]
[Originally posted on GoogleCode (id 2303) on 2014-09-03]

Salut

Ce n'est pas un synonyme de V. labrusca.  Ce taxon est valide selon The Plant List et il s'agit d'un hybride: Vitis x labruscana L.H. Bailey
Voir IPNI pour les parents

http://www.ipni.org/ipni/idPlantNameSearch.do;jsessionid=694663728DE41B077983693EAC39403C?id=60458947-2&amp;back_page=%2Fipni%2FeditAdvPlantNameSearch.do%3Bjsessionid%3D694663728DE41B077983693EAC39403C%3Ffind_infragenus%3D%26find_isAPNIRecord%3Dtrue%26find_geoUnit%3D%26find_includePublicationAuthors%3Dtrue%26find_addedSince%3D%26find_family%3D%26find_genus%3Dvitis%26find_sortByFamily%3Dtrue%26find_isGCIRecord%3Dtrue%26find_infrafamily%3D%26find_rankToReturn%3Dall%26find_publicationTitle%3D%26find_authorAbbrev%3D%26find_infraspecies%3D%26find_includeBasionymAuthors%3Dtrue%26find_modifiedSince%3D%26find_isIKRecord%3Dtrue%26find_species%3Dlabr*%26output_format%3Dnormal

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-20 19:16Z]

synonyme supprimé
