### ISSUE TITLE
typos in spelling of epithet and var. of synonym; authority of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1600]
[Originally posted on GoogleCode (id 1517) on 2012-10-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4662

<b>What data are incorrect or missing?</b>
Sedum kamtshcaticum subsp. ellacombianum (Praeger) R.T. Clausen

<b>What data are you expecting instead?</b>
Sedum kamtschaticum subsp. ellacombeanum R.T. Clausen

<b>If applicable, please provide an authoritative source.</b>
IPNI and Tropicos for spelling; see IPNI for explanation of
Clausen's invalid name - incomplete ref. to basionym.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-29 13:22Z]

Well, that one was missed when FNA was being published and it has not been corrected since... And neither has TRO.
