### ISSUE TITLE
Betula × murrayana B.V.Barnes & Dancik

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#161]
[Originally posted on GoogleCode (id 2350) on 2014-11-18]

Addition à la flore de l'Ontario
Dans le livre suivant, on le traite comme une espèce alors que Plants le traite comme un hybride.
IUCN Red List: The Red List of Betulaceae
http://www.bgci.org/files/Global_Trees_Campaign/Betulaceae/Betulaceae_final.pdf

**Comment by brouille** [comment]
FNA le traite comme espèce dérivée d'hybridation
ajouté à Ont
