### ISSUE TITLE
authority abbreviation in species and synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1613]
[Originally posted on GoogleCode (id 1530) on 2012-10-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5775

<b>What data are incorrect or missing?</b>
Acmispon denticulatus (E. Drew) D.D. Sokoloff
Hosackia denticulata E. Drew
Anisolotus denticulatus (E. Drew) A. Heller
Lotus denticulatus (E. Drew) Greene

<b>What data are you expecting instead?</b>
Acmispon denticulatus (Drew) D.D. Sokoloff
Hosackia denticulata Drew
Anisolotus denticulatus (Drew) A. Heller
Lotus denticulatus (Drew) Greene

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI, IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-02 14:10Z]

This is a remnant of the time when initials had been given to all - there must be many remaining still...
