### ISSUE TITLE
incorrect authority for synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1614]
[Originally posted on GoogleCode (id 1531) on 2012-10-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5778

<b>What data are incorrect or missing?</b>
Anisolotus decumbens (Bentham) Thornberg

<b>What data are you expecting instead?</b>
Anisolotus decumbens (Bentham) M.Armstrong &amp; Thornber

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos, IPNI authors
It looks like Thornber is misspelled, but checking IPNI authors, that is the proper spelling.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-02 14:11Z]

an embarrassing mistake...
