### ISSUE TITLE
confusion over spelling of epithet of species 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1615]
[Originally posted on GoogleCode (id 1532) on 2012-10-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5682

<b>What data are incorrect or missing?</b>
Astragalus aboriginum Sprengel  (1827)

<b>What data are you expecting instead?</b>
?Astragalus aboriginorum Richardson  (1823)
or Astragalus aboriginum Richardson ex Sprengel {1827)

<b>If applicable, please provide an authoritative source.</b>
In IPNI and GRIN, Sprengel's spelling (aboriginum) is listed as a correction of the original spelling (aboriginorum) by Richardson.  But why was this corrected? Was it a typo that Richardson acknowledged, or did Sprengel assume he'd spelled it incorrectly.  If that latter, I can't think that would be a valid reason to change the original spelling.  Aren't there other names that have gone back to the original spelling too?  I'm not sure of the rules here, but Tropicos lists both A. aboriginum and A. aboriginorum for each variety, which just confuses things.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-02 14:14Z]

I cannot answer your query. I can only add Richardson ex for the time being, given it is in both TROPICOS and IPNI
I probably will have to query this one
Astragalus is being reviewed, but it is massive and has author complications...

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-06 21:06Z]

This is currently the object of a discussion among nomenclaturalists: aboriginorum was the name as published initially by Richardson, later correct to the better formed aboriginum (hence the ex)

I am waiting for the final conclusion. I would prefer aboriginum (then it would be ex)

**Comment by brouille** [comment]
According to Kanchi Gandhi, aboriginorum must be kept and is not to be corrected to aboriginum

This leaves open the question of infraspecies attached to one or the other, however : must they be transferred or left as it, if synonyms ?

Luc
