### ISSUE TITLE
synonym an illeg. homonym; authorities of 2 synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1616]
[Originally posted on GoogleCode (id 1534) on 2012-11-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5628

<b>What data are incorrect or missing?</b>
Astragalus viciifolius Hultén
Astragalus adsurgens subsp. viciifolius (Hultén) Welsh
Astragalus laxmannii var. tananaicus (Hultén) Barneby &amp; Welsh

<b>What data are you expecting instead?</b>
Astragalus viciifolius Hultén, nom. illeg. hom. [non DC.]
Astragalus adsurgens subsp. viciifolius S.L. Welsh
Astragalus laxmannii var. tananaicus (Hultén) Barneby &amp; S.L.Welsh

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

Since Hulten's A. viciifolius is a later homonym, it can't be used as the basionym of later combinations of viciifolius.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-05 20:09Z]

I need to compare the VASCAN entries to the FNA treatment - there are changes
