### ISSUE TITLE
formatting error

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1617]
[Originally posted on GoogleCode (id 1535) on 2012-11-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5634

<b>What data are incorrect or missing?</b>
Astragalus forwoodii S. Watson, Astragalus scrupulicola Fernald &amp; Weatherby - these two names appear on the same line
they should be one above the other.

<b>What data are you expecting instead?</b>
Astragalus forwoodii S. Watson
Astragalus scrupulicola Fernald &amp; Weatherby

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-05 20:13Z]

There is a further synonymy problem, but I at least removed the second name; scrupulicola was present elsewhere in the database - this needs to be checked against FNA ms
