### ISSUE TITLE
synonym an illeg. homonym; missing basionym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1618]
[Originally posted on GoogleCode (id 1536) on 2012-11-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5642

<b>What data are incorrect or missing?</b>
Astragalus brevidens Rydberg
basionym is missing:

<b>What data are you expecting instead?</b>
Astragalus brevidens Rydberg [1929], nom. illeg. hom., non Freyn &amp; Sintenis [1900]
Add: Astragalus mortonii var. brevidens Gandoger

<b>If applicable, please provide an authoritative source.</b>
Tropicos lists Freyn &amp; Sint. as a homonym, but give no date
This link: http://130.235.149.100:591/Lund/images/1038116.jpg 
is of an isotype of Freyn &amp; Sintenis's type specimen from 1900.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-05 20:17Z]

I added the nom. illeg. to the Rydb. name

I am hesitant, however, to add the basionym you mention since it does not look to belong to the same entity acc. to the information in the databases

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-11-05 23:36Z]

Actually, I should have written Astragalus mortonii forma brevidens 
Gandoger, not var.
HWR, that causes a problem, since you don't list forma ranks.
See GRIN, IPNI, & Tropicos:
See: http://www.ars-grin.gov/cgi-bin/npgs/html/taxon.pl?5741
http://www.tropicos.org/Name/13063134
IPNI:


      /Astragalus/ /mortonii/ Nutt.
      <http://www.ipni.org/ipni/idAuthorSearch.do?id=24198-1&back_page=%2Fipni%2FeditAdvPlantNameSearch.do%3Ffind_infragenus%3D%26find_isAPNIRecord%3Dtrue%26find_geoUnit%3D%26find_includePublicationAuthors%3Dtrue%26find_addedSince%3D%26find_family%3D%26find_genus%3DAstragalus%26find_sortByFamily%3Dtrue%26find_isGCIRecord%3Dtrue%26find_infrafamily%3D%26find_rankToReturn%3Dall%26find_publicationTitle%3D%26find_authorAbbrev%3D%26find_infraspecies%3D%26find_includeBasionymAuthors%3Dtrue%26find_modifiedSince%3D%26find_isIKRecord%3Dtrue%26find_species%3Dcanadensis%26output_format%3Dnormal>
      f. /brevidens/ Gand.
      <http://www.ipni.org/ipni/idAuthorSearch.do?id=3009-1&back_page=%2Fipni%2FeditAdvPlantNameSearch.do%3Ffind_infragenus%3D%26find_isAPNIRecord%3Dtrue%26find_geoUnit%3D%26find_includePublicationAuthors%3Dtrue%26find_addedSince%3D%26find_family%3D%26find_genus%3DAstragalus%26find_sortByFamily%3Dtrue%26find_isGCIRecord%3Dtrue%26find_infrafamily%3D%26find_rankToReturn%3Dall%26find_publicationTitle%3D%26find_authorAbbrev%3D%26find_infraspecies%3D%26find_includeBasionymAuthors%3Dtrue%26find_modifiedSince%3D%26find_isIKRecord%3Dtrue%26find_species%3Dcanadensis%26output_format%3Dnormal>



        Bull. Soc. Bot. France
        <http://www.ipni.org/ipni/idPublicationSearch.do?back_page=%2Fipni%2FeditAdvPlantNameSearch.do%3Ffind_infragenus%3D%26find_isAPNIRecord%3Dtrue%26find_geoUnit%3D%26find_includePublicationAuthors%3Dtrue%26find_addedSince%3D%26find_family%3D%26find_genus%3DAstragalus%26find_sortByFamily%3Dtrue%26find_isGCIRecord%3Dtrue%26find_infrafamily%3D%26find_rankToReturn%3Dall%26find_publicationTitle%3D%26find_authorAbbrev%3D%26find_infraspecies%3D%26find_includeBasionymAuthors%3Dtrue%26find_modifiedSince%3D%26find_isIKRecord%3Dtrue%26find_species%3Dcanadensis%26output_format%3Dnormal&id=578-2>
        48(Sess. Extraord.): xvi. 1902 [1901 publ. Jan 1902]
