### ISSUE TITLE
Crepis acuminata Nuttall - addition à la flore du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#163]
[Originally posted on GoogleCode (id 2354) on 2014-11-25]

Salut

Selon BEN 484, il faut ajouter la Colombie-Britannique.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-05 21:29Z]

La fiche a été modifiée pour indiquer indigène avec la réf.
