### ISSUE TITLE
basionym authority is an illeg. homonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1632]
[Originally posted on GoogleCode (id 1551) on 2012-11-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5727

<b>What data are incorrect or missing?</b>
Desmodium rotundifolium (Michaux) de Candolle
Hedysarum rotundifolium Michaux

<b>What data are you expecting instead?</b>
Desmodium rotundifolium de Candolle
Hedysarum rotundifolium Michaux, nom. illeg. hom., non Vahl

<b>If applicable, please provide an authoritative source.</b>
IPNI &amp; GRIN; Tropicos lists (Michx.) DC., but then notes that the basionym is an illeg. homonym.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-28 14:33Z]

FNA ms not available yet - most corrections you are requesting in Fabaceae will be of this nature: there has been no review yet of nomenclature and taxonomy. Not all issues may be solved or may be as clear as appearances. Please note this.
Luc
