### ISSUE TITLE
typo in common English name - synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1633]
[Originally posted on GoogleCode (id 1552) on 2012-11-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5745

<b>What data are incorrect or missing?</b>
darkpark pea

<b>What data are you expecting instead?</b>
drypark pea

<b>If applicable, please provide an authoritative source.</b>
USDA and other web sites; no website had darkpark pea.

http://plants.usda.gov/java/profile?symbol=LABI2

http://biology.burke.washington.edu/herbarium/waflora/checklist.php?Taxon=Lathyrus%20bijugatus&amp;ID=11642

http://www.calflora.org/cgi-bin/species_query.cgi?where-calrecnum=10040

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-28 14:40Z]

Marilyn: for your information. I made the correction. If you object, please say so.

Thanks

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-12-11 16:00Z]

tremendous catch! Many thanks!
