### ISSUE TITLE
incorrect authorities for subsp.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1635]
[Originally posted on GoogleCode (id 1554) on 2012-11-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5750

<b>What data are incorrect or missing?</b>
Lathyrus nevadensis subsp. lanceolatus S. Watson

<b>What data are you expecting instead?</b>
Lathyrus nevadensis subsp. lanceolatus (Howell) C.L.Hitchcock

<b>If applicable, please provide an authoritative source.</b>
Tropicos; S.Watson is the author of Lathyrus nevadensis
Ipni doesn't list this combination, although they do list the basionym, but not as a synonym.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-28 14:48Z]

It is interesting that IPNI does not list this combination, yet Plant List does (based on ILDIS)
GRIN also does not list it under this species

Added basionym to var. pilosellus entry
