### ISSUE TITLE
question about authority of var.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1636]
[Originally posted on GoogleCode (id 1555) on 2012-11-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5749

<b>What data are incorrect or missing?</b>
Lathyrus nevadensis ... var. pilosellus (M. Peck) C.L. Hitchcock

<b>What data are you expecting instead?</b>
Lathyrus nevadensis ... var. pilosellus (M. Peck) C.L. Hitchcock &amp; Ownbey

<b>If applicable, please provide an authoritative source.</b>
Tropicos has C.L.Hitchcock &amp; Ownbey, but IPNI just has C.L.Hitchcock, however the publication is listed as C.L.Hitchcock et al., so Tropicos may have listed the books author rather than the species' author.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-28 14:51Z]

TRO clearly states the in authorities as Hitchcock et al., so there is no confusion on the authorities.

What is curious is that Plant List also uses only C.L. Hitchc., though they cite TRO as the source

This may have to be revisited once Lathyrus ms is circulated
