### ISSUE TITLE
authority of synonym; wrong placement for basionym of species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1638]
[Originally posted on GoogleCode (id 1557) on 2012-11-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5764

<b>What data are incorrect or missing?</b>
Lespedeza juncea var. sericea F.B. Forbes &amp; Hemsley
Hedysarum junceum Linnaeus f.

<b>What data are you expecting instead?</b>
Lespedeza juncea var. sericea Maximowicz (1873), non F.B. Forbes &amp; Hemsley (1887)
move: Hedysarum junceum Linnaeus f. - this is the basionym of the species, so should be on the previous entry.

<b>If applicable, please provide an authoritative source.</b>
GRIN (for a)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-28 14:57Z]

We provide syns only at the lowest level, so I will simply remove the basionym
