### ISSUE TITLE
Le lien web pour Harms 2006 ne fonctionne pas

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#164]
[Originally posted on GoogleCode (id 2355) on 2014-11-25]

Salut

Utilise celui-ci
http://www.biodiversity.sk.ca/Docs/AnnotatedCatalogueSKVascPlants2006.pdf

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-05 21:22Z]

Le lien fonctionne: il télécharge un document pdf. Ce n'est pas un lien vers une page web

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-05 21:43Z]

modifié
