### ISSUE TITLE
author abbreviations in species and synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1641]
[Originally posted on GoogleCode (id 1560) on 2012-11-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
a) http://data.canadensys.net/vascan/taxon/5793
b) http://data.canadensys.net/vascan/taxon/5792
c) http://data.canadensys.net/vascan/taxon/5794

<b>What data are incorrect or missing?</b>
a) Lupinus arcticus Watson
b) Lupinus arcticus Watson subsp. arcticus
c) Lupinus arcticus subsp. subalpinus (Piper &amp; B.L. Robinson) D. Dunn
   Lupinus arcticus subsp. canadensis (C.P. Smith) D. Dunn

<b>What data are you expecting instead?</b>
a) Lupinus arcticus S.Watson
b) Lupinus arcticus S. Watson subsp. arcticus
c) Lupinus arcticus subsp. subalpinus (Piper &amp; B.L. Robinson) D.B.
   Dunn
   Lupinus arcticus subsp. canadensis (C.P. Smith) D.B Dunn

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-28 15:11Z]

added basio + syns of syns
