### ISSUE TITLE
Abbeviation in authority of species & synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1647]
[Originally posted on GoogleCode (id 1566) on 2012-11-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5836

<b>What data are incorrect or missing?</b>
Medicago sativa subsp. varia (T. Martyn) Arcangeli
Medicago varia T. Martyn

<b>What data are you expecting instead?</b>
Medicago sativa subsp. varia (Martyn) Arcangeli
Medicago varia Martyn

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-28 15:21Z]

added a x sign to M. varia given it was described as a hybrid fide TRO
