### ISSUE TITLE
author abbreviations in species and synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1648]
[Originally posted on GoogleCode (id 1567) on 2012-11-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5852

<b>What data are incorrect or missing?</b>
Oxytropis borealis var. viscida (Nuttall) Welsh
Oxytropis glutinosa Porsild
Oxytropis sheldonensis Porsild
Oxytropis verruculosa Porsild

<b>What data are you expecting instead?</b>
Oxytropis borealis var. viscida (Nuttall) S.L.Welsh
Oxytropis glutinosa A.E.Porsild
Oxytropis sheldonensis A.E.Porsild
Oxytropis verruculosa A.E.Porsild

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-11-28 15:29Z]

added typic syns
