### ISSUE TITLE
Platanthera shriveri

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#165]
[Originally posted on GoogleCode (id 2361) on 2014-12-08]

Salut

Addition à la flore du Québec.
Spécimen déposé à MT

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-05 20:02Z]

ES tu conscient que PLANTS http://plants.usda.gov/core/profile?symbol=PLSH4 considère cette plante comme un hybride? Je ne sais qui a changé le statut à celui d'hybride. Les parents seraient grandiflora x lacera

En fait, le nothotaxon deviendrait le nom pour l'hybride entre les deux parents déjà rapporté dans VASCAN (sous la combinaison hybride).

Connaîtrais tu une réf. au fait que le taxon soit un hybride? PLANTS n'en donne pas.

J'aurai simplement à changer la combinaison pour le nothotaxon, si vraiment c'est le cas.

Luc

**Comment by brouille** [comment]
FNA : Platanthera grandiflora is known to hybridize with P. lacera in the northeasternmost portion of its range, where the species bloom simultaneously. The name P. × keenanii P. M. Brown has recently been proposed for these hybrids, but the complex synonymy of this group dictates that types be checked for possible priority. See the discussion under P. lacera.

PAs trouvé de ref où le taxon serait montré comme hybride - PLANTS ne fournit pas de ref

**Comment by brouille** [comment]
L'article de PM Brown montre les différences entre P. x keenanii et P. shriveri. J'accepte donc P. shriveri comme sp distincte. 
source:  MT - quoiqu'un mémoire non publié mentionne la présence de cette espèce
Luc

**Comment by brouille** [comment]
Marc et Marylin:
Svp, fournir un nom vernaculaire au Platanthera shreveri. Brown et al. 2008 n'en proposent pas en anglais, mais je crois que c'est plutôt évident dans ce cas.
Merci
Luc

**Comment by MFavreau** [comment]
French name added.

Marilyn : please note, the name is shriveri, not shreveri.

**Comment by manions** [comment]
English vernacular added
