### ISSUE TITLE
spelling of synonym name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1659]
[Originally posted on GoogleCode (id 1579) on 2012-11-15]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5879

<b>What data are incorrect or missing?</b>
Oxytropis nigrescens subsp. bryophylla (Greene) Hultén

<b>What data are you expecting instead?</b>
Oxytropis nigrescens subsp. bryophila (Greene) Hultén
basionym: Aragallus bryophilus Greene

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-12-12 21:57Z]

added homotypic synonyms
