### ISSUE TITLE
Manns & Anderberg, 2009.

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#166]
[Originally posted on GoogleCode (id 2459) on 2015-01-26]

Salut

Le lien pour cette article ne fonctionne pas dans Lysimachia borealis.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 18:35Z]

Lien remplacé par doi, non disponible à l'époque

Note que le lien fonctionnait, mais tu n'as sans doute pas accès à la revue

Luc
