### ISSUE TITLE
typo in epithet of 1 synonym; incorrect authorities for 2nd synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1667]
[Originally posted on GoogleCode (id 1593) on 2012-11-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5905

<b>What data are incorrect or missing?</b>
Cracca virgiana Linnaeus
Tephrosia holosericea (Nuttall) Torrey &amp; A. Gray

<b>What data are you expecting instead?</b>
Cracca virginiana Linnaeus
Tephrosia holosericea Nuttall; 
the authorities given made this combination:
Tephrosia virginiana (Nuttall) Torrey &amp; A. Gray

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-11-18 18:55Z]

That last line should read: Tephrosia virginiana var. holoserica (Nuttall) Torrey & A. Gray; I hit the enter too soon.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-12-13 13:49Z]

Added homotypic syns
