### ISSUE TITLE
Anchusa azurea P. Miller - autorité

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#167]
[Originally posted on GoogleCode (id 2471) on 2015-02-03]

Salut

FNAms n'indique pas le P. dans Miller.  Ipni n'indique pas le P.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 15:05Z]

Vieille pratique du début de VASCAN où on mettait une initiale à tous les noms. Pas une erreur, mais nous avons adopté le standard général depuis.

Merci
Luc
