### ISSUE TITLE
accepted common name is for Parthenocissus quinquefolia

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1676]
[Originally posted on GoogleCode (id 1646) on 2013-03-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9538

<b>What data are incorrect or missing?</b>
Accepted common name, Virginia creeper and 4 other names listed, refer to Parthenocissus cinquefolia, not P. inserta.
including:
American ivy
five-leaved ivy
five-leaved Virginia creeper
red-twig creeper

<b>What data are you expecting instead?</b>
thicket creeper is the accepted name suggested by James Pringle in 2010.
Virginia creeper is retained for Partenocissus quinquefolia
grape woodbine and false Virginia creeper are also listed by Pringle as common names for P. inserta, which should be added.

Also suggest you add a new French common name: fausse vigne vierge de Virginie.  See reference below.

I question the use of red-twig creeper, as this plant does not have red stems; the fruiting pedicels are red, but in both P. inserta and P. quinquefolia;, they both have 5 leaflets, so five-leaved Virginia creeper actually describes itself.  American ivy also refers to P. quinquefolia in online dictionaries and other website:
[American ivy
     n : common North American vine with compound leaves and
         bluish-black berrylike fruit [syn: Virginia creeper, American
         ivy, woodbine, Parthenocissus quinquefolia]
 
Redtwig creeper also refers to P. virginiana in these websites:
http://www.noble.org/apps/plantimagegallery/Plant.aspx?PlantID=123&amp;IndexType=CommonName&amp;PlantMainName=Redtwig%20Creeper&amp;PlantTypeID=3

http://aggie-horticulture.tamu.edu/ornamentals/nativeshrubs/parthenocissusquin.htm

Have not seen any of these 4 names used for P. inserta.

<b>If applicable, please provide an authoritative source.</b>

James Pringle’s publication on the differences between Parthenocissus inserta and P. quinquefolia list thicket creeper, false Virginia creeper, and grape-woodbine as common names for P. inserta, with Virginia creeper retained for P. quinquefolia. See: 

&lt;http://quod.lib.umich.edu/cgi/p/pod/dod-idx/nomenclature-of-the-thicket-creeper-parthenocissus-inserta.pdf?c=mbot;idno=0497763.0049.301&gt; 

Also, this website from France uses the common name fausse vigne vierge de Virginie for P. inserta. 
&lt;http://www.cps-skew.ch/fileadmin/template/pdf/inva_francais/inva_part_ins_f.pdf&gt;

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-09 20:44Z]

After looking at the common names for the other Parthenocissus, the English names all seem to be placed incorrectly, though the French names are correct for each species.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 13:54Z]

Marilyn

Please review this issue and make corrections as appropriate.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-18 12:38Z]

completed
