### ISSUE TITLE
common names in Parthenocissus tricuspidata refer to P. inserta

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1678]
[Originally posted on GoogleCode (id 1648) on 2013-03-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9540

<b>What data are incorrect or missing?</b>
common English names provided refer to Parthenocissis inserta.  See J.S. Pringle publication listed in previous issue on Parthenocissus inserta

<b>What data are you expecting instead?</b>
Boston ivy (preferred name by Royal Horticultural Society)
Japanese creeper
Japanese ivy

<b>If applicable, please provide an authoritative source.</b>
Royal Horticultural Society and Virginia Tech Dendrology websites
http://apps.rhs.org.uk/plantselector/plant?plantid=1385
http://dendro.cnre.vt.edu/dendrology/syllabus/factsheet.cfm?ID=301

as well as MBG, USDA Plants NC State, Iowa State, and UCONN hort websites.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 13:56Z]

Marilyn

Please review and correct as you see fit.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-18 12:38Z]

completed
