### ISSUE TITLE
common names in Parthenocissus quinquefolia refer to P. tricuspidata; question about range of P.q.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1679]
[Originally posted on GoogleCode (id 1649) on 2013-03-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9539

<b>What data are incorrect or missing?</b>
Boston ivy
Japanese creeper
Japanese ivy

<b>What data are you expecting instead?</b>
These common English name refer to Parthenocissus tricuspidata
Virginia creeper should be the accepted name, and other names listed under P. inserta should be lised here too.

I think the range map is also incorrect for provinces outside of ON and QC; possibly only introduced in Ontario too.

<b>If applicable, please provide an authoritative source.</b>
See previous entry re: names.  
For range question, see Gray's Manual &amp; Soper &amp; Heimburger's Shrubs of Ontario. Its listed as native in seQuebec in Gray's, and Soper &amp; Heimburger say it is doubtfully native to Ontario. I'm not sure if it is found in other provinces, but it is not native there, according to these sources.  Pringle lists southern Ontario, but this contradicts S&amp;H.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 14:00Z]

The species is introduced in QC at least in the Montreal area. Other locations might be incerta. It may be introduced in Ont. also. 

I believe that the wrong name has been used for the native taxon in all traditional floras.

This is a taxon that has not been revised since there is not treatment of Vitaceae yet for FNA. I will see if I can find the Pringle paper.

MArilyn:

Could you please review the vernacular names and correct as appropriate.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 14:33Z]

range corrected

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-13 19:28Z]

Hi Luc,
Here is a link to the Pringle paper.You'll need to cut and past, as I 
don't think the hyperlink works.  - Sue.

Pringle, J.S. 2010.Nomenclature of the thicket creeper, /Parthenocissus 
inserta/ (Vitaceae)./Michigan Botanist/ 49(3): 73-78.

<http://quod.lib.umich.edu/cgi/p/pod/dod-idx/nomenclature-of-the-thicket-creeper-parthenocissus-inserta.pdf?c=mbot;idno=0497763.0049.301>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 20:15Z]

Sue

I got the paper via electronic publications.

The Parthenocissus issue is done except for vernaculars.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-18 12:39Z]

completed
