### ISSUE TITLE
Antennaria glabrifolia Fernald

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#168]
[Originally posted on GoogleCode (id 1036) on 2012-01-30]

Antennaria glabrifolia Fernald

smoothleaf pussytoes; Fr: antennaire à feuilles glabres.  Quebec.
[Labrador reports of Antennaria glabrifolia probably refer to collections from Saguenay Co. (Labrador Peninsula), eQue.]

Salut

Un ajout dans les synonymes.  Une exclusion pour le Labrador fide ??? (un vieux document que tu as fait avec Stuart si je ne me trompe pas.).

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-31 13:28Z]

Ajout dans les synonymes de quelle espèce? J'aurais besoin d'une source pour cet ajout.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-26 12:53Z]

= Antennaria neglecta
il n'est pas nécessaire d'ajouter des vernaculaires ou une répartition
exclusion Labr. ajoutée
