### ISSUE TITLE
suggested French common names for Hibiscus moscheutos

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1681]
[Originally posted on GoogleCode (id 1654) on 2013-03-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6621

<b>What data are incorrect or missing?</b>
no French common name

<b>What data are you expecting instead?</b>
ketmie des marais, hibiscus des marais

<b>If applicable, please provide an authoritative source.</b>
&lt;http://nature.jardin.free.fr/vivace/aj_hibiscus_moscheutos.html&gt; 
&lt;http://www.aujardin.info/plantes/hibiscus-moscheutos.php&gt;

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-14 00:54Z]

Ignore this entry, I missed the variety entry at first.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-22 13:48Z]

Sue

It is still valid in some way since Marc is eventually supposed to add an acc FR name to the sp, even if it repeats the var. It just has not been done yet.

I will correct myself

Luc
