### ISSUE TITLE
synonym an invalid name (nom. nudum)

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1682]
[Originally posted on GoogleCode (id 1655) on 2013-03-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6623

<b>What data are incorrect or missing?</b>
Sphaeralcea rivularis (Douglas) Torrey

<b>What data are you expecting instead?</b>
Sphaeralcea rivularis (Douglas) Torrey, nom. inval. (nom. nudum)

<b>If applicable, please provide an authoritative source.</b>
Tropicos has this name listed as 'name only'; but not mentioned in IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-22 13:45Z]

IPNI GCI has nom. inval. with a note
