### ISSUE TITLE
status of synonym Betula x ungavensis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1684]
[Originally posted on GoogleCode (id 1657) on 2013-03-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3711

<b>What data are incorrect or missing?</b>
?Betula ×ungavensis Lepage as a syn. of B. xhornei

<b>What data are you expecting instead?</b>
Since Betula xhornei is listed only from Saskatchewan, how can Lepage's B. ungavensis, be considered a synonym?  IPNI gives this information re: B.ungavensis by Lepage:
Bord d'un lac, entre la riv. Fort George et le lac¹Sakami, 53°34'N, 76°29'W, Quebec (Canada)

<b>If applicable, please provide an authoritative source.</b>
IPNI, Lepage's publication: Naturaliste Canad. 103: 226, fig. 5, 1976 
In Lepage's article he lists B. glandulosa x B. papyrifera as the parents, with specimens seen from Quebec and N.S.
Lepage describes B. hornei right after B. ungavensis, listing B. kenaica and B. nana subsp. exilis as the parents and the range to be BC &amp; Alaska, non SK.  He does not synonymize these two hybrids.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-22 16:17Z]

Here is a list of specimens Lepage examined of B. xungavaneis (p. 226, 228)

QUÉBEC: bord d'un lac, entre la riv. Fort George et le lac Sakami, 53°34' N., 76°29' W., 12 août 1956, Dutilly et Lepage 34220 (holotype: Herbier Louis-Marie, Faculté d'agricul- ture. Université Laval; isotypes: CAN, RIM). — Poste de la Baleine. 55°17' N., 77°46' W., 21 juil. 1969, Brisson et Forest 20458 (RIM, QUE. QFA, TRT, sub B. minor). — Ibid., 21 juil. 1970, Gauthier et Payette GP-200 (QFA). — Rivière Caniapiscau, berge rocheuse en face du confluent de la rivière Swampy Bay, 56°52' N., 69°05' W., 23 août 1961. Dutiily et Lepage 39421 (QFA, RIM, QUE. DAO, CAN, sub B. borealis). — Ashuanipi Lake, halfway between Seven Island and Knob Lake, Aug. 26, 1946, Hustich 768 (CAN, sub B. minor). — Mont Logan, comté de Gaspé, 14 sept. 1950, P. Levés- que 45968 (QUE). — Mont Lyall, comté de Gaspé, Aug. 18, 1936, G.C. Riley, s.n. (DAO). — Mont Albert, comté de Gaspé, coulée du ruisseau du Diable, 25 juil. 1940, Lepage 2069 (RIM, QFA, sub B. minor). 

NOUVELLE-ECOSSE: Mt. Young, Inverness Co.. June 26, 1953, Smith, Taylor, Webster & Slipp 7504 (RIM, sub B. borealis).

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-22 20:10Z]

Do not take hybrid data too litterally: we have not been able to complete information.

THanks for the data that complete the record.

We enter hybrids as they are found in provincial lists, but have not necessarily backtracked.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 17:36Z]

Sue

The reason this happened is that initially, I used the hybrid parentage provided by Kartesz in his Synthesis. This parentage is wrong.

The hybrids are being untangled and the distributions corrected.

Luc
