### ISSUE TITLE
range of Betula x dugleana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1685]
[Originally posted on GoogleCode (id 1658) on 2013-03-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3708

<b>What data are incorrect or missing?</b>
Saskatchewan as only range

<b>What data are you expecting instead?</b>
Yukon

<b>If applicable, please provide an authoritative source.</b>
Lepage (1967) referred to in previous entry, lists specimens examined from the Yukon and Alaska, but does not mention SK.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-22 20:09Z]

the SK report is not from Lepage but from Harms, as stated in VASCAN

I will have to check the Lepage paper - it is 1976 and not 67, right? Given the name was published then acc. to TRO

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-22 20:20Z]

Lepage, E., 1976.  *Les Bouleau Arbustifs du Canada et de l'Alaska.*  /Naturaliste canadien/. Vol 103: 215-233.

Abstract  We attempted to determine the lines of cleavage between the six species of shrubby birches, as well as their
varieties and sub-species, found from Alaska to Newfoundland./Betula borealis/  (aut.) and/B. minor/  are found to be
hybrids and we are describing/B/./saxophila/, as a new species. Considering the frequent introgression between the species,
we are reporting 16 hybrids, 4 of which are new taxa:/B/. �/dugleana/,/B/. �/ungavensis/,/B/. �/minor/  and
/B/. �/sandbergii/  nm./fernaldii/.  


[Lepage  earlier papers mentioned here & hybrids:,/B. �neoborealis/:Naturaliste can. 84: 56-57, (1957)./B. �dutillyi:/Naturaliste can. 79: 124, (1952), (fig. 4).]

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 15:58Z]

neoborealis is now a syn., fide Lepage himself
