### ISSUE TITLE
range of Betula x eastwoodae

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1686]
[Originally posted on GoogleCode (id 1659) on 2013-03-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3710

<b>What data are incorrect or missing?</b>
BC missing from range map

<b>What data are you expecting instead?</b>
BC should be included, according to Lepage

<b>If applicable, please provide an authoritative source.</b>
Lepage (p.l 225, 1976) lists specimens that he examined from BC, as well as SK &amp; NWT
&quot;Distribution: selon Dugle (1966) «Alberta and north into Mackenzie District, Northwest Ter ritories, Yukon and Alaska». Nous en avons aussi examiné des endroits suivants: 

COLOMBIE BRITANNIQUE: Nicola. June 29, 1937, E.W. Tisdale 6432 (UBC, sub B. occidentalis). — Kootenay Riv., prairie N. of Kimberley, Sept. 7, 1950, V.C. Brink 50-90 (UBC, sub 8. Occidents- lis). — Big Bar Road, Aug. 2, 1953, V.C. Brink, s.n. (UBC, no d'herb. 121352). — 2.7 mi. from McGrath Ave, on road up Sabine ML, Aug. 26, 1970, J. Maze 680 (UBC, sub B. occidentslis).&quot;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 15:59Z]

Nunavut added to range fide Lepage (at limit with MB)
