### ISSUE TITLE
range of Betula x dutillyi

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1687]
[Originally posted on GoogleCode (id 1660) on 2013-03-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3709

<b>What data are incorrect or missing?</b>
N.S. missing from range map

<b>What data are you expecting instead?</b>
add N.S. to map, if ID is correct of specimen below

<b>If applicable, please provide an authoritative source.</b>
Lepage (p. 226, 1976 lists a specimen from NS:
&quot;NOUVELLE-ECOSSE: Twin Island Lake, Ingonish Barrens, Victoria Co., July 23, 1951, Smith, Scho field, Sampson &amp; 8enf 4623 (RIM, sub B. glandulosa. &quot;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-22 20:07Z]

What is the full ref of the Lepage paper? Not the one where he published the name, is it?

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-22 20:49Z]

Lepage, E., 1976.  Les Bouleau Arbustifs du Canada et de l'Alaska. Naturaliste canadien. Vol 103: 215-233.
4 new hybrids are described: 4 nouveaux: B. ×dugleana, B. ×ungavensis, B. ×minor et B. ×sandbergii nm. fernaldii.
