### ISSUE TITLE
Achillea millefolium subsp. millefolium

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#169]
[Originally posted on GoogleCode (id 1427) on 2012-10-04]

Dans la version « Administration » de VasCan, la sous-espèce Achillea millefolium subsp. millefolium n'est pas mentionnée. Est-ce normal?

J'ai toujours cru que la sous-espèce typique était présente au Canada en plus de la subsp. lanuginosa.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-17 15:53Z]

J'aimerais qu'on cesse de mentionner ce cas. J'ai un problème à cause d'un nom non existant encore (ou peut-être que si, mais il faut que je valide).

Une fois réglé, je n'aurai pas besoin d'une subsp. millefolium.

Problème connu. Je ferme cette fenêtre (il y avait déjà une entrée).

Luc
