### ISSUE TITLE
parentage of NL specimens of Betula xsandbergii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1691]
[Originally posted on GoogleCode (id 1665) on 2013-03-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3715

<b>What data are incorrect or missing?</b>
The parents of B. sandbergii are listed as B. papyrifera and B. pumila subsp. glandulifera

<b>What data are you expecting instead?</b>
Since NL does not have B. pumila subsp. glandulifera, species described as B. sandbergii from NL should be reviewed.
Lepage lists specimens from NL as a cross of P. papyrifera x P. pumila subsp. pumila, so another name for eastern specimens should be used, ?possibly Betula ×borggreveana Zabel ex H.J.P.Winkler (1904).  

<b>If applicable, please provide an authoritative source.</b>
Lepage (1967) lists B. xsandbergii nothomorph. fernaldii from NL, with the following parentage:
B. papyrifera x B. pumla var. pumila. Synonyms include Betula ×berggreveana Zabel. [See note below [Betula ×borggreveana 1904]

Lepage (1976, pg.230) for B. xsandbergii nothomorph. fernaldii 
TERRE-NEUVE: Bateau Barens, four miles north of Bellburn, 22 June 1969, G. Argus &amp; G. McPherson 7198 (CAN, sub B. fontinalis). — Blomidon Mountains, Aug. 20, 1910, Fernald &amp; Wiegand 3246 (CAN). 

Betula ×sandbergii Britton fut publié en mars 1904 et B. ×berggreveana* en juin de la même année et les deux ont pour parents les mêmes espèces. C'est la raison de l'alignement ici proposé. 
*Note: B. ×berggreveana is listed in IPNI &amp; Tropicos as B. ×borggreveana Zabel ex H.J.P. Winkler. (1904)
http://www.buchholznursery.com/plant_page.html?id=26de58

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 18:49Z]

This is a repeat of an earlier query. Please do not do new queries of old issues. Check before.

I have not had time to do all these corrections that require more research, like finding what other names might be involved.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 15:49Z]

Lepage's decision to use the same nothotaxon because the species involved were the same did not take into account the fact that the vars. involved on the pumila side differed. We will be using the new name.

The distr. will include NB as well as NF.

This leaves entire the question of the report from Labr. of xsandbergii by Lepage 76, even as he was not including LB as part of the range of var. glandulifera (particularly not from Goose Bay!). Would you agree that the Labr. report is really the berggr. nothotaxon?

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-04-05 16:30Z]

Luc, when you say "We will be using the new name. "  What name do you 
mean?  Is there a new nothotaxon for
Betula papyrifera x B. pumila var. pumila?

If there is a new name, I agree, NB should be included with NL in it's 
range.

I also saw the report of B. xsandbergii from Labr. by Lepage 76, but I 
assumes this was a mis-ID, as we had this listed as excluded from LB in 
our NF checklist;
butI don't know what your note below means: berggr.?? [nothotaxon]; just 
a typo? or am I missing something?

Perhaps Lepage's Betula xungavensis actually belongs here too, if Lepage 
misIDed the proposed parent as B. nana exilis rather than B. pumila 
pumila?  Have you ever had an opportunity to see this specimen?
