### ISSUE TITLE
range of Betula x winteri

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1692]
[Originally posted on GoogleCode (id 1666) on 2013-03-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3718

<b>What data are incorrect or missing?</b>
Range of Betula x winteri Dugle

<b>What data are you expecting instead?</b>
In addition to SK, the following provinces are listed in Lepage (1976, p.232) - as reported by Dugle (1966): AB, MB, NWT

<b>If applicable, please provide an authoritative source.</b>
Lepage 1976 and Dugle 1966

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 15:14Z]

I did not add Yukon as reported in Lepage 76 because no specimen is cited and it is not in Dugle 66. 
Needs confirmation

Luc
