### ISSUE TITLE
range of Betula x eastwoodae

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1694]
[Originally posted on GoogleCode (id 1668) on 2013-03-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3710

<b>What data are incorrect or missing?</b>
range of Betula x eastwoodae does not include BC.

<b>What data are you expecting instead?</b>
In addition to AB, SK, &amp; NWT, Lepage (1976, p. 225) reports specimens from BC:
COLOMBIE BRITANNIQUE: Nicola. June 29, 1937, E.W. Tisdale 6432 (UBC, sub B. occidentalis). — Kootenay Riv., prairie N. of Kimberley, Sept. 7, 1950, V.C. Brink 50-90 (UBC, sub B. occidentalis). — Big Bar Road, Aug. 2, 1953, V.C. Brink, s.n. (UBC, no d'herb. 121352). — 2.7 mi. from McGrath Ave, on road up Sabine ML, Aug. 26, 1970, J. Maze 680 (UBC, sub B. occidentalis). 

<b>If applicable, please provide an authoritative source.</b>
Lepage, E., 1976.  Les Bouleau Arbustifs du Canada et de l'Alaska. Naturaliste canadien. Vol 103: 215-233.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 15:54Z]

Lepage also mentions Nueltin Lake, Keewatin, which is now Nunavut. Though the lake straddles the MB-NU border, the location appears within NU
