### ISSUE TITLE
English common name for Alchemilla xanthochlora

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1695]
[Originally posted on GoogleCode (id 1669) on 2013-03-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9699

<b>What data are incorrect or missing?</b>
English common name missing

<b>What data are you expecting instead?</b>
intermediate lady's mantle
also, yellowgreen lady's mantle is used in German language sites

<b>If applicable, please provide an authoritative source.</b>
&lt;http://www.floralimages.co.uk/page.php?taxon=alchemilla_xanthochlora,1&gt; 
&lt;http://www.ukwildflowers.com/Web_pages/alchemilla_xanthochlora_intermediate_ladys_mantle.htm&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:25Z]

Marilyn: please see to it
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-18 10:41Z]

completed with suggested additions
