### ISSUE TITLE
authority of a 2nd synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1697]
[Originally posted on GoogleCode (id 1671) on 2013-03-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8601

<b>What data are incorrect or missing?</b>
Eupatorium gryposepalum (Wallroth) Nieuwland

<b>What data are you expecting instead?</b>
Eupatorium gryposepalum (Wallroth) Lunell (1918, 1919)

<b>If applicable, please provide an authoritative source.</b>
I know Nieuwland has published other Agrimonia names in 1915, so the name you have may be correct, but I can't find it on IPNI, Tropicos, or other taxonomic database.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:22Z]

But he would not have published under Eupatorium...
the name by Lunell is illeg. fide TRO
