### ISSUE TITLE
missing common names

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1702]
[Originally posted on GoogleCode (id 1679) on 2013-03-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/24815

<b>What data are incorrect or missing?</b>
no common names listed

<b>What data are you expecting instead?</b>
Chinese bearberry, bearberry cotoneaster; 
Fr: cotonéaster de Dammer or cotonéastre de Dammer 

<b>If applicable, please provide an authoritative source.</b>
http://nature.jardin.free.fr/1105/cotoneaster_dammeri.html
Marc, I don't know if you've seen this website yet; they have a good 
selection of garden species with French and English common names:
Jardin! L'Encyclopédie
Homepage: http://nature.jardin.free.fr/

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:14Z]

Marc and Marilyn: svp ajouter les vernaculaires
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-30 21:01Z]

J'ai ajouté les 2 noms français suggérés, mais en utilisant d'autres sources figurant déjà dans notre liste de références.
TelaBotanica propose "cotonéaster de Damner" (au lieu de "Dammer"), mais il s'agit sûrement d'une erreur, car Schneider (1906) fait référence à un herborisateur appelé "Dammer".

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-05-01 03:21Z]

I agree, Marc, Damner is likely a typo.  Thanks.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-01 18:46Z]

English vernaculars are the only information left to be added
Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 21:40Z]

completed
