### ISSUE TITLE
typo in authority of species name; English common name missing

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1704]
[Originally posted on GoogleCode (id 1681) on 2013-03-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9689

<b>What data are incorrect or missing?</b>
Cotoneaster dielsianus E. Pritz ex Diels
English common name missing

<b>What data are you expecting instead?</b>
Cotoneaster dielsianus E. Pritzel ex Diels
Diels' cotoneaster

<b>If applicable, please provide an authoritative source.</b>
IPNI: authority: E.Pritz. ex Diels
IPNI Authors:
    E.Pritz. - Ernst Georg Pritzel 1875-1946
    Pritz. - George August Pritzel 1815-1874

English common name: http://calphotos.berkeley.edu/cgi/img_query?stat=BROWSE_IMG&amp;query_src=photos_browseimgs_plant_com&amp;where-genre=Plant&amp;where-namesoup=Cotoneaster&amp;rel-namesoup=matchphrase&amp;title_tag=Cotoneaster

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:12Z]

Typo fixed

Marilyn: please deal with vernacular
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 21:22Z]

English vernacular entered, thanks
