### ISSUE TITLE
missing English common names

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1706]
[Originally posted on GoogleCode (id 1683) on 2013-03-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9682

<b>What data are incorrect or missing?</b>
English common names missing

<b>What data are you expecting instead?</b>
Parney's cotoneaster, late cotoneaster, or milkflower cotoneaster

<b>If applicable, please provide an authoritative source.</b>
	&lt;http://www.cal-ipc.org/ip/management/plant_profiles/Cotoneaster_lacteus.php&gt; 
	&lt;http://www.pnwplants.wsu.edu/PlantDisplay.aspx?PlantID=69&gt; 
	&lt;http://apps.rhs.org.uk/plantselector/plant?plantid=565&gt; 
	&lt;http://plants.usda.gov/java/profile?symbol=COLA18&gt; 
	&lt;http://nature.jardin.free.fr/1108/cotoneaster_lacteus.html&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:11Z]

Marilyn: please see to it.
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 21:13Z]

completed - thanks
