### ISSUE TITLE
typo in sp. epithet of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1708]
[Originally posted on GoogleCode (id 1685) on 2013-03-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8648

<b>What data are incorrect or missing?</b>
Mespilus racimiflora Desfontaines

<b>What data are you expecting instead?</b>
Mespilus racemiflora Desfontaines

<b>If applicable, please provide an authoritative source.</b>
IPNI and: http://www.efloras.org/florataxon.aspx?flora_id=1130&amp;taxon_id=242421636
Tropicos has it misspelled.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-03-31 18:37Z]

This website (Xycol) has lists of common names & synonyms:
http://82.67.101.128/index.php?categorie=200&op=fiche&appellation_nsr=Cotoneaster+racemiflorus+%28Desf.%29+K.+Koch%2C+1869&appellation=Cotoneaster+racemiflorus&appellation_id=35248&via=rechercheappellation&introspect=ok

blackwood and redbead cotoneaster are 2 English common names given; they also use cotonéaster sauvage as the French common name, maybe Marc would like to add this as a syn?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:10Z]

Fixed

Marc: suggestion de Sue?

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:41Z]

I cannot find any other source associating the name « cotonéaster sauvage » to Mespilus racemiflora or Cotoneaster racemiflorus, while it is the recommended (TelaBotanica) and widely used (Google) French name for Cotoneaster integerrimus (not in Canada, but reported from France).

It might be an error, and the name is rather unspecific.

For those reasons, I would not add it as a synonym, until it can be confirmed from other sources.

Thank you however for this interesting source of names

Marc
