### ISSUE TITLE
validity of specie name Cotoneaster simonsii or C. symondsii? 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1709]
[Originally posted on GoogleCode (id 1686) on 2013-03-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8649

<b>What data are incorrect or missing?</b>
Cotoneaster simonsii Baker

<b>What data are you expecting instead?</b>
?Cotoneaster symondsii T.Moore

<b>If applicable, please provide an authoritative source.</b>
[Dickor &amp; Kasperek, 2010. Species of Cotoneaster (Rosaceae, Maloideae) indeigenout to, naturalizeing or commonly cultivated in Central Europe. Willdenowia 40:13-45] 
http://user.uni-frankfurt.de/~kasperek/papers/dickore_kasperek_2010.pdf

At the end of page 24 (of 33 pp in the pdf) of the above article, 
the authors accept the name C. symondsii T.Moore (1861) over T. simonsii Baker (1869).  This may not agree with FNA ms, but I don't know if the FNA authors have considered this info.

&quot;As Kumar &amp; Panigrahi (1992) have pointed out, on the basis of priority, Cotoneaster symondsii T. Moore replaces the later synonym C. simonsii Baker. Moore’s name was effectively published in a journal and accompanied by a description. It does not matter that, contrary to Baker’s protologue of C. simonsii, his description is not in Latin and is lacking an illustration.  Orthography cannot be corrected, since there is no unequivocal indication as to whom Moore intended to commemorate (possibly,P.L. Simmonds, or, as for Baker’s name,C. J. Simons;kumar &amp;panigrahi 1992.&quot;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:07Z]

Since we are final-editing the Rosaceae, this is timely. I will have to check what has been done. It may have been corrected from the draft. I am not sure.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 18:39Z]

Cotoneaster symondsii T. Moore has priority as they are the same taxon
fide K. Gandhi
