### ISSUE TITLE
Accepted English Name for Lupinus arbustus

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#171]
[Originally posted on GoogleCode (id 1806) on 2013-06-28]

Marilyn,

In VasCan, the accepted name is &quot;long-spurred lupine&quot;, while &quot;spurred lupine&quot; is given as a synonym. I believe the two should be reversed, since the species' main character is the presence of a short spur at the base of the calyx, as opposed to no spur at all in other species of Lupinus (Illustrated Flora of BC 3, p. 120, where the name &quot;spurred lupine&quot; is used for the species as a whole). I would think the name &quot;long-spurred lupine&quot; is a misnomer.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-07-23 18:06Z]

Many thanks Marc, I agree. I'll be reviewing all of the genus Lupinus soon!
(I just placed the VernacularEN label, so when I sort on issues, it comes up).

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-07-25 20:08Z]

yes I'll change to 'spurred lupine' although the other name is very much in use as well. Finished a review of all of the Lupinus.
Thanks again for your input
