### ISSUE TITLE
incorrect synonym for Crataegus margarettae var. angustifolia

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1710]
[Originally posted on GoogleCode (id 1687) on 2013-03-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/23980

<b>What data are incorrect or missing?</b>
Crataegus angustifolia E.J. Palmer

<b>What data are you expecting instead?</b>
delete synonym?

<b>If applicable, please provide an authoritative source.</b>
I can't find any reference to Palmer making a new combination of is var. angustifolia, but IPNI has a Crataegus angustifolia (Ehrh.) Borkh., which does not seem to be the same taxon.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-24 19:22Z]

Sue

This is a repeat of an issue first sent by Oldham.

Name removed now because it is inexistant (it has been removed from FNA ms during editing)
