### ISSUE TITLE
authority of synonym - missing basionym author

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1713]
[Originally posted on GoogleCode (id 1690) on 2013-04-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8692

<b>What data are incorrect or missing?</b>
Crataegus coccinea var. macrantha Dudley

<b>What data are you expecting instead?</b>
Crataegus coccinea var. macrantha (Loddiges ex Loudon) Dudley

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI mentions the basionym

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:03Z]

I guess it is macracantha, too
