### ISSUE TITLE
missing English common name for Crataegus populnea

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1716]
[Originally posted on GoogleCode (id 1693) on 2013-04-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8709

<b>What data are incorrect or missing?</b>
missing English common name

<b>What data are you expecting instead?</b>
poplar hawthorn, Grubner's hawthorn

<b>If applicable, please provide an authoritative source.</b>
poplar hawthorn from New England Bot Soc:
http://gobotany.newenglandwild.org/species/crataegus/populnea/
Grubner's hawthorn from Britton &amp; Brown (Dover edition)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 19:00Z]

Marilyn: please handle this.
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 19:53Z]

completed but I still need to figure out how to cite the New England Wildflower Society.
