### ISSUE TITLE
incorrect authority for entry variety

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1717]
[Originally posted on GoogleCode (id 1694) on 2013-04-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8670

<b>What data are incorrect or missing?</b>
Crataegus pruinosa var. dissona (Sargent) J.B. Phipps (2007)

<b>What data are you expecting instead?</b>
Crataegus pruinosa var. dissona (Sargent) Eggleston (1908)

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 18:59Z]

I have to check: there may be a reason for the Phipps 2007 name (or not)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-24 20:53Z]

it has been changed in the FNA ms and is now correct - also corrected in VASCAN
