### ISSUE TITLE
Présence double de Physalis ixocarpa

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#172]
[Originally posted on GoogleCode (id 2179) on 2014-04-10]

Le Physalis ixocarpa est mentionné comme nom accepté d'espèce, avec une seule occurrence, douteuse, en Saskatchewan. Le taxon est aussi mentionné dans une autre fiche, comme synonyme du P. philadelphica var. immaculata, avec des occurrences à titre de taxon introduit dans plusieurs provinces, mais non en Saskatchewan.

Je suppose que la fiche ayant le P. ixocarpa comme nom accepté d'espèce peut être éliminée, et la mention douteuse pour la Saskatchewan peut sans doute être transférée au P. philadelphia var. immaculata.

Je ne m'appuie sur aucune source particulière. C'est une question de cohérence interne.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-24 18:19Z]

Marc

Tu soulignes un bon problème, mais il y a une subtilité ici:
le nom utilisé pour la Sask. est Physalis ixocarpa Brotero ex Hornemann
le nom utilisé en syn est un nom sensu: Physalis ixocarpa auct. non Brotero ex Hornemann

Le problème qui se pose à moi est ceci: le rapport de Sask devrait-il aussi se fonder sur auct. non? Je ne peux résoudre cela facilement

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-04-24 18:51Z]

En effet, il est théoriquement possible, bien qu'improbable, que le vrai P. ixocarpa ait été observé en Saskatchewan, alors que c'est le P. philadelphica qui a été observé dans la plupart des autres provinces. On oublie ça pour l'instant. Merci de ta réponse.
