### ISSUE TITLE
issue with common English name for Anemone virginiana var. alba

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1723]
[Originally posted on GoogleCode (id 1700) on 2013-04-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8442

<b>What data are incorrect or missing?</b>
Virginia anemone as accepted name

<b>What data are you expecting instead?</b>
riverbank anemone - more appropriate common name, given Fernald's synonym Anemone riparia, for this variety.  Also, this variety does not ever occur in Virginia, so that's a misnomer.

<b>If applicable, please provide an authoritative source.</b>
http://www2.swgc.mun.ca/botany/generalplants/anemoneriparia.asp?&amp;info=general&amp;num=1&amp; 
http://www.florelaurentienne.com/flore/Groupes/Spermatophytes/Angiospermes/Dicotyles/033_Renonculacees/08_Anemone/riparia.htm

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-04 18:51Z]

Marilyn: could you please deal with this?

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 18:56Z]

completed English vernacular review for all Anemone virginiana and varieties
