### ISSUE TITLE
authoriy of species, synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1726]
[Originally posted on GoogleCode (id 1703) on 2013-04-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8448

<b>What data are incorrect or missing?</b>
a) Aquilegia jonesii C. Parry
b) Aquilegia jonesii var. elatior Boothman

<b>What data are you expecting instead?</b>
a) Aquilegia jonesii Parry
b) Aquilegia jonesii var. elatior (Standl.) Boothman  (1934)
   and Aquilegia jonesii subsp. Standl.  (1921)

<b>If applicable, please provide an authoritative source.</b>
a) IPNI authors
b) IPNI, Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 18:22Z]

a) fixed
b) TROPICOS does not have the basionym auth. for the var. but it is obvious it is needed
