### ISSUE TITLE
English common name spelling: travellers's vs traveler's

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1731]
[Originally posted on GoogleCode (id 1708) on 2013-04-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8466

<b>What data are incorrect or missing?</b>
traveler's joy

<b>What data are you expecting instead?</b>
traveller's joy

<b>If applicable, please provide an authoritative source.</b>
For consistency, I suggest you stick to either British or American spelling differences: colour vs color, metre vs metre, etc.  Traveller is another that falls into this category, with traveller being the US spelling.  This wiki article lists many of the differences:

http://en.wikipedia.org/wiki/American_and_British_English_spelling_differences#Doubled_consonants

Doubled consonants:
    The British English doubling is used for all inflections (-ed, -ing, -er, -est) and for the noun suffixes -er and -or. Therefore, British English usage is cancelled, counsellor, cruellest, labelled, modelling, quarrelled, signalling, traveller, and travelling. Americans usually use canceled, counselor, cruelest, labeled, modeling, quarreled, signaling, traveler, and traveling. 

Also, non US-websites use traveller's rather than travelers:
http://www.thefreedictionary.com/traveller%27s+joy
http://en.wikipedia.org/wiki/Clematis_vitalba
http://eol.org/pages/596256/overview

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 15:51Z]

Marilyn: please handle

I do not know what is preferred for Canada.

Marc: opinion?

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-05 16:39Z]

Canadian usage is more or less a blend American and British usages. We always write cheques, not checks as in the US, but we inflate tires, never tyres as until recently in the UK. We have research centres as they do in Britain, while the Americans have centers.

As far doubling the consonants or not is concerned, both usages are considered correct in Canada according to my favorite Canadian dictionnary (Gage's). However, in Gage's, the doubling option is given first, and it is systematically used in the examples.

I would vote for "traveller's joy", hey.

Of course, this type of rule would apply only to "accepted" names. Synonyms should be whatever the sources say.

Marc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-04-05 16:52Z]

Yes, I agree, it's not alway clearcut, and since I'm originally from the 
US, I often get mixed up on which one is accepted here.  I've taken to 
using -re's rather that '-er's as endings, but the double letters are 
still a bit confusing. Thanks for your clarification, Marc.  I'll have 
to get a copy of Gage's.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 18:05Z]

many thanks for noticing this and your input. Yes aiming for Canadian spelling and usage.
