### ISSUE TITLE
question about authority of synonym; also 1 illeg. tautonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1733]
[Originally posted on GoogleCode (id 1710) on 2013-04-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8464

<b>What data are incorrect or missing?</b>
a) Clematis viorna var. flaccida (Small ex Rydberg) R.O. Erickson
   and Viorna flaccida (Small ex Rydberg) Small

b) Viorna viorna (Linnaeus) Small

<b>What data are you expecting instead?</b>
a) IPNI &amp; FNA have Small ex Rydb. as the basionym authority (re: Clematis flaccida Small ex Rydb.), but Tropicos has Small, published in Britton, so I'm not sure which is correct

b) Viorna viorna (Linnaeus) Small, nom. illeg. tautyonym  {see Tropicos}

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos, FNA

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 17:41Z]

b) fixed

**Comment by brouille** [comment]
a) both TRO and IPNI have now have Small ex Rydb.
and it was published in Britton's Manual according to both sources
No change required to VASCAN
