### ISSUE TITLE
Synonyme à ajouter

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#174]
[Originally posted on GoogleCode (id 2182) on 2014-04-24]

Sous Corispermum villosum, il serait bon d'ajouter le synonyme Corispermum hyssopifolium var. emarginatum (Rydb.) B. Boivin

Ce synonyme est utilisé comme nom accepté dans Darbyshire et al. 2003

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-24 18:13Z]

ajouté avec TROPICOS comme réf. - c'est un synonyme immédiat d'autres synonymes
