### ISSUE TITLE
authority abbreviation of varieties

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1740]
[Originally posted on GoogleCode (id 1717) on 2013-04-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8490
http://data.canadensys.net/vascan/taxon/8492

<b>What data are incorrect or missing?</b>
Myosurus apetalus var. borealis A.T. Whittemore
Myosurus apetalus var. montanus (G.R. Campbell) A.T. Whittemore

<b>What data are you expecting instead?</b>
Myosurus apetalus var. borealis Whittemore
Myosurus apetalus var. montanus (G.R. Campbell) Whittemore

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 13:27Z]

Remnants of when we were adding all initials...
TX
