### ISSUE TITLE
missing English common names for Rubus arcticus subsp. stellatus

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1742]
[Originally posted on GoogleCode (id 1719) on 2013-04-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8924

<b>What data are incorrect or missing?</b>

<b>What data are you expecting instead?</b>
nagoonberry, Alaskan raspberry, arctic blackberry

<b>If applicable, please provide an authoritative source.</b>
GRIN, USDA, also these websites:
&lt;http://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Rubus%20arcticus%20ssp.%20stellatus&gt; 

&lt;http://eol.org/pages/6171057/overview&gt; 
EOL uses the name dwarf nagoonberry, but this seems to used on the web mainly for subsp. acaulis:
http://natureofthehills.wordpress.com/tag/dwarf-nagoonberry/

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 13:28Z]

Marilyn:

Please add vernaculars for this name.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 21:15Z]

completed
