### ISSUE TITLE
issue with common English name for subsp. arcticus

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1743]
[Originally posted on GoogleCode (id 1720) on 2013-04-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8923

<b>What data are incorrect or missing?</b>
English common name: plumboy is a Newfoundland name, so not appropriate for subsp. arcticus

<b>What data are you expecting instead?</b>
delete plumboy from the names for subsp. arcticus; 
keep for subsp. acaulis and the species Rubus arcticus

<b>If applicable, please provide an authoritative source.</b>
Meades et al. checklist and Dictionary of Newfoundland English

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 13:30Z]

Marilyn

Please deal with this.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 21:14Z]

completed
