### ISSUE TITLE
queston about common name Rubus millspaughii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1744]
[Originally posted on GoogleCode (id 1721) on 2013-04-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8927

<b>What data are incorrect or missing?</b>
Millspaugh's blackberry is listed as an English common name (syn),
but Rubus millspaughii Britton is not listed in synonymy.

<b>What data are you expecting instead?</b>
If Rubus millspaughii Britton is not a synonym of R. canadensis, 
move the common name 'Millspaugh's blackberry' to the appropriate species. 
If Rubus millspaughii is a syn. of R.canadensis, please add it.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 13:40Z]

The FNA ms does not deal with  Rubus millspaughii Britton, so I do not know whether it is a syn of canadensis or not.

I do not know why Millspaugh's blackberry was added as a vernacular syn: there is no ref. after the name.

Marilyn: is there a reason why this vernacular should be kept under canadensis?

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 20:43Z]

yes, Britton & Brown's original English name and listed synonym
