### ISSUE TITLE
question about English common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1746]
[Originally posted on GoogleCode (id 1723) on 2013-04-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8928

<b>What data are incorrect or missing?</b>
Jones' berry as an English common name

<b>What data are you expecting instead?</b>
Delete Jones' berry

<b>If applicable, please provide an authoritative source.</b>
I've never found Jones' berry in any internet search, other than in reference to a lemonade soda company.  There is also no source given
for this name.  It seems too obscure to list here. Britton &amp; Brown and the CAA flora list other common names, but not Jones' berry.  I suggest it be excluded.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 13:41Z]

Marilyn:

Please handle.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 20:08Z]

completed
