### ISSUE TITLE
issue with common English name for subsp. strigosus

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1748]
[Originally posted on GoogleCode (id 1725) on 2013-04-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8934

<b>What data are incorrect or missing?</b>
Common name European red raspberry inappropriate for native North American subsp.

<b>What data are you expecting instead?</b>
European red raspberry should refer to Rubus idaeus subsp. idaeus; subsp. strigosus is native to North America, while subsp. idaeus is European.
If all the garden raspberries are cultivars of subsp. idaeus, this name should be kept also for subsp. idaeus.

Also, the name grayleaf raspberry (gray-leaved) raspberry is often used for subsp. strigosus, but is not listed here.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 13:44Z]

Marilyn:

The problem is not only with the native taxon but also with the introduced European red raspberry: you provide apparently the same list of vernaculars to both, or at least, American red raspberry is erroneous under the introduced subsp.

Please untangle and correct.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 20:31Z]

English vernaculars fixed. Perhaps the French name of 'ronce du mont Ida' should also be removed on the ssp. strigosus name list - Marc?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-12 12:39Z]

Marc
Apparamment, Marilyn a oublié que tu n'étais pas en cc de ce problème.

Il me semble en effet que le nom souligné par Marilyn ne devrait pas être rattaché aux deux subspp.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-06-12 20:58Z]

J'ai corrigé les noms français, en ne conservant que les noms acceptés pour chacune des sous-espèces et en transférant à l'espèce les divers synonymes.

Done, je pense.

Marc
