### ISSUE TITLE
issue with common English name for subsp. idaeus

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1749]
[Originally posted on GoogleCode (id 1726) on 2013-04-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8932

<b>What data are incorrect or missing?</b>
wild red raspberry &amp; American red raspberry

<b>What data are you expecting instead?</b>
wild red raspberry &amp; American red raspberry refer to subsp. strigosus, not subsp. idaeus

<b>If applicable, please provide an authoritative source.</b>
GRIN uses American red raspberry for Rubus strigosus, which they recognize as a distinct species; and European red raspberry for R. idaeus.
Tropicos lists wild red raspberry under var. strigosus.
I know that USDA has American red raspberry as the common name for subsp. idaeus, but they also note that it's introduced in the US, so this seems like an obvious error.

Other names: http://www.fs.fed.us/database/feis/plants/shrub/rubida/all.html

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 13:45Z]

see previous item

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 20:28Z]

thanks for helping to get this sorted out
