### ISSUE TITLE
Accepted English name for Oxytropis sericea

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#175]
[Originally posted on GoogleCode (id 2188) on 2014-05-06]

The accepted English name « white locoweed » can apply only to subsp. sericea, which is not reported from Canada. Only subsp. spicata is reported in Canada, and it has yellow flowers.

So I would think another accepted English name is required for Oxytropis sericea at the species level. In French, I used « oxytrope hâtif », since both subsp. are characteristically early flowering. You may want to consider « early locoweed », or pick among the existing synonyms that do not refer to the white flowers.

However, the synonym « silky locoweed » cannot be used as the accepted name, because it is already the accepted name for a different taxon, i.e. O. deflexa var. sericea.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-05-13 20:49Z]

Hi, thanks for your suggestion Marc, which I used. I tried to review this across Canada and the U.S. for various names. What a mix of vernaculars over many taxa! I'll have to review again after the treatment is out, as most likely there will be more changes to be made throughout the Oxytropis.
