### ISSUE TITLE
2 synonyms of same taxa listed under different Rubus species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1753]
[Originally posted on GoogleCode (id 1730) on 2013-04-07]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8945
http://data.canadensys.net/vascan/taxon/8923

<b>What data are incorrect or missing?</b>
Rubus alaskensis L.H.Bailey is listed as a synonym of Rubus arcticus subsp. arcticus
but Rubus pubescens Raf. var. alaskensis (L.H.Bailey) B.Boivin is listed as a synonym of Rubus pubescens

<b>What data are you expecting instead?</b>
Should both of these be synonymous with R. arcticus subsp. arcticus?

<b>If applicable, please provide an authoritative source.</b>
re: your issue #660

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 12:57Z]

Good catch.

There is the further issue that this name may be a hybrid of arcticus and idaeus or other Rubus sp. and thus should not be synonymized under arcticus, though FNA ms does this. I need to query the authors.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 18:14Z]

I am removing alaskensis from syn in both placese (the taxon could be a hybrid and its disposition is uncertain)

with respect to the name alaskensis itself, here is what G. Moore, a co-author of Rubus in FNA, wrote:

 I can confidently conclude that I am not confident regarding the taxonomic placement of Rubus alaskensis, and, therefore, am certain about the doubt we expressed regarding this taxon.
  My initial reaction is that the listing of this name as a synonym under R. arcticus subsp. arcticus should be removed (although I like Tropicos’s approach to indicating doubt by confidently referring it as a species and hybrid at the same time). I assume this simple change can be made when we get the proofs.
