### ISSUE TITLE
Question about varieties of Viburnum opulus subsp. trilobum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1755]
[Originally posted on GoogleCode (id 1732) on 2013-04-07]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2453

<b>What data are incorrect or missing?</b>
Viburnum opulus subsp. trilobum has only 1 variety listed (var. americanum)

<b>What data are you expecting instead?</b>
I haven't seen the Viburnum FNA ms, so, are there other varieties of this North American subsp.?  
If not, why are varieties recognized if var. americanum is the same as subsp. trilobum - just recognized at a different level? 
If the subsp. were geographically based: old world (subsp. opulus) vs. new world (subsp. trilobum), and if there is a var. americanum, shouldn't there be a var. trilobum?  

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
Vibrunum FNA ms entered now and issue resolved
