### ISSUE TITLE
missing common name for Rosa nutkana subsp. macdougalii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1757]
[Originally posted on GoogleCode (id 1735) on 2013-04-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8902

<b>What data are incorrect or missing?</b>
no English common name for Rosa nutkana subsp. macdougalii

<b>What data are you expecting instead?</b>
MacDougal's rose, bristly Nootka rose

<b>If applicable, please provide an authoritative source.</b>
MacDougal's rose - LeRoy Abrams et al. Ill. Flora of Pacific States: Polygonaceae-Krameriaceae. pg. 459
http://books.google.ca/books?id=Md_4wQqO5uQC&amp;pg=PA462&amp;lpg=PA462&amp;dq=Rosa+nutkana+macdougalii&amp;source=bl&amp;ots=aM60R0J42v&amp;sig=NtyLLKCQmoXy1sUUDyYqPe2Yi2A&amp;hl=en&amp;sa=X&amp;ei=DiRkUfvmBsLD4AOh9IHQCg&amp;redir_esc=y#v=onepage&amp;q=Rosa%20nutkana%20macdougalii&amp;f=false

bristly Nootka rose - USDA Plants

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-10 19:18Z]

Marilyn: your domain.
Luc

(NOte that I am trying to vary my injunction)

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 20:00Z]

completed
