### ISSUE TITLE
status of species name: Rosa cinnamomea

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1759]
[Originally posted on GoogleCode (id 1737) on 2013-04-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8893

<b>What data are incorrect or missing?</b>
Rosa cinnamomea Linnaeus

<b>What data are you expecting instead?</b>
?Rosa majalis

<b>If applicable, please provide an authoritative source.</b>
Tropicos has Rosa majalis Herrmann as the accepted name of Rosa cinnamomea L.
 while GRIN and Index Synonymique have 
Rosa cinnamomea L. = Rosa pendulina L. (alpine rose)
Rosa cinnamomea auct. = Rosa majalis Herrmann (cinnamon rose)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-10 20:34Z]

thorny - this is more than mere nomenclature

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-12 14:02Z]

This results from the recent conservation of the type of Rosa on R. cinnamomea (J. McNeill et al. 2006, App. IIIA) {from FNA ms}

If the type of Rosa is cinnamomea, I can hardly see that this sp. would be reduced in syn. of other spp. And the Rosa cinnamomea introduced here is the L. taxon, not auct.

I will not make this change.

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-04-12 15:22Z]

Fine with me.  GRIN is often up to date on the nomenclature of cultivated species, but I wasn't sure with the Roses.
