### ISSUE TITLE
Additional English names for Erysimum capitatum var. purshii

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#176]
[Originally posted on GoogleCode (id 2234) on 2014-07-09]

Marilyn,

The name « Dawson wallflower » is used in the USDA PLANTS database, while « narrow-leaved wallflower » is used by the COSEWIC (http://www.cosewic.gc.ca/eng/sct1/searchdetail_e.cfm?id=490&amp;StartRow=1&amp;boxStatus=All&amp;boxTaxonomic=All&amp;location=All&amp;change=All&amp;board=All&amp;commonName=&amp;scienceName=erysimum%20angustatum&amp;returnFlag=0&amp;Page=1), in both cases for the species Erysimum angustifolium Rydb., which is now considerered part of E. capitatum var. pushii in FNA (and VasCan)[not to be confused with the Californian E. capitatum var. angustatum (Greene) Rossbach, which is now part of var. capitatum].

You may want to add the names « Dawson wallflower » and « narrow-leaved wallflower » as English synonyms for E. capitatum var. purshii.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-07-17 18:21Z]

Many thanks Marc, I've incorporated your suggestions. Please indicate with the label Vernacular English so I can find easily in the issues by sorting on that label.
