### ISSUE TITLE
missing English common name for Drymocallis pseudorupestris var. saxicola

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1763]
[Originally posted on GoogleCode (id 1741) on 2013-04-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8820

<b>What data are incorrect or missing?</b>
missing English common names for Drymocallis pseudorupestris var. saxicola

<b>What data are you expecting instead?</b>
cliff woodbeauty, cliff drymocallis, and/or Rocky Mountain sticky cinquefoil 

<b>If applicable, please provide an authoritative source.</b>
See: 	&lt;http://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Drymocallis%20pseudorupestris&gt; 
	&lt;http://biology.burke.washington.edu/herbarium/imagecollection.php?ID=3852&gt; 
	&lt;http://science.halleyhosting.com/nature/basin/5petal/rose/cinquefoil/glandulosa/pseudorupestris/pseudorupestris.htm&gt; 
	&lt;http://www.calflora.org/cgi-bin/species_query.cgi?where-taxon=Drymocallis+pseudorupestris+var.+saxicola&gt; 
	&lt;http://web.ewu.edu/ewflora/Rosaceae/Drymocallis%20pseudorupestris.html&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-10 19:17Z]

Marilyn: one more for you.
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 19:52Z]

completed
