### ISSUE TITLE
Question about rank of entry: subsp. groenlandica

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1764]
[Originally posted on GoogleCode (id 1742) on 2013-04-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
Question about status of subsp. rank

<b>What data are incorrect or missing?</b>
Potentilla anserina subsp. groenlandica Trattinnick
Potentilla anserina  var.  groenlandica Trattinnick

<b>What data are you expecting instead?</b>
IPNI and Tropicos list this taxon at the var. rank but don't list a subsp. entry. Publication info Rosacearum Monographia 4: 13. 1824. 

GRIN and the Panarctic Flora list this taxon at the subp. rank and don't include a var. entry.  The publication info is identical.  

If Trattinnick published both ranks at the same time, wouldn't sources list both ranks? If he only published one rank, shouldn't there be a new combination for the other rank?

<b>If applicable, please provide an authoritative source.</b>
Panarctic flora entry:
http://nhm2.uio.no/paf/641060c

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-04-10 14:05Z]

Sorry, copied the wrong think into the URL line.  
See: http://data.canadensys.net/vascan/taxon/8634

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-10 19:16Z]

The issue here is not whether Trattinick was the author of one or the other, but really what tax. level he was suggesting for his combination: var. or subsp.? Elven suggests, following Sojak, that Trattinik infrasp. were subsp. - the var. comb. would not exist then, I presume.

this requires input from Gandhi

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-12 19:02Z]

Gandhi: "P. anserina subsp. groenlandica Tratt.": OK;  on the validating page, NO rank is given, but in the preface (p. 19), the rank subsp. Is mentioned"

I am removing the var. - it does not exist
