### ISSUE TITLE
authority of subsp. and all combinations

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1765]
[Originally posted on GoogleCode (id 1743) on 2013-04-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8635

<b>What data are incorrect or missing?</b>
Potentilla anserina subsp. egedei (Wormskjöld) Hiitonen
Potentilla egedii Wormskjold 
Argentina anserina subsp. egedei (Wormskjöld) Á. Löve &amp; Ritchie
Argentina egedei (Wormskjold) Rydberg

<b>What data are you expecting instead?</b>
Potentilla anserina subsp. egedei (Wormskjöld ex Hornemann) Hiitonen
Potentilla egedii Wormskjold ex Hornemann
Argentina anserina subsp. egedei (Wormskjöld ex Hornemann) Á. Löve &amp; Ritchie
Argentina egedei (Wormskjold ex Hornemann) Rydberg

<b>If applicable, please provide an authoritative source.</b>
Tropicos &amp; GRIN has all the combinations with egedei (Wormsk. ex Hornem.)
http://www.tropicos.org/Name/27802377
IPNI lists both with and without the ex

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-10 19:12Z]

Again a case of ex.

Those are really bothersome because they need input by Gandhi to be solved for good.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-11 20:48Z]

Gandhi: P. egedei Wormsk. ex Hornem.: OK; I already checked this. (Note the epithet spelling with a single "i")
