### ISSUE TITLE
polygonum subsection polygonella is empty in VasCan

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#177]
[Originally posted on GoogleCode (id 2237) on 2014-07-16]

Dans la section Polygonum du genre Polygonum, il y a deux sous-sections, Polygonum et Polygonella, mais toutes les espèces sont placées dans la sous-section Polygonum.

Je crois que le Polygonum articulatum devrait être transféré à la sous-section Polygonella.

Je ne pense pas que ce soit le cas d'autres espèces, mais ça reste à vérifier.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-25 20:21Z]

C'était en effet une erreur

Luc
