### ISSUE TITLE
Missing English common name for Potentilla drummondii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1770]
[Originally posted on GoogleCode (id 1748) on 2013-04-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8810

<b>What data are incorrect or missing?</b>
missing English common name for Potentilla drummondii

<b>What data are you expecting instead?</b>
Drummond's cinquefoil

<b>If applicable, please provide an authoritative source.</b>
	&lt;http://biology.burke.washington.edu/herbarium/imagecollection.php?ID=3919&gt; 
	&lt;http://science.halleyhosting.com/nature/plants/5petal/rose/potentilla/drummondii.htm&gt; 
	&lt;http://www.calflora.org/cgi-bin/species_query.cgi?where-taxon=Potentilla+drummondii&gt; 
	&lt;http://plants.usda.gov/java/profile?symbol=PODR&gt; 
	&lt;http://www.pnwflowers.com/flower/potentilla-drummondii-ssp-breweri&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-10 18:59Z]

Marilyn: yours to handle.
Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 19:45Z]

getting through these!!!
