### ISSUE TITLE
authority of 1 synonym; 2nd synonym an illeg. hom.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1775]
[Originally posted on GoogleCode (id 1754) on 2013-04-11]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8847

<b>What data are incorrect or missing?</b>
Potentilla nivea var. pentaphylla Lehmann
Potentilla quinquefolia Rydberg

<b>What data are you expecting instead?</b>
Potentilla nivea var. pentaphylla Lehmann (1851), nom. illeg. [hom., non Turcz. (1843)
Potentilla quinquefolia (Rydberg) Rydberg  {1898)
basionym of this name: Potentilla nivea var. quinquefolia Rydberg {1896)

<b>If applicable, please provide an authoritative source.</b>
Tropicos; IPNI has the basionym as a syn.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-12 18:47Z]

Two other names that have been used periodically for American members of sect. x\Rubricaules are Potentilla nivea var. pentaphylla Lehmann and its substitute name P. quinquefolia Rydberg.  Although Lehmann’s combination is often treated as a later homonym of P. nivea var. pentaphylla Turczaninow (for example, J. Soják 1986), the two are better interpreted as isonyms with Turczaninow’s combination having priority (as done by T. Wolf 1908).  By current taxonomy (for example, S. Juzepczuk 1941; J. Soják, pers. comm.), Turczaninow’s type (hence also the type of P. quinquefolia) is a variant of P. altaica Bunge, endemic to central Asia.  Neither P. nivea var. pentaphylla nor P. quinquefolia, therefore, has any application in North America. 

Given this analysis by Ertter in her FNA ms, I believe it safer to remove these names (and other ambiguous names) from the synonymy.

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-04-13 13:18Z]

Thanks!  Will remove them from our dB also.
