### ISSUE TITLE
authority abbreviation of species and synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1776]
[Originally posted on GoogleCode (id 1756) on 2013-04-12]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8751

<b>What data are incorrect or missing?</b>
Fragaria chiloensis subsp. lucida (E. Vilmorin ex J. Gay) Staudt
Fragaria lucida E. Vilmorin ex J. Gay

<b>What data are you expecting instead?</b>
Fragaria chiloensis subsp. lucida (E. Vilmorin ex Gay) Staudt
Fragaria lucida E. Vilmorin ex Gay

<b>If applicable, please provide an authoritative source.</b>
GRIN, IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-12 19:25Z]

Both TROPICOS and IPNI have J. Gay.
GRIN has Gay.

I believe GRIN is incorrect in this and it is J. Gay
