### ISSUE TITLE
unique English common names missing

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1779]
[Originally posted on GoogleCode (id 1759) on 2013-04-12]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8759

<b>What data are incorrect or missing?</b>
Englsh common names listed are the same as for the species and typical subsp. 
western websites use the name broadpetal wild strawberry, which is in line with the accepted French common name.

<b>What data are you expecting instead?</b>
broadpetal wild strawberry 

<b>If applicable, please provide an authoritative source.</b>
&lt;http://biology.burke.washington.edu/herbarium/imagecollection.php?ID=4581&gt; 
&lt;http://science.halleyhosting.com/nature/plants/5petal/rose/fragaria/virginiana.htm&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 14:03Z]

Marilyn: please handle

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 19:45Z]

completed
