### ISSUE TITLE
superfluous entry

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#178]
[Originally posted on GoogleCode (id 2290) on 2014-08-27]

Il y a deux fiches pour le Carex lasiocarpa subsp­. americana, dont une semble vide et devrait sans doute être éliminée.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-10 20:31Z]

L'une, illeg., est un syn. de l'autre - erreur au moment de l'entrée

La raison que c'est ainsi est qu'il semble y avoir un bog dans l'éditeur qui m'empêche de changer son statut.

À faire asap
