### ISSUE TITLE
missing English common name for Geum schofieldii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1782]
[Originally posted on GoogleCode (id 1762) on 2013-04-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8773

<b>What data are incorrect or missing?</b>
missing English common name for Geum schofieldii

<b>What data are you expecting instead?</b>
Queen Charlotte avens (from the BC website below)

<b>If applicable, please provide an authoritative source.</b>

http://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Geum%20schofieldii&amp;lifeform=7

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 14:08Z]

Marilyn : please handle
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 19:44Z]

tremendous, thanks
