### ISSUE TITLE
synonym an invalid name (nom. nudum)

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1784]
[Originally posted on GoogleCode (id 1764) on 2013-04-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8778

<b>What data are incorrect or missing?</b>
Geum hirsutum Muhlenberg

<b>What data are you expecting instead?</b>
Geum hirsutum Muhlenberg 1813, nom. inval., nom. nud.
Geum hirsutum Muhlenberg ex Link (1822)

<b>If applicable, please provide an authoritative source.</b>

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-04-13 21:51Z]

See IPNI, Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 14:12Z]

added Link as per FNA - I will not weep the invalid homonym in this case
