### ISSUE TITLE
missing English common name for Sanguisorba stipulata

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1785]
[Originally posted on GoogleCode (id 1765) on 2013-04-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8955

<b>What data are incorrect or missing?</b>
missing English common name

<b>What data are you expecting instead?</b>
Sitka burnet - move this name over from S. canadensis

<b>If applicable, please provide an authoritative source.</b>
Tropicos and these sites:
&lt;http://www.botany.hawaii.edu/faculty/carr/ofp/san_can.htm&gt;
&lt;http://science.halleyhosting.com/nature/basin/5petal/rose/sanguisorba/sitchensis/sitchensis.htm&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 14:12Z]

Marilyn: please handle
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 17:48Z]

fixed, many thanks
