### ISSUE TITLE
inappropriate English common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1786]
[Originally posted on GoogleCode (id 1766) on 2013-04-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8954

<b>What data are incorrect or missing?</b>
Sitka burnet is now inappropriate, as the range of S. canadensis 
no longer includes the western 'Sitka' region.

<b>What data are you expecting instead?</b>
Move common name Sitka burnet to Sanguisorba stipulata

<b>If applicable, please provide an authoritative source.</b>
see issue 1765

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 14:13Z]

Marilyn: please handle
Luc

Sue: you could have done a single issue of these two... L.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 17:48Z]

fixed, many thanks
