### ISSUE TITLE
inappropriate English common names

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1787]
[Originally posted on GoogleCode (id 1767) on 2013-04-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9750

<b>What data are incorrect or missing?</b>
English common names given: great burnet, burnet bloodwort, official burnet are the same names used for Sanguisorba officinalis:
http://data.canadensys.net/vascan/taxon/8959
These names should appear only under S. officinalis

<b>What data are you expecting instead?</b>
western burnet - to coincide with the french common name sanguisorbe de l'Ouest 

<b>If applicable, please provide an authoritative source.</b>
Since this species was separated from Poteridium (Sanguisorba) annuum, all the websites borrow one or more of the common names of this species for P. occidentale, so it seems logical to use the name western burnet here rather than for P. annuum.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 14:14Z]

Marilyn: please handle
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 17:47Z]

fixed, many thanks
