### ISSUE TITLE
synonym an invalid name (nom. rej.)

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1790]
[Originally posted on GoogleCode (id 1770) on 2013-04-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8750

<b>What data are incorrect or missing?</b>
Filipendula hexapetala Gilibert

<b>What data are you expecting instead?</b>
Filipendula hexapetala Gilibert, nom. inval.

<b>If applicable, please provide an authoritative source.</b>
Tropicos, Index Synonymique.  
IPNI doesn't mention it being invalid, but I think Gilibert's entire pubication Flora Lituanica Inchoata is invalid/rejected.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 14:25Z]

it is a nom. rej. indeed - which makes it invalid too, I guess
