### ISSUE TITLE
misspelling in common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1796]
[Originally posted on GoogleCode (id 1790) on 2013-06-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4226

<b>What data are incorrect or missing?</b>
Tartarian honeysuckle

<b>What data are you expecting instead?</b>
Tatarian honeysuckle  (without the first 'r')

<b>If applicable, please provide an authoritative source.</b>
http://www.tropicos.org/Name/6000144
http://www.invasive.org/browse/subinfo.cfm?sub=3043
http://plants.usda.gov/java/profile?symbol=lota
http://www.missouribotanicalgarden.org/gardens-gardening/your-garden/plant-finder/plant-details/kc/c327/lonicera-tatarica-alba.aspx

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 17:44Z]

Hi - I can look into this again if you wish as it's an English vernacular issue. I do remember reviewing this a while ago. It can be spelled both ways, but I'll review this again.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-17 17:46Z]

Please do
TX
Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-06-17 17:57Z]

Note that the specific epithet is spelled /tatarica/, not /tartarica/

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 21:06Z]

Hi
Sometimes indeed the specific epithet is different with spelling as that used by the vernacular. In this case I will stay with 'Tartarian'. Also this spelling is in wide usage, plus used by earlier references such as Fernald and Britton & Brown.
Note the French vernacular also spells similarly.
ok to mark as completed with review.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-18 12:31Z]

Sue: see http://en.wikipedia.org/wiki/Tatars
Tatars sometimes spelled Tartars

Nonetheless, it might be appropriate to provide both spellings as alternatives

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-18 13:57Z]

finished

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-06-22 11:39Z]

Yes, including the spelling Tatarian honeysuckle as a synonym is appropriate, since this name occurs more frequently in the lit.  Thanks, Luc.
