### ISSUE TITLE
Nativity of Crataegus in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1797]
[Originally posted on GoogleCode (id 1791) on 2013-06-17]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/name/Crataegus%20chrysocarpa%20var.%20chrysocarpa
http://data.canadensys.net/vascan/taxon/8695

<b>What data are incorrect or missing?</b>
Question: how certain are you that these two taxa (Crataegus chrysocarpa and C. macrosperma) are native in Nfld.  Are any found outside of established communities?

<b>What data are you expecting instead?</b>
unsure

<b>If applicable, please provide an authoritative source.</b>
We had them listed as native in the NL checklist, but John only has one photo of C. chrysocarpa from Crabbe's River.  The distribution dots in the Atlas look like they're all in communities along the highway.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-18 12:29Z]

Sue:

I collected both species myself in the wild, at localities found by previous botanists and at new locales. They are both native.

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-06-22 11:36Z]

Thanks Luc. - Sue.
