### ISSUE TITLE
Lotus americanus (synonym) a nom. illeg.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1798]
[Originally posted on GoogleCode (id 1796) on 2013-06-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5783

<b>What data are incorrect or missing?</b>
Lotus americanus (Nuttall) Bischoff

<b>What data are you expecting instead?</b>
Lotus americanus (Nuttall) Bischoff, nom. illeg. hom. [non Vellozo 1827]

<b>If applicable, please provide an authoritative source.</b>
IPNI; Tropicos lists both also, but doesn't designate this one as a homonym.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-25 12:30Z]

Thanks. This is also useful reminder to me as writer of the Acmispon FNA treatment
