### ISSUE TITLE
English vernacular

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#180]
[Originally posted on GoogleCode (id 2344) on 2014-10-30]

Marilyn, you may want to check this.

<b>What is the URL of the page where the problem occurs?</b>
Astragalus beckwithii var. weiserensis

<b>What data are incorrect or missing?</b>
Weiser's milk-vetch

<b>What data are you expecting instead?</b>
Weiser milk-vetch

<b>If applicable, please provide an authoritative source.</b>
1. Name used in Ill. Flora of BC, vol. 3
2. Type locality is Weiser, Idaho

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-10-30 22:15Z]

fixed, many thanks
