### ISSUE TITLE
authority of species Thermopsis mollis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1800]
[Originally posted on GoogleCode (id 1798) on 2013-06-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/26581

<b>What data are incorrect or missing?</b>
Thermopsis mollis (Michaux) M.A. Curtis &amp; A. Gray

<b>What data are you expecting instead?</b>
Thermopsis mollis (Michaux) M.A. Curtis

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos; One of ipni's entries explains where the ex A.Gray originated, but they don't use Gray's name in the authority.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-27 12:31Z]

query sent to editors FNA where the name is given like this

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-27 13:29Z]

M.A. Curtis in A. Gray
