### ISSUE TITLE
Synonymy for Baptisia alba

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#181]
[Originally posted on GoogleCode (id 2349) on 2014-11-13]

Fernald (1950) mentionne le Baptisia leucantha (B. alba var. macrophylla selon USDA PLANTS) pour l'Ontario. Or, cette espèce et cette variété ne figurent pas dans VasCan, ni comme taxons exclus, ni comme synonymes.

Dans VasCan, le B. alba est donné comme exclus en Ontario, mais sans synonymes ni taxons infraspécifiques.

Je pense qu'il faudrait soit exclure séparément le B. leucantha ou le B. alba var. macrophylla, soit placer ces deux taxons en synonymie du B. alba.

Marc

**Comment by brouille** [comment]
En fait, la difficulté provient en partie du fait que Morton & Venn aient traité B. alba (sans var.) et non la var. macrophylla, qui selon le traitement FNA n'est pas B. leucantha, comme le dit PLANTS, mais B. leucophaea. Donc plusieurs courants croisés ici, malheureusement.

Fernald : B. leucantha to sw Ont = lactea var. lactea selon FNA ms, mai non rapporté d'Ont.
B. alba: espèce du sud-est de EU (plaine côtière), certainement pas au Canada
B. leucophaea avec pour syn B. laba var. macrophylla (et non leucothea selon PLANTS)

Tous à exclure?
Je dois demander aussi à Oldham

**Comment by MichaelOldham** [comment]
I'm pretty sure that any ON reports (e.g. by Fernald) of B. alba, lactea, or leucantha are in error.  They were excluded by Morton and Venn (1990) and I have come across no valid records.

Mike

*********************************************************
Michael J. Oldham
Ontario Natural Heritage Information Centre (NHIC)
Ministry of Natural Resources
300 Water Street, 2nd Floor, North Tower
P.O. Box 7000 Peterborough, Ontario K9J 8M5, Canada
phone 705-755-2160; fax 705-755-2168
michael.oldham@ontario.ca<mailto:michael.oldham@ontario.ca>
NHIC requests: NHICrequests@ontario.ca<mailto:NHICrequests@ontario.ca>
NHIC web page: http://nhic.mnr.gov.on.ca/nhic_.cfm
Ontario Reptile & Amphibian Atlas:
http://www.ontarionature.org/protect/species/herpetofaunal_atlas.php
________________________________

**Comment by brouille** [comment]
Added B. alba var. alba [syn B. leucantha] and B. leucophaea [syn B. alba var. macrophylla] and excluded both citing Morton & Venn 1990. I am uncertain whether they cite all these taxa specifically, but given the taxonomic mess mentioned above, this is as good as it will get.
LB
