### ISSUE TITLE
typos in common names

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1813]
[Originally posted on GoogleCode (id 1892) on 2013-10-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5994

<b>What data are incorrect or missing?</b>
Andrew's bottle gentian
Andrew's gentian

<b>What data are you expecting instead?</b>
Andrews' bottle gentian
Andrews' gentian

<b>If applicable, please provide an authoritative source.</b>
This plant was named in honour of Henry Andrews, not Andrew, so the apostrophe should be placed after the 's'.

http://wisplants.uwsp.edu/scripts/detail.asp?SpCode=GENANDvAND

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-10-16 23:54Z]

Same for var. page: http://data.canadensys.net/vascan/taxon/16435

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-17 19:07Z]

I am transferring this to Marilyn.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-20 21:31Z]

corrected and many thanks for catching this error!
