### ISSUE TITLE
incorrect genus in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1818]
[Originally posted on GoogleCode (id 1908) on 2013-10-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6018

<b>What data are incorrect or missing?</b>
Gentianella crinita (Froelich) Ma subsp. crinita

<b>What data are you expecting instead?</b>
Gentianopsis crinita (Froelich) Ma subsp. crinita

<b>If applicable, please provide an authoritative source.</b>
see species entry

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-21 12:51Z]

The subsp. exists in both genera. I corrected the authorities of the current entry and added the Gentianopsis subspecies

Thanks
Luc
