### ISSUE TITLE
English names for Saxifraga bronchialis

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#182]
[Originally posted on GoogleCode (id 2464) on 2015-01-29]

Marylin, I would think that the names &quot;yellow-dotted saxifrage&quot; and &quot;yellow-spotted saxifrage&quot; should only apply to subsp. funstonii, since the petal dots are red in the more widespread subsp. austromontana, according to Ill. Fl. BC.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-02 15:13Z]

Thanks Marc, much appreciated! I'll review the other Saxifragaceae later (big deadlines right now!)
