### ISSUE TITLE
missing tribe or genera within Tordylideae

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1826]
[Originally posted on GoogleCode (id 1917) on 2013-10-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/83?lang=en

<b>What data are incorrect or missing?</b>
on this page, 17 genera are listed below the Tribe Tordylideae

<b>What data are you expecting instead?</b>
When you click on the Tribe name, only 2 genera are listed: Heracleum and Pastinaca

<b>If applicable, please provide an authoritative source.</b>
I don't know if there's a Tribe missing between Pastinaca and Berula, or the remaining genera were misplaced.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 21:26Z]

Sue

The reason for this is that I do not have tribal information for the genera listed beyond the two recognized in Tordylideae. And the formating of the page makes it as if genera without tribes belong to the latter. Not much I can do until I get info on tribal placement of genera.

Thanks for raising it. In some ways, this is a styling issue of our web page.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-15 16:48Z]

The whole classification needs to be revamped in light of recent phylogenetic work, but the dust has yet to settle. Tribal names are lacking for some groups, and generic assignment even need revision.

I am not trying to improve the taxonomy for now.
Luc
