### ISSUE TITLE
Labrador range of Betula xsandbergii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1827]
[Originally posted on GoogleCode (id 1918) on 2013-10-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3715

<b>What data are incorrect or missing?</b>
Betula xsandbergii not present in LB

<b>What data are you expecting instead?</b>
?Betula xsandbergii present in LB if specimens listed below are accurate.

<b>If applicable, please provide an authoritative source.</b>
In our NL checklist, we had this information: Lepage (1976) reports Betula ×sandbergii from Goose Bay, cLab. (DAO, TRT)

**Comment by brouille** [comment]
this has been resolved
LB
