### ISSUE TITLE
Geum laciniatum var. trichocarpum Fernald should be recognized as a good variety

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#183]
[Originally posted on GoogleCode (id 802) on 2011-10-23]

http://data.canadensys.net/vascan/name/Geum%20laciniatum%20var.%20trichocarpum

Geum laciniatum var. trichocarpum Fernald should be recognized; it is clearly distinguishable in Québec although much less common than var. laciniatum; in Québec the 2 varieties almost never are found growing together in my experience, backed up by many collections.  According to a discussion in Sept. 2011 with David Werier of the New York Flora Asssociation, the 2 varieties are as readily distinguishable in New York State but much more likely in that state to be found growing at the same site -Geoffrey Hall, MT

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-28 14:11Z]

Présentement, je fonde ma taxonomie sur le ms FNA. 
Personne à ma connaissance n'a publié d'étude concernant ce taxon. Ce serait nécessaire avant de l'adopter. Il est possible qu'il faille le reconnaître, mais pas sans une étude publiée.
