### ISSUE TITLE
duplicate synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1830]
[Originally posted on GoogleCode (id 1924) on 2013-11-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5661

<b>What data are incorrect or missing?</b>
Microphacos gracilis (Nuttall ) Rydberg - appears 2x in synonymy

<b>What data are you expecting instead?</b>
delete one of the entries

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 20:19Z]

I cannot see how I could have entered the exact same name twice as the program should not allow it... But I did and the program did. Bugger.
