### ISSUE TITLE
wrong genus in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1831]
[Originally posted on GoogleCode (id 1925) on 2013-11-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5685

<b>What data are incorrect or missing?</b>
Astragalus elegans var. minor Hooker

<b>What data are you expecting instead?</b>
Phaca elegans var. minor Hooker

<b>If applicable, please provide an authoritative source.</b>

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-11-04 22:30Z]

Forgot to add - Source: IPNI, MBG

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 20:17Z]

This being from the FNA ms, I returned there: it was a transcription error (i.e., going too fast). It is Phaca there
Luc
