### ISSUE TITLE
mistake in common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1833]
[Originally posted on GoogleCode (id 1927) on 2013-11-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6048

<b>What data are incorrect or missing?</b>
Pyrenee's geranium
Pyrenee's cranesbill

<b>What data are you expecting instead?</b>
Pyrenees geranium
Pyrenees cranesbill

This plant was named for the Pyrenees Mts., not someone named Pyrenee, so the apostrophe is not needed in either rname.

<b>If applicable, please provide an authoritative source.</b>

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-11-06 01:57Z]

Also refers to the subsp. entry http://data.canadensys.net/vascan/taxon/6047

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 20:14Z]

Marilyn

Please correct this

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 19:31Z]

geesch, I don't know how that happened! Now corrected and thanks
