### ISSUE TITLE
authority and rank of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1834]
[Originally posted on GoogleCode (id 1928) on 2013-11-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6009

<b>What data are incorrect or missing?</b>
Gentiana amarella S. Watson

<b>What data are you expecting instead?</b>
Do you mean: Gentiana amarella var. stricta (Griseb.) S. Watson

<b>If applicable, please provide an authoritative source.</b>
Linnaeus made the combination Gentiana amarella, but IPNI lists S.Watson as the author of G.a. var. stricta.  MBG lists this too, but leaves out the basionym author (Griseb.), so their entry is incomplete.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 20:13Z]

The entry for Gentiana amarella was really for the var stricta
Initially, sp was entered instead of var in the status, which made the var invisible
It is already fixed

Gentiana amarella cannot be a syn of var. acuta...
