### ISSUE TITLE
wrong genus in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1836]
[Originally posted on GoogleCode (id 1930) on 2013-11-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6018

<b>What data are incorrect or missing?</b>
Gentianella crinita (Froelich) Ma subsp. crinita

<b>What data are you expecting instead?</b>
I think you mean: Gentianopsis crinita (Froelich) Ma subsp. crinita

<b>If applicable, please provide an authoritative source.</b>
MBG

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 20:07Z]

no I meant (Froelich) Berchtold ex ...
This is what is currently in the database, but not in the visible VASCAN
And the Gentianopsis is also in the database

So I am not certain when the correction was made - after the last compilation appears doubtful, in which case I wonder what happened

Luc
