### ISSUE TITLE
authorities of synonyms; gender of Anthopogon synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1839]
[Originally posted on GoogleCode (id 1933) on 2013-11-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6027

<b>What data are incorrect or missing?</b>
Gentianopsis virgata subsp. macounii (T. Holm) J.S. Pringle
Gentianopsis macounii (T. Holm) H. Iltis
Gentianopsis crinita subsp. macounii (T. Holm) Á. Löve &amp; D. Löve
Gentiana macounii T. Holm
Gentianopsis procera subsp. macounii (T. Holm) H. Iltis
Gentianella crinita subsp. macounii (T. Holm) J.M. Gillett
Anthopogon tonsum (Lunell) Rydberg
Anthopogon procerum var. tonsum (Lunell) Lunell

<b>What data are you expecting instead?</b>
Gentianopsis virgata subsp. macounii (Holm) J.S. Pringle
Gentianopsis macounii (Holm) Iltis
Gentianopsis crinita subsp. macounii (Holm) Á. Löve &amp; D. Löve
Gentiana macounii Holm
Gentianopsis procera subsp. macounii (Holm) Iltis
Gentianella crinita subsp. macounii (Holm) J.M. Gillett
Anthopogon tonsus (Lunell) Rydberg
Anthopogon procerus var. tonsus (Lunell) Lunell

<b>If applicable, please provide an authoritative source.</b>
IPNI, IPNI authors, MBG for Holm and Iltis
IPNI has a -us ending for all appropriate species of Anthopogon, but MBG has a mixture of -us and -um; this must be a fairly recent gender change.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 19:55Z]

Anthopogon: obviously a masculine sounding name - the mixture in TRO is suspicious
IPNI has tended to correct gender properly lately
