### ISSUE TITLE
additional English vernaculars for Desmodium paniculatum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1846]
[Originally posted on GoogleCode (id 1940) on 2013-11-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5726

<b>What data are incorrect or missing?</b>
If Desmodium perplexum is an accepted synonym, I suggest you add the common English names in synonymy that are associated with this name, as many of the online descriptions use these names.

<b>What data are you expecting instead?</b>
perplexing tick-trefoil
perplexed tick-trefoil 

<b>If applicable, please provide an authoritative source.</b>
Illinois wildflowers:
http://www.illinoiswildflowers.info/savanna/plants/perplexing_trefoil.htm
USDA
http://plants.usda.gov/core/profile?symbol=DEPE80&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 19:35Z]

Marilyn

Please can you verify and change this?

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 20:20Z]

ok perhaps in this case. Usage of 'perplexing' and 'perplexed' however is directly with the specific usage of D. perplexum not with D. paniculatum.
