### ISSUE TITLE
spelling of hybrid species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1849]
[Originally posted on GoogleCode (id 1943) on 2013-11-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5899

<b>What data are incorrect or missing?</b>
Robinia ×margarettiae Ashe

<b>What data are you expecting instead?</b>
Robinia ×margaretta Ashe

<b>If applicable, please provide an authoritative source.</b>
MBG, GRIN, and the Plant List spell the epithet as margaretta (the original spelling), while IPNI lists it as margarettae.  Only the USDA Plants database has the spelling as xmargarittiae.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 15:07Z]

I will have to check this. It is possible that the original spelling be correctible

Luc

**Comment by brouille** [comment]
margarettae
