### ISSUE TITLE
validity of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1852]
[Originally posted on GoogleCode (id 1946) on 2013-11-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9800

<b>What data are incorrect or missing?</b>
Juglans alba Linnaeus

<b>What data are you expecting instead?</b>
Juglans alba Linnaeus, nom. rej.

<b>If applicable, please provide an authoritative source.</b>
IPNI and MBG have this listed as a name proposed for rejection; has this name been officially rejected?

**Comment by brouille** [comment]
nom. rej. added, with references to synonyms not referenced before
LB
