### ISSUE TITLE
Question change in genus

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1854]
[Originally posted on GoogleCode (id 1948) on 2013-11-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/25469
http://data.canadensys.net/vascan/taxon/16625

<b>What data are incorrect or missing?</b>
Hypericum fraseri (Spach) Steudel
Hypericum virginicum Linnaeus

<b>What data are you expecting instead?</b>
Triadenum fraseri (Spach) Gleason
Triadenum virginicum (Linnaeus) Rafinesque

<b>If applicable, please provide an authoritative source.</b>
I read the article you referenced that proposed the use of Hypericum over Triadenum, but his charts clearly show that the Triadenum group are in a separate sister clade than Hypericum.  Their arguments include noting that although the petal colour and fascicles of stamens are different, they still think they should be included  in Hypericum.  They didn't mention that the petals of Triadenum are imbricate in bud, while those of all Hypericum are convolute, nor do they mention that all Triadenum species have nectaries, while no Hypericum species do.  Their pollination mechanisms are also very different.  The Triadenum species present pollen for cross pollination (by crepuscular moths), then the 2nd day the petals fold around the stamens and the anthers fuse to the stigma, facultative self-pollination.  Triadenum flowers are only open for one day, while Hypericum flowers are open for more than one day and anthers do not fuse to the stigmas, leaving the flowers open for considerable time to cross-pollination.  The authors did mention a paper by Nurk nad Blattner (Taxon 59: 1495-1507 (Oct. 2010) which disagreed with their conclusion.  There seem to be more than enough differences to recognize Triadenum as a separate genus.  I'd like to know what the rationale of the Hypericum FNA author was - hopefully not based on this paper by Ruhfel et al.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 15:00Z]

I will read the paper again.

FNA kept Triadenum separate, but then the paper was published after. I do not know whether the author made a comment to it in a more recent version, which I have not seen.

Luc
