### ISSUE TITLE
inappropriate English vernaculars

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1860]
[Originally posted on GoogleCode (id 1956) on 2013-11-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6466

<b>What data are incorrect or missing?</b>
smooth hedge-nettle
slender betony
narrow-leaved betony

<b>What data are you expecting instead?</b>
hispid hedge-nettle

<b>If applicable, please provide an authoritative source.</b>
The three names listed above refer to Stachys tenuifolia in other databases; an excluded species in Canada, but still an accepted species in the US.  I gather from the USDA entry, S. hispida was once considered a synonym of tenuifolia, but not that it has been elevated to separate/accepted status, appropriate English vernaculars should be used, leaving the common names for S. tenuifolia with that species.  The epithet hispida suggests the name hispid nedge-nettle, which agrees with given French vernacular and common usage is US website:

&lt;https://gobotany.newenglandwild.org/species/stachys/hispida/&gt; 
&lt;http://www.keiriosity.com/gallery/main.php/v/plants/Lamiaceae/Stachys_hispida/&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 14:53Z]

Marilyn

Please consider the comment from Sue.
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 23:48Z]

Many thanks for outlining this for corrections
