### ISSUE TITLE
suggested synonym: basionym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1862]
[Originally posted on GoogleCode (id 1958) on 2013-11-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
Stachys arvensis 

<b>What data are incorrect or missing?</b>
missing basionym

<b>What data are you expecting instead?</b>
Glechoma arvensis L. 

<b>If applicable, please provide an authoritative source.</b>
The Plant list and Index Synonymique:
http://www2.dijon.inra.fr/flore-france/ge-gn.htm
This is not mentioned in MBG nor IPNI, so would be good to add in case people think the parenthetical (L.) is incorrect.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 14:25Z]

TROPICOS has a small note: Annotation: Glechoma arvensis L. ? 

Note that INPN also has it (L.) L.

I will notify Gandhi and Zarucchi, since the taxon is in FNA (otherwise, I would not bother... you nearly have to do it yourself)

Luc
