### ISSUE TITLE
typo in synonym; authority of 2nd synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1864]
[Originally posted on GoogleCode (id 1960) on 2013-11-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6449

<b>What data are incorrect or missing?</b>
Salvia lancifolia Poiret
Salvia lanceolata Willdenow

<b>What data are you expecting instead?</b>
Salvia lanceifolia Poiret
Salvia lanceolata Lamarck, nom. illeg. [hom., non Brouss.]

<b>If applicable, please provide an authoritative source.</b>
IPNI and TPL spell the first name lanceifolia; MBG has it listed as lanceaefolia.
Can't find any combination of S. lanceolata by Willdenow in IPNI or MBg, should be Lamarck.

**Comment by brouille** [comment]
lanceaefolia in TROPICOS, alt. spelling correctible to lancei
