### ISSUE TITLE
nativity of Salvia nemorosa in ON

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1865]
[Originally posted on GoogleCode (id 1961) on 2013-11-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6446

<b>What data are incorrect or missing?</b>
Salvia nemorosa L. listed as native in ON

<b>What data are you expecting instead?</b>
Salvia nemorosa L. is introduced in ON; it is native to Eurasia.

<b>If applicable, please provide an authoritative source.</b>
GRIN

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 14:19Z]

An obvious mistake - SE in FOIBIS = int
Luc
