### ISSUE TITLE
error in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1868]
[Originally posted on GoogleCode (id 1964) on 2013-11-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6394?lang=en

<b>What data are incorrect or missing?</b>
Lycopus uniflorus var. pauciflorus Bentham

<b>What data are you expecting instead?</b>
Lycopus virginicus var. pauciflorus Bentham

<b>If applicable, please provide an authoritative source.</b>
IPNI, MBG, Bentham made his combination with Lycopus virginicus.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 14:12Z]

The Lycopus var. is now a syn of L. virginicus: there is no indication it is syn of uniflorus 

I wonder where this came from...

There has not been a FNA ms yet on this genus

Luc
