### ISSUE TITLE
Question about authority of variety

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1871]
[Originally posted on GoogleCode (id 1971) on 2013-11-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6420

<b>What data are incorrect or missing?</b>
Monarda punctata var. villicaulis (Pennell) E.J. Palmer &amp; Steyermark

<b>What data are you expecting instead?</b>
?Monarda punctata var. villicaulis (Pennell) Shinners

<b>If applicable, please provide an authoritative source.</b>
MBG lists on Shinners (1953) as the author of var. villicaulis, while IPNI lists E.J.Palmer &amp; Steyermark, but gives no publication data.  Palmer &amp; Steyerm. did describe M.p. var. occidentalis (1935), so I'm wondering if E.J.Palmer &amp; Steyermark is an error for var. villicaulis.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 13:29Z]

Will have to investigate a bit on this one. You seem to be right.
Luc

**Comment by brouille** [comment]
Correction done. FNA confirms this too
LB
