### ISSUE TITLE
authorities of subspecies and synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1872]
[Originally posted on GoogleCode (id 1973) on 2013-11-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6436

<b>What data are incorrect or missing?</b>
Prunella vulgaris subsp. lanceolata (W.P.C. Barton) Hultén
Prunella vulgaris var. lanceolata (W.P.C. Barton) Hultén

<b>What data are you expecting instead?</b>
Prunella vulgaris subsp. lanceolata (W.P.C. Barton) Piper &amp; Beattie (1915), non Hultén (1949)
Prunella vulgaris var. lanceolata (W.P.C. Barton) Fernald

<b>If applicable, please provide an authoritative source.</b>
IPNI, MBG.  Can't find any info that makes Piper and Beattie's name illeg., so Hulten's is a later isonym.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 13:22Z]

Sue:

Firstly, I sent an email to Gandhi and Zarucchi for them to add nom. illeg. to the Hultén name

I kept the illegitimate name but placed it in syn of the legit one
