### ISSUE TITLE
Mentzelia decapetala: authorities of species and synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1884]
[Originally posted on GoogleCode (id 1986) on 2013-12-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6564

<b>What data are incorrect or missing?</b>
a) Mentzelia decapetala (Pursh ex Sims) Urban &amp; Gilg ex Gilg
b) Bartonia decapetala Pursh
c) Mentzelia ornata Pursh
d) Nuttallia decapetala Greene

<b>What data are you expecting instead?</b>
a) Mentzelia decapetala (Pursh ex Sims) Urban 
b) Bartonia decapetala Pursh ex Sims
c) Mentzelia ornata (Pursh) Torr. &amp; A.Gray; basionym already listed
d) Nuttallia decapetala (Pursh ex Sims) Raf. 1817, non (Pursh ex Sims) Greene 1906

<b>If applicable, please provide an authoritative source.</b>
a) See Tropics, &amp; IPNI notes for use of just Urban
b-d) Tropicos, GRIN; IPNI has Nuttalia decapetala (L.) Greene as 1906

**Comment by brouille** [comment]
Nuttallia decapetala (Pursh ex Sims) Raf. 1817 : according to TROPICOS, this is an invalid name, no combination being made in the text
Luc
