### ISSUE TITLE
missing English vernacular for Alcea pallida

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1886]
[Originally posted on GoogleCode (id 1988) on 2013-12-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6614

<b>What data are incorrect or missing?</b>
missing English vernacular

<b>What data are you expecting instead?</b>
Turkish wild hollyhock

<b>If applicable, please provide an authoritative source.</b>
I know these are less than authoritative sites, but the only locations I can find a name for this species are nursery websites or blogs, plus the seeds, under the name Turkish wild hollyhock, are for sale on E-Bay.
&lt;http://www.georgiavines.com/cart/index.php?main_page=product_info&amp;products_id=1159&gt; 
&lt;http://www.ebay.co.uk/itm/ALCEA-PALLIDA-TURKISH-WILD-HOLLYHOCK-1-PKT-x-20-SEEDS-/330621901140&gt; 

Yesteday, I found the name on this site, but it seems to be down today
&lt;http://www.rareplants.de/shop/product.asp?P_ID=8156&gt; 
It's a German site on rare plants.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-23 00:48Z]

still working on this one. I thought I'd share what I found out so far. 
I think Alcea biennis is a synonym and many European countries are using A. biennis, including TeleBotanica with the FR vernacular.
Again can't find a source which I'd like to add to our reference list!
A. biennis is named 'biennial hollyhock' on some sites.
Ontario Natural Heritage Information Centre can be cited as a reference. ONHIC is using 'eastern hollyhock' as its name.
of central and southeast Europe - also on some invasive species sites like NOBANIS.
I'm thinking of using what is already used in Canada by Ontario as the accepted name, with the other names as synonyms.
thoughts anyone?

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-23 00:49Z]

Marc - to help out, does Macura have this species listed? (no issue with the FR vernacular though), Many thanks.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-23 23:44Z]

Thanks - worked this one out for the English names.
