### ISSUE TITLE
Query about vernaculars for Tilia xvulgaris

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1887]
[Originally posted on GoogleCode (id 1989) on 2013-12-06]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6645

<b>What data are incorrect or missing?</b>
If Tilia xeuropaea is listed in synonymy as an auct non L. 
that means that Tilia xeuropeaea L. is an accepted species? If so, what are the hybrid parents of both species, since T. cordata x T. platyphyllos are listed for both species.  The name xeuropaea L. would have priority if they'r synonyms, but I haven't seen any clear information online on the relationship between these two taxa.

<b>What data are you expecting instead?</b>
If these are two separate species, then the common names European linden and tilleul d'Europe should more correctly go with T. xeuropaea L., while the French vernacular tilleul de Hollande and whatever equivalent there is in english (Holland linden?) should stay here with T. x vulgaris

<b>If applicable, please provide an authoritative source.</b>
http://www.waymarking.com/waymarks/WME9A5_Tilia_X_vulgaris_Sambeek_the_Netherlands

**Comment by manions** [comment]
I believe this can be closed now. With adopted common names and T. x europaea assigned.
