### ISSUE TITLE
status of species name; authority of basionym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1889]
[Originally posted on GoogleCode (id 1994) on 2013-12-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6679

<b>What data are incorrect or missing?</b>
a)  Myrica californica Chamisso &amp; Schlechtendal

b)  Myrica californica Chamisso &amp; Schlechtendal
    Gale californica (Chamisso &amp; Schlechtendal) Greene
    Morella californica (Chamisso &amp; Schlechtendal) Wilbur
 
<b>What data are you expecting instead?</b>
a) Morella californica (Chamisso)Wilbur as the accepted species.  FNA's keys put all the waxy-fruited Myrica in subgenus Morella, including M. californica.

b) Myrica californica Chamisso 
   Gale californica (Chamisso) Greene
   Morella californica (Chamisso) Wilbur
   
<b>If applicable, please provide an authoritative source.</b>
There may be something more recent that changes this, but according to these references, the sp. should be Morella californica.
FNA: see key to subgenera of Myrica
http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=121458
Also, Wilbur's and Hebert's papers:
Wilbur, R.L. 1994. The Myricaceae of the United States and Canada: Genera, Subgenera, and Series. Sida 16(1): 102. 1994.
Herbert, J. 2005. New combinations and a new species in Morella (Myricaceae). Novon 15: 293-295.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-15 16:26Z]

You are right: this species properly belongs to Morella. I should have transferred it before. The Jepson Manual was a good ref. for it.
