### ISSUE TITLE
Fragaria virginiana VASCAN, IPNI authority differs from The Plant List, Tropicos, Arthur Haines authority

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#189]
[Originally posted on GoogleCode (id 1613) on 2013-01-15]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8758?lang=fr

<b>What data are incorrect or missing?</b>
Fragaria virginiana Miller

<b>What data are you expecting instead?</b>
Fragaria virginiana Duchesne

<b>If applicable, please provide an authoritative source.</b>
http://www.theplantlist.org/tpl/record/tro-27800063
http://www.tropicos.org/Name/27800063
http://www.arthurhaines.com/tricolpates_r_of_new_england.html

IPNI agrees with VASCAN (Fragaria virginiana Miller), following Staudt 1981 (Taxon 30: 299) who stated that Duchesne treated all strawberries as belonging to a single species with constant races for which he coined binomials
http://www.ipni.org:80/ipni/idPlantNameSearch.do;jsessionid=5C3174382289F1C7A77F22AF593E1DF4?id=725144-1&amp;back_page=%2Fipni%2FeditSimplePlantNameSearch.do%3Bjsessionid%3D5C3174382289F1C7A77F22AF593E1DF4%3Ffind_wholeName%3DFragaria%2Bvirginiana%26output_format%3Dnormal

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-01-28 18:51Z]

Miller est correct, Duchesne est incorrect pour des raisons techniques publiées. Cela a été validé pour FNA 9.
Luc
