### ISSUE TITLE
duplicate variety listed in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1893]
[Originally posted on GoogleCode (id 2005) on 2013-12-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6751?lang=en

<b>What data are incorrect or missing?</b>
Clarkia amoena var. caurina caurina (Abrams ex Piper) C.L. Hitchcock

<b>What data are you expecting instead?</b>
Clarkia amoena var. caurina Abrams ex Piper) C.L. Hitchcock

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-10 16:51Z]

a cut and paste error when adding the authorities in fact
