### ISSUE TITLE
Typo in authority of subspecies

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1903]
[Originally posted on GoogleCode (id 2015) on 2014-01-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8263

<b>What data are incorrect or missing?</b>
Claytonia rubra subsp. depressa (A. Gray) J.M. Miller &amp; K.L. Chambers

<b>What data are you expecting instead?</b>
Claytonia rubra subsp. depressa (A. Gray) John M. Miller &amp; K.L. Chambers

<b>If applicable, please provide an authoritative source.</b>
See Tropicos and IPNI authors; there is a John M. Miller and a J.M. Miller. Too common a name.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-08 18:51Z]

isotypic synonyms added
