### ISSUE TITLE
incomplete authority of synonym; 2nd synonym an illeg. name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1904]
[Originally posted on GoogleCode (id 2016) on 2014-01-03]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8268

<b>What data are incorrect or missing?</b>
Montia sibirica var. heterophylla (A. Gray) B.L. Robinson
Claytonia heterophylla (Torrey &amp; A. Gray) Swanson

<b>What data are you expecting instead?</b>
Montia sibirica var. heterophylla (Torr. &amp; A. Gray) B.L. Robinson
Claytonia heterophylla (Torrey &amp; A. Gray) Swanson

<b>If applicable, please provide an authoritative source.</b>
MBG; IPNI was unavailable tonight.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-08 18:44Z]

Claytonia heterophylla: nom. illeg. but no issue with auth.
