### ISSUE TITLE
Author name for Chrysosplenium americanum differs from common sources

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#191]
[Originally posted on GoogleCode (id 1650) on 2013-03-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9227

<b>What data are incorrect or missing?</b>
Chrysosplenium americanum de Schweinitz ex Hooker

<b>What data are you expecting instead?</b>
Chrysosplenium americanum Schweinitz ex Hooker

<b>If applicable, please provide an authoritative source.</b>
http://www.tropicos.org/Name/29100122
http://www.theplantlist.org/tpl/record/kew-2720092

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 14:03Z]

typo
