### ISSUE TITLE
rank of synonym incorrect

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1913]
[Originally posted on GoogleCode (id 2025) on 2014-01-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6983

<b>What data are incorrect or missing?</b>
Castilleja pallida subsp. elegans (Malte) B. Boivin

<b>What data are you expecting instead?</b>
Castilleja pallida var. elegans (Malte) B. Boivin
or
Castilleja pallida subsp. elegans (Malte) Pennell

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos - 
Pennell made the subspecies combination in 1934, Boivin named the variety.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-09 20:25Z]

THe FNA ms is yet to be circulated - I am awaiting this for sources and other synonyms
