### ISSUE TITLE
authority of synonym; question about species authority

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1917]
[Originally posted on GoogleCode (id 2030) on 2014-01-11]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/27537

<b>What data are incorrect or missing?</b>
Pedicularis kanei Durand ex A. Gray

<b>What data are you expecting instead?</b>
Pedicularis kanei Durand 

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI, PlantList

IPNI lists Pedicularis lanata Pallas ex Pursh 1813 as the earliest version of this name, with 2 others: P. lanata Willd. ex Steven 1823 (the one here) and P. lanata Willd. ex Chamisso &amp; Schltdl. 1827. I can't find any online resources that say Pallas's name is invalid or illegitmate.  If it isn't, then this name would have priority, but is it the same entity?  If a valid name, wouldn't the existence of this name negate the legitimacy of P. lanata Willd. ex Steven?

Tropicos only lists the 1827 name for P. lanata Willd. ex Cham. &amp; Schltdl.

Note also that IPNI spells Pedicularis willdenowii as willdenovii.  Am not sure if this is just a typo or something that needs to be checked.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-13 15:13Z]

Currently, the FNA treatment (draft in revision) has:
Pedicularis lanata   Willdenow ex Chamisso & Schlechtendal, Linnaea 2: 583.  1827

I do not know what K. Gandhi is making of all this. Will have to consult.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-15 15:13Z]

Pedicularis kanei already corrected in db following FNA ms of Pedicularis

Pedicularis lanata: FNA ms has Willd. ex Cham. & Schltdl. and I am correcting it this way, but this may not have been revised by K. Gandhi (I do not know whether he saw it before it was sent to regional review)
