### ISSUE TITLE
nativity of Fumaria reuteri in BC

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1921]
[Originally posted on GoogleCode (id 2034) on 2014-01-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/23632

<b>What data are incorrect or missing?</b>
nativitiy of Fumaria reuteri in BC

<b>What data are you expecting instead?</b>
Should be introduced, as this is a Mediterranean species.  The USDA site has it listed as introduced in adjacent Washington state.

<b>If applicable, please provide an authoritative source.</b>

http://plants.usda.gov/core/profile?symbol=FURE3
Spanish wiki: http://es.wikipedia.org/wiki/Fumaria_reuteri
&lt;http://www.pnwherbaria.org/m/datasets/vascular-plants/pages/papaveraceae/fumaria-reuteri.htm&gt; 
And this may be the soure of the report of Fumaria bastardii in BC:
&lt;http://bridge.botany.ubc.ca/herbarium/images/vwsp_images/Large_web/V193811.jpg&gt; 
This species is also listed in a number of swEuropean websites, such as flora of Catalan, Malta, Canaries, etc.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 19:11Z]

corrected to introduced - I guess I did not pay attention when Lomer added it to the flora and VASCAN (it is not in eFlora).
Luc
