### ISSUE TITLE
typo in author abbreviation of species, authority of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1929]
[Originally posted on GoogleCode (id 2043) on 2014-01-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7221

<b>What data are incorrect or missing?</b>
Collinsia parviflora var. grandiflora (Douglas ex Lindley) Ganders &amp; Krause
Collinsia grandiflora Lindley

<b>What data are you expecting instead?</b>
Collinsia parviflora var. grandiflora (Douglas ex Lindley) Ganders &amp; G.R.Krause
Collinsia grandiflora Douglas ex Lindley

<b>If applicable, please provide an authoritative source.</b>
MBG, IPNI, GRIN; HWR, for C. grandiflora, IPNI is inconsistent in its use of Lindley vs Douglas ex Lindley.  For C. parviflora, IPNI only has Lindley, but they provide no notes to explain why Douglas was dropped in those entries.  Most sites have Douglas ex Lindley for both of these names, but I remember a previous species entry where IPNI had an explanation as to why Douglas was dropped from the authorship.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-23 15:13Z]

I will await the FNA ms to see whether this issue is taken care of. I cannot judge from the information provided - I am uniformizing on Douglas ex Lindley for now
This may have to change yet

the initials were added
L

**Comment by brouille** [comment]
corrected
LB
