### ISSUE TITLE
leavigata should be laevigata

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#193]
[Originally posted on GoogleCode (id 1820) on 2013-07-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/25571?lang=fr

<b>What data are incorrect or missing?</b>
Persicaria pensylvanica var. leavigata (Fernald) W.C. Ferguson

<b>What data are you expecting instead?</b>
Persicaria pensylvanica var. laevigata (Fernald) W.C. Ferguson
Bull. Torrey Bot. Club 51: 190, 1924

<b>If applicable, please provide an authoritative source.</b>
&lt;http://www.biodiversitylibrary.org/item/44246#page/194/mode/1up&gt;
(Ferguson, William C. 1924. Contributions to the Flora of the Long Island, N.Y., Second Paper. Bulletin of the Torrey Botanical Club 51: 177-201)

**Comment by geoffreyhall** [comment]
[Originally posted on GoogleCode on 2013-08-12 18:56Z]

Je crois qu'il y a un oubli; le 12 août 2013 les pages utilisent encore l'orthographie de leavigata au lieu de laevigata

http://data.canadensys.net/vascan/taxon/25571
http://data.canadensys.net/vascan/name/Persicaria%20pensylvanica%20var.%20leavigata
http://data.canadensys.net/vascan/taxon/8153

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-12 19:01Z]

LA correction a �t� faite apr�s la derni�re compilation. Elle est bien
faite. VASCAN se publie une fois par mois.
Luc
