### ISSUE TITLE
authoirty of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1931]
[Originally posted on GoogleCode (id 2045) on 2014-01-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7316

<b>What data are incorrect or missing?</b>
Tonella tenella (Bentham) A.Heller  {vas}  [BC]

<b>What data are you expecting instead?</b>
Tonella tenella (Benthan ex Alphonse de Candolle) A.Heller

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropcios

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-23 15:06Z]

Please note that not all genera in future FNA volumes have been submitted and that I have therefore not revised these, which leaves many questions open. 

Thanks for raising the issues.

Luc
