### ISSUE TITLE
authorities of synonyms; missing English vernacular

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1934]
[Originally posted on GoogleCode (id 2049) on 2014-01-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9637;jsessionid=D479CE6BAD5A4D45558F93000CD1C8DD

<b>What data are incorrect or missing?</b>
missing English vernacular
Veronica wormskjoldii var. nutans Pennell
Veronica alpina var. nutans (Bongard) B. Boivin

<b>What data are you expecting instead?</b>
suggest: nodding alpine speedwell, as per the latin meaning
Veronica wormskjoldii var. nutans (Bong.) Pennell
Veronica alpina var. nutans (Bongard) Ledeb. [1847]
and/or Veronica alpina var. nutans (Bongard) B. Boivin, nom. illeg. hom. [1967]

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-23 20:16Z]

thanks, yes 'nodding' is suitable; also Weber & Wittman's 2012 Colorado Flora use 'nodding' for V. nutans, although it's in brackets.
Added English name
