### ISSUE TITLE
Question about use of Plantanus hybrida over earlier names

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1938]
[Originally posted on GoogleCode (id 2053) on 2014-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7349

<b>What data are incorrect or missing?</b>

Question about acceptance of Platanus hybrida Brotero

<b>What data are you expecting instead?</b>

Since P. hybrida was published in 1804, I wonder why you're using this name instead of Platanus x acerifolia (Aiton) Willdenow, which was publoished in 1797.  Also, the earliest name given to London planetree, Platanus x hispanica (Miller ex Munchh. [1770] is used by GRIN as the accepted species now, while it was formerly considered a nom. dubium. 
Also, most other sources describe the London planetree as a hybrid of P. occidentalis x P. orientalis), while you make no mention of these names.  I realize it's not accepted as occurring in Canada (at least not outside of cultivation), but it's also in Dan McKenney's Plant Hardiness Zone database, so I'd like to correct this entry if needed.  Was

<b>If applicable, please provide an authoritative source.</b>
GRIN - accepts Platanus x hispanica, yet doesn't mention P. hybrida
MBG - lists Platanus × hispanica cv. acerifolia as the accepted name of Platanus hybrid Brot.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-24 18:32Z]

This is an issue that requires some consultation.
TX
L

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-24 18:38Z]

Just after, I checked TROPICOS again to discover a paper by Geerinck that appears to solve the issue [I cannot include the CV to the name, however]:

Geerinck, D. 1979. Platanus × hispanica Mill. ex Münchh. cv. Acerifolia, nom correct du platane hybride ou à feuilles d'érable. Bull. Jard. Bot. Natl. Belg. 49(1–2): 160–161. 

Luc
