### ISSUE TITLE
Crataegus cearulescens Sargent should be Crataegus caerulescens Sargent

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#194]
[Originally posted on GoogleCode (id 1966) on 2013-11-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/19999

<b>What data are incorrect or missing?</b>
Crataegus cearulescens Sargent

<b>What data are you expecting instead?</b>
Crataegus caerulescens Sargent

<b>If applicable, please provide an authoritative source.</b>
http://www.tropicos.org/Name/50080445

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 13:58Z]

an obvious typo... not so easy to catch
thanks
L
