### ISSUE TITLE
authority abbreviations in species and synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1942]
[Originally posted on GoogleCode (id 2057) on 2014-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8048

<b>What data are incorrect or missing?</b>
Linanthus septentrionalis Mason
Linanthus harknessii var. septentrionalis (Mason) Jepson &amp; V. Bailey

<b>What data are you expecting instead?</b>
Linanthus septentrionalis H. Mason
Linanthus harknessii var. septentrionalis (H. Mason) Jepson &amp; V.L. Bailey

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-24 16:56Z]

Thanks for the correction.

I just realized that some Linanthus are now Leptosiphon (Jepson).

More correction to do.
