### ISSUE TITLE
typo in author abbreviation of species; missing English vernacular

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1946]
[Originally posted on GoogleCode (id 2061) on 2014-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8047

<b>What data are incorrect or missing?</b>
a) Linanthus minimus (Mason) Goodwillie
b) missing English vernacular

<b>What data are you expecting instead?</b>
a) Linanthus minimus (H. Mason) Goodwillie
b) suggested English vernatcular: minute babystars or minute linanthus

<b>If applicable, please provide an authoritative source.</b>
a) MBG, IPNI authors
b) As Leptosiphon spp., L. minimus and L. bicolor were given the same English vernaular in US-PLANTS: true babystars. This vernacular is also used by CalFlora and others. See: http://www.calflora.org/cgi-bin/specieslist.cgi?where-genus=Leptosiphon
and: http://coepark.net/pineridgeassociation/plants-animals-geology/wildflowers?sobi2Task=sobi2Details&amp;catid=16&amp;sobi2Id=30
However, I this relates back to the fact that L. minimus was only elevated to species status in 2001.  So, a new vernatcular name seems to be appropriate.  I suggest the name minute babystars or minute linanthus, since  L. minimus flowers are about 1 cm long and white (not bicolored) compared to L. biflora flowers, which are 1.5 to 3 cm long and always bicoloured [re: Ill. Flora of Pacific States, LeRoy Abrams et al.], 
I had searched for other names, but could find none that weren't also applied to L. bicolor.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-25 18:41Z]

Baldwin et al (Jepson 2012) describe L. minimus flowers differently (with 2 colours)
I used 'small bicoloured' and 'small' linanthus to indicate relationship, plus also 'minute' would seem more suitable with reference to L. pygmaeus.
