### ISSUE TITLE
Status of subsp. of Polemonium pulcherrimum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1947]
[Originally posted on GoogleCode (id 2062) on 2014-01-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8085

<b>What data are incorrect or missing?</b>
Status of Polemonium pulcherrimum subsp. lindlelyi

<b>What data are you expecting instead?</b>
No synonyms are listed if Polemonium pulcherrimum, but the US-Plants site and Panarctic Flora had BC ranges for subsp. pulcherrimum and subsp. lindleyi.  Have these both been synonymized under the species, or has subsp. lindleyi been elevated to species level?

<b>If applicable, please provide an authoritative source.</b>

http://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Polemonium%20pulcherrimum%20ssp.%20lindleyi

http://nhm2.uio.no/paf/700205#paf-700205b

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-27 14:52Z]

There is no recent treatment of Polemonium available to solve this and the FNA ms is not out yet.

**Comment by brouille** [comment]
This issue has been solved by the release of the FnA draft treatment. See latest VASCAN release
LB
