### ISSUE TITLE
variety name missing

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1948]
[Originally posted on GoogleCode (id 2074) on 2014-01-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/26706

<b>What data are incorrect or missing?</b>
Polygala verticillata var. Fernald

<b>What data are you expecting instead?</b>
Polygala verticillata var. dolichoptera Fernald

<b>If applicable, please provide an authoritative source.</b>
MBG

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-27 16:47Z]

Strangely, var. name was not entered - probably tried to copy and slide, which does not work in the database
