### ISSUE TITLE
status of Eriogonum ovalifolium var. depressum in Canada

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1953]
[Originally posted on GoogleCode (id 2086) on 2014-01-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8116

<b>What data are incorrect or missing?</b>
Eriogonum ovalifolium var. depressum Blankinship is not listed as a variety in Canada

<b>What data are you expecting instead?</b>
Eriogonum ovalifolium var. depressum Blankinship is listed as present in Alberta in FNA and in BC from the BC flora website.  Perhaps these are based on misIDs, but thought I'd check.

<b>If applicable, please provide an authoritative source.</b>
FNA lists it from southern AB, 
BC lists it as native: http://www.bcflora.org/data/taxon/2324.php

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 19:09Z]

This will need more validation: eFlora differs from the BC Flora in the presence of Eriogonum ovalifolium infrasp. I will have to consult with BC specialists.

Thanks for raising the issue.

L

**Comment by brouille** [comment]
according to FNA: 
var. nivea in BC, as per eFlora BC
var. depressum in Alta. [not in eFlora BC]
var. purpureum is BC, Alta [but not eFlora BC contra FNA specialist account]
eFlora may not be reliable here
added var. depressum for Alta
