### ISSUE TITLE
typo in Enlish vernacular

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1955]
[Originally posted on GoogleCode (id 2088) on 2014-01-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8131

<b>What data are incorrect or missing?</b>
corpse bindweed

<b>What data are you expecting instead?</b>
copse bindweed

<b>If applicable, please provide an authoritative source.</b>
FNA has this mistake too.  Remember, the accepted common name is hedge bindweed, a copse (meaning a small group of trees or a thicket, likr a hedge) is a term that originated in Europe, where this plant is native.  Other occurrences of corpse bindweed are likely copied from FNA's mistake, so I don't recommend keeping this as an 'synonym' vernacular, since it's obviously a typo in FNA that should not be perpetuated.
**See GRIN for acceptance of the vernacular copse-bindweed.
Clive Stace's New Flora of the British Isles also uses copse bindweed, along with a variety of websites: 
&lt;http://www.hairycalyx.com/wildflowers/families/dock/copse_bindweed.htm&gt; 
&lt;http://www.brc.ac.uk/plantatlas/index.php?q=node/3218&gt; 
&lt;http://www.luontoportti.com/suomi/en/kukkakasvit/black-bindweed&gt; at end
&lt;http://www.bioimages.org.uk/html/Fallopia_dumetorum.htm&gt; 
&lt;http://www.somersetrareplantsgroup.org.uk/wp-content/uploads/2013/03/Fallopia-dumetorum-extinct.pdf&gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 18:55Z]

I notified FNA of the error, so that it be corrected on the online version, eventually
