### ISSUE TITLE
synonymy of Polygonum cuspidatum Willd. ex Spreng.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1956]
[Originally posted on GoogleCode (id 2089) on 2014-01-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8132

<b>What data are incorrect or missing?</b>
Polygonum cuspidatum Willdenow ex Sprengel

<b>What data are you expecting instead?</b>
Delete: Polygonum cuspidatum Willdenow ex Sprengel - this is a synonym of Polygonum acuminatum Kunth, according to MBG.  It's also an invalid name (pro syn. of P. acuminatum.)

<b>If applicable, please provide an authoritative source.</b>
IPNI, MBG; this earlier P. cuspidatum is a syn of P. acuminatum, not Fallopia japonica.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-31 18:46Z]

Deleted. Tx
My mistake
Luc
