### ISSUE TITLE
New taxon name (to add as accepted name or as synonym of accepted name) and possible subtraction of taxon from flora of Canada

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#196]
[Originally posted on GoogleCode (id 2099) on 2014-02-02]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5080

<b>What data are incorrect or missing?</b>
Carex scoparia var. tessellata Fernald &amp; Wiegand

<b>What data are you expecting instead?</b>
Carex waponahkikensis M. Lovit &amp; A. Haines

According to Botanical Notes 14: 4-5: &quot;As a result of careful examination of specimens, especially in the light of the additional characters that separate these two taxa, it is now realized that Carex waponahkikensis is a globally restricted taxon that is found only in extreme eastern Maine along the coastal plain. Many collections, including all those from Canada (New Brunswick and Nova Scotia) and regions of Maine outside of Hancock and Washington Counties, were misidentified. We are aware of fewer than 20 living populations (approximately 12), contributing to a tentative G-rank of G2.&quot;

Whether Carex waponahkikensis M. Lovit &amp; A. Haines is recognized as an accepted name or as a synonym, the taxon should de considered by Vascan as either excluded, extirpated, doubtful or absent in Canada until justified by a specimen (NB, the Canadensys current Canadian records for Carex scoparia Schkuhr ex Willdenow var. tessellata Fernald &amp; Wiegand listed below should be checked):

http://data.canadensys.net/explorer/r/mt-specimens/21063?view=dwc
MT-21063; Christie, David S., sn, 1980-07-13; Grindstone Island, Albert County, New Brunswick, 45° 43' N, 64° 37' W; det. Hall, Geoffrey, 2010-12-21

http://data.canadensys.net/explorer/r/mt-specimens/21052?view=dwc
MT-21052; Clayden, Stephen R.; Bagnell, Bruce A.; Noel, Paula E., sn; 1994-07-21; Long Creek, 3.5 km south of Coles Island, Queens County, New Brunswick, 45° 53' N, 65° 47' W; det. Hall, Geoffrey, 2011-01-19

<b>If applicable, please provide an authoritative source.</b>
http://www.maine.gov/dacf/mnap/features/carex_waponahkikensis_botnotes_n14.pdf
http://www.maine.gov/dacf/mnap/features/carxwap.htm
http://www.mainenaturalhistory.org/sedges-maine-field-guide-cyperaceae [Sedges of Maine - A Field Guide to Cyperaceae (2013)]

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-07 15:20Z]

Email from Tony Reznicek, 2014-02-06
"Yes, a good species, I think; recognizable even driving along the roads once you get familiar with it -- though a terrible name! I was hoping Andrew Hipp and Paul Rothrock, who were working on the Carex scoparia group, would publish it as a species, but with a more pronounceable name, but it did not happen. So we have Carex waponahkikensis Lovit & A.Haines! I teach it to my sedge class in Maine, though we don't always see it (and I don't ask them to pronounce it.) 
  Last summer, I spent a couple days with Marilee Lovit trying to locate it in New Brunswick, to no avail. Though reported from New Brunswick in FNA, I've not seen a specimen and neither have Marilee or Arthur, so I am dubious the collection exists (even though I am also convinced it must be there somewhere).
Tony"

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-07 15:23Z]

MArc et Marilyn

This var. now has been recognized as a species.

Please verify that the vernaculars are still suitable. I do not see an urgent need to change them, but one or the other En vernaculars might be less desirable now.
Marily, please note that the Maine Natural Areas program name this taxon: Dawn-land sedge
http://www.maine.gov/dacf/mnap/features/carxwap.htm


Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-02-14 21:00Z]

No need to change the French name published in FNA.
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-03-02 16:05Z]

English vernaculars reviewed and new accepted English vernacular. Very interesting!
