### ISSUE TITLE
status of Viola xbissellii 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1960]
[Originally posted on GoogleCode (id 2097) on 2014-02-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9534;jsessionid=65438120675D414E58E8B840A1C271A9

<b>What data are incorrect or missing?</b>
status of Viola bissellii House

<b>What data are you expecting instead?</b>
Viola bissellii House is listed as a hybrid of V. cucullata x V. sororia, but in NB it is listed as the accepted name for V. melissifolis.  Is this a distinct hybrid, or should it be synonymized with V. xmelissifolia?  I'm not sure if V. sororia and V. septentrionalis were recognized as distinct when this was named in 1924.

<b>If applicable, please provide an authoritative source.</b>
for Viola bissellii, see: http://www.macbe.com/botanyclub/english/nbvioletkeyb.html
see Key trait 2a, which links to the description farther down
They list is as a hybrid of V. cucullata x V. sororia

**Comment by brouille** [comment]
Now that FNA has appeared and given I received another enquiry concerning this, I have decided to synonymize x bissellii with x melissifolia, the latter being the younger name and both with the same parent. The NB report was particularly nomenclaturally ill-informed.
Luc
