### ISSUE TITLE
authority of species Viola kitaibeliana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1961]
[Originally posted on GoogleCode (id 2098) on 2014-02-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9490

<b>What data are incorrect or missing?</b>
Viola kitaibeliana Roemer &amp; Schultes

<b>What data are you expecting instead?</b>
Viola kitaibeliana Schultes

<b>If applicable, please provide an authoritative source.</b>
IPNI, GRIN - see notes in GRIN

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-04 19:41Z]

Please note that the Viola treatment has not been checked again for changes, etc., and thus much has not been validated.
L
