### ISSUE TITLE
authority of synonyms; typo in English vernacular

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1965]
[Originally posted on GoogleCode (id 2103) on 2014-02-03]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9495

<b>What data are incorrect or missing?</b>
Macloskie's violet
Viola rotundifolia var. pallens Banks ex De Candolle
Viola pallens Banks ex De Candolle
Viola macloskeyi var. pallens (Banks ex de Candolle) C.L. Hitchcock
Viola macloskeyi subsp. pallens (Banks ex de Candolle) M.S. Baker
Viola pallens (Banks ex de Candolle) Brainerd subsp. pallens

<b>What data are you expecting instead?</b>
Macloskey's violet
Viola rotundifolia var. pallens Banks ex Gingens [în DC.]
Viola pallens (Banks ex Gingens) Brainerd
Viola macloskeyi var. pallens (Banks ex Gingens) C.L. Hitchcock
Viola macloskeyi subsp. pallens (Banks ex Gingens) M.S. Baker
Viola pallens (Banks ex Gingens) Brainerd subsp. pallens

<b>If applicable, please provide an authoritative source.</b>
IPNI: Remarks: Eponymy: &quot;The species is named in honor of Professor George Macloskey, of the College of New Jersey, Princeton&quot;
IPNI has Banks ex Gingens as the basionym of V. pallens combinations.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-04 19:53Z]

vernacular corrected
I have to check a bit more for the authorities
TX
Luc

**Comment by brouille** [comment]
authorities corrected
author is Gingins, not Gingens

LB
