### ISSUE TITLE
same synonym (V. papilionacea)  listed under 2 species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1968]
[Originally posted on GoogleCode (id 2106) on 2014-02-03]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9606
http://data.canadensys.net/vascan/taxon/9526

<b>What data are incorrect or missing?</b>
Viola papilionacea Pursh listed as a synonym for:
Viola septentrionalis and Viola sororia var. sororia

<b>What data are you expecting instead?</b>
retain the synonym for the appropriate species

<b>If applicable, please provide an authoritative source.</b>

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-02-03 04:47Z]

Also, now that Viola septentrionalis has been removed from synonymy, should the vernacular violette septentrionale also be removed?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-04 19:33Z]

this has to wait that I obtain the latest version of the FNA ms, just returned after (much) corrections by the author
Luc

**Comment by brouille** [comment]
septentrionalis now syn of sororia only
Luc
