### ISSUE TITLE
placement error: English verncular placed with French vernacular

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1970]
[Originally posted on GoogleCode (id 2113) on 2014-02-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8831

<b>What data are incorrect or missing?</b>
English vernacular alpine cinquefoil placed with the French vernaculars.

<b>What data are you expecting instead?</b>
move the name down a couple of lines - to below Crantz's cinquefoil.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-06 21:19Z]

The name was associated with the wrong marker in the database. Data entry error (not mine). Now corrected. Will show in next compilation.
