### ISSUE TITLE
synonym a illeg. homonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1971]
[Originally posted on GoogleCode (id 2114) on 2014-02-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8843

<b>What data are incorrect or missing?</b>
Potentilla pilosa Willdenow

<b>What data are you expecting instead?</b>
Potentilla pilosa Willdenow 1799, nom. illeg. [hom., non Villars 1779]

<b>If applicable, please provide an authoritative source.</b>
IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-06 21:18Z]

Need to check in FNA ms also
L

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-11 21:44Z]

The name was very ambiguous and was not in FNA ms. So I deleted it.
