### ISSUE TITLE
Separate of Potentilla hookeriana from P. rubricaulis in Ertter et al's new paper

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1972]
[Originally posted on GoogleCode (id 2115) on 2014-02-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8847

<b>What data are incorrect or missing?</b>
Potentilla hookeriana Lehmann
Potentilla nivea subsp. hookeriana (Lehmann) Hiitonen
Potentilla hookeriana Lehmann subsp. hookeriana TROPICOS
Potentilla hookeriana Lehmann var. hookeriana
Hooker's cinquefoil and possibly Rocky Mountain cinquefoil

<b>What data are you expecting instead?</b>
If you accept the Ertter et al. 2013 paper (below),
These names (including vernaculars) should be deleted from synonym of Potentilla rubicaulis and moved to P. hookeriana Lehmann.
But these names can be added in synonym under P. rubricaulis:
Potentilla dissecta Pursh var. rubricaulis (Lehm.) Rydb.
Potentilla nivea L. subsp. rubricaulis (Lehm.) Hiitonen 
and Potentilla hookeriana Lehmann added as a distinct species from Alberta, am not sure if BC or YK are represented.

<b>If applicable, please provide an authoritative source.</b>
See: http://brit.org/webfm_send/471
Ertter, B., R.Elven, and D.F.Murray. 2013. Changes to Potentilla rubricaulis s.l., P. hookeriana (Rosaeae), and erstwhile synonyms in Flora of North America North of Mexico.  J.Bot. Res. Inst. Texas 7(2): 703-711.
They don't list full ranges for any of these species, but their MS on Potentilla may provide that info.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-06 21:18Z]

I need to go over the corrected FNA treatment, now complete.
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-11 21:40Z]

I effected the change using the FNA ms as a basis.
Luc
