### ISSUE TITLE
Prunus ×cistena introduced in Ontario

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1973]
[Originally posted on GoogleCode (id 2116) on 2014-02-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
under Genus Prunus
http://data.canadensys.net/vascan/taxon/1593;jsessionid=CFCC75EBC7E1868FEB5D1A17992273C6

<b>What data are incorrect or missing?</b>
Not listed: Prunus ×cistena (N.E.Hansen) Koehne  (P. cerasifera × P. pumila)

<b>What data are you expecting instead?</b>
Consider adding Prunus ×cistena to Ontario as introduced.
I have found Prunus ×cistena growing wild on the St. Mary's Island portion of Whitefish Island in Ontario, adjacent to the locks in Sault St. Marie.  The young shrubs I've seen (about 6-7 ft tall) are too young to have been planted during colonization of the islands while the locks were being built and Parks Canada does not plant on these islands, so they probably arose from a seed/fruit deposited by a bird.  I have pix if you'd like to see them.

<b>If applicable, please provide an authoritative source.</b>
http://www.ars-grin.gov/cgi-bin/npgs/html/taxon.pl?405249

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-06 21:17Z]

And the data were made public where? What can I cite as a source of the record?
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 21:59Z]

Mike

Source for record? I am adding it, but a source will be required. No specimen?

Luc

**Comment by brouille** [comment]
Mike you never answered me concerning a source for specimen: NHIC?
For the time being, I am listing it as doubtful (which includes incomplete data)
Luc

**Comment by brouille** [comment]
Sue

Did you deposit a specimen in a herbarium for documenting this? It is new to Canada and Ontario. I presume you have not published it, have you?

Luc

**Comment by sjmeades** [comment]
Yes, I sent you a package of specimens; last I heard, Geoff had put them in the freezer in the hearbarium.  Maybe they’re still there.

 

I haven’t added it to the checklist, since I’m not familiar with European Pilosella species, and the differences (mainly flower colour) seem very vague to me.  Howard’s an amateur botanist, but as a retired chem prof from MUN, he’s good with detail and has found a good number of European weeds around SJ.  

 

Thanks, Sue.

**Comment by brouille** [comment]
added with MT as source
It might be worth a note somewhere as it is new to Canada
Luc

**Comment by sjmeades** [comment]
Hi Luc,

 

Once we’re allowed to go walking on Whitefish Island again (near the SSM Locks), I’ll make a collection of this species for you.  – Sue.
