### ISSUE TITLE
According to Canadensys data, Botrychium boreale present in Alberta & BC but not mapped in Vascan

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#198]
[Originally posted on GoogleCode (id 2313) on 2014-10-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/name/Botrychium%20boreale

<b>What data are incorrect or missing?</b>
Dans Vascan, taxon absent du Canada, mais 6 récoltes au Canada repérées dans Explorateur de Canadensys :
http://data.canadensys.net/explorer/fr/rechercher?view=map&amp;1_f=16&amp;1_o=EQ&amp;1_v_1=Botrychium+boreale
http://data.canadensys.net/explorer/fr/rechercher?view=table&amp;1_f=16&amp;1_o=eq&amp;1_v_1=Botrychium%20boreale

De plus, il y a une récolte en Colombie-Britannique qui vient d'être déposée à MT :
http://media.canadensys.net/mt-specimens/large/MT00191325.jpg

<b>What data are you expecting instead?</b>
Botrychium boréale présent dans 2 provinces, Alberta et Colombie-Britannique

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
Les spécimens auxquels tu réfères seraient maintenant assignés au Botrychium pinnatum (syn: B. boreale subsp. obtusifolium)
Farrar ne traite pas du boreale en Amérique du Nord
Luc
