### ISSUE TITLE
incorrect authority for hybrid entry

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1981]
[Originally posted on GoogleCode (id 2185) on 2014-05-03]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9055

<b>What data are incorrect or missing?</b>
Populus ×berolinensis C. Koch

<b>What data are you expecting instead?</b>
Populus ×berolinensis (K.Koch) Dippel - see below

<b>If applicable, please provide an authoritative source.</b>

IPNI has Populus × berolinensis K.Koch -- Wochenschr. viii. (1865) 239.

MBG has Populus hybrida var. berolinensis C.Koch, with no pubication information, and Populus berolinensis Dippel, 1982

Flora of China has Populus ×berolinensis Dippel (1891}

ITIS has Populus ×berolinensis (K.Koch) Dippel
http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&amp;search_value=195770

I'm not sure why this taxon is so poorly listed in the respective dBs, but if K.Koch coined the name P. berolinensis, then Dippel's name would be an isonym, but it's more likely that K.Koch's name was actually P.hybrida var. berolinensis, named in 1865, and Dippell elevated it to species level in 1892, so I checked the web for Dippel's publication: Handb. Laubholzk. 2: 210. 1892, see below

In: http://archive.org/stream/illustrierteshan01schnuoft/illustrierteshan01schnuoft_djvu.txt

Hwr, the digital recognition software used has produced many errors:

2bxl3 /'. nigra rar. italica X lanrifolia : P. berolinensis DlPPEL, Lailbholzk. II. 210. i8q2 (/'. liybrida berolinensis K. KoCIL in Woclienschr. für (»ärtn. Y I 1 1 . 22.&quot;). i86j : /'. certinensis der (»arten! fy. bis 2&lt; • m ; 

Looks like this should say: ... P. nigra var. italica x laurifolia: P. berolinensis Dippel, Laubholzk. 2:210, 1892. (P. hybrida berolinensis K.Koch in Wochenschr. für Gärtn. {1865)

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-05-03 00:55Z]

You might also want to add the basionym: 
Populus hybrida M.Bieb. var. berolinensis K.Koch

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-05-16 14:25Z]

GRIN uses Dippel, but cites works that have (K. Koch) Dippel
I am still confused, but temporarily will do as you suggest.

This is an issue that may deserve more scrutiny, but I am sure K. Gandhi would not want to be involved since it is not clearly NA.
