### ISSUE TITLE
incorrect parent listed for hybrid

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1983]
[Originally posted on GoogleCode (id 2192) on 2014-05-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5153?lang=en

<b>What data are incorrect or missing?</b>
Parents: Carex aquatilis var. aquatilis x Carex crinita var. crinita. 

<b>What data are you expecting instead?</b>
Parents: Carex aquatilis var. aquatilis x Carex gynandra (C. crinita var. gynandra. 

<b>If applicable, please provide an authoritative source.</b>
USDA Plants; also, it C. crinita var. crinita cannot be a parent since it doesn't occur in Nfld., and the type is from Nfld.  See IPNI

**Comment by brouille** [comment]
@sjmeades
When Cayouette & Catling 1992 did their survey, they dropped the var. gynandra from crinita, a big difference indeed
I will cite PLANTS as source
