### ISSUE TITLE
incorrect parent listed of hybrid

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1984]
[Originally posted on GoogleCode (id 2193) on 2014-05-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5155?lang=en

<b>What data are incorrect or missing?</b>
Carex nigra x Carex paleacea

<b>What data are you expecting instead?</b>
Carex bigelowii x C. paleacea

<b>If applicable, please provide an authoritative source.</b>
FNA, under C. paleacea

**Comment by brouille** [comment]
correction made
LB
