### ISSUE TITLE
Odontites serotina / serotinus and combinations are missing from list of synonyms of Odontites vulgaris

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#199]
[Originally posted on GoogleCode (id 2511) on 2015-03-06]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/23732?lang=fr

<b>What data are incorrect or missing?</b>
some synonyms for Odontites vulgaris

<b>What data are you expecting instead?</b>
as synonyms, one or several of the following:
Odontites verna (Bellardi) Dumort. subsp. serotina (Dumort.) Corb.
Odontites serotinus (Lam.) Dumort.
Odontites serotina (Lam.) Dum.
Odontites serotina (Lam.) Rchb. s.s.

see:
http://www.efloras.org/florataxon.aspx?flora_id=3&amp;taxon_id=200020789
http://wisplants.uwsp.edu/scripts/detail.asp?Spcode=ODOVERsSER

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-18 18:29Z]

Nous avons réinstitué les noms qui avaient été effacés [par erreur] et ajouté O. serotinus

Note que les noms en a sont incorrects: us est la terminaison

Certains de ces noms sont mal appliqués ou illégitimes.

Luc
