### ISSUE TITLE
authority of subspecies americana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1990]
[Originally posted on GoogleCode (id 2201) on 2014-05-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4932?lang=en

<b>What data are incorrect or missing?</b>
Carex lasiocarpa subsp. americana (Fernald) Hultén

<b>What data are you expecting instead?</b>
Carex lasiocarpa subsp. americana (Fernald) D.Löve &amp; J.-P.Bernard
Carex lasiocarpa subsp. americana (Fernald) Hultén, nom. invalid

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos

**Comment by brouille** [comment]
done
