### ISSUE TITLE
typos in authorities of synonyoms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1992]
[Originally posted on GoogleCode (id 2203) on 2014-05-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4973?lang=en

<b>What data are incorrect or missing?</b>
Carex incurva var. setina Christ
Carex maritima var. setina (H. Christ ex Scheutz) Fernald
Carex setina (Christ) V.I. Kreczetowicz
Vignea maritima subsp. setina (Christ) Soják

<b>What data are you expecting instead?</b>
Carex incurva var. setina Christ ex Scheutz
Carex maritima var. setina (Christ ex Scheutz) Fernald
Carex setina (Christ ex Scheutz) V.I. Kreczetowicz
Vignea maritima subsp. setina (Christ ex Scheutz) Soják

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos; FNA is incorrect with H.Christ., see IPNI authors.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-06-20 20:27Z]

Corrected the H. Christ.

HAve to check for the ex

**Comment by brouille** [comment]
ex removed
