### ISSUE TITLE
status of Carex praticola in insular Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1994]
[Originally posted on GoogleCode (id 2205) on 2014-05-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5042?lang=en

<b>What data are incorrect or missing?</b>
Status of Carex praticola in Nfld.

<b>What data are you expecting instead?</b>
Unsure of status of report: See below:

<b>If applicable, please provide an authoritative source.</b>
We had this note in our CL: [There is one report of Carex praticola from swNfld. (Rouleau &amp; Lamoureux, 1992), however the voucher specimen at GH has not been checked for accuracy. 

Has this specimen ever been checked?

**Comment by brouille** [comment]
The voucher is at GH and I do not know whether it has been verified. According to our database, entered from Rouleau's cahiers, the specimen is 
Pease, Arthur S.; Edgerton, Claude W. 27194
Tompkins, Saddle Mountain

Stu had written a note in the MT folder stating that this report appeared doubtful
I do not know whether we saw the GH specimen when we visited there for the Rare Plants of Nfld. - it is not listed there

We are trying to investigate more, perhaps with GH
Luc
