### ISSUE TITLE
Status of Carex ×pseudohelvola in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1995]
[Originally posted on GoogleCode (id 2206) on 2014-05-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5182?lang=en

<b>What data are incorrect or missing?</b>
Carex ×pseudohelvola is listed for N &amp; L

<b>What data are you expecting instead?</b>
In our CL, we had this note: [Reports from sLab. are based on a collection from the Côte Nord, eQue. (Scoggan 1978).]
No mention was made of Nfld. pops. But maybe you've received more recent information?

**Comment by brouille** [comment]
this has been resolved
LB
