### ISSUE TITLE
typo in parenthetical author of hybrid

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#1996]
[Originally posted on GoogleCode (id 2210) on 2014-06-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5197?lang=en

<b>What data are incorrect or missing?</b>
Carex ×subviridula (Kukenthal) Fernald

<b>What data are you expecting instead?</b>
Carex ×subviridula (Kükenthal) Fernald

<b>If applicable, please provide an authoritative source.</b>
typo in spelling of Kükenthal (ü rather than u)

Fernald (in Rhodora 35: 231) lists Carex flava x Carex oederi forma subviridula Kükenthal as the basionym, however, this name is not listed in other sources.  Is this an oversight, or has Kükenthal's name been designated as illeg. or invalid?
IPNI also lists a 2007 name: Carex x alsatica Zahn northosubsp. subviridula (Fernald) Govaerts, which apparently doesn't recognize Kükenthal's name.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-06-18 21:36Z]

typo corrected 

I cannot say about the other issue. I am also not including formas in VASCAN, even when basionym
