### ISSUE TITLE
Synonyme

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#20]
[Originally posted on GoogleCode (id 785) on 2011-09-27]

Salut

Je viens de tomber sur ce vieux synonyme.  Par nostalgie....
Betula quebeccensis Burgsd., Neue Schriften Ges. Naturf. Freunde Berlin 5: 196 (1784).  est un synonyme de Betula pumila.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-19 14:11Z]

Fred

Quand tu ajoutes des noms, il serait préférable de me fournir une source (préférablement déjà dans les ref) qui cite le syn sous pumila (je présume var. pumila).

Aurais tu une source?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-28 13:18Z]

il faudrait déterminer si ce nom est syn. de var. pumila ou var. glandulifera - ce n'est pas précisé non plus
