### ISSUE TITLE
Labrador status of 2 Cyperaeae

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2003]
[Originally posted on GoogleCode (id 2223) on 2014-06-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5321
and 
http://data.canadensys.net/vascan/taxon/5301?lang=en

<b>What data are incorrect or missing?</b>
Status of Schoenoplectus subterminalis in Labrador?
Status of Rhynchospora capillacea in Labrador?

<b>What data are you expecting instead?</b>
Neither Schoenoplectus subterminalis nor Rhynchospora capillacea were listed for Labrador in our 2000 checklist.  Do you have data on specimens of either species from Labrador?

<b>If applicable, please provide an authoritative source.</b>
FNA lists N &amp; L., but I wonder if that was due to treating N&amp;L as one province with 1 record.

**Comment by brouille** [comment]
Data corrected as per Meades & Meades 2022
