### ISSUE TITLE
status of Scirpus hattorianus in Labrador

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2007]
[Originally posted on GoogleCode (id 2227) on 2014-06-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5331?lang=en

<b>What data are incorrect or missing?</b>
Scirpus hattorianus is listed for Labrador, as well as insular NL

<b>What data are you expecting instead?</b>
Scirpus hattorianus was not listed as from Labrador in our 2000 checklist, ans since most records were separated from S. atrovirens, which was never reported from Labrador, I have to wonder if this is an error in reporting.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-25 20:26Z]

Was cited as native without source. I suspect it was an error of entry, somehow. I removed the data from Labr.
L
