### ISSUE TITLE
status of Najas gracillima in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2008]
[Originally posted on GoogleCode (id 2228) on 2014-06-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6123

<b>What data are incorrect or missing?</b>
Najas gracillima not listed from insular Nfld.

<b>What data are you expecting instead?</b>
FNA lists Najas gracillima from insular Nfld.

<b>If applicable, please provide an authoritative source.</b>
See: FNA, vol. 22, pg. 82.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-06-27 20:41Z]

Is there a specimen, however? need to check this

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-06-29 04:07Z]

I don't know where the report came from either, but needs to be verified; the author of the FNA treatment should have a record or reason whey they added Nfld. to the distribution.

**Comment by brouille** [comment]
I am excluding it from Nfld.
