### ISSUE TITLE
status of Sisyrinchium angustifolium in Labrador

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2009]
[Originally posted on GoogleCode (id 2229) on 2014-06-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6197

<b>What data are incorrect or missing?</b>
Sisyrinchium angustifolium is listed for Labrador

<b>What data are you expecting instead?</b>
Sisyrinchium angustifolium is not listed for Labrador in our NL checklist.

<b>If applicable, please provide an authoritative source.</b>
FNA has a dot around the Goose Bay area for this taxon, but was this based on a verified specimen or old records?  Our NL checklist includes Sisyrinchium angustifolium in Appendix 1, as not present in NL.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-29 13:53Z]

For the time being, I am putting the report as doubtful. I do not know on what the Goose Bay dot is based. Need to check whether or not there is a specimen, etc.
Luc

**Comment by brouille** [comment]
excluded Labr based on your site
it is probably less mistaken than keeping it
LB
