### ISSUE TITLE
missing FR vernacular for Huperzia arctica

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#201]
[Originally posted on GoogleCode (id 788) on 2011-10-11]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
Huperzia arctica
This taxon was not on the list provided to us by Peter, but is on VASCAN.

<b>What data are incorrect or missing?</b>
French vernacular

<b>What data are you expecting instead?</b>
as Marc provides

<b>If applicable, please provide an authoritative source.</b>
check Elven 2007+ (PanArctic Flora) but no vernaculars are suggested

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-11 14:31Z]

Done : lycopode arctique
Concerning the accepted English name : can the species really be considered "high-arctic", when it is reported from Quebec?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-11 20:36Z]

High-artic?

Oui, car une petite partie de l'extr�me Ungava est consid�r� �cologiquement
haut arctique.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-11 20:49Z]

Merci Luc. Je croyais que le haut arctique se situait entièrement au Nunavut, à partir de Resolute environ. Ça doit être une question de définition, ou de précision des limites.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2011-10-11 21:07Z]

fixed

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-12 13:25Z]

C'est bioclimatique et �cologique
Luc
