### ISSUE TITLE
status of Acer pseudoplatanus in insular Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2010]
[Originally posted on GoogleCode (id 2239) on 2014-07-17]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9211

<b>What data are incorrect or missing?</b>
Acer pseudoplatanus exluded from Newfoundland

<b>What data are you expecting instead?</b>
Acer pseudoplatanus is naturalized in the St. John's and Logy abay area of  Newfoundland

<b>If applicable, please provide an authoritative source.</b>
We're in St. John's on holiday and visited a cousin in Logy Bay who asked me to identify a few plants in her backyard that just grew spontaneously near her house.  One of them was Acer pseudoplatanus.  Today, we saw numerous specimens planted around St. John's and it seems to have naturalized some outside of St. John's.  I can get a specimen if you'd like one from the Logy Bay site.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-29 13:46Z]

If I understand correctly, you are modifying the statement made in Meades et al. 2000, where it was considered excluded, cultivated only.

Is a specimen deposited in a herbarium, so I could cite it? If not, I would certainly appreciate a specimen for MT, which could be cited.

I will await a source.

Thanks
Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-07-29 15:38Z]

Hi Luc,

Yes, that's what I mean.  It should be listed as introduced that than 
just cultivated in NL, since we found it escaped in several of the 
larger cities across the island, plus Eastport, which is smaller, but 
near Terra Nova Park, so has lots of city visitors probably 
inadvertently spreading the occasional seed.  I'll add the comment to 
the next version of our NL checklist that Acer pseudoplatanus is widely 
cultivated in urban areas, but is also occasionally found as an escape.

I made a collection that I'll send to you.  Could you remind me of the 
address and who to send it to, as I only had Stu's address.

Sue.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-29 15:42Z]

Address for the herbarium below

Luc Brouillet
Conservateur
Herbier Marie-Victorin
Centre sur la biodiversit�
Institut de recherche en biologie v�g�tale
Universit� de Montr�al
4101 rue Sherbrooke E
Montr�al, QC, Canada
H1X 2B2

514-343-2142
fax 514-343-2288
http://www.biodiversite.umontreal.ca/herbier-marie-victorin
CITES no. CA-035



Le 2014-07-29 11:38, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by brouille** [comment]
Sue

Never did see a specimen of this. Is there one at a Nfld. herbarium?

Luc

**Comment by brouille** [comment]
Sue

Where is the specimen located? NFM or NFLD?
Luc
