### ISSUE TITLE
authority of some synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2011]
[Originally posted on GoogleCode (id 2241) on 2014-08-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6908?lang=en

<b>What data are incorrect or missing?</b>
Gymnadenia tridentata (Hooker) Lindley
Habenaria tridentata Hooker

<b>What data are you expecting instead?</b>
Add: Orchis clavellata Michx. var. tridentata Muhl. [1813]
Gymnadenia tridentata (Muhl.) Lindley [1835]
Habenaria tridentata (Muhl.) Hooker [1824]

<b>If applicable, please provide an authoritative source.</b>
See the Plant List:
http://www.theplantlist.org/tpl1.1/record/kew-157085
Tropicos lists Orchis clavellata Michx. var. tridentata (Muhl. ex Willd.) Muhl. [1813] as a synonym of the illeg. homonmym Orchis tridentatal Muhl. ex Willd. 1805, but they should have deleted the basionym authority, since it's an illeg. homonym.  That leaves Muhl. as the earliest author of the name tridentata, as Hooker's combination, Habenaria tridentata wasn't published until 1822.  The Plant List has all the combinations of tridentata with Muhl. as the basionym authority.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-01 18:28Z]

This will require validation with Gandhi. 
Luc

**Comment by brouille** [comment]
I checked various databases and made the correction.
