### ISSUE TITLE
Range in Labrador?; authority of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2013]
[Originally posted on GoogleCode (id 2243) on 2014-08-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6925

<b>What data are incorrect or missing?</b>
Platanthera orbiculata in Labrador
Habenaria orbiculata (Pursh) Torrey [1826]
Habenaria orbiculata (Pursh) Torrey var. orbiculata

<b>What data are you expecting instead?</b>
Platanthera orbiculata not in Labrador
Habenaria orbiculata (Pursh) Hooker [1825]
Habenaria orbiculata (Pursh) Hooker var. orbiculata

<b>If applicable, please provide an authoritative source.</b>
FNA for range of P. orbiculata; we noted in our CL that Labrador reports of P. orbiculata were discounted by Reddoch and Reddoch (1993).
You may have  heard of a recent record from Labrador, but I don't know of anything recent.

Re: authority: Tropicos &amp; IPNI list Hooker's name as being published 1 year earlier than Torrey's.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-04 20:24Z]

needs more checking since FNA also is wrong (?)

**Comment by brouille** [comment]
Labrador excluded
The Torrey name is nom. illeg. (later homonym) - I kept it because of FNA, but added the other, legitimate name
