### ISSUE TITLE
incorrect placement of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2014]
[Originally posted on GoogleCode (id 2244) on 2014-08-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7371

<b>What data are incorrect or missing?</b>
Agrostis alba var. aristata Spenner

<b>What data are you expecting instead?</b>
Agrostis alba var. aristata Spenner should be listed as a synonym of Agrostis canina.
Agrostis vulgaris var. aristata Parnell could be listed as a synonym of Agrostis capillaris, but this is a later homonym (nom. illeg.) of A. vuglaris var. aristata Wahlenb. [1814], as seen in IPNI.

<b>If applicable, please provide an authoritative source.</b>
The Plant List

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-04 20:22Z]

needs verif

**Comment by brouille** [comment]
synonym displaced to A canina
LB
