### ISSUE TITLE
synonym should be auct. non All.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2015]
[Originally posted on GoogleCode (id 2245) on 2014-08-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7378;jsessionid=E77BD36970A323B0A6A6FD8527BBD1FC

<b>What data are incorrect or missing?</b>
Agrostis rupestris Allioni

<b>What data are you expecting instead?</b>
Agrostis rupestris auct. non Allioni

<b>If applicable, please provide an authoritative source.</b>
The Plant List has Agrostis rupestris as an accepted species, we had this listed as a synonym of A. mertensii as auct. non All.
TelaBotanica And Kew list A. rupestris as a distinct European spp.:
http://www.tela-botanica.org/bdtfx-nn-1845-synthese
http://www.kew.org/data/grasses-db/www/imp00259.htm

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-04 20:22Z]

needs validation

**Comment by brouille** [comment]
changed to auct. non Allioni after validation in WCSP & E+M
Luc
