### ISSUE TITLE
synonym a nom. inval.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2019]
[Originally posted on GoogleCode (id 2249) on 2014-08-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7530

<b>What data are incorrect or missing?</b>
Deschampsia cespitosa var. genuina (Reichenbach) O.H. Volk

<b>What data are you expecting instead?</b>
Deschampsia cespitosa var. genuina (Reichenbach) O.H. Volk, nom. inval.

<b>If applicable, please provide an authoritative source.</b>
Tropicos; genuina or typica epithets are all invalid.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-04 20:19Z]

This is partly a result of the so and so work done on nomenclature for the Grasses... Barkworth went her own way in many things...
