### ISSUE TITLE
change to French vernacular?

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#202]
[Originally posted on GoogleCode (id 1618) on 2013-01-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9591 

<b>What data are incorrect or missing?</b>
French vernacular 'braya de MacCall'

<b>What data are you expecting instead?</b>
braya de McCalla

<b>If applicable, please provide an authoritative source.</b>
named for William Copeland McCalla (1814-1849); hence spelling should change?

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-02 20:30Z]

French name corrected to « braya de McCalla ». Merci.
Marc
