### ISSUE TITLE
status of Leymus arenarius in Newfoundland

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2024]
[Originally posted on GoogleCode (id 2254) on 2014-08-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7744

<b>What data are incorrect or missing?</b>
Leymus arenarius not listed for Nfld.

<b>What data are you expecting instead?</b>
Leymus arenarius not listed for Nfld.

<b>If applicable, please provide an authoritative source.</b>
In our NL checklist, we had this annotation:
[Bowden (1957) reports an introduction of Leymus (Elymus) arenarius at Alexander Bay, neNfld., but does not indicate whether it was a deliberate planting or an introduction from discarded ballast.]  Unless this was shown to be an incorrect ID, we could list this an an ephemeral introduction or a historical record (i.e., no longer present), but I don't know if there are any recent reports of this.st

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-04 20:11Z]

For the time being, I will have to cite our NL list as the source of exclusion - old report is best in this case - and it would imply ephemeral since not found again
