### ISSUE TITLE
2 incorrect synonyms listed

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2025]
[Originally posted on GoogleCode (id 2255) on 2014-08-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/18809

<b>What data are incorrect or missing?</b>
Fluminia arundinacea (Roemer &amp; Schultes) Fries 
Graphephorum arundinaceum (Roemer &amp; Schultes) Ascherson

<b>What data are you expecting instead?</b>
Delete: Fluminia arundinacea (Roemer &amp; Schultes) Fries 
Delete: Graphephorum arundinaceum (Roemer &amp; Schultes) Ascherson
These names are not synonyms of Lolium arundinaceum

<b>If applicable, please provide an authoritative source.</b>
Tropicos
Schedonorus arundinaceus Roemer &amp; Schultes, nom. illeg. hom., is a synonym of: Scolochloa festucacea (Willd.) Link, not Lolium arundinaceum (Schreb.) Darbysh.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-04 20:09Z]

A bizarre mistake given the names are in syn of Scolochloa!

Added the last name to syn of Scolochloa (rej)
