### ISSUE TITLE
status of Lolium multiflorum in Labrador

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2026]
[Originally posted on GoogleCode (id 2256) on 2014-08-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7755

<b>What data are incorrect or missing?</b>
Lolium multiflorum not listed from Labrador.

<b>What data are you expecting instead?</b>
Lolium multiflorum collected in Labrador in 1999.

<b>If applicable, please provide an authoritative source.</b>
In the Nfld. Checklist, we had this annotation:
Lolium perenne subsp. multiflorum has recently been reported from Red Bay, seLab, by the NFRPP 1999 (NDC #99-580).] So, this specimens should be in the Rooms in St. John's.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-04 20:04Z]

HAve to check info
L

**Comment by brouille** [comment]
It is also at MT. I am adding the record
