### ISSUE TITLE
Erigeron ochroleucus not in SK

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#203]
[Originally posted on GoogleCode (id 1644) on 2013-02-26]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3104

<b>What data are incorrect or missing?</b>
Harms 2006 excludes Erigeron ochroleucus (&amp; var scribneri) from Saskatchewan. Also SK CDC is deleting their record(s)
Is there a record known? I'll need to inform SK CDC as well, as currently working on their data exchange (and deleting these records).

<b>What data are you expecting instead?</b>
remove SK from map

<b>If applicable, please provide an authoritative source.</b>
Harms 2006

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-27 13:09Z]

Excluded now (will appear at next compilation). I guess this was misread.
Luc
