### ISSUE TITLE
error and typo of authorities of synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2039]
[Originally posted on GoogleCode (id 2269) on 2014-08-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5468

<b>What data are incorrect or missing?</b>
Equisetum hyemale var. pseudohyemale C.V. Morton
Hippochaete hymealis (Linnaeus) Brubin

<b>What data are you expecting instead?</b>
Equisetum hyemale var. pseudohyemale (Farw.) C.V. Morton
basionym of this name: Hippochaete praealta var. pseudohyemalis Farw.
Hippochaete hymealis (Linnaeus) Milde ex Bruhin  [note spelling of Bruhin]

<b>If applicable, please provide an authoritative source.</b>

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-08-05 17:25Z]

Forgot to mention, the last one should also be Hippochaete hyemalis (Linnaeus) Milde ex Bruhin subsp. affine (Engelmann) W.A.Weber, or some other combination of the varieties, since the name H. hyemalis would be a synonym of the species, not of E. hyemale var. affine.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-08-05 17:31Z]

ITIS and IPNI have the combination (Farw.) C.V.Morton, but not Tropicos.
IPNI has Hippochaete hyemalis (L.) Milde ex Bruhin 1868, and H.h. (L.) Farwell 1916 as a later isonym; Tropicos accepts Farwell's later name, probably because Milde ex Bruhin spelled the epithet as hiemalis, but I don't think that matters now.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-06 13:20Z]

Hippochaete hymealis should not have been in syn since it is syn with the type subsp., not the subsp. present in NA - now removed
Other corrections fixed
