### ISSUE TITLE
add synonym Achillea sibirica?

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#204]
[Originally posted on GoogleCode (id 1673) on 2013-03-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
Achillea alpina

<b>What data are incorrect or missing?</b>
synonym as listed in FNA

<b>What data are you expecting instead?</b>
synonym Achillea sibirica

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 18:28Z]

IT would be adequate to add it if the taxon were the typical var., but what we have is var. multiflora and thus I cannot add the syn. mentioned in FNA

The taxonomy used here is more recent than the FNA treatment
