### ISSUE TITLE
2 'jesupi' synonyms placed under 2 different species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2041]
[Originally posted on GoogleCode (id 2271) on 2014-08-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5483
and http://data.canadensys.net/vascan/taxon/5468

<b>What data are incorrect or missing?</b>
Under E. x mackii: Equisetum variegatum var. jesupii A.A. Eaton
Under E. hyemale subsp. affine: Equisetum hyemale var. jesupi Victorin

<b>What data are you expecting instead?</b>
IPNI lists Victorin's combination as a synonym of A.A.Eaton's name.  If correct, the 2nd name should be E. hyemale var. jesupi (A.A.Eaton) Vict.

Either IPNI is wrong, and they're both different taxa, or both should be synonyms of E. x mackii, according to FNA.

<b>If applicable, please provide an authoritative source.</b>
IPNI; Tropicos lists only Victorin's combination.
FNA only lists A.A.Eaton's name in synonymy with E. xmackii

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-08-05 18:19Z]

That should read x mackaii, not mackii

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-06 13:21Z]

This needs to be checked
