### ISSUE TITLE
authorities of hybrid species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2045]
[Originally posted on GoogleCode (id 2276) on 2014-08-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5412

<b>What data are incorrect or missing?</b>
Dryopteris ×uliginosa (A. Braun ex Dowell) Druce

<b>What data are you expecting instead?</b>
Dryopteris ×uliginosa (A. Braun ex Döll) Kuntze ex Druce 

<b>If applicable, please provide an authoritative source.</b>
IPNI.  There is a lot of confusion about the citation of this species in different databases; some confusing it with Kuntze's name for a S.American sp., so it's possible that the Kuntze ex Druce should just be Druce.  Tropicos doesn't list this hybrid.
IPNI suggests looking at Ballard, Amer. Fern Journ. 50: 106. 1960

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-11 15:40Z]

will require consultation

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-20 18:32Z]

Dryopteris uliginosa may not be an appropriate name for the hybrid carthusiana x cristata because it is based on specimens of cristata x spinulosa from Europe. I checked the Ballard paper.

Thus, instead of making a correction to authorities, I have to make a correction to the name applied erroneously. Note that I did not have a source for this in NA.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-20 19:01Z]

Worse: there seems to be two Dryopteris uliginosa, one based on Aspidium uliginosum Kuntze, a Macrothelypteris synonym, and one based on Aspidium spinulosum var. uliginosum A.Br. ex Doll. The transfer is attributed to different authors.

Thus, D. x uliginosa as per VASCAN is the hybrid cristata x spinulosa. Cody & Britton 89 are the source of my usage of this name for Canada, but it is erroneous.

The name still cannot be applied to our hybrid. I have to use the hybrid formula instead, as there does not appear to be a name for the nothotaxon.

LB
