### ISSUE TITLE
question placement of synonyms var./subsp. americana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2046]
[Originally posted on GoogleCode (id 2277) on 2014-08-07]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5391

<b>What data are incorrect or missing?</b>
These names are listed as synonyms of Dryopteris expansa
Aspidium spinulosum var. americanum Fischer ex Kunze
Dryopteris dilatata subsp. americana (Fischer ex Kunze) Hultén
Thelypteris spinulosa var. americana (Fischer ex Kunze) Weatherby

<b>What data are you expecting instead?</b>
Should be synonyms of Dryopteris campyloptera

Dryopteris spinulosa var. americana (Fischer ex Kunze) Fernald p.p., is listed as p.p. for both D. expansa and D. campyloptera. Should this remain as a p.p., when the other taxa all considered to be synonymous with D. campyloptera?

<b>If applicable, please provide an authoritative source.</b>
Tropicos, Plant List, ITIS, Cody &amp; Britton's Ferns &amp; Fern Allies of Canada.
Hardy Ferns website: http://hardyfernlibrary.com/ferns/listSpecies.cfm?Auto=25
FNA has Fernald's name = D. campyloptera, but Hulten's name = D. expansa.
Since both have the same basionym author, something is not right here.

**Comment by brouille** [comment]
correction made
