### ISSUE TITLE
missing basionym authority in synonym of Woodsia alpina

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2047]
[Originally posted on GoogleCode (id 2278) on 2014-08-07]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5439

<b>What data are incorrect or missing?</b>
Woodsia hyperborea R. Brown

<b>What data are you expecting instead?</b>
Woodsia hyperborea (Liljeblad) R. Brown
basionym of this name: Acrostichum hyperboreum Liljeblad
<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-11 15:43Z]

FNA has the corrected authority - I am uncertain why we have the erroneous one given source if FNA - entry error
