### ISSUE TITLE
common names missing for Solidago brendiae; suggested synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2049]
[Originally posted on GoogleCode (id 2280) on 2014-08-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/27639

<b>What data are incorrect or missing?</b>
common names missing

<b>What data are you expecting instead?</b>
Brenda's goldenrod
Marc, perhaps you can add the French equivalent of Brenda?

<b>If applicable, please provide an authoritative source.</b>
English common name provided by Semple in his 2013 paper, and on his Astereae lab website: https://uwaterloo.ca/astereae-lab/research/goldenrods/classification-and-illustrations/solidago-brendiae

Also, in this page (and mentioned in his Phytonuron publication), a synonym you can add is Solidago lepida DC. var. elongata sensu Fernald (or (Nuttall] Fernald is that is equivalent)]

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-11 15:47Z]

link to SEmple's page is broken - will check later

Marc et Marilyn: please validate vernaculars

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-08-15 21:02Z]

French Name added.

However, the species "Solidago brendae" used in VasCan does not correspond to the name used in the original publication, Solidago brendiae. The epithet "brendae" might be more consistent with the honoured person's given name, "Brenda", but the author seems to have preferred the epithet "brendiae". See http://www.phytoneuron.net/2013Phytoneuron/57PhytoN-Solidagobrendiae.pdf

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-18 14:09Z]

Marc

Ceci �tait une erreur corrigible de l�auteur. Il faut donc la corriger.
C�est Semple lui-m�me qui m�a soulign� le probl�me.

Luc

Le 2014-08-15 17:02, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-08-19 13:11Z]

OK, Merci Luc. Me semblait aussi que ce latin n'était pas conforme à la tradition vaticane.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-20 15:27Z]

English vernacular added from Semple 2013
