### ISSUE TITLE
spelling of genus

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#205]
[Originally posted on GoogleCode (id 2048) on 2014-01-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6414

<b>What data are incorrect or missing?</b>
Molucella

<b>What data are you expecting instead?</b>
Moluccella - checking on the spelling

<b>If applicable, please provide an authoritative source.</b>
IPNI, although IPNI indicates as Moluccella laevis L. not Hudson

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-23 15:01Z]

Molucella is a rej. orth. var. - FNA draft also has Moluccella (should have caught on)
corrected to Moluccella
TX
