### ISSUE TITLE
question about 1 synonym, now syn. with S. brendiae

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2050]
[Originally posted on GoogleCode (id 2281) on 2014-08-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/27484

<b>What data are incorrect or missing?</b>
Solidago lepida var. elongata (Nuttall) Fernald

<b>What data are you expecting instead?</b>
Delete: Solidago lepida var. elongata (Nuttall) Fernald
Fernald missapplied the name Solidago elongata to this taxa.

<b>If applicable, please provide an authoritative source.</b>

Semple: https://uwaterloo.ca/astereae-lab/research/goldenrods/classification-and-illustrations/solidago-brendiae

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-20 15:25Z]

The synonym had already been moved. You did not have the updates when you made the request. now published
