### ISSUE TITLE
missing basionym authors of 3 synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2051]
[Originally posted on GoogleCode (id 2282) on 2014-08-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3499

<b>What data are incorrect or missing?</b>
 Aster terrae-novae Kuntze 
 Aster uliginosus Kuntze 
 Aster uniligulata Kuntze

<b>What data are you expecting instead?</b>
 Aster terrae-novae (Torrey &amp; A.Gray) Kuntze 
 Aster uliginosus (Nuttall) Kuntze 
 Aster uniligulatus (deCandolle) Kuntze  [note ending in -us]

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-11 15:56Z]

Aster uniligulatus : correction FNA needed (?)

corrections done, but needs checking nonetheress concerning last
