### ISSUE TITLE
typos in authority of species: Eleocharis quinqueflora

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2055]
[Originally posted on GoogleCode (id 2286) on 2014-08-11]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5254;jsessionid=AF0F9ED4015BF6B47D5C7B815362AEF0

<b>What data are incorrect or missing?</b>
Eleocharis quinqueflora (Hartman) Schwarz 

<b>What data are you expecting instead?</b>
Eleocharis quinqueflora (Hartmann) O.Schwarz

<b>If applicable, please provide an authoritative source.</b>
IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-08-11 17:04Z]

It is currently corrected but has yet to be compiled (before end of August)

Luc
