### ISSUE TITLE
status of Carex ovalis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2058]
[Originally posted on GoogleCode (id 2292) on 2014-08-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5012?lang=en

<b>What data are incorrect or missing?</b>
status of C. leporina vs. C. ovalis

<b>What data are you expecting instead?</b>
TelaBotanica and the Carex Working Group, below, now accept the name C. leporina over C. ovalis. Will this change be followed in nAm?

<b>If applicable, please provide an authoritative source.</b>
See: http://www.carexworkinggroup.com/pages/february2008.html
and Tela Botanica: http://www.tela-botanica.org/bdtfx-nn-14174-nomenclature

**Comment by brouille** [comment]
ovalis syn leporina
