### ISSUE TITLE
status of Carex vacillans and C. xarctophila in LB

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2062]
[Originally posted on GoogleCode (id 2296) on 2014-09-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5133;jsessionid=F0D44AA246C8D3FDE0DBBC0F909AF354
and
http://data.canadensys.net/vascan/taxon/5150;jsessionid=F0D44AA246C8D3FDE0DBBC0F909AF354

<b>What data are incorrect or missing?</b>
Carex x arctophila is listed for Labrador
Carex vacillans is listed for Labrador

These reports are not listed in our 2000 checklist from NL.  Do you have new reports of C. vacillans and the hybrid C. x arctophila occurring in LB?

I realize that parents of the hybrid both occur in LB, so it's possible, but I haven't seen any reports.

**Comment by brouille** [comment]
correction faite
