### ISSUE TITLE
question about parents of Carex ×crinitoides 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2063]
[Originally posted on GoogleCode (id 2297) on 2014-09-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5153;jsessionid=F0D44AA246C8D3FDE0DBBC0F909AF354

<b>What data are incorrect or missing?</b>
Carex ×crinitoides Lepage - one of the parents - C. crinita var. crinita does not occur in NL

<b>What data are you expecting instead?</b>
Either that parent (C. crinita) should be C. gynandra or Lepage's type from Grand Falls is incorrect. 

<b>If applicable, please provide an authoritative source.</b>
NL Checklist 2000 and VASCAN ranges for the involved spp.

**Comment by brouille** [comment]
gynandra is parent - this has been solved
LB
