### ISSUE TITLE
status of Carex radiata in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2065]
[Originally posted on GoogleCode (id 2299) on 2014-09-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5047;jsessionid=63539CECD19FBA0879EDE2B7214C7123

<b>What data are incorrect or missing?</b>
Carex radiata listed for insular Newfoundland

<b>What data are you expecting instead?</b>
We have no record of this species from Nfld. in our 2000 checkist.  Do you have new records?

**Comment by brouille** [comment]
this was apparently an error - there was no source - removed
L
