### ISSUE TITLE
add orth. var. Spirodela polyrrhiza

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#207]
[Originally posted on GoogleCode (id 2120) on 2014-02-07]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6493?lang=en

<b>What data are incorrect or missing?</b>
alternative spelling for 'polyrhiza'

<b>What data are you expecting instead?</b>
polyrrhiza

<b>If applicable, please provide an authoritative source.</b>
http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=200027353

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-02-10 15:02Z]

FNA is wrong and needs correction: in TROPICOS, polyrhiza is correct, and polyrrhiza is invalid - they both have the same authorship

You want me to add the invalid orthograph? It is not truly necessary.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-02-10 22:58Z]

Ok, agree, not necessary, but hopefuly FNA online will be fixed soon before that invalid name becomes too much in use across North America.
