### ISSUE TITLE
status of Najas gracillima in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2071]
[Originally posted on GoogleCode (id 2307) on 2014-09-12]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6123

<b>What data are incorrect or missing?</b>
Najas gracillima not in insular NL

<b>What data are you expecting instead?</b>
FNA lists insular NL in the range for this species.  They mention not seeing species from several province, don't include NL in this list, which implies that they've seen a specimen of Najas gracillima from NL.
Our checklist cites the FNA reference (Vol. 22:82) and lists swNfld. for the range, but I don't have any data recorded on where this report originated.

**Comment by brouille** [comment]
this is currently corrected in the published version VASCAN
