### ISSUE TITLE
numerous errors in authorities of synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2074]
[Originally posted on GoogleCode (id 2314) on 2014-10-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6715?lang=en

<b>What data are incorrect or missing?</b>
a) Nuphar advena var. variegata (Engelmann ex Durand) A. Gray
b) Nuphar lutea subsp. variegata (Durand) E.O. Beal 
c) Nuphar luteum subsp. variegatum E.O. Beal nom. inval.
d) Nuphar variegatum Engelmann nom. illeg.
e) Nymphaea americana Miller &amp; Standley p.p.
f) Nymphaea fraterna Miller &amp; Standley
g) Nymphaea variegata (Engelmann ex Durand) Fernald
h) Nymphozanthus variegatus (Durand) Fernald

<b>What data are you expecting instead?</b>
a) Nuphar advena var. variegata (Engelmann ex Durand) Engelmann [in A. Gray]
b) Nuphar lutea subsp. variegata (Engelmann ex Durand) E.O. Beal 
c) Nuphar luteum subsp. variegatum E.O. Beal nom. inval.
d) Nuphar variegata Engelmann nom. illeg.
e) Nymphaea americana [sensu?] (Prov.) G.S.Miller &amp; Standley p.p.
f) Nymphaea fraterna  G.S.Miller &amp; Standley
g) Nymphaea variegata (Engelmann ex Durand) G.S.Miller (1902)
h) Nymphozanthus variegatus (Engelmann ex Durand) Fernald

<b>If applicable, please provide an authoritative source.</b>
a,b,f,g,h) ipni

c) This is listed as an orthographic variation in Tropicos, not a nom. invalid., and since the only difference is the gender (mentioned in all of the IPNI entries), is it necessary to include this entry?
d) see remarks under the 2nd entry of Nuphar variegata in IPNI; change gender
e) fna &amp; http://www.biodiversitylibrary.org/page/371911#page/128/mode/1up

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-17 18:20Z]

a)b)e)f)g)h) fixed
d) removed
c) such forms are often encountered in herbaria - if you search Nuphar luteum subsp. variegatum in TRO <http://www.tropicos.org/Name/22600049>, the name is clearly presented as invalid - I am keeping it, though I wonder whether to add (Engelm. ex Durand)
e) why add sensu? it is not provided this way in sources
