### ISSUE TITLE
typos in authority of species: Arctium tomentosum, and error in authority of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2079]
[Originally posted on GoogleCode (id 2320) on 2014-10-08]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2849

<b>What data are incorrect or missing?</b>
Arctium tomentosum P. Miller
Arctium lappa var. tomentosum (Lamarck) A. Gray

<b>What data are you expecting instead?</b>
Arctium tomentosum Miller
Arctium lappa var. tomentosum (Miller) A. Gray
[Lamarck made the combination Lappa tomentosa (Miller) Lamarck]

<b>If applicable, please provide an authoritative source.</b>
MBG, IPNI, IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-10 20:10Z]

added Lappula t.
