### ISSUE TITLE
Spelling of Artemesia

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#208]
[Originally posted on GoogleCode (id 2143) on 2014-03-03]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
1. synonym of Artemisia borealis subsp. borealis
2 &amp; 3. synonym of Artemisia tilesii

<b>What data are incorrect or missing?</b>
noticed the misspelling of Artemesia with: 
1. Artemesia purshii, 
2. Artemesia unalaskensis var. aleutica, and 
3. Artemesia vulgaris subsp. tilesii.

<b>What data are you expecting instead?</b>
Artemisia

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-04 16:15Z]

Marilyn

How embarrassing. Thanks: this is the type of typo that is hard to catch.
Luc
