### ISSUE TITLE
status of Lactuca biennis in LB

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2086]
[Originally posted on GoogleCode (id 2327) on 2014-10-11]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3262

<b>What data are incorrect or missing?</b>
Status of Lactuca biennis in LB

<b>What data are you expecting instead?</b>
We had Lactuca biennis as occurring N to central Labrador.

<b>If applicable, please provide an authoritative source.</b>
Our NL checklist; also Scoggan list it as occurring N to the Hamilton River Basin in Labrador.
Do you have more recent information about it's range?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-15 19:24Z]

the exclusion was in error
