### ISSUE TITLE
typo in authority of subsp. entry and 2 synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2088]
[Originally posted on GoogleCode (id 2329) on 2014-10-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/26590

<b>What data are incorrect or missing?</b>
Pilosella piloselloides subsp. praealta (Gochnat) S. Bräutigam &amp; Greuter
Hieracium florentinum subsp. praealtum (Gochnat) Nägeli &amp; Peter
Hieracium piloselloides subsp. praealtum (Gochnat) Zahn

<b>What data are you expecting instead?</b>
Pilosella piloselloides subsp. praealta (Villars ex Gochnat) S. Bräutigam &amp; Greuter
Hieracium florentinum subsp. praealtum (Villars ex Gochnat) Nägeli &amp; Peter
Hieracium piloselloides subsp. praealtum (Villars ex Gochnat) Nägeli &amp; Peter 1885 
[Zahn published between 1907-1929]

<b>If applicable, please provide an authoritative source.</b>
Villars ex Gochnat is listed in this entry as the author of the basionym and one synonym. It's also listed in Tropicos, FNA (under H. piloselloides) and the Plant List, but not in IPNI.
See: Telabotica
http://www.tela-botanica.org/bdtfx-nn-118622-synthese
Neither IPNI nor Tropicos provide consistent publication info with dates on the Hieracium names published by Nageli &amp; Peter or Zahn.
TelaBotanica lists: Nägeli &amp; Peter: 1885, Hier. Mitteleur., 1 : 530, etc.

**Comment by brouille** [comment]
done
LB
