### ISSUE TITLE
synonym Rubus discolor added to R. bifrons?

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#209]
[Originally posted on GoogleCode (id 2153) on 2014-03-14]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

Rubus discolor is reported with Canadian vegetation classification plots, having the synonym listed will help.(if indeed this synonymy is correct!)

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8925?lang=en

<b>What data are incorrect or missing?</b>
Add Rubus discolor Weihe &amp; Nees

<b>What data are you expecting instead?</b>
Add synonym if suitable

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-03-17 19:02Z]

I have to validate this.

**Comment by brouille** [comment]
Rubus discolor is syn of Rubus ulmifolius, which is not introduced in Canada
I have to exclude the name if I add it - it appears to be misapplied if people intend bifrons
