### ISSUE TITLE
typo in authority of species authority

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2091]
[Originally posted on GoogleCode (id 2333) on 2014-10-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/name/Diphasiastrum%20%C3%97takedae

<b>What data are incorrect or missing?</b>
Diphasiastrum ×takedae Y.A. Ivanenko

<b>What data are you expecting instead?</b>
Diphasiastrum ×takedae Ivanenko

<b>If applicable, please provide an authoritative source.</b>
IPIN, IPNI authors 

Luc, were the 3 NL specimens based on recent annotations?  We didn't list this hybrid in the 2000 checklist.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-20 19:03Z]

Based on specimens of alpinum X sitchense, updated to the nothotaxon name that corresponds to it.

D. x takedae is questionable for eNA, may require another name bec hybrid not exactly same as D. alpinum x D. sitchense var. nikoense (=takedae). But as there is no other name currently, I am (mis?)using it.

The 2000 list did not report all hybrids, did it? So it is not surprizing.

Luc
