### ISSUE TITLE
questionable record of Huperzia porophla in VASCAN Explorer from ACAD

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2093]
[Originally posted on GoogleCode (id 2335) on 2014-10-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/explorer/en/search?view=table&amp;1_f=9&amp;1_o=EQ&amp;1_v_1=Newfoundland+and+Labrador&amp;2_f=24&amp;2_o=CLIKE&amp;2_v_1=&amp;3_f=24&amp;3_o=CLIKE&amp;3_v_1=Huperzia&amp;4_f=14&amp;4_o=EQ&amp;4_v_1=Plantae&amp;5_f=2&amp;5_o=EQ&amp;5_v_1=Lycopodiaceae

<b>What data are incorrect or missing?</b>
The report below from ACAD lists Huperzia porophila from Goose Bay, LB

<b>What data are you expecting instead?</b>
This is most likely a misID, but wondered if this report had been verified?

<b>If applicable, please provide an authoritative source.</b>
VASCAN Records for NL - Huperzia porophila

Herbatim scientific name: Huperzia porophila (Lloyd &amp; Underw.) Holub
Institution: Acadia University
Dataset name: E. C. Smith Herbarium (ACAD)
Catalog No.: 42567
Collector: Gillett, JM; Findlay, WI
Date: 1950-08-19
Province: Newfoundland and Labrador
Locality: Goose Bay, Terrington Basin
Lat./Long.: 53.383 -60.417
Habitat: alder-willow scrub above beach

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-20 18:53Z]

Sue:

This has not been verified. I will not do such a validation myself: I do not have time. It is indeed highly questionable.

However, you should write ACAD and request a validation of the determination of this specimen. There is no image that I could use there, though it says IMG.

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-10-21 00:37Z]

OK, Luc.  I'll ask ACAD for a validation.  Will get back to you later. - 
Sue.
