### ISSUE TITLE
missing authority in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2097]
[Originally posted on GoogleCode (id 2341) on 2014-10-29]

(This is the template to report a data issue for Vascan. If you want to
report another issue, please change the template above.)

What is the URL of the page where the problem occurs?
http://data.canadensys.net/vascan/taxon/6871?lang=en

What data are incorrect or missing?
Amesia latifolia (Linnaeus)

What data are you expecting instead?
Amesia latifolia (Linnaeus) A.Nelson &amp; J.F.Macbr.

If applicable, please provide an authoritative source.
IPNI, Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-31 13:48Z]

In the database, the name is correctly written, yet it does not appear correctly on the web. No correction is required but there appears to be a technical issue when publishing

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-31 13:49Z]

Christian:

Le problème ici paraît être que la donnée est correcte dans le back end mais qu'elle ne s'affiche pas bien à la publication: l'autorité après la parenthèse n'apparaît pas alors qu'elle est dans la bd.


Luc

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2014-11-03 15:21Z]

Cette entrée a été mise à jour le 2014-08-26 et la dernière compilation date du 2014-08-18 donc, les modifications ne sont pas incluses.

À noter aussi que dans le back end l'auteur est: "(Allioni) A. Nelson & J.F. Macbride" et non "(Linnaeus) A.Nelson & J.F.Macbr."

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-11-03 16:52Z]

I know that Tropicos has Amesia latifolia (All.) A.Nelson & J.F.Macbr., but that comination was based on Epipactis latifolia (L.) All.  The basionym of the latifolia combinations is Serapias helleborine L. var. latifolia L., so shouldn't the name be Amesia latifolia (L.) A.Nelson & J.F. Macbr.?  Or is the Linnaean name illeg.?

**Comment by brouille** [comment]
Despite TROPICOS and IPNI, I changed the basionym author to Linnaeus since the basionym is Serapias helleborine var. latifolia L.  
Luc
