### ISSUE TITLE
check on spelling of French vernacular 'elscholtzie'

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#210]
[Originally posted on GoogleCode (id 2157) on 2014-03-18]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6372?lang=en 

<b>What data are incorrect or missing?</b>
Hi Marc - just wondering about the French vernacular spelling with the 'c' in &quot;elscholtzie ciliée&quot; instead of perhaps as &quot;elsholtzie ciliée&quot;?
I think there was an orth. var. on the genus spelled as Elscholtzia previously.

<b>What data are you expecting instead?</b>
elsholtzie ciliée

<b>If applicable, please provide an authoritative source.</b>

Many thanks for checking on this

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-03-20 16:43Z]

You are right, the c had to be deleted. This name was coined by one of us (Alain Cuerrier), so we are quite free to make the correction. Probably a typo. Change made.

Done.
