### ISSUE TITLE
error in entry of variety

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2100]
[Originally posted on GoogleCode (id 2353) on 2014-11-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5372;jsessionid=FA39B736E6C344D0AA95964B0EDA8E76

<b>What data are incorrect or missing?</b>
Athyrium filix-femina var. laurentianum Butters

<b>What data are you expecting instead?</b>
Athyrium angustum var. laurentianum Butters
[and Athyrium filix-femina forma laurentianum (Butters)Fernald]

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI, and Butter's article in Rhodora

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-05 21:35Z]

TROPICOS is erroneous for the f. laur. (we do not cite f. in VASCAN, but I had entered the name in the remarks of the database - I cannot see why I did not catch the error at the time)

IPNI cites correctly
