### ISSUE TITLE
typo in authority of species and synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2103]
[Originally posted on GoogleCode (id 2358) on 2014-11-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9408

<b>What data are incorrect or missing?</b>
Thelypteris quelpaertensis (H. Christ) Ching
Dryopteris quelpaertensis H. Christ
Oreopteris quelpaertensis (H. Christ) Holub

<b>What data are you expecting instead?</b>
Thelypteris quelpaertensis (Christ) Ching
Dryopteris quelpaertensis Christ
Oreopteris quelpaertensis (Christ) Holub

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI, IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-05 21:14Z]

Thanks for the correction.

There is a second problem, however: the spelling of quelpaertensis vs quelpartensis.

I have to check this.
Luc
