### ISSUE TITLE
basionym errors in 2 synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2107]
[Originally posted on GoogleCode (id 2393) on 2015-01-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9416?lang=en

<b>What data are incorrect or missing?</b>
Tofieldia borealis Wahlenberg
Tofieldia minima (Hill) Druce

<b>What data are you expecting instead?</b>
Tofieldia borealis (Wahlenberg ) Wahlenberg (1812)
  basionym: Narthecium boreale Wahlenberg (1805)
Tofieldia minima Druce
  invalid basionym: Phalangium minimum Hill, nom. inval.

<b>If applicable, please provide an authoritative source.</b>
Tropicos &amp; Kew: http://apps.kew.org/wcsp/namedetail.do?name_id=290255
http://apps.kew.org/wcsp/namedetail.do?name_id=284312
&amp; ipni, see Tofieldia minima

**Comment by brouille** [comment]
Narthecium pusilla corrected to pusillum
