### ISSUE TITLE
Najas flexilis in Northwest Territories

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#211]
[Originally posted on GoogleCode (id 2200) on 2014-05-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6122?lang=en

<b>What data are incorrect or missing?</b>
NWT is reporting Najas flexilis as present in NWT based upon McJannet, Argus &amp; Cody 1995 (Rare VasPlts of NT) as well as one additional report: Mackenzie Gas Pipeline project 2004 Volume 3 Part D Section 9 page 137. Hopefully this link will work out. (but I don't know if a specimen collected)
http://www.mackenziegasproject.com/theProject/regulatoryProcess/applicationSubmission/Documents/MGP_EIS_Vol3_%20Part_D_Section_9_S.pdf 
The main website
http://www.mackenziegasproject.com/theProject/regulatoryProcess/applicationSubmission/Applicationscope/EIS.html#threed

<b>What data are you expecting instead?</b>
add if you think this source is credible for this species, otherwise I'll have to search more if there has been a collection

<b>If applicable, please provide an authoritative source.</b>

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-01-07 16:14Z]

I found a NT specimen of Najas flexilis - DAO792970
Kershaw, L. 2003. Mackenzie District; northeast corner of unnamed lake. Beside beaver lodge. Lat. 62.9854 Long. 123.1753

**Comment by brouille** [comment]
Added
