### ISSUE TITLE
Thinopyrum intermedium subsp. intermedium in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#212]
[Originally posted on GoogleCode (id 2208) on 2014-05-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/24139?lang=en

<b>What data are incorrect or missing?</b>
reported for NT, collected by Mike Oldham in 2006. As per NT Infobase.
Shale Creek at Hwy. 1 (Mackenzie Hwy.), about 51 km NW of Fort Simpson on road to Wrigley 62.06276318;122.20570316

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-28 15:41Z]

specimen delivered to DAO. Mike had Stephen Darbyshire check his specimen and Stephen verified the identification.

**Comment by brouille** [comment]
added
