### ISSUE TITLE
missing authority in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2121]
[Originally posted on GoogleCode (id 2466) on 2015-01-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5495?lang=en

<b>What data are incorrect or missing?</b>
Arctostaphylos alpina var. rubra Rehder &amp; E.H. Wilson

<b>What data are you expecting instead?</b>
Arctostaphylos alpina var. rubra (Rehder &amp; E.H. Wilson) Bean

<b>If applicable, please provide an authoritative source.</b>
ipni,tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-30 19:19Z]

Thanks. THe authors of Arctous alpina var. r. were used, apparently
