### ISSUE TITLE
missing English vernacular names

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2123]
[Originally posted on GoogleCode (id 2468) on 2015-02-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5527

<b>What data are incorrect or missing?</b>
common English names are missing for Hypopitys monotropa

<b>What data are you expecting instead?</b>
pinesap, false beechdrops

<b>If applicable, please provide an authoritative source.</b>
Gray's Manual 
You might also want to add basionyms of these synonyms that you have listed:Hypopitys fimbriata (A. Gray) Howell
  Basionym: Monotropa fimbriata A.Gray
Monotropa hypopitys subsp. lanuginosa (Michaux) H. Hara
  Basionym: Monotropa lanuginosa Michx.
Monotropa latisquama (Rydberg) Hultén 
  Basionym: Hypopitys latisquama Rydb.
found in Plant List, IPNI, etc.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 18:31Z]

The vernacular names have been added a while ago, but since I have not published the new entries of VASCAN, you could not know. 

I am copying Marylin in case, so she has your information

Tx

Luc
