### ISSUE TITLE
authority of 1 synonym, rank of a 2nd synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2124]
[Originally posted on GoogleCode (id 2469) on 2015-02-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5536

<b>What data are incorrect or missing?</b>
a)Moneses grandiflora Salisbury ex Gray
b)Pyrola uniflora subsp. reticulata (Nuttall) H. St.John

<b>What data are you expecting instead?</b>
a)Moneses grandiflora Gray
b)Pyrola uniflora var. reticulata (Nuttall) H. St.John

<b>If applicable, please provide an authoritative source.</b>
a) IPNI, Plant List, and Index Synonymique have just Gray (S.F.), 
but Tropicos has Salisb. ex Gray
b) IPNI, Tropicos all have var. for these authors, with no subsp. combination for Pyrola uniflora.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 18:29Z]

Christian:

Pour les taxons suivants:
http://data.canadensys.net/vascan/taxon/15952 Pyrola uniflora subsp. uniflora
http://data.canadensys.net/vascan/taxon/15951 Pyrola uniflora subsp. reticulata

Pourrais tu svp changer le statut de subsp. à var.

Merci
Luc

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2015-02-05 19:40Z]

C'est fait dans le backend
