### ISSUE TITLE
missing English vernacular

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2125]
[Originally posted on GoogleCode (id 2472) on 2015-02-03]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5584

<b>What data are incorrect or missing?</b>
common English vernacular missing

<b>What data are you expecting instead?</b>
Newfoundland bilberry

<b>If applicable, please provide an authoritative source.</b>
our NL checklist

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 15:26Z]

We do not usually provide vernaculars for hybrids, even those with names.

I will forward your suggestion to Marilyn for consideration.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-02-03 15:37Z]

Actually, Luc, it would be more accurate to say that we do not bother coining new  vernacular names for hybrids, or for taxa that do not occur in Canada (i.e. Greenland only).

However, we have been mentioning vernacular names already published elsewhere for hybrids and Greenland only taxa.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-03 15:42Z]

yes, vernaculars are already present for this hybrid and have been placed in the database. I'll place this as 'done'.
If a Greenland-only taxa has a vernacular available, I've been adding it but not spending any time researching for it. Also for hybrids.
