### ISSUE TITLE
incorrect rank of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2133]
[Originally posted on GoogleCode (id 2508) on 2015-03-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/name/Echium%20vulgare

<b>What data are incorrect or missing?</b>
Echium vulgare var. pustulatum (Sibthorp &amp; Smith) Rouy

<b>What data are you expecting instead?</b>
Echium vulgare proles pustulatum (Smith) Rouy

<b>If applicable, please provide an authoritative source.</b>
You probably don't use proles (race), so there's a subsp. entry:
E. vulgare subsp. pustulatum (Smith) Bonnier &amp; Layens 1894 in Index Synonymique; Tropicos lists a later homonym : subsp. pustulatum (Sm.) Em.Schmid  ex Gams 1927

**Comment by brouille** [comment]
Echium vulgare var. pustulatum (Sibthorp & Smith) Rouy removed from synonymy
subsp pustulatum added, though it is sometimes recognized in Europe

LB
