### ISSUE TITLE
typo on variety name; typo in authority of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2137]
[Originally posted on GoogleCode (id 2513) on 2015-03-07]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4407

<b>What data are incorrect or missing?</b>
Gastrolychnis apetala subsp. artica ....
Wahlbergella apetala (Linneaus) Fries

<b>What data are you expecting instead?</b>
Gastrolychnis apetala subsp. arctica ...
Wahlbergella apetala (Linneaus) Th.Fries

<b>If applicable, please provide an authoritative source.</b>
The Flora of the Canadian Arctic Archipelago lists Wahlbergella apetala (L.) Th.Fr., and var. arctica Th.Fr. with lit. citation for var. arctica:
http://nature.ca/aaflora/data/www/casiur.htm
Öfvers. Förh. Kongl. Svenska Vetensk.-Akad. 26, 2: 133. 1870.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-19 19:07Z]

It is strange that both IPNI and TROPICOS have Fries [Elias Magnus] instead of Th. Fries

Note that the citation is for the var., but the same issue arises here: Fries vs Th. Fries?

I will inform them and advise.

Luc

**Comment by brouille** [comment]
Fries, Elias Magnus (1794-1878) = Fries
Fries, Theodor Magnus (1832-1913) = Th. Fries

Wahlbergella apetala (L.) Fr. was published in 1845 - Th. Fries would have been 13 yo then... Unless you tell me that the publication is not 1845?

The citation in Arctic Archipelago appears erroneous...

ALL other current sources use Fries (Fr.)

I am not changing the authorities
