### ISSUE TITLE
parentage and range of this hybrid

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2139]
[Originally posted on GoogleCode (id 2515) on 2015-03-08]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/27246

<b>What data are incorrect or missing?</b>
 Cornus canadensis Linnaeus x Cornus suecica Linnaeus. 

<b>What data are you expecting instead?</b>
 Cornus canadensis Linnaeus subsp. pristina Gervais &amp; Blondeau x Cornus suecica Linnaeus 9inserta). 

<b>If applicable, please provide an authoritative source.</b>
From their 2003 paper, Gervais &amp; Blondeau descibe a new subspecies for the western diploid &quot;cytodemes&quot; of C. canadensis as subsp. pristina.  They also describe the new diplod hybrid C. xlepagei Gervais &amp; Blondeau as a hybrid of Cornus suecica and C. canadensis subsp. pristina, not subsp. canadensis, which is from Nfld. and eastern Canada.  So, C. x lepagei cannot be the taxon from Nfld. and most of Labrador, except far northern Labrador.  See their map, Figure 1. 
They propose no name for C. canadensis subsp. canadensis x C. suecica, but there isn't another name in the list for this combination, unless it's Cornus intermedia (Farr) Calder &amp; Roy L. Taylor, which is currently listed, in part, as a synonym of C. unalascensis.  Cornus canadensis subsp. canadensis x C. suecica is a common hybrid on the northern Peninsula, which is well within the range of the tetraploid subsp. canadensis.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-09 15:12Z]

Sue

I have looked at that paper. I am not certain I accept their taxonomy.
They have been overenthusiastic splitters. We will see.

Luc

Le 2015-03-08 00:19, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2015-03-09 21:21Z]

The problem is that they proposed the name C. x lepagei, so unless 
someone amends or revises their description, the name can't be used for 
all subtaxa of the species involved in the cross.  What the status of C. 
x intermedia?

**Comment by brouille** [comment]
Subsp. pristina is not recognized in FNA Cornus treatment.
x intermedia applies to unalaschkensis, not the F1 hybrids (western type)

Recently, I changed the name of the hybrid to x lepagei = canadensis x suecica
See range in VASCAN, published

Luc
