### ISSUE TITLE
Juncus longistylis new to NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#214]
[Originally posted on GoogleCode (id 2213) on 2014-06-11]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6289?lang=en 

<b>What data are incorrect or missing?</b>
Juncus longistylis reported from NWT in 2006 (I assume a Mike Oldham collection as when he did some field work). Collected in roadside ditch along Hwy 1, might be introduced.

<b>What data are you expecting instead?</b>
add NWT

<b>If applicable, please provide an authoritative source.</b>

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-28 15:44Z]

specimen at DAO

**Comment by brouille** [comment]
added
