### ISSUE TITLE
missing variety name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2145]
[Originally posted on GoogleCode (id 2537) on 2015-03-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7014

<b>What data are incorrect or missing?</b>
Euphrasia williamsii var. Fernald &amp; Wiegand

<b>What data are you expecting instead?</b>
Euphrasia williamsii var. vestita Fernald &amp; Wiegand

<b>If applicable, please provide an authoritative source.</b>
IPNI - I assume you mean var. vestita.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-19 18:59Z]

Yes. The var. name was absent. And it was vestita.

Thanks for catching a booboo on my part!
Luc
