### ISSUE TITLE
synonym an illeg. isonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2146]
[Originally posted on GoogleCode (id 2541) on 2015-03-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7083

<b>What data are incorrect or missing?</b>
Oxalis corniculata var. stricta (Linnaeus) C.C. Huang &amp; L.R. Xu

<b>What data are you expecting instead?</b>
Oxalis corniculata var. stricta (Linnaeus) C.C. Huang &amp; L.R. Xu (1998), nom. illeg. isonym - should be: 
Oxalis corniculata var. stricta (Linnaeus) Sav. ex Trel. (1888)

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
added nom. illeg.
added acc syn
