### ISSUE TITLE
authority of subsp. and synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2148]
[Originally posted on GoogleCode (id 2550) on 2015-03-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7340

<b>What data are incorrect or missing?</b>
Veronica serpyllifolia subsp. humifusa (Dickson ex Withering) Syme
Veronica humifusa Dickson ex Withering

<b>What data are you expecting instead?</b>
Veronica serpyllifolia subsp. humifusa (Dickson) Syme
Veronica humifusa Dickson 1794
Veronica humifusa Dickson ex Withering, 1835 nom. illeg. (isonym)

<b>If applicable, please provide an authoritative source.</b>
Unless Dickson's 1794 publication is illeg., this name should have priority over Dickson ex Withering, which wasn't published until 1835.  He does make clear reference to Dickson's previous article, andit doesn't look like Withering is trying to make a new combination.
Dickson's 1794 publication: Trans. Linn. Soc. London 2: 288
http://www.biodiversitylibrary.org/item/13712#page/323/mode/1up

Withering's article:
https://books.google.ca/books?id=AatWAAAAcAAJ&amp;pg=PR6&amp;lpg=PR6&amp;dq=Botanical+Arrangement+of+British+Plants,+3rd+edition&amp;source=bl&amp;ots=HagXnSxO7e&amp;sig=kLBwOm1sC5XS59_DdQmBziG0Bh4&amp;hl=en&amp;sa=X&amp;ei=k-ASVYLSIMbhsAT5t4L4CA&amp;redir_esc=y#v=onepage&amp;q=Botanical%20Arrangement%20of%20British%20Plants%2C%203rd%20edition&amp;f=false

**Comment by brouille** [comment]
corrections done fide FNA
