### ISSUE TITLE
typo in authority of synonym, also a homonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2149]
[Originally posted on GoogleCode (id 2551) on 2015-03-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7337

<b>What data are incorrect or missing?</b>
Veronica tournefortii Gmelin

<b>What data are you expecting instead?</b>
Veronica tournefortii C.C.Gmelin 1805, nom. illeg. hom., non Villars 1779

<b>If applicable, please provide an authoritative source.</b>
IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:41Z]

These have not been verified since I have not seen the FNA draft of Veronica.

Thanks. It was not in TROPICOS.

Luc
