### ISSUE TITLE
typo in authority name of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2150]
[Originally posted on GoogleCode (id 2554) on 2015-03-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8201

<b>What data are incorrect or missing?</b>
Rumex acetosella subsp. arenicola Y. Mäkinen ex Elve

<b>What data are you expecting instead?</b>
Rumex acetosella subsp. arenicola Y. Mäkinen ex Elven

<b>If applicable, please provide an authoritative source.</b>
IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:35Z]

The infraspecific taxonomy of this taxon in NA will have to be addressed. For the time being, I am keeping all as onoe sp. as per FNA, which aknowledged complexities in the group. Europeans divide into several subspp., but it is difficult to determine which are in NA.
