### ISSUE TITLE
question on validity of one synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2151]
[Originally posted on GoogleCode (id 2555) on 2015-03-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8216

<b>What data are incorrect or missing?</b>
Rumex occidentalis subsp. fenestratus (Greene) Hultén

<b>What data are you expecting instead?</b>
I don't think Hultén made this combination.  IPNI, Tropicos, Kew and other databases do not have this.  Hultén did make the combination R. aquaticus subsp. fenestratus, which you already have listed.

FNA includes this name, but this might be an error, since I don't see the name in any other online resource.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
Sue

Here is my conversation with K. Gandhi (concerning FNA, the source of the erroneous name):

"Kanchi :
    
    I believe an inexistant synonym was added to the list of synonyms under Rumex occidentalis  :
    
    http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250060790
    
    The combination R. occidentalis S. Watson subsp. fenestratus (Greene) Hultén does not appear to have been made ever.
    Rumex aquaticus Linnaeus subsp. fenestratus (Greene) Hultén is the combination by Hultén.
    
    The only combination under R. occidentalis that includes fenestratus is: Rumex occidentalis S.Watson var. fenestratus ( Greene ) Lepage
    http://www.ipni.org/ipni/idPlantNameSearch.do?id=224470-2
    
    I would suggest the name be removed from the list of synonyms in FNA. It is the only source for this name. Unless of course you can provide me with a source for the name.
    
    This was raised by Sue Meades because I had it in VASCAN. I would prefer to remove it for VASCAN if it does not exist."
REsponse from Kanchi:
"Luc is correct.  I checked several publs. and did not find “R. occidentalis subsp. fenestratus”

Thus I am removing this name from VASCAN, but will be adding the Lepage var. combination.

Luc
