### ISSUE TITLE
typos in synonymy of Ficaria verna

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2153]
[Originally posted on GoogleCode (id 2559) on 2015-03-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8515

<b>What data are incorrect or missing?</b>
Ranunculus ficaria subsp. bulbifer Lambinon
Ranunculus ficaria var. bulbifera Albert
Ranunculus verna var. bulbifera Albert

<b>What data are you expecting instead?</b>
Ranunculus ficaria subsp. bulbilifer Lambinon (note the extra 'il')
Ranunculus ficaria var. bulbifer Albert

Albert did not have an 'a' at the end of his name bulbifer, that was added by Á.Löve &amp; D.Löve, when they made their new combination: Ficaria verna subsp. bulbifera 
no combiniation exists of Ranunculus verna var bulbifer Albert, this is probably an error in entry of R. ficaria var. bulbifer Albert

<b>If applicable, please provide an authoritative source.</b>
IPNI

**Comment by brouille** [comment]
correction done
