### ISSUE TITLE
authority of 1 synonym 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2154]
[Originally posted on GoogleCode (id 2560) on 2015-03-28]

(This is the template to report a data issue for Vascan. If you want to
report another issue, please change the template above.)

What is the URL of the page where the problem occurs?
http://data.canadensys.net/vascan/taxon/8520

What data are incorrect or missing?
Ranunculus flammula subsp. reptans (Linnaeus) E. Meyer 

What data are you expecting instead?
Ranunculus flammula subsp. reptans (Linnaeus) Turczaninow (1842)

If applicable, please provide an authoritative source.
E. Meyer made the var. combination(1830); see FNA (for E.Mey.) and Tropicos (for Turcz.)

**Comment by brouille** [comment]
authority subsp. corrected
LB
