### ISSUE TITLE
missing basionym author in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2155]
[Originally posted on GoogleCode (id 2561) on 2015-03-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8504

<b>What data are incorrect or missing?</b>
Ranunculus bulbosus var. valdepubens Briquet

<b>What data are you expecting instead?</b>
Ranunculus bulbosus var. valdepubens (Jordan) Briquet
the basionym of this name is Ranunculus valdepubens Jordan (1861)

<b>If applicable, please provide an authoritative source.</b>
ITIS: http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&amp;search_value=539451
For some reason FNA took down the page to Ranunculus bulbosus.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:24Z]

FNA: I will investigate since the sp. is not listed in the treatment in eFlora
