### ISSUE TITLE
change in rank of basionym due to ICBN rules

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2160]
[Originally posted on GoogleCode (id 2572) on 2015-04-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5374

<b>What data are incorrect or missing?</b>
Athyrium filix-femina var. sitchense Ruprecht

<b>What data are you expecting instead?</b>
Athyrium sitchense Ruprecht

<b>If applicable, please provide an authoritative source.</b>
This was a change dictated by the ICBN.
See rational in IPNI under subsp. sitchense or A. sitchense: 

http://www.ipni.org/ipni/idPlantNameSearch.do?id=60465668-2&amp;back_page=%2Fipni%2FeditAdvPlantNameSearch.do%3Ffind_infragenus%3D%26find_isAPNIRecord%3Dtrue%26find_geoUnit%3D%26find_includePublicationAuthors%3Dtrue%26find_addedSince%3D%26find_family%3D%26find_genus%3DAthyrium%26find_sortByFamily%3Dtrue%26find_isGCIRecord%3Dtrue%26find_infrafamily%3D%26find_rankToReturn%3Dall%26find_publicationTitle%3D%26find_authorAbbrev%3D%26find_infraspecies%3D%26find_includeBasionymAuthors%3Dtrue%26find_modifiedSince%3D%26find_isIKRecord%3Dtrue%26find_species%3Dsitchense%26output_format%3Dnormal

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:13Z]

Change made but change in rank pending action from database manager. Will be done before next publication.
Luc
