### ISSUE TITLE
synonym a rejected name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2162]
[Originally posted on GoogleCode (id 2574) on 2015-04-04]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4487?lang=en

<b>What data are incorrect or missing?</b>
Atriplex hastata Linnaeus
Atriplex patula var. hastata (Linnaeus) Gray

<b>What data are you expecting instead?</b>
Atriplex hastata Linnaeus, nom. rej.
Atriplex patula var. hastata ? A. Gray

<b>If applicable, please provide an authoritative source.</b>
IPNI states that this is now a rejected name, otherwise, Atriplex prostrata Boucher ex DC. (1805) could not have priority over a Linnaean name from 1753.  I assume this affects the Asa Gray combination too.

http://www.ipni.org/ipni/idPlantNameSearch.do?id=26342-2&amp;back_page=%2Fipni%2FeditAdvPlantNameSearch.do%3Ffind_infragenus%3D%26find_isAPNIRecord%3Dtrue%26find_geoUnit%3D%26find_includePublicationAuthors%3Dtrue%26find_addedSince%3D%26find_family%3D%26find_genus%3DAtriplex%26find_sortByFamily%3Dtrue%26find_isGCIRecord%3Dtrue%26find_infrafamily%3D%26find_rankToReturn%3Dall%26find_publicationTitle%3D%26find_authorAbbrev%3D%26find_infraspecies%3D%26find_includeBasionymAuthors%3Dtrue%26find_modifiedSince%3D%26find_isIKRecord%3Dtrue%26find_species%3Dhastata%26output_format%3Dnormal

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 14:27Z]

IPNI kept (Linnaeus) for both the var. and subsp. names
I cannot judge whether or not this is correct - it is possible that in this case, since the name is not illeg. or inval., the original author has to be kept - rejection is an active process (i.e. a choice by a committee)

Luc
