### ISSUE TITLE
Lolium arundinaceum in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#217]
[Originally posted on GoogleCode (id 2216) on 2014-06-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/18809?lang=en

<b>What data are incorrect or missing?</b>
Mike Oldham has collected this taxon in NT in 2006. 
Details: Collected from a roadside along Hwy 3. Frontier Trail at Stag River bridge and roadside pulloff, about 12 km SE of Frank Channel.

<b>What data are you expecting instead?</b>
add NT record

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-06-27 20:36Z]

Marilyn
For me to be able to enter the new province/terr., I need a source, either in the form of a publication I can cite, or the herbarium where specimen is deposited.

Please provide source. I cannot run after all these elements.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-06-28 01:46Z]

yes for sure, I'll get the specimen information on each of these.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-28 15:45Z]

Specimen delivered to DAO and verified by Stephen Darbyshire

**Comment by brouille** [comment]
added
