### ISSUE TITLE
Vernacular names for Alchemilla micans; addition of A. acutiloba to NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2171]
Re: http://data.canadensys.net/vascan/taxon/9698

suggestions for new vernaculars: 
Alchemilla micans: gleaming lady's mantle (FNA vol 9, p.308), shining lady's mantle (Bradshaw 2009)
Alchémille grêle (Tela Botanica)

Alchemilla acutiloba: starry lady's mantle (Bradshaw 2009); Alchémille commune (Tela Botanica)

John McNeill annoted John Maunder's images of Alchemilla on his Digital Flora and reported that his images from the St. John's airport area were of A. acutiloba, a new report for NA, as well as NL.  I guess he didn't have time to add a full description in FNA, but does mention the report on pg. 303 of FNA vol. 9.
See pag. 29 of Bradshaw 2009 for a list of English vernacular names.
Bradshaw 2009: http://archive.bsbi.org.uk/Wats27p315.pdf
shining lady's mantle: http://www.bbc.com/news/uk-england-12032458; 
shining lady's mantle: http://www.botanicalkeys.co.uk/northumbria/VC67RPR2014.pdf

**Comment by manions** [comment]
English vernaculars reviewed/added for all Alchemilla.
Many thanks for the Bradshaw reference.

**Comment by MFavreau** [comment]
French names added
