### ISSUE TITLE
French name incorrect

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2183]
[Originally posted on GoogleCode (id 1967) on 2013-11-27 by ndignard]

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/9126?lang=fr

<b>What data are incorrect or missing?</b>

Incorrect French name of Salix maccalliana &quot;Saule de McCall&quot;
<b>What data are you expecting instead?</b>

Should be replaced by &quot;Saule de MCCalla&quot;

<b>If applicable, please provide an authoritative source.</b>
See the english name. Specific epithet refers to a certain mister McCalla, not McCall

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 13:57Z by luc.brouillet]

Marc

svp valider et corriger

Je crois que Norman est correct

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-01-14 19:26Z]

J'ai vérifié dans la description originale de l'espèce, et les spécimens types ont été récoltés par « McCalla ». Il y aussi une erreur dans FNA, où le nom anglais est « MacCalla's Willow ».
Nom français corrigé dans VasCan.
