### ISSUE TITLE
St.John’s wort vs. St. Jonh's-wort

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2191]
[Originally posted on GoogleCode (id 2455) on 2015-01-25 by jleslie1980]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/145

<b>What data are incorrect or missing?</b>
Very minor discrepancy but the common family name for Hypericaceae does not use a hyphen, yet the common names for each species are hyphenated.  I assume it should be one or the other for all entries.  

james

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 18:13Z by luc.brouillet]

James

Thanks for pointing this out. I am forwarding to the English vernacular editor.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-05 14:53Z]

Many thanks, indeed this was an error - fixed now.
Marilyn
