### ISSUE TITLE
orthographe, nom vernaculaire français «pentstémon»

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2193]
[Originally posted on GoogleCode (id 1299) on 2012-04-04 by 32mars]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/24968?lang=fr

<b>What data are incorrect or missing?</b>
pentstémon à longs sépales

<b>What data are you expecting instead?</b>
penstémon à longs sépales

Dans certains cas, le terme «pentstémon» est synonyme (coquille aussi?)
Voir : 
Penstemon fruticosus var. fruticosus
Penstemon lyallii
Penstemon serrulatus
Penstemon procerus var. procerus

Marie D'Aoûst

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-04-09 19:11Z by luc.brouillet]

Merci madame.

Je transfère votre question à M. Favreau, qui s'occuppe des noms français.

Luc Brouillet

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-05-01 20:45Z]

J'ai corrigé le nom penstémon à longs sépales. L'uniformité était nécessaire. Dans le cas des divers synonymes français en « pentstémon », il faut conserver cette graphie plus ancienne, parce que c'est elle qui est employée dans les sources. Le nom scientifique Penstemon a souvent été épelé « Pentstemon » (comme le souligne Fernald 1950 dans Grays's Manual). Cette autre graphie est plus près de l'étymologie, mais c'est Penstemon qui semble correct.
