### ISSUE TITLE
Draba simmonsii ; English common name

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2194]
[Originally posted on GoogleCode (id 1323) on 2012-04-13 by 32mars]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/name/Draba%20simmonsii?lang=fr

<b>What data are incorrect or missing?</b>
Simmonds whitlowgrass

<b>What data are you expecting instead?</b>
Simmons whitlowgrass?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-04-16 14:50Z by luc.brouillet]

Marilyn

Could you please verify and correct?

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:04Z]

fixed
