### ISSUE TITLE
problème de synonymes non valides

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2195]
[Originally posted on GoogleCode (id 1431) on 2012-10-09 by kim.damboise]

Bonjour, 

J'ai téléchargé la version 17 des données de Vascan (fichier taxon.txt). Se peut-il que le problème (possiblement une erreur à l'exportation) dont j'ai fait mention à Luc Brouillet en septembre ne soit pas réglé dans cette version?
Il semble y avoir des erreurs au genre lorsqu'il s'agit d'une espèce qui a changé de nom genre. Par exemple, pour les ID 10199 à 10207, tous ces taxons synonymes sont listés sous le genre Maianthemum alors qu'il devait être écrit un autre genre (Asteranthemum, Smilacina, Tovaria, Unifolium) selon les noms d'auteurs de chacun de ces entrées.

Merci beaucoup.

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2013-07-10 15:07Z]

Bonjour,
Ce problème est maintenant corrigé : http://data.canadensys.net/ipt/resource.do?r=vascan
Merci est désolé pour le délai.
