### ISSUE TITLE
addition to list of Euphorbia dentata Michaux

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2197]
[Originally posted on GoogleCode (id 1640) on 2013-02-18 by stuart.hay]

Luc: we have a couple of collections of this species of Euphorbia now from Québec. Pierre Guertin has a collection at MT and I have one from La Prairie that isn't in the Herbarium yet. I that there is no report for Ontario, which seems surprising. Stu

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-18 18:48Z by luc.brouillet]

Stu: FOIBIS rapporte cette espèce de l'Ontario, mais elle n'est en effet pas ds VASCAN et je ne sais pourquoi. Je vérifie et l'ajoute.

J'imagine que je pourrai citer MT comme source pour le Québec?

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-19 20:23Z by luc.brouillet]

Comment from Mike Oldham (email 2013-02-19)
"Hi Luc,
Yes, E. dentata is in Ontario.  A Pelee Island collection verified by Tony Reznicek (at MICH).  Hard to know if it is native or introduced.  There are many southern and midwestern species on Pelee Island, some at their northern range limits, but there are also many exotics on the island.  Voss and Reznicek (2012) state that it is native south of Michigan, so perhaps not native in Ontario.  E. davidii (frequently reported as E. dentata) is much more common.
Cheers,mike"

Marilyn, Marc:

Vernacular names are needed. For the EN, I input the EN vernacular provided in FNA12, which is a no-brainer as a matter of fact. You just need to review it.
Marc: French?

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-20 15:41Z by stuart.hay]

Bonjour Luc,
Suivant les commentaires de Mike Oldham, je dois avouer que je ne connaisais
m�me pas Euphorbia davidii.  Cependant, il figure d�j� dans la liste VASCAN
pour le Qu�bec.  Tu dois douter, comme moi, que les sp�cimens identifi�s
comme E.  dentata pour le Qu�bec sont probablement des �chantillons de E.
davidii.  OOOppps!!!
Stu

-----Message d'origine-----
De�: canadensys@googlecode.com [mailto:canadensys@googlecode.com] 
Envoy�: 19 f�vrier 2013 15:24
��: stuart.hay@videotron.ca
Objet�: Re: Issue 1640 in canadensys: addition to list of Euphorbia dentata
Michaux

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-20 16:21Z by luc.brouillet]

Stu

Je crois qu'il faut vérifier...

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-20 18:17Z by luc.brouillet]

Stu

La question vient de m'être posée par l'auteur, via Geoff Levin l'éditeur.
Nous allons prêter les spécimens pour nous assurer que la détermination est
exacte.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-13 13:49Z by luc.brouillet]

tout les spécimens sont E. davidii

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-22 20:28Z]

Noms français corrigés ou ajoutés pour E. dentata et E. davidii.
