### ISSUE TITLE
Pilosella flagellaris authorship

### ISSUE THREAD

**Issue by dshorthouse** [Canadensys/vascan-data#2199]
[Originally posted on GoogleCode (id 1452) on 2012-10-18]

VASCAN entry Pilosella flagellaris http://data.canadensys.net/vascan/taxon/3223 : Authorship &quot;P.D. Sell &amp; C. West&quot; is erroneous and not according to the source cited, please compare
http://wp6-cichorieae.e-taxonomy.eu/portal/cdm_dataportal/taxon/3c3df9bb-a490-40f9-99d1-3ca089daa842/synonymy

Best regards,
Norbert

Dr Norbert Kilian
Cichorieae Portal
Botanic Garden and Botanical Museum Berlin-Dahlem
Freie Universitaet Berlin
Koenigin-Luise-Str. 6-8
14195 Berlin
Germany
E-mail: n.kilian@bgbm.org

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-19 18:06Z]

You are right.
Curiously, both IPNI and TROPICOS have the Sell & West authority, but Plant List has both (the latter considered syn.)
Authority changed.

Thank you

Luc Brouillet

**Comment by dshorthouse** [comment]
[Originally posted on GoogleCode on 2012-10-19 18:09Z]

Luc - did you get a chance to respond to Norbert directly?
