### ISSUE TITLE
Manque un synonyme

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#22]
[Originally posted on GoogleCode (id 851) on 2011-11-15]

Salut

Il manque Solidago graminifolia pour Euthamia graminifolia.....

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-11-15 13:26Z]

Il était là: Solidago graminifolia var. graminifolia. J'ai ajouté l'espèce de toute façon
