### ISSUE TITLE
orthographic error for Inula britannica

### ISSUE THREAD

**Issue by dshorthouse** [Canadensys/vascan-data#2200]
[Originally posted on GoogleCode (id 2516) on 2015-03-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3252

<b>What data are incorrect or missing?</b>
orthographical error, see http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=250067000

<b>What data are you expecting instead?</b>
Inula brittanica

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-09 17:41Z]

David

I checked Tropicos and IPNI - VASCAN is correct.

Luc

Le 2015-03-09 12:08, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by dshorthouse** [comment]
[Originally posted on GoogleCode on 2015-03-09 17:58Z]

Then the name should not be sensu FNA, which has the orthographic error but sensu Tropicos or IPNI.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-09 18:16Z]

I have sent a correction, which will show in eFNA shortly. Thus I am not changing the current reference.

Thanks
Luc
