### ISSUE TITLE
taxonID 7742 disappeared

### ISSUE THREAD

**Issue by dshorthouse** [Canadensys/vascan-data#2201]
[Originally posted on GoogleCode (id 2517) on 2015-03-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7742

<b>What data are incorrect or missing?</b>
Page is missing, should resolve to something.

<b>What data are you expecting instead?</b>
Earlier versions of VASCAN treat this id as Leptochloa fusca (Linnaeus) Kunth

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-18 18:23Z]

David

7742	Leptochloa fusca (Linnaeus) Kunth

In VASCAN, under 27725 Diplachne fusca var. fascicularis (Lamarck) P.M. Peterson & N. Snow
exist the synonym : Leptochloa fusca subsp. fascicularis (Lamarck) N. Snow 7741

Which includes therefore the name you seek to add.

This name would be syn only under subsp. fusca in VASCAN, and it is not in CAnada. Therefore I cannot add it, as we discussed.

Luc
