### ISSUE TITLE
Arnica gracilis not in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#221]
[Originally posted on GoogleCode (id 2231) on 2014-06-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2858?lang=en

<b>What data are incorrect or missing?</b>
I think the addition of Arnica gracilis for occurring in NWT is in error. The VASCAN file cites A. gracilis from Porsild &amp; Cody 1980, however it's Arnica latifolia which is cited not A. gracilis in Porsild &amp; Cody 1980. Nor can I find A. gracilis mentioned in Porsild &amp; Cody 1980, or any further CanFieldNat updates on the NWT Flora. FNA doesn't report A. gracilis from NWT. The NWT Infobase also only reports A. latifolia not A. gracilis.

<b>What data are you expecting instead?</b>
remove NWT unless another source is known for A. gracilis (if there is, I'd like to know please, as I'm working on NWT records - thanks)

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-29 13:49Z]

Removed. It was indeed an error.

thanks
Luc
