### ISSUE TITLE
Taxon ajouté à VASCAN: Penstemon calycosus - noms vernaculaires requis

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2212]
[Originally posted on GoogleCode (id 1002) on 2012-01-26]

Marc et Marilyn:

Suivant FNA et Newmaster, j'ai ajouté P. calycosus pour l'Ont.
Il faut ajouter les noms vernaculaires.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:25Z]

English vernacular finished

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-01-30 22:15Z]

French vernacular done. Thank you Marilyn.
