### ISSUE TITLE
Bellis perennis present in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#222]
[Originally posted on GoogleCode (id 2233) on 2014-06-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2925?lang=en

<b>What data are incorrect or missing?</b>
Bellis perennis present in NWT; located by Michael Oldham in 2006 at Blackstone Territorial park (campground)

<b>What data are you expecting instead?</b>
add NWT

<b>If applicable, please provide an authoritative source.</b>

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-28 15:47Z]

specimen at DAO

**Comment by brouille** [comment]
added
