### ISSUE TITLE
Incorrect author

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2220]
[Originally posted on GoogleCode (id 167) on 2011-01-24]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/16131

<b>What data are incorrect or missing?</b>
Typo in the author: ù(Rydberg) H.F. Lewis

<b>What data are you expecting instead?</b>
Rydberg) H.F. Lewis

<b>If applicable, please provide an authoritative source.</b>
http://www.ipni.org/ipni/idPlantNameSearch.do?id=1047231-2
The species is written incorrectly (I assume) as &quot;fernaldi&quot; (single i) on http://www.theplantlist.org/tpl/record/ild-27280

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-24 19:39Z]

In VASCAN, the species is currently written correctly as fernaldii
The problem is that a symbol was added that should not be there. This problem has been corrected since the publication of VASCAN.
