### ISSUE TITLE
Rework properties files

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2222]
[Originally posted on GoogleCode (id 635) on 2011-08-01]

Once the new file structure is in place for VASCAN (issue 634), the properties files (vascan_en.properties / vascan_fr.properties) need to be reworked. Use the IPT properties as an example

- Group properties in sections
- Naming convention with dots: checklist.msg1
- Change all the ftl files

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2011-11-08 15:03Z]

This should also lead to the cleaning of those files. Some properties are never used.
