### ISSUE TITLE
Add Cronquist / Marie-Victorin / Scoggan families

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2223]
[Originally posted on GoogleCode (id 637) on 2011-08-01]

We decided not to provide alternative classifications based on Cronquist, Marie-Victorin and Scoggan, because it was to complicated for the back-end and for maintenance.

But we should explore the possibility to add Cronquist and Scoggan family names as synonyms in the database and Marie-Victorin families as French vernacular names.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-01 17:17Z]

There would be little difficulty in transforming the Marie-Victorin names into French vernacular names, except in a few cases. I believe I may already have a list of such names in the original databases.

The problem with the Cronquist and Scoggan names is that they are not synonyms as such. Sometimes, they are a different taxonomic concept from the one adopted by APGIII and followed here. In many cases, one family of Cronquist or Scoggan would be split among several in our system, sometimes families already accepted in part by these authors. Thus these families could not be used as synonyms.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-01 17:36Z]

Decision:
Marie-Victorin names are already included as vernacular names (e.g. http://data.canadensys.net/vascan/name/Pinacées).
Cronquist and Scoggan families cannot be added as synomyms, so we won't include them.
