### ISSUE TITLE
Double URL in references

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2224]
[Originally posted on GoogleCode (id 672) on 2011-08-12]

<b>What is the URL of the page where the problem occurs?</b>
Darwin Core archives / References

<b>What data are incorrect or missing?</b>
References for online resources have a URL in the &quot;reference&quot; field and in the &quot;URL&quot; field:

referenceshort: Klinkenberg, 2010+
reference: Klinkenberg, B. (Editor). 2010+. E-Flora BC: Electronic Atlas of the Plants of British Columbia. Lab. for Advanced Spatial Analysis, Department of Geography, University of British Columbia, Vancouver, B.C. http://www.eflora.bc.ca/
url: http://www.eflora.bc.ca/

This is not a problem for the taxon file in the Darwin Core archive, since there is a field for the reference (nameAccordingTo), and one for the url (nameAccordingToID). But for the vernacularnames and the distribution, the fields &quot;reference&quot; and &quot;URL&quot; are concatenated together, so we don't lose the information from the URL field. However, this results in a double URL for online resources:

Klinkenberg, B. (Editor). 2010+. E-Flora BC: Electronic Atlas of the Plants of British Columbia. Lab. for Advanced Spatial Analysis, Department of Geography, University of British Columbia, Vancouver, B.C. http://www.eflora.bc.ca/ http://www.eflora.bc.ca/

<b>What data are you expecting instead?</b>
We need to find a solution for this. One option is to not add a URL in the reference field.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-16 13:30Z]

Peter

It would be fine to remove URLs from the reference, provided that the URL is always provided when we export data.

How do you want to handle this? It seems to be a case by case type of correction.

Luc

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-09-09 16:05Z]

It has been decided that URL should be kept in the reference field for online resources, as it is part of the reference. The URL field is to create a link, which in the case of online resource is the same URL, but in the case of articles a DOI or other.

For the Darwin Core Archive, we are going to continue to concatenate both fields (if not empty), but with a pipe | as delimiter. See issue 719.
