### ISSUE TITLE
3400+ vernacular names have a space at the end

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2228]
[Originally posted on GoogleCode (id 709) on 2011-08-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
Example: http://data.canadensys.net/vascan/name/abronie%20de%20sable
This error is not necessarily visible on the web portal, but it is in the Darwin Core Archive downloads. 

<b>What data are incorrect or missing?</b>
3400+ vernacular names have a space at the end of the name

<b>What data are you expecting instead?</b>
No space

17 names end with ), like: http://data.canadensys.net/vascan/name/bipinnate%20cinquefoil%20(E-Flora%20BC)
1 names ends with a number: http://data.canadensys.net/vascan/name/cressy-greens188

This might be a result of importing from FileMaker Pro. Hopefully we can fix this issue in batch, instead of one by one.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-23 20:06Z]

An excel list with all the names

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-23 20:43Z]

The following function was used to trim all text fields in the database:
UPDATE table_name SET field_name=trim(field_name)

vernacularname
- name: 3860 corrected

taxon
- uninomial: 7
- binomial: 6
- trinomial: 5
- author: 15
- commentary: 193

reference
- referencecode: 2
- referenceshort: 2
- reference: 19
- url: 3

All the other text field were correct.

No data was corrected in the lookup table, this will correct itself after a new update.

The 17 names with ) and the 1 name with a number still needs to be corrected.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-23 21:00Z]

The part between parenthesis has been removed for the following names. Marilyn, you'll have to check if it contained useful information: e.g. a source for that name.

summer snowflakes (Calif.)
ice cold buttercup (R. karelinii)
wet slope buttercup (R. verecundus)
Gray's buttercup (R. grayi)
Earle's buttercup (syn R. uncinatus var earlei)
Idaho buttercup (syn R. uncinatus var parviflorus)
St. Benedict's herb (herba benedicta)
reddish cinquefoil (PLANTS)
old field cinquefoil (FOIBIS)
circumpolar cinquefoil (NatureServe)
finely villous cinquefoil (MA)
high arctic cinquefoil (MA)
far northern cinquefoil (MA)
Ushakov's cinquefoil (MA)
Pedersen's cinquefoil (MA)
Jepson's cinquefoil (MA)
bipinnate cinquefoil (E-Flora BC)
spreading cinquefoil (ITIS)

cressy-greens188 has been changed to "cressy-greens" with source 188 (FNA 2010)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-19 13:52Z]

The cleaning had been done by Peter. This issue is closed.
