### ISSUE TITLE
Habit missing for the following taxa

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2229]
[Originally posted on GoogleCode (id 713) on 2011-08-24]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/23424	empty section
http://data.canadensys.net/vascan/taxon/23439	empty section
http://data.canadensys.net/vascan/taxon/23440	empty section
http://data.canadensys.net/vascan/taxon/23365	empty section
http://data.canadensys.net/vascan/taxon/22666	empty section
http://data.canadensys.net/vascan/taxon/22668	empty section
http://data.canadensys.net/vascan/taxon/9812	hybrid
http://data.canadensys.net/vascan/taxon/9801	hybrid
http://data.canadensys.net/vascan/taxon/9836	species
http://data.canadensys.net/vascan/taxon/9806	species
http://data.canadensys.net/vascan/taxon/9807	species
http://data.canadensys.net/vascan/taxon/9831	species
http://data.canadensys.net/vascan/taxon/23626	species
http://data.canadensys.net/vascan/taxon/9821	species
http://data.canadensys.net/vascan/taxon/13742	species
http://data.canadensys.net/vascan/taxon/23625	species
http://data.canadensys.net/vascan/taxon/9828	species
http://data.canadensys.net/vascan/taxon/23667	species
http://data.canadensys.net/vascan/taxon/23636	species
http://data.canadensys.net/vascan/taxon/23487	species
http://data.canadensys.net/vascan/taxon/23494	variety
http://data.canadensys.net/vascan/taxon/22316	variety
http://data.canadensys.net/vascan/taxon/23600	variety

<b>What data are incorrect or missing?</b>
These taxa are all leaves in the taxonomy, but do not have a habit.

<b>What data are you expecting instead?</b>
The species, varieties and hybrids in the list above should have a habit.
The empty sections should have at least one child taxon. The creation of the child taxon might be blocked by another error.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-25 13:42Z]

http://data.canadensys.net/vascan/taxon/23424	empty section solved
http://data.canadensys.net/vascan/taxon/23439	empty section solved
http://data.canadensys.net/vascan/taxon/23440	empty section solved
http://data.canadensys.net/vascan/taxon/23365	empty section solved
http://data.canadensys.net/vascan/taxon/22666	empty section solved
http://data.canadensys.net/vascan/taxon/22668	empty section solved
Primula section Primula created with P. veris
http://data.canadensys.net/vascan/taxon/9812	hybrid herb added
http://data.canadensys.net/vascan/taxon/9801	hybrid tree added
http://data.canadensys.net/vascan/taxon/9836	species tree added
http://data.canadensys.net/vascan/taxon/9806	species herb added
http://data.canadensys.net/vascan/taxon/9807	species herb added
http://data.canadensys.net/vascan/taxon/9831	species herb added
http://data.canadensys.net/vascan/taxon/23626	species herb added
http://data.canadensys.net/vascan/taxon/9821	species herb added
http://data.canadensys.net/vascan/taxon/13742	species herb added
http://data.canadensys.net/vascan/taxon/23625	species herb added
http://data.canadensys.net/vascan/taxon/9828	species tree added
http://data.canadensys.net/vascan/taxon/23667	species herb added
http://data.canadensys.net/vascan/taxon/23636	species herb added
http://data.canadensys.net/vascan/taxon/23487	species herb added
http://data.canadensys.net/vascan/taxon/23494	variety herb added
http://data.canadensys.net/vascan/taxon/22316	variety herb added
http://data.canadensys.net/vascan/taxon/23600	variety herb added
