### ISSUE TITLE
Abbreviated connecting terms for infrageneric taxa?

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2230]
[Originally posted on GoogleCode (id 726) on 2011-08-31]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2099
Carex section Acrocystis

<b>What data are incorrect or missing?</b>
For infraspecific taxa, we use an abbreviated connecting term:
subsp.
var.

For infrageneric taxa, we use a full English connecting term:
subgenus
section
subsection
series

<b>What data are you expecting instead?</b>
Shouldn't we use abbreviated connecting terms for all names?
subg.
sect.
subsect.
ser.

<b>If applicable, please provide an authoritative source.</b>
http://ibot.sav.sk/icbn/no%20frames/0025Ch3Sec3a021.htm

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-09 13:05Z]

Yes, we should abbreviate to be consistent.
Can a do a global replace?

Luc

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-09-09 16:08Z]

In the scientific name building function, the following has to be replaced to create correct infrageneric names:
subgenus → subg.
section → sect.
subsection → subsect.
series → ser.

We need to check if all names are displayed correctly after this change. The rank names themselves should not change, only within the scientific names (similar to Variety vs var.)

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-05 22:38Z]

Test file looks ok.

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2012-03-06 19:01Z]

fixed in r188
