### ISSUE TITLE
New rank name in DwC-A for pro parte synonyms

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2231]
[Originally posted on GoogleCode (id 727) on 2011-08-31]

<b>On what part of the backend does the problem occur? (No URL)</b>
http://data.canadensys.net/vascan/taxon/15774

<b>What steps will reproduce the problem?</b>
1. In the Darwin Core Archive, pro parte synonyms like the one above have a double parentNameUsageID: 5384|5391
2. This is correct
3. According to the GNA guidelines, their taxonomic status should be written as &quot;proParteSynonym&quot; however, not &quot;synonym&quot; in the Darwin Core Archive.

Since the script to generate DwC-A is able to detect double parentNameUsageIDs, it should be able to write a new taxonomic status too.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-31 20:01Z]

Sorry, parentNameUsageID should be acceptedNameUsageID

**Comment by cgendreau** [comment]
Transfered to https://github.com/Canadensys/vascan/issues/32
