### ISSUE TITLE
Provide genus, subgenus, specificEpithet, infraspecificEpithet in DwC-A

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2234]
[Originally posted on GoogleCode (id 731) on 2011-08-31]

To make the DwC-A even more useful, we could try to provide information for the following terms:
- genus: populate just like the family field, via parentid
- subgenus: populate just like the family field, via parentid
- specificEpithet: binomial for species
- infraspecificEpithet: tri OR quadrinomial for subspecies and varieties.

The easiest way would be to include these fields in the lookup table

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-10 18:22Z]

specificEpithet
ranks: species, subspecies, variety
value: binomial

infraspecificEpithet
ranks: subspecies, variety
value: if quadrinomial { quadrinomial } else { trinomial }

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2012-02-17 13:59Z]

Fixed in r183 but a new database compilation is needed to generate the specificEpithet and infraspecificEpithet.
