### ISSUE TITLE
10 accepted taxa have no distribution

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2236]
[Originally posted on GoogleCode (id 751) on 2011-09-08]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2539
http://data.canadensys.net/vascan/taxon/10719
http://data.canadensys.net/vascan/taxon/3242
http://data.canadensys.net/vascan/taxon/23711
http://data.canadensys.net/vascan/taxon/23679
http://data.canadensys.net/vascan/taxon/9975
http://data.canadensys.net/vascan/taxon/20371
http://data.canadensys.net/vascan/taxon/9738
http://data.canadensys.net/vascan/taxon/9678
http://data.canadensys.net/vascan/taxon/9642

<b>What data are incorrect or missing?</b>
The distribution for this taxa is empty.

<b>What data are you expecting instead?</b>
Either a distribution needs to be added, or the taxa need to be removed from this Canadian checklist.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-19 13:49Z]

2539: information requested from J. Gould (Alta) - Probably EXC
10719: distribution corrected as per FNA06a
3242: NF added
23711 : Primula sect. Primula: calculated distribution - there are now spp. within the taxon 
23679: Rhus subgen. Rhus: calculated distribution - there are now spp. within the taxon
9975: Rhus xborealis : there is a distribution in back-end
20371: distribution must be determined
9738: excluded from NT and YU
9678: query to Cayouette
9642: must find distribution and source

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-19 14:08Z]

9642: FNA does not include this taxon within Canada (or even close to it) - I remove it as there are no source citing it and thus no need for exclusion

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-19 20:47Z]

20371: Rubus lepagei - ajouter source distribution (voir VASCAN) après avoir vérifié article de Bailey

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-20 14:48Z]

2539: J. Gould (emial 11-09-20) confirms that there is no basis for reporting this taxon in Alta or Canada. It is considered EXC

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-22 12:41Z]

20371: Rubus lepagei  - réf ajoutée
point résolu

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-22 12:45Z]

9678: query to Cayouette
Réponse de J. Cayouette (email 2011-09-19)
"Scoggan (vol. p. 481) traite d’un Luzula multiflora var. congesta (Thuill.) Koch, avec L. campestris var. congesta comme synonyme (Thuill.) Meyer. Il doit s’agir de ton L. congesta, j’imagine. Il considère cette variété comme voisine de la var. acadiensis, et rattache ces deux variétés à la subsp. multiflora. Pour sa répartition, c’est curieux car il indique : « introd. in St-Pierre and Miquelon and Nfld. ».
 
À DAO, on a une récolte de SPM identifiée par Boivin, 1950 à L. multiflora var. congesta : « Langlade, Miquelon, Saint-Pierre, M. Le Hors s.n. (DAO) ». Cela ressemble à du multiflora à inflorescence plus condensée. Curieusement, on a également trois spécimens identifiés L. multiflora var. congesta pour BC :
 
- Lulu Island, peat bog, sea level, coll. K. Beamish, F. Vrugtman 60522, June 3, 1960. Det. J.W. Eastham (DAO)
 
- Mt. Seymour Park, roadside edge of Tsuga heterophylla, Thuja plicata, Pseudotsuga forest, alt. 900’, coll. K. Beamish, F. Vrugtman 60561, July 4, 1960. Det. J.W. Eastham (DAO)
 
- Dewdney Trunk Rd., between Haney and Stave Falls, roadside, edge of Thuja plicata & Tsuga heterophylla forest, alt. 450’, coll. K. Beamish, F. Vrugtman 60463, May 26, 1960. Det. J.W. Eastham (DAO).
 
Vu la grande variabilité du L. campestris et tous les noms de taxons qui lui ont été attribués, celui-ci n’est peut-être pas mieux que les autres. Je ne connais pas bien ce groupe et ne peux savoir sur quelles bases Scoggan le dit introduit à TN et SPM, ni pourquoi il a omis de le rapporter pour BC.
 
En examinant superficiellement le matériel, il semble entrer dans la variabilité du L. multiflora. Tu peux partir avec cette hypothèse et continuer tes recherches. D’après les noms des descripteurs, il s’agit probablement d’un taxon européen.
 
Si jamais tu veux examiner le matériel cité, ou le montrer à Stu, on pourrait te l’envoyer."

Le problème reste à résoudre.
