### ISSUE TITLE
Bibliographic citation field in DwC-A

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2238]
[Originally posted on GoogleCode (id 789) on 2011-10-11]

To allow the citation of a single taxon, add the field bibliographicCitation (http://rs.tdwg.org/dwc/terms/index.htm#dcterms:bibliographicCitation) to the Darwin Core Archives.

1. Include the field between &quot;modified&quot; and &quot;source&quot;.
2. The field should be included in the vascan.zip as well as user-generated DwC-A.
3. The content of the field can be calculated during generation:

Brouillet et al. 2010+ {calnameauthor} in VASCAN, the Database of Vascular Plants of Canada. http://data.canadensys.net/vascan/taxon/{taxonid}

4. The meta.xml file needs to be changed once this is done.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-17 16:37Z]

Maybe we could include the consultedDate too? This the same as the publicationDate.

Brouillet et al. 2010+ Acer saccharum Marshall in VASCAN, the Database of Vascular Plants of Canada. http://data.canadensys.net/vascan/taxon/9214 (consulted on 2012-02-17)

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2012-02-28 19:25Z]

Does "consulted on" could be current date?

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-02-29 14:49Z]

Brouillet et al. 2010+. {calnameauthor} in VASCAN, the Database of Vascular Plants of Canada. http://data.canadensys.net/vascan/taxon/{taxonid} (consulted on {generationDate})

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-05 22:40Z]

The test file looks ok (except the domain name of course: http://devdata2.canadensys.net)
