### ISSUE TITLE
Add tomato as vernacular name

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2239]
[Originally posted on GoogleCode (id 844) on 2011-11-09]

We are using the vernacular name &quot;tomato&quot; as an example on our about page (at the very bottom): http://data.canadensys.net/vascan/about

Christian noticed that the name has been removed from the database. The official name is now &quot;garden tomato&quot;: http://data.canadensys.net/vascan/name/garden%20tomato Could we re-add &quot;tomato&quot; as a synonym name or doesn't that make sense. The official French name is &quot;tomate&quot;.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-11-09 21:49Z]

Peter

I am cc'ing this to Marilyn, who made the change.

Luc

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-11-09 22:36Z]

Yes, i already assigned her as the issue owner.


Op 9 nov. 2011 om 16:49 heeft canadensys@googlecode.com het volgende geschreven:

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:19Z]

returned
