### ISSUE TITLE
misspelling of Scientific Name (synonym) of Salix sessilifolia

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#224]
[Originally posted on GoogleCode (id 2339) on 2014-10-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9103?lang=en

<b>What data are incorrect or missing?</b>
synonym Salix sesssilifolia var. villosa (3 's')

<b>What data are you expecting instead?</b>
Salix sessilifolia var. villosa

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-31 13:52Z]

Added FNA sources to names
