### ISSUE TITLE
French vernacular names for Toxicodendron radicans

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2249]
[Originally posted on GoogleCode (id 876) on 2011-12-05]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2524
http://data.canadensys.net/vascan/taxon/2526

<b>What data are incorrect or missing?</b>
Toxicodendron radicans var. radicans is a shrub (and maybe a herb), but has the French name &quot;herbe à puce grimpante&quot;. It seems the climbing one should be &quot;Toxicodendron radicans var. rydbergii&quot;, which is a vine.

Toxicodendron radicans var. radicans has the synonym name &quot;herbe à la puce&quot;, while &quot;Toxicodendron radicans var. rydbergii&quot; has the name &quot;herbe à puce&quot; (no &quot;la&quot;). Both names can probably be used for both plants.

<b>If applicable, please provide an authoritative source.</b>
-

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-01-05 17:27Z]

Thank you for pointing out the problem. I made the necessary corrections. Please note:

1. all poison ivies are called "herbe à puce" (or often "herbe à la puce", but only in printing), even though they are shrubs or vines. This misnomer is too deeply and too anciently in use to be changed.

2. the name "herbe à puce grimpante" referred specifically to T. radicans var. negundo and was transferred by error to var. radicans when var. negundo was put into synonymy of var. radicans. The French name "herbe à puce de l'Est" can accomodate both var. radicans s.s. and var. radicans s.l., so I preferred it to "herbe à puce grimpante".
