### ISSUE TITLE
change SciName? Hypopitys to Monotropa?

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#225]
[Originally posted on GoogleCode (id 2342) on 2014-10-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5527?lang=en

<b>What data are incorrect or missing?</b>
FNA lists Monotropa hypopitys; VASCAN lists Hypopitys monotropa without a reference

<b>What data are you expecting instead?</b>
change to FNA or a reference for use as Hypopitys; thanks

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-29 18:31Z]

Marylin

Phylogenetically, VASCAN is correct and FNA not. I do have to find a reference, however. Thanks for raising this point.

Luc
