### ISSUE TITLE
Populate denormalized DwC term for that rank

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2250]
[Originally posted on GoogleCode (id 1134) on 2012-02-20]

In the Darwin Core Archive, we currently don't populate the denormalized term (class, order, family, genus, subgenus) for a taxon of that rank. We only populate it for its children.

After verifying with Markus Döring &amp; David Remsen, I would populate this field for its own rank:

scientificName=Equisetum
taxonRank=genus
class=Equisetum
order=Equisetaceae
genus=Equisetum

This applies to class, order, family, genus &amp; subgenus, for accepted taxa only (we currently don't populate this for synonyms, and we're going to keep it that way for the moment). It is already done correctly for specificEpithet &amp; infraspecificEpithet.

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2012-02-20 15:54Z]

Example for Equisetum should be:
scientificName=Equisetum
taxonRank=genus
class=Equisetopsida
order=Equisetales
family=Equisetaceae
genus=Equisetum

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-05 22:43Z]

Test file look ok: after_supposed_to_changed.csv
The subgenus is still written as: Equisetum subgenus Equisetum (issue 726)

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-09 17:07Z]

group 1:
class
order
family
subgenus

group 2 (see issue 731):
genus
specificEpithet
infraspecificEpithet

group 1 = populated with the taxon itself or via its parent
group 2 = populated by the uninomial, binomial, trinomial, quadrinomial of the taxon itself

accepted taxa: group 1 + group 2
synonym taxa: group 2

Currently, group 1 is also populated for synonyms, which is somewhat odd as it refers to the parent of the synonym. For Darwin Core, synonyms don't have parents, which is why we left parentNameUsage and higherClassification empty. To be consistent, this should be fixed, so I'm reopening the issue.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-15 01:21Z]

http://data.canadensys.net/vascan/taxon/25639 is currently shared as:
scientificName=Sorengia longifolia (Torrey) Zuloaga & Morrone
acceptedScientificName=Coleataenia longifolia (Torrey) Soreng subsp. longifolia
class=Equisetopsida
order=Poales
family=Poaceae
genus=Coleataenia (!)
subgenus=
specificEpithet=longifolia
infraspecificEpithet= (!)
taxonRank=species (!)

Although not incorrect according to the Darwin Core standard, it is confusing. You cannot build a name from genus + specificEpithet + infraspecificEpithet, since the genus is coming from the accepted taxon.
As discussed above, I propose to share synonyms as such:
scientificName=Sorengia longifolia (Torrey) Zuloaga & Morrone
acceptedScientificName=Coleataenia longifolia (Torrey) Soreng subsp. longifolia
class=
order=
family=
genus=Sorengia
subgenus=
specificEpithet=longifolia
infraspecificEpithet=
taxonRank=species

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2012-03-15 12:37Z]

We need to figure out how to get genus=Sorengia from the taxon 25639. The current method to get the genus of a taxon is to look in the higher hierarchy (for synonyms, we look in the higher hierarchy of the accepted taxon), which doesn't seem to work in that case.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-15 12:55Z]

I'm going to propose a change for the definition of the genus term in
Darwin Core, so we can populate it with "Sorengia". It currently is
counter-intuitive.

-- 
Peter Desmet
Biodiversity Informatics Manager
Canadensys - www.canadensys.net

Université de Montréal Biodiversity Centre
4101 rue Sherbrooke est
Montreal, QC, H1X2B2
Canada

Phone: 514-343-6111 #82354
Fax: 514-343-2288
Email: peter.desmet@umontreal.ca / peter.desmet.cubc@gmail.com
Skype: anderhalv
Public profile: http://www.linkedin.com/in/peterdesmet
