### ISSUE TITLE
French vernacular name for Anthoxanthum nitens

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2251]
[Originally posted on GoogleCode (id 1218) on 2012-03-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7412

<b>What data are incorrect or missing?</b>
French vernacular name is missing

Reported via email by Renée Gaudette

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-12 12:45Z]

Marc

Je ne crois pas que tu étais au courant de ce problème. On ne t'avait pas mis en cc. J'ai mis de problème à ton nom dans le Google-Code.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-06-12 21:04Z]

Il s'agit d'un des nombreux cas où je n'ai pas encore eu le temps d'inscrire le nom vernaculaire de l'espèce au sens large, dans le cas où existent des taxons infraspécifique.

J'y travaille activement en ce moment, et j'ai réglé le cas de l'Anthoxanthum nitens.

Done, je pense.

Marc
