### ISSUE TITLE
Caughuawaga hawthorn misspelled

### ISSUE THREAD

**Issue by peterdesmet** [Canadensys/vascan-data#2252]
[Originally posted on GoogleCode (id 1324) on 2012-04-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8719

<b>What data are incorrect or missing?</b>
The name Caughuawaga in Crataegus suborbiculata is misspelled.

<b>What data are you expecting instead?</b>
It should be Caughnawawa.

<b>If applicable, please provide an authoritative source.</b>
Issue reported by Alain Cuerrier by email.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-04-30 17:32Z by alzycuerrier]

Sorry, but I myself introduced an error...

It should have read Caughnawaga not Caughnawawa...

Sorry again,

Alain

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:11Z]

fixed

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-11-21 09:46Z]

Verify and close.
