### ISSUE TITLE
Tanacetum treatment

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2253]
[Originally posted on GoogleCode (id 1418) on 2012-09-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

What is the URL of the page where the problem occurs? http://data.canadensys.net/vascan/name/Tanacetum%20huronense

<b>What data are incorrect or missing?</b>

Seems to be a problem with Tanacetum huronense and T. bipinnatum in VASCAN.  The former has no vernacular names or synonyms listed while the latter, which is mapped as only occurring in Yukon, is called Lake Huron tansy.

Mike Oldham

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-09-18 20:07Z]

Mike

The correction of English vernacular names by M. Anions is not complete.

I will transmit this query for it will to be corrected.

Thanks
Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-10-18 15:26Z]

This relates to issue 149.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:23Z]

T. bipinnatum as 'dwarf tansy' T. huronense as 'Lake Huron tansy'
