### ISSUE TITLE
Honckenya

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2254]
[Originally posted on GoogleCode (id 1419) on 2012-09-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4312

<b>What data are incorrect or missing?</b>
Honckenya peploides ssp. robusta is mapped from Ontario but does not occur in the province to my knowledge (not mapped from it by FNA).

Mike Oldham

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-09-18 20:10Z]

Mike

I probably could not determine whether the taxon was present or not in Ont. 

It is now removed and will appear changed at the next compilation.

Luc
