### ISSUE TITLE
Crataegus chrysocarpa var. phoenica

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2256]
[Originally posted on GoogleCode (id 1425) on 2012-10-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/name/Crataegus%20chrysocarpa%20var.%20phoenica
<b>What data are incorrect or missing?</b>

Should this be var. phoenicea?  See Phipps, J.B. 2012. Crataegus chrysocarpa Ashe var. phoenicea (ser. Rotundifoliae; Rosaceae). Phytoneuron 2012-30: 1–5. [M.J. Oldham]

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-02 15:31Z]

corrected the authority, since orig. name was superfl.
