### ISSUE TITLE
Crataegus margarettae var. angustifolia

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2258]
[Originally posted on GoogleCode (id 1672) on 2013-03-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/23980

<b>What data are incorrect or missing?</b>
I notice that the authority for Crataegus margarettae var. angustifolia is E.J. Palmer who is also the author for the synonym Crataegus angustifolia, which seems incorrect.  MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-24 19:20Z]

The name C. angustifolia E.J. Palmer has been removed from the edited FNA treatment and is not found in TROPICOS or IPNI. It is not the basionym of the var.

I am removing this name from VASCAN
