### ISSUE TITLE
Alchemilla filicaulis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2259]
[Originally posted on GoogleCode (id 1674) on 2013-03-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8608

<b>What data are incorrect or missing?</b>

Alchemilla filicaulis (and subsp. filicaulis) are introduced in Ontario.
MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-27 15:49Z]

please provide a source I can cite

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2013-03-27 15:57Z]

Morton & Venn (1990)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-27 15:58Z]

gracias
L
