### ISSUE TITLE
Orobanche fasciculata French vernacular check

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#226]
[Originally posted on GoogleCode (id 2343) on 2014-10-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7030?lang=en
just wondering if this is fasciculée or fasciculé with Orobanche? thanks

<b>What data are incorrect or missing?</b>
fasciculée

<b>What data are you expecting instead?</b>
fasciculé

<b>If applicable, please provide an authoritative source.</b>

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-10-29 17:27Z]

Le mot français « orobanche » est un nom féminin selon Le Petit Robert et selon les flores que j'ai consultées. L'orthographe « fasciculée » proposée par Alain Cuerrier est donc correcte.

Marc
