### ISSUE TITLE
Quercus hybrids

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2260]
[Originally posted on GoogleCode (id 1776) on 2013-04-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/5978

<b>What data are incorrect or missing?</b>

Both Quercus x porteri and Quercus x hawkinsiae are listed as Q. rubra X Q. velutina hybrids.  According to FNA Vol. 3, the latter is correct (though spelled Q. x hawkinsii, page 466).
MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-10 17:39Z]

Q. x hawkinsii has priority, x porteri is illeg.
Luc
