### ISSUE TITLE
Triphora trianthophoros spelling

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2263]
[Originally posted on GoogleCode (id 1781) on 2013-05-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/6954

<b>What data are incorrect or missing?</b>

I am wondering about the spelling of trianthophoros.  FNA and all other sources I checked use the spelling trianthophora.  Is there a reference supporting the spelling trianthophoros?  (MJ OLDHAM)

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

FNA Vol. 26

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-13 17:50Z]

Both TROPICOS and IPNI use Triphora trianthophoros  - there is nothing with -phora
FNA may be in error here. I need to verify with authorities.
The only other place with -phora is PLANTS, which followed BONAP or FNA...

Go see the explanation for -os in the TROPICOS entry.

This need to be validated with Gandhi and Zarucchi.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-13 18:33Z]

VASCAN is correct, as are TROPICOS and IPNI.
FNA will be corrected.
Thanks.
