### ISSUE TITLE
Liatris sphaeroidea

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2264]
[Originally posted on GoogleCode (id 1783) on 2013-05-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/11667

<b>What data are incorrect or missing?</b>

Liatris sphaeroidea is considered a synonym of L. aspera in VASCAN based on FNA, but FNA (Vol 21, p. 535) treats it as a hybrid (as does Gaiser in her 1946 revision of Liatris).  Note that Gaiser (1946) reported L. x sphaeroidea from Ontario and it is also listed for Ontario by Morton and Venn (1990).  Only L. sphaeroidea var. salutans (restricted to TX, LA, AR, OK) is synonymized with L. aspera by FNA.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-31 13:42Z]

This entry had not been verified. Thanks.
L
