### ISSUE TITLE
Hordeum jubatum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2265]
[Originally posted on GoogleCode (id 1785) on 2013-06-12]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/7724

<b>What data are incorrect or missing?</b>

VASCAN uses Hordeum jubatum ssp. xintermedium referencing FNA Vol. 24, but FNA uses ssp. intermedium (no x).

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-12 15:26Z]

Mike
Hordeum jubatum subsp. intermedium is a nom. illeg. (see TROPICOS, among others)
originally, the name was published as:
Hordeum jubatum nothosubsp. intermedium Bowden (which clearly indicates a hybrid status, between subsp. jubatum and subsp. breviaristatum) - see CNWG also

This is why I corrected the entry using a multiply sign. I realize that FNA used the name without the x - myabe I should change the citation, but there is none exactly like this. 

For the time being, I will leave as is. I have no means of indicating nothosubsp. in VASCAN, but I can indicate a hybrid with x

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2013-06-12 15:58Z]

Thanks Luc,

mike
