### ISSUE TITLE
Elymus x pseudorepens

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2266]
[Originally posted on GoogleCode (id 1787) on 2013-06-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/7623

<b>What data are incorrect or missing?</b>

Wondering what the basis is for mapping this hybrid from Ontario?  It is not mentioned from Ontario in FNA Vol. 24.  Also, since E. lanceolatus ssp. lanceolatus is not native to Ontario (one of the listed parents), should the hybrid be considered native?  FNA Vol. 24 says this Elymus x pseudorepens consists of hybrids between E. lanceolatus and E. trachycaulus, but they do not specify the ssp. involved (but VASCAN indicates E. lanceolatus ssp. lanceolatus X E. trachycaulus ssp. trachycaulus).

Note that Dore &amp; McNeill (1980) mention a hybrid between E. lanceolatus ssp. psammophilus and E. trachycaulis - could this be the basis for the report of Elymux x pseudorepens from Ontario?

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 13:23Z]

Mike

When you click on list view, you get the source of the map (when it could be
ascertained: we are still improving): Dore & McNeill 1980 in this case. This
needs to be checked as it may be wrong.

More later.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 14:08Z]

Mike

Mike

You are right, pseudorepens is not even mentioned in Dore & McNeill. There may have been successive misinterpretations. In fact, it was initially entered as simply lanceolatus x trachycaulus - probably the source of error.

I will remove the Ont. report for this.

Now should I add the hybrid between the two taxa mentioned? (We should, unless there is data against it).

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2013-06-13 15:10Z]

Luc,

Do you know that Elymux x pseudorepens was described as E. lanceolatus ssp.
lanceolatus X E. trachycaulus ssp. trachycaulus or simply as E. lanceolatus
X E. trachycaulus?  If the former then Ontario should be removed, if the
latter Ontario could remain.  Presumably the hybrid E. lanceolatus
ssp. psamophilus X E. trachycaulus has not been formally named but Gillett
and Senn (1961) and Dore & McNeill (1980) both indicate its occurrence in
Ontario and I don't know of any contrary reports.

mike

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 15:20Z]

Mike

The description of the taxon may have nothing to do with its eventual
interpretation by other specialists. Currently, it is interpreted as var.
lanceolatus. Therefore I will remove it from Ont.

I will add the other hybrid, which is documented.

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2013-06-13 15:37Z]

Luc,

I'm still a bit confused.  What is the basis for your statement that Elymus
x pseudorepens is "currently, ... interpreted as var. lanceolatus".  FNA
does not mention ssp. (or var.) lanceolatus in the treatment of E. x
pseudorepens (senior author of the FNA treatment is Barkworth who is also
senior author on the combination) and in fact mentions E. x pseudorepens
from Michigan where ssp. lanceolatus does not occur.

mike

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 15:39Z]

I have to review all this.
I do not know why we assigned the hybrid to this var.

I cannot answer this now.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-18 13:23Z]

Mike

I managed to retrace the steps that led me to determine pseudorepens as the hybrid of lanceolatus subsp. lanceolatus x trachycaulus. I followed the trail of references in TROPICOS (http://www.tropicos.org/Name/25501278) and checked the Bowden 1965 paper that, based on cytology, determined A. dasystachyum as a parent with A. trachycaulum. The former is a syn of Elymus lanceolatus subsp. lanceolatus
However, Barkworth et al. in the FNA treatment, did not specify which subsp. of lanceolatus recognized was the parent of the hybrid (as you stated), which is a bother and neglectful of them. They do mention this taxon from Michigan west to Alta. etc., but do not list Ont.

Interestingly, Bowden mentions : "Gillett and Senn (1961) reported the natural hybrid, A . psammophilum X A. trachycaulum var. trachycaulum" - thus he considered this entity distinct from pseudorepens

So the statement by Barkworth et al. seems to eliminate Ont., on one hand, though they do not specify the subsp. of lanceolatus involved. And Bowden distinguishes among the two subspp. as producing distinct hybrids.

Would you agree then with the interpretation that pseudorepens has one parent subsp. lanceolatus, and therefore we can remove Ont. from its range? At least for the time being. Dealing with such situations is never certain and rarely perfect.

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2013-06-18 14:25Z]

Hi Luc,

Thanks for the additional explanation.  Yes, I agree it makes the most
sense to remove pseudorepens from Ontario in VASCAN.

mike

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-19 13:50Z]

I added the hybrid reported by Dore & McNeill and recognized by Bowden, pres. in Ont.
