### ISSUE TITLE
http://data.canadensys.net/vascan/taxon/4906?lang=en

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2267]
[Originally posted on GoogleCode (id 1866) on 2013-09-17]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/4906?lang=en

<b>What data are incorrect or missing?</b>

FNA spells this Carex hookerana Dewey while VASCAN uses Carex hookeriana Dewe.  Just wondering if this is intentional?

Thanks,

Mike Oldham

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

MIKE OLDHMA

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-09-20 13:54Z]

Carex hookerana is mispelled FNA <http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242357243>

Indeed, the name must be corrected to hookeriana <see: http://www.tropicos.org/Name/9900195>
It is also spelled hookeriana in IPNI

I inquired with K. Gandhi and J. Zarucchi.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-09-20 14:24Z]

Answer from Kanchi Gandhi:
Luc,

You are correct in changing "hookerana" to "hookeriana"

The "-er" ending in a personal name acts like a vowel for noun genitives, but not so for adjectival epithets.  That was the Roman practice.

Before Heidi does any correction: any question on "Carex muricata var. gracilis"?

Kanchi
