### ISSUE TITLE
Atriplex prostrata native?

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2268]
[Originally posted on GoogleCode (id 1867) on 2013-09-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/4487?lang=en 

<b>What data are incorrect or missing?</b>

FNA considers Atriplex prostrata to be introduced or doubtfully native in coastal eastern North America.  Likely not native in Ontario.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-09-20 14:17Z]

Mike

You are correct: I should put it as int in all provinces west of Ontario. The situation for Québec is probably mixed (was is native in maritime areas)? Native status in the Maritimes should be maintained for now, but it should be discussed in view of the uncertainty in FNA.

In fact, I wonder why native was in all taxa when the sources state int. There was a data entry mistake in the old database here.

Thanks
Luc
