### ISSUE TITLE
Chamaecrista fasciculata 

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2269]
[Originally posted on GoogleCode (id 1869) on 2013-09-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/5703?lang=en

<b>What data are incorrect or missing?</b>

change to ephemeral or introduced

A population was discovered in September 1995 in Brantford, Brant County, by Jeff W. Thompson (pers. comm. to M.J. Odlham 29 Oct. 1995 and 16 May 1996).  The site was disturbed suggesting an introduction, though the property was not planted or seeded.  A photo and correspondence is on file at the Ontario Natural Heritage Information Centre.  The only previous record is a mention in Gray's Manual of Botany (Fernald 1950) from &quot;S. Ont.&quot;, though the source of this report is not known and the species was excluded by Morton and Venn (1990; &quot;ON report needs confirmation&quot;).  No other Ontario reports known, and it is not known if the Brantford population persisted.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-09-24 20:50Z]

epehmeral now
