### ISSUE TITLE
Buddleja davidii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2271]
[Originally posted on GoogleCode (id 1876) on 2013-09-30]

<b>What is the URL of the page where the problem occurs?</b>

http://code.google.com/p/canadensys/issues/entry?template=Vascan%20-%20Data%20issue

<b>What data are incorrect or missing?</b>

see NHIC 6 (attached) [NHIC 6 for VASCAN_2013_09_30.xlsx]

**Comment by brouille** [comment]
It is in VASCAN
http://data.canadensys.net/vascan/taxon/9319
