### ISSUE TITLE
Symphyotrichum racemosum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2273]
[Originally posted on GoogleCode (id 1880) on 2013-10-03]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/3581?lang=en

<b>What data are incorrect or missing?</b>

see NHIC 8 (attached)

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 19:10Z]

It has been excluded from Ont.
