### ISSUE TITLE
Tragopogon mirus

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2274]
[Originally posted on GoogleCode (id 1890) on 2013-10-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/3638?lang=en

<b>What data are incorrect or missing?</b>

Newmaster et al. (1998) is given as the source for this being in Ontario but this lists only Tragopogon x mirus, which is not listed as a synonym in VASCAN (or mentioned in FNA).  FNA does not map T. mirus from Ontario and states that it is an allotetraploid formed from T. dubius and T. porrifolius and that there are also F1 hybrids between the two (presumably T. x mirus?).  Based on the fact that the Ontario record is given as T. x mirus rather than T. mirus, I suspect it is based on the F1 hybrid rather than the allotetraploid.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 19:33Z]

REcently resolved in another issue.
