### ISSUE TITLE
Dichanthelium ovale subsp. villosissimum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2275]
[Originally posted on GoogleCode (id 1909) on 2013-10-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/7563?lang=en

<b>What data are incorrect or missing?</b>

I don't believe this subsp. occurs in Ontario.  To my knowledge only subsp. praecocius and subsp. pseudopubescens occur (e.g. Dore &amp; McNeill 1980, Argus et al. 1982-1987).  The report of Panicum villosissimum in Newmaster et al. (1998) is based on Dichanthelium ovale subsp. praecocius.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-24 13:45Z]

It had been reported also by Morton & Venn, but I believe it is erroneous - I excluded it
