### ISSUE TITLE
Potentilla gracilis var. flabelliformis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2276]
[Originally posted on GoogleCode (id 1919) on 2013-10-31]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/9788

<b>What data are incorrect or missing?</b>

Listed for Ontario (as native) based on specimen(s) at DAO, but not listed for ON in FNA Draft. Has DAO specimen(s) been checked vs. P. pulcherrima?  I was under the impression that Ontario reports of P. gracilis were referrable to P. pulcherrima.  If P. gracilis var. flabelliformis does occur it may be introduced?

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
Mike
P. gracilis var. flabelliformis  was recognized for Ontario in FNA volume 9
http://floranorthamerica.org/Potentilla_gracilis_var._flabelliformis
Therefore, no changement will be made
Luc
