### ISSUE TITLE
Elymus macgregori

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2277]
[Originally posted on GoogleCode (id 1920) on 2013-11-01]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/23667?lang=en

<b>What data are incorrect or missing?</b>

Spelling macgregorii is used in the original description (attached) and in FNA Vol. 24.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 20:29Z]

mcgregorii is correct - a typo on our part, most likely
