### ISSUE TITLE
Juncus trifidus name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2278]
[Originally posted on GoogleCode (id 1970) on 2013-11-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/6311?lang=en

<b>What data are incorrect or missing?</b>

Hi Luc,

Attached article may be of interest re. Juncus trifidus, if you haven't seen it.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 13:43Z]

Mike 

Thanks. Again, I had not seen this. It is interesting that these taxa are sister to both Luzula and Juncus s. str.

I changed the genus to Oreojuncus for trifidus. It will appear at our next compilation. Sue Meades sent me so many corrections before X-mas (and I was too busy then), and I would like to have most of those small ones in too before refreshing.

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2014-01-14 15:38Z]

Glad they were useful Luc.

Is there a way to tell from VASCAN when the data were last
updated/compiled?  Or, if not, can you let me know when it is next done.  I
would like to compare VASCAN to our provincial list again (did so a few
months ago) but will wait until the next update.
