### ISSUE TITLE
Potamogeton ogdenii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2279]
[Originally posted on GoogleCode (id 1984) on 2013-12-05]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8310?lang=en

<b>What data are incorrect or missing?</b>

Considered a hybrid, Potamogeton x ogdenii (P. hillii X P. zosteriformis), by Kaplan et al. (2013).

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 13:01Z]

Thanks Mike

I would not have found this ref. very readily.

Luc
