### ISSUE TITLE
misspelling of SciName - Eritrichium chamissonis synonym

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#228]
[Originally posted on GoogleCode (id 2363) on 2014-12-10]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3766?lang=en

<b>What data are incorrect or missing?</b>
Synonym spelled as 'Eritrichim' - Eritrichim nanum var. chamissonis

<b>What data are you expecting instead?</b>
spelling as 'Eritrichium' - Eritrichium nanum var. chamissonis

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-05 19:29Z]

Thanks. It allowed me to correct two errors in the database.

Happy New Year
Luc
