### ISSUE TITLE
Symphyotrichum racemosum in Ontario?

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2280]
[Originally posted on GoogleCode (id 2167) on 2014-03-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/3581?lang=en

<b>What data are incorrect or missing?</b>

Are you aware of a valid record of Symphyotrichum racemosum from Ontario?

Newmaster et al. (1998) is given as the source for the inclusion of this species in Ontario by VASCAN (Brouillet et al. 2010+), but the species is not mentioned in Newmaster et al. It is also not mentioned for Ontario in Scoggan (1979) or Morton and Venn (1990). Semple et al. (2002) in &quot;Cultivated and Native Asters of Ontario&quot; state that S. racemosum &quot;has erroneously been reported from Ontario, put the plants were either S. lateriflorum or S. dumosum&quot;. It is mapped from Ontario in FNA Vol. 20 (2006), though we are not aware of the source of this report. FNA Vol. 20 states that the species is introduced in Canada.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-24 19:03Z]

I believe the mapping for Ont. in FNA came from mistating Semple et al.

FOIBIS lists it currently, but without status

I am excluding this as misidentification, citing Semple et al. 2002
