### ISSUE TITLE
Cardamine dentata

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2281]
[Originally posted on GoogleCode (id 2178) on 2014-04-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/3965;jsessionid=6EF8C9154294A795B661C04BFF920CB0?lang=en

<b>What data are incorrect or missing?</b>

I believe this plant occurs in Ontario and in fact is the commonest member of the Cardamine pratensis group in the province, with C. pratensis sensu stricto being a rare introduction and C. nymanii only in northern Ontario.  However the relative distribution and status of C. dentata and C. nymanii in the province are poorly known. It is reported from Ontario in various floras (e.g. Morton and Venn's 2000 &quot;Flora of Manitoulin Island&quot;) and there are numerous specimens in herbaria.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-24 18:21Z]

I believe part of the reason I have this as is currently is that this is one taxon that was not properly solved in FNA by Al-Shehbaz. I aknowledge the issue, but it will need more work to solve it properly for Canada
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 19:40Z]

Put as native for now anyway. Issue closed. The larger Canadian distribution will have to be evaluated.
Luc
