### ISSUE TITLE
Hieracium vulgatum non-native in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2283]
[Originally posted on GoogleCode (id 2232) on 2014-06-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/3241;jsessionid=97D73D3D25108B21DC9BFEEF6122CFF6

<b>What data are incorrect or missing?</b>

Hieracium vulgatum is indicated as native to Ontario, though is almost certainly entirely introduced (as considered by NHIC and earlier provincial checklists, e.g. Morton and Venn 1990, Ontario Plant List, as H. lachenalii).  The native component (H. groenlandicum) is not known from Ontario and I suspect may not be known from some other Canadian jurisdictions where H. vulgatum is mapped as native (e.g. BC, PEI).  Note that H. vulgatum (as H. lachenalii) is considered introduced in Michigan (Michigan Field Manual) and New England (Flora Novae Angliae).

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-07-25 20:24Z]

Need to verify other jurisdictions

I must say I do not like this taxonomy of Strother: he lumped too much, but it is difficult to rectify.

Luc
