### ISSUE TITLE
Carex preslii no authority name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2284]
[Originally posted on GoogleCode (id 2317) on 2014-10-06]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

<b>What data are incorrect or missing?</b>

no authority name

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-10-10 20:19Z]

VASCAN shows Steudel currently
