### ISSUE TITLE
Solidago brendae

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2285]
[Originally posted on GoogleCode (id 2348) on 2014-11-09]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/27639

<b>What data are incorrect or missing?</b>

Spelled brendiae in the original description (http://www.phytoneuron.net/2013Phytoneuron/57PhytoN-Solidagobrendiae.pdf) and brendae in VASCAN.

Mike Oldham

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-05 21:38Z]

The spelling in the original description is erroneous and correctible. It was corrected in IPNI, for instance. I consulted with K. Gandhi. J. Semple is aware of the problem (he caused).

Luc
