### ISSUE TITLE
Euphrasia wettsteinii author name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2286]
[Originally posted on GoogleCode (id 2359) on 2014-11-28]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/9820?lang=en

<b>What data are incorrect or missing?</b>

The authority name for Euphrasia wettsteinii should be Gussarova not Gusarova

MJ OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-05 20:21Z]

Mike

Gusarova is the standard form, Gussarova is an alternate form. Both TROPICOS and IPNI use the standard form and so do I.

Luc
