### ISSUE TITLE
Blitum capitatum var. capitatum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2288]
[Originally posted on GoogleCode (id 2374) on 2015-01-15]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/27688?lang=en

<b>What data are incorrect or missing?</b>

Blitum capitatum Linnaeus var. capitatum is an accepted variety name sensu Mosyakin, 2013, according to VASCAN, but Mosyakin (2013) uses subsp. not var.  See attached. [Mosyakin 2013_New nomenclatural combinations in Blitum, Oxybasis, Chenopodiastrum, and Lipandra (Chenopodiaceae).pdf ]

MIKE OLDHAM

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 19:55Z]

Probably slipped when selecting the proper rank
Thanks
Luc

Christian: pourrais tu changer le rang du taxon suivant:
http://data.canadensys.net/vascan/taxon/27688 Blitum capitatum var. capitatum

à subsp.

svp
merci
Luc

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2015-02-06 20:16Z]

C'est fait
