### ISSUE TITLE
Dichanthelium ovale

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2289]
[Originally posted on GoogleCode (id 2376) on 2015-01-17]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/7562

<b>What data are incorrect or missing?</b>

Subsp. praecocius occurs in Ontario (e.g. Dore and McNeill 1980 as Panicum lanuginosum var. praecocius; Argus et al. 1982-1987 as Dichanthelium villosissimum var. praecocius); multiple Ontario specimens in herbaria (e.g. DAO, TRTE, MICH, NHIC).

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
Mike
According to Cat. NW Grasses , most subspp. of D. ovale we have are syn of D. acuminatum subsp. acuminatum, while WCSP (Kew) puts them under Panicum acuminatum subsp. acuminatum

Only D. ovale s. str. remains, and we do not appear to have this taxon in Canada.

Here is the statement in the online Grass Manual (FNA) : "There is considerable overlap among the nine subspecies recognized and, in addition, there appears to be widespread introgression from other Dichanthelium species, such as D. dichotomum, D. sphaerocarpon, D. ovale, and D. aciculare into the D. acuminatum complex, contributing to the taxonomic difficulties."

Thus, I believe changes are in ordre, but not what you expected. All will be under acuminatum.

Luc

**Comment by MichaelOldham** [comment]
Hi Luc,



Not sure if you've seen it, but there is a relatively recent revision of Dichanthelium Section Lanuginosa (which includes the acuminatum and ovale groups).  I much prefer this treatment (Thomas 2015, attached) over the FNA treatment for Ontario taxa.



Cheers,



mike





*********************************************************
Michael J. Oldham
Ontario Natural Heritage Information Centre (NHIC)
Ministry of Natural Resources
300 Water Street, 2nd Floor, North Tower
P.O. Box 7000 Peterborough, Ontario K9J 8M5, Canada
phone 705-755-2160; fax 705-755-2168
michael.oldham@ontario.ca<mailto:michael.oldham@ontario.ca>
NHIC requests: NHICrequests@ontario.ca<mailto:NHICrequests@ontario.ca>
NHIC web page: http://nhic.mnr.gov.on.ca/nhic_.cfm<https://webmail.ontario.ca/owa/redir.aspx?C=oYt4O5oPNUOsn1H3HmanID5fehjWsNAINC47ZwVJniyQjRw8C6vFRPVyWJ9nVJLyVpgnNwrFZYs.&URL=http%3a%2f%2fnhic.mnr.gov.on.ca%2fnhic_.cfm>
Ontario Reptile & Amphibian Atlas:
http://www.ontarionature.org/protect/species/herpetofaunal_atlas.php<https://webmail.ontario.ca/owa/redir.aspx?C=oYt4O5oPNUOsn1H3HmanID5fehjWsNAINC47ZwVJniyQjRw8C6vFRPVyWJ9nVJLyVpgnNwrFZYs.&URL=http%3a%2f%2fwww.ontarionature.org%2fprotect%2fspecies%2fherpetofaunal_atlas.php>
________________________________

**Comment by brouille** [comment]
I guess I have to start over again.
What is difficult, however, is synonymy. Authors rarely do it all...
Luc
