### ISSUE TITLE
Dichanthelium acuminatum subsp. acuminatum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2290]
[Originally posted on GoogleCode (id 2377) on 2015-01-17]

(This is the template to report a data issue for Vascan. If you want to
report another issue, please change the template above.)

What is the URL of the page where the problem occurs?

http://data.canadensys.net/vascan/taxon/7541?lang=en

What data are incorrect or missing?

I don't believe this taxon in the sense used by FNA occurs in Ontario and that any Ontario reports refer to other subsp. of D. acuminatum (primarily ssp. implicatum).  FNA says that subsp. acuminatum &quot;grows primarily ... on the Atlantic and Gulf coastal plains&quot; and it is not included for adjacent Michigan by Voss and Reznicek (2012). 

MIKE OLDHAM

What data are you expecting instead?

If applicable, please provide an authoritative source.

**Comment by brouille** [comment]
dealt with
L
