### ISSUE TITLE
Dichanthelium acuminatum subsp. acuminatum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2291]
[Originally posted on GoogleCode (id 2378) on 2015-01-17]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/7541?lang=en

<b>What data are incorrect or missing?</b>

Hi Luc,  I submitted an issue on this earlier today, but now have a bit more information via correspondence with Tony Reznicek.  The first paragraph below is my question to him; the second paragraph is his response.  He agrees that D. a. ssp. acuminatum does not occur in Ontario.
1.  Dichanthelium acuminatum subsp. acuminatum in the FNA sense does
   not occur in Ontario (VASCAN accepts it for Ontario).  You do not
   include it for Michigan and I presume any Ontario reports are probably
   referable to other subsp. of D. acuminatum.
   
   The type of D. acuminatum is from Jamaica -- and most people give
   the typical subspecies or variety a SE coastal plain distribution in
   the US -- Massachusetts south to Florida,  west to Texas (also in West
   Indies, Mexico, Central America, and n. South America). It's not
   anything we seem to have in SW Michigan, where some plants with this
   distribution do occur (at least not that we have recognized), so no --
   I should think it impossible that it could occur in Ontario.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
please, you should avoid sending issues twice - please check first - comments may be added to a live issue

Luc
