### ISSUE TITLE
Dichanthelium acuminatum, add subsp. columbianum for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2292]
[Originally posted on GoogleCode (id 2379) on 2015-01-17]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/name/Dichanthelium%20acuminatum

<b>What data are incorrect or missing?</b>

Dichanthelium acuminatum subsp. columbianum (sensu FNA) occurs in Ontario and should be added to VASCAN.  I asked Tony Reznicek about this and he is in agreement.  The first paragraph below is my question to him, the subsequent paragraphs are his response.
1.  Dichanthelium columbianum, in the sense you use it in the Michigan
   Field Manual, is presumably the same thing as what Dore and McNeill
   call Panicum columbianum var. siccanum.  FNA calls P. columbianum var.
   siccanum a synonym of D. acuminatum subsp. implicatum, though they
   also recognize D. acuminatum subsp. columbianum.  It seems to make
   more sense to me that D. columbianum (sensu Michigan Field Manual) is
   the same as D. acuminatum subsp. columbianum (sensu FNA) and P.
   columbianum var. siccanum (sensu Dore &amp; McNeill), but perhaps I'm
   missing something.  Unfortunately FNA does not map the subsp.
   separately or map them separately or list states and provinces of
   occurrence.
   
   This issue comes about because Hitchcock &amp; Chase, in their big
   monograph of Panicum, split P. columbianum into different entities,
   the northern one of which (called Panicum tsugetorum) was the one that
   occurs in Ontario.  Nowadays, everyone lumps Panicum tsugeorum with P.
   columbianum. But, wanting to still  recognize Panicum tsugetorum as a
   variety, Dore &amp; McNeill used the varietal name var. siccanum -- the
   type of which I have not seen. But if you do not even recognize
   varieties, our Ontario and Michigan plant simply becomes Panicum
   columbianum or Dichanthelium columbianum =  D. acuminatum subsp.
   columbianum.
   
   What FNA is suggesting is that Dore &amp; McNeil were mistaken to use
   the name &quot;var. siccanum&quot; to apply to P. tsugetorum (or columbianum
   s.l.) As I've not seen the type, I don't have an opinion here.
   
   But regardless, Ontario plants are certainly Dichanthelium
   acuminatum subsp. columbianum in the sense of FNA despite their
   putting the name &quot;var. siccatum&quot; into the synonymy of D. acuminatum
   subsp. implicatum

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
done with revision of sect. Lanuginosa
L
