### ISSUE TITLE
Euthamia gymnospermoides

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2293]
[Originally posted on GoogleCode (id 2381) on 2015-01-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/3158

<b>What data are incorrect or missing?</b>

Ontario specimens of Euthamia gymnospermoides have been revised to E. caroliniana (e.g. at MICH, pers. comm. A. A. Reznicek).  E. gymnospermoides should be &quot;excluded&quot; for Ontario for VASCAN and E. caroliniana added.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-30 19:40Z]

Issue 1642 has been merged into this issue.
