### ISSUE TITLE
Grindelia hirsutula

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2294]
[Originally posted on GoogleCode (id 2382) on 2015-01-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/3181

<b>What data are incorrect or missing?</b>

I am not aware of the basis for the listing of this species in Ontario by FNA, but presume the FNA authors saw one or more specimens.  If it does occur in Ontario (and I'm okay with accepting the FNA report), then it is almost certainly exotic rather than native.  Traditionally only one Grindelia species has been accepted for Ontario (G. squarrosa) and considered introduced (e.g. Morton and Venn 1990).  

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
hirsutula now excluded 
LB
