### ISSUE TITLE
Huperzia miyoshiana

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2296]
[Originally posted on GoogleCode (id 2384) on 2015-01-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/6586

<b>What data are incorrect or missing?</b>

The Ontario specimens have been examined by Weston Testo (Univ. Vermont) who is working on the genus and found to belong to other species (primarily H. selago).  H. miyoshiana should be excluded for ON.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 19:29Z]

There was no source anyway, so I wonder why Ont. was in the range at all.

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-02-24 11:47Z]

It was in originally because I had collected material in northern Ontario
that was identified as H. miyoshiana by Bob Preston (MICH).  More recently
revised to H. selago by W. Testo.

mike
