### ISSUE TITLE
Juncus bufonius var. halophilus Buchenau & Fernald in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2297]
[Originally posted on GoogleCode (id 2385) on 2015-01-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/6261

<b>What data are incorrect or missing?</b>

Occurs in Ontario. Collected from Attawapiskat, Kenora District, in 2000 (M.J. Oldham 24504 at MICH, NHIC, PRA, TRTE; !A.A. Reznicek) and mapped from five additional James Bay coast sites in Ontario by Dutilly et al. (1958). Possibly overlooked elsewhere.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 19:35Z]

The taxonomy of this taxon has been controversial and many do not recognize vars., which may be why the taxon was ignored. It is recognized by the world monographer, however, and I am following him now.

Thanks
Luc
