### ISSUE TITLE
Carex membranacea in ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2298]
[Originally posted on GoogleCode (id 2386) on 2015-01-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/name/Carex%20membranacea

<b>What data are incorrect or missing?</b>

Documented new for Ontario in 2014 by Sam Brinker from the Niskibi Cape in the Hudson Bay lowland (specimens sent to MICH, CAN, TRT).  Specimen verified by A.A. Reznicek.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 20:12Z]

I used MICH to indicate that Tony validated it. No surprize here, though.
