### ISSUE TITLE
Equisetum pratense not in Nunavut

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#230]
[Originally posted on GoogleCode (id 2365) on 2014-12-18]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5472?lang=en

<b>What data are incorrect or missing?</b>
Equisetum pratense isn't known in NU. The distribution reference for NU is Cody &amp; Britton 1989, but the map dot is definitely in NWT not NU.
I've also searched multiple herbaria online without any results for E. pratense in NU.

<b>What data are you expecting instead?</b>
remove NU

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 21:56Z]

I checked and you are correct.
Luc
