### ISSUE TITLE
Linnaea borealis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2300]
[Originally posted on GoogleCode (id 2388) on 2015-01-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/4201

<b>What data are incorrect or missing?</b>

I'm trying to sort out Linnaea borealis subsp.  VASCAN lists subsp. borealis for eastern Canada and subsp. longiflora for BC, but provides no taxonomic authority.  Other floras and checklists do otherwise.  Eg.  Morton and Venn (1990) list only subsp. longiflora for Ontario.  Voss and Reznicek (2012) state that Michigan plants are ssp./var. longiflora and that ssp./var. borealis is Alaskan.  Haines (2011) accepts subsp. americana (synonym of subsp. longiflora in VASCAN) for New England.  Thanks!!

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-22 13:32Z]

This has been reported previously. I have yet to find a good source to untangle

Luc
