### ISSUE TITLE
Crataegus x media

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2306]
[Originally posted on GoogleCode (id 2400) on 2015-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8724

<b>What data are incorrect or missing?</b>

Remove from VASCAN? Listed for ON in VASCAN based on Newmaster et al. (1998) but not mentioned in Newmaster et al.  FNA Vol. 9 states that &quot;only cultivars are seen in North America&quot;, and doesn't specifically mention Ontario. Phipps &amp; Muniyamma 1980 (A taxonomic revision of Crataegus (Rosaceae) in Ontario) mention that it is only known in cultivation in Ontario.  Any evidence of occurrence in the wild in Ontario?, otherwise exclude?

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 19:59Z]

I will exclude because only in cultivation, citing FNA
Luc
