### ISSUE TITLE
Crataegus x persimilis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2307]
[Originally posted on GoogleCode (id 2401) on 2015-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8725

<b>What data are incorrect or missing?</b>

Treated as a species not a hybrid in FNA Vol. 9, though stated to be &quot;plausibly a hybrid complex&quot;.  Change to species rather than hybrid in VASCAN?

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 20:01Z]

It is part of his interserial hybrids, but he advocated that some were ± stabilized.

I will follow FNA and remove the x
