### ISSUE TITLE
Crataegus ater

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2309]
[Originally posted on GoogleCode (id 2403) on 2015-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8650

<b>What data are incorrect or missing?</b>

Further to my previous &quot;issue&quot; on this species, I found correspondence from Jim Phipps stating &quot;Delete from list, no longer recognized&quot; (J.B. Phipps pers. comm. 4 Dec. 2003). Also see Phipps and Muniyamma (1980, page 1684). &quot;A very rare segregate of C. pruinosa. Hardly worth inclusion.&quot; (J.B. Phipps pers. comm. 26 May 1993). Remove from VASCAN, taxon no longer recognized.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 20:08Z]

I agree not to recognize it as an entity. There is no problem with the associated data (they disappear).

But what of the name? If it has been used in a Canadian or Ontario document or list, should I dispose of it somehow?

Unfortunately, the notion of rare segregate of Phipps is difficult to interpret. Should I synonymize it with pruinosa? Or ask Phipps?

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-02-09 22:01Z]

Probably safest to ask Phipps.  Or synonymize with pruinosa.  Agree it is good to deal with these names that have been used.

**Comment by brouille** [comment]
synonymized with pruinosa var pruinosa
