### ISSUE TITLE
Crateagus chrysocarpa var. faxonii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2310]
[Originally posted on GoogleCode (id 2404) on 2015-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/9675

<b>What data are incorrect or missing?</b>

Remove for ON.  Listed for ON in VASCAN with no source provided.  Not listed for ON in FNA Vol. 9, Phipps &amp; Muniyamma (1980), Newmaster et al. (1998) or any other source I know of other than VASCAN.  Source for occurrence in Ontario?

Mike Oldham

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 20:10Z]

Note that my source was his initial draft. I had to wait to the very end of the process for a clean copy, and then I did not have time to review all Rosaceae anew.

REmoved.
Luc
