### ISSUE TITLE
Crataegus chrysocarpa var. phoenicea

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2312]
[Originally posted on GoogleCode (id 2406) on 2015-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8659

<b>What data are incorrect or missing?</b>

Further to my previous issue on this taxon, the name Crataegus chrysocarpa var. phoeniceoides (used in FNA Vol. 9)should replace Crataegus chrysocarpa var. phoenicea in VASCAN, as per the attached article.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 20:25Z]

Again, updates were not made from the draft to the final version. Phipps made so many changes (taking many years to do so...)

Luc
