### ISSUE TITLE
Crataegus chrysocarpa var. subrotundifolia

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2313]
[Originally posted on GoogleCode (id 2407) on 2015-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/23944

<b>What data are incorrect or missing?</b>

Add as native to AB, SK, ON, QC based on FNA Vol. 9

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 20:28Z]

Thanks
L
