### ISSUE TITLE
Crataegus jonesiae

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2314]
[Originally posted on GoogleCode (id 2408) on 2015-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8686

<b>What data are incorrect or missing?</b>

CHANGE TO EXCLUDED OR DOUBTFUL FOR ONTARIO IN VASCAN? Reported from Ontario by VASCAN though not included for Ontario in FNA Vol. 9 (2014), Phipps and Muniyamma (1980) or Morton and Venn (1990). Presence in Ontario unconfirmed.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 21:12Z]

I simply removed the Ont. entry
Luc
