### ISSUE TITLE
Crataegus macracantha var. divida

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2315]
[Originally posted on GoogleCode (id 2409) on 2015-01-21]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9669

<b>What data are incorrect or missing?</b>

REMOVE FROM VASCAN? No infraspecific taxa recognized in VASCAN Vol. 9.

Mike Oldham

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 21:14Z]

Issue 2410 has been merged into this issue.

**Comment by brouille** [comment]
Crataegus divida, the basionym for C. macracantha var. divida, is placed in synonymy of C. macracantha in FNA 9 - done so in VASCAN now
