### ISSUE TITLE
Crataegus chrysocarpa var. vigintistamina

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2316]
[Originally posted on GoogleCode (id 2411) on 2015-01-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

https://bioticson.natureserve.org/biotics/services/page/ElementSubnational/0.html?type=N1010966,67

<b>What data are incorrect or missing?</b>

Add for Ontario in VASCAN (currently listed as doubtful based on Newmaster et al., who don't mention it); mapped for Ontario in FNA Vol. 9.

In FNA Vol. 9 for taxon 103g (Crataegus chrysocarpa var. vigintistamina; page 600) the author and place of publication is given as J. B. Phipps, J. Bot. Res. Inst. Texas 1: 1008. 2007.  However that publication (attached) makes no mention of Crataegus chrysocarpa var. vigintistamina.  Where then was this name published?

Mike Oldham

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 20:30Z]

Mike

The publication is not attached, but this is a good question and should have been caught. Major problems if it was not since it would happen to have been published in FNA 9!

Needs to query.

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-02-09 20:53Z]

Not sure how I messed up (probably working through species too quickly), but it looks like the FNA treatment is just fine.  Publication attached.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-09 21:21Z]

ANyway, correction made using FNA
