### ISSUE TITLE
Packera paupercula

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2317]
[Originally posted on GoogleCode (id 2414) on 2015-01-22]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3334

<b>What data are incorrect or missing?</b>

Suggest adopting the attached for infraspecific taxonomy of P. paupercula (Mahoney &amp; Kowal 2008), published since the relevant FNA volume.  Adopting this would add 3 vars of P. paupercula to VASCAN: var. paupercula (all but Greenland + St. Pierre &amp; Miquelon); var. savannarum (ON, based on a specimen identified by R. Kowal); and var. pseudotomentosa (ON).  This would also result in the removal of P. plattensis from Ontario (specimens are P. paupercula var. pseudotomentosa).  This taxonomy has been adopted in other regional floras (e.g. Voss &amp; Reznicek 2012 for Michigan).
[Mahoney & Kowal 2008_Three new varieties of Packera paupercula in midwestern and southeastern North America.pdf ]

MIKE OLDHAM

**Comment by brouille** [comment]
Mahoney & Kowal 2008_Three new varieties of Packera paupercula in midwestern and southeastern North America

The pdf did not attach - could you please provide full citation so that I can find it?

Luc

**Comment by brouille** [comment]
Mahoney, Alison-Mckenzie; Kowal, Robert, R., 2008: Three new varieties of Packera paupercula Asteraceae, Senecioneae in midwestern and southeastern North America. Novon 18(2): 220-228

found - no need to bother
L

**Comment by brouille** [comment]
Kowal does not mention savannarum for Ont. in the paper - where is the specimen identified to this var. for Ont., so I can cite the herbarium as source?
Luc

**Comment by MichaelOldham** [comment]
The only Ontario collection is from Windsor, Essex County, M.J. Oldham #2373 (NHIC, WIS), collected in 1982 and identified by R.R. Kowal in 2008.

Mike
