### ISSUE TITLE
Physocarpus intermedius

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2318]
[Originally posted on GoogleCode (id 2416) on 2015-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/9746?lang=en

<b>What data are incorrect or missing?</b>

What is the basis for excluding from Ontario (no source provided)?  The species is listed by Scoggan (1978, Flora of Canada, Vol. 3) from Lambton, Bruce and Welland Counties (as P. opulifoilus var. intermedius) and mapped from Ontario in FNA Vol. 9.

MIKE OLDHAM 

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 21:25Z]

The basis was FOIBIS where it is SU

As I said, I did not have time to validate all data against FNA 9
