### ISSUE TITLE
Platanthera hyperborea

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2321]
[Originally posted on GoogleCode (id 2419) on 2015-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/6919?lang=en

<b>What data are incorrect or missing?</b>

According to Sheviak (2011; attached) and Paul Catling (pers. comm.) P. hyperborea occurs in North America.  Sheviak (2011) cites specimens from Yukon, Manitoba, Ontario, and Newfoundland.  Both Sheviak and Catling have identified recent northern Ontario collections as P. hyperborea.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 20:16Z]

Are you saying you attached a file? I cannot find it.

If there, then it should be in N. Qc.
Luc

**Comment by brouille** [comment]
@MichaelOldham 
Could you send me the pdf by email? Attachments were lost, apparently, when moved to Github.
Luc
