### ISSUE TITLE
Polygonatum biflorum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2322]
[Originally posted on GoogleCode (id 2420) on 2015-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/2745

<b>What data are incorrect or missing?</b>

VASCAN recognizes subsp. melleum and subsp. biflorum, though FNA mentions only var. melleum.  I don't think the combination Polygonatum biflorum subsp. melleum has been made.  Switch to var. melleum and var. biflorum?

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
Have to reconsider the whole taxonomy here anyway. 
Later.

A new publication will be done Monday.
Luc
