### ISSUE TITLE
Potamogeton ×scoliophyllus Hagström

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2323]
[Originally posted on GoogleCode (id 2421) on 2015-01-23]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8333?lang=en

<b>What data are incorrect or missing?</b>

According to Kaplan et al. ([Kaplan et al 2013_Revision of chromosome numbers of Potamogetonaceae, a new basis for taxonomic and evolutionary implications.pdf], p. 450; attached), the correct name for this hybrid should be Potamogeton x luxurians.

MIKE OLDHAM

**Comment by brouille** [comment]
the correct name is indeed luxurians, but the hybrid does not seem to occur in Ontario or Québec, all material being assigned to the one parent
thus I did not add luxurians and rejected scoliophyllus (so that we would know what is happening)
Luc
