### ISSUE TITLE
 Hagström

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2324]
[Originally posted on GoogleCode (id 2422) on 2015-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/8333?lang=en

<b>What data are incorrect or missing?</b>

Further to my previous issue on this hybrid, the Ontario and Quebec records are both apparently P. illinoensis (see page 471 of Kaplan et al. 2013).  Potamogeton ×scoliophyllus should be excluded from ON and QC.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 21:34Z]

AS I understand it from the paper you provided, this taxon in fact should simply be synonym of P. illinoensis.

If so, would there be records of the hybrid for Canada, then under luxurians? In other words, is luxurians even in Canada? The author only reports specimens from USA.

I would simply place the taxon in synonymy and this will resolve the issue. Agreed?

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-02-09 22:04Z]

Agreed, although the taxon itself is not a synonym, just that Canadian reports of it were in error and based on P. illinoensis.  I don't know of any evidence of occurrence in Canada.  Previous reports in error.

**Comment by brouille** [comment]
I re-read the paper, and P. scoliophyllus is indeed synonymous with illinoiensis. This solves the problem. No need to invoke luxurians either since it is not reported for Canada.
