### ISSUE TITLE
Salix x glatfleteri

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2327]
[Originally posted on GoogleCode (id 2425) on 2015-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/search/?q=Salix&amp;lang=en&amp;page=10

<b>What data are incorrect or missing?</b>

Not in VASCAN, but reported from Ontario in FNA Vol. 7, page 38.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 21:41Z]

New nothotaxon added.

It is difficult to find hybrids in the literature. Thanks for alerting me to this one.

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-02-09 22:06Z]

Agreed. I haven't included hybrids without a hybrid binomial in the Ontario list, though there are many and even harder to find!
