### ISSUE TITLE
Salix x hudsonensis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2328]
[Originally posted on GoogleCode (id 2426) on 2015-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/search/?q=Salix&amp;lang=en&amp;page=10

<b>What data are incorrect or missing?</b>

Not in VASCAN. Collected in 2000 from Cape Henrietta Maria, Kenora District, Ontario (M.J. Oldham 25088 at DAO, NHIC, det. G.W. Argus).

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 21:48Z]

I have to identify the parents. The taxon is not mentioned in FNA, nor is S. groenlandica.
Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-02-09 22:11Z]

Salix x hudsonensis is mentioned in FNA (p. 80) as an S. arctica X S. arctophila hybrid.

**Comment by brouille** [comment]
added
