### ISSUE TITLE
Schizachyrium littorale

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2330]
[Originally posted on GoogleCode (id 2428) on 2015-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/9635

<b>What data are incorrect or missing?</b>

Change to Doubtful for Ontario.  Several authors have expressed doubt that Great Lakes material belongs to S. littorale (e.g. Dore and McNeill 1980; Voss &amp; Reznicek 2012; Lonard &amp; Judd 2010, page 656; attached).  I have also been unable to separate Great Lakes dunes material (supposedly S. littorale) from S. scoparium.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 21:43Z]

I put it as doubtful.
L
