### ISSUE TITLE
Sedum rupestre

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2332]
[Originally posted on GoogleCode (id 2430) on 2015-01-23]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/4673?lang=en

<b>What data are incorrect or missing?</b>

Ontario records of Sedum reflexum (e.g. Morton and Venn 1990, Newmaster et al. 1998) and S. rupestre (FNA Editorial Committee 2009) presumably all refer to S. thartii.  Sedum reflexum is excluded from North America by Gallo and Zika (2014; attached).

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-23 18:10Z]

Already modified
Luc

Le 2015-01-23 13:09, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-01-23 18:19Z]

Thanks Luc,

I thought I'd already sent that issue, but searched and couldn't find it;
perhaps I sent it via an email.

Sorry to be inundating you with issue emails, but I'm doing a big push on
cleaning up our vascular plants Elements Table and thought I might as well
pass on comments and questions that arose as a result.

When is the next update to VASCAN planned and how frequently do they occur?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-01-23 18:23Z]

No worry. I just wanted you to know I had done this one. VASCAN has not
been republished recently, which is why this may happen.

It was via email indeed. You see why googlecode is preferred.

Luc

Le 2015-01-23 13:19, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :
