### ISSUE TITLE
Solidago rigidiuscula

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2333]
[Originally posted on GoogleCode (id 2431) on 2015-01-23]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3496

<b>What data are incorrect or missing?</b>

Elevate Solidago rigidiuscula to the rank of species following Semple et al. ([Semple, Tong, Oldham & Bakowsky 2012_Solidago pallida new to Ontario and Canada.pdf ]; attached, see page 4).  This makes sense since S. pallida was recently elevated by VASCAN and S. rigidiuscula also occurs in Canada (only Ontario).  Although Solidago speciosa subsp. speciosa var. rigidiuscula is excluded from Ontario in VASCAN, it is present (on Walpole Island) with vouchers in herbaria (also legally listed as an Endangered species in Canada).  If adopting the splitting of S. speciosa, then S. speciosa sensu stricto should be removed from VASCAN and replaced by S. pallida (already in), S. jejunifolia (already in), and S. rigidiuscula (name change needed).

MIKE OLDHAM

**Comment by brouille** [comment]
I neglected doing this one
done now
Luc
