### ISSUE TITLE
Tragopogon mirus

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2336]
[Originally posted on GoogleCode (id 2437) on 2015-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/name/Tragopogon%20mirus

<b>What data are incorrect or missing?</b>

I suspect the Ontario report of T. mirus is actually T. x neohybridus (T. dubius X T. porrifolius).  Morton and Venn (1990) and Newmaster et al. (1998) report T. x mirus (T. dubius X T. porrifolius) on which the VASCAN report of T. mirus is based.  We don't have any way to know for sure (other than locating and examining specimens), but since Morton and Venn (1990) reported it as a hybrid and T. mirus is rare and only known from a few sites in the western U.S., I would rather see T. mirus listed as Excluded or Doubtful in Ontario and T. x neohybridus added.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 20:08Z]

Mike

You are correct in this. I was rather uncomfortable with this entry.

I do not have a source for the exclusion, however (a source stating what you said above). Is there a source concerning the hybrid.

One small concern: one parent is given as pratensis var. tortilis. But I do not believe this is an accepted name anyway.

Another issue: I know both parents are introduced, but the hybrid was spontaneously produced in situ, and not introduced. What status should we give? Native?

The latest FOIBIS report the nothotaxon in Ont., so there is a source.

Luc

Luc

**Comment by MichaelOldham** [comment]
[Originally posted on GoogleCode on 2015-02-09 21:26Z]

RE: Another issue: I know both parents are introduced, but the hybrid was spontaneously produced in situ, and not introduced. What status should we give? Native?

I have puzzled over this.  To me it seems quite odd to consider a hybrid between two introduced species to be native.  I would think that in many cases of such hybrids we would not know whether the hybrid was produced in situ here, or if the hybrid was produced in Europe (or elsewhere) and introduced as a hybrid, particularly for cultivated hybrids, hybrids that can reproduce vegetatively or ones that are partially fertile.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-09 21:29Z]

Mike

There are clear cases of introduced hybrids. In most, one parent is
missing in NA, if not both.

However, when a hybrid is found with both parents present�

Still, does not solve the issue. Think on this: is Tragopon mires,
restricted to NA, then introduced?

Luc

Le 2015-02-09 16:26, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :
