### ISSUE TITLE
add Thaspium chapmanii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2337]
[Originally posted on GoogleCode (id 2438) on 2015-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/1750?lang=en

<b>What data are incorrect or missing?</b>

Most Ontario records of T. barbinode are actually T. chapmanii (B.E. Wofford, pers. comm.), which has more dissected leaves and flowers that are creamy yellow, rather than sulfur yellow. True T. barbinode has only been collected in Niagara R.M., where it has not been seen recently. Reports of T. barbinode from adjacent Michigan are now referred to T. chapmanii (Voss &amp; Reznicek 2012).

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 21:13Z]

Thaspium chapmannii added

Marc et Marilyn: svp ajouter vernaculaires
http://data.canadensys.net/vascan/taxon/28721 [si publié]

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-02-06 21:19Z]

Nom français ajouté.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-07 15:47Z]

English vernacular added
