### ISSUE TITLE
Add Tulipa gesneri for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2338]
[Originally posted on GoogleCode (id 2439) on 2015-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/1797?lang=en

<b>What data are incorrect or missing?</b>

Add Tulipa gesneri as ephemeral for Ontario.  Found at several places on the Bruce Peninsula (Grey and Bruce Counties) by Joe Johnson (specimen at MICH), probably persisting from garden throw-outs.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 20:06Z]

Newmaster & RAgupathy 2005 mention it so I am using FOIBIS as source
I am using the status ephemeral you propose

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 21:11Z]

Marc et Marilyn:

Noms vernaculaires pour Tulipa gesneriana
http://data.canadensys.net/vascan/taxon/28720 [si publié]

Merci
Luc

**Comment by brouille** [comment]
@MFavreau 
Marilyn and Marc: could you provide vernaculars please ?

Luc

**Comment by manions** [comment]
English vernacular added

**Comment by MFavreau** [comment]
French name added.

Marilyn,
L.H. Bailey (Standard Cyclopedia of Horticulture, vol. 3) calls this species « common garden tulip » and « late tulip », and also mentions a _Tulipa didieri _ which may or may not be a synonym... Just wondering...
