### ISSUE TITLE
Deutzia scabra add

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2343]
[Originally posted on GoogleCode (id 2444) on 2015-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/name/Hydrangeaceae

<b>What data are incorrect or missing?</b>

Add to VASCAN. Collected in 2006 from disturbed woods at Dufferin Islands Nature Area (Niagara Parks Commission), Niagara Regional Municipality (M.J. Oldham 32582; MICH, NHIC; det. A.A. Reznicek Jan. 2013). Several shrubs were seen and the species appeared non-planted. No other Ontario records known.

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 21:42Z]

Added with source NEwmaster & Ragu... 2005

Marc et Marilyn: svp ajouter noms vernaculaires
data.canadensys.net/vascan/taxon/28724 [si publié]

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-07 15:46Z]

English vernaculars added

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-02-12 21:36Z]

Done en français también.
