### ISSUE TITLE
Exochorda racemosa add

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2346]
[Originally posted on GoogleCode (id 2447) on 2015-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/name/Rosaceae

<b>What data are incorrect or missing?</b>

Collected in 2006 from disturbed woods at Dufferin Islands Nature Area (Niagara Parks Commission), Niagara Regional Municipality (M.J. Oldham 32583; MICH, NHIC; det. A.A. Reznicek Jan. 2013). Several shrubs were seen and the species appeared non-planted. No other Ontario records known.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 21:59Z]

I wonder why this was not caught when we were editing this treatment for FNA 9...

MArc et Marilyn: vernaculaire svp

http://data.canadensys.net/vascan/taxon/28727

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-07 15:45Z]

English vernacular added

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-02-10 21:29Z]

French names added for genus and species
