### ISSUE TITLE
Ficus carica add

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2347]
[Originally posted on GoogleCode (id 2448) on 2015-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/172?lang=en

<b>What data are incorrect or missing?</b>

First documented in Ontario in 2007 from a railway yard in Windsor, Essex County (M.J. Oldham #34791 at DAO, NHIC).

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 15:20Z]

It is cited in FOIBIS so I used this source. Hope you do not mind.
Luc
