### ISSUE TITLE
Helleborus niger add

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2348]
[Originally posted on GoogleCode (id 2449) on 2015-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/204?lang=en

<b>What data are incorrect or missing?</b>

Discovered by Charles P. Cecile (pers. comm.) in a wooded area near the Halton-Wellington border south of Erin, Wellington County, in 2009 (specimen in HAM, OAC).

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 20:21Z]

Mike

Added with HAM as source. You realize this was not in FNA and may be a new record for Canada and North America.

Marilyn and Mark:
Please provide vernaculars for Helleborus niger. This should be easy.
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-05 15:08Z]

English vernaculars added.
Also found in New York and Michigan (Explorer and New York Floral Atlas)
Thanks for the addition Mike.
Marilyn

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-02-06 21:05Z]

French name added from TelaBotanica. L'espèce est présente en France.

Marc

(done)
