### ISSUE TITLE
Packera pseudaurea var. semicordata add for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2349]
[Originally posted on GoogleCode (id 2450) on 2015-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/3338?lang=en

<b>What data are incorrect or missing?</b>

Add for Ontario. Recently collected in NW Ontario (M.J. Oldham #35610, det. R. Kowal); three earlier collections at LKHD all det. by R. Kowal (E. North, pers. comm. 2008). Not listed for Ontario by Morton and Venn (1990) or FNA Vol. 20. Moist areas in northwestern Ontario. See Barkley (1962). Ontario plants are var. semicordata. 2 records from 2 Far North study sites, also recent records from Windsor and Lake of the Woods area.

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-26 18:39Z]

I now wonder about Manitoba...
Luc
