### ISSUE TITLE
Symphyotrichum lanceolatum ssp. heperium

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2351]
[Originally posted on GoogleCode (id 2452) on 2015-01-24]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

http://data.canadensys.net/vascan/taxon/3547

<b>What data are incorrect or missing?</b>

Why is S. lanceolatum ssp. hesperium var. hesperium, following FNA Vol. 20, not recognized as with varieties of S. lanceolatum ssp. lanceolatum?

MIKE OLDHAM

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 18:39Z]

Since the subsp. is monotypic, there is no need to add the var. infraspecies, contrary to subsp. lanceolatum with 4 vars.

Note that var. hesperium is placed in synonymy. 

Luc
