### ISSUE TITLE
Viola sororia var. novae-angliae

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2356]
[Originally posted on GoogleCode (id 2569) on 2015-04-02]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9497

<b>What data are incorrect or missing?</b>

Should V. sororia var. grisea (Fernald) L.E. McKinney be the accepted name for this taxon?  See attached [Little & McKinney 2010_Four nomenclatural changes in Viola (Violaceae).pdf].

**Comment by brouille** [comment]
change done
