### ISSUE TITLE
Viola epipsila

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2357]
[Originally posted on GoogleCode (id 2570) on 2015-04-02]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9487?lang=en

<b>What data are incorrect or missing?</b>

var. repens accepted in FNA draft and published in attached article [Little & McKinney 2010_Four nomenclatural changes in Viola (Violaceae).pdf] but not mentioned in VASCAN.

**Comment by brouille** [comment]
The Viola taxonomy has been corrected according to FNA 6, which was published recently. There were many issues that were unresolved in the initial draft.
Luc
