### ISSUE TITLE
Malus sieboldii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2358]
http://data.canadensys.net/vascan/taxon/27932?lang=en

According to FNA Vol. 9 Malus sieboldii is an illegitimate name; they use M. toringo.

MIKE OLDHAM

**Comment by MFavreau** [comment]
French vernaculars added.

Marilyn ( @manions ), you may want to add the English vernaculars provided by FNA9 p. 479.

Marc

**Comment by manions** [comment]
English vernaculars added
