### ISSUE TITLE
Matthiola incana

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2359]
http://data.canadensys.net/vascan/name/Matthiola%20incana

List as ephemeral (my preference) or excluded for Ontario.  Reported by Sabourin (Sabourin, A. 1991. Guide des Cruciferes Sauvages de l'est du Canada. Privately published, Blainville, Quebec. 249 pp.) from Sillsville, Lennox & Addington County, though not listed for Ontario by Morton and Venn (1990) or Mulligan (2000) or FNA Vol. 7. This species reportedly does not usually persist in a given locality for long periods (Rollins 1981).

MIKE OLDHAM

**Comment by brouille** [comment]
Entered as ephemeral for Ont., though if it is not reported again, it should be excluded ultimately.
Luc
