### ISSUE TITLE
whoops a nom. inval. is listed as an accepted species

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#236]
[Originally posted on GoogleCode (id 2375) on 2015-01-16]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4932?lang=en

<b>What data are incorrect or missing?</b>
Carex lasiocarpa subsp. americana (Fernald) Hultén nom. inval. is listed as an accepted species but Carex lasiocarpa subsp. americana (Fernald) D. Löve &amp; J.-P. Bernard is also listed as the accepted species

<b>What data are you expecting instead?</b>
place Carex lasiocarpa subsp. americana (Fernald) Hultén nom. inval. as a synonym? or list with Carex lasiocarpa subsp. americana (Fernald) D. Löve &amp; J.-P. Bernard?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
Carex lasiocarpa subsp. americana (Fernald) Hultén nom. inval. now syn of Carex lasiocarpa subsp. americana (Fernald) etc. since based on same basionym
Luc
