### ISSUE TITLE
Phlox subulata

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2362]
Vascan URL:
http://data.canadensys.net/vascan/taxon/8076

Seems quite unlikely that Phlox subulata is native in Manitoba (or subsp. subulata).

MIKE OLDHAM

**Comment by brouille** [comment]
You are right. I will change to introduced.

Note that I had not validated any source here, waiting for the FNA draft. I will add sources where I can at the same time.
Luc



De : MichaelOldham <notifications@github.com<mailto:notifications@github.com>>
R�pondre � : Canadensys/vascan-data <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mardi 14 avril 2015 14:58
� : Canadensys/vascan-data <vascan-data@noreply.github.com<mailto:vascan-data@noreply.github.com>>
Objet : [vascan-data] Phlox subulata http://data.canadensys.net/vascan/taxon/8076 (#2362)


Seems quite unlikely that Phlox subulata is native in Manitoba (or subsp. subulata).

MIKE OLDHAM

�

**Comment by brouille** [comment]
Sources were there at the subsp. level.

I had misread the Man source. It is indeed int.

Luc

De : MichaelOldham <notifications@github.com<mailto:notifications@github.com>>
R�pondre � : Canadensys/vascan-data <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mardi 14 avril 2015 14:58
� : Canadensys/vascan-data <vascan-data@noreply.github.com<mailto:vascan-data@noreply.github.com>>
Objet : [vascan-data] Phlox subulata http://data.canadensys.net/vascan/taxon/8076 (#2362)


Seems quite unlikely that Phlox subulata is native in Manitoba (or subsp. subulata).

MIKE OLDHAM

�
