### ISSUE TITLE
Polemonium reptans

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2364]
Vascan URL:
http://data.canadensys.net/vascan/taxon/8087?lang=en

Polemonium reptans (and var. reptans) is a garden escape in Ontario and not native (treated as exotic by Scoggan (1979) and Morton and Venn (1990).

MIKE OLDHAM

**Comment by brouille** [comment]
Do not know why it was native in VASCAN�
L

De : MichaelOldham <notifications@github.com<mailto:notifications@github.com>>
R�pondre � : Canadensys/vascan-data <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mardi 14 avril 2015 17:16
� : Canadensys/vascan-data <vascan-data@noreply.github.com<mailto:vascan-data@noreply.github.com>>
Objet : [vascan-data] Polemonium reptans http://data.canadensys.net/vascan/taxon/8087?lang=en (#2364)


Polemonium reptans (and var. reptans) is a garden escape in Ontario and not native (treated as exotic by Scoggan (1979) and Morton and Venn (1990).

MIKE OLDHAM

�
