### ISSUE TITLE
Potentilla canadensis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2365]
Vascan URL:
http://data.canadensys.net/vascan/taxon/8804?lang=en

Why excluded from Ontario?  Mapped for Ontario in FNA Vol. 9, which is given as the source for misidentification.  There are specimens in Ontario herbaria (e.g. TRT) and accepted for Ontario by various sources (e.g. Morton and Venn 1990).  Considered a rare native plant in Ontario by NHIC.

MIKE OLDHAM

**Comment by brouille** [comment]
Distribution statement changed between draft and publication. I had not been able to update.
Luc
