### ISSUE TITLE
Prunus x cistena

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2366]
Vascan URL:
http://data.canadensys.net/vascan/taxon/28716?lang=en

What is source for occurrence in Ontario (no source provided)?  Name not used in FNA Vol. 9.

MIKE OLDHAM

**Comment by brouille** [comment]
I excluded it as only cultivated - but I cannot find why this was added to Canada
Sue Meades made a host of suggestions - I wonder whether it came from her
