### ISSUE TITLE
typo in synonym of Erigeron strogosus var. strigosus

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2367]
Re: http://data.canadensys.net/vascan/taxon/3128

Error:Phalacroloma strigosa (Muhlenberg ex Willdenow) ) Tzvelev

Should be: Phalacroloma strigosum (Muhlenberg ex Willdenow) ) Tzvelev

See IPNI; all other Phalocroloma combinations in IPNI have a neuter ending.

**Comment by brouille** [comment]
I followed TROPICOS where the wrong ending came from.
Corrected
