### ISSUE TITLE
incorrect authority in 2 synonyms of Draba lactea

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2368]
re: http://data.canadensys.net/vascan/taxon/4011?lang=en

error: Draba fladnizensis var. heterotricha (Lindblad) Ball
error:Draba wahlenbergii var. heterotricha Lindblad

should be: Draba fladnizensis var. heterotricha (Lindblom) Ball
should be: Draba wahlenbergii var. heterotricha Lindblom

See: Lindblom's 1939 publication
http://babel.hathitrust.org/cgi/pt?id=wu.89036557841;view=1up;seq=27
I couldn't access the orginal publication from 1938, but it was reprinted in this 1939 article.

**Comment by brouille** [comment]
corrected the author name
