### ISSUE TITLE
authority of Myosotis sylvatica

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2369]
re:http://data.canadensys.net/vascan/taxon/3807?lang=en

Incorrect: Myosotis sylvatica Ehrhardt ex Hoffman

Should be:Myosotis sylvatica Hoffman

See Grin: http://www.ars-grin.gov/cgi-bin/npgs/html/tax_search.pl
GRIN explains why the authorship should be just Hoffmann, not Ehrh. ex Hoffman

**Comment by brouille** [comment]
corrected
