### ISSUE TITLE
Scientific Authority for genus Deschampsia

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#237]
[Originally posted on GoogleCode (id 2391) on 2015-01-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/1086?lang=en

<b>What data are incorrect or missing?</b>
Check on SciAuth for the genus Deschampsia pls.
Currently listed is 'Kunth', however everywhere I've checked it is 'P. Beauv.'

<b>What data are you expecting instead?</b>
IPNI and TROPICOS list the SciAuth as 'P. Beauv.'

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 20:09Z]

Thanks. A mistake indeed.
Luc
