### ISSUE TITLE
Sabulina litorea

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2375]
http://data.canadensys.net/vascan/taxon/28298
In FNA Vol. 5 and in Fernald's (1906) original description (as Arenaria litorea), S. litorea is mentioned from Ontario with specimens cited from the Lake Superior area by Fernald, but VASCAN does not list it from Ontario, why?

Thanks,

Mike Oldham

**Comment by brouille** [comment]
Because I did not know. And are you certain it is this taxon?

Luc

**Comment by MichaelOldham** [comment]
The original description by Fernald (1906) cites two Ontario specimens from Lake Superior and FNA Vol. 5 mentions that it occurs in Ontario (under M. dawsonensis), but I do not know the taxon and have not seen the specimens, so can't say with any certainty.

mike

**Comment by brouille** [comment]
Mike
I am adding it to Ontario; I will cite the FNA 5 source since I already have it among references.
Luc
