### ISSUE TITLE
spelling of scientific name and common names: Equisetum x mackayi

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2376]
re: http://data.canadensys.net/vascan/name/Equisetum%20%C3%97mackaii

Errors: Equisetum ×mackaii (Newman) Brichan
     Equisetum hyemale var. mackaii Newman
    prêle de MacKay 
    prêle de Mackai  
    MacKay's scouring-rush Anions
    MacKay's horsetail

Should be: Equisetum ×mackayi (Newman) Brichan
     Equisetum hyemale var. mackayi Newman
    prêle de Mackay 
    prêle de Mackay
    Mackay's scouring-rush Anions
    Mackay's horsetail

Source: Ted Ahti questioned the spelling, based on ICBN, so I e-mail Kanchi Gandhi about this, as IPNI and Tropicos had different spellings; here is the summary that Kanchi sent. 

Equisetum hyemale var. mackayi Newman, Phytologist 1(no. 16): 307. Sep 1842 (as var. mackaii)
Equisetum mackayi (Newman) Brichan Phytologist 1(no. 18): 369. Nov 1842 (as mackaii)
Eponymy: "Named after the original discoverer, Mr. J. T. Mackay, of Dublin."
The above info is correct.  Thanks.  Best, Kanchi

 If you want to see the entire e-mail, I'll forward to you, but won't copy it here.  Thanks, Sue.

**Comment by manions** [comment]
Thanks very much Sue for getting this figured out.
English vernaculars adjusted.
Marilyn

**Comment by MFavreau** [comment]
I corrected the accepted French vernacular : "prêle de Mackay" is obviously the right choice.
I kept the spelling "prêle de Mackai" as a synonym, in case the species gets searched under that name.
The scientific name still needs to be corrected.

Marc

**Comment by sjmeades** [comment]
Thanks, Marc!
