### ISSUE TITLE
typo in synonym of Huperzia miyoshiana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2377]
Re: http://data.canadensys.net/vascan/taxon/6586

Error: Urostachys miyoshiana (Makino) Nessel

Should be: Urostachys miyoshianus (Makino) Nessel

This was recently corrected in IPNI; all endings with Urostachys should be masculine
See IPNI; Tropicos hasn't changed yet

**Comment by brouille** [comment]
corrected
