### ISSUE TITLE
range of Diphasiastrum ×sabinifolium 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2378]
re: http://data.canadensys.net/vascan/taxon/6580

It looks like there are 2 or 3 distribution dots for Diphasiastrum ×sabinifolium in wLabrador in Payette's Flore Nordique, pg. 125.  Are these confirmed from Lab.?

**Comment by brouille** [comment]
Two of the dots are in Québec, but one is on the northeast of the Smallwood Reservoir. Furthermore, I have 4 records in the MT database, but I do not know whether the author saw and revised them, one being at Nain by Wynne-Edwards.

I believe it is safe to add Labr., with source MT.
Luc

**Comment by brouille** [comment]
Source will remain as is.
