### ISSUE TITLE
range and authorities of Huperzia arctica

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2379]
Re: Huperzia arctica (Tolmatchew) Siplivinsky

There are several distribution dots shown for Huperzia arcitca in n/wLabrador in Payette's Flore Nordique
Also, the Panarctic Flora lists it as rare from Hudson Bay-Labrador.
See: http://nhm2.uio.no/paf/flora#paf-010303

Errors: 
Huperzia arctica (Tolmatchew) Siplivinsky
Huperzia selago subsp. arctica (Grossheim) Á. Löve & D. Löve

Should be: 
Huperzia arctica (Grossheim ex Tolmatchew) Siplivinsky
Huperzia selago subsp. arctica (Grossheim ex Tolmatchew) Á. Löve & D. Löve

Panarctic flora (link above) also has the authority information

**Comment by brouille** [comment]
Neither IPNI (most notably) nor TROPICOS have an ex authorship
Though Panarctic (and Canadian Arctic, influenced by them) indicates Grossheim, they do not explain the basis for this attribution
I will consult on this before changing it

Labrador added fide PAyette 2010+

**Comment by brouille** [comment]
added the ex
LB
