### ISSUE TITLE
Calamagrostis cinnoides SciAuth nom illeg resolved yet?

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#238]
[Originally posted on GoogleCode (id 2394) on 2015-01-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9629?lang=en

<b>What data are incorrect or missing?</b>
is this resolved yet?
with increasing use of VASCAN by the public, it's awkward to cite a SciAuth as a nom.illeg

<b>What data are you expecting instead?</b>
just wondering if a SciAuth could be placed, such as used in FNA, until there is a publication to conserve the name of C. cinnoides (as mentioned in FNA vol24 pg 716-717

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 18:54Z]

This name was kept due to the NS distribution.

However, I just checked in Cat NW Grasses (see TROPICOS) and they synonymize this illeg. name with Calamagrostis canadensis. I will thus correct the database using this taxonomy. This seems to be a recent correction in this source given I had not found this information previously.

That of FNA 24 is not available anyway online.

tx for the reminder! 

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 19:23Z]

In fact, it is possible that the taxon be a genuine one, but not under C. cinnoides.

Currently, CAt. NW Grass recognizes the issue but has not resolved it yet. They place the concept under C. coarctata, another illeg. name. C. nuttalliana is valid, but they seem not to have concluded on the proper name.

I suspect this entity is what is present in NS, so I am not changing anything now. I removed the vernaculars, however, as they were little appropriate...

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-06 14:57Z]

Shouldn't we leave the vernaculars: small reedgrass (FNA 2007) and calamagrostide faux-cinna (Favreau) for now? So that some names are present?
Otherwise we'd probably get feedback that there isn't any vernaculars provided.
Then when we know more, we can make adjustments as necessary.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-02-06 15:31Z]

I agree with Marilyn. These vernaculars should stay for now. « Small reedgrass » is a published name, and the taxon is a candidate COSEWIC species under the name « calamagrostide faux-cinna ». We should wait until the taxonomic status of the NS material is more or less settled before we reevaluate those vernaculars.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 19:26Z]

Let�s leave as is until de name is resolved. NWG opened the issue but left
it unresolved.

Luc

Le 2015-02-06 10:31, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :
