### ISSUE TITLE
add Ampelopsis brevipedunculata for ON (exotic)

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2381]
There is an Ontario record from outside cultivation where the species persisted for more than a decade. First collected in Ontario in 1993 from Hendrie Valley, Burlington, Halton County, by W. J. Crins (#9737 at MICH, TRTE, det. A.A. Reznicek 1997).  Collected again in the same area in 1997 and 2004 by W. J. Crins, though has apparently disappeared from its single known Ontario site (W.J. Crins pers. comm. 7 Jan. 2015).  An invasive species in some parts of its range (e.g. readily escapes in southern Michigan) and likely to be found again in Ontario.

Mike Oldham

**Comment by brouille** [comment]
Mike
Though the location has apparently disappeared, I will still include it. I wonder whether I should not put it as EPHEMERAL (not excluded) until new populations are found and establishment confirmed, a criterion for introduced.
NB: In the FNA treatment of Vitaceae (FNA 12), the species is treated as a synonym of Ampelopsis glandulosa (Wallich) Momiyama. I believe you received the treatment in 2014. You may want to inform the editors or author that the species briefly established in Ontario before disappearing. If so, let me know.
Luc

**Comment by MichaelOldham** [comment]
Hi Luc,

It did persist at the site for more than a decade (1993-2004) and based on nearby areas (e.g. Michigan) I think the species is likely to show up again in Ontario.  It is considered invasive in some parts of North America.

Yes, the FNA treatment author or editors could be informed (will you do so, or should I?).

mike

**Comment by brouille** [comment]
@manions @MFavreau 
Marilyn & Marc
Comme vous pouvez voir, à l'instigation de Mike Oldham, je viens d'ajouter Ampelopsis glandulosa à VASCAN
Je ne connais pas de nom français, mais le traitement FNA donne le vernaculaire anglais suivant: Porcelainberry
Merci d'ajouter les vernaculaires
Luc

**Comment by brouille** [comment]
Mike
OK, I will put it as introduced, though it is inconsistent.
Luc

**Comment by MFavreau** [comment]
Nom français ajouté.

Marc

**Comment by brouille** [comment]
English vernacular added
