### ISSUE TITLE
Presence of Hippuris lanceolata in LB?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2382]
Question presence of Hippuris lanceolata in LB - do you have an specimens?

John Maunder received a message from Raider Elven about Hippuris lanceolata and indicated that they have seen no specimens of H. lanceolata from NL.  Here is his message: 
Attached is the file summarizing the Hippuris in CAN and DAO. No record
of H. lanceolata in Nfl there. David Murray (Fairbanks) is writing the
genus for FNA, and my task was mainly to supply him with distributional
data. There is pretty little to find in morphology, not many characters.
However, we have seen no specimens with aborting anthers of fruits
whatsoever, suggesting that the hybrid hypothesis for H. lanceolata
either is wrong or represents a fairly strange genetic situation.
Hippuris lanceolata seems to be the ONLY taxon present in Greenland and
the Canadian Arctic Archipelago, and sympatry of the three, or even of
two of them, is a rather rare situation. Hippuris lanceolata and H.
tetraphylla share the anther characters, whereas H. lanceolata and H.
vulgaris are more similar in leaf characters (but with a gap in the
variation pattern). We have not seen a single intermediate between H.
tetraphylla (leaves in middle and upper parts of the stem 4(-5), obovate
to oblong, and obtuse) and H. lanceolata (leaves in middle and upper
part of stem (5-)6(-7), narrowly oblanceolate or oblong and subacute).
Also H. vulgaris (leaves in middle and upper parts of stem (7-)8(-more),
linear or very narrowly lanceolate, acute) seems to have no real overlap
with H. lanceolata in leaf features. I am not sure what these plants
really are, and some low-level genetics (e.g., AFLP) would be nice.
Dave's email adress is: ffdfm@uaf.edu

Best greetings, Reidar E."

GitHub won't support a word attachment, so I'll send that to Luc via e-mail.

Sue.

**Comment by brouille** [comment]
specimen from Buckle's Point, Forteau Bay, Labrador (MT)
Elven did not ask for MT specimens
Luc

**Comment by sjmeades** [comment]
Thanks!
