### ISSUE TITLE
Status of Nuphar x rubrodisca in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2383]
http://data.canadensys.net/vascan/taxon/6716?lang=en 

Given that this collection (Fernald & Wiegand, 1911, #5417, US), was apparently from near the Northcliffe estate in Grand Falls (pers. comm., J.Maunder), and no new reports have been observed for over 100 yrs, should this taxon still be listed as present in Nfld.?

**Comment by brouille** [comment]
This is a native nothotaxon. The status I could use is EXTIRPATED.
Would this be OK?
Luc

**Comment by sjmeades** [comment]
Considering that the presence of one parent, Nuphar microphylla, in NL was actually based in a single specimen that was a misidentification of N. variegata, annotated by Stu, there is no N. microphylla in NL, so the hybrid would likely be an introduction. I recently received confirmation of this from Kanchi, so have included this info in the new checklist:  [A report in FNA of Nuphar microphylla from swLabrador is referred to Nuphar variegata (G. Lamoureux, pers. comm.,1999).  Also, a collection by A.M. Ayre of Nuphar microphylla (GH) from Salmonier, eNfld., collected in 1932, was annotated by Stu Hay in 1989 as Nuphar variegata, then by B. Hellquist in 1992 as Nuphar advena subsp. variegata (K.Gandhi, pers. comm., June 7, 2015).  
Does this change your response?

**Comment by brouille** [comment]
It is still possible that the taxon reached Nfld by its own means via long-distance dispersal. It need not have been created in situ. The best would be to check the material to see whether it is truly rubro and not variegata.

**Comment by sjmeades** [comment]
I think one of the authors of the Nuphar treatment discounted this report, since I posted this question back in 2015.
