### ISSUE TITLE
Status of Brassica juncea in LB?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2384]
Re: http://data.canadensys.net/vascan/taxon/3921?lang=en

In our  2000 checklist, we had Brassica juncea listed as: Labrador reports require confirmation.  Have you seen any verified records from LB?

**Comment by brouille** [comment]
I do not see a statement as you mention above in the version I have ot the 2000 list. 
Here is a copy:
"[N] i  Brassica juncea (L.) Czern. Jan. 1859, non Cosson post Aug. 1859
Indian mustard, chinese mustard; Fr: moutarde joncée, moutarde de l’Inde.  Eurasian; intr. in w/nw/eNfld.
        [=Sinapis juncea L.]
    [Brassica kaber  -  see Sinapis arvensis]"
There is no specimen at MT for Labr., and there is no entry in the MT database (including the Rouleau records from all herbaria) either.
I believe the entry in VASCAN was a sheer mistake and I am removing it, unless you have evidence to the contrary.
Luc
