### ISSUE TITLE
incomplete authority for Conioselinum gmelinii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2385]
Re: http://data.canadensys.net/vascan/taxon/2565?lang=en

Error: Conioselinum gmelinii J.M. Coulter & Rose nom. illeg.

Should be: Conioselinum gmelinii (Chamisso & Schlechtendal) J.M. Coulter & Rose nom. illeg.

Basonym: Ligusticum gmelinii Chamisso & Schlechtendal 

Also, see Fernald: Rhodora 28: 221, 1926 (also p. 117), who states that Conioselinum gmelinii (Bray) Steudel (1840) is the proper name for eastern Canada collections from the Gaspe, so should C. gmelinii (Gray) Steudel be synonymous with C. chinense rather than C. pacificum?

**Comment by sjmeades** [comment]
Re: Conioselinum gmelinii (Bray) Steudel, this is now accepted as a synonym of Conioselinum vaginatum (Spreng.) Thell. in The Plant List.
http://www.theplantlist.org/tpl1.1/record/kew-2734144

**Comment by brouille** [comment]
The basionym of Conioselinum gmelinii is not Ligusticum but Selinum gmelinii Bray. I will correct accordingly.
I am using the FNA draft treatment on Conioselinum by Wendy Applequist as the source of taxonomy here, and NOT The Plant List based on Kew (which is currently in revision anyway). Not always reliable.
She is placing the name in synonymy of pacificum, a more likely disposition.
With respect to Fernald's remark, Applequist maintains C. chinense for eastern Canadian specimens. His remark has not been followed up and both taxa are considered distinct. She lists many differences between the two taxa.
Luc
