### ISSUE TITLE
range of Amelanchier gaspensis in NL?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2387]
Re: http://data.canadensys.net/vascan/taxon/9650?lang=en

Campbell et al's treatment of Amelanchier in FNA states that Amelanchier gaspensis has a range in Canada restricted to the Gaspe.  Could it be that our records from NL are actually Amelanchier fernaldii, which is reported from NL, and which had been synonymized with A. gaspensis in our 2000 checklist?

**Comment by brouille** [comment]
Sue

I find no specimen of gaspensis at MT. All is fernaldii. We did not change our determination.
I do not know where the synonymy used came from (fernaldii under sanguinea var. gaspensis). As cited in the list, Bouchard et al. 91 used fernaldii
gaspensis is not in Nfld. I will have to exclude, but I am uncertain what I will cite as source of exclusion.
fernaldii is in the list already.
Luc
