### ISSUE TITLE
change Verbena bracteata to exotic in Ontario 

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2389]
http://data.canadensys.net/vascan/taxon/9460?lang=en

I have recently been reviewing the status of a number of Ontario vascular plants as a result of the Wild Species in Canada (General Status) project.  Although we previously considered Verbena bracteata to be native in Ontario (following Morton and Venn's 1990 checklist), I have looked more carefully at the species' status and think it is more likely to be an introduction and we have changed it to introduced in our database.  I added the following rationale for exotic status in Ontario to our database: "Although considered native in Ontario by Morton and Venn (1990), this species is always found in highly disturbed situations and never as a component of undisturbed natural vegetation communities.  The native status in Morton and Venn (1990) might be based on Scoggan (1978-1979) who considered it "probably native in sand at Point Edward, near Sarnia, Lambton Co. (John Macoun 1890); probably introd. along railway ballast and in freight yards at Strathroy, Middlesex Co., and Westmeath, Renfrew Co."  It was considered introduced in Ontario and excluded by Argus et al. (1982-1987) from the "Atlas of the Rare Vascular Plants of Ontario".  It is considered probably not native in adjacent Michigan by Voss and Reznicek (2012) and exotic in New England (Haines 2011).  An uncommon weed in southern Ontario."

Michael J. Oldham

**Comment by brouille** [comment]
Status change.
Only problem is source : currently, I have Newmaster & Rag. FOIBIS - but these authors give S4?
I cannot change source too readily, but I need one.
Luc

**Comment by MichaelOldham** [comment]
Could you reference the NHIC database or M.J. Oldham pers. comm.?  We will eventually (hopefully soon) have a revised species list posted on the NHIC web page but right now the list that is there is almost 2 years old and this change (and many others) are not reflected in it.

mike

**Comment by brouille** [comment]
Mike

I am trying to provide sources that can be verified. Pers. comm. are awkward, but I will use that to minimize new references.

Luc

De : MichaelOldham <notifications@github.com<mailto:notifications@github.com>>
R�pondre � : Canadensys/vascan-data <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : mardi 16 juin 2015 13:33
� : Canadensys/vascan-data <vascan-data@noreply.github.com<mailto:vascan-data@noreply.github.com>>
Cc : Luc Brouillet <luc.brouillet@umontreal.ca<mailto:luc.brouillet@umontreal.ca>>
Objet : Re: [vascan-data] change Verbena bracteata to exotic in Ontario (#2389)

Could you reference the NHIC database or M.J. Oldham pers. comm.? We will eventually (hopefully soon) have a revised species list posted on the NHIC web page but right now the list that is there is almost 2 years old and this change (and many others) are not reflected in it.

mike
