### ISSUE TITLE
Agropyron cristatum in Labrador - ephemeral intro?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2393]
re: Agropyron cristatum in Labrador.

Photo supplied to Nathalie from DAO of this specimen; no other records are reported from DAO or NFM, or in the Grass Manual (FNA), so this species might be better treated as ephemeral in Labrador.

[A single specimens exists of Agropyron cristatum from "lawns and clearings about building",  Goose Bay, collected on July 29, 1950, by J.M.Gillett and W.I.Findlay (DAO), originally identified as A. pectiniforme.  Photo supplied to N.Djan-Ckekar (NFM), courtesy of DAO. No recent records of A. cristatum have been reported.]

**Comment by brouille** [comment]
Sue
Excluded - ephemeral (and old report, no new reports)
Luc
