### ISSUE TITLE
Carte à modifier_Euonymus alatus se reproduit de façon autonome au Québec

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#2394]
Alexandre Blain, botaniste à l'Agence canadienne d'inspection des aliments (ACIA) a documenté la présence d'Euonymus alatus dans le parc de la Gatineau au Québec, un arbuste qu'il écrit "devient envahissant".  Veuillez trouver ci-joint son courriel du 19 juin 2015 qui justifie l'ajoutt de l'espèce à la flore du Québec:

from:   Alexandre Blain Alexandre.Blain@inspection.gc.ca
to: hall.geoffrey@gmail.com
date:   Fri, Jun 19, 2015 at 1:04 PM
subject:    Re: Occurrences documentées au parc de la Gatineau et environs, extraites de la base de données MT
Bonjour Geoffrey,
Merci beaucoup pour ton aide, c'est très apprécié. Je vais regarder ta liste plus en détail cette fin de semaine. Ce sera très utile pour nos recherches. Je compte déposer des spécimens d'herbier à MT bientôt. Il s'agit de Euonymus alata, cet arbuste devient envahissant à l'intérieur du parc. Je pense que VASCAN devrait l'inclure comme plante introduite au Québec puisqu'il se reproduit de façon autonome. J'espère que celui-ci pourra être contrôlé dans le parc du moins parce qu'il commence a prendre beaucoup d'espace. Berberis thunbergii est aussi à surveiller dans le parc.
Meilleures salutations,
Alex

> > > Geoffrey Hall hall.geoffrey@gmail.com 2015-06-19 10:47 AM >>>
> > > Bonjour Alexandre,
> > > Pour faire suite à ta demande de renseignements sur les récoltes recensées à MT provenant de la région du projet de flore du parc de la Gatineau, je joins un fichier Excel qui comporte 1047 enregistrements centrés géographiquement sur le parc et les mots clef suivants :
> > > Parc de la Gatineau 558
> > > Alcove 5
> > > Breckenridge 21
> > > Chelsea 108
> > > Doherty 0
> > > Duclos 0
> > > Eardley 63
> > > Gatineau + MRC Gatineau 267
> > > Lac-des-Loups 0
> > > La Pêche + MRC Les Collines-de-l'Outaouais 105
> > > Luskville 59
> > > Mohr 0
> > > Rockhurst 0
> > > Ruthledge 1
> > > Sainte-Cécile-de-Masham 0
> > > Wakefield 95
> > > J'ai exclu le mieux que je pouvais les données de bord de rivière (Outaouais, Gatineau).
> > > L'Herbier Marie-Victorin détient un nombre inconnu de spécimens supplémentaires provenant de la zone en question. Seulement 2/7 des planches classées dans l'herbier de recherche sont saisies dans le système.
> > > Il y a un chevauchement entre les récoltes attribuées aux municipalités et celles effectuées dans le parc. La majorité des 1047 récoltes sont déposées à MT mais un certain nombre ne le sont pas et celles-ci sont probablement à DAO ou CAN, ou bien ici, mais à confirmer par des prospections que seulement un chercheur sur place pourrait réaliser. Dans le fichier, il y a une colonne qui s'appelle "statut" qui indique où se trouvent les spécimens dans la plupart des cas.
> > > En souhaitant que ces renseignements contribuent à la réalisation de votre projet, salutations,
> > > Geoffrey

**Comment by brouille** [comment]
Un spécimen a-t-il été déposé à MT ou un autre herbier important ?
Luc

**Comment by herbier** [comment]
Alexandre Blain n'a toujours pas déposé de spécimen mais il y en a d'autres qui documentent que l'espèce s'est échappée au Québec:

Spécimens à MT d'Euonymus alatus

186459     Grégoire, Fleurette     no. 81     1974-04-21
Cimetière Mont-Royal, Outremont, île de Montréal
Cimetière, isolé
Don de l'herbier d'enseignement dont le responsable, Alexandre Bergeron, croît qu'il s'agit d'un individu échappé

22382     Malo, Marie     no. 365     2005-07-06
Montréal, Mont Royal, le long du chemin Olmsted allant du stationnement au grand chalet
Lisière d'érablière; bord de sentier

186438     Bergeron, Alexandre; Mignot, Jean-Sébastien; Brice, Marie-Hélène; Fayet, Basil     no. 12026     2012-06-05
Île de Montréal; Parc du Mont-Royal; près de la bordure du chemin de la Montagne
Espace ouvert et gazonné 

206977     Lambert, François     no. 2015-158     2015-10-06    [et doublon 206985]
Île Sainte-Hélène, près du Musée Stewart
Érablière à sucre mature en haut de pente abrupte; sous-bois de nerprun et d'abondants semis d'érables à sucre; 10 arbustes et semis isolés; commun en sous-bois
