### ISSUE TITLE
Vernacular names for Plagiobothrys humistratus

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2397]
@MFavreau 
Plagiobothrys humistratus was added to VASCAN for BC
Please provide vernaculars
FNA ms not yet available
Thanks
Luc

**Comment by MFavreau** [comment]
French name added. I choose to translate the scientific epithet humistratus, which means « prostrate », rather than the English name used in CalFlora, « dwarf... ».

**Comment by manions** [comment]
English vernaculars added. Updated Jepson's Manual has the name 'low' which is suitable
