### ISSUE TITLE
Vernacular names requested

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2399]
@MFavreau 
The following taxa are being added for BC and require French and English vernaculars:

Arum italicum [introduced; Europe; not in FNA]

Aubrieta deltoidea [introduced; Europe; http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242416161]

Carex jonesii [native; http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242357263]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Carex jonesii

Carex pendula [introduced; Europe; http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242357395]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Carex pendula

Centranthus ruber [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Centranthus ruber

Cistus creticus [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Cistus creticus
French: http://inpn.mnhn.fr/espece/cd_nom/91646

Cyclamen hederifolium [introduced; Eurasia; not in FNA]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Cyclamen hederifolium

Cytisus striatus [introduced; Europe]
BC: http://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Cytisus striatus

Epilobium obscurum [introduced]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Epilobium obscurum

Epilobium smithii [native]

Epilobium tetragonum subsp. tetragonum [introduced]
linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Epilobium tetragonum

Fumaria muralis [introduced; Europe]
French: http://inpn.mnhn.fr/espece/cd_nom/99106

Genista monspessulana [introduced; Europe]
linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Genista monspessulana
French : http://inpn.mnhn.fr/espece/cd_nom/99785

Geranium lucidum [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Geranium lucidum
French: http://inpn.mnhn.fr/espece/cd_nom/100085

Hypericum calycinum [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Hypericum calycinum
French: http://inpn.mnhn.fr/espece/cd_nom/103254

Isotoma fluviatilis [introduced; Australia : http://bie.ala.org.au/species/Isotoma+fluviatilis]

Lemna minuta [introduced possibly; North America : http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=222000206]

Meconopsis cambrica [introduced]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Meconopsis cambrica
French: http://inpn.mnhn.fr/espece/cd_nom/107519

Mentha requienii [introduced; Europe]
French: http://inpn.mnhn.fr/espece/cd_nom/108145

Plagiobothrys humistratus [native; Calif: http://ucjeps.berkeley.edu/cgi-bin/get_IJM.pl?tid=38504]

Sanicula europaea [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Sanicula europaea
French: http://inpn.mnhn.fr/espece/cd_nom/120772

Sarcocornia pacifica [native - may be the proper name for the S. perennis specimens of the Pacific WN]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Sarcocornia pacifica
FNA: http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242415617
You have to decide whether the names used for perennis are pertinent for pacifica, which is apparently the species present and not perennins

Schoenoplectus triqueter [introduced ; Eurasia]
FNA: http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242101177
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Schoenoplectus triqueter
French: http://inpn.mnhn.fr/espece/cd_nom/121556

Spergularia rupicola [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Spergularia rupicola
French: http://inpn.mnhn.fr/espece/cd_nom/717562 [ss Spergula rupicola - il y a des complexités que je préfère ne pas aborder maintenant concernant le status de Spergularia vs Spergula]

Tomostima reptans [former name: Draba reptans]
Please verify that the current vernaculars (from Draba) are acceptable

Thanks
Luc

**Comment by MFavreau** [comment]
@Luc, il semble que l'Hypericum calycinum n'a pas encore été inscrit dans la base de données.

Marc

**Comment by MFavreau** [comment]
French Name added for Sarcocomia pacifica. I used the translation « salicorne du Pacifique » because the type locality is from California, whatever the actual status of the eastern North American material of S. pacifica mentioned in FNA. S. perennis may or may not occur in North America, but the French name « salicorne vivace » should certainly not be applied to S. pacifica.

**Comment by MFavreau** [comment]
French names added for Arum italicum, Aubrieta deltoidea, Carex jonesii, Carex pendula, 
Centranthus ruber, Cistus creticus, Cyclamen hederifolium, Cytisus striatus, Epilobium obscurum, Epilobium smithii, Epilobium tetragonum subsp. tetragonum [as well as Epilobium tetragonum], Fumaria muralis, Genista monspessulana, and Geranium lucidum.

More to come

Marc

**Comment by MFavreau** [comment]
Bonjour Luc,

GitHub nest pas accessible en ce moment.

Jai ajouté ou vérifié tous les noms français demandés, sauf pour
lHypericum calycinum qui ne figure pas encore dans VasCan.

Est-ce normal que cette espèce ne soit pas encore dans la base? Cette
absence semble due à une erreur ou à une omission, si jen juge daprès les
données mentionnées dans la demande 2399.

Marc

---

De : brouille [mailto:notifications@github.com] 
Envoyé : 25 juin 2015 16:54
À : Canadensys/vascan-data
Cc : MFavreau
Objet : [vascan-data] Vernacular names requested (#2399)

@MFavreau https://github.com/MFavreau  
The following taxa are being added for BC and require French and English
vernaculars:

Arum italicum [introduced; Europe; not in FNA]

Aubrieta deltoidea [introduced; Europe;
http://www.efloras.org/florataxon.aspx?flora_id=1
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242416161
&taxon_id=242416161]

Carex jonesii [native; http://www.efloras.org/florataxon.aspx?flora_id=1
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242357263
&taxon_id=242357263]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Carex jonesii

Carex pendula [introduced; Europe;
http://www.efloras.org/florataxon.aspx?flora_id=1
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242357395
&taxon_id=242357395]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Carex pendula

Centranthus ruber [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Centranthus ruber

Cistus creticus [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Cistus creticus
French: http://inpn.mnhn.fr/espece/cd_nom/91646

Cyclamen hederifolium [introduced; Eurasia; not in FNA]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Cyclamen hederifolium

Cytisus striatus [introduced; Europe]
BC: http://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Cytisus striatus

Epilobium obscurum [introduced]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Epilobium obscurum

Epilobium smithii [native]

Epilobium tetragonum subsp. tetragonum [introduced]
linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Epilobium tetragonum

Fumaria muralis [introduced; Europe]
French: http://inpn.mnhn.fr/espece/cd_nom/99106

Genista monspessulana [introduced; Europe]
linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Genista monspessulana
French : http://inpn.mnhn.fr/espece/cd_nom/99785

Geranium lucidum [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Geranium lucidum
French: http://inpn.mnhn.fr/espece/cd_nom/100085

Hypericum calycinum [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Hypericum calycinum
French: http://inpn.mnhn.fr/espece/cd_nom/103254

Isotoma fluviatilis [introduced; Australia :
http://bie.ala.org.au/species/Isotoma+fluviatilis]

Lemna minuta [introduced possibly; North America :
http://www.efloras.org/florataxon.aspx?flora_id=1
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=222000206
&taxon_id=222000206]

Meconopsis cambrica [introduced]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Meconopsis cambrica
French: http://inpn.mnhn.fr/espece/cd_nom/107519

Mentha requienii [introduced; Europe]
French: http://inpn.mnhn.fr/espece/cd_nom/108145

Plagiobothrys humistratus [native; Calif:
http://ucjeps.berkeley.edu/cgi-bin/get_IJM.pl?tid=38504]

Sanicula europaea [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Sanicula europaea
French: http://inpn.mnhn.fr/espece/cd_nom/120772

Sarcocornia pacifica [native - may be the proper name for the S. perennis
specimens of the Pacific WN]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Sarcocornia pacifica
FNA: http://www.efloras.org/florataxon.aspx?flora_id=1
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242415617
&taxon_id=242415617
You have to decide whether the names used for perennis are pertinent for
pacifica, which is apparently the species present and not perennins

Schoenoplectus triqueter [introduced ; Eurasia]
FNA: http://www.efloras.org/florataxon.aspx?flora_id=1
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242101177
&taxon_id=242101177
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Schoenoplectus triqueter
French: http://inpn.mnhn.fr/espece/cd_nom/121556

Spergularia rupicola [introduced; Europe]
BC: linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Spergularia rupicola
French: http://inpn.mnhn.fr/espece/cd_nom/717562 [ss Spergula rupicola - il
y a des complexités que je préfère ne pas aborder maintenant concernant le
status de Spergularia vs Spergula]

Tomostima reptans [former name: Draba reptans]
Please verify that the current vernaculars (from Draba) are acceptable

Thanks
Luc


Reply to this email directly or view it on GitHub
https://github.com/Canadensys/vascan-data/issues/2399 .
<https://github.com/notifications/beacon/ALN5j4g4AgFKr2AbQ4fdqPyj50cVvDmxks5
oXGIDgaJpZM4FMJn0.gif> 

---

size=1 width="100%" noshade color="#a0a0a0" align=center> 

Aucun virus trouvé dans ce message.
Analyse effectuée par AVG - www.avg.fr
Version: 2015.0.6037 / Base de données virale: 4365/10094 - Date: 25/06/2015

**Comment by manions** [comment]
phew, got through all of these and many other related taxa! 
Marc if you are finished as well, this issue can be closed.

**Comment by MFavreau** [comment]
Yes, all done including H. calycinum.
Marc
