### ISSUE TITLE
Autorité - Campanula gieseckeana Vest

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#24]
[Originally posted on GoogleCode (id 917) on 2012-01-13]

Salut Luc

Campanula gieseckeana Vest
tandis que Lammers, T.G. (2007) World Checklist and Bibliography of Campanulaceae indique Vest ex Schult. in Roem. &amp; Schult. comme autorité.

Il faudrait vérifier si on ajoute le &quot;ex Schult.&quot;

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-16 16:44Z]

tant IPNI que TROPICOS ont Vest et non pas ex Schult. in Roem. & Schult.
à valider

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-24 18:10Z]

GRIN aussi a Vest
je décide de ne pas changer cela - attendons FNA...
