### ISSUE TITLE
Solidgo rugosa from seLab?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2400]
http://data.canadensys.net/vascan/taxon/9882?lang=en

A collection is reported in the ACCDC data of Solidago rugosa from a dune area behind a barachois in Pinware Provincial Park (NLRPP 1999) (NFM), SP09955, collectors listed: Hay, S., Brouillet, L., Charest, R., Hanel, C., Djan-ChΘkar, N., Meades, S.& D., Wentzell, C., Pollock, B., Lavers, L.& P.

Since you don't include Lab. in the range, was this specimens later re-IDed?

**Comment by brouille** [comment]
@sjmeades 
There is no good specimen of S. rugosa for Labrador.
The specimen collected in 1999 was NOT a rugosa (and I did not determine it - I sent it to J.C. Semple who did not provide an answer - I suspect the specimen to be among the masses of Solidago received from WAT - will have to dig it out). I do not know who determined it as such. It was hairy, but not in the rugosa way, and the architecture of the plant was in the canadensis complex - something like lepida

Luc
