### ISSUE TITLE
Apiaceae: should Erigenia not be in tribe Erigenieae?

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#2401]
According to Vascan URL http://data.canadensys.net/vascan/taxon/83, Erigenia is not placed in a tribe, whereas tribe Erigenieae contains the single genus Glehnia.
According toauthoritative source Downie et al. in "Major clades within Apiaceae subfamily Apioideae as inferred by phylogenetic analysis of nrDNA ITS sequences" [Plant Div. Evol. 128(1-2) 111–136 (2010)] at URL http://www.life.illinois.edu/downie/DownieITS.pdf, Erigenia is the only member of tribe Erigenieae, whereas Glehnia is in tribe Selineae (tribe not used by Vascan).  Many of the Apiaceae genera not linked to a tribe in Vascan are members of tribes in Downie et al.'s treatment.

Geoff

**Comment by brouille** [comment]
La raison de la classification actuelle ds VASCAN est que je n'avais pas encore consulté Downie et al. 2010. Elle était celle de Takhtajan.
Luc
