### ISSUE TITLE
Antennaria alpina in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2402]
Can this be changed to Doubtful for Ontario?  Although reported from Ontario by Kartesz (1999) and FNA Vol. 19, the basis for these reports is unknown.  Not listed for the province by Argus et al. (1982-1987), Morton and Venn (1990), or Riley (2003), and we are unaware of any Ontario specimens. 

Mike Oldham

**Comment by brouille** [comment]
I would prefer to exclude it because of a lack of documentation - FOIBIS has it as SNA, which could be cited
Luc
