### ISSUE TITLE
Betula murrayana

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2403]
Add Betula murrayana for Ontario (native).

Now known from Ontario based on a specimen from the St. Williams area, Norfolk County.  See Ashburner, K., and H. McAllister. 2013. The Genus Betula: A Taxonomic Revision of Birches. Royal Botanic Gardens, Kew. 448 pp.

Mike Oldham

**Comment by MFavreau** [comment]
French name added.
Marc Favreau

**Comment by manions** [comment]
English vernacular added
