### ISSUE TITLE
Petunia integrifolia

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2404]
add for Ontario (introduced).

Collected in 2014 near Wiarton, Grey County, by Joe Johnson (pers. comm.) where not planted and established.  Specimen at MICH identified by A.A. Reznicek.

MIKE OLDHAM

**Comment by MFavreau** [comment]
French name added.

Could we also add the important synonym « P. violacea Lindl. » (Source  TROPICOS, see http://www.tropicos.org/Name/29600082?tab=synonyms ; also USDA PLANTS.

**Comment by brouille** [comment]
P. violacea ajouté
