### ISSUE TITLE
Sambucus racemosa: is author of subsp. pubens (Michaux) Hultén or (Michaux) S. Watson?

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#2406]
PROBLEM: http://data.canadensys.net/vascan/taxon/2442 = Sambucus racemosa subsp. pubens (Michaux) S. Watson var. pubens
does not agree with http://www.tropicos.org/Name/50293748 = Sambucus racemosa var. pubens (Michaux) S. Watson

WHEREAS http://data.canadensys.net/vascan/taxon/2440 = Sambucus racemosa subsp. pubens (Michaux) Hultén
agrees with http://www.tropicos.org/Name/6000030 = Sambucus racemosa subsp. pubens (Michaux) Hultén

see also http://www.tropicos.org/Name/6000285 = Sambucus racemosa var. pubens (Michaux) Koehne

It seems that Sambucus racemosa subsp. pubens (Michaux) Hultén is correct and that Sambucus racemosa subsp. pubens (Michaux) S. Watson is incorrect.

Geoff

**Comment by brouille** [comment]
Sambucus racemosa subsp. pubens (Michx.) Hultén OK fide TROPICOS & IPNI
ms quand on ajoute la var. c'est incorrect
il semble que VASCAN ait automatiquement attribué les auteurs de la var. à la subsp. car c'est un autonyme! 
pour var. pubens, il y a 3 auteurs différents, 2 chacun par TROPICOS et IPNI:
var. pubens     (Michx.) Koehne 1893
var. pubens     (Michx.) S. Watson 1871
var. pubens (Michx.) Trautv. & C.A.Mey.

**Comment by brouille** [comment]
[le message a sauté avant que je termine- suite]
var. pubens ( Michx. ) Trautv. & C.A.Mey. 1856 ds IPNI
Il semble donc que les autorités sont incorrectes dans les deux cas et que la dernière soit la bonne !

J'ai écrit à K. GAndhi pour avoir une meilleure info sur ce cas. Nous devrons peut-être corriger VASCAN manuellement à cause de la règle automatique qui agit.
