### ISSUE TITLE
Valeriana uliginosa: author name incomplete if following MT dB & Tropicos

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#2407]
Valeriana uliginosa (Torrey & A. Gray) Rydberg
according to
http://data.canadensys.net/vascan/taxon/9454

Valeriana uliginosa (Torrey & A. Gray) Rydberg ex Britton
according to
http://www.tropicos.org/Name/33500559
MT database (taxon ID 13867)

Geoff

**Comment by brouille** [comment]
IPNI has Rydberg, Rydberg ex Britton & Rydb. in Britton
Who to believe? I have been waiting for FNA to solve such minor issues of in and ex.

Luc

**Comment by brouille** [comment]
I added the ex, but still expect FNA to make definite decision
L
