### ISSUE TITLE
Streptopus in the Liliaceae, not the Colchicaceae

### ISSUE THREAD

**Issue by tle003** [Canadensys/vascan-data#2409]
Hi, 

While working on the phylogeny of the vascular plants of Mont St. Hilaire, I noticed that the genus Streptopus is currently listed under the Colchicaceae in VasCan; however, I have found three other sources that place it within the Liliaceae:

VasCan URL:
http://data.canadensys.net/vascan/taxon/1721

Fay et al. (2006). Phylogenetics of Liliales: summarized evidence from combined analyses of five plastid and one mitochondrial loci. Aliso, 22, 559-565.

Fay URL: https://www.researchgate.net/profile/Nina_Ronsted/publication/228687437_Phylogenetics_of_Liliales_summarized_evidence_from_combined_analyses_of_five_plastid_and_one_mitochondrial_loci/links/0fcfd50ade735dff20000000.pdf

Kim et al. (2013). Familial relationships of the monocot order Liliales based on a molecular phylogenetic analysis using four plastid loci: matK, rbcL, atpB and atpF‐H. Botanical Journal of the Linnean Society, 172, 5-21.

Kim URL:
http://onlinelibrary.wiley.com/doi/10.1111/boj.12039/epdf

ANGIOSPERM PHYLOGENY WEBSITE, version 13. Liliaceae - http://www.mobot.org/MOBOT/research/APweb/

Thanks,
Tammy Elliott

**Comment by brouille** [comment]
Thanks for catching this. Obviously wrong. I had it correct for the herbarium.
LB
