### ISSUE TITLE
New names in Carex - validate vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2410]
@manions 
Due to a recent publication from the Global Carex Group, several species names were changed in our flora. Please verify that the names initially attributed still fit. You need not change all vernaculars, of course. The paper from which changes are drawn is open access at:
http://onlinelibrary.wiley.com/doi/10.1111/boj.12298/epdf
Luc

Carex zikae (replaced Carex brevicaulis, a nom. illeg.)

Transfer of Kobresia to Carex: Obviously here, names in Kobresia may prove inappropriate - I would be very reluctant to keep kobresia as a vernacular since it is little-known (my opinion) and the vernaculars made up.
Carex borealipolaris [Kobresia sibirica]
Carex myusuroides [K. m.]
Carex simpliciuscula [K. s.]
some clean-up is required because some English names are repeated with different sources.

**Comment by MFavreau** [comment]
Noms français ajoutés ou rajustés. J'ai conservé la plupart des anciens noms comme synonymes, car ils semblent être utilisés.

Marc

**Comment by manions** [comment]
English vernaculars reviewed and adjusted. Many thanks for the pdf
