### ISSUE TITLE
Carex vacillans

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2411]
Carex vacillans is listed from Labrador in VASCAN, but I have no records of it from Lab. Do you hsve any records at MT of C. vacillans from Labrador?

**Comment by sjmeades** [comment]
Carex vacillans is listed from Labrador in VASCAN, but I have no records of it from Lab. Do you hsve any records at MT of C. vacillans from Labrador?

**Comment by brouille** [comment]
FNA unfortunately listed Nfld. & Labr. without adding the (Nfld.)
But this does not explain why Lab. was added on the basis of our list
I removed the entry
Thanks
Luc
