### ISSUE TITLE
Cynoglossum virginianum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2412]
http://data.canadensys.net/vascan/taxon/3762?lang=en

Cohen (2015; Syst. Bot. 40(2)) has suggested that C. virginianum should be included in a new genus as Andersonglossum virginianum (L.) J. I. Cohen.  He does not accept boreale as distinct from virginianum at any taxonomic level.

MIKE OLDHAM

**Comment by brouille** [comment]
Though I look nearly every week for new issues of Sys Bot, I had not seen this one yet (vacations).
Unusual to make a combination for a taxon one does not want recognized...
Thanks
Luc

**Comment by MichaelOldham** [comment]
I thought that was odd too, but I guess someone will make the combination eventually (though not yet made as a ssp. or var.).

mike
