### ISSUE TITLE
Isoetes riparia

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2413]
http://data.canadensys.net/vascan/name/Isoetes%20riparia

Northern plants, including those from Canada, have recently been described as a new species, I. septentrionalis Brunton (Brunton, D.F., and J. McNeill. 2015. Status, distribution, and nomenclature of Northern Quillwort, Isoetes septentrionalis (Isoetaceae) in Canada. Canadian Field-Naturalist 129(2): 174–180.)

MIKE OLDHAM

**Comment by brouille** [comment]
Also changed the parentages of 2 nothotaxa where the species is a parent

@MFavreau 
Marilyn and Marc:
Isoetes riparia is now excluded from Canada
Isoetes septentrionalis, a new species, is present in Ont. and Qc
Please verify that the vernacular names under I. riparia should not be moved to septentrionalis (or simply removed)
Please use the link in the reference section to see the paper by Brunton & McNeill 2015

Thanks
Luc

**Comment by MFavreau** [comment]
French name added.

Marc

**Comment by manions** [comment]
English names reviewed
