### ISSUE TITLE
Ptelea trifoliata

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2414]
http://data.canadensys.net/vascan/taxon/9039?lang=en

Although COSEWIC is given as the source of the VASCAN English common name, COSEWIC uses Common Hoptree rather than Common Hop Tree.

MIKE OLDHAM

**Comment by brouille** [comment]
@manions 
Marilyn, please verify this
Thanks
Luc

**Comment by manions** [comment]
Yes in this case, both 'hoptree' and 'hop-tree' are used by COSEWIC. Changes made.
