### ISSUE TITLE
Carex pairae devrait être Carex pairaei

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#2417]
Carex pairae devrait être Carex pairaei selon FNA

http://data.canadensys.net/vascan/taxon/15278?lang=fr

Geoff

**Comment by brouille** [comment]
FNA me paraît erroné
tropicos, wcsp et ipni ont la même graphie que VASCAN

Je vais suggérer une correction à FNA cependant

Merci
Luc
