### ISSUE TITLE
Vaccinium oxycoccos

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2418]
http://data.canadensys.net/vascan/taxon/5577?lang=en

Recent article (will send separately via email since I don't seem to be able to attach PDF here) suggests that V. microcarpum be treated as a species separate from V. oxycoccus (Smith et al 2015 "Evaluating the relationship between diploid and tetraploid Vaccinium oxycoccos L. (Ericaceae) in eastern Canada" in Botany).

MIKE OLDHAM

**Comment by brouille** [comment]
Separation in V. oxycoccus and V. microcarpum done, but distribution in Canada based on Scoggan (interpreted) because data are lacking in most floras

**Comment by MFavreau** [comment]
French names sorted. Marc

**Comment by manions** [comment]
yes I reviewed the English names as well
