### ISSUE TITLE
Eleocharis elliptica confirmed for NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#242]
[Originally posted on GoogleCode (id 2458) on 2015-01-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5235?lang=en

<b>What data are incorrect or missing?</b>
In Catling et al 2005 (BEN#353 23Nov2005). Paul has examined Cody's report of Eleocharis compressa (2 specimens) and revised to E. elliptica.
E. elliptica specimens also at ATLA from 2 other NT locations - identified by S. Galen Smith (FNA author).

<b>What data are you expecting instead?</b>
NWT confirmed (not doubtful)

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-26 18:35Z]

I had done a half job here: excluding compressa but not adding elliptica
Thanks for mentioning it
Allowed me to update the ref. properly too
L
