### ISSUE TITLE
Andersonglossum boreale

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2420]
Re: http://data.canadensys.net/vascan/taxon/29172

In the article by J.I. Cohen (2015) that you cite, he makes a few new combinations, including Andersonglossum boreale, which implies that he recognizes this as distinct from A. virginianum.  So why have you synonymized A. boreale under A. virginianum?  I couldn't get the article to open, even though I have an online subscription.

**Comment by brouille** [comment]
Sue

Here is what the author writes:
"Given these phylogenetic relationships, the North American species of Cynoglossum should no longer be included in Cynoglossum; instead, C. occidentale and C. virginianum (including C. boreale Fernald, a species sometimes segregated from C. virginianum, but not by the author) "

and

```
Andersonglossum boreale (Fernald) J. I. Cohen, comb, nov. Cynoglossum boreale Fernald Rhodora 7: 250. 1905. Cynoglossum virginianum subsp. boreale (Fernald) A. Haines Stantec Bot. Notes 13: 3. 2010. Cynoglossum virginianum var. boreale (Fernald) Cooperr. Michigan Bot. 23: 166. 1984.—TYPE: CANADA. Quebec: Little Cascapedia River, July 17, 1905, E. F. Williams , J. F. Collins, & M. L. Fernald s. n. (lectotype: GH [image]!).

Although the author does not accept A. boreale as distinct from A. virginianum, given that it is accepted by other botanists, the appropriate new combination has been made.
```

Therefore, I chose to follow the authority on the taxon.
Luc
