### ISSUE TITLE
Alnus viridis scientific name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2421]
http://data.canadensys.net/vascan/taxon/3682?lang=en

Greuter, W., and E. von Raab-Straube (ed.). 2011. Euro+Med Notulae, 5. Willdenowia 41: 129–138. suggest that the correct name for this species is Alnus alnobetula (Ehrh.) K. Koch. and also publish new combinations for subspecies occurring in Canada, i.e. Alnus alnobetula subsp. crispa (Aiton) Raus,  Alnus alnobetula subsp. fruticosa (Rupr.) Raus, and Alnus alnobetula subsp. sinuata (Regel) Raus.  These names should be in VASCAN, at least as synonyms if not primary scientific names.

See also Chery, J. 2015. New nomenclature combinations in the green alder species complex (Betulaceae). PhytoKeys 56: 1–6.

I will send you PDFs of these articles via email.

MIKE OLDHAM

**Comment by brouille** [comment]
Change done. Will appear at the next publication of VASCAN.
Luc
