### ISSUE TITLE
Bromus catharticus Exclude for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2423]
http://data.canadensys.net/vascan/taxon/7452?lang=en

Change Bromus catharticus from Introduced to Excluded for Ontario.  Not known outside cultivation in Ontario, to my knowledge.  No source for occurrence in Ontario given in VASCAN, but not accepted in floristic works that I am aware of.  E.g. Scoggan (1978-1979- Flora of Canada) only Ontario record listed is "grounds of the Central Experimental Farm, Ottawa; DAO"; Morton and Venn (1990; Checklist of Plants of Ontario) "reject, no confirmed reports away from cult."; Dore and McNeill (1980; Grasses of Ontario) "sometimes cultivated as an ornamental plant but is not known as an escape".  Not listed for Ontario in Newmaster et al. (1998) or in NHIC database.

MIKE OLDHAM

**Comment by brouille** [comment]
excluded cultivated (and old)
Thanks
L
