### ISSUE TITLE
Bromus squarrosus var. squarrosus - source of name?

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2424]
http://data.canadensys.net/vascan/taxon/28907?lang=en

The name Bromus squarrosus var. squarrosus is said to be based on FNA Vol. 24, but there is no mention of var. squarrosus in FNA Vol. 24.  

MIKE OLDHAM

**Comment by brouille** [comment]
You are correct with respect to FNA24
but
http://herbarium.usu.edu/webmanual/default.htm
Grasses of NA (FNA volume online) citing Saarela 2008
has var. squarrosus vs var. villosus
So I will cite Saarela 2008 instead
Luc
