### ISSUE TITLE
change Amaranthus caudatus from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2426]
http://data.canadensys.net/vascan/taxon/27768?lang=en

Why Excluded if there are valid Ontario specimens verified by an expert?

Rare escape from cultivation.  1940 specimen (W.R. Ellis 1844, OAC) from Stamford, Niagara R.M., cited by Costea and Tardif (2003).

MIKE OLDHAM

**Comment by brouille** [comment]
will not change
LB
