### ISSUE TITLE
change Amaranthus hybridus ssp. quitensis from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2427]
http://data.canadensys.net/vascan/taxon/27767?lang=en

Why Excluded if there are valid Ontario specimens verified by an expert?

Known only from a single collection from Toronto (W. Scott s.n. (TRT) in 1904) (Costea and Tardif 2003).

MIKE OLDHAM

**Comment by brouille** [comment]
will not change
LB
