### ISSUE TITLE
change Amaranthus hypochondriacus from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2428]
http://data.canadensys.net/vascan/taxon/27774?lang=en

Why Excluded if there are valid Ontario specimens verified by an expert?

Rare escape from cultivation. Not listed for Ontario by FNA Vol. 4 or VASCAN but listed by Costea and Tardif (2003), who cite specimens from several Ontario counties.

MIKE OLDHAM

**Comment by brouille** [comment]
the entry clearly states: old report, not established
I used the data from Costea and Tardif

I already explained the difference between our interpretations of ephemeral
Luc
