### ISSUE TITLE
change Anoda cristata from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2429]
http://data.canadensys.net/vascan/taxon/6618?lang=en

"Collected in cultivated ground ... on Pelee Island in 1956" (Montgomery 1957) and reported from St. Catherines, Niagara R.M. (McCalla in 1897; CAN) by Scoggan (1978-1979).  No recent records.

MIKE OLDHAM

**Comment by brouille** [comment]
remains excluded - I explained my reasoning to you - this is not a case of potentially recurring waif, like wheat or corn

Luc
