### ISSUE TITLE
Eriophorum tenellum not in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#243]
[Originally posted on GoogleCode (id 2460) on 2015-01-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5279?lang=en

<b>What data are incorrect or missing?</b>
NWT is listed on the distribution tab without any reference. It's not listed in FNA nor can I find any specimens for NT (checking CAN, ALTA, Consortium of Pacific Northwest, and no specimens with a previous DAO check by Erich Haber).

<b>What data are you expecting instead?</b>
Probably best to remove NWT, until there is confirmation it occurs there.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-04 19:38Z]

I am removing the report. Probably a bad entry in the old database, more than anything.

Luc
