### ISSUE TITLE
change Asperugo procumbens from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2430]
http://data.canadensys.net/vascan/taxon/3746?lang=en

Collected by J. Fletcher at Ottawa in 1883 (Montgomery 1957), and reported by Macoun (1894) from Whitby, Durham Region.  No recent records known.

MIKE OLDHAM

**Comment by brouille** [comment]
will not change
LB
