### ISSUE TITLE
recognition of Carex leersii from Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2431]
http://data.canadensys.net/vascan/taxon/4847 

FNA Vol. 23 recognizes Carex divulsa subsp. divulsa as the only subspecies of Carex divulsa occurring in North America, stating that specimens of subsp. leersii "appear to be best accommodated in subsp. divulsa".

This group has recently been investigated in Europe (Molina, A., C. Acedo, and F. Llamas. 2008. Taxonomy and new taxa of the Carex divulsa aggregate in Eurasia (section Phaestoglochin, Cyperaceae). Botanical Journal of the Linnean Society 156: 385–409.; I'll send you this via email) and the authors elevate C. divulsa subsp. leersii to species status as C. leersii F.W. Schultz.  The senior author of this study (Ana Molina) examined specimens at MICH, including several of my collections from Ontario.  She identified one Ontario collection of mine  as Carex leersii (M.J. Oldham 17182 at MICH, NHIC, det. A. Molina, from Carden Alvar, City of Kawartha Lakes) and several Ontario specimens as Carex divulsa.

My recommendation would be to accept Carex leersii as a species distinct from C. divulsa and list both from Ontario in VASCAN.  An alternative would be to add Carex divulsa subsp. leersii to VASCAN and list for Ontario.

MIKE OLDHAM

**Comment by brouille** [comment]
Segregation of C. divulsa and C. leeersii done based on Molina et al. 2008 
Report for Ont. based on NHIC
Report of divulsa kept as is for Ont.
Subsp. divulsa synonimized with species

Luc
