### ISSUE TITLE
add Carex lachenalii for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2432]
http://data.canadensys.net/vascan/taxon/4924?lang=en

First documented in Ontario in 2014 (M.J. Oldham 42374b at TRT, identified by P.W. Ball April 2015) from an open fenny pond margin at Crescent Beach candidate ANSI, ca. 95 km S of Fort Severn, ca. 94 km SSW of Hudson Bay coast.  Known from adjacent northern Manitoba and northern Quebec.

MIKE OLDHAM

**Comment by brouille** [comment]
added, source TRT
