### ISSUE TITLE
change Carex lapponica from Native to Doubtful for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2433]
http://data.canadensys.net/vascan/taxon/4931?lang=en

Not listed for Ontario by Morton and Venn (1990) or FNA (Vol. 23), but reported from Cape Henrietta Maria by Riley (2003; as C. canescens var. subloliacea) and listed for Ontario by VASCAN (Brouillet et al. 2010+).  No known verified Ontario records; no specimens at TRT or TRTE (P.W. Ball pers. comm.).

MIKE OLDHAM

**Comment by brouille** [comment]
excluded as undocumented
