### ISSUE TITLE
change Chenopodium ficifolium (and subsp. ficifolium) from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2434]
http://data.canadensys.net/vascan/taxon/4505?lang=en

Morton and Venn (1990; as C. serotinum) include the species for Ontario based on "a single plant found in the wild in 1964". Presumably this is the report from Kettle Point, Lambton County, by Gaiser and Moore (1966) who state "Dr. Wahl wrote: This is of very particular interest. The leaf shape, small seeds, finely reticulate pericarp and farinules mark it as the widespread Eurasiatic C. serotinum. This is the fourth known collection from North America, two others being from southwest Pennsylvania and one from Florida". Not mentioned from Ontario by Bassett and Crompton (1982), though mapped from Ontario in FNA Vol 4 (2003). Chenopodium ficifolium has often been called C. serotinum, though the type of C. serotinum is a sterile Atriplex specimen (FNA Vol. 4). No recent Ontario records.

MIKE OLDHAM

**Comment by brouille** [comment]
although limit, I will not change the status - at most it would be ephemeral in my own definition, but since it does not recur, it would not fit
LB
