### ISSUE TITLE
add Crataegus jesupii for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2435]
Crataegus jesupii Sargent is accepted as a valid species for Ontario in FNA Vol. 9 but is not included in VASCAN.

MIKE OLDHAM

**Comment by brouille** [comment]
name added with FNA 9 as ref.

**Comment by brouille** [comment]
@MFavreau 
MArilyn and Marc
Please add vernacular name
see http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250100115 for English

Luc

**Comment by MFavreau** [comment]
French name added. After H. G. Jesup (1826-1903), according to Gray's Manual.

**Comment by manions** [comment]
English vernacular added
