### ISSUE TITLE
change Dianthus chinensis from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2438]
http://data.canadensys.net/vascan/taxon/4286?lang=en

Reported as inclined to persist in sandy ground at Point Edward, Lambton County, by Dodge (1915).  No more recent records known.  Included for Ontario by Scoggan (1978-1979, Morton and Venn (1990), and Newmaster et al. (1998).

MIKE OLDHAM

**Comment by brouille** [comment]
will not change
LB
