### ISSUE TITLE
exclude Dichanthelium acuminatum subsp. acuminatum from Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2439]
http://data.canadensys.net/vascan/taxon/7541?lang=en

According to FNA Vol. 25 this subsp. occurs "on the Atlantic and Gulf Coastal Plains" and I believe that Ontario reports of it should be referred to subsp. implicatum (or other Dichanthelium).  Dichanthelium acuminatum subsp. acuminatum is not accepted for Michigan by Voss and Reznicek (2012). Reznicek (pers. comm. 2015) informed me that "The type of D. acuminatum is from Jamaica -- and most people give the typical subspecies or variety a SE coastal plain distribution in the US -- Massachusetts south to Florida,  west to Texas (also in West Indies, Mexico, Central America, and n. South America). It's not anything we seem to have in SW Michigan, where some plants with this distribution do occur (at least not that we have recognized), so no -- I should think it impossible that it could occur in Ontario."

MIKE OLDHAM

**Comment by brouille** [comment]
The species was excluded from Canada in revision of sect. Lanuginosa
Luc
