### ISSUE TITLE
question about Carex atratiformis reported for Nunavut

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#244]
[Originally posted on GoogleCode (id 2470) on 2015-02-02]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4761?lang=en

<b>What data are incorrect or missing?</b>
Carex atratiformis isn't listed for NU in the text in FNA, but has a dot present for NU on the map.
There isn't any distribution reference for listing NU in the VASCAN database but it's listed as native.

<b>What data are you expecting instead?</b>
I've searched literature and online herbaria without any luck to find Carex atratiformis present in NU. It's also not listed for any islands in James Bay or Hudson Bay by Kotanen 2005 and Blondeau &amp; Roy 2004.
I think the dot on the FNA map for NU is a mistake. Should it be listed as doubtful for NU or excluded for NU?
Nearest locations seem to be Hudson Bay lowlands in Ontario (Riley 2003).

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 18:16Z]

You seem to forget that Nunavut also includes southern James Bay Islands, such as Charleston. I need to check lists from there.

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-06 21:45Z]

AS I cannot find any documentation, I am simply removing Nu from the range.

Luc
