### ISSUE TITLE
add Dichanthelium acuminatum subsp. columbianum to VASCAN for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2440]
http://data.canadensys.net/vascan/taxon/7542?lang=en

This subsp. is fairly common and widespread in southern and central Ontario and has been generally called Panicum columbianum in Ontario (e.g. Dore and McNeill 1980, Morton and Venn 1990, Newmaster et al. 1998).

I was confused by synonymy here and posed the following question in an email to Tony Reznicek: 

"Dichanthelium columbianum, in the sense you use it in the Michigan Field Manual, is presumably the same thing as what Dore and McNeill call Panicum columbianum var. siccanum.  FNA calls P. columbianum var. siccanum a synonym of D. acuminatum subsp. implicatum, though they also recognize D. acuminatum subsp. columbianum.  It seems to make more sense to me that D. columbianum (sensu Michigan Field Manual) is the same as D. acuminatum subsp. columbianum (sensu FNA) and P. columbianum var. siccanum (sensu Dore & McNeill), but perhaps I'm missing something.  Unfortunately FNA does not map the subsp. separately or list states and provinces of occurrence."

Tony's response (pers. comm. 2015) was:

"This issue comes about because Hitchcock & Chase, in their big monograph of Panicum, split P. columbianum into different entities, the northern one of which (called Panicum tsugetorum) was the one that occurs in Ontario.  Nowadays, everyone lumps Panicum tsugeorum with P. columbianum. But, wanting to still  recognize Panicum tsugetorum as a variety, Dore & McNeill used the varietal name var. siccanum -- the type of which I have not seen. But if you do not even recognize varieties, our Ontario and Michigan plant simply becomes Panicum columbianum or Dichanthelium columbianum =  D. acuminatum subsp. columbianum.

  What FNA is suggesting is that Dore & McNeil were mistaken to use the name "var. siccanum" to apply to P. tsugetorum (or columbianum s.l.) As I've not seen the type, I don't have an opinion here.

  But regardless, Ontario plants are certainly Dichanthelium acuminatum subsp. columbianum in the sense of FNA despite their putting the name "var. siccanum into the synonymy of D. acuminatum subsp. implicatum"

The last sentence above is the key, and agrees with what I was thinking, i.e. we have Dichanthelium acuminatum subsp. columbianum quite commonly in Ontario (and Dore and McNeill 1980 also map it for Quebec, as P. columbianum var. siccanum).

MIKE OLDHAM

**Comment by brouille** [comment]
Done with revision of Dichanthelium sect. Lanuginosa in VASCAN
Luc
