### ISSUE TITLE
add Dichanthelium ovale subsp. praecocius to VASCAN for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2441]
http://data.canadensys.net/vascan/taxon/7562?lang=en

Occurs in prairie remnants in southwestern Ontario.  A taxonomically complex plant which has been variously treated by different authors, e.g. called Dichanthelium praecocius by Voss and Reznicek (2012), called D. villosissimum var. praecocius by Argus et al. (1982-1987), included in Panicum acuminatum by Morton and Venn (1990), called P. lanuginosum var. praecocius by Dore and McNeill (1980).

MIKE OLDHAM

**Comment by brouille** [comment]
Done with other Dichanthelium in the group
