### ISSUE TITLE
change Echinochloa frumentacea from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2442]
http://data.canadensys.net/vascan/taxon/7577

According to Dore and McNeill (1980) stray plants may be seen in dumps or along field margins but do not perpetuate themselves from year to year in Ontario.

MIKE OLDHAM

**Comment by brouille** [comment]
ephemeral

However, it would be best if specimens were filed in herbaria from time to time to prove this. All reports currently are old. 
Luc
