### ISSUE TITLE
add Epilobium arcticum for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2443]
http://data.canadensys.net/vascan/taxon/6760?lang=en

Recently collected in Ontario.  M.J. Oldham 42397 (NHIC, TRT; det. P.W. Ball) in 2014 from bedrock outcrop on east side of Severn River, ca. 47 km SSW of Fort Severn.  Only Ontario record.

MIKE OLDHAM

**Comment by brouille** [comment]
added for Ontario with source TRT
Luc
