### ISSUE TITLE
add Euphrasia randii for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2444]
http://data.canadensys.net/vascan/taxon/7015?lang=en

Known in Ontario from three specimens (all var. farlowii) from the Hudson Bay Lowlands identified by either Galina Gussarova (University of Oslo) or Peter Ball (University of Toronto), specimens at NHIC, O, PFM, TRTE.  Likely more widespread but undercollected.

MIKE OLDHAM

**Comment by brouille** [comment]
added source TRTE
