### ISSUE TITLE
add Euphrasia suborbicularis for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2445]
http://data.canadensys.net/vascan/taxon/7020?lang=en

Known in Ontario from a single collection from the Hudson Bay Lowland where collected by M.J. Oldham in 2001 (#26543; NHIC, O) and identified by Galina Gussarova.  Further collecting in the area or examination of herbarium specimens my turn up additional records as this genus is poorly known.

MIKE OLDHAM

**Comment by brouille** [comment]
added with NHIC as source
