### ISSUE TITLE
add Euphrasia wettsteinii for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2446]
http://data.canadensys.net/vascan/taxon/9820?lang=en

11 specimens (at NHIC, O, PFM, TRTE) from widespread sites in northern Ontario (Kenora District and Thunder Bay District) have been identified as this species by Galina Gussarova (University of Oslo) or Peter Ball (University of Toronto), suggesting the species is widespread in northern Ontario.

MIKE OLDHAM

**Comment by brouille** [comment]
added with source TRTE
