### ISSUE TITLE
change Grindelia hirsutula from Native to Introduced for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2448]
http://data.canadensys.net/vascan/taxon/3181?lang=en

I don't know what the basis is for the inclusion of Grindelia hirsutula for Ontario in FNA Vol. 20, but presumably they saw specimen(s).  The only Grindelia reported from the province (other than in FNA) is G. squarrosa which is invariably considered introduced (e.g. Scoggan 1978-1979, Morton and Venn 1990, Newmaster et al. 1998).  I have seen Grindelia a number of times in Ontario and always in disturbed situations and I have not seen it in natural habitats in the southern part of NW Ontario near Manitoba where it might be expected to occur if it were native.

Scoggan (1978-1979) reports G. squarrosa var. quasiperennis (a synonym of G. hirsutula according to FNA) as widespread in Ontario (11 counties) based on Groh (1929).  However Groh (1929) reports the species from Ontario but does not mention any subspecies.

MIKE OLDHAM

**Comment by brouille** [comment]
corrected
