### ISSUE TITLE
change Helianthus nuttallii (and subsp. rydbergii) from Native to Introduced for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2449]
http://data.canadensys.net/vascan/taxon/3199
http://data.canadensys.net/vascan/taxon/3200

I feel that Helianthus nuttallii is entirely introduced in Ontario (all records of both subsp.).  

Mapped from Ontario by FNA Vol. 21.  Although considered native to Ontario by Morton and Venn (1990) and VASCAN (Brouillet et al. 2010+), the only available Ontario records (2 specimens, 1 from Kenora District and 1 from Rainy River District) come from along railways.  This species has not been encountered during extensive NHIC surveys of natural habitats in the Rainy River and Lake of the Woods areas of northwestern Ontario and seems likely to be a rare introduction in the province.  It is not known from the Hudson Bay Lowland (Riley 2003).

MIKE OLDHAM

**Comment by brouille** [comment]
This looks more like at most an ephemeral (my sense) or even excluded/ephemeral
But why does Scoggan mentions it at Fort Hope?
Have you seen all specimens (including DAO)?
How old are the specimens?
Luc
