### ISSUE TITLE
change Hordeum marianum (and subsp. gussoneanum) from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2450]
http://data.canadensys.net/vascan/taxon/7728?lang=en

Single Ontario record from "Ball Grounds, Toronto" collected by W. Scott in 1904 (see Dore and McNeill 1980, under Hordeum geniculatum, page 221).  Reported as Hordeum pusillum by Montgomery (1956).  Accepted as a valid Ontario species in the provincial checklists of Morton and Venn (1990) and Newmaster et al. (1998).

MIKE OLDHAM

**Comment by brouille** [comment]
will not change
LB
