### ISSUE TITLE
change Hordeum pusillum from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2451]
http://data.canadensys.net/vascan/taxon/7733?lang=en

Reported by Macoun (1888) as an introduction along a railway in Amherstburg, Essex County. No subsequent Ontario reports (Dore and McNeill 1980).   Accepted as a valid Ontario species in the provincial checklists of Morton and Venn (1990) and Newmaster et al. (1998).

MIKE OLDHAM

**Comment by brouille** [comment]
will not change
LB
