### ISSUE TITLE
recognition of Houstonia canadensis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2452]
http://data.canadensys.net/vascan/taxon/9033?lang=en

No source is provided in VASCAN for the taxonomic reference used for Houstonia.  I suggest recognizing Houstonia canadensis Willd. ex Roemer & J.A. Schultes as a separate species from H. longifolia following the most recent revision of the genus (Terrell, E.E. 1996. Revision of Houstonia (Rubiaceae - Hedyotidea). Systematic Botany Monographs 48, University of Michigan Herbarium, Ann Arbor, Michigan.).  Terrell (1996) is followed by recent floras for areas near Canada (e.g. Voss & Reznicek 2012, Haines 2011) and although there are occasional intergrades (Terrell 1996, Voss & Reznicek 2012) the two are generally readily distinguished.  In Canada H. canadensis occurs only in Ontario.

MIKE OLDHAM

**Comment by brouille** [comment]
I do not know what was used for Houstonia. It is clearly an error. 

H. canadensis added

Luc
