### ISSUE TITLE
add Huperzia haleakalae for Ontario (Native)

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2453]
http://data.canadensys.net/vascan/taxon/6584?lang=en

Two collections from the Cape Henrietta Maria area of the Hudson Bay Lowland in northern Ontario (M.J. Oldham 25960 at MICH, NHIC, VT; M.J. Oldham 26034d at MICH, VT) have been recently identified as belonging to this species (Weston Testo, University of Vermont, March 2015 pers. comm.).  In North America the species is primarily western in distribution (FNA Vol. 2, 1993) though specimens from northern Saskatchewan and northern Quebec have recently been identified as belonging here.  Distribution and status of H. haleakalae in Ontario is poorly known due to confusion with similar species (H. arctica, H. selago) and the fact that it occurs in a remote and under-explored part of the province.

MIKE OLDHAM

**Comment by brouille** [comment]
added
