### ISSUE TITLE
taxonomy of Juncus effusus aggregate

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2454]
http://data.canadensys.net/vascan/taxon/6276?lang=en

Suggest following Kirschner's (2002) world monograph on Juncaceae for the Juncus effusus group (and all Juncus) rather than FNA.  Kirschner (2002) is followed by VASCAN for the Juncus arcticus-balticus group but not for the J. bufonius or J. effusus groups (any basis for this?).  Many authors, particularly European, but also in North America, recognize additional taxa in this group than are recognized by FNA and VASCAN.  E.g. Morton and Venn's (1990) Ontario checklist recognizes J. pyliae and Haines (2011; Flore Novae-Angliae) follows Kirschner (2002).  See also Hämet-Ahti, L. 1980. The Juncus effusus aggregate in eastern North America. Ann. Bot. Fenn. 17: 183-191.

If Kirschner (2002) is followed provincial/territorial distribution in Canada can be found in Kirschner (2002) and Hämet-Ahti (1980).  Juncus pyliae is widespread in southern Ontario (Hamet-Ahti 1980, Kirschner et al. 2002), and while not mapped from Ontario by Hamet-Ahti (1980) or Kirschner et al. (2002) J. conglomeratus has been collected in Ontario; J. pyliae is native and J. conglomeratus is exotic. Hamet-Ahti (1980), Kirschner et al. (2002), and Haines (2011) recognize two subspecies of J. effusus occurring in northeastern North America, ssp. effusus (exotic) and ssp. solutus (native), both of which are reported from Ontario (Kirschner et al. 2002). 

MIKE OLDHAM

**Comment by brouille** [comment]
Juncus bufonius complex done : J. bufonius, J. ranarius (both native), J. minutulus (int NS)
cannot determine with certainty whether J. hybridus present in Canada, though the syn J. ambiguus mentioned (but report appear to belong to ranarius)
J. effusus complex: J. conglomeratus and J. pylaei added
J. effusus with 3 subspp: effusus, solutus, pacificus

**Comment by brouille** [comment]
@MFavreau 
Marc et Marilyn:

Comme vous pouvez le voir, j'ai travaillé le complexe du J. effusus. Dans l'entrée ci-haut, vous pourrez voir les espèces et sous-espèces affectées. Des noms vernaculaires sont nécessaires pour tous les nouveaux taxons et parfois un nettoyage s'impose.

Il ne faut laisser que des noms acc. sous J. effusus car les subspp. devraient recevoir les divers noms disponibles. À vous de répartir.

MErci
Luc

**Comment by MFavreau** [comment]
J'ai ajouté ou rajusté les noms français.

Marilyn : for J. pylaei (La Pylaie's), J. conglomeratus (massed together) and J. effusus ssp. solutus (loosened), the meaning of the epithet is explained in Fernald (1950).

**Comment by brouille** [comment]
is this done?
Luc

**Comment by MFavreau** [comment]
Cest terminé en ce qui concerne les noms français.

Marc

---

De : brouille [mailto:notifications@github.com] 
Envoyé : 14 mars 2016 14:26
À : Canadensys/vascan-data
Cc : MFavreau
Objet : Re: [vascan-data] taxonomy of Juncus effusus aggregate (#2454)

is this done?
Luc


Reply to this email directly or view
<https://github.com/Canadensys/vascan-data/issues/2454#issuecomment-19645525
6>  it on GitHub.
<https://github.com/notifications/beacon/ALN5j3hAaieFpK4WZCzPqmHvsLGRb-4Bks5
ptagzgaJpZM4F-cZm.gif> 

---

size=1 width="100%" noshade color="#a0a0a0" align=center> 

Aucun virus trouvé dans ce message.
Analyse effectuée par AVG - www.avg.fr
Version: 2016.0.7497 / Base de données virale: 4542/11829 - Date: 17/03/2016

**Comment by manions** [comment]
finished the English vernaculars
