### ISSUE TITLE
change Lavatera thuringiaca from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2455]
http://data.canadensys.net/vascan/taxon/6625?lang=en

Found by C. Frankton in 1955 on the Rideau Canal, just S of Ottawa (Montgomery 1957; DAO).  Considered "an occasional garden-escape ... but scarcely established" by Scoggan (1978-1979).  Accepted as a valid member of the Ontario flora by Morton and Venn (1990) and Newmaster et al. (1998).  No recent records known.

MIKE OLDHAM

**Comment by brouille** [comment]
will not change unless recent reports are provided
LB
