### ISSUE TITLE
change Lepidium aucheri from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2456]
http://data.canadensys.net/vascan/taxon/4060?lang=en

"adventive, single collection dated 1906" (Morton and Venn 1990), based on a W. Scott collection (TRT) from a ball park in Toronto.  No subsequent Ontario records.  Not mentioned in FNA Vol. 7.

MIKE OLDHAM

**Comment by brouille** [comment]
will not change
LB
