### ISSUE TITLE
add Lolium temulentum (and subsp. temulentum) for Ontario (as Epehmeral)

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2457]
http://data.canadensys.net/vascan/taxon/7759?lang=en

Rare and sporadic ephemeral introduction in southern Ontario (Dore and McNeill 1980). Spontaneous occurrences at Snelgrove (Peel Region) in 1913, Sarnia (Lambton County) in 1952, and known from a dump at Guelph (Wellington County) in 1928, and the harbour front at Kingston (Frontenac County) in 1932 (Dore and McNeill 1980).  No recent reports known.

MIKE OLDHAM

**Comment by brouille** [comment]
in VASCAN, it is not listed as excluded/old report (not relocated)
Luc

**Comment by MichaelOldham** [comment]
My suggestion was that it should be listed as "excluded/old report (not relocated)" because there are no records since 1952 as far as I know.

**Comment by MichaelOldham** [comment]
Just checked VASCAN where it is listed as "?" (doubtful) for ON, but there are specimens from multiple locations and it is included in multiple Ontario lists and floras, so not doubtful in my opinion.

**Comment by brouille** [comment]
Mike

I believe there is a misunderstanding here. Status is not assigned to species when there are infraspecies represented. 
For Lolium tomentulum (http://data.canadensys.net/vascan/taxon/7759), there are:
Lolium temulentum Linnaeus subsp. temulentum (/7761) = excluded
and 
Lolium temulentum subsp. remotum (/7758), currently labeled as "doubtful" (= uncertain)
The calculation is that we provide for the species the "highest" status, and therefore in this case doubtful is assigned for the species.
However, if subsp. remotum were to be excluded also, THEN the species status

**Comment by brouille** [comment]
Then the species status would be excluded.

There is ambiguity for subsp. remotum currently that was not addressed.

Luc
