### ISSUE TITLE
change Mercurialis annua from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2459]
http://data.canadensys.net/vascan/taxon/5619?lang=en

VASCAN excludes this species for Ontario stating "old report, not established" and citing Scoggan 1978-79, but Scoggan does not indicate that the species was not established.  As far as I can tell we have no information on whether or not the species was established at various collection sites, only that there are no recent records.  Personally I prefer to see such species treated as Ephemeral (once present, and apparently no longer present) rather than Excluded, since they are included in other floras and checklists.

Collected from a wharf at Chatham, Chatham-Kent County, in 1890 by Cox, specimen at CAN (Scoggan 1978-1979).  No more recent records known.  Accepted as a valid Ontario species by Morton and Venn (1990) and Newmaster et al. (1998).

MIKE OLDHAM

**Comment by brouille** [comment]
will not be done
LB
