### ISSUE TITLE
change Oenothera glazoviana from Excluded to Ephemeral for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2460]
http://data.canadensys.net/vascan/taxon/6816?lang=en

Two old collections are at CAN, both collected by T. Burgess: near London in 1883 and Woodstock in 1883, both determined by W. Dietrich.  Also a recent collection from Halton Region (W.J. Crins pers. comm.; specimen at TRTE).  Not in Morton and Venn (1990).  A probable garden escape (Voss and Reznicek 2012).

MIKE OLDHAM

**Comment by brouille** [comment]
not done
LB
