### ISSUE TITLE
add Papaver somniferum for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2462]
http://data.canadensys.net/vascan/taxon/7126?lang=en

A Eurasian species introduced with grain or a garden-escape to roadsides and waste places in North America (Scoggan 1978-1979).  Reported in regional floras and checklists from various southern Ontario counties north to the Ottawa District (e.g. Peel, Simcoe, Toronto, Hamilton-Wentworth, Manitoulin, Ottawa-Carleton, Lanark).  Most populations probably ephemeral.

All Papaver species in Ontario should probably be considered Ephemeral.  I've never seen any Papaver species outside cultivation in Ontario, though Morton and Venn (1990) list four for the province (all also listed for Ontario in VASCAN, except P. somniferum).

MIKE OLDHAM

**Comment by brouille** [comment]
ephemeral
