### ISSUE TITLE
change Penstemon calycosus to Excluded for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2463]
http://data.canadensys.net/vascan/taxon/24968?lang=en

Listed only for Ontario in VASCAN, based on Newmaster et al. (1998), however this source makes no mention of P. calycosus or any synonyms for it.  I am not aware of any records of this species for Ontario or any published sources that mention it in the province.  It is listed in the Draft FNA treatment for Penstemon (28 Dec. 2011) so perhaps the author saw Ontario specimens.  Until we know of an Ontario specimen or better information on its presence here, I would prefer it be excluded for Ontario, since it is not listed in previous floristic treatments or provincial checklists.  

MIKE OLDHAM

**Comment by brouille** [comment]
Did you comment on the FNA draft at the time?
Luc

**Comment by brouille** [comment]
I am excluding it, but I have no source to do so propertly
