### ISSUE TITLE
change subsp. to var. for Polygonatum biflorum subsp. melleum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2464]
http://data.canadensys.net/vascan/taxon/2746?lang=en

Polygonatum biflorum subsp. melleum (Farwell) R. Ownbey is not a valid combination.  This name was applied as a variety by Ownbey not as a subspecies (see Ownbey, R.P. 1944. The liliaceous genus Polygonatum in North America. Annuals of the Missouri Botanical Garden 31(4): 373-413.).  P. biflorum subsp. commutatum also needs to be changed to var., following FNA Vol. 26.

MIKE OLDHAM

**Comment by brouille** [comment]
Mike

I cannot change the rank myself ; I need to ask the database person (the editor has the quirk that the data manager cannot change this particular datum...) . We have a new programmer who is unfamiliar with VASCAN yet. I am asking him.

Luc

**Comment by brouille** [comment]
correction done
Luc
