### ISSUE TITLE
Anemone multiceps

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2469]
@manions 
Anemone multiceps http://data.canadensys.net/vascan/taxon/19517

This taxon was erroneously placed in synonymy of another species. It is recognized.

I entered the vernacular English from FNA, but I am not sure it is adequate.

Un vernaculaire français est requis.

Merci
Luc

**Comment by MFavreau** [comment]
Nom français ajouté, d'après le nom latin, après vérification dans la description originale de Greene (1893).

Marilyn, you may want to check the adequacy of the name used in FNA, since several species can have purple flowers.

Marc

**Comment by manions** [comment]
reviewed the English vernaculars for Anemone. Thanks for pointing out about A. multiceps.
