### ISSUE TITLE
add Huperzia arctica for Ontario (Native)

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2470]
http://data.canadensys.net/vascan/taxon/23487?lang=en

Specimen from Winisk, Ontario, cited in Gilman & Testo 2015 (Gilman, A.V., and W.L. Testo. 2015. Use of Gemma Characters to Identify North American Huperzia (Lycopodiaceae). American Fern Journal 105(3):145–161.). 

MIKE OLDHAM

**Comment by brouille** [comment]
added
