### ISSUE TITLE
change Huperzia selago to Native in BC

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2471]
http://data.canadensys.net/vascan/taxon/6588?lang=en

Specimen from BC, cited in Gilman & Testo 2015 (Gilman, A.V., and W.L. Testo. 2015. Use of Gemma Characters to Identify North American Huperzia (Lycopodiaceae). American Fern Journal 105(3):145–161.). [Kootenay Dist., Kokanee Glacier Provincial Park, “moist slopes,” Thompson 14443 (WTU; mixed  sheet with H. haleakalae, Neville Jones 8967)]

MIKE OLDHAM

**Comment by brouille** [comment]
added
This is a nice paper. Thanks.
Luc
