### ISSUE TITLE
add SK and QC as Native for Huperzia haleakalae

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2472]
http://data.canadensys.net/vascan/taxon/6584?lang=en

Specimens from SK and QC cited in Gilman & Testo 2015 (Gilman, A.V., and W.L. Testo. 2015. Use of Gemma Characters to Identify North American Huperzia (Lycopodiaceae). American Fern Journal 105(3):145–161.).  "One specimen (Raup 6367, GH) was from the northern shore of Lake Athabaska in Saskatchewan; the other (Abbe and Abbe 3171, GH), from Richmond Gulf in 
northern Quebec, extends the range of H. haleakalae eastward by approximately 3000 km."  "Quebec: Nunavik, Richmond Gulf, S of Cairn Island, “moist pockets and crack in granite hills,” Abbe and Abbe 3171 (GH). Saskatchewan: Northern Reg., Vicinity of Charlot Pt., Lake Athabaska, 
Raup 6367 (GH; mixed sheet with H. selago, Raup and Abbe 4591)."

MIKE OLDHAM

**Comment by brouille** [comment]
Added
Also added Yukon, which Bennet had me removed, because of this paper
Luc
