### ISSUE TITLE
Hieracium xfassettii in Nfld?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2473]
re: http://data.canadensys.net/vascan/taxon/29117

The parentage of H. xfassettii, which is now the accepted name of H. xfernaldii, 
is listed as H. scabrum x H. umbellatum (or as Lepage recorded H. canadense x H. scabrum),

 but H. scabrum does not occur in NL, so is the NL report incorrect, or is the parentage of H. xfernaldii incorrect?

**Comment by brouille** [comment]
You ask me questions to which I cannot readily answer: is it possible the report is simply erroneous?

The parentage of the hybrid was verified (though who knows).

Luc

**Comment by brouille** [comment]
The parentage of fassettii is indeed scabrum x umbellatum. I just checked the MT material, where there is no NF material for this nothotaxon.

Luc

**Comment by brouille** [comment]
Excluded from Nfld, undocumented
LB
