### ISSUE TITLE
Orthographe autorité_Solidago randii (Porter) Britton

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#2474]
Vascan = Solidago randii (Porter) Briton
http://data.canadensys.net/vascan/taxon/12256?lang=fr

Astereae lab semple = ... Britton
https://uwaterloo.ca/astereae-lab/research/goldenrods/classification-and-illustrations/solidago-simplex/var-monticola

The Plant list = ... Britton
http://www.theplantlist.org/tpl1.1/record/gcc-86186

Geoff

**Comment by brouille** [comment]
basionyme Solidago virgaurea var. randii Porter  
donc VASCAN OK voir aussi TROPICOS et IPNI
PL est erroné
Luc

**Comment by geoffreyhall** [comment]
Vascan = Solidago randii (Porter) Briton
http://data.canadensys.net/vascan/taxon/12256?lang=fr

Britton de Nathaniel L. Britton, je crois que Briton est une faute de frappe

Britton selon Tropicos
http://www.tropicos.org/Name/2725287

Britton selon IPNI
http://www.ipni.org/ipni/idPlantNameSearch.do;jsessionid=1C4F15660D276133CABF6AA851EA0F89?id=240451-2&back_page=%2Fipni%2FeditSimplePlantNameSearch.do%3Bjsessionid%3D1C4F15660D276133CABF6AA851EA0F89%3Ffind_wholeName%3DSolidago%2Brandii%26output_format%3Dnormal

**Comment by geoffreyhall** [comment]
SVP vérifier la base de données où le nouveau traitement de Vascan n'a pas été ajouté

**Comment by brouille** [comment]
J'ai vérifié tous les Solidago de la bd
Luc
