### ISSUE TITLE
Botrychium alaskense author name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2475]
http://data.canadensys.net/vascan/taxon/9840?lang=en

Change Wagner & Grant to W.H. Wagner & Grant to be consistent with other Botrychium scientific names.

MIKE OLDHAM

**Comment by brouille** [comment]
Worse than that: IPNI and TROPICOS have W.H. Wagner & J.R. Grant
corrected
Luc
