### ISSUE TITLE
Castilleja parviflora varieties

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2478]
@manions 
Varieties are recognized in the FNA draft for this species.

There were no vernaculars for the infraspecies. I tentatively added those that were appropriate, but please verify. French vernaculars are needed.

see document sent earlier
Luc

**Comment by MFavreau** [comment]
Noms français ajoutés.
Marc

**Comment by manions** [comment]
finished review of the Castilleja English vernaculars.
Just need to look at adding C. gracillima and C. purpurascens into the VASCAN database, as mentioned for Canada in the FNA manuscript
