### ISSUE TITLE
Hypericum tetrapterum - vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2479]
@MFavreau 
Mike Oldham a ajouté Hypericum tetrapterum à la liste de l'Ontario et B.C., une espèce nouvelle pour nous. L'espèce provient d'Europe.

Vernaculaires anglais et français svp.

Luc

**Comment by MFavreau** [comment]
Nom français ajouté, selon TelaBotanica.

**Comment by manions** [comment]
English vernacular added
