### ISSUE TITLE
Hypericum calycinum - BC

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2480]
@MFavreau 
Espèce additionnelle en BC
http://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Hypericum%20calycinum&redblue=Both&lifeform=7

Noms vernaculaires manquent
Luc

**Comment by brouille** [comment]
provient d'Asie

**Comment by MFavreau** [comment]
Nom français ajouté. L'espèce est asiatique, mais introduite et répandue en France. J'ai donc utilisé le nom recommandé par TelaBotanica.
Marilyn : TelaBotanica mentions the English name "rose-of-Sharon".

**Comment by MFavreau** [comment]
Marilyn : The name "rose-of-Sharon" is actually used for several cultivated species, including Hibiscus syriaca (FNA6). Not a good "accepted" name.

**Comment by manions** [comment]
English vernacular added, will close this issue and I'll review all the other Hypericum taxa soon
