### ISSUE TITLE
Tilia xeuropaea - problem

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2481]
David:
17313
While trying to change the status of this entity from synonym to accepted, something unusual happened that I seem not to be able to crawl out from under: the interface tells me that I now have two entries of this taxon, and yet I cannot find the second one
I need to get rid of the phantom/goblin to be able to change the status.

Luc

**Comment by dshorthouse** [comment]
It looks like nothing 'stuck' in the editing actions except for the name change. Its current parent is 6645, Tila ×vulgaris and is still marked as a synonym with statusid = 2. I'm assuming then you want T. ×europea's parent to be 1761, Tilia. Correct? There is no duplicate of anything that I can see.

**Comment by dshorthouse** [comment]
Changed statusid = 1 and parentid = 1761 for id = 17313

**Comment by dshorthouse** [comment]
Issue still present.

**Comment by brouille** [comment]
Issue now resolved
