### ISSUE TITLE
Malvaceae vernaculars - please verify all

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2482]
@MFavreau 
FNA 6 - Malvaceae was just published.
Unfortunately, it is not yet online and will not be for a while.

Vernaculars, both French and English, needs to be checked: some are missing (in English particularly) and there is a lack of sources for the names provided

Thanks
Luc

**Comment by MFavreau** [comment]
J'ai vérifié tous les noms français des Malvacées, y compris les tilleuls.

Marc

**Comment by manions** [comment]
Finished review with sources for all Malvaceae.
