### ISSUE TITLE
Drosera ENglish vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2484]
Marilyn
sources are needed for English vernaculars
Luc

**Comment by manions** [comment]
reviewed the English vernaculars and sources. Just didn't get a name for the hybrid x linglica, which simply is a combination of linearis & anglica by the first hybridization by Nagamato, but published by Kusakabe.
Martin Cheek 1993 Notes on hybrids in Drosera. Curtis's Botanical Magazine vol 10 Issue 3: 138-144 might have a name for x linglica, but I can't access it. 
A name for x linglica also might be published in Cullen et al 2011 The European Garden Flora vol 2 - also I don't have access to it.
But this is a hybrid...
