### ISSUE TITLE
Datura meteloides auct. non de Candolle ex Dunal

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2488]
Salut

Ce synonyme (Datura meteloides auct. non de Candolle ex Dunal) devrait être lié avec Datura wrightii   Regel selon FNAms
VASCAN le lie avec Datura innoxia Miller

**Comment by brouille** [comment]
Le syn est bien placé avec l'autorité Dunal
Cela provenait d'une complication avec certains auteurs et leur interpretation
