### ISSUE TITLE
Viola cucullata 9486

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2492]
David:

Viola cucullata 9486 is one of the parents of Viola ×porteriana 9536
It is indicated as a parent under the latter
But: the hybrid does not show under "parent hybrids" in the species entry

I thought this was automatic - but it appears not to always function

Could you please fix this? I wonder whether there are further cases.

Luc

**Comment by dshorthouse** [comment]
This is what I see without having made any edits. Is this correct?
![screen shot 2015-11-02 at 10 40 24 am](https://cloud.githubusercontent.com/assets/326459/10886015/2cb042de-814e-11e5-9aa5-5534b24c21f9.png)

**Comment by brouille** [comment]
Yes, the hybrid and its parent were correct

What is missing is the mention of the hybrid under the parent.

Luc

**Comment by dshorthouse** [comment]
Where do expect to see that mention being made? Please provide an example where it works as expected and I'll try to sort out what's going on in this instance.

**Comment by dshorthouse** [comment]
Does not require fix.
