### ISSUE TITLE
Viola vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2493]
@MFavreau 
Viola has received several corrections in VASCAN following the publication of FNA 6
Please verify the vernacular for Viola. Sources are often missing in English (I added some from FNA6).

The following has no vernacular: Viola novae-angliae. It is possible that some names be under V. sororia but I could not establish that with certainty
Merci
Luc

**Comment by brouille** [comment]
Names for novae-angliae found under sororia var. grisea (separated as sp)
Luc

**Comment by brouille** [comment]
Viola riviniana, added by FNA 6, has no vernacular at all
FNA6 has: Dog or wood violet

**Comment by MFavreau** [comment]
Viola subsinuata is also without a French vernacular so far, and the English name "wood violet" in FNA6 is at best unspecific. The original description (Greene 1898) states that the leaves are "subpinnately and subsinuately deeply toothed or parted". The species is illustrated in FNA6, but the "subsinuateness" of the leaves remains unclear. I might end up using a safe but bland "violette subsinuée".

**Comment by MFavreau** [comment]
J'ai vérifié et rajusté au besoin tous les noms français du genre Viola.
Marc

**Comment by manions** [comment]
All Viola English vernaculars reviewed/adjusted. 
Viola subsinuata (as V. angellae) did have an English vernacular of Angell's violet long ago in 1905, but spelling slightly different from V. angelliae. Thoughts?
This would avoid the name of 'wood', which is used elsewhere.

**Comment by MFavreau** [comment]
The spelling difference is not important, since both variants explicitly refer to the same Miss Lillie Angell. However, I normally try to avoid naming after a synonym when the types are different (even though I must admit I did  it a few times). Your next young botanist may some day discover the two species to be distinct, which makes this a risky way out.

**Comment by manions** [comment]
Thanks so much Marc! I've now found a suitable name in use.
