### ISSUE TITLE
Gratiola ebracteata Bentham ex A. de Candolle - autorité incorrecte

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2495]
Salut

Selon FNAms, l'autorité devrait être Gratiola ebracteata   Bentham in A. P. de Candolle and A. L. P. P. de Candolle

**Comment by brouille** [comment]
Fred

on n'ajoute pas les "in" parmi les autorités - cela fait partie de la citation seulement
Luc

**Comment by FredCoursol** [comment]
Je sais pour le in. C'est que tu as un ex....  Il faut donc enlever les Candolle dans Vascan
