### ISSUE TITLE
Callitriche intermedia subsp. hamulata (Kützing ex W.D.J. Koch) Clapham

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2497]
Salut

Le nom retenu dans FNAms est plutôt Callitriche brutia Petagna var. hamulata   (Kützing ex W. D. J. Koch) Lansdown.

De plus, FNAms mentionne B.C. dans la répartion géographique.  À ajouter dans VASCAN

**Comment by FredCoursol** [comment]
J'oubliais, introduite au B.C.

**Comment by brouille** [comment]
je l'ai mise comme doubtful en BC car non mentionnée par sources de BC
à valider
