### ISSUE TITLE
Carex lepidocarpa

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#25]
[Originally posted on GoogleCode (id 985) on 2012-01-23]

Salut

Carex lepidocarpa de la flore laurentienne n'est pas dans la liste des synonymes.
Carex lepidocarpa Tausch is a synonym of Carex viridula subsp. brachyrhyncha (Celak.) B.Schmid selon The Plantlist

Pas dans FNA.

Fred

**Comment by FredCoursol** [comment]
[Originally posted on GoogleCode on 2012-01-23 19:34Z]

Carex viridula Michx. ssp. brachyrrhyncha (Celak.) B. Schmid var. elatior (Schltdl.) Crins - selon PLANTS.USDA.GOV

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-24 13:30Z]

ajouté à l'aide de Crins & Ball 1989
