### ISSUE TITLE
Boechera paupercula reported for BC

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#2503]
Boechera paupercula is reported for BC but not currently listed by VASCAN.
Here is the BC E-Flora link.
http://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Boechera paupercula&redblue=Both&lifeform=7

**Comment by brouille** [comment]
It had not been listed for BC previously. It is not in FNA, yet this was revised by BC botanists too.
If I am not notified, I can hardly know

@MFavreau 
Marilyn and Marc
Please add vernaculars
Luc

**Comment by manions** [comment]
English vernaculars added

**Comment by MFavreau** [comment]
Nom français ajouté. Arabette minuscule. Normalement, l'épithète paupercula se traduit par « appauvri », mais c'est déjà utilisé pour le B. depauperata.

Marc
