### ISSUE TITLE
Tiarella californica var. austrina Lakela should be T. cordifolia var. austrina Lakela

### ISSUE THREAD

**Issue by nonenmac** [Canadensys/vascan-data#2507]
url: http://data.canadensys.net/vascan/taxon/21334

"Tiarella californica var. austrina Lakela" should be "Tiarella cordifolia var. austrina Lakela" 

ref: http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=220013540 etc.

**Comment by brouille** [comment]
correction made
