### ISSUE TITLE
Botrychium michiganense présent au Canada

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#2508]
Gilman, Arthur V.; Farrar, Donald R.; Zika, Peter F.  2015.  Botrychium michiganense sp. nov. (Ophioglossaceae), a new North American moonwort.   J. Bot. Res. Inst. Texas 9(2): 295-309

Spécimens cités des provinces suivantes :
Alberta
British Columbia
New Brunswick
Ontario
Québec
Saskatchewan

Seuls herbiers canadiens consultés :  ALTA, DAO

Geoff

**Comment by brouille** [comment]
@MFavreau 
Botrychium michiganense was added to the flora of CAnada. Vernaculars are needed. The taxon number is 29422 (if this helps...).

The paper where it was published should be attached. If it does not work, let me know I will send it via email.

Best wishes for the New Year
Luc
[295_Gilman.pdf](https://github.com/Canadensys/vascan-data/files/80327/295_Gilman.pdf)

**Comment by manions** [comment]
Great to get this taxon published! English vernacular added.
Happy New Year to everyone!

**Comment by MFavreau** [comment]
Nom français ajouté. J'ai aussi demandé à Termium de corriger sa fiche erronée.

Je vous souhaite tous un fécond et joyeux 2016!

Marc
