### ISSUE TITLE
Atriplex gmelinii var. alaskensis (S. Watson) S.L. Welsh ou Atriplex alaskensis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2512]
This species is doubtful in BC (F. Lomer, pers. Comm. 2015). Taxonomic uncertainty : this species' delimitation from A. gmelinii is questionable; very little is known about this taxon. It may be a good species, but too few specimens exist to fairly assess this. No recent records from BC (C. Bjork, pers. comm. 2014).
fide http://www.env.gov.bc.ca/atrisk/documents/2015Plant_Changes_VascularPlants.xlsx

**Comment by brouille** [comment]
doubtful
