### ISSUE TITLE
Luzula kjellmaniana - absent de BC

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2515]
The name has been commonly misapplied to L. arcuata. I have seen no specimens of typical L. kjellmaniana from BC. The specimens at V are L. arcuata (C. Bjork, pers. Comm. 2014).
fide http://www.env.gov.bc.ca/atrisk/documents/2015Plant_Changes_VascularPlants.xlsx

**Comment by brouille** [comment]
exclus
même problème de citation - je ne trouve même pas la page où on peut y accéder
