### ISSUE TITLE
Ribes oxyacanthoides var. irriguum - absent de BC et du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2516]
This is species is Reported but Unconfirmed in British Columbia. All specimens of this taxon at UBC are apparently hybrids between R. oxyacanthoides and R. inerme. All specimens are from SE BC, where the ranges of the two parental taxa overlap, and present intermediate morphology between the parental taxa that approaches that of R. irriguum (e.g., shorter hypanthia) but fits better with plants of hybrid origin (J. Fenneman pers. comm. 2014). Specimens at V still need to be examined.
fide http://www.env.gov.bc.ca/atrisk/documents/2015Plant_Changes_VascularPlants.xlsx

**Comment by brouille** [comment]
le problème ici est le suivant: comment peut-on avoir des hybrides (F1) sans avoir le parent ? 
aussi, examen spécimens à V requis

**Comment by brouille** [comment]
doubtful pour l'instant
