### ISSUE TITLE
Valeriana capitata - absent de BC

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2517]
There are no good specimens in BC. Likely based on a V specimen which was apparently re-identified because the folder for this species was empty (K. Marr, pers. Comm. 2015). 
fide http://www.env.gov.bc.ca/atrisk/documents/2015Plant_Changes_VascularPlants.xlsx

**Comment by brouille** [comment]
malheureusement, cela me laisse sans source car je ne peux citer un tel tableau

corrigé
