### ISSUE TITLE
Galium brandegei - variante orthographique  et statut taxonomique douteux

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2518]
Selon IPNI, le nom devrait être Galium brandegeei A.Gray  (deux e) à la finale.
Idem avec The Plant List & WCSP.
http://apps.kew.org/wcsp/namedetail.do?name_id=85892
De plus, le taxon n'est pas reconnu dans plusieurs sources.

Fred

**Comment by brouille** [comment]
TROPICOS aussi
corrigé
