### ISSUE TITLE
Scientific Authority for genus Astragalus

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#252]
[Originally posted on GoogleCode (id 2482) on 2015-02-11]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/872?lang=en

<b>What data are incorrect or missing?</b>
double check on this one pls
on VASCAN - Astragalus Necker
on Tropicos and IPNI - Astragalus Linnaeus

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>
http://www.tropicos.org/Name/40021672

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-25 21:56Z]

FNA also has L.

These errors may date from way back and were not caught.

Thanks
Luc
