### ISSUE TITLE
Potentilla multisecta - absent du Canada selon FNA

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2521]
Salut

L'espèce ne serait pas présent au Canada.  
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250100344

**Comment by brouille** [comment]
La difficulté ici est que je pense que l'auteur du genre n'a pas considéré la présence possible du taxon en Alberta et que cela n'a pas été validé par les réviseurs régionaux de l'ouest.

Il me faut vérifier avant de l'enlever sur la foi de FNA 9

**Comment by brouille** [comment]
Voici la discussion de FNA: Not included here are some subpalmate collections from Saskatchewan that would key to P. multisecta (for example, A. Breitung 4045, MO, RM), whose optimum disposition has yet to be resolved.
Aucune mention de l'Alberta. Je ne sais pas si l'auteur y a fait attention. Mais je ne peux enlever cette citation sans validation de quelqu'un en Alta. et Sask.
