### ISSUE TITLE
Carex ovalis - indigène au BC vs reste du Canada 

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2522]
Salut

Le BC CDC traite le Carex traceyi comme indigène.  Ce dernier est devenu un synonyme de C. ovalis.
Voir commentaire dans FNA
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242357377

**Comment by brouille** [comment]
corrigé à native
FNA indique que les populations de l'W sont indigènes - eFLora BC aussi
