### ISSUE TITLE
Naturalized species found on Mont St. Hilaire not found during 'Name search'

### ISSUE THREAD

**Issue by tle003** [Canadensys/vascan-data#2525]
Hi,

While doing my research on Mont St. Hilaire during the summers of 2012-2015, I found two naturalized species that do not come-up on the VASCAN 'Name search':
1. _Primula beesiana_ Forrest - http://www.boldsystems.org/index.php/Taxbrowser_Taxonpage?taxon=Primula+beesiana&searchMenu=taxonomy&query=Primula+beesiana; MTMG accession number - 137407; identified with _European Garden Flora_
2. _Weigela floribunda_ C.A. Mey.- http://www.boldsystems.org/index.php/Taxbrowser_Taxonpage?taxid=448600; MTMG accession number - 137409

Don't hesitate to contact me if you want to know more details about these specimens,
Tammy Elliott

**Comment by brouille** [comment]
Tammy
Two years ago (or more), I wrote Marcia Waterway asking her about the Primula and a yellow "Scroph" (frequent along the road between the house on the lake and the small meeting/teaching place). Never got an answer (it was during her sabbatical - I asked again, but...). 
Therefore, thanks for providing me the information above about the Primula and the Weigela (which I did not know about). Still need info on the scroph (probably a Plantaginaceae now). Cannot recall the name.

I am pissed off that Marcia published data in BOLD (probably contributing to a barcoding project) but did NOT publish data in Canadensys, for which she received grant money. This is an unfulfilled contract. (Sorry about this - it bothers me).
Anyway, I will be able to cite MTMG as a source for both taxa.

Thanks and best
Luc

**Comment by brouille** [comment]
@MFavreau 
Marilyn and Marc: please provide vernaculars in English and French for this species, present in Québec.

https://www.rhs.org.uk/Plants/13711/i-Primula-beesiana-i-(Pf)/Details : Bee's primrose

**Comment by brouille** [comment]
@MFavreau 
the previous was for Primula beesiana Forrest
ibid for Weigela floribunda
PLANTS: Crimson weigela

Merci
Luc

**Comment by tle003** [comment]
Hi Luc,

I wonder if the yellow Plataginaceae you are thinking of is _Digitaria lanata_ Ehrh. 
http://www.boldsystems.org/index.php/Public_RecordView?processid=VEMSH176-13; MTMG accession # 137092.

The other Lamiales in the Orobanchaceae, Phyrmaceae, Plataginaceae and Scrophulariaceae I found on MSH are listed below:

![image](https://cloud.githubusercontent.com/assets/10818993/12752418/7c7e8714-c990-11e5-9636-21f8bb0e041c.png)
![image](https://cloud.githubusercontent.com/assets/10818993/12752387/555b002c-c990-11e5-9dad-ffd76a293d93.png)

The Mont St. Hilaire project is something that I worked on solely with Jonathan Davies at McGill as a side project of my PhD (Marcia has nothing to do with this project). It is true that the specimens are published on BOLD, but to my knowledge MTMG is also preparing to publish this information on VASCAN. I can look into having the information published quicker if you think that is best.

Thanks,
Tammy

**Comment by brouille** [comment]
YEs, must be it. I noted the species as being documented at MTMG. But that might have been a guess.

I realized after having written to you that indeed you were the one sending to BOLD, not Marcia. I apologize for this. She still does not respond to our entrities to send material to Canadensys, however.

Luc

**Comment by MFavreau** [comment]
French names added for both species.
Marilyn: the name «Bee's primrose» provided by Luc is incorrect. According to Bailey, it was named after « Bees, nurseryman, Liverpool». Another source says that it was named after «Bees, a nursery and seed supplier in Cheshire, UK». Either way, it is Bees, not Bee.
Marc

**Comment by manions** [comment]
Thanks Luc et Marc (I thought that would be the case!). English vernaculars added.
Luc - Weigela floribunda is also listed as a synonym (#29476) for Weigela floribunda

**Comment by brouille** [comment]
the syn is an invalid name, added for clarification of authorities
