### ISSUE TITLE
Carex pauciflora in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#2526]
The Scotty Creek document is published now in the Can Field Naturalist, with note of this species.
Previously the photo of Arethusa bulbosa, new record for NWT, was provided also from this location. It also is mentioned in this article.
I'll try to attach.
Marilyn
[NT new boreal flora Scotty Crk 2015.pdf](https://github.com/Canadensys/vascan-data/files/112338/NT.new.boreal.flora.Scotty.Crk.2015.pdf)

**Comment by brouille** [comment]
all done
