### ISSUE TITLE
Addition au Canada - Amaranthus viridis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2529]
Salut

Selon Costea et Tardif ( Rhodora, 2003) que tu cites pour certaines espèces d'amaranthe, il existe un seul spécimen de cette espèce (les autres ont été réidentifiés) dans un champ de tomates à Saint-Césaire (récolté par D. Tanguay le 25 juillet 1983).  Le spécimen est à l'herbier QUE.

**Comment by brouille** [comment]
je l'ajoute comme éphémère avec QUE source
je vérifierais auprès de Romain Néron quant à ce statut

**Comment by brouille** [comment]
@MFavreau 
Marilyne et Marc

vernaculaires pour cette espèce de mauvaise herbe - je ne sais si elle persistera

EN: http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=200006991
FR: http://www.tela-botanica.org/bdtfx-nn-4029-synthese

Merci
Luc

**Comment by MFavreau** [comment]
Nom français ajouté.

**Comment by manions** [comment]
English vernacular added
