### ISSUE TITLE
Cyclachaena xanthiifolia - Indigène en Saskatchewan

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2532]
Salut

Le CDC de la Saskatchewan considère cette mauvaise herbe comme indigène, probablement sur ce commentaire dans Flora of North America.
Cyclachaena xanthiifolia is thought to be native to North American prairies and is evidently adventive east of the Mississippi River and in western states

**Comment by brouille** [comment]
cela laisse ouverte la question de l'indigénat en Alta. (le Man. considère cette plante introduite)
