### ISSUE TITLE
Poa nervosa - absent de l'Alberta

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2537]
Salut

La version en ligne du webmanual indique quelques points dans les Rocheuses, assez loin de la répartition plutôt du côté pacifique dans le nord-ouest des USA.  
La version papier ne comprend pas les points en question.  Il faut donc supprimer l'entrée!  

Fred

**Comment by brouille** [comment]
exclus Alta
enlevé Sask
