### ISSUE TITLE
Crassula viridis - red list in BC (S1S2)

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2538]
Salut

Il faut changer le statut douteux à celui d'indigène.
http://a100.gov.bc.ca/pub/eswp/speciesSummary.do?id=35539

Fred

**Comment by brouille** [comment]
cela ne me dit en rien sur la foi de quoi on a pris cette décision - pas de spécimen à UBC (visible du moins) - peut-être nouvelle réc. étant donné 2015, mais il y a un manque de substance dans ces entrées que je déplore
c'est d'autant plus improbable que le taxon n'approche même pas BC selon FNA:
Terrestrial or aquatic, margins of pools and streams; of conservation concern; 2100-2500 m; Ariz., Idaho; Mexico; South America (Brazil). 
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250092032

Je trouve cela trop douteux pour ajouter sans m'informer plus avant. Je ne comprends pas pourquoi ce serait indigène là.
Luc

**Comment by brouille** [comment]
indigène
