### ISSUE TITLE
Andropogon hallii - introduit en Saskatchewan

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2539]
Salut

Effectivement, il y a un seul point sur la carte et il est un peu désaxé par rapport à la répartition (Manitoba vers le sud).

Fide Grasses of Saskatchewan. 2014. Vernon L. Harms and Anna L. Leighton
http://www.naturesask.ca/publications/complete-listing

**Comment by brouille** [comment]
tu veux que je change le statut de native à introduced, si je comprends bien
je ne pourrai facilement citer Harms et Leighton (je n'ai pas la citation complète)
je change le statut en laissant la réf.
