### ISSUE TITLE
Scientific Authority for genus Delphinium

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#254]
[Originally posted on GoogleCode (id 2484) on 2015-02-13]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/1082?lang=en

<b>What data are incorrect or missing?</b>
Currently listed: Delphinium Rafinesque
Should be?: Delphinium Linnaeus

<b>What data are you expecting instead?</b>
Delphinium Linnaeus

<b>If applicable, please provide an authoritative source.</b>
Listed as Delphinium Linnaeus in FNA volume 3 1997
Also in IPNI
I couldn't connect to Tropicos to check as well

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-25 21:53Z]

Linnaeus is in TRO also
