### ISSUE TITLE
Silene scouleri - statut incertain en Alberta

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2542]
Voici le commentaire que j'ai du AB CDC
Accepted taxon found in AB according to FNA and VasCan but no AB records in Canadensys and no specimens in UofA Herbarium; not ranked in AB-NServExp; only ssp.hallii in AB=S.hallii,S.concolor,Lychnis elata-FNA

**Comment by brouille** [comment]
Il semblerait que la source de mention de cette sp. pour l'Alberta (subsp. hallii, précisons) soit Scoggan 78-79: ... and sw?Alta (Boivin 1966b) - Scoggan semble douter du rapport - je vais donc l'exclure pùr manque de documentation, citant Scoggan
C,est peut-être pour cela qu'on le trouve ds FNA
