### ISSUE TITLE
Elymus virginicus var. jejunus

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2544]
http://data.canadensys.net/vascan/name/Elymus%20virginicus%20var.%20jejunus

Reported from Ontario by VASCAN (Brouillet et al. 2010+; checked 2016-02-09) based on Newmaster et al. (1998), though the name does not appear in Newmaster et al. Not mentioned from Ontario by FNA Vol. 24 or Dore and McNeill (1980).  Reported from Moosonee by Dutilly et al. (1954) but not listed by Riley (2003) for the Hudson Bay Lowland,  Suggest removing for Ontario until a reliable record is known.

Mike Oldham

**Comment by brouille** [comment]
It is reported in FOIBIS (based on Newmaster et al. 98) as S4?
The Grass Manual recognized it (range from Alta. to Nfld.) as a taxon, but Cat. NW Grasses makes it a syn. of var. virginicus
I prefer to follow the route of synonymizing the taxon, which would rather solve the issue.
The other vars. are retained by CNWG.
Luc
