### ISSUE TITLE
Anemone nemorosa - présence non confirmée au Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2545]
Aucune source pour le Québec.  Scoggan mentionne que les stations connues dans l'E. du Québec sont probablement basées sur A. nemorosa var. bifolia (ce nom est un synonyme de A. quinquefolia).
C'est donc un cas de mauvaise synonymie en fabriquant des listes de plantes sans tenir compte des variétés.....

**Comment by brouille** [comment]
présente selon spécimens MT, au moins à Québec, dans 2 boisés distincts
