### ISSUE TITLE
Draba aleutica au Yukon

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2546]
@MFavreau 
Marilyn et Marc:

Bruce Bennett a ajouté Draba aleutica à la flore du Yukon (spécimen DAO identifié en 2011, après la publication de FNA7 en 2010)

Noms vernaculaires svp.
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250094721

Merci
Luc

**Comment by manions** [comment]
English vernaculars added

**Comment by MFavreau** [comment]
Nom français ajouté.
