### ISSUE TITLE
Ribes watsonianum - erreur dans Flora of North America?

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2547]
Flora of North America mentionne cette répartition.

Ribes watsonianum occurs in the Cascade Range of Oregon, Washington, and British Columbia, and in Alberta

**Comment by brouille** [comment]
possiblement car je ne connais pas de rapport de cette sp. pour les 2 provinces mentionnées - quelqu'un n'a pas fait son travail de révision dans l'ouest
explicitement exclus ds Douglas et non repris dans Klinkenberg, donc pas au BC
Je ne vois pas pourquoi ce serait en Alberta
Luc
