### ISSUE TITLE
Fournier 2006 is used for 2 distinct references

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#2549]
I noticed that we have 2 references coded "Fournier 2006". I would assume one of them should be "Fournier 2006b", since there is also a "Fournier 2006c". I do not know how difficult it would be to correct this, since the code may have been used several times for either references.

Marc

**Comment by brouille** [comment]
Les références de Fournier 2006 sont numérotées a, b et c. Je crois que chacune n'a été utilisée qu'une fois
