### ISSUE TITLE
Potentilla psychrophila Soják, sp. nova - Yukon

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2550]
Salut

Une addition à la flore du Canada.
Le lien de la référence: http://www.upjs.sk/public/media/5705/thaiszia-16-093-097-sojak.pdf
SOJÁK, J. (2006): Two new American species of Potentilla (Rosaceae). (Notes on Potentilla XXIII.). – Thaiszia – J. Bot. 16: 93-97. – ISSN 1210-0420.

**Comment by brouille** [comment]
@manions @MFavreau 

New vernaculars required for this species (http://data.canadensys.net/vascan/taxon/30160)

Thanks
Luc

**Comment by MFavreau** [comment]
French name added. "psychrophile" is an existing French word, it means "cold-loving".
Marc

**Comment by manions** [comment]
English vernacular added.
