### ISSUE TITLE
Strigosella africana - nom accepté dans Flora of North America pour Malcolmia africana

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2551]
Salut

Ihsan A. Al-Shehbaz a changé d'idée dans le volume 7 car nous avions reçu le traitement sous Malcolmia en 2006.  
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242350689

**Comment by brouille** [comment]
Strigosella ajouté et Malcolmia transféré
