### ISSUE TITLE
authority listed for subsp. longiflora a later homonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2553]
http://data.canadensys.net/vascan/taxon/4202?lang=en

Re: Linnaea borealis subsp. longiflora (Torrey) Hultén

Hultén published his combination in 1937, while Piper and Beattie made the same combination in 1915.

The accepted name should be: Linnaea borealis subsp. longiflora (Torrey) Piper & Beattie

Synonym: Linnaea borealis subsp. longiflora (Torrey) Hultén, nom. illeg. hom.

See Tropicos & IPNI

**Comment by brouille** [comment]
name corrected - I was waiting the FNA treatment to correct things here

still troubled by the distribution issue
