### ISSUE TITLE
Re: Catalpa speciosa authority

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2554]
Catalpa speciosa Warder ex Engelmann (1880) is a later isonym of 
Catalpa speciosa Teas (1875)
See the discussion in Taxon 60(6): 1760-1763.  (2011) by Kirkbride and Olsen.

You could also add the synonym: Catalpa bignonioides var. speciosa (Teas) Meehan (1875), which is discussed in this paper too.  This is the correct authorship of the variety, usually attributed to Warder ex Barney (1878),

**Comment by brouille** [comment]
correction made and syn. var. added
Luc
