### ISSUE TITLE
incorrect synonyms for Oxytropis campestris var. johannensis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2555]
http://data.canadensys.net/vascan/taxon/5857

The synonyms Oxytropis terrae-novae and Oxytropis campestris var. terrae-novae both refer to O. campestris var. minor, as does the common name Newfoundland oxytrope.  I checked this with Stan Welsh, who wrote the FNA treatment, as well as the monograph on Oxytropis, and sent him specimens.  The correct synonymy is as I've indicated here and in the 2015 NL checklist.

Also the common name listed for var. minor is inappropriate - small northern yellow locoweed 
since all of the plants in eastern NAm. are purple, not yellow.  See common names in our NL checklist, which were approved or coinied by Stan Welsh.

**Comment by manions** [comment]
Hi, yes I've been waiting to get this fixed up for the vernaculars. There were previous issues #906 and #5859 which I've keep on my 'backburner' list, I'm not sure if those issue numbers are still listed still.
Is it possible to see the draft FNA treatment or the Oxytropis monograph, or have a copy of the 2015 NL checklist? If the checklist - also how to cite it, for use with the vernaculars.
Thanks

**Comment by sjmeades** [comment]
Hi Marilyn,  Thanks.  The new checklist was posted online at this 
website: http://www.newfoundlandlabradorflora.ca/checklist/

I have some updates to it, but they're in the process of changing the 
FTP files to searchable internet files, with access by family and 
genus.  That is being done at the Corner Brook AFC-CFS office, so I 
don't have any control over how quickly the new files get posted.  But 
the Fabaceae list hasn't changed since this list was posted.  You can 
cite this 2015 version.

Thanks, Sue.

**Comment by brouille** [comment]
Sue

For your information, the Oxytropis treatment has yet to be circulated for review, which explains why I have not seen it yet. Should come soon as the vol. is being actively edited.

In fact, I will ask whether I can have it.

Luc

**Comment by brouille** [comment]
Sue

I checked the Oxytropis 1991 treatment by Welsh and have temporarily corrected terrae-novae as per what he did then. In there, it was a distinct var., not a synonym.

What monograph are you referring to? FNA treatment still not at hand

Luc

**Comment by sjmeades** [comment]
Stan sent me a copy of his monograph on Oxytropis a couple of yrs ago.  Here's the citation:
Welsh, S.L. 2001. Revision of North American species of Oxytropis de Candole (Leguminosae).  E.P.S. Inc., Orem, Utah.  Do you want me to scan the info on Oxytropis campestris and send to you?  He also told me he had submitted the MS for FNA several years ago, so you should be able to access it.

**Comment by brouille** [comment]
Coincidentally, right after I wrote my last message, FNA sent the Oxytropis draft. Thus all corrections are now effected.

LB
