### ISSUE TITLE
incorrect spelling of synonyms of Silene uralensis subsp. porsildii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2556]
http://data.canadensys.net/vascan/taxon/9638

The specific epithet soczavana (soczavanum) is misspelled as soczaviana or soczavianum in the following names:

Gastrolychnis soczaviana 
Melandrium soczavianum
Silene soczaviana
Silene soczaviana subsp. macrosperma

see The Plant List & IPNI; Tropicos has some correct, some incorrect

**Comment by brouille** [comment]
I just searched IPNI and it is spelled with the "-viana for GAstrolychnis but not for the others
i tried both forms and could not get the -vana form - this form does not sound Latin to me
according to TROPICOS, the original spelling of the basionym was "soczaveanum" 

This is not as clear-cut as it seems and I will have to ask Kanchi
Luc

**Comment by sjmeades** [comment]
On 2016-03-18 10:19 AM, brouille wrote:

> I just searched IPNI and it is spelled with the "-viana for 
> GAstrolychnis but not for the others
> i tried both forms and could not get the -vana form - this form does 
> not sound Latin to me
> according to TROPICOS, the original spelling of the basionym was 
> "soczaveanum"
> 
> This is not as clear-cut as it seems and I will have to ask Kanchi
> Luc
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/Canadensys/vascan-data/issues/2556#issuecomment-198380144
> 
> Good idea.  Tropicos and the BHL were down yesterday when I was 
> reviewing this, but I did not in TPL that they had referenced Tropicos.

Thanks for the update, Sue.

**Comment by brouille** [comment]
according to K. Gandhi, the proper spelling is soczvana
there is no reason it should be viana or veana
Correction done
LB
