### ISSUE TITLE
incorrect authorities in name & synonyms of Solidago ptarmicoides

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2557]
Re: http://data.canadensys.net/vascan/taxon/3472

Solidago ptarmicoides (Nees) B. Boivin
should be: Solidago ptarmicoides (Torry & A.Gray) B. Boivin

Aster albus (Nuttall) Eaton, nom. illeg. 
should be: Aster albus (Nuttall) Eaton & Wright, nom. illeg. 

Aster ptarmicoides Nees var. ptarmicoides 
should be Aster ptarmicoides Torrey & A.Gray var. ptarmicoides, since Nees did not name this species.

Diplopappus ptarmicoides (Torrey & A.Gray) Lindlley 
should be: Diplopappus ptarmicoides (Torrey & A.Gray) Lindley  (note there were 2 ll's in Lindley in your entry)

Doellingeria ptarmicoides Nees 
should be: Doellingeria ptarmicoides Nees, nom. illeg. superfl.

Unamia ptarmicoides (Nees) Greene 
should be: Unamia ptarmicoides (Torrey & A.Gray) Greene 

See IPNI for details, and the Global Compositae Checklist
http://compositae.landcareresearch.co.nz/?Page=NameDetails&NameId=DCC6B0EF-DE11-4913-BBEF-276AA4F3E8D9

**Comment by brouille** [comment]
all fixed
I wonder when the Nees error got in - probably long ago, not revisited
