### ISSUE TITLE
incorrect authority in synonym of Solidago radula

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2558]
re: http://data.canadensys.net/vascan/taxon/3475

Aster decemflora (A. Gray) Kuntze 
should be: Aster decemflora Kuntze 

since A. Gray's 1850 name, S. decemflora, is an illeg. homonym of S. decemflora DC. 1836, so can't be used.  See IPNI

**Comment by brouille** [comment]
fixed
