### ISSUE TITLE
typo in name & authority of Solidago gillmanii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2560]
re: http://data.canadensys.net/vascan/taxon/12250

Solidago gillmani (A. Gray) Steele
should be: Solidago gillmanii (A. Gray) E.S.Steele  {note the 2 'ii's in gilmanii

Solidago glutinosa var. gillmani (A. Gray) Cronquist 
should be: Solidago glutinosa var. gillmanii (A. Gray) Cronquist 

Solidago humilis var. gillmani A. Gray 
should be: Solidago humilis var. gillmanii A. Gray 

Solidago spathulata var. gillmani (A. Gray) Gleason 
should be: Solidago spathulata var. gillmanii (A. Gray) Gleason

**Comment by brouille** [comment]
fixed
