### ISSUE TITLE
Amaranthus californicus - indigène en Saskatchewan (et probablement Alberta)

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2561]
Salut

Harms a changé d'opinion.  Dans sa version ancienne, il mentionne introduit, mais dans la version 2006, il met indigène....

À corriger.

Fred

**Comment by brouille** [comment]
changement effectué pour les 2 provinces, mais j'aimerais des confirmations de Alta. parfois...
Luc
