### ISSUE TITLE
Artemisia douglasiana - découverte en BC (2011) - modifier l'exclusion pour cette province

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2562]
Salut

http://a100.gov.bc.ca/pub/eswp/reports.do?elcode=PDAST0S0G0

**Comment by MFavreau** [comment]
Un nom français était requis. Je l'ai ajouté.
English names already in.

Marc

**Comment by brouille** [comment]
corrigé - indigène - Klinkenberg
