### ISSUE TITLE
Silene hitchguirei - remove BC (aucune donnée)

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2563]
Salut

J'ai vérifié ta source avec tous les synonymes.  Aucune donnée pour BC
Flora of North America mentionne seulement Alberta.
Source pour DAO - Yukon?  Aucune mention au Yukon CDC

**Comment by brouille** [comment]
la source est DAO même, mais je ne sais qui me l'a rapportée. C'est un ajout qu'on m'a demandé de faire sur la foi du spécimen. Il faut demander à Bruce Bennett

**Comment by brouille** [comment]
enlevé de BC
