### ISSUE TITLE
remove Danthonia intermedia for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2564]
http://data.canadensys.net/vascan/taxon/7523?lang=en

Remove Danthonia intermedia and D. intermedia subsp. intermedia for Ontario.  Inclusion of this species (and subspecies) in Ontario by NHIC was based on the report by Riley (2003) from Ontario's Hudson Bay Lowland, with supporting specimens at TRT.  These specimens were recently examined by Stephen Darbyshire (Agriculture Canada and FNA treatment author) and found to be D. spicata.

MIKE OLDHAM

**Comment by brouille** [comment]
excluded misidentification TRT (since the specimen is annotated, I presume)
Luc

**Comment by MichaelOldham** [comment]
yes, specimens annotated.

mike

---

Michael J. Oldham
Ontario Natural Heritage Information Centre (NHIC)
Ministry of Natural Resources
300 Water Street, 2nd Floor, North Tower
P.O. Box 7000 Peterborough, Ontario K9J 8M5, Canada
phone 705-755-2160; fax 705-755-2168
michael.oldham@ontario.camailto:michael.oldham@ontario.ca
NHIC requests: NHICrequests@ontario.camailto:NHICrequests@ontario.ca
NHIC web page: http://nhic.mnr.gov.on.ca/nhic_.cfmhttps://webmail.ontario.ca/owa/redir.aspx?C=oYt4O5oPNUOsn1H3HmanID5fehjWsNAINC47ZwVJniyQjRw8C6vFRPVyWJ9nVJLyVpgnNwrFZYs.&URL=http%3a%2f%2fnhic.mnr.gov.on.ca%2fnhic_.cfm
Ontario Reptile & Amphibian Atlas:
http://www.ontarionature.org/protect/species/herpetofaunal_atlas.phphttps://webmail.ontario.ca/owa/redir.aspx?C=oYt4O5oPNUOsn1H3HmanID5fehjWsNAINC47ZwVJniyQjRw8C6vFRPVyWJ9nVJLyVpgnNwrFZYs.&URL=http%3a%2f%2fwww.ontarionature.org%2fprotect%2fspecies%2fherpetofaunal_atlas.php
