### ISSUE TITLE
change Grindelia hirsutula to Excluded for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2565]
http://data.canadensys.net/vascan/taxon/3181?lang=en

VASCAN lists G. hirsutula for Ontario based on FOIBIS and presumably inclusion in FOIBIS is based on FNA Vol. 20, since I know of no other reports of the species from Ontario (e.g. it is not in the OPL, Newmaster et al. 1998).  The basis is for the inclusion of Grindelia hirsutula for Ontario in FNA Vol. 20, is not known.  The only Grindelia generally reported from the province (other than in FNA) is G. squarrosa which is invariably considered introduced (e.g. Scoggan 1978-1979, Morton and Venn 1990, Newmaster et al. 1998).  Grindelia has been recently seen a number of times in Ontario and always in disturbed situations and has not been observed in natural habitats in the southern part of NW Ontario near Manitoba where it might be expected to occur if it were native.  Scoggan (1978-1979) reports G. squarrosa var. quasiperennis (a synonym of G. hirsutula according to FNA) as widespread in Ontario (11 counties) based on Groh (1929; Groh, H. 1929. Gumweed (Grindelia squarrosa (Pursh) Dunal) in Ontario. Canadiann Field-Naturalist. XLIII: 106-107.).  However Groh (1929) reports the species from Ontario but does not mention any subspecies.  Until better evidence is available I think it best to exclude the species from Ontario, which we have done in the NHIC database where it is included as "reported" (but unconfirmed) from Ontario.

MIKE OLDHAM

**Comment by brouille** [comment]
Excluded as undocumented
