### ISSUE TITLE
Lysimachia lanceolata - remove Manitoba

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2566]
Salut

Je n'ai pas réussi à trouver une source pour cette mention.  Dans les fichiers reçus pour le contrat, on mentionne "reported but doubtful".
NatureServe n'inclut pas le Manitoba dans sa répartition et il est vrai qu'en regardant les États américains, le Manitoba serait disjoint.
Je suis prêt à parier que la mention vient de "Lysimachia lanceolata subsp. hybrida (Michaux) J.D. Ray" qui est devenu Lysimachia hybrida.  Quand on ne tient pas compte des ssp., on crée des erreurs.

**Comment by brouille** [comment]
Fred:

je ne pourrai le faire automatiquement car le Manitoba Checklist la rapporte sans autre commentaire.

Tu as sans doute raison, mais je devrai vérifier avec le Manitoba avant de faire ce retrait.

Luc

**Comment by brouille** [comment]
J'ai exclus lanceolata du Man. en suivant Scoggan
Il est évident que les auteurs ont confondu lanceolata et hybrida (voir FOIBIS)
Luc
