### ISSUE TITLE
Delete Carex microglochin subsp. microglochin

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2567]
http://data.canadensys.net/vascan/taxon/4986?lang=en

FNA Vol. 23 (2002) recognizes subsp. microglochin in North America and subsp. fuegina in South America.  More recently Wheeler and Guaglianone (2003) demonstrated that subsp. fuegina is a distinct species (C. camptoglochin) and did not recognize infraspecific taxa in C. microglochin, and approach followed by other recent authors (e.g. Saarela et al. 2013).

Saarela, J.M., L.J. Gillespie, L.L. Consaul, and R.D. Bull. 2013. Annotated checklist to the vascular plant flora of Tuktut Nogait National Park and the Melville Hills region (Canadian Low Arctic). Phytotaxa 102(1): 1-177.

Wheeler, G.A., and E.R. Guaglianone. 2003. Notes on South American Carex (Cyperaceae): C. camptoglochin and C. microglochin. Darwiniana 41: 193–206.

**Comment by brouille** [comment]
taxonomy modified
I am not sure one can deduce usage of new concept from a checklist, unless it is stated clearly in said list - authors tend to eliminate infraspecies in lists, at times - probably true in this case, however
an instance of the latter is Wild Species Canada...
Luc

**Comment by MichaelOldham** [comment]
I think the concept was changed by Wheeler & Guagianone (2003) by raising the status of subsp. fuegina to species level.  I just mentioned the Saarela et al. (2013) paper as evidence that this concept was being followed by others.  Saarela et al. (2013) do recognize infraspecific taxa in their paper and have some excellent comments on the nomenclature and taxonomy of various species.
