### ISSUE TITLE
typos in synonyms of Crataegus macracantha

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2568]
Re: http://data.canadensys.net/vascan/taxon/8693?lang=en

The synonym Crataegus pareclara Sargent
should be spelled Crataegus praeclara Sargent

The final authority of this name: Mespilus macracantha (Loddiges ex Loudon) Wenz.ig 
should be Wenzig, without the period

**Comment by brouille** [comment]
typos corrected
L
