### ISSUE TITLE
Mertensia drummondii - NWT à ajouter dans la répartition canadienne

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2569]
Salut

Voici la carte de la répartition canadienne selon le NWT Species at Risk.
http://www.nwtspeciesatrisk.ca/sites/default/files/speciesmap_drummondblbell_2014.jpg

**Comment by brouille** [comment]
j'aurais préféré avoir accès au rapport et non à la seule carte, ou à la liste des spécimens d'herbier qui documentent les sites, pour pouvoir citer une source
ceci ne peut être cité

**Comment by manions** [comment]
Here are the specimens I know about.
DAO 689693 G.W. Scotter 1995, Horton River 69.4000 -126.8333
DAO 206739 (69.6833 -124.6500) & DAO 207014 (68.8167 -124.4167) G.W. Scotter & S. Zoltai 1978, near Horton River
Other DAO specimens are in NU

**Comment by brouille** [comment]
ajouté sur la base des spécimens à DAO
