### ISSUE TITLE
Scientific Authority for genus Lithospermum

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#257]
[Originally posted on GoogleCode (id 2492) on 2015-02-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/1359?lang=en

<b>What data are incorrect or missing?</b>
Currently listed: Lithospermum Luce

<b>What data are you expecting instead?</b>
Should be: Lithospermum Linnaeus

<b>If applicable, please provide an authoritative source.</b>
As per TROPICOS
http://www.tropicos.org/Name/40007843

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-25 21:22Z]

This is a mistyping that I do not quite fathom
L
