### ISSUE TITLE
Nymphaea loriana - nouvelle espèce décrite au Canada (Saskatchewan et Manitoba)

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2571]
Salut

Voici l'article mentionnant la description de cette nouvelle espèce
http://www.nrcresearchpress.com/doi/abs/10.1139/cjb-2014-0060#.VvbrO_nhDIU

http://www.ipni.org/ipni/idPlantNameSearch.do?id=77145364-1&back_page=%2Fipni%2FeditAdvPlantNameSearch.do%3Ffind_infragenus%3D%26find_isAPNIRecord%3Dtrue%26find_geoUnit%3D%26find_includePublicationAuthors%3Dtrue%26find_addedSince%3D%26find_family%3D%26find_genus%3DNymphaea%26find_sortByFamily%3Dtrue%26find_isGCIRecord%3Dtrue%26find_infrafamily%3D%26find_rankToReturn%3Dall%26find_publicationTitle%3D%26find_authorAbbrev%3D%26find_infraspecies%3D%26find_includeBasionymAuthors%3Dtrue%26find_modifiedSince%3D%26find_isIKRecord%3Dtrue%26find_species%3Dlor*%26output_format%3Dnormal

**Comment by brouille** [comment]
espèce ajoutée

**Comment by MFavreau** [comment]
Nom français ajouté. Il faut encore un nom anglais.

**Comment by brouille** [comment]
MArilyn
English vernacular lacking - see paper
Luc

**Comment by manions** [comment]
English vernacular added
