### ISSUE TITLE
Elodea nuttallii - ajout en Alberta

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2573]
Salut

Voici le commentaire que j'ai dans le fichier de Kershaw et al.
not in AB-VC; found in a cooling pond in 2001; presumed introduced. Unknown if species persisted. Specimens at UofA (acc#107842)

**Comment by brouille** [comment]
Ajouté comme introduite pour l'instant. Les spécimens étaient dans Canadensys
Luc
