### ISSUE TITLE
Juncus effusus subsp. effusus

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2576]
http://data.canadensys.net/vascan/taxon/25005?lang=en

This subsp. is native to Europe and entirely introduced in North America.

Delete for Ontario.  Newmaster & Ragupathy, 2005 report this only as a synonym of J. effuses var. solutus.  I know of no records of ssp. effuses for Ontario.

MIKE OLDHAM

**Comment by brouille** [comment]
Placing subsp. effusus as a synonym of var. solutus is grossly erroneous. Does FOIBIS mean to say by this that reports of effusus are solutus ?
I am removing the entry.

**Comment by MichaelOldham** [comment]
Hi Luc,

Yes, I suspect that FOIBIS means that Ontario report of subsp. effuses refer to var. solutus.  I wouldn’t trust “synonymy” in FOIBIS.

mike
