### ISSUE TITLE
Viola pedatifida var. pedatifida

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2578]
http://data.canadensys.net/vascan/taxon/9506?lang=en

It is stated in VASCAN that "Viola pedatifida G. Don var. pedatifida is an accepted variety name sensu FNA Ed. Comm., 2015.", however FNA Vol. 6 (2015) does recognize or mention infraspecific taxa in V. pedatifida.

MIKE OLDHAM

**Comment by brouille** [comment]
VASCAN had not been corrected completely from earlier data in vol. 6, apparently. I missed this one.
Variety removed.
Luc
