### ISSUE TITLE
incorrect synonym listed for Crataegus succulenta var. succulenta

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2579]
re: http://data.canadensys.net/vascan/taxon/8720

FNA lists Crataegus pisifera Sargent  as a synonym of C. succulenta var. pisifera, not var. succulenta.

If you want to add it, FNA does list Crataegus membranacea Sargent as another syn. of C. succulenta var. succulenta.

See FNA: http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242416356

**Comment by brouille** [comment]
This was an old entry that had not been cleaned. I am removing this name from synonymy. 

Added C. membranacea as syn
