### ISSUE TITLE
Add synonym Lotus micranthus to Acmispon parviflorus?

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#258]
[Originally posted on GoogleCode (id 2493) on 2015-02-20]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5777?lang=en

<b>What data are incorrect or missing?</b>
Synonym Lotus micranthus seems to fit with Acmispon parviflorus but it's not directly listed on TROPICOS. However basionym Hosackia parviflora is listed for both Lotus micranthus and Acmispon parviflorus on TROPICOS.

<b>What data are you expecting instead?</b>
Is there a chance to review this please and add Lotus micranthus as a synonym with Acmispon parviflorus? As Lotus micranthus is in use with a lot of Canadian databases and it would be great to have it referenced on VASCAN to place data with Acmispon parviflorus.

<b>If applicable, please provide an authoritative source.</b>
http://www.tropicos.org/Name/50325387
http://www.tropicos.org/Name/13022290

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-25 21:21Z]

Had it in my list of synonyms - I do not know why it was not added initially
Luc
