### ISSUE TITLE
new sp. of Nymphaea : vernaculars required

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2580]
@MFavreau 
A new species was described in 2014
[cjb-2014-0060.pdf](https://github.com/Canadensys/vascan-data/files/228623/cjb-2014-0060.pdf)
http://data.canadensys.net/vascan/taxon/29906 [not published yet]
Nymphaea loriana

French and English vernaculars are required.

Merci
Luc

**Comment by MFavreau** [comment]
French name added.
« It is named in honor of the late Lori Wittlake Wiersema
(1958–2013), the wife of the discoverer and a steadfast
supporter and principal inspiration for his water-lily research,
who also accompanied J.H. Wiersema and ... »

**Comment by manions** [comment]
English vernacular added
