### ISSUE TITLE
Re: status of Crataegus laurentiana - present in NL?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2581]
re: http://data.canadensys.net/vascan/taxon/9671?lang=en

FNA no longer lists this as a hybrid, although they mention in the text that it is of hybrid origin.  Also, they describe specimens from NL - see 2nd paragraph below

Hybrid origin for Crataegus laurentiana between a ser. Macracanthae species and C. chrysocarpa in the broad sense, or C. jonesiae, is supported by intermediacy and sympatry of the suspected parents. Chrysocarpoid characteristics include leaf shape and glandular petioles; macracanthoid traits include late anthesis, pink anthers, and variably eroded pyrene sides.

Specimens from Newfoundland and Quebec are var. laurentiana and are characterized by larger but proportionately narrow leaves, thicker and paler twigs, and pink, normal-sized (1 mm) anthers. They may be distinguished from the partly sympatric var. brunetiana by the smaller and proportionately broader leaves of the latter, and cream anthers, more like Crataegus chrysocarpa. In both forms, the leaves abaxially have conspicuously appressed-pilose veins. A Maine variant is atypically arborescent.
See: http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250100122

**Comment by brouille** [comment]
I maintain the taxon as a hybrid. I do not recognize the varieties. It appears to be a hybrid of multiple origins in various areas. Unfortunately, Phipps did things like this, not entirely coherent. I added Nfld in the distribution
LB
