### ISSUE TITLE
Cephalaria alpina (Linnaeus) Schrader

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2583]
Salut

The Plant List diffère au niveau des auteurs. (L.) Schrad. ex Roem. & Schult.
Tropicos, IPNI et The Plant List ne concordent pas....

Fred

**Comment by brouille** [comment]
Il semble que (Linnaeus) Schrader ex Roemer & Schultes soit correct
IPNI ajoute le "ex" en note
Plant List suit WCSP
INPN a cette autorité (ms accepte ce nom comme distinct de gigantea, plutôt que comme syn) - à revisiter
Je crois que TROPICOS est incomplet
Corrigé
Luc
