### ISSUE TITLE
Cephalaria alpina

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2584]
@MFavreau 
http://data.canadensys.net/vascan/taxon/15747

Cephalaria gigantea et C. alpina sont 2 spp. distinctes, dont seule la seconde est présente au Canada et an AN - Kartesz les avait mises en syn de façon erronée 

svp ajouter les vernaculaires EN et FR de alpina - j'ai effacé les vernaculaires de gigantea car non pertinents
Merci
Luc

**Comment by manions** [comment]
English vernaculars added. 
I couldn't find C. gigantea. Shouldn't it still be present and listed as 'excluded'?

**Comment by brouille** [comment]
C. gigantea: the name is still there but inaccessible. I do not know why. Must wait til our computer guy is back.
L

**Comment by brouille** [comment]
Cephalaria gigantea is accessible as I can see. Please add the vernaculars. They are not there.

**Comment by MFavreau** [comment]
Noms français ajoutés pour les deux espèces

**Comment by manions** [comment]
English vernaculars added
