### ISSUE TITLE
spelling of egglestonii in syns and common names

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2586]
Re: http://data.canadensys.net/vascan/name/Crataegus%20egglestonei
Crataegus scabrida var. egglestonii

The correct spelling of Eggleston is without the 'e' - see IPNI authors, which changes all of these entries:
    aubépine d'Egglestone - should be  aubépine d'Eggleston
    Egglestone's hawthorn - should be: Eggleston's hawthorn
    Crataegus brainerdii var. egglestonei (Sargent) B.L. Robinson - should be var. egglestonii
    Crataegus egglestonei Sargent - should be Crataegus egglestonii

See FNA, IPNI combinations and comments: Remarks: as" "C. egglestoni"; specific name honors: W. W. Eggleston

**Comment by MFavreau** [comment]
French name corrected.

Marc

**Comment by brouille** [comment]
English vernacular corrected
Latin names corrected
Luc
