### ISSUE TITLE
Additions to BC - vernaculars required

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2587]
@MFavreau 

Vernaculars are required for the following species added to BC:
Cornus sanguinea
Cotoneaster salicifolius (EN only)
Cotoneaster sternianus
Potentilla brunnescens
Potentilla ovina var. decurrens
Prunus lusitanica
Pseudosasa japonica

Most of these are published in FNA

Merci Luc

**Comment by manions** [comment]
English vernaculars, except Potentilla, finished. I'll work on all Potentilla vernaculars soon (including those listed above)

**Comment by manions** [comment]
Finished reviewing all the 'cinquefoils', including those above.

**Comment by brouille** [comment]
Marc

Je ne semble pas avoir pris le bon moyen pour cette issue. JE te la communique donc à nouveau.

Luc

**Comment by MFavreau** [comment]
Voilà, les noms français sont ajoutés ou vérifiés.
