### ISSUE TITLE
Authority correction for Sceptridium multifidum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2589]
Re: http://data.canadensys.net/vascan/taxon/12955

The authority is listed as (S.G. Gmelin) Nishida ex Tagawa
but it should be (S.G.Gmelin) M. Nishida ex Tagawa

There are several Nishada authors, the one with no initial died in 1927, well before the 1958 publication date.  See IPNI and IPNI authors.

**Comment by brouille** [comment]
Correction to initial

GCI does not have the ex : I have to query Dr. Gandhi since the other entry in IK and TROPICOS have the ex.
Luc

**Comment by brouille** [comment]
K. Gandhi also removed the ex author. Now fully corrected
Luc
