### ISSUE TITLE
Correction in authority of Betula xborggreveana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2590]
Re: http://data.canadensys.net/vascan/taxon/27145
Betula ×borggreveana Zabel ex H. Winkler
should be: Betula ×borggreveana Zabel ex H.J.P. Winkler

See IPNI and IPNI authors
Tropicos is wrong; there is no H.Winkler in IPNI authors.  Hubert [J.P.] Winker wrote the treatment in the Betulaceae treatment of Pflanzenreich (Engler).

**Comment by brouille** [comment]
corrected
