### ISSUE TITLE
Invalid synonym of Andersonglossum virginianum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2591]
re: http://data.canadensys.net/vascan/taxon/29172

Andersonglossum boreale (Fernald) J.I. Cohen is an invalid name; I've discussed this with Kanchi Gandhi and, since Cohen coined the new combination, but did not accept it as distinct from A. virginianum, it is an invalid number under ICBN Melbourne Code, Art. 36.1a.

Should be listed as Andersonglossum boreale (Fernald) J.I. Cohen, nom. inval.

**Comment by brouille** [comment]
Forgot to add nom. inval. when I entered the data. I knew it was not correct after communication with Kanchi myself.
Luc
