### ISSUE TITLE
Correction in authority of Conringia orientalis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2592]
re: http://data.canadensys.net/vascan/taxon/3975

Conringia orientalis (Linnaeus) Dumortier (1827)
should be: Conringia orientalis (Linnaeus) C.Presl

See: IPNI: Brassicaceae Conringia orientalis (L.) C.Presl Fl. Sicul. (Presl) 1: 79. 1826 [early-mid ? 1826]
IPNI Remarks: Publication usually cited as B.C.Dumortier in Florula Belgica (1827) 123, however the above is earlier. 
Tropicos also lists C.Presl as the authority rather than Dumortier.

**Comment by brouille** [comment]
I could not just change the authorities because they are used in FNA, unfortunately (which should have been caught). Thus I created a new name and transferred all information to it, and made the isonym (nom. illeg.) a synonym, as per IPNI, for instance
