### ISSUE TITLE
Status of C. capitata in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2593]
VASCAN has excluded C. capitata from NL, but in our NL checklist, I have this notation, based on info from you, Luc: Although the full range [of Carex capitata] in NL has not been confirmed, annotation of NL specimens in Québec herbaria by Dr. J. Cayouette indicate that both species are present in NL (L. Brouillet, pers. comm., June 28, 2016).  Carex capitata was reported from pool margins in limestone barrens along the Strait of Belle Isle, nwNfld. (Bouchard et al., 1991).]

**Comment by sjmeades** [comment]
That date should be probably be April; I'll check on that.

**Comment by sjmeades** [comment]
The date should be January 28, 2016.  I think an autocorrection of Jun. to June occurred, where it should have been Jan.

**Comment by brouille** [comment]
Following annotation by Jacques Cayouette, we have only specimens of capitata in Nfld., but only specimens of arctogena in Labrador. Obviously, only specimens at MT were seen.
I still have not properly corrected entries because it is obscure for other provinces.
Luc

**Comment by sjmeades** [comment]
Thanks for the update, Luc!  - Sue.
