### ISSUE TITLE
status of Carex x grantii in Labrador

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2594]
In our NL checklist, I have the following notation:

[Reported from Lab. (Gready Is., NL), Québec, and Ont. (Scoggan1978).]

Were these reports annotated to a different species?

**Comment by brouille** [comment]
Sue

I have no record of this taxon for Labrador in the MT database (it was therefore not in Rouleau's list of specimens). We have several specimens from QC and one from ON (9 in total).

However, Cayouette & Catling 1992, in their review of Carex hybrids in NA, rejectd NL reports as misidentified, which is the information currently provided in VASCAN. J. Cayouette may be able to tell you more, or his paper.

Luc

**Comment by brouille** [comment]
Sue

Labrador reports of this hybrid were rejected by Cayouette & Catling 1992, as stated in VASCAN. Please see the paper to determine how the specimen was disposed of.

Luc

**Comment by sjmeades** [comment]
Thanks, Luc.  I’ll update the NL list with this info.  – Sue
