### ISSUE TITLE
Status of Carex garberi in Lab.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2595]
In our NL checklist, I have this notation:
[There is one known specimen of Carex garberi from Porcupine Strand, NNW of Cartwright: TRTE, P. Ball (pers. comm. 1997); also, FNA shows one collection from wLab.]

Was this specimen annotated to a different species?

**Comment by brouille** [comment]
I have no knowledge of this record.
Who collected it? What herbarium is it in? No way to check with info provided

Luc

**Comment by sjmeades** [comment]
As listed in the annotation, the specimen is in TRTE. I’ve written to Peter Ball to see if he can provide further info.

[There is one known specimen of Carex garberi from Porcupine Strand, NNW of Cartwright: TRTE, P. Ball (pers. comm. 1997); also, FNA shows one collection from wLab.]

Sue.

**Comment by brouille** [comment]
added as native
