### ISSUE TITLE
Authority of Carex x limula

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2596]
VASCAN has Th.Fries as the author of this hybrid, but Elias M. Fries (Fr.) is the correct author.

See the IPNI entry and publication:
http://www.ipni.org/ipni/idPublicationSearch.do?id=5740-2&back_page=%2Fipni%2FeditAdvPublicationSearch.do%3Ffind_title%3D%26find_abbreviation%3DSumma%2Bveg.%2Bscand.%26output_format%3Dnormal

**Comment by brouille** [comment]
corrected
L
