### ISSUE TITLE
Authority of synonym of Carex macloviana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2597]
In VASCAN, the authority is listed as: Carex macloviana var. stricta (L.H. Bailey) Holm ex Kükenthal

it should be (L.H. Bailey) Kükenthal

See IPNI and page 196 of the original publication:
http://www.biodiversitylibrary.org/item/98637#page/2/mode/1up

**Comment by brouille** [comment]
Confirmed in WCSP
corrected
