### ISSUE TITLE
status of Carex x pseudohelvola in NL.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2598]
Cayouette & Catling give no specifics about the location of this hybrid from NL, but do cite Tiovonen (1980) who reports this about North American specimens:
"Outside northwestern Europe the hybrid has been identified with certainly only in eastern North America.  Fernald (1950) reports that it is scattered from Labrador to Maine. during the revision of the large herbarium material of the Carex canescens aggregate from North America Ihave seen only 3 hybrid collections (from New Brunswick and Quebec). Two of these were crosses between C. canescens var. disjuncta Fernald and C. mackenziei."

However, Fernald does not say Labrador, he says the se. Lab. Pen. to Me., which usually means the North Shore of Quebec, not Labrador.  Do you have any verified specimens of this hybrid or know of any from NL?

**Comment by brouille** [comment]
MT/NFM have 1 collection (2 specimens) of this nothotaxon from Shoal Point, Port au Port District, verified by G. Hall, collected by Charest and Djan-Chekar in 1999

I have no confirmed record from Labrador
