### ISSUE TITLE
typo in authority of Eleocharis quniqueflora

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2599]
re: Eleocharis quinqueflora (Hartman) O. Schwarz
http://data.canadensys.net/vascan/taxon/5254
authorities should be:  (Hartmann) O. Schwarz

See IPNI
You've got the correct spelling in the basionym, but the authority in the following 2 synonyms should also be corrected:
Eleocharis quinqueflora (Hartman) O. Schwarz subsp. quinqueflora
Eleocharis quinqueflora (Hartman) O. Schwarz var. quinqueflora

**Comment by brouille** [comment]
corrected
