### ISSUE TITLE
Décalage des sources des noms français

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#26]
[Originally posted on GoogleCode (id 1253) on 2012-03-29]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

<b>What data are incorrect or missing?</b>

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by FredCoursol** [comment]
[Originally posted on GoogleCode on 2012-03-29 14:34Z]

Les noms français dans la fiche Menyanthes trifoliata sont décalés d'une position.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-03-30 12:29Z]

Cela peut dépendre de l'affichage. Tout est correct sur mon écran.
