### ISSUE TITLE
Range of Juncus effusus subsp solutus not shown

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2601]
This species is described by Fernald (1950) as occuring from Fla. to eTexas, N to Nfld., Quebec, and Ont., and is the most common variety/subsp. of Juncus effusus.

Also, Hämet-Ahti (1980) shows a distribution map (Fig. 12) that shows the range of subsp. solutus from insular Nfld. sw to Texas, and west to sQue. and nON (Sault Ste. Marie area).

**Comment by brouille** [comment]
a revision of Juncus in VASCAN and MT database is ongoing - this has been corrected and will show at next publication
