### ISSUE TITLE
Corallorhiza maculata

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2602]
Salut

Addition à la flore du N.W.T.
J'ai seulement une photo qu'une biologiste a pris dans une tourbière minérotrophe.  J'ai demandé pour un spécimen d'herbier.  J'attends des nouvelles.  J'ai aussi demandé des photos pour déterminer la variété.

Fred

**Comment by brouille** [comment]
Fred

Une photo sans référence et coordonnées précises est peu fiable
Luc

**Comment by FredCoursol** [comment]
Oublie la mention. Reidentification hier à trifida par un spécialiste 

Envoyé de mon iPhone
