### ISSUE TITLE
Scutellaria parvula

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2603]
http://data.canadensys.net/vascan/taxon/6458?lang=en

Suggest recognizing var. parvula (ON, QC) and var. missouriensiis (ON, MB) for Canada.  Var. missouriensis is widely recognized by many recent authors (e.g. Flora Novae-Angliae, Michigan Field Manual) and is often called var. leonardii (recognized as a full species, S. leonardii by Gleason & Cronquist 1991 and in the last monograph of the North American members of the genus, Epling 1942). I don't think we've seen an FNA draft yet for this genus.

In Ontario the two have different morphology, habitat, and distribution.  Var. parvula is widespread in southern and central Ontario, mainly on alvars; var. missouriensis is rare in the province primarily in northwestern Ontario on open granitic outcrops and slopes, often with prairie species.  VASCAN maps S. parvula also from Manitoba where presumably only var. missouriensis occurs (S. leonardii first reported from Manitoba by Looman (1969) in Canadian Field-Naturalist 83(4): 392-393).  Goodman & Lawson (1992; Rhodora 94(880): 381-382) clarified that var. missouriensis has priority over var. leonardii. Scoggan (1978-1979) includes var. leonardii in var. parvula.  Epling in his 1942 monograph does not map S. leonardii from Canada and Boivin (1966-1967) recognizes only S. parvula var. parvula from Canada.

Mike Oldham

**Comment by brouille** [comment]
M ike

This issue has already been submitted. Please do not submit issues twice or thrice (as happened once). It complicates matters. Some issues are not dealt with immediately because I am waiting for the FNA ms to see more clearly.

Thanks
Luc

**Comment by brouille** [comment]
Varieties added based on ITIS, which was reviewed in 2010 by FNA authors. THus likely to be the adopted taxonomy. Differs from POWO in leonardi not accepted
FNA ms still pending, however.
Luc

**Comment by brouille** [comment]
Marilyn and Marc

please provide vernaculars for the varieties of S. parvula
Thanks
Luc

**Comment by MFavreau** [comment]
French vernacular added.

Easy one, Marilyn.

Marc

**Comment by manions** [comment]
English vernaculars added.
