### ISSUE TITLE
Ranunculus codyanus B.Boivin

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2605]
Salut
Deux noms que l'on ne retrouve pas dans VASCAN.
Ranunculus codyanus B.Boivin  Canad. Field-Naturalist 65: 3. 1951
Ranunculus aquatilis L. var. codyanus (B.Boivin) B.Boivin Phytologia 16: 252. 1968

**Comment by brouille** [comment]
placés en syn de R. aquatilis var. diffusus en attendant une résolution de aquatilis vs trichophyllus
