### ISSUE TITLE
Lonicera ruprechtiana

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2606]
@MFavreau 
taxon/30139
Added to QC and Canada

vernacular names required
Thanks
Luc

**Comment by MFavreau** [comment]
French name added.
Marilyn : the English name " Manchurian honeysuckle" is provided by Termium, with the following source :
Trees and shrubs of the Dominion Arboretum / A. R. Buckley. Ottawa : Research Branch, Agriculture Canada, 1980. You could also use "Termium, 2009+" as a source, if the original source is hard to check.

Marc

**Comment by manions** [comment]
English vernacular added
thanks
