### ISSUE TITLE
Draba bruce-bennettii : vernaculars required

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2607]
A new,-Yukon endemic species was described and added to VASCAN recently (see attached paper, if it shows) [no 30157]
New vernacular names are required in French and English.

Thanks
Luc

[Al-shehbaz_2016_Draba_bruce_bennettii_new_species.pdf](https://github.com/Canadensys/vascan-data/files/485673/Al-shehbaz_2016_Draba_bruce_bennettii_new_species.pdf)

**Comment by brouille** [comment]
Bruce Bennett: We are using the common name Klaza Draba after the region of Yukon where it has been found.

**Comment by MFavreau** [comment]
French name added, translated from Dr. Bennett's English name proposal, since another Draba is already named after him.

Marc
