### ISSUE TITLE
Saxifraga rivularis subsp. arctolitoralis au Québec/Labrador?

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#2608]
Marcel Blondeau nous a envoyé une carte de répartition qui indiquerait la présence de cette variété au Québec/Labrador (v. p.j. et courriel copié plus bas).  La base de données de MT contient plusieurs spécimens annotés par Marcel en 2009 qui appuient cette affirmation (v. tableau joint).  Doit-on considérer que le taxon est donc présent dans les deux juridictions?

Geoff

---

from:   Marcel Blondeau marcel_blondeau@videotron.ca
to: Geoffrey Hall geoffrey.hall@umontreal.ca
date:   Mon, Oct 3, 2016 at 9:48 AM
subject:    carte Sassifraga rivularis arctolitoralis

Cher Geoffrey,

Je t’inclus une carte de répartition de Saxifrage rivularis subsp. arctolitoralis 
réalisée par Kristine Westergaard: je lui ai fourni les données pour le Québec et l’île de Baffin.
Bonne journée. Des saluts à Luc.

---

![atlantic arctolitoralis](https://cloud.githubusercontent.com/assets/11761405/19119186/f9579410-8aec-11e6-9051-ab5a322a0f50.jpg)
[Saxifraga rivularis subsp. arctolitoralis_MT_22se2016.pdf](https://github.com/Canadensys/vascan-data/files/511538/Saxifraga.rivularis.subsp.arctolitoralis_MT_22se2016.pdf)

**Comment by brouille** [comment]
QC et LAbrador ajoutés, source: MT

Luc
