### ISSUE TITLE
Chenopodium nitens in Yukon

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2609]
@MFavreau 
http://data.canadensys.net/vascan/taxon/30171

Chenopoium nitens is a new species, reported from Yukon

Vernacular names are required. I did not find any suggested in the publication (hopefully) attached.

Luc

[BenetPierce_Simpson_2014_The taxonomy of Chenopodium desiccatum and C nitens_JTBS.pdf](https://github.com/Canadensys/vascan-data/files/514642/BenetPierce_Simpson_2014_The.taxonomy.of.Chenopodium.desiccatum.and.C.nitens_JTBS.pdf)

**Comment by MFavreau** [comment]
French name added.

Actually, there is a "suggested common name" in the publication (p. 170): Shiny-Seed Goosefoot.

nitens means shiny.

Marc

**Comment by manions** [comment]
English vernacular added
