### ISSUE TITLE
Arctium x nothum parents

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2610]
http://data.canadensys.net/vascan/taxon/2851?lang=en

Arctium x nothum is considered to be an A. lappa X A. tomentosum hybrid based on FNA Vol. 19, however FNA makes no mention of this hybrid and other authors consider it a hybrid between A. lappa and A. minus (e.g. Moore & Frankton 1974, Morton and Venn 1990).

Mike Oldham

**Comment by brouille** [comment]
This may be, but the following provide the same parent combination  as VASCAN:
https://data.nbn.org.uk/Taxa/NBNSYS0000161419
https://www.ispotnature.org/species-dictionaries/uksi/Arctium%20lappa%20x%20minus%20%3D%20A.%20x%20nothum

So who should I believe?
Luc

**Comment by brouille** [comment]
I removed the ref. however. Must confirm parentage and find source.
Luc

**Comment by brouille** [comment]
Finally, I misread : nothum is a combination with minus, not tomentosum - corrected in VASCAN
Luc
