### ISSUE TITLE
Erodium moschatum   (Linnaeus) L’Héritier ex Aiton

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2611]
Selon FNAms, il nous manque le "ex Aiton" dans VASCAN

**Comment by brouille** [comment]
Je ne vais pas faire ce changement car c'est sans aucun doute erroné:

K. Gandhi concernant Erodium
"As in the case of Pelargonium, L’Héritier alone is the author for the genus name Erodium.
As you may or may not know, Aiton did not write the 3 volume work Hort. Kew.; but his colleagues Dryander and Solander wrote them; Aiton did not even thank them or mention their names anywhere.
However, Aiton made an exception to Linnaeus f. and L’Héritier; Aiton (Hort. Kew. 1: preface vi, paragraph 3. 1789) mentioned the following (quoted): 
http://www.biodiversitylibrary.org/item/201545#page/12/mode/1up
"References are frequently made to the works of  M. L’Heritier, under Plants of which he has not yet published either descriptions or figures; these are taken from communications this gentleman frequently made, during the course of printing, of every thing he had prepared for the press …”
Therefore, L’Héritier is the author of this genus name and the species names wherever his name is cited. "

Luc
