### ISSUE TITLE
Erodium cicutarium subsp. bipinnatum (Desfontaines) Tourlet - autorité à corriger

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2612]
Salut

VASCAN a actuellement E. cicutarium subsp. bipinnatum (Cavanilles) Tourlet alors que l'autorité devrait être subsp. bipinnatum (Desfontaines) Tourlet selon IPNI et FNAms.

**Comment by brouille** [comment]
corrigé
