### ISSUE TITLE
Elatine triandra

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2613]
http://data.canadensys.net/vascan/taxon/15821?lang=en

Considered introduced to North America by Rosman, A.J., H. Razifard, G.C. Tucker, and D.H. Les. 2016. New records of Elatine ambigua (Elatinaceae), a nonindigenous North American species. Rhodora 118(974): 235-242.

MIKE OLDHAM

**Comment by brouille** [comment]
Correction made following FNA 12 publication
Tx
Luc
