### ISSUE TITLE
http://data.canadensys.net/vascan/about

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2615]
When you click on ITIS Canada on this page you get an error message.

This problem communicated to me by Anne Barbour.

MIKE OLDHAM

**Comment by JeGoi** [comment]
Thanks, it will be fixed on the next update.
Regards.

**Comment by brouille** [comment]
Cela a-t-il été corrigé?
Luc

**Comment by JeGoi** [comment]
No. Vascan is not yet upgraded.
Thks for the update.

**Comment by JeGoi** [comment]
Fixed in dev vascan branch.
