### ISSUE TITLE
status of Euphorbia serpyllifolia in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2616]
http://data.canadensys.net/vascan/taxon/5597?lang=en

CHANGE status of Euphorbia serpyllifolia in Ontario from introduced to native.

Although considered introduced in Ontario by NHIC previously (based on Morton and Venn 1990), the presence of populations in high quality natural habitat in the southern part of NW Ontario, adjacent to its native range from Manitoba westward, suggests that some populations in this part of Ontario are native.  From NHIC database:  "rare but widespread weed in dry, open, disturbed ground in southern Ontario where presumably introduced from further west. More common in northwestern Ontario (Rainy River and southern Kenora Districts) where it is likely native and near the eastern limit of its native range, occurring on moist sandy shores, dry open rock barrens and Bur Oak openings (as well as disturbed habitats such as along railways).  Status of native populations in Ontario are poorly known, since in the past it has been considered an introduced species (e.g. Morton and Venn 1990), though there are at least seven Ontario collections from high quality natural habitat in the Lake of the Woods and Rainy River areas (CAN, DAO, MICH, NHIC, TRTE). ".

This comment applies to ssp. serpyllifolia also.

MIKE OLDHAM

**Comment by brouille** [comment]
status changed
note that spelling is serpillifolia
Luc
