### ISSUE TITLE
Thesium ramosum replaces T. arvense

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2617]
@MFavreau 

http://data.canadensys.net/vascan/taxon/27199

Following FNA 12, it is necessary to place T. arvense in syn. (as a nom. illeg. superfl.) of T. ramosum
Marc had assigned English and French vernaculars to arvense. Please consider what to do with the name change - given the name was a creation. 
MArylin please confirm the EN vernacular provided. There may be one from Europe.

Luc

**Comment by brouille** [comment]
nouvelle page: http://data.canadensys.net/vascan/taxon/30188 (non visible encore)

**Comment by MFavreau** [comment]
The French name we proposed earlier is now used by several organizations. Since it remains unambiguous, I believe it would be counterproductive to change it.

**Comment by manions** [comment]
English vernacular review completed
