### ISSUE TITLE
Arceuthobium campylopodum subspecies added

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2618]
@MFavreau 

Two subspecies were added to http://data.canadensys.net/vascan/taxon/6571

subsp. laricis (A. laricis in Klinkenberg)
subsp. tsugense (A. tsugense in Klinkengerg)

Vernacular names are required for the infrapsecies. English names exist for the sp. in Klinkengerg

Luc

**Comment by MFavreau** [comment]
Noms français ajoutés.

**Comment by manions** [comment]
English vernaculars added
