### ISSUE TITLE
Cronus sericea vs stolonifera

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2619]

**Comment by brouille** [comment]
@MFavreau 

http://data.canadensys.net/vascan/taxon/4651 C. stolonifera definitely becomes C. sericea http://data.canadensys.net/vascan/taxon/30197

Please verify that the vernaculars provided still apply under this new name, particularly accepted names

Luc

**Comment by brouille** [comment]
@MFavreau 
il manque le vernaculaire FR à Cornus occidentalis
http://data.canadensys.net/vascan/taxon/28175
Luc

**Comment by MFavreau** [comment]
Puisque le nom C. stolonifera semble irrémédiablement relégué en synonymie, j'ai choisi d'en faire autant pour son calque français cornouiller stolonifère, même s'il est utilisé depuis Marie-Victorin, et d'élever au rang de « nom accepté » le nom français qu'avait très opportunément proposé Gisèle Lamoureux dans la dernière mouture de sa Flore printanière : cornouiller hart-rouge.
Le nom populaire hart rouge est recensé au moins au Québec (Provancher le mentionne déjà), au Manitoba (dans le roman Rivière Rouge) et en Saskatchewan (nom d'un groupe musical local), ce qui en fait un nom essentiellement pancanadien.

Noms français ajoutés pour le C. occidentalis.

Marc

**Comment by manions** [comment]
English vernacular review completed
