### ISSUE TITLE
fétuque rouge traçante

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2621]
Salut

On m'a demandé de lier ce nom français à un nom latin.  La "fétuque rouge traçante" serait un nom français à ajouter dans VASCAN.  On l'a utilisé dans la littérature du gouvernement fédéral comme par exemple dans ce document.  http://publications.gc.ca/collections/collection_2014/aac-aafc/agrhist/A53-1122-1980-fra.pdf
Je n'ai pas réussi à trouver le var genuina ou la ssp. genuina dans les bases de données courantes comme TROPICOS, IPNI, mais on la trouve comme nom invalide dans Catalogue of New World Grasses sous  Festuca rubra var. genuina Hack. 
Malheureusement, pour le nom latin, le mieux que j'ai trouvé pour cette espèce provenant de Tchécoslovaquie: Festuca rubra ssp. rubra var. genuina.

Fred

**Comment by MFavreau** [comment]
Le nom « fétuque rouge traçante » est donnée dans FNA24 et dans Termium comme nom français propre à la sous-espèce rubra.

Cependant, j'ai l'impression que la fétuque rouge traçante est un ensemble de variétés cultivées généralement placées dans cette sous-espèce, et qu'il ne s'agit pas nécessairement de la sous-espèce dans son ensemble.

Il existe également des variétés semi-traçantes (généralement rapportées à la subsp. litoralis) et des variétés gazonnantes (généralement rapportées à la subsp. commutata) 

Je vais tout de même ajouter ce nom français pour la sous-espèce, puisqu'il figure dans FNA.

**Comment by brouille** [comment]
ajouté var. genuina Hackel nom. inval. à subsp. rubra
Luc
