### ISSUE TITLE
Linum lewisii var. lewisii - do not add for ON based on FNA

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2622]
http://data.canadensys.net/vascan/taxon/17115?lang=en

VASCAN currently does not list Linum lewisii var. lewisii from ON or QC, though FNA Vol. 12 lists it for both, based on Becker (2010).  NHIC did not have this var. listed for ON and I contacted Bruce Ford to ask for a copy of Becker (2010), an unpublished Univ. of Manitoba Honours B.Sc. thesis.   Bruce sent me a copy of the thesis, however in the document there is no mention of L. lewisii var. lewisii from ON.  There is mention of its occurrence in Quebec "Specimens received from DAO indicated a presence of L. lewisii var. lewisii around the metropolitan areas of Quebec; however, these individuals likely have an anthropogenic origin".

MIKE OLDHAM

**Comment by brouille** [comment]
Mike

Thanks for the update. I cannot currently correct distribution data in the VASCAN editor due to a database problem- will be done as soon as problem corrected - obviously, data will appear modified at next publication (delayed due to IT issue)
Luc

**Comment by MichaelOldham** [comment]
Thanks Luc,

If it is possible to let me know when VASCAN is next updated, that would be helpful.  I hope to have a new Ontario NHIC vascular plant list ready within a month or two and would like to do a final comparison with VASCAN if there is time.

Cheers,

mike

P.S.  In case you haven't seen it, the attached paper describes a new species of Chenopodium, C. nitens (not currently in VASCAN), and reports it from the Yukon.

---

Michael J. Oldham
Ontario Natural Heritage Information Centre (NHIC)
Ministry of Natural Resources
300 Water Street, 2nd Floor, North Tower
P.O. Box 7000 Peterborough, Ontario K9J 8M5, Canada
phone 705-755-2160[X]; fax 705-755-2168[X]
michael.oldham@ontario.camailto:michael.oldham@ontario.ca
NHIC requests: NHICrequests@ontario.camailto:NHICrequests@ontario.ca
NHIC web page: http://nhic.mnr.gov.on.ca/nhic_.cfmhttps://webmail.ontario.ca/owa/redir.aspx?C=oYt4O5oPNUOsn1H3HmanID5fehjWsNAINC47ZwVJniyQjRw8C6vFRPVyWJ9nVJLyVpgnNwrFZYs.&URL=http%3a%2f%2fnhic.mnr.gov.on.ca%2fnhic_.cfm
Ontario Reptile & Amphibian Atlas:
http://www.ontarionature.org/protect/species/herpetofaunal_atlas.phphttps://webmail.ontario.ca/owa/redir.aspx?C=oYt4O5oPNUOsn1H3HmanID5fehjWsNAINC47ZwVJniyQjRw8C6vFRPVyWJ9nVJLyVpgnNwrFZYs.&URL=http%3a%2f%2fwww.ontarionature.org%2fprotect%2fspecies%2fherpetofaunal_atlas.php

**Comment by brouille** [comment]
Mike
An update was done in late December
Luc

**Comment by brouille** [comment]
Taxon excluded as not documented for Ontario. Could you provide me the full citation of Becker's thesis? I do not need a copy, just the reference.

For Québec, is the specimen date provided? I believe it is probably ephemeral or even excluded as old/ephemeral.

Luc
