### ISSUE TITLE
Archangelica norwegica Rupr.

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2623]
Salut

Dans le taxon suivant Angelica archangelica subsp. norvegica (Ruprecht) Nordhagen, il faut corriger norvegica afin de substituer le v pour un w.
Il faut aussi ajouter le basyonyme.

Finalement, le taxon est maintenant considéré comme un synonyme de la subsp. archangelica.

Fred

**Comment by brouille** [comment]
corrigé et synonymes ajoutés
