### ISSUE TITLE
Botrychium acuminatum included in B. matricariifolium

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2625]
http://data.canadensys.net/vascan/taxon/3844?lang=en

Attached paper suggests that B. acuminatum should be included in B. matricariifolium

Mike Oldham

[Williams et al 2016_Cryptic speciation in allotetraploids, Lessons from the Botrychium matricariifolium complex.pdf](https://github.com/Canadensys/vascan-data/files/629824/Williams.et.al.2016_Cryptic.speciation.in.allotetraploids.Lessons.from.the.Botrychium.matricariifolium.complex.pdf)

**Comment by brouille** [comment]
Following this paper, acuminatum put in synonymy of matricariifolium
