### ISSUE TITLE
Flueggea suffruticosa

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2626]
http://data.canadensys.net/vascan/taxon/30288

Nouvelle espèce pour le Québec et le Canada (introduite, échappée de culture)
Flueggea suffruticosa

vernaculaires anglais et français

Merci
Luc

**Comment by MFavreau** [comment]
Noms français ajoutés. Il y avait un nom français recensé dans Termium (securinega sous-frutescent), mais ce nom ne convient plus, car le genre _Flueggea_ est maintenant considéré comme peu apparenté au genre _Securinega_; de plus, l'espèce n'est pas sous-frutescente, mais carrément arbustive comme la plupart des autres espèces du genre. J'ai utilisé la révision de Webster (1984) - http://herbarium.ucdavis.edu/publications/webster/70.Allertonia%201984%20pp.%20259-312.pdf

**Comment by manions** [comment]
English names added
