### ISSUE TITLE
A revised classification of Anemone s.l., in which Clematis is nested

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2627]
This paper proposes a revised classification of Anemone s.l. and includes new combinations in the resurrected genus Anemonastrum Holub for taxa currently recognized (in VASCAN) as Anemone canadensis, A. richardsonii; the correct name for A. patens in Pulsatilla; as well as recognition of other genera currently included in Anemone s.l. (and possibly other relevant combinations, if the taxa are in Canada):

Mosyakin SL. 2016. Nomenclatural notes on North American taxa of Anemonastrum and Pulsatilla (Ranunculaceae), with comments on the circumscription of Anemone and related genera. Phytoneuron 2016-79:1-12. 

Quick summary of the main issue:
Recent authors have recognized Anemone s.l., which is consistent with molecular data (e.g.,Hoot SB, Meyer KM, and Manning JC. 2012. Phylogeny and reclassification of Anemone (Ranunculaceae), with an emphasis on austral species. Systematic Botany 37:139–152. 10.1600/036364412X616729).

However, recent work shows that Clematis is nested within Anemone s.l. - which means recognition of Anemone s.l. would necessitate many new combinations for the species of Clematis. This was apparently not known previously b/c earlier molecular studies of Anemone s.l. used Clematis as an outgroup, when in fact it is part of the outrgroup.  

Lehtonen S, Christenhusz MJM, and Falck D. 2016. Sensitive phylogenetics of Clematis and its position in Ranunculaceae. Botanical Journal of the Linnean Society 182:825-867. 10.1111/boj.12477

Mosyakin (2016) argues that recognition of multiple smaller genera rather than Anemone s.l. is a better approach (particularly given the placement of Clematis). Perhaps this is not the last word on this, but it sounds reasonable. Whatever approach is accepted for VASCAN, the new combinations should be included in the database. 

Jeff Saarela

**Comment by brouille** [comment]
Jeff
Anemone taxonomy was adjusted to take into account Mosyakin 2016 (and supporting papers): Pulsatilla, Hepatica, Anemonastrum and Anemone recognized for Canada.
Data will be published at next update, probably end of Jan given numerous significant changes in taxonomy

Luc

**Comment by brouille** [comment]
MArc and Marilyn:

As suggested by Jeff Saarela above, I changed the taxonomy within tribe Anemoneae to follow recent phylogenies and the taxonomy suggested by Mosyakin 2016.

Please review names in the following genera: Hepatica (reinstated from Anemone), Pulsatilla (ditto), Anemonastrum (a few species of Anemone). Species of Anemone do not need revision. It is most likely that the vernaculars do not need to change.

Luc

**Comment by MFavreau** [comment]
Effectively, the French name are still in accordance with the reborn genera.

I only changed the French name for Anemonastrum sibiricum, because it was based on a different epithet and had never really come into usage.

**Comment by manions** [comment]
I reviewed all the species within the suggested and new genera. English vernaculars unchanged as are suitable and in use.
