### ISSUE TITLE
Two new combinations in Bromus

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2628]
Please add these to the database, from:
Brainerd RE, Otting N, and Wilson BL. 2016. New combinations in Bromus sitchensis (Poaceae). Phytoneuron 2016-36:1-4. 

**Bromus sitchensis Trin. var. carinatus (Hook. & Arn.) R.E. Brainerd & Otting**, comb. nov. Basionym: Bromus carinatus Hook. & Arn., Bot. Beechey Voy. 403. 1841 [1840].

**Bromus sitchensis Trin. var. polyanthus (Scribn. ex Shear) R.E. Brainerd & Otting**, comb. nov. Basionym:  Bromus polyanthus Scribn. ex Shear, Bull. Div. Agrostol., U.S.D.A. 23: 56. 1900.

The taxonomic treatment proposed in this paper is certainly defensible (recognizing the Bromus carinatus complex as a single species, for which the correct name is B. sitchensis s.l.). Or they can be listed as synonyms of the currently accepted names in VASCAN.

Jeff Saarela

**Comment by brouille** [comment]
All taxa now var. of sitchensis in Canada have been transferred to sitchensis
It would be good to validate the presence in BC of all the vars., mostly as reported by FNA 2007

Luc
