### ISSUE TITLE
Bromus latiglumis in Alberta

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2630]
This taxon currently is recorded as "excluded" from Alberta, citing "Saarela 2009" personal communication. http://data.canadensys.net/vascan/taxon/7466?lang=en

Please see: Saarela JM. 2009. Taxonomy of Bromus sections Bromus, Bromopsis and Genea (Poaceae) in British Columbia: a summary, a key, new records, specimen citations, and miscellaneous notes. Botanical Electronic News 415. http://bomi.ou.edu/ben/ben415.html

I noted there that specimens from southwestern Alberta determined as B. latiglumis were misidentified, but specimens mapped in FNA from more northerly parkland sites are likely correct (at least nobody has suggested otherwise to my knowledge).

Please record the taxon as native in Alberta.

Thanks,
Jeff Saarela

**Comment by brouille** [comment]
correction made
Luc
