### ISSUE TITLE
Bromus riparius recorded for Alberta, Saskatchewan and Manitoba

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2631]
http://data.canadensys.net/vascan/taxon/28785?lang=en

Please see pages 352-355 in: Saarela JM. 2008. Taxonomy of Bromus (Poaceae: Pooideae: Bromeae) sections Bromopsis, Bromus, and Genea in British Columbia, Canada. Journal of the Botanical Research Institute of Texas 2:323–372.

Records from Manitoba and Alberta are cited there, and the text indicates the taxon is recorded for Saskatchewan by Harms (2006), as well as BC, which is already recorded in VASCAN. 

Jeff Saarela

**Comment by brouille** [comment]
added
Luc
