### ISSUE TITLE
Bromus lanceolatus - ephemeral in BC

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2632]
http://data.canadensys.net/vascan/taxon/7465?lang=en

Please see comments on a collection of this taxon from BC in:
Saarela JM. 2009. Taxonomy of Bromus sections Bromus, Bromopsis and Genea (Poaceae) in British Columbia: a summary, a key, new records, specimen citations, and miscellaneous notes. Botanical Electronic News 415. 

Jeff Saarela

**Comment by brouille** [comment]
added as ephemeral
Luc
