### ISSUE TITLE
Correct author of Bromus pubescens...

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2633]
is Spreng.  (1807) -- according to: 
Veldkamp JF. 2009. The authorship of Bromus pubescens (Gramineae). The Journal of the Torrey Botanical Society 136:137–138. doi:10.3159/08-RA-069R.1

Bromus pubescens Muhl. ex Willd. (1809) is therefore an isonym of the earlier combination. 

IPNI has this correct but there are errors in Tropicos at the moment (I alerted the powers that be there to fix this). 

http://data.canadensys.net/vascan/taxon/7473?lang=en.

Jeff Saarela

**Comment by brouille** [comment]
I probably based the interversion on TROPICOS. Should have checked more sources. Correction done.

**Comment by jmsaarela** [comment]
Thanks Luc. Tropicos was in error about this until a few days ago. Rob Soreng has since corrected the info there, as of a few days ago.

Jeff
From: brouille
Sent: Tuesday, December 20, 2016 3:58 PM
To: Canadensys/vascan-data
Reply To: Canadensys/vascan-data
Cc: Jeff Saarela; Author
Subject: Re: [Canadensys/vascan-data] Correct author of Bromus pubescens... (#2633)



I probably based the interversion on TROPICOS. Should have checked more sources. Correction done.
