### ISSUE TITLE
Five new records for Nunavut (two not yet recorded in VASCN, 3 recorded with incorrect ref)

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2634]
First records for Nunavut of the following three taxa are reported in this paper: 
Gillespie LJ, Saarela JM, Sokoloff PC, and Bull RD. 2015. New vascular plant records for the Canadian Arctic Archipelago. Phytokeys 52:23–79. 10.3897/phytokeys.52.8721

The current VASCAN records indicate something else and should be updated.

http://data.canadensys.net/vascan/taxon/8390?lang=en
http://data.canadensys.net/vascan/taxon/4247?lang=en
http://data.canadensys.net/vascan/taxon/9879?lang=en

Saxifraga escholtzii newly reported for nunavut in the same publication
http://data.canadensys.net/vascan/name/Saxifraga%20eschscholtzii

Utricularia ochroleuca newly reported for Nunavut in the same publication
http://data.canadensys.net/vascan/taxon/6512?lang=en

**Comment by brouille** [comment]
Jeff:

The three taxa you ask to update are all reported in Nunavut in VASCAN already. What needs to be updated for these?

Nunavut added for the two species mentioned.

Luc

**Comment by jmsaarela** [comment]
Luc, what I meant was, the references given for presence of these three taxa in Nunavut are incorrect. They should be corrected as follows:

http://data.canadensys.net/vascan/taxon/8390?lang=en
-Saarela et al. 2013 is given but the taxon not reported there for Nunavut. This was first reported for Nunavut in Gillespie et al. 2015

http://data.canadensys.net/vascan/taxon/4247?lang=en
-CAN is currently given as source for Nunavut. That is technically correct, but this was first reported in the literature in Gillespie et al. 2015, which would be a better source.

http://data.canadensys.net/vascan/taxon/9879?lang=en
-Consaul et al. 2008 is given as a source for Nunavut. No Nunavut records for the taxon reported in that paper. First records for Nunavut reported in Gillespie et al. 2015
-also, CAN is reported as source for NWT. Would be better to cite Consaul et al. 2008 for NWT.

Jeff

**Comment by brouille** [comment]
Thanks
Corrections to reports made
Luc
