### ISSUE TITLE
Spartina ×townsendii and S. densiflora recorded for British Columbia

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2635]
Please see: Saarela JM. 2012. Taxonomic synopsis of invasive and native Spartina (Poaceae: Chloridoideae) in the Pacific Northwest (British Columbia, Washington and Oregon), including the first report of Spartina ×townsendii for British Columbia, Canada. Phytokeys 10:25–82. doi: 10.3897/phytokeys.10.2734

Neither of these taxa currently treated in VASCAN.

Thanks
Jeff

**Comment by brouille** [comment]
These were added as Sporobolus given issue 2636 and ref therein
Source for distribution provided is Klinkenberg, given the source cites your paper above ; your source added in note (not visible but available to editors)
Luc
