### ISSUE TITLE
Species of Spartina have been transferred to Sporobolus

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2636]
All the new combinations are in: 
Peterson PM, Romaschenko K, Arrieta YH, and Saarela JM. 2014. A molecular phylogeny and new subgeneric classification of Sporobolus (Poaceae: Chloridoideae: Sporobolinae). Taxon 63:1212–1243. 10.12705/636.19

This proposal to conserve Sporobolus against several older names was approved by the relevant nomenclatural committee of the IAPT:
Peterson PM, Romaschenko K, Arrieta YH, and Saarela JM. 2014. (2332) Proposal to conserve the name Sporobolus against Spartina, Crypsis, Ponceletia, and Heleochloa (Poaceae: Chloridoideae: Sporobolinae). Taxon 63:1373–1374. 10.12705/636.23

If the revised circumscription of Sporobolus is not adopted in VASCAN (i.e. if one prefers to recognize non monophyletic genera), the new names should at least be included as synonyms. 

Thanks,
Jeff

**Comment by brouille** [comment]
This is more than I can do before the publication of VASCAN tomorrow. Will be done soon after and appear at next publication.
Luc

**Comment by brouille** [comment]
All transfers have been done, checking for later corrections in names.

Luc
