### ISSUE TITLE
Calamovilfa and Crypsis also transferred to Sporbolus

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2637]
All the new combinations are in:
Peterson PM, Romaschenko K, Arrieta YH, and Saarela JM. 2014. A molecular phylogeny and new subgeneric classification of Sporobolus (Poaceae: Chloridoideae: Sporobolinae). Taxon 63:1212–1243. 10.12705/636.19

Sorry...forgot to include those two names in my previous post.

Thanks,
Jeff

**Comment by brouille** [comment]
Done also
Luc
