### ISSUE TITLE
Revised subgeneric classification of Bouteloua

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2638]
This new subgeneric classification, based on a comprehensive phylogeny, differs from what is currently in VASCAN. The classification only recognizes sections: 

Peterson PM, Romaschenko K, and Arrieta YH. 2015. Phylogeny and subgeneric classification of Bouteloua with a new species, B. herrera-arrietae (Poaceae: Chloridoideae: Cynodonteae: Boutelouinae). Journal of Systematics and Evolution 53:351–366. 10.1111/jse.12159

Bouteloua dactyloides now placed in B. sect. Buchloe (Engelm.) P.M. Peterson, Romasch. & Y. Herrera, 

Bouteloua curtipendula placed in B. sect. Bouteloua.

Bouteloua hirsuta placed in B. sect. Hirsuta P.M. Peterson, Romasch. & Y. Herrera subsect. hirsuta

Bouteloua gracilis now place din B. sect. Chondrosum (Desv.) Benth. & Hook

Thanks,
Jeff

**Comment by brouille** [comment]
Will take care of this after next VASCAN publication tomorrow.
Luc

**Comment by brouille** [comment]
Note that sect. Hirsuta must be corrected to Hirsutae - see TROPICOS

Changes made - I did not include the subsection Hirsutae, however, as there was only a single species of the section in the flora.

Luc
