### ISSUE TITLE
The rice subfamily is back to being called Oryzoideae Kunth ex Beilschm.

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2639]
..after a period of time being referred to as Ehrhartoideae Link.

http://data.canadensys.net/vascan/taxon/352

Details in: 
Soreng RJ, Peterson PM, Romaschenko K, Davidse G, Zuloaga FO, Judziewicz EJ, Filgueiras TS, Davis JI, and Morrone O. 2015. A worldwide phylogenetic classification of the Poaceae (Gramineae). Journal of Systematics and Evolution 53:117–137. 10.1111/jse.12150

The broader grass community has quickly reverted back to using the name Oryzoideae for the clade, and I suspect this is now stable. I hope so, b/c Ehrhartoideae is always a pain to spell.

Also, correct authority for Ehrhartoideae is Jacq.-Fél. ex Caro, not Link (details at Tropicos and in same paper)

Jeff

**Comment by brouille** [comment]
I will do this change after the VASCAN publication. There are several complications here.

Luc

**Comment by brouille** [comment]
Change made from Ehrhartoideae to Oryzoideae
Unfortunately, there is no mechanism to keep synonyms at higher ranks (might come later) and the name Ehrhartoideae is suppressed from the database (though an unpublished note keep the information)
Luc
