### ISSUE TITLE
Chasmanthium latifolium (Michaux) H.O. Yates in MB

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2640]
This is recorded for Canada only in MB, where it is indicated as "Excluded - not documented". Is this an error?

Thanks
Jeff

**Comment by brouille** [comment]
What do you mean by: is this an error. Is it actually present, with a record that is well documented (though it could be an old report, not recollected)?
Luc

**Comment by jmsaarela** [comment]
The listing for Manitoba currently reads 'excluded: not documented',‎ which suggests to me there is no record, even if an old one. I think elsewhere in VASCAN i've seen 'excluded: old record' or something similar, for cases where there is only a very old record, which makes sense.

FNA reports 'Yates (1966b) reported seeing one specimen each from New Jersey, New Mexico, and Manitoba, but none of the specimens had clear locality information. In the absence of any further specimens from these regions, the locality data on these three specimens are regarded as probably erroneous.'

Yates (1966) cites a  MB specimen from 'cow creek bridge. Stillwater'. There is no such place in MB.

Tucker (1990) ‎ http://www.jstor.org/stable/43782240 notes in a footnote on pg 176 this putative MB specimen is an error (there is such a location in Oklahoma) and says the taxon should be removed from the flora of Canada. Image of that page attached but not sure if attachments allowed in git.

With all that in mind, the current VASCAN notation 'excluded: not documented' ‎does make sense - but only in light of this info (so confusing for a user). Something like 'previous literature report is an error (specimen not from manitoba)' might make more sense, if 'excluded' is maintained, and assuming there are no legitimate records. I don't know of any. The 1966 report seems to be the cause of all the confusion.

I see the MB report is perpetuated broadly on the web. I will update wikipedia with the info above to clarify for future workers.


Jeff
From: brouille
Sent: Tuesday, December 20, 2016 3:47 PM
To: Canadensys/vascan-data
Reply To: Canadensys/vascan-data
Cc: Jeff Saarela; Author
Subject: Re: [Canadensys/vascan-data] Chasmanthium latifolium (Michaux) H.O. Yates in MB (#2640)



What do you mean by: is this an error. Is it actually present, with a record that is well documented (though it could be an old report, not recollected)?
Luc

**Comment by brouille** [comment]
Jeff

Unfortunately, the number of categories used to classify excluded material is limited. This is not a free-form comment but a database entry with controled vocabulary. The fact that the information on which the report was based was erroneous fits exactly within the category used.

However, you are providing me with a source (Tucker 1990) for the exclusion, which will help explain the issue. VASCAN is intended as a link to sources, as much as possible, and we cannot add comment. I am adding the Tucker paper.

Luc

**Comment by jmsaarela** [comment]
Thanks Luc. I certainly understand the limitations. Yes, the previous lack of a sourc‎e for this exclusion was the confusing bit.

Jeff
From: brouille
Sent: Wednesday, January 4, 2017 2:38 PM
To: Canadensys/vascan-data
Reply To: Canadensys/vascan-data
Cc: Jeff Saarela; Author
Subject: Re: [Canadensys/vascan-data] Chasmanthium latifolium (Michaux) H.O. Yates in MB (#2640)



Jeff

Unfortunately, the number of categories used to classify excluded material is limited. This is not a free-form comment but a database entry with controled vocabulary. The fact that the information on which the report was based was erroneous fits exactly within the category used.

However, you are providing me with a source (Tucker 1990) for the exclusion, which will help explain the issue. VASCAN is intended as a link to sources, as much as possible, and we cannot add comment. I am adding the Tucker paper.

Luc
