### ISSUE TITLE
Correct name of Avenula hookeri

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2641]
...is Helictochloa hookeri (Scribn.) Romero Zarco. 

See: Romero-Zarco C. 2011. Helictochloa Romero Zarco (Poaceae), a new genus of oat grass. Candollea 66:87–103. 

http://data.canadensys.net/vascan/taxon/7437

This is now widely accepted. 

Jeff

**Comment by brouille** [comment]
correction entered - will appear next publication VASCAN
