### ISSUE TITLE
A new combination in Deschampsia

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2642]
Deschampsia cespitosa subsp. septentrionalis Chiapella, nom. nov. Basionym: Deschampsia brevi-
folia R. Br., Chlor. Melvill. 33( 34). 1823. Replaced synonym: Deschampsia cespitosa subsp. brevifolia (R. Br.) Tzvelev., Fl. Severo-Vostoka Evr. Casti SSSR 1: 141. 1974. 

The name Deschampsia cespitosa subsp. brevifolia (R. Brown) Tzvelev is illegitimate, hence the need for the new name.

Chiapella recognizes D. brevifolia as this "new" subspecies in D. cespitosa, whereas others recognize D. brevifolia as a species. It would be fine to include this new name as a synonym of D. brevifolia. I could argue it either way.  

See: Chiapella J. 2016. A new combination in Deschampsia (Poaceae) in Arctic North America. Novon: A Journal for Botanical Nomenclature 24:343–346. 10.3417/2015036

Thanks,
Jeff

**Comment by brouille** [comment]
I already have this new name in the database - it is just that VASCAN had not yet been published - it will be tomorrow, Dec. 21
