### ISSUE TITLE
Spartina, Crypsis, Calamovilfa transferred to Sporobolus (Poaceae)

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2643]
Following a publication by Peterson et al. 2014, all species of the genera mentioned above were transferred to Sporobolus. Please verify the English and French vernacular for their appropriateness (I am not suggesting we change the French spartine, for instance). Notably, note that several species changed epithet due to priority in the transfer.
Also, two introduced species were added to BD, from Spartina : Sporobolus x townsendii and Sorobolus montevidensis (= Spartina densiflora) - these are without vernaculars.

Luc

**Comment by MFavreau** [comment]
Je ne crois pas qu'il serait opportun de modifier immédiatement les noms français, car les génériques crypside, calamovilfa et spartine correspondent à des sections précises du genre Sporobolus s.l. De plus, les génériques crypside et spartine sont en usage en Europe, et le générique spartine est d'usage courant au Canada.

Par ailleurs, j'ai ajouté les noms français requis pour les deux espèces ajoutées.

Marc

**Comment by manions** [comment]
I reviewed the English vernaculars for all taxa within the above genera, plus added English vernaculars to the two taxa.
