### ISSUE TITLE
Opuntia humifusa name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2644]
http://data.canadensys.net/vascan/taxon/4145?lang=en

Recent research suggests that Opuntia cespitosa Raf. is the correct name for what has been called O. humifusa in Canada.  See Majure, Lucas C., Walter S. Judd, Pamela S. Soltis, & Douglas E. Soltis. 2017. Taxonomic Revision of the Opuntia humifusa Complex (Opuntieae: Cactaceae) of the Eastern United States. Phytotaxa 290: 1-65.

MIKE OLDHAM

**Comment by brouille** [comment]
I do not have access to Phytotaxa
Will have to wait until I get a copy, which is not available online
Luc

**Comment by brouille** [comment]
Changes have been made to VASCAN concerning O. cespitosa instead of O. humifusa.
O. humifusa var. humifusa (and sp.) excluded from Ont. as misidentification.
Luc

**Comment by brouille** [comment]
Marc and Marilyn:

I believe the vernaculars attributed to O. humisa cannot simply be transferred to O. cespitosa because the latter taxon exists (though not in Canada) and the names applied to the latter are not good fits for the species now recognized. However, the vernaculars have been used by COSEWIC.

I leave it to you to decide what is to be done with the vernaculars.
Luc

**Comment by MFavreau** [comment]
According to the authors, Opuntia cespitosa is both the most common and the most widespread member of the Humifusa clade in eastern North America. Some species may be more "eastern" but they are also rarer and more local.

The French name used for O humifusa s.l., "oponce de l'Est", is based on the English name "Eastern prickly-pear" and could be transferred to O. cespitosa as the most appropriate French name for this commonest segregate of O. humifusa, if the corresponding English name is also transferred, However, in the case a different English name would be preferred for O. cespitosa, then the French name should also be changed.

So, I will have to wait until Marilyn has made a decision about the English name before making my own decision about the French name.

Marc

**Comment by MichaelOldham** [comment]
I favour retaining the existing common names, i.e. transferring from O. humifusa to O. cespitosa, at least until someone proposes better ones.  The existing names are well entrenched in the literature (e.g. COSEWIC) and still seem appropriate.



mike



*********************************************************
Michael J. Oldham
Ontario Natural Heritage Information Centre (NHIC)
Ministry of Natural Resources
300 Water Street, 2nd Floor, North Tower
P.O. Box 7000 Peterborough, Ontario K9J 8M5, Canada
phone 705-755-2160; fax 705-755-2168
michael.oldham@ontario.ca<mailto:michael.oldham@ontario.ca>
NHIC requests: NHICrequests@ontario.ca<mailto:NHICrequests@ontario.ca>
NHIC web page: http://nhic.mnr.gov.on.ca/nhic_.cfm<https://webmail.ontario.ca/owa/redir.aspx?C=oYt4O5oPNUOsn1H3HmanID5fehjWsNAINC47ZwVJniyQjRw8C6vFRPVyWJ9nVJLyVpgnNwrFZYs.&URL=http%3a%2f%2fnhic.mnr.gov.on.ca%2fnhic_.cfm>
Ontario Reptile & Amphibian Atlas:
http://www.ontarionature.org/protect/species/herpetofaunal_atlas.php<https://webmail.ontario.ca/owa/redir.aspx?C=oYt4O5oPNUOsn1H3HmanID5fehjWsNAINC47ZwVJniyQjRw8C6vFRPVyWJ9nVJLyVpgnNwrFZYs.&URL=http%3a%2f%2fwww.ontarionature.org%2fprotect%2fspecies%2fherpetofaunal_atlas.php>
________________________________

**Comment by manions** [comment]
Yes I won't change the English COSEWIC name, but I'll read the article to
see if another alternative name might be suitable to add.
Marilyn

**Comment by MFavreau** [comment]
I transferred the French names from O. humifusa s.l. to O. cespitosa.
Marc

**Comment by manions** [comment]
I transferred over the English vernaculars
