### ISSUE TITLE
name for Apetlorhamnus alnifolia

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2645]
http://data.canadensys.net/vascan/taxon/29897

See attached article for using Endotropis alnifolia rather than Apetlorhamnus alnifolia.

Mike

[Corrigendum to Hauenschild et al, Analysis of the cosmopolitan buckthorn genera Frangula and Rhamnus s.l. supports the description of a new genus, Ventia.pdf](https://github.com/Canadensys/vascan-data/files/702691/Corrigendum.to.Hauenschild.et.al.Analysis.of.the.cosmopolitan.buckthorn.genera.Frangula.and.Rhamnus.s.l.supports.the.description.of.a.new.genus.Ventia.pdf)

**Comment by brouille** [comment]
corrected
Luc
