### ISSUE TITLE
Micranthes rufopilosa 

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2646]
Marilyn and Marc

I added taxon 30407 Micranthes rufopilosa to VASCAN (Yukon).
[Murray-Elven_Micranthes_9(1)JBRIT.pdf](https://github.com/Canadensys/vascan-data/files/712354/Murray-Elven_Micranthes_9.1.JBRIT.pdf)

Vernaculars are required
Luc

**Comment by MFavreau** [comment]
French name added,

Marilyn : please note, another saxifrage has a similar epithet, also referring to hair colour : Micranthes ruscidula.

**Comment by manions** [comment]
Hi
Yes I've reviewed all the Micranthes as I'm aware of the common names referring to 'red hairs'! I'll review all the Saxifraga next for any missing references.
I'm having trouble connecting right now via Administration.

**Comment by manions** [comment]
Thanks for the article Luc

**Comment by brouille** [comment]
Marilyn
The server is being queried heavily from outside via an API, which makes our server crash because of memory problems. This should not happen. Jeremy increased memory and restarted. Hope it works now.
Luc

**Comment by manions** [comment]
oh great, thanks, I got connected and finished with the Micranthes English vernacular review, plus for M. rufopilosa (already an existing name).
