### ISSUE TITLE
authority for Sambucus racemosa var. pubens

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2647]
Currently, (Michaux) S. Watson (1871) is listed as the accepted authority for var. pubens, but there is an earlier name: (Michaux) Trautv. & C.A. Meyer (1856), which is listed in IPNI.  It also occurs in the COL:
http://www.catalogueoflife.org/col/details/reference/synonym/30921064.  But on goggling the var. name with this author, this reference comes up with a notation that the name is an ambiguous synonym, however when you click on the link, all you get is the list of synonyms.  Do you know Trautv. and C.A. Meyer's earlier name, S. racemosa var. pubens, is valid or not?  If it is, it should replace S.Watson.

**Comment by brouille** [comment]
Sue

As far as I can tell, both var. names have the same basionym, according to TROPICOS for one (not in IPNI), and IPNI for the second (not in TRO). There does not seem to be any indication that the Trautv. & Meyer combination is illegitimate or invalid - it was probably merely missed by most authors. Therefore, it should be the proper authority indeed. IPNI further mentions another, later isonym by (Michx.) Koehne in 1893, which, surprizingly, ITIS accepts but which IPNI names as an isonym...

I am correcting VASCAN for the nonce, but who knows what the taxonomy will be in FNA once we get the manuscript. I will keep the other combination as illegitimate, so as not to confuse users.

Luc
