### ISSUE TITLE
Vernacular names for Dichanthelium sect. Lanuginosa

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2648]
Marc and Marilyn:
Following the paper (hopefully attached herein), the taxonomy of species within the sect. Lanuginosa of Dichanthelium has been dramatically revised. All vernacular names within the group need to be revised (some are appropriate, but many are missing and others are not very coherent given the accepted species name). Could you please review them all and remove names that are no longer pertinent and add names for the newly accepted taxa?

Beware, this was a complex job.

Thanks
Luc

[Thomas 2015_Revision of Dichanthelium sect. Lanuginosa (Poaceae).pdf](https://github.com/Canadensys/vascan-data/files/727300/Thomas.2015_Revision.of.Dichanthelium.sect.Lanuginosa.Poaceae.pdf)

**Comment by MFavreau** [comment]
French names added or corrected.

Plusieurs des « nouvelles » épithètes sont en fait ressuscitées, et il existait déjà des noms français, soit dans la Flore laurentienne, soit dans une version ancienne de VasCan.

Marilyn, you may want to check into Fernald 1950 for the meaning of some epithets. "spretum" is interesting.

**Comment by manions** [comment]
I'll start on the English vernacular review this week. Many thanks for the article, so important to include these!
Thanks for the heads-up Marc, yes I refer to Fernald 1950 frequently, yup interesting on that epithet! ha!

**Comment by manions** [comment]
finished the review of English vernaculars for all Dichanthelium/Panicum with corrections/additions (yet to review the few Coleataenia)
