### ISSUE TITLE
Solidago bicolor × Solidago canadensis var. canadensis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2650]
Salut

Pour le taxon suivant: http://data.canadensys.net/vascan/taxon/9792, il y a eu une réévaluation des parents de l'hybride trouvé par Hinds.
Voir l'article de Semple: DOCUMENTING A SOLIDAGO BICOLOR × S. BRENDIAE HYBRID
 (ASTERACEAE: ASTEREAE) FROM NOVA SCOTIA
http://www.phytoneuron.net/2016Phytoneuron/23PhytoN-SolidagoHybrid.pdf

**Comment by brouille** [comment]
corrigé
LB
