### ISSUE TITLE
Amelanchier interior - nom français douteux dans VASCAN

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2652]
Salut Marc

Je crois que le nom français utilisé actuellement (amélanchier de Wiegand) ne devrait pas être utilisé. Je crois que le nom utilisé par Meades (amélanchier de l'intérieur) devrait avoir préséance. 

Qu'en penses-tu?

Fred

**Comment by MFavreau** [comment]
Je suis d'accord avec toi, pour des raisons de cohérence et parce que c'est le nom utilisé dans le Dictionnaires mondial des arbres. De plus, on ne sait jamais, des études futures pourraient bien annuler la synonymie actuelle, et on se retrouverait avec un problème. Malheureusement, l'espèce figure sous de nom de « amélanchier de Wiegand » dans la liste officielle des noms de mauvaises herbes du Canada. Enfin, entre deux maux, il faut choisir le moindre. Merci beaucoup d'avoir porté ce cas à mon attention. J'ai fait le changement requis.
