### ISSUE TITLE
new taxon: Huperzia continentalis

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2654]
Marc and Marilyn

Following the attached paper, I just added Huperzia continentalis to VASCAN. It replaces H. haleakalae, a Hawaiian endemic, in the NA flora. I did not transfer the vernacular names from the latter because I did not know whether this would be appropriate (not, mostly). NAmes are required for this taxon.

http://data.canadensys.net/vascan/taxon/30495 [will not display, but here is the taxon number]

[s7.pdf](https://github.com/Canadensys/vascan-data/files/814679/s7.pdf)

Thanks
Luc

**Comment by MFavreau** [comment]
French name added. J'ai volontairement préféré « du continent » à « continental », parce que ce dernier adjectif a été beaucoup utilisé pour l'épithète « interior ».

**Comment by manions** [comment]
English vernaculars (haleakalae & continentalis) reviewed/added. Interesting paper - makes sense to investigate these occurrences
