### ISSUE TITLE
Minuartia = Cherleria

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2655]
Marilyn and Marc

A recent paper transferred all remaining species of Minuartia in our flora to the genus Cherleria (see attached doc).

I transferred vernaculars to the taxa. Please verify that they are correct. I doubt that minuartie is appropriate for these species, in French, for instance.

Thanks
Luc
[Moore & Dillenberger 2017_A conspectus of the genus Cherleria (Minuartia s.l., Caryophyllaceae).pdf](https://github.com/Canadensys/vascan-data/files/817543/Moore.Dillenberger.2017_A.conspectus.of.the.genus.Cherleria.Minuartia.s.l.Caryophyllaceae.pdf)

**Comment by MFavreau** [comment]
Luc,

Je pense que nous allons revenir à la bonne vieille « sabline », que nous n'aurions jamais dû quitter. C'est encore un bel exemple de la futilité de suivre aveuglément chaque sursaut taxonomique lorsqu'il s'agit de noms vernaculaires.

Je vais faire les vérifications la semaine prochaine.

Marc



Marc

(a tabula)

-------- Message d'origine --------
De :brouille <notifications@github.com>
Envoyé :Fri, 03 Mar 2017 13:11:41 -0500
À :Canadensys/vascan-data <vascan-data@noreply.github.com>
Ci :Subscribed <subscribed@noreply.github.com>
Sujet :[Canadensys/vascan-data] Minuartia = Cherleria (#2655)

**Comment by manions** [comment]
checked the English vernaculars and they are ok. Good caution to note Marc, I agree.

**Comment by MFavreau** [comment]
Finalement, il y avait trois options : minuartie, sabline et cherlérie.

Les sablines sont relativement lointaines au sein de la famille, et il; faudrait créer des noms.

Le nom cherlérie n'est plus utilisé depuis le 19e siècle.

Les espèces présentes en France sont encore appelées là-bas "minuartie", et ce nom est utilisé pour au moins une espèce officiellement désignée au Québec.

Je pense finalement que dans les circonstances il faut conserver le nom « minuartie » pour ces quatre espèces.
