### ISSUE TITLE
Botrychium lunaria var lunaria & B. neolunaria

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#2656]
See attached article re Botrychium lunaria var lunaria and B. lunaria var melzeri (Greenland), and B. neolunaria as additions to review for VASCAN.
Article received from John Maunder.
Marilyn Anions
[BotrychiumLunariaComplexStensvold2016.pdf](https://github.com/Canadensys/vascan-data/files/824640/BotrychiumLunariaComplexStensvold2016.pdf)

**Comment by brouille** [comment]
This has been entered in VASCAN already.
I do not recall whether I had asked you for vernaculars, however.
Luc

**Comment by MFavreau** [comment]
Il manquait finalement les noms français. Je les ai ajoutés.
