### ISSUE TITLE
incorrect reference for Ranunculus arcticus as accepted name

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#266]
[Originally posted on GoogleCode (id 2503) on 2015-02-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8552?lang=en

<b>What data are incorrect or missing?</b>
Currently listed as the reference for Ranunculus arcticus as a SciName is FNA Ed. Comm. 1997, but FNA doesn't mention R. arcticus anywhere.

<b>What data are you expecting instead?</b>
I'd like to know the reference for R. arcticus! (as needed for a project
Does Whittemore 2009 provide it? Would you have the published article to share please?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-26 18:15Z]

Elven 2007, Panarctic Flora, provided the information required
Changed - I neglected to modify the citation
Luc
