### ISSUE TITLE
Add synonym of Carex ovalis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2660]
In Ton Damman's Vegetative Key to the NL Carex, he includes Carex leporina L.  FNA mentions that Carex leporina L. was applied incorrectly to Carex ovalis, so I'd like to see Carex leporina auct. non L. added as a synonym of Carex ovalis Gooden.  I'm updating the nomenclature of Ton's Carex key, so will be including this correction, plus we've got this synonym listed in our NL checklist.

**Comment by brouille** [comment]
I added Carex laporina auct. non Linnaeus, source FNA

Luc
