### ISSUE TITLE
Arrhenatherum elatius subsp. bulbosum

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2662]
New taxon: Arrhenatherum elatius subsp. bulbosum
http://data.canadensys.net/vascan/taxon/30573

REquires French and English vernaculars

Thanks
Lue

**Comment by MFavreau** [comment]
Nom français ajouté. J'ai utilisé le nom en usage en France.

**Comment by manions** [comment]
added English vernacular
