### ISSUE TITLE
×Elyhordeum chatangense (Roshevitz) Tzvelev synonym and add for NWT

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2663]
http://data.canadensys.net/vascan/taxon/8016

For ×Elyhordeum chatangense (Roshevitz) Tzvelev, add xElyhordeum pilosilemma (W.W. Mitch. & H.J. Hodg.) Barkworth as a synonym, as this is the name used by FNA Vol. 24.

I collected this hybrid twice in NWT in 2006.  Specimens at CAN, determined by Jeff Saarela.

Mike Oldham

**Comment by brouille** [comment]
Name added, as well as homotypic synonyms
Added NWT with source CAN
Thanks
Luc
