### ISSUE TITLE
récupération des données de distribution

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2665]
Jérémie

Les données de distribution pour le taxon suivant manquent (suite au transfert apparemment raté de données lors d'un changement taxonomique):
http://data.canadensys.net/vascan/taxon/30377
Pulsatilla nuttalliana

Les données originales se trouveraient sous
http://data.canadensys.net/vascan/taxon/8432
Anemone patens var. multifida

Il faut récupérer les données de 2016 de la distribution et les placer sous Pulsatilla

Merci
Luc

**Comment by JeGoi** [comment]
Fait.
Validation ?
Merci.

**Comment by brouille** [comment]
Tout est beau
Merci
L
