### ISSUE TITLE
Synonym of Carex echinodes misspelled

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2666]
Re: http://data.canadensys.net/vascan/taxon/25728?lang=en

Carex festucacea var. echinoides (Fernald) Farwell
should be: Carex festucacea var. echinodes (Fernald) Farwell (without the 2nd 'i'.  as per Rothrock et al's paper on the Carex tenera group.

**Comment by brouille** [comment]
correction done
it is strange that TROPICOS spells it that way given the basionym, etc.
Luc
