### ISSUE TITLE
incorrect synonym of Eleocharis palustris

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2667]
http://data.canadensys.net/vascan/taxon/5251

Eleocharis palustris (Willdenow) Cosson & Germain
should be Eleocharis palustris (L.) Roemer and Schulltes var. glaucescens (Willdenow) Cosson & Germain (1845, which is the name that make's A. Grays later combination an isonym.

**Comment by sjmeades** [comment]
Note, the spelling of Schultes should be with one 'l', not 2 as I mistyped above.

**Comment by brouille** [comment]
It is var. glaucescens, but the status of the entry was erroneous (species instead of var.)
This will be corrected asap.
Luc
