### ISSUE TITLE
correction in authority of Anticlea elegans synonym 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2669]
Re: http://data.canadensys.net/vascan/taxon/6649
The synonym: Zigadenus elegans var. glaucus (Nuttall) Preece ex Cronquist

should be just Zigadenus elegans var. glaucus (Nuttall) Preece

This name appears in Gleason & Cronquist [page 827 of the 2005 8th printing] the citation in IPNI has page 864 of Edition 2 (1991), but that's due to a difference in pagination of the initial and corrected printings] 

Preece's name was originally published in his Ph.D. thesis (See FNA entry of Zigadenus)
Preece, S. J. 1956. A Cytotaxonomic Study of the Genus Zigadenus (Liliaceae). Ph.D. dissertation. State College of Washington [Washington State University]

**Comment by brouille** [comment]
I was following FNA, which was taken up by TROPICOS. But IPNI indeed has in instead of ex
Corrected
Luc
