### ISSUE TITLE
Status of Scirpus pedicellatus in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2670]
In our 2015 Checklist (annotation below), we have a new report of Scirpus pedicellatus from 2000.  Please add to Nfld., unless you've found that this was a misidentification.

[The first reports from Nfld. of Scirpus pedicellatus are from 2 collections made in 2000 along shorelines of the Upper Humber River, near Reidville, wNfld., by members of the NFRPP (C. Hanel, L. Lavers, C. Wentzell, and H. Mann).  Identification was confirmed by A.E. Schuyler (PH) (Djan-Chékar et al. 2004). This species was also collected in 2005 by J. Maunder from Whitbourne, eNfld.]

**Comment by brouille** [comment]
Now added with source: NFM
Luc
