### ISSUE TITLE
Status of Schoenoplectus tabernaemontani in NL.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2671]
In our 2015 NL Checklist, there's a notation about a 2010 report that confirms the presence of Schoenoplectus tabernaemontani from Labrador too.  Please add Labrador to the range of this species.

[Schoenoplectus tabernaemontani was reported from lacustrine marshes in wNfld. (Bouchard et al., 1991, as Scirpus validus),   A 1995 collection (S.J. Meades: MT) extended the Nfld. range to Indian Pond, north of Port au Choix. (H. Mann 1995a).  Since then, several new locations have been reported around Nfld. An undated collection by R. Day from Goose Bay, Labrador, provided the first Labrador report for the softstem bulrush (see the Digital Flora for images) and a recent verified report from C. Hanel and A. Voitk was made from Goose Bay (NFM) in 2010.]

**Comment by brouille** [comment]
Added now
Luc
