### ISSUE TITLE
list of subgeneric species of Eriophorum 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2672]
Re: the list of subgeneric species of Eriophorum 
http://data.canadensys.net/vascan/taxon/1152

E. ×pylaieanum is listed under subgenus Intersubgeneric
but its parents are both members of subgenus Eriophorum, so shouldn't E. ×pylaieanum also be under the same subgenus?  E. ×medium, which also has both parents in subgenus Eriophorum is lusted under this genus, it seems logical that E. ×pylaieanum should also be listed under that subgenus.

**Comment by brouille** [comment]
moved to subg. Eriophorum
Tx
L
