### ISSUE TITLE
Viola xsublanceolata English vernacular name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2673]
http://data.canadensys.net/vascan/taxon/9537?lang=en

Change English vernacular name from "primose-leaved violet" to "primrose-leaved violet".  English vernacular is missing the second ‘r’ in Primrose-leaved.  Error pointed out to me by Anne Barbour.

**Comment by manions** [comment]
Fixed! Thanks SO much for this correction!
