### ISSUE TITLE
add Craetaegus prona

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2674]
Crataegus prona Ashe (synonym C. gravis Ashe) is reported from Ontario in FNA Vol. 9 (2014) but does not appear in VASCAN.  

Reported from Ontario by Sargent (1908, as C. gravis): "Point Edward, near the shores of Lake Huron, Lambton County, C. K. Dodge (no. 59), May 30 and September 14, 1903, June 4 and Sept. 23, 1905; also common near Port Huron, Michigan".  Considered doubtful (reported, but no authentic specimens seen) in Ontario by Phipps and Muniyamma (1980) and Morton and Venn (1990) but accepted for Ontario by FNA Vol. 9 (2014).  Presumably James Phipps verified an Ontario collection, as he included it for Ontario in FNA.

**Comment by brouille** [comment]
species added

**Comment by MFavreau** [comment]
French name added
