### ISSUE TITLE
Erythranthe - please verify following FNA treatment

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2675]
Marilyn and Marc:

I received the FNA treatment (attached). In general, species remained unchanged, but E. sookensis was reduced in syn of E. nasuta (are the vernaculars still pertinent?) and E. microphylla was added to the flora (see eFlora BC also) : needs names.

Please verify names as required.

Luc

[Erythranthe02rev.pdf](https://github.com/Canadensys/vascan-data/files/1069152/Erythranthe02rev.pdf)

**Comment by MFavreau** [comment]
Noms français ajoutés et ajoutés.

In the case of E. microphylla, I based the French name on the English name, because leaf-size is evidently not a distinguishing character, so microphylla is a misnomer.

**Comment by manions** [comment]
English names reviewed with adjustment to E. nasuta to Latin specific (which is also in usage by some jurisdictions). 
E. microphylla English name kept the same based upon the FNA manuscript, however the "small-leaved" aspect is starting to be used by jurisdictions unfortunately. I think the FNA manuscript English name is most suitable. Hopefully that name will take precedence in usage.
