### ISSUE TITLE
Dichanthelium subvillosum in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2676]
http://data.canadensys.net/vascan/taxon/24358?lang=en

Thomas (2015) is given as the source for the listing of Dichanthelium subvillosum from Ontario, however he cites no Ontario specimens and presumably the range statement "distributed from Nova Scotia to Saskatchewan" has been used to attribute the species to Ontario.  While it may well occur in the province we know of no correctly identified specimens or specific reports from Ontario.  Dore and McNeill (1980) in their monograph of Ontario grasses state that "reports and records of P. subvillosum in Ontario all refer to this taxon [P. lanuginosum var. implicatum, =D. implicatum] or the following one [P. lanuginosum var. fasciculatum, =D. lanuginosum]".  We prefer to exclude D. subvillosum from Ontario until there is better evidence of its presence here.

Mike Oldham

**Comment by brouille** [comment]
Ont removed from distribution statement
Luc
