### ISSUE TITLE
A "herbarium name": Lycodopodium selago var. depressum

### ISSUE THREAD

**Issue by jmsaarela** [Canadensys/vascan-data#2678]
Luc, 

This a "herbarium name" we have come across, for your list of these, if it's not already on it. 

"Lycodopodium selago var. depressum" (CAN 331452 barcode CAN 10004101); Axel Heiberg Island, 20 June 1967, M. Kuc 176.

![can10004101](https://user-images.githubusercontent.com/24579276/27443682-e5afa94e-5741-11e7-9755-a079388f68ff.jpg)

**Comment by brouille** [comment]
Jeff

I cannot find a var. depressum, but there is the high arctic var. or subsp. appressa. I wonder whether Kuc did not make a mistake here. I have seen this often, even with the best, on MT specimens. Creativity knows no boundaries. Appressum is in VASCAN.

Luc

De : jmsaarela <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : jeudi 22 juin 2017 11:57
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] A "herbarium name": Lycodopodium selago var. depressum (#2678)


Luc,

This a "herbarium name" we have come across, for your list of these, if it's not already on it.

"Lycodopodium selago var. depressum" (CAN 331452 barcode CAN 10004101); Axel Heiberg Island, 20 June 1967, M. Kuc 176.

<https://user-images.githubusercontent.com/24579276/27443682-e5afa94e-5741-11e7-9755-a079388f68ff.jpg>

**Comment by brouille** [comment]
Jeff I cannot find a var. depressum, but there is the high arctic var. or subsp. appressa. I wonder whether Kuc did not make a mistake here. I have seen this often, even with the best, on MT specimens. Creativity knows no boundaries. Appressum is in VASCAN. Luc

**Comment by jmsaarela** [comment]
Indeed, i suspect the intention here was "appressum".
