### ISSUE TITLE
Euphrasia confusa - new species for British Columbia

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2680]
Salut
Fide http://www2.gov.bc.ca/gov/content/environment/plants-animals-ecosystems/conservation-data-centre/explore-cdc-data/conservation-data-centre-updates
Voir le fichier Excel 2017, onglet New and Deleted

Euphrasia confusa | confused eyebright | Exotic | SNA | GNR | Collected by C. Bjork (destined for UBC   Beaty Biodiversity museum herbarium).

Fred

**Comment by brouille** [comment]
non listé pour FNA ds ms Gussarova cependant

**Comment by brouille** [comment]
Non listé ds BC Species & Ecosystems Explorer de 2022 ni ds eFlora BC, ni ds la bd de UBC. Je n'ajouterai pas ce taxon qui ne semble pas avoir été retenu au final.

LB
