### ISSUE TITLE
Fragaria x ananassa var. ananassa - new species for British Columbia

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2681]
Salut
BC reconnait deux variétés pour cet hybride.  On a déjà l'autre dans VASCAN.

Fragaria   x ananassa var. ananassa: (The cultivated   strawberries have escaped and been well-established in BC for decades (F.   Lomer pers. comm.); specimens at UBC Beaty Biodiversity museum herbarium.)
--

**Comment by brouille** [comment]
ajouté comme subsp. ananassa
