### ISSUE TITLE
Hieracium pilosella ssp. micradenium - à ajouter dans les synonymes?

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2682]
Salut

Dans le fichier Excel 2017, BC reconnait cette ssp.  http://www2.gov.bc.ca/gov/content/environment/plants-animals-ecosystems/conservation-data-centre/explore-cdc-data/conservation-data-centre-updates

Hieracium   pilosella ssp. micradenium
--

**Comment by brouille** [comment]
Selon http://cichorieae.e-taxonomy.net/ c'est un synonyme de Pilosella officinarum (H. pilosella), listée comme introduite par Douglas et al. , et non rapportée par eFlora
Ce n'est qu'un synonyme, que j'ajoute à VASCAN cependant à cause de cette mention
Luc
