### ISSUE TITLE
Lupinus depressus - addition à la flore du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2683]
Salut

Maintenant dans la Blue List de BC: 

A plant of   subalpine balds in the West Kootenays (perhaps ranging into the Rockies   also)(C. Bjork, pers. comm.); specimens at UBC Beaty Biodiversity museum   herbarium.
--

**Comment by brouille** [comment]
non trouvé ds UBC database

**Comment by manions** [comment]
BC specimens under Lupinus argenteus var. depressus at UBC, also listed on Consortium of Pacific Northwest Herbaria. But not searchable by L. depressus.

**Comment by brouille** [comment]
Marilyn and Marc
Species added
Vernacular names are required for this taxon.
Thanks
Luc

**Comment by MFavreau** [comment]
Nom français ajouté. Comme il existait déjà un « lupin nain » et un « lupin subalpin », j'ai dû me résoudre à appeler celui-ci « lupin déprimé ».

Marilyn : beware, several other lupines have similar-meaning epithets.

**Comment by manions** [comment]
English name added
