### ISSUE TITLE
Luzula macrantha - ajout pour le Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2684]
Salut  

BC Red List 2017: 

A new woodrush for   the Pacific Northwest, just published (Zika, P.F., B.L. Wilson, and J.   Kirschner. 2015. The Luzula comosa complex (Luzula section Luzula, Juncaceae)   in western North America. Phytotaxa 192 (4): 201–229). Specimen for BC at   University of Washington herbarium.
--

**Comment by brouille** [comment]
Ai corrigé la répartition et synonymie de L. comosa
Ai ajouté L. macracantha
Ai ajouté L. subsessilis
LB

**Comment by brouille** [comment]
Marc and Marilyn

Vernacular names required for : 
Luzula macrantha http://data.canadensys.net/vascan/taxon/30742
Luzula subsessilis http://data.canadensys.net/vascan/taxon/16893

Luc

**Comment by MFavreau** [comment]
French names added

**Comment by manions** [comment]
English names added.
Marc - reference needed for the French name you added for L. subsessilis (Favreau?). Then close this issue please.

**Comment by MFavreau** [comment]
Reference added for French name. Thank you Marilyn.
