### ISSUE TITLE
Pellaea breweri - addition pour le Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2685]
Salut

Pellaea   breweri: 

Collected by F.   Lomer in 2016 (UBC Beaty Biodiversity museum herbarium). A new Pellaea   species from southern BC, previously not known in Canada.The petiole bases   have clear articulation lines, any one of which can break off, leaving behind   a dense clump of broken bases. The lower pinnae are  deeply two-lobed, unlike the Pellaea   glabella ssp. simplex plants that grow in southern BC, usually on limestone.
--

--

**Comment by brouille** [comment]
aucune collection de cette sp ds UBC database encore

**Comment by brouille** [comment]
Marilyn and Marc

Species added based on UBC

Vernacular names are required for this species
Thanks
Luc

**Comment by MFavreau** [comment]
French name added

**Comment by manions** [comment]
English name added
