### ISSUE TITLE
Pyrola crypta - addition à la flore du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2687]
Salut

BC: 

New collection from   R. Batten, confirmed by D. Jolles; seen on Crest and Adder mts. Concept based   on Jolles, Diana D. & Wilson, Carol A. 2014. Pyrola crypta: A Pacific   Northwest species belonging to the Pyrola picta species complex.Taxon, Volume   63, Number 4. Pp. 789-800(12).
--

**Comment by brouille** [comment]
pas de spécimen cité ds UBC database - doit vérifier article pour voir si BC mentionné

**Comment by brouille** [comment]
Pyrola crypta added for BC, but need specimen in herbarium (not yet in UBC database)

**Comment by brouille** [comment]
Pyrola crypta - see Taxon 63(4): 798, 2014
New taxon for BC
Require vernacular in French and English (none provided in paper)
Thanks
Luc

**Comment by manions** [comment]
English name added

**Comment by MFavreau** [comment]
French name added.
