### ISSUE TITLE
Rhinanthus glaber - addition à la flore du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2688]
Salut

introduite au BC: 

Native to Eurasia,   introduced at Atlin and Alaska, now known in BC due to a collected by V.   Skilton (UBC Beaty Biodiversity museum herbarium).
--

**Comment by brouille** [comment]
aucune entrée ds UBC database

**Comment by brouille** [comment]
Rhinanthus glaber est syn de R. minor subsp. minor selon certaines sources.

De plus pas ds UBC db ni E FLora, ni ds site de conservation BC

non ajouté
LB
