### ISSUE TITLE
Symphyotrichum hendersonii - addition à la flore du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2689]
Salut

BC:
Collected by F.   Lomer in 2015 (UBC Beaty Biodiversity museum herbarium)
--

**Comment by brouille** [comment]
aucune entrée ds UBC database

**Comment by brouille** [comment]
Cannot find the Lomer 2015 collection in UBC
I did find a collection by Krajina 1968 under Aster foliaceus var. lyallii (a syn), but I do not know whether this was verified.
Luc

UBC a enfin publié les données de ce spécimen

**Comment by brouille** [comment]
Marc
Il faudrait ajouter un vernaculaire français pour cette espèce nouvelle au Canada
J'ai ajouté le vernaculaire anglais de FNA
Luc

**Comment by MFavreau** [comment]
C'est fait. Une facile.
