### ISSUE TITLE
Amelanchier quebecensis - ajout d'un synonyme pour A. bartramiana

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2690]
Salut

Amelanchier quebecensis  http://www.ipni.org/ipni/idPlantNameSearch.do?id=11236-2   

Selon cet article, notre A. quebecensis est synonyme de A. bartraminana..
Kevin R. Cushman, Michael B. Burgess, Eric T. Doucette, Gretchen A. Nelson, and Christopher S. Campbell. Species Delimitation in Tetraploid, Apomictic Amelanchier (Rosaceae). Systematic Botany Apr-Jun 2017 : Vol. 42, Issue 2, pg(s) 234- 256
https://doi.org/10.1600/036364417X695529

**Comment by brouille** [comment]
ajouté
