### ISSUE TITLE
Autorité à changer pour Amelanchier x neglecta

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2691]
Salut

Selon cet article, Amelanchier x neglecta avec Eggleston ex G.N. Jones comme autorité est invalide.
L'autorité est Eggleston ex K.R. Cushman, M.B. Burgess, E.T. Doucette & C.S. Campb.

2e L'article mentionne beaucoup de synonymes qui ne sont pas dans VASCAN. 

Kevin R. Cushman, Michael B. Burgess, Eric T. Doucette, Gretchen A. Nelson, and Christopher S. Campbell. Species Delimitation in Tetraploid, Apomictic Amelanchier (Rosaceae). Systematic Botany Apr-Jun 2017 : Vol. 42, Issue 2, pg(s) 234- 256
https://doi.org/10.1600/036364417X695529

**Comment by brouille** [comment]
autorité changée - synonymes ajoutés
