### ISSUE TITLE
Lonicera chrysantha remove

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2693]
http://data.canadensys.net/vascan/name/Lonicera%20chrysantha

The sole report of Lonicera chrysantha for Ontario (and Canada), as far as I am aware, is based on a misidentified specimen (see attached).  An occasional escape from cultivation reported from Peel Regional Municipality by Webber (1984), with specimen(s) at TRTE.  However the Peel Region (Mississauga) specimen on which its occurrence in the region was based (J. M. Webber 2365, TRTE) was revised to Lonicera x bella by P.M. Catling in 2015 (P. W. Ball, pers. comm. July 2017).  Listed for Ontario by Morton and Venn (1990) based on the Webber (1984) report.  Catling et al. (2016) do not mention this species in their summary of alien invasive Lonicera in Canada.

MIKE OLDHAM
[Lonicera xbella (sub. L. chrysantha) PEEL (TRTE).pdf](https://github.com/Canadensys/vascan-data/files/1183010/Lonicera.xbella.sub.L.chrysantha.PEEL.TRTE.pdf)

**Comment by brouille** [comment]
L. chrysantha now excluded as misidentification, source : DAO
