### ISSUE TITLE
Lonicera chrysantha

### ISSUE THREAD

**Issue by peterball2** [Canadensys/vascan-data#2694]
This record is based on a specimen that is in TRTE (collected by J. Webber). This specimen has been redetermined as Lonicera x bella by Paul Catling. I agree with this redetermination. Therefore there is no evidence that Lonicera chrysantha occurs in Canada.

**Comment by brouille** [comment]
Lonicera chrysantha is already excluded from Ont.
Thanks for the additional confirmation.
Luc
