### ISSUE TITLE
recognition of Potamogeton pusillus subsp. tenuissimus at species level

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2696]
http://data.canadensys.net/vascan/taxon/8315

Using molecular data, Les et al. (2009; attached) demonstrated that P. pusillus subsp. tenuissimus should be recognized at the species level as P. berchtoldii.  Note that the attached article also has implications for the nomenclature of subsp. gemmiparus.  Les et al. (2009) recommend treating it as a either a distinct species or as a subsp. of P. berchtoldii.  
[Les et al 2009_Systematics of two imperiled pondweeds (Potamogeton vaseyi, P. gemmiparus) and taxonomic ramifications for Section Pusilli (Potamogetonaceae).pdf](https://github.com/Canadensys/vascan-data/files/1239331/Les.et.al.2009_Systematics.of.two.imperiled.pondweeds.Potamogeton.vaseyi.P.gemmiparus.and.taxonomic.ramifications.for.Section.Pusilli.Potamogetonaceae.pdf)

**Comment by brouille** [comment]
P. berchtoldii acc
P. gemmiparus acc
P. pusillus without subsp.
Luc
