### ISSUE TITLE
Arisaema triphyllum subsp. pusillum and subsp. stewardsonii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2699]
http://data.canadensys.net/vascan/taxon/2673?lang=en
http://data.canadensys.net/vascan/taxon/2675?lang=en

Author name should be Huttleston not Huttlestone.

[Huttleston 1949_The Three Subspecies of Arisaema triphyllum.pdf](https://github.com/Canadensys/vascan-data/files/1277923/Huttleston.1949_The.Three.Subspecies.of.Arisaema.triphyllum.pdf)

Mike Oldham

**Comment by brouille** [comment]
typo corrected
Thanks
Luc
