### ISSUE TITLE
Echinocystis oregana (Torrey & S. Watson) Cogniaux

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#27]
[Originally posted on GoogleCode (id 1298) on 2012-04-04]

Salut

L'autorité est mauvaise:
Devrait être (Torrey ex S. Watson) Cogniaux

Le ex....

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-04-10 13:54Z]

Où as tu trouvé ces autorités? Je ne peux les trouver...

Luc
