### ISSUE TITLE
Ranunculus Section Batrachium taxonomy

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2700]
http://data.canadensys.net/vascan/taxon/8502

Suggest following the recent global revision by Wiegleb et al. (2017) of Ranunculus Section Batrachium.  The FNA treatment, now more than
[Wiegleb et al 2017_A taxonomic account of Ranunculus section Batrachium (Ranunculaceae).pdf](https://github.com/Canadensys/vascan-data/files/1278341/Wiegleb.et.al.2017_A.taxonomic.account.of.Ranunculus.section.Batrachium.Ranunculaceae.pdf)
 20 years old, was always a little unsatisfactory as it lumped so many taxa, which were often recognized by others, in R. aquatilis var. diffusus.  Following Wiegleb et al. (2017) we have R. longirostris, R. subrigidus, and R. trichophyllus in Ontario.  Unfortunately since Wiegleb et al. have only fairly broad range statements and no distribution maps it may be difficult to sort out presence/absence for some species in Canadian provinces and territories.

Mike Oldham

**Comment by brouille** [comment]
In Canada we now have:
hederaceus (int.)
lobbi (BC)
trichophyllus
longirostris
subrigidus
mongolicus (BC)
porteri (BC?)
codyanus (arctic)

I was able to provide approximate distributions but these need to be validated with Crow & Hellquist 2000

Luc

**Comment by MFavreau** [comment]
Marilyn,

I just noticed that there are no vernaculars for R. trichophyllus, R. mongolicus, R. porteri, R. subrigidus, and R. codyanus, and no English vernacular for R. longirostris.

I will add the missing French names shortly.

Marc

**Comment by MFavreau** [comment]
French names added.

**Comment by manions** [comment]
Many thanks, sorry I missed this. English vernaculars added.
