### ISSUE TITLE
Stuckenia filiformis subspecies

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2702]
http://data.canadensys.net/vascan/taxon/8338

The most recent revision of Stuckenia (Kaplan 2008; attached) makes a compelling case that subspecies and varieties that have been described in S. filiformis are environmentally induced (e.g. river forms vs. lake forms); transplant experiments have confirmed this.  Kaplan (2008) recommends not recognizing infraspecific taxa and Barre Hellquist (pers. comm. Aug. 2017) agrees with this approach.  We no longer recognize ssp. alpina and ssp. occidentalis in our Ontario list.

Mike Oldham
[Kaplan 2008_A Taxonomic Revision of Stuckenia (Potamogetonaceae) in Asia, with Notes on the Diversity and Variation of the Genus on a Worldwide Scale.pdf](https://github.com/Canadensys/vascan-data/files/1296133/Kaplan.2008_A.Taxonomic.Revision.of.Stuckenia.Potamogetonaceae.in.Asia.with.Notes.on.the.Diversity.and.Variation.of.the.Genus.on.a.Worldwide.Scale.pdf)

**Comment by brouille** [comment]
Removed subspecies of S. filiformis

Corrected taxonomy of P. pusillus-P. berchtoldii complex

Luc
