### ISSUE TITLE
Symphyotrichum undulatum in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2704]
http://data.canadensys.net/vascan/name/Symphyotrichum%20undulatum

We (NHIC) exclude this report as a probable label error.  From the NHIC database: "Reported doubtfully for Ontario by Ontario by Semple et al. (2002), based on a specimen at TRT reportedly collected at Silver Hill, Norfolk County.  Ontario reports (e.g. FNA Vol. 20) are probably in error.  According to Morton and Venn (1990) the Ontario report needs confirmation.  A labeling error is strongly suspected and subsequent searches of the area have not revealed the species (Sutherland 1987)."

Mike Oldham

**Comment by brouille** [comment]
Excluded due to misidentification
