### ISSUE TITLE
coquille Latin? Solidago brendiae

### ISSUE THREAD

**Issue by MarieDAoust** [Canadensys/vascan-data#2706]
Solidago brend**iae** plutôt que S. brendae
source : https://uwaterloo.ca/astereae-lab/research/goldenrods/classification-and-illustrations/solidago-brendiae

**Comment by brouille** [comment]
L'épellation de ce nom fait l'objet d'une controverse entre Semple et K. Gandhi: ce dernier rappelle que la forme latine correcte serait brendae (de Brenda) et non brendiae
Semple dit qu'il a le choix
Je préfère utiliser brendae pour l'instant car K. Gandhi est un nomenclaturiste reconnu
Luc Brouillet
