### ISSUE TITLE
Carex lenticularis taxonomy

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2707]
http://data.canadensys.net/vascan/taxon/4941?lang=en

Suggest following Dragon and Barrington (2009; attached) for taxonomy and nomenclature of the Carex lenticularis group (see their Table 3).  This would result in the elevation of several varieties to the species level.

Mike Oldham
[Dragon & Barrington 2009_SYSTEMATICS OF THE CAREX AQUATILIS AND C. LENTICULARIS LINEAGES, CAREX SECTION PHACOCYSTIS (CYPERACEAE).pdf](https://github.com/Canadensys/vascan-data/files/1398418/Dragon.Barrington.2009_SYSTEMATICS.OF.THE.CAREX.AQUATILIS.AND.C.LENTICULARIS.LINEAGES.CAREX.SECTION.PHACOCYSTIS.CYPERACEAE.pdf)

**Comment by brouille** [comment]
Carex lenticularis taxonomy was modify following Dragon & Barrington 2009, and more particularly WCSP (all names properly changed):
var. dolia auct.  = C. enanderi [var. dolia s.str. not in Canada]
var. impressa = C. kelloggii var. impressa
var. limnophila = C. kelloggii var. limnophila
var. lipocarpa = C. kelloggii var. kelloggii
var. lenticularis = C. lenticularis [no var.]

spp of sect. Scitae [exc. C. paysonis that needs validation as to position] transferred to sect. Phacocystis
