### ISSUE TITLE
Chamerhodos erecta introduced (not native) in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2708]
http://data.canadensys.net/vascan/taxon/8642

The only Ontario record came from highly disturbed habitat where almost certainly introduced.

M.J. Oldham & W.D. Bakowsky 20136 (MICH, TRTE, DAO,WAT,NHIC,mb,+3), 17 July 1997, KENORA, Redditt, cinders and gravel of railway and adjacent runway, locally common in cinders of grassy runway adjacent to railway, weedy assoc, apparently adventive, not seen in native rock barrens habitat nearby.

Mike Oldham

**Comment by brouille** [comment]
correction made
There was a note in the database questioning the status in ON, without solution.
Thanks
Luc
