### ISSUE TITLE
Erigeron purpuratus reported for NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#271]
[Originally posted on GoogleCode (id 2538) on 2015-03-19]

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/search/?q=Erigeron+purpuratus

<b>What data are incorrect or missing?</b>
missing from NWT

<b>What data are you expecting instead?</b>
I asked Paul Catling to look at the Erigeron hyperboreus specimen at DAO. He wrote Guy Nesom. Reply from both below.

<b>If applicable, please provide an authoritative source.</b>
Paul made the following comments regarding the specimen in question: he had trouble dealing with this meagre and immature specimen.  We sent images to an expert on the group, Guy Nesom, who responded “That's probably E. purpuratus - compared with what material you have.  Definitely not E. hyperboreus.”  Paul found that it did compare relatively well with purpuratus, but was without divided leaves (which are not always divided in purpuratus specimens) and with a tawny pappus (like pallens), but the pappus was not mature. Although purpuratus was not mapped for NWT by Nesom in FNA, there are several locations shown in Porsild and Cody (but he cannot find our NWT folder).  Regardless he believes that it is probably best to accept the expert opinion of E. purpuratus.”

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-20 13:46Z]

I entered it with DAO as source

This will require further confirmation (finding that NWT folder at DAO would be good)

Luc
