### ISSUE TITLE
add Rubus x wisconsinensis for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2713]
http://data.canadensys.net/vascan/taxon/1629?lang=en

Rubus x wisconsinensis has been collected in Ontario (Quetico Provincial Park, Rainy River District, in 2014, P.A.Scott 3976 at ISC, det. M.K. Widrlechner as R. wisconsinensis).  FNA Vol. 9 considers it a R. pensilvanicus X R. setosus hybrid.

Mike Oldham

**Comment by brouille** [comment]
nothospecies and distribution data added
Luc
