### ISSUE TITLE
Euphrasia farlowii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2716]
http://data.canadensys.net/vascan/name/Euphrasia%20randii%20var.%20farlowii

Combination is now published by Gussarova (2017).

Mike Oldham
[Gussarova 2017_New combinations in Nearctic endemic Euphrasia (Orobanchaceae).pdf](https://github.com/Canadensys/vascan-data/files/1523754/Gussarova.2017_New.combinations.in.Nearctic.endemic.Euphrasia.Orobanchaceae.pdf)

**Comment by brouille** [comment]
This was already entered in VASCAN but remains to be published
It is curious Gussarova does not have it in QC while it is in both ON and NB...
Luc
