### ISSUE TITLE
Euphrasia oakesii varieties

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2717]
http://data.canadensys.net/vascan/taxon/7014

Euphrasia oakesii varieties recognized by Gussarova (2017).   Var. oakesii from NL, QC; var. williamsii from NL, QC.

Mike Oldham
[Gussarova 2017_New combinations in Nearctic endemic Euphrasia (Orobanchaceae).pdf](https://github.com/Canadensys/vascan-data/files/1523770/Gussarova.2017_New.combinations.in.Nearctic.endemic.Euphrasia.Orobanchaceae.pdf)

**Comment by brouille** [comment]
varieties now added
LB
