### ISSUE TITLE
Sida hermaphrodita new name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2718]
http://data.canadensys.net/vascan/name/Sida%20hermaphrodita

Weakley et al. (2017) published Ripariosida hermaphrodita (L.) Weakley & D.B. Poind. for Sida hermaphrodita.  In Canada only from Ontario.

Mike Oldham
[Weakley et al 2017_New combinations, rank changes, and nomenclatural and taxonomic comments in the vascular flora of the southeastern United States. II.pdf](https://github.com/Canadensys/vascan-data/files/1523773/Weakley.et.al.2017_New.combinations.rank.changes.and.nomenclatural.and.taxonomic.comments.in.the.vascular.flora.of.the.southeastern.United.States.II.pdf)

**Comment by brouille** [comment]
Change made
