### ISSUE TITLE
Maianthemum racemosum subspecies

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2719]
http://data.canadensys.net/vascan/taxon/2738

Weakley et al. (2017) elevate subsp. amplexicaule to species status.

Mike Oldham

[Weakley et al 2017_New combinations, rank changes, and nomenclatural and taxonomic comments in the vascular flora of the southeastern United States. II.pdf](https://github.com/Canadensys/vascan-data/files/1523776/Weakley.et.al.2017_New.combinations.rank.changes.and.nomenclatural.and.taxonomic.comments.in.the.vascular.flora.of.the.southeastern.United.States.II.pdf)

**Comment by brouille** [comment]
Change made
