### ISSUE TITLE
Gypsophila muralis confirmed for NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#272]
[Originally posted on GoogleCode (id 2539) on 2015-03-19]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4302?lang=en

<b>What data are incorrect or missing?</b>
<b>What data are you expecting instead?</b>
add NWT

<b>If applicable, please provide an authoritative source.</b>
I wrote Michael Oldham to double check on his 2006 survey notes reporting this species. He has confirmed that it's definitely G. muralis.
Specimens will be at TRTE and mjo.
Mike's survey report can be cited as follows:
Oldham, M.J. 2014. A survey of exotic plants along Northwest Territories highways and additions to the vascular plant flora of the Northwest Territories, Canada. Report submitted to NWT Govt.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-20 13:51Z]

I cannot cite such a report because it is not generally available. But I can cite TRTE.

Luc
