### ISSUE TITLE
Mentha x gentilis name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2720]
http://data.canadensys.net/vascan/taxon/6408?lang=en

Haines (2011; Flora Novae-Angliae) treats Mentha x gentilis as a superfluous synonym of M. x gracilis.  Tucker and Naczi (2007) also consider M. x gentilis a synonym of M. x gracilis. 

According to Haines (2011) the type specimen of M. gentilis is a pollen-sterile clone of M. arvensis, which he treats as M. arvensis ssp. parietariaefolia (Becker) Briq. (also recognized by Tucker and Naczi 2007) and reports as widespread in New England.

[Tucker & Naczi 2007_Mentha - an overview of its classification and relationships.pdf](https://github.com/Canadensys/vascan-data/files/1544653/Tucker.Naczi.2007_Mentha.-.an.overview.of.its.classification.and.relationships.pdf)

**Comment by brouille** [comment]
M. xgracilis adopted with xgentilis in syn
LB
