### ISSUE TITLE
Calystegia pubescens - espèce reconnue dans FNA

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2721]
Salut
Il faut enlever ce nom (Calystegia pubescens) comme un synonyme de  C. hederacea.  Cependant, le C. pubescens dans FNA ne semble pas présent au Canada.

**Comment by brouille** [comment]
Merci
L

De : FredCoursol <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : mardi 12 décembre 2017 11:59
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] Calystegia pubescens - espèce reconnue dans FNA (#2721)


Salut
Il faut enlever ce nom (Calystegia pubescens) comme un synonyme de C. hederacea. Cependant, le C. pubescens dans FNA ne semble pas présent au Canada.

**Comment by brouille** [comment]
Synonyme enlevé de la bd
Luc
