### ISSUE TITLE
Calystegia spithamaea (Linnaeus) Pursh subsp. spithamaea  - absent du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2722]
Salut

FNAms reconnait que la subsp. stans (Michaux) Brummitt au Canada.
D'ailleurs, en faisant la clé d'identification, j'étais surpris de voir que ma mémoire ne m'amenait pas vers le subsp. spithamaea car je me rappelais que VASCAN indiquait seulement la ssp. typique pour le Québec.  Ce fut donc une grande surprise de constater que la ssp. spithamaea est absente!  Au moins, la clé d'identification confirme le tout!

**Comment by MFavreau** [comment]
Curieusement, le mot stans veut dire dressé, et c'est justement le nom français utilisé pour l'espèce par Marie-Victorin. J'ai donc déplacé le nom français vers la sous-espèce stans.

**Comment by manions** [comment]
Calystegia English vernaculars reviewed and added
