### ISSUE TITLE
Calystegia silvatica   (Kitaibel) Grisebach subsp. disjuncta Brummitt

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2725]
ajout pour le Canada.
Il semble correspondre à la subsp. silvatica présente dans VASCAN.  Probablement une réidentification de la ssp. présente au BC.

**Comment by brouille** [comment]
en effet, c'est ainsi que j'ai fait cette correction, en excluant aussi subsp. silvatica puisqu'elle est rapportée
LB
