### ISSUE TITLE
 Campanula intercedens Witasek - ajout pour le Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2727]
Salut

Je ne vois pas ce taxon dans VASCAN.  On en avait parlé ce printemps et Pierre Morriset confirmait que dans l'estuaire, c'était ce taxon qui était présent alors que Campanula giesekiana se trouve plus en Gaspésie.

**Comment by brouille** [comment]
Campanula intercedens ajouté, répartition corrigée pr giesekeana [non giesekiana]
LB
