### ISSUE TITLE
Asclepias tuberosa

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2728]
http://data.canadensys.net/vascan/taxon/2712

I'm curious regarding the recognition of var. interior (Woodson) Shinners [1949] rather than ssp. interior, which was used later by Woodson (1954) in his monograph of North American Asclepias and seems to be more often used in regional floras (e.g. Haines 2011, Flora Novae-Angliae).  Woodson (1954) lists both ssp. interior and ssp. tuberosa for Ontario, so even if varieties rather than subspecies are used, then presumably var. tuberosa should be listed for Ontario.

Reference:  Woodson, Jr., R. E. 1954. The North American species of Asclepias L. Annals of the Missouri Botanical Garden 41: 1-203.

**Comment by brouille** [comment]
Am awaiting FNA treatment currently. Will not deal with this until I have seen the draft.
Luc

**Comment by brouille** [comment]
FNA treatment now used : subsp. interior adopted
LB
