### ISSUE TITLE
Arctium tomentosum in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#2729]
Add as Exotic for NWT as Michael Oldham collected Arctium tomentosum at Fort Providence, NWT in 2016.

**Comment by brouille** [comment]
Please speficy where specimen is deposited for citation, as Mike did not inform me of this record
Luc

**Comment by manions** [comment]
I'll double check with Mike, but on his collection spreadsheet, he has indicated specimens at DAO, MJO, BABY, plus photos

**Comment by brouille** [comment]
That is enough. He usually does that.
L

De : manions <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : mardi 9 janvier 2018 15:40
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Luc Brouillet <luc.brouillet@umontreal.ca>, Comment <comment@noreply.github.com>
Objet : Re: [Canadensys/vascan-data] Arctium tomentosum in NWT (#2729)


I'll double check with Mike, but on his collection spreadsheet, he has indicated specimens at DAO, MJO, BABY, plus photos

**Comment by brouille** [comment]
added, based on DAO specimen
Luc
