### ISSUE TITLE
New Spiranthes species

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2730]
Marilyn and Marc
The attached paper recognizes new species within the Spiranthes cernua complex in eastern NA. Two species are added to the flora of Canada in VASCAN: S. arcisepala and S. incurva

Though the authors do not propose vernacular names, I attach the paper to help you with etimology.

Vernaculars are required for both.

Happy New Year
Luc
[Pace & Cameron 2017_The Systematics of the Spiranthes cernua Species Complex (Orchidaceae).pdf](https://github.com/Canadensys/vascan-data/files/1616343/Pace.Cameron.2017_The.Systematics.of.the.Spiranthes.cernua.Species.Complex.Orchidaceae.pdf)

**Comment by MFavreau** [comment]
Marilyn,

Actually, the authors do propose English vernacular names : “Appalachian
ladies’ tresses” for Spiranthes arcisepala, and "sphinx ladies' tresses" for S. incurva.

Noms français ajoutés à VasCan.

Marc

**Comment by manions** [comment]
Many thanks, English vernaculars added.
