### ISSUE TITLE
Douglasia gormanii in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#2731]
Reported for NWT.  Here is the data entry in the NWT InfoBase:
August 12, 2013 64.63703	-128.34094 Mackenzie Mountains, Canyon Range plateau, Site H	1982 m	Poorly vegetated moist low slope unglaciated alpine plateau mainly limestone bedrock. Dominated by Salix arctica, Dryas integrifolia, Cerastium, Draba spp., and Micranthes rufopilosa.	Locally common but only place seen. Herbarium Deposits UBC; CAN; BABY (B Bennett database 2013)

**Comment by brouille** [comment]
added to NWT with source CAN
LB
