### ISSUE TITLE
Taraxacum lapponicum in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#2735]
Found two specimens (CAN 269033 and UBC V89700) same locality/collector (Raup & Soper 1939) with previous ID as T. ?croceum. Maybe could be checked if ID is correct, as T. lapponicum is listed for NWT. The CAN website lists update as per 2011, so I'm not sure if ID has been checked.
NWT is reporting the species.

**Comment by brouille** [comment]
Difficult to just add this without specimens being revised by credible authority. Who revised specimens at CAN, and was it based on Solsted's work? 
Please enquire at CAN for more data
Luc

**Comment by manions** [comment]
confirmed presence in NWT by Dr. Jeff Saarela with CAN specimen. See emails 8Feb2018.

**Comment by brouille** [comment]
added to NWT
