### ISSUE TITLE
Polygonum erectum subspecies

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2737]
http://data.canadensys.net/vascan/taxon/8172?lang=en

Mueller (2017) recently described ssp. watsoniae from Arkansas and Illinois, making the Polygonum erectum in Canada ssp. erectum.

Mike Oldham

Mueller, N.G. 2017. An extinct domesticated subspecies of erect knotweed in eastern North America: Polygonum erectum subsp. watsoniae (Polygonaceae). Novon 25: 166-179.
--

[Mueller 2017_An Extinct Domesticated Subspecies of Erect Knotweed in Eastern North America, Polygonum erectum subsp. watsoniae (Polygonaceae).pdf](https://github.com/Canadensys/vascan-data/files/1632911/Mueller.2017_An.Extinct.Domesticated.Subspecies.of.Erect.Knotweed.in.Eastern.North.America.Polygonum.erectum.subsp.watsoniae.Polygonaceae.pdf)

**Comment by brouille** [comment]
I will not include and extinct, domesticated subsp. in VASCAN, at least for the time being
LB
