### ISSUE TITLE
Polygala cruciata name change

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2738]
http://data.canadensys.net/vascan/taxon/8091?lang=en

Based on Sorrie and Weakley (2017) Polygala cruciata (var. aquilonia) in Canada should be called Polygala aquilonia.

Mike Oldham
[Sorrie & Weakley 2017_Reassessment of variation within Polygala cruciata sensu lato (Polygalaceae).pdf](https://github.com/Canadensys/vascan-data/files/1632996/Sorrie.Weakley.2017_Reassessment.of.variation.within.Polygala.cruciata.sensu.lato.Polygalaceae.pdf)

Sorrie, B.A., and A.S. Weakley. 2017. Reassessment of variation within Polygala cruciata sensu lato (Polygalaceae). Phytoneuron 2017-37: 1–9.
--

**Comment by brouille** [comment]
Polygala cruciata removed from VASCAN, replaced by Polygala aquilonia

Marc and Marylin:
the current vernaculars appear to apply to cruciata, no longer recognized here; notably, any allusion to cross refers directly to cruciata - thus I believe names based on aquilonia would be best - Please see the reference provided by Mike Oldham above for reference to original publication of the name (as variety) - this may provide suitable base for vernaculars
Thanks Luc

**Comment by MFavreau** [comment]
French name changed.
L'ancien nom français « polygale des marais » n'était pas lié à l'`épithète latine cruciata, mais il était lié à l'espèce cruciata dans la source. Il vaut mieux le changer, d'autant plus qu'il y a une différence d'habitat entre les deux espèces, selon la référence fournie.
J'ai donc choisi une traduction de aquilonia, qui veux dire « du Nord ».

**Comment by manions** [comment]
Full review of English vernaculars for Polygalaceae completed. Many thanks for the reference, this is always appreciated.
