### ISSUE TITLE
Missplaced synonym of Matteuccia struthiopteris

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2741]
Re: http://data.canadensys.net/vascan/taxon/5421

Pteretis struthiopteris (Linnaeus) Nieuwland is listed as a synonym of Matteuccia struthipteris var. pensylvanica, as also shown in FNA.  But I think this was anerror on their part, as this name should appear as a synonym under the typical Eurasian variety, Matteuccia struthiopteris var. struthiopteris.

**Comment by brouille** [comment]
I moved the synonym to the species name, so as not to loose it. But you are right. This was incorrect in FNA. It predates K. Gandhi as nomenclature editor
I sent a note to FNA and Kanchi.
Luc
