### ISSUE TITLE
pickerelweed common name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2742]
http://data.canadensys.net/vascan/taxon/8244

Pickerelweed is hyphenated as an English common name for the family (i.e. pickerel-weed) but not hyphenated for the sole Canadian species.

Mike Oldham

**Comment by brouille** [comment]
Marilyn and Marc
Please consider this
Luc

**Comment by MFavreau** [comment]
I will let Marilyn act on this one, which has no impact on the French vernaculars.

Marc

**Comment by manions** [comment]
corrected, thanks. Sometimes someone else has added the family name (I don't use the capital)
