### ISSUE TITLE
hyphenating evening-primrose

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2743]
http://data.canadensys.net/vascan/taxon/6808

Evening primrose is not hyphenated in species common names but is hyphenated (evening-primrose) in the family common name.

Mike Oldham

**Comment by brouille** [comment]
Marilyn and Marc
Please consider this
Luc

**Comment by MFavreau** [comment]
I believe it should be hyphenated, since it is not a real primrose. But again, no impact on the French names, so I will let Marilyn decide.

**Comment by manions** [comment]
Corrected, many thanks. Can someone send me the FNA manuscript please as more review is needed of the English vernaculars - thanks.
