### ISSUE TITLE
Cerastium pumilum common name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2744]
http://data.canadensys.net/vascan/taxon/4272?lang=en

European chickweed seems an odd English common name for Cerastium pumilum since quite a few of our Cerastium species are introduced from Europe.  I see that NatureServe also uses this common name, but I prefer Curtis' mouse-ear chickweed, which is the common name currently used by NHIC.

Mike Oldham

**Comment by brouille** [comment]
Marilyn (and Marc)
Please consider this.
Luc

**Comment by MFavreau** [comment]
Marilyn:
The name « sticky mouse-ear chickweed » is used in FNA5, but it is based on the synonym C. glutinosum.

**Comment by manions** [comment]
Review completed with my decision to change English vernacular to 'dwarf mouse-ear chickweed' (which is widely used for this species). The common name of 'European chickweed' is widely used (not just by NatureServe) and kept as an alternate name. The Ontario name of 'Curtis' m-e chickweed' is not widely used. The name 'sticky m-e chickweed' (FNA) is also used fro C. glomeratum (FNA). There is also the name of 'small chickweed' in use (NY). All of these names are listed.
