### ISSUE TITLE
Correction in authorities of synonym Phegopteris robertianum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2745]
Re: http://data.canadensys.net/vascan/taxon/5417?lang=en

VASCAN lists Phegopteris robertianum (Hoffmann) Fée as a synonym of Gymnocarpium robertianum

But the authors of this combination should be Phegopteris robertianum (Hoffmann) A.Braun ex Ascherson 

IPNI lists it as Phegopteris robertiana A.Br.; Aschers.
Tropicos has Phegopteris robertianum, with several different authors.
I checked Fée's publication online {Mém. Foug., 5. Gen. Filic. 1850, pg. 243.} and he makes no mention of P. robertiana, but under  Phegopteris he does list: -- calcarea (Polypod., Hoffm.#).  
It does not appear that he made any combination using the epithet robertianum.

Ascherson (1864) legitimized A. Braun's unpublished name: Phegopteris robertianum (Hoffm.) A.Br.,(ined.).   in his Flora der Provinz Brandenburg (p. 920).  He lists P. calcareum Sm. as a synonym.

**Comment by brouille** [comment]
http://worldplants.webarchiv.kit.edu/ferns/ has Phegopteris robertiana (Hoffm.) Ascherson
 -um or -a ? when one looks at the list of spp in this genus, it should be -a 
corrected - but who to cite for the authors? not one db seem to have the right one
LB

**Comment by sjmeades** [comment]
Perhaps this is a question for Kanchi Gandi?
