### ISSUE TITLE
misspelling of synonym Dicksonia punctilobula

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2746]
Re: http://data.canadensys.net/vascan/taxon/5347

there is a misspelling in the synonym: Dicksonia punctilobula Michaux
This should be either Nephrodium punctilobulum Michx. (which you already have listed in synonymy), 
- or Dicksonia punctiloba (Michx.) Hooker, but since Michaux spelled it differently, Dicksonia punctiloba Hooker is probably correct; maybe we could consult Kanchi Gandhi on this?

Hooker (1840, pg. 264) lists Nephrodium puntilobum Mx. and Aspidium punctilobum WIlld. as synonyms of Dicksonia pilosiuscula Willd.  In 1846 (Sp. Fil.), he published Dicksonia punctiloba Hook., citing Nephrodium punctilobum Michx. (Flor. Bor. Am. ii, p.268) as the basionym, but misspelled the specific epithet as punctiloba, rather than punctilobula.  Later, Gray (1848) corrected the spelling: Dicksonia punctilobula (Michx.) Hook. – in A. Gray 1848, without noting it had been misspelled in Hooker's publication, but I don't think he meant to make a new combination. 

I think this is why Gray's corrected spelling has appeared in the lit  in the past, but it is not included in IPNI, since it was never actually published as a new name.  Tropicos attributes the spelling Dicksonia punctiloba to A.Gray, but again, Gray included it as Dicksonia punctilobula (Michx.) Hook.

**Comment by brouille** [comment]
removed the offending synonym - not significant
LB
