### ISSUE TITLE
Medicago sativa confirmed in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#275]
[Originally posted on GoogleCode (id 2543) on 2015-03-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5835?lang=en

<b>What data are incorrect or missing?</b>
confirmed for NWT (not doubtful)

<b>What data are you expecting instead?</b>
add NWT (as Introduced)

<b>If applicable, please provide an authoritative source.</b>
Michael Oldham's 2006 survey located both M. falcata and M. sativa (which he reported as M. sativa ssp. sativa).
Specimens deposited at TRTE, DAO and mjo.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:53Z]

subsp.sativa, introduced - I left the source as is.

Note that there are 2 subspp. in Canada
