### ISSUE TITLE
Sambucus racemosa var. pubens in Labrador

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2752]
Re: http://data.canadensys.net/vascan/taxon/2442

Labrador is not listed in the range for Sambucus racemosa subsp pubens var. pubens.

We had this information in the NL checklist: [The first Labrador report was made by C. Hanel, T. Keats, and R. Belbin in 2004 from Black Bay Brook, near Red Bay, seLab.] 

Claudia has 2 entries in the ACCDC data and her collection # is CH 040830-23

**Comment by brouille** [comment]
What herbarium are they deposited at?
This is the required source to document the entry
Thanks
Luc

**Comment by brouille** [comment]
herbarium?

**Comment by brouille** [comment]
Labrador listed in S. racemosa
