### ISSUE TITLE
Invalid synonym: Ptarmica integrifolia Gilib.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2755]
Re: http://data.canadensys.net/vascan/taxon/2770

Gilib. published the name Ptarmica integrifolia in Flora Lituanica Inchoata i., 1782.

All names published in this work are considered invalid.  See IPNI Pubication Comments:
Comments:
Flora Lituanica Inchoata (2 vols): this is one of the suppressed works; names at the ranks of species and infraspecies in this work are not treated as validly published (vide Melbourne Code Appendix VI, p. 448)

**Comment by brouille** [comment]
Ptarmica integrifolia nom. illeg.
also added sources to synonyms
LB
