### ISSUE TITLE
illeg. homonym - synonym of Tanacetum vulgare

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2757]
Re: http://data.canadensys.net/vascan/taxon/3605

the synonym Chrysanthemum vulgare (L.) Bernhardi (misspelled here as Bernahrdi) 1800 is an illegitimate homonym,  Gatereau published the same combination in 1789, now considered a synonym of Leucanthemum vulgare Lam.

**Comment by brouille** [comment]
It is interesting that Chrysanthemum vulgare (Lam.) Gatereau is itself a nom. illeg. superfl.  according to TROPICOS (also added for interest to Leucanthemum vulgare)
correction done
LB
