### ISSUE TITLE
error in synonym name: Erigeron uniflorus (DC.) B.Boivin

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2759]
re: http://data.canadensys.net/vascan/taxon/3094

The synonym Erigeron uniflorus (de Candolle) B. Boivin, nom. inval.
should read Erigeron uniflorus var. unalaschkensis (de Candolle) B.Boivin, nom. illeg.
Since B.Boivin made this combination in 1972, well after Ostenfeld's 1923 publication.  You have Ostenfeld's name listed, but the variety was deleted from the entry attributed to B.Boivin.
Linnaeus was the author of Erigeron uniflorus.

**Comment by brouille** [comment]
This is not the error you believe. The rank of the name was at species instead of variety. The varietal name is entered but cannot be seen.

I have to ask the database manager to make this change because I do not have access, but it will be done.
Luc

**Comment by brouille** [comment]
Jeremy

Svp, faire le changement suivant dans la base de données de VASCAN:

taxon/30379 [syn parent taxon/3094] : changer rank "species" pour "variety"

Cela devrait corriger la situation rapportée ci-haut
Luc

**Comment by JeGoi** [comment]
Done. Merci

**Comment by brouille** [comment]
correction completed. Will appear at next publication
LB
