### ISSUE TITLE
Dracocephalum thymiflorum confirmed in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#276]
[Originally posted on GoogleCode (id 2544) on 2015-03-21]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6371?lang=en

<b>What data are incorrect or missing?</b>
NWT is missing

<b>What data are you expecting instead?</b>
add NWT

<b>If applicable, please provide an authoritative source.</b>
Michael Oldham's 2006 survey
Specimens at DAO, MICH, mjo

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:51Z]

Introduced as all other Canadian entries.
