### ISSUE TITLE
Status and placement of Erigeron annuus 'var' septentrionalis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2760]
re: http://data.canadensys.net/vascan/taxon/3126

Erigeron annuus var. septentrionalis (Fernald & Wiegand) Frey, Baltisberger & Edwards is listed in synonymy of Erigeron annuus subsp. septentrioalis; however, on reading the publication, the authors do not seem to ba making a new combination, they are saying that var. septentrionalis has been misplaced and should be included as a synonym of Erigeron annuus.   If their work is accepted, then it appears that E. strigosus var. septentrionalis (Fernald & Wiegand) Fernald and all of its synonyms should be moved to E. annuus. 
 See: Frey, D., M. Baltisberger, and P.J. Edwards.  2003. Cytology of Erigeron annuus s.l. and its consequences in Europe. Bot. Helv. 113/1:1-14.
They are not publishing a new variety, just trying to move this taxon to where they think it belongs, as a synonym of E. annuus.  Note also that IPNI does not include this species and Tropicos provides no publication information, but ranks it with 2 asterisks, which means an invalid name.

[Frey-Baltisb-Edwards_2003_Cytology-Erigeron-annuus.pdf](https://github.com/Canadensys/vascan-data/files/1671612/Frey-Baltisb-Edwards_2003_Cytology-Erigeron-annuus.pdf)
If the file I attached does not appear, I'll send it by e-mail.

**Comment by brouille** [comment]
Name erased from the list of synonyms.

I am not currently moving the taxon under annuus  because I reviewed all our NA material of this var. and it appears to fit in E. strigosus. I have to read more from Noyes who studied the complex more completely in NA.

LB

**Comment by AlexBERGER0N** [comment]
I agree with Luc's cautious approach.
