### ISSUE TITLE
correction in authority of synonym: Solidago multiradiata var. parviceps

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2761]
re: http://data.canadensys.net/vascan/taxon/3462

The authority of the synonym Solidago multiradiata var. parviceps Aiton 
- should be var. parviceps Fernald

See IPNI and Tropicos.  Aiton was the author of the species, not the var.

**Comment by brouille** [comment]
an error: the author was not corrected from that of the parent at entry
now corrected
LB
