### ISSUE TITLE
minor change in authority of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2762]
Re: http://data.canadensys.net/vascan/taxon/3164 

For the synonym Eupatorium trifoliatum var. foliosum (Fernald) O.A. Farwell, 
Farwell is the only person listed in IPNI authors with that name, so using his initials, O.A., is unnecessary.

**Comment by brouille** [comment]
A remnant of the time when I added initials to all names. Removed now. Unfortunately, the editing tool in VASCAN does not allow global changes for authorities
Luc
