### ISSUE TITLE
invalid synonym: Antennaria margaritacea (L.) R.Br.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2763]
Re: http://data.canadensys.net/vascan/taxon/2797

Antennaria margaritacea (Linnaeus) R. Brown

R. Brown's 1817 publication was invalid (nomen nudum).  DeCandolle republished it as R.Br. ex DC. in 1838, but Sweet had already validly published this combination in 1926, making his combination the correct name to use. 
Antennaria margaritacea (Linnaeus) Sweet (1926): see Tropicos+IPNI, The Plant List, and Global Composite Checklist
https://compositae.landcareresearch.co.nz/?Page=NameDetails&NameId=993FFD5E-B12C-484A-9F6B-7B2687543A69

**Comment by brouille** [comment]
modified authorities to (L.) Sweet - used IPNI as source
