### ISSUE TITLE
Status of synonym Iva monophylla

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2764]
Re: http://data.canadensys.net/vascan/taxon/2792

Vascan has: Iva monophylla Walter nom. rej., citing Tropicos as the source.

HWR, neither Tropicos, IPNI, nor the Plant List indicate that this name was rejected.

**Comment by brouille** [comment]
This was probably a slip at entry from the menu, where Walter and Walter nom. rej. are adjacent
Corrected
LB
