### ISSUE TITLE
misplacement of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2766]
re: http://data.canadensys.net/vascan/taxon/16356

Oxytropis uralensis var. minor Hooker  is the basionym of Oxytropis campestris var. minor (Hook.) S.L.Welsh, so should be included as a synonym under that variety, rather than var. terrae-novae (Fernald) Barneby.

**Comment by brouille** [comment]
already corrected following FNA ms
see #VASCAN-plants tweets on Canadensys
LB
