### ISSUE TITLE
spelling error in authority

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2768]
Re: http://data.canadensys.net/vascan/taxon/30562

Should be G.L. Gusarova, not Gussarova

Galina Gusarova spells her name with 1 's'.  IPNI authors has it correct, but the JBRIT paper spelled it with 2 's's.  In her e-mail address, given in the paper, she uses only one 's'.  
See her webpage: http://www.nhm.uio.no/english/about/organization/research-collections/people/galinag/ 
This is the 2nd name in IPNI authors with that surname, so her initials are needed in the authority.

**Comment by brouille** [comment]
corrected
TX
L
