### ISSUE TITLE
Epilobium clavatum not in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#277]
[Originally posted on GoogleCode (id 2546) on 2015-03-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6768?lang=en

<b>What data are incorrect or missing?</b>
E. clavatum is listed for NWT (no reference)

<b>What data are you expecting instead?</b>
remove NWT

<b>If applicable, please provide an authoritative source.</b>
There is no evidence, that I can find, for E. clavatum occurring in NWT. I searched the following herbaria online with negative results: CAN, UA, UBC, V, CPNWH (consortium). Also no specimens at DAO. Any literature I have consulted also do not report this species.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:45Z]

REmoved totally
L
