### ISSUE TITLE
typo in authority of subsp. cruentifoium (Hieracium lachenalii)

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2772]
Re: http://data.canadensys.net/vascan/taxon/30729

The name Dahlsted in both entries below should be **Dahlstedt**, as shown in Euro+Med's treatment (as Dahlst., the accepted abbrviation for his name).  Also, IPNI Authors has no Dahlsted listed.

Hieracium lachenalii subsp. cruentifolium (Dahlsted & Lübeck) Zahn - should be (Dahlstedt & Lübeck) Zahn
Hieracium cruentifolium Dahlsted & Lübeck - should be Dahlstedt & Lübeck

**Comment by brouille** [comment]
corrected 
thanks
L
