### ISSUE TITLE
Polygalaceae references as FNA 2015 incorrect

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#2773]
Throughout the Polygalaceae (Scientific names and synonyms), the reference of FNA 2015 is frequently used and is incorrect. The FNA volume dealing with Polygalaceae isn't published yet, however a provisional publication might be available?

**Comment by brouille** [comment]
Indeed, at this time it should be FNA Ed. Comm., in prep. c
All corrected
Luc
