### ISSUE TITLE
genus change for North American Orobanche

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2774]
http://data.canadensys.net/vascan/taxon/1488

Wonder if you plan on recognizing Aphyllon?

Mike

[Schneider 2016_Resurrection of the genus Aphyllon for New World broomrapes (Orobanche s.l., Orobanchaceae).pdf](https://github.com/Canadensys/vascan-data/files/1717039/Schneider.2016_Resurrection.of.the.genus.Aphyllon.for.New.World.broomrapes.Orobanche.s.l.Orobanchaceae.pdf)

**Comment by brouille** [comment]
not decided yet. FNA ms has not adopted this, though the authors are aware of the suggestion. Need evaluation
L

**Comment by brouille** [comment]
Aphyllon recognized vs FNA ms (incl. in Orobanche) because of expertise of author and current trends in Orobanchaceae.
Modification made, will appear at next publication. See also #VASCAN_plants tweet
LB
