### ISSUE TITLE
Labrador range of Huperzia continentalis is likely historic

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2775]
Re: http://data.canadensys.net/vascan/taxon/30495?lang=en

Unless you have more information from a review of Labrador specimens, Huperzia continentalis is known from only Cape Chidley.  Testo et al reported the following NL specimens, but the Button Islands site is actually in Nunavut, leaving only the Cape Chidley collection from 1894.  Also note that Testo mispelled Dan Brunton's name as Britton in connection with this 2014 collection from Little Quirpon (McIntosh is Dan's wife).  If only the 1894 specimen is known from Lab., this should be considered an SH, but i fyou have more recent reports, please let me know so I can properly evaluate the S-rank.

From Testo et al. 2016: Newfoundland: Button Islands, Lacie Island, granitic slopes, 31 Jul 1934, Potter & Brierly 2013 (GH); Ekontiasuk, Cape Chudleigh, 20–30 Aug 1894, Schmitt 315 (GH); Northern Peninsula, Little Quirpon, 515 m southwest of seashore road, 51.5765°N, 55.4477°W, 62 m, 6 Aug 2014, Britton (should be Brunton) & McIntosh 18729 (VT).

**Comment by brouille** [comment]
VASCAN does not attribute conservation ranks to species. This is left to CDCs and NatureServe.

For native species, they are considered present unless they have been formally declared extirpated, which is not the case here.

Luc
