### ISSUE TITLE
Status of Cuscuta campestris in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2776]
Referring back to Feedback issue 501, several years ago, re: reports of Cuscuta pentagona in NL,

The report refers to an old Fernald speciemsn collected in Topsail that was annotated as Cuscuta campestris, but no further specimens had been found, so you had decided to either exclude it or list is a ephemeral, which is how we've got it listed in the checklist.  But on VASCAN, NL is included in it's natural range.  Do you have new reports of Cuscuta campestris form NL, or was NF included in the range by FNA authors based on this old report?

**Comment by brouille** [comment]
The FNA author put a ? besides Nfld.
But Costea 2008 did not clearly (source cited) - I am changing this.
I am excluding it (as I should have done all along) - it will be excluded in our new list, right?
LB
