### ISSUE TITLE
Status of Thermposis montana var. ovata in NL.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2778]
Re: http://data.canadensys.net/vascan/taxon/26580

A single naturalized population of this species had existed in St. John's on a vacant lot, but this lot has since been excavated to build town houses, so this species no longer exists in NL.  If FNA MS in prep. includes this from NL, the authors should be told that this pop. no longer exists.  I recommend changing the NL status from introduced to excluded or absent.

**Comment by brouille** [comment]
Will you exclude it also in the Nfld & Labr list, so that eventually I can cite a source?
L
