### ISSUE TITLE
Centaurium erythraea in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2779]
re: http://data.canadensys.net/vascan/taxon/5985?lang=en

Henry Mann reported this new addition to the NL Flora.  I'll try to find out collection data, but the specimen is at Grenfell (SWGC) in Corner Brook.  The plant was collected in 2016 in Stephenville.
See pg. 21 of this volume of Sarracenia for the article (Butt, et al. 2017)
http://www.wildflowersocietynl.ca/page9/files/Sarracenia_Vol_22-2.pdf

**Comment by brouille** [comment]
added with source Sarracenia
LB
