### ISSUE TITLE
Berberis sensu lato taxonomy and nomenclature

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2780]
http://data.canadensys.net/vascan/taxon/893

This recent article in Taxon has implications for several Canadian Berberis s.l. species, e.g. B. repens and B. aquifolium are placed in Mahonia.

Yu, C.-C., and K.-F. Chung. 2017. Why Mahonia? Molecular recircumscription of Berberis s.l., with the description of two new genera, Alloberberis and Moranothamnus. Taxon 66 (6): 1371–1392.
--

Mike Oldham
[Yu & Chung 2017_Why Mahonia; Molecular recircumscription of Berberis s.l., with the description of two new genera, Alloberberis and Moranothamnus.pdf](https://github.com/Canadensys/vascan-data/files/1719677/Yu.Chung.2017_Why.Mahonia.Molecular.recircumscription.of.Berberis.s.l.with.the.description.of.two.new.genera.Alloberberis.and.Moranothamnus.pdf)

**Comment by brouille** [comment]
already effected - will appear at next publication
LB
