### ISSUE TITLE
rank error in synonym of Stuckenia filiformis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2782]
Re: http://data.canadensys.net/vascan/taxon/8338

Potamogeton marinus var. alpinus Blytt was published as forma alpinus Blytt in 1861

See IPNI

**Comment by brouille** [comment]
http://www.tropicos.org/Name/100246103 has Potamogeton marinus var. alpinus Blytt 
also in Kaplan 2008 A Taxonomic Revision of Stuckenia (Potamogetonaceae) in Asia, with Notes on the Diversity and Variation of the Genus on a Worldwide Scale. Folia Geobotanica 3: 159–234
citing:
= Potamogeton marinus var. alpinus Blytt, Norges Fl. 1: 370. 1861.
    Type: [material from several sites in Norway cited in the prologue, the following specimens were studied:] “Potamogeton filiformis Pers. Forma: alpinus Blytt, Lomsvand i Lom, Norvegia, 1200’ inf. mare, leg. N. Moe, comm. I. Baagøe” (syntype: C-Baagöe); [label 1:] “E museo botanico Christianiensi, Norvegia: Lomsvand i Lom, 1200’, N. Moe” [label 2:] “Potamogeton marinus β alpinus Blytt” (syntype: C-Baagöe).

now, whether β is a form or a var. may be subject to discussion among specialists

So your comment is not as straightforward. Need to consult.
LB

**Comment by brouille** [comment]
IPNi provides the authorship for var. marinus as (Blytt) Asch. & Graebn. -

You were correct concerning the forma, but I can simply correct the authors and the syn will be OK. I cannot add forms in VASCAN

Luc
