### ISSUE TITLE
Ulmus parvifolia in ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2783]
http://data.canadensys.net/vascan/taxon/9427?lang=en

Suggest excluding Ulmus parvifolia from ON (and Canada).

This species is included in VASCAN based on Newmaster et al. (1998), however this is one of several ornamental species included in this publication that are not known outside cultivation in the province.  A literature report (Gaiser and Moore 1966) was excluded by Scoggan (1978-1979) since there was no indication the species had spread from original plantings.  Morton and Venn (1990) rejected the species from their Ontario checklist and FNA Vol. 3 does not include the species for Ontario.  NHIC has this species on their "excluded species" list as reported from Ontario but without documentation that it is or was naturalized in the province.

Mike Oldham

**Comment by brouille** [comment]
Excluded as cultivated, source Scoggan

Thanks for the information. These are difficult to catch
Luc
