### ISSUE TITLE
Can. range of Ranunculus confervoides

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2784]
Re: http://data.canadensys.net/vascan/taxon/19649?lang=en

Ranunculus confervoides is not listed from Canada in VASCAN's range map.

However, the Pan Arctic Flora lists Canada, including Labrador, in its range:
http://nhm2.uio.no/paf/3612#paf-361209 
Also, reading Drew's original description of R. trichophyllus includes a var. eradicatus (now a synonym of R. confervoides), with several locations noted from Nfld. 

Also, Fernald describes the range as Greenland and Labrador to Alaska, S to Nfld., Anticosti I., and Gaspe Pen. Que., Ung. and Wyo. (Er.).

Unless the synonymy is all wrong, NL (and other provinces) should be included in the range of Ranunculus confervoides.

**Comment by manions** [comment]
Check Wiegleb et al 2017 which is listed as the reference for this taxon.  "Records of this species from Asia and North America belong to small forms of polymorphic R. trichophyllus."
Hope this helps
