### ISSUE TITLE
Solanum revisited : need revision of vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2786]
The FNA Solanum manuscript has been sent to regional review and significant changes in taxonomy in VASCAN result from this (see attached document). The changes are already implemented in VASCAN. But vernacular names need to be revised in some cases:
Solanum emulans - replaces ptychanthum (misapplied, in fact a syn of americanum) - names need to be assessed
Solanum nitidibaccatum - replaces  physalioides (misapplied) and saccharoides (misapplied) - I removed all vernaculars pertaining to these taxa and retained names that appear to pertain to this taxon fide FNA ms - but this needs to be validated by you

The situation with Solanum is complex because names have been bandied about seriously.

Thanks
Luc

[Solanum02rev_ECAN.docx](https://github.com/Canadensys/vascan-data/files/1763408/Solanum02rev_ECAN.docx)

**Comment by manions** [comment]
Review of English vernaculars completed

**Comment by MFavreau** [comment]
French names verified and corrected.

Marilyn : please have a look at the English names for S. nitidibaccatum : none is yet considered as "accepted".

Marc

**Comment by manions** [comment]
fixed, thanks!
