### ISSUE TITLE
New Potentilla species

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2787]
Marilyn and Marc:

A new Potentilla species, Potentilla hudsonii Ertter, was just described from Canada-Montana (see attached). Vernacular names are required. The obvious is : Hudson's cinquefoil, potentille de Hudson
since it was name for the Hudson fellow mentioned in the text. But I leave it to you nonetheless.
Luc

[Ertter 2018_Two new North American Potentilla sect. Rubricaules (Rosaceae).pdf](https://github.com/Canadensys/vascan-data/files/1781274/Ertter.2018_Two.new.North.American.Potentilla.sect.Rubricaules.Rosaceae.pdf)

**Comment by manions** [comment]
English vernacular added, thanks

**Comment by MFavreau** [comment]
Nom français proposé par Luc ajouté.
