### ISSUE TITLE
correction à la base de données VASCAN : Solanum

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2788]
Jérémie
 
En faisant des corrections complexes au genre Solanum dans VASCAN à partir du manuscrit de FNA, j’ai effacé par erreur le taxon Solanum sarrachoides auct. non Sendtner ex Martius http://data.canadensys.net/vascan/taxon/21402, qui était alors synonyme de S. physalifolium Rusby, un taxon que je vais exclure.
 
Serait-il possible de le récupérer dans la version antérieure sauvegardée et de le placer sous le (nouveau) taxon suivant svp :
Solanum nitidibaccatum
http://data.canadensys.net/vascan/taxon/31287
 
Merci
Luc

**Comment by JeGoi** [comment]
Bonjour,
C'est mis à jour.
