### ISSUE TITLE
status of Solidago rugosa in LB?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2789]
I have a report of a specimen of Solidago rugosa, collected in 1999 by Stu Hay, Luc, and the rest of the NL Rare plant group from Pinware Provincial Pk, with the following info:  Dune at E end of barachois between S shore of river and ocean, E of picnic tables.  Habitat: Dune slack in between barachois and ocean dominated by Calamagrostis canadensis, Leymus mollis and in underbrush, Cornus ssp. and Vaccinium vitis-idaea.

Do you have a copy of this specimen at MT?  The record doesn't provide an herbarium name.

**Comment by brouille** [comment]
It is probably not rugosa. I sent it to Semple and is probably back somewhere at MT. But never got a det at the time.

Luc

De : sjmeades <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : mercredi 21 mars 2018 14:55
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] status of Solidago rugosa in LB? (#2789)


I have a report of a specimen of Solidago rugosa, collected in 1999 by Stu Hay, Luc, and the rest of the NL Rare plant group from Pinware Provincial Pk, with the following info: Dune at E end of barachois between S shore of river and ocean, E of picnic tables. Habitat: Dune slack in between barachois and ocean dominated by Calamagrostis canadensis, Leymus mollis and in underbrush, Cornus ssp. and Vaccinium vitis-idaea.

Do you have a copy of this specimen at MT? The record doesn't provide an herbarium name.

**Comment by brouille** [comment]
The Solidago collected by our group in Labrador that you think was rugosa (it was hairy indeed) is Solidago lepida subsp. fallax var. fallax
Luc
