### ISSUE TITLE
exclude Bidens bipinnata from ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2791]
http://data.canadensys.net/vascan/taxon/2929?lang=en

Reports of Bidens bipinnata from Ontario (e.g. Newmaster et al. 1998) are based on a specimen (W. Botham 177 at CAN) which was revised to B. pilosa.

Mike Oldham

**Comment by brouille** [comment]
excluded misidentification CAN
LB
