### ISSUE TITLE
Change Helianthus nuttallii ssp. rydbergii to introduced for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2792]
http://data.canadensys.net/vascan/taxon/3200?lang=en

Although listed as native to Ontario by Morton and Venn (1990) we are aware of no records from natural habitats in Ontario and considerable recent fieldwork in areas of northwestern Ontario near the Manitoba border, where native populations might be expected, have not found the species in natural habitats.  Not mapped from Ontario by Long (1966) or Heiser et al. (1969) or listed for the province by Scoggan (1978-1979); there are at least two recent records from northwestern Ontario, both along railway tracks.

Mike Oldham

**Comment by brouille** [comment]
change made
LB
