### ISSUE TITLE
Epilobium x wisconsinense add ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2793]
http://data.canadensys.net/vascan/taxon/6795?lang=en

Collected in Ottawa by M. O. Malte in 1912 (CAN) and initially identified as Epilobium coloratum.  Identified in 1975 by N. J Purcell as E. x wisconsinense, and identification agreed with by P. C. Hoch in 1979. Not listed for Ontario by Scoggan (1978-1979), Morton and Venn (1990) or Newmaster et al. (1998).

Mike Oldham

**Comment by brouille** [comment]
added because it is native - otherwise I would have had to exclude it as old report - also, it is a hybrid, which by definition may be episodic in the flora
LB
