### ISSUE TITLE
elevate Arabis pycnocarpa var. adpressipilis to species?

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2794]
http://data.canadensys.net/vascan/taxon/3893?lang=en

elevate Arabis pycnocarpa var. adpressipilis to species following Al-Shebaz (2017)?

Mike Oldham
[Al-Shebaz 2017_Nomenclatural Adjustments in North American Arabis , Chinese Hilliella , and South American Neuontobotrys (Brassicaceae).pdf](https://github.com/Canadensys/vascan-data/files/1843927/Al-Shebaz.2017_Nomenclatural.Adjustments.in.North.American.Arabis.Chinese.Hilliella.and.South.American.Neuontobotrys.Brassicaceae.pdf)

**Comment by brouille** [comment]
Arabis adpressipilis accepted and Arabis pycnocarpa var. adpressipilis in syn
Arabis pycnocarpa var. pycnocarpa is syn of Arabis pycnocarpa [no var. required now]
Thanks
LB
