### ISSUE TITLE
Add var. williamsii (Fernald) Shiels & Monfils for ON and CA

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2795]
http://data.canadensys.net/vascan/taxon/27887?lang=en

Specimens of Schoenoplectiella purshiana var. williamsii (Fernald) Shiels & Monfils from Niagara Region, Ontario, are at CAN and TRT.  Specimens were identified by S. Galen Smith and Derek Shiels (both of whom have worked on the genus).

Mike Oldham

**Comment by brouille** [comment]
I do not know why G. Smith, who wrote the FNA treatment, missed so many Canadian provinces that he had seen and annotated while visiting (we had a few cases at MT)
added with source TRT
Luc

**Comment by brouille** [comment]
Marilyn and Marc
Please add vernacular names to this var. that I added to VASCAN
Luc

**Comment by MFavreau** [comment]
Nom français ajouté.
Fernald (1950, p. 258) précise que l'épithète _williamsii_ honore un certain E.F. Williams.

**Comment by manions** [comment]
English vernacular added
