### ISSUE TITLE
Camelina sativa change to INT from Ephemeral for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2796]
http://data.canadensys.net/vascan/taxon/3942?lang=en

Listed as Ephemeral for ON based on Newmaster et al. (1998), but as Introduced in other Canadian provinces.  Multiple Ontario records and there is nothing in Newmaster et al. (1998) to suggest that the species is ephemeral in ON.

Mike Oldham

**Comment by brouille** [comment]
the eph was due to Morton (no recent collection in Ont)
changed to int
the source now is Newmaster & Ragupathi 2005
I update the source after checking for Ont and BC
Luc
