### ISSUE TITLE
remove Carex x involuta for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2797]
http://data.canadensys.net/vascan/taxon/15481?lang=en

Newmaster et al. (1998) is listed as the source for the occurrence of Carex x involuta in ON, but this reference makes no mention of this hybrid (or its synonyms).  Boivin (1992; Les Cyperacees de l'est du Canada) states that the Ontario specimen was revised to C. rostrata.

Mike Oldham

**Comment by brouille** [comment]
NEwmaster et al. list it as a name without information.
I will exclude it as misidentification fide Boivin 1992
