### ISSUE TITLE
change EXT to EXP for extirpated taxa?

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2798]
http://data.canadensys.net/vascan/taxon/5121?lang=en

Great to see Extirpated species now differentiated in VASCAN.  Suggest changing EXT to EXP, since EXT is the official COSEWIC abbreviation for Extinct vs. EXP which is the official COSEWIC and SARA abbreviation for Extirpated.  These two abbreviations are used in other legal lists (e.g. Ontario's Species at Risk in Ontario list) and it may avoid confusion to use the same abbreviation for Extirpated (don't think any Canadian vascular plants are extinct?).

Mike Oldham

**Comment by brouille** [comment]
Mike

We did as you suggested. EXP is not data but merely a small image that appears in all windows where pertinent (user interface only). 

The change is done and will show at the next update of the interface (like tomorrow AM or even now).

Luc
