### ISSUE TITLE
Cephalaria alpina vs. gigantea in Canada

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2799]
http://data.canadensys.net/vascan/taxon/15747?lang=en

McNeill (1981, page 239-240; attached) examined material (at DAO) from Carleton, Quebec (reported in Scoggan 1979 as C. alpina), and specifically stated that it was C. gigantea and not C. alpina.  Only C. gigantea has been reported from Ontario (Morton and Venn 1990, 2000), as is the case for adjacent areas such as New York state (Werier 2017) and New England (Haines 2011). Cephalaria gigantea is not mentioned in VASCAN.

Mike Oldham
[McNeill 1981_Taxonomic, nomenclatural and distributional notes on Canadian weeds and aliens.pdf](https://github.com/Canadensys/vascan-data/files/1879450/McNeill.1981_Taxonomic.nomenclatural.and.distributional.notes.on.Canadian.weeds.and.aliens.pdf)

**Comment by brouille** [comment]
Cephalaria alpina excluded as misidentification for QC (removed Ont entry)
Cephalaria gigantea: excluded as old from QC, introduced Ont source: FOIBIS
Luc
