### ISSUE TITLE
round-leaved groundsel

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#28]
[Originally posted on GoogleCode (id 1380) on 2012-06-18]

http://data.canadensys.net/vascan/name/Packera%20obovata?lang=fr

La source pour le nom anglais recommandée est incorrecte.  Impossible!

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-21 13:06Z]

MArilyn:

Fred is correct: the source cited in the published VASCAN is implausible.

I removed it.

Could you please provide a proper source for the accepted vernacular, please?

thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:20Z]

corrected, thanks for finding this
