### ISSUE TITLE
Ranunculus hispidus (& var. caricetorum) not in NWT (revised specimen)

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#280]
[Originally posted on GoogleCode (id 2549) on 2015-03-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8530?lang=en

<b>What data are incorrect or missing?</b>
NWT listed

<b>What data are you expecting instead?</b>
remove NWT for R. hispidus &amp; R. hispidus var. caricetorum

<b>If applicable, please provide an authoritative source.</b>
I've tracked down the R. septentrionalis occurrence listed &amp; mapped in Porsild &amp; Cody 1980.
CAN261019 has been revised to R. macounii

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:43Z]

Marilyn:

note that when a sp. has infrasp., its distribution is calculated from the latter. THus is it not required to ask for changes to the species as it is automatic

Luc
