### ISSUE TITLE
change Dichanthelium commonsianum to Native for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2800]
http://data.canadensys.net/vascan/taxon/18364?lang=en

Two ON specimens verified by A.A. Reznicek.  "Very rare and local in dry, sandy, open ground of southwestern Ontario, with records from Essex, Norfolk, and Middlesex Counties. First collected in Ontario by Lorne E. James in 1952, ten miles southwest of London, Middlesex County (DAO, MT, OAC, TRT, UWO). Dore and McNeill (1980) mention an Elgin County collection, subsequently found to be misidentified (Argus et al. 1982-1987). A taxonomically complicated group." (NHIC database).

See attached from Ontario Rare Plant Atlas (ARVPO).

Mike Oldham
[Dichanthelium commonsianum var. euchlamydeum from Aiken et al 1984, 1987_Poaceae ARVPO.pdf](https://github.com/Canadensys/vascan-data/files/1883316/Dichanthelium.commonsianum.var.euchlamydeum.from.Aiken.et.al.1984.1987_Poaceae.ARVPO.pdf)

**Comment by brouille** [comment]
replace ? by native based on DAO
