### ISSUE TITLE
Dryopteris x uliginosa

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2801]
http://data.canadensys.net/vascan/taxon/5412?lang=en

Why is Dryopteris ×uliginosa (A. Braun ex Dowell) Kunze ex Druce not accepted for D. carthusiana X D. cristata?

Mike Oldham

**Comment by brouille** [comment]
It is because of the interpretation of the name: Dryopteris uliginosa was misapplied to the hybrid in question, which is why it is like a syn with auct. non ....

Luc
