### ISSUE TITLE
Exclude Epilobium ciliatum ssp. watsonii for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2802]
http://data.canadensys.net/vascan/taxon/6767?lang=en

A western taxon not listed for eastern North America in FNA draft.  Ontario report by Morton and Venn (1990) and Newmaster et al. (1998) presumably in error.

Mike Oldham

**Comment by brouille** [comment]
excluded - but I have no source for the exclusion. I do not know why it was reported either
Luc
