### ISSUE TITLE
Exclude Eriophorum triste from ON as Not documented

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2803]
http://data.canadensys.net/vascan/taxon/5267?lang=en

"Eriophorum triste is reported from Ontario by Morton and Venn (1990) and Newmaster et al. (1998), though the basis for these reports is not known (the latter is likely based on the former).  The species is not mapped from Ontario by Hulten (1968), Porsild and Cody (1980), or FNA Vol. 23 (2002), nor is it listed from the Hudson Bay Lowland by Riley (2003) or for Ontario by Scoggan (1978-1979).  We are considering its presence in Ontario unconfirmed until better documentation on its occurrence in the province is available." (NHIC database)

Mike Oldham

**Comment by brouille** [comment]
Excluded as not documented based on FNA (I have no other source I can see)
Luc
