### ISSUE TITLE
Euphorbia heterophylla change from Doubtful to Ephemeral or Excluded for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2804]
http://data.canadensys.net/vascan/taxon/27732?lang=en

There is at least one Ontario specimen, collected from along a railway line in SW Ontario.  "Collected along a railway line in Dunwich Tp. in 1971, Elgin County (W.G. Stewart #1696; UWO)." (NHIC database).  I know of no other Ontario records.

Mike Oldham

**Comment by brouille** [comment]
status changed to ephemeral
Luc
