### ISSUE TITLE
Euphorbia humistrata change from Introduced to Doubtful for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2805]
http://data.canadensys.net/vascan/taxon/5591?lang=en

Based on FNA it seems likely that Ontario specimens were misidentified.  "Reported by Scoggan (1978-1979) as a rare introduction along roadsides and railways in southern Ontario, from Lambton, Norfolk, York, Waterloo, and York Counties.  However not mentioned by Mulligan and Lindsay (1978) and no recently verified Ontario records known.  Not included for the province in FNA Vol. 12 (2016) where it is stated that Ontario reports had not been verified by the authors. It is possible that most or all Ontario specimens have been revised to other species (e.g. Euphorbia maculata). Not listed for adjacent Michigan, New York, or New England (Haines 2011; Reznicek et al. 2011; FNA Vol. 12, 2016; Werier 2017)." (NHIC database). 

Mike Oldham

**Comment by brouille** [comment]
status changed
LB
