### ISSUE TITLE
add ON for Euphrasia micrantha

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2806]
http://data.canadensys.net/vascan/taxon/29956?lang=en

Species included in VASCAN (and FNA draft) but not listed for any Canadian provinces or territories.  Listed for NS and ON in FNA draft.  Re. occurrence in Ontario: "Six Ontario specimens collected by M.J. Oldham have been identified as Euphrasia micrantha by Galina Gassarova (University of Oslo), specimens at MICH, O, NHIC, and TRTE. Records widely scattered, from Algoma, Rainy River, Thunder Bay, Timiskaming, and Wellington counties.  Status in Ontario poorly known due to confusion with other Euphrasia." (NHIC database).

Mike Oldham

**Comment by brouille** [comment]
added for Ont. introduced TRT
