### ISSUE TITLE
Euphrasia randii change from Native to Excluded for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2807]
http://data.canadensys.net/vascan/taxon/7015?lang=en

All Ontario specimens of E. randii examined by G. Gussarova belong to var. farlowii which is now elevated to species status in VASCAN.  E. randii in the strict sense is not known from ON (FNA draft).

Mike Oldham

**Comment by brouille** [comment]
Excluded due to misidentification - I will need a source eventually (FNA?)
LB
