### ISSUE TITLE
link in Lolium remotum not working

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2808]
http://data.canadensys.net/vascan/taxon/18603?lang=en

Link to Soreng et al. 2000+ not working.

Mike Oldham

**Comment by brouille** [comment]
Jérémie
Svp voir ce qui pourrait être le problème
Luc

**Comment by brouille** [comment]
Carole
Ce problème persiste. Quand tu pourras, pourrais-tu vérifier svp?
Luc

**Comment by CaroleSinou** [comment]
Luc, est-ce que ce lien est le bon ?
http://legacy.tropicos.org/Project/CNWG

**Comment by brouille** [comment]
Oui
Merci
Luc

De : CaroleSinou <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : mercredi 13 mai 2020 à 15:01
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Luc Brouillet <luc.brouillet@umontreal.ca>, Comment <comment@noreply.github.com>
Objet : Re: [Canadensys/vascan-data] link in Lolium remotum not working (#2808)


Luc, est-ce lien est le bon ?
http://legacy.tropicos.org/Project/CNWG

**Comment by CaroleSinou** [comment]
La référence a été modifiée dans la base de données.
