### ISSUE TITLE
Mercurialis annua change from Excluded to Ephemeral for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2809]
http://data.canadensys.net/vascan/taxon/5619?lang=en

Found relatively recently at two different sites in Hamilton (Rothfels 2005; attached).  "Collected from a wharf at Chatham, Chatham-Kent County, in 1890 by Cox, specimen at CAN (Scoggan 1978-1979).  Accepted as a valid Ontario species by Morton and Venn (1990) and Newmaster et al. (1998).  Mentioned from Ontario (based on old collections) by FNA Vol. 12 (2016) who state that it no longer appears to be an established species anywhere in eastern North America.  However the species has been recently found at two sites in Hamilton (Rothfels 2005; HAM).  Considered "excluded - Old report, not established" by VASCAN (Brouillet et al. 2010+)."

[Rothfels 2005_Significant 2004 Hamilton Study Area Plant Records from the Royal Botanical Gardens Herbarium (HAM)_Part I Families Aceraceae to Lamiaceae.pdf](https://github.com/Canadensys/vascan-data/files/1887380/Rothfels.2005_Significant.2004.Hamilton.Study.Area.Plant.Records.from.the.Royal.Botanical.Gardens.Herbarium.HAM._Part.I.Families.Aceraceae.to.Lamiaceae.pdf)

Mike Oldham

**Comment by brouille** [comment]
status changed and source added

Luc
