### ISSUE TITLE
Drymocallis convallaria not in NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#281]
[Originally posted on GoogleCode (id 2552) on 2015-03-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8799?lang=en

<b>What data are incorrect or missing?</b>
NWT is listed

<b>What data are you expecting instead?</b>
remove NWT

<b>If applicable, please provide an authoritative source.</b>
there isn't any evidence that Drymocallis convallaria is present in the NWT. It's not reported as occurring in FNA, nor found in any online herbaria searched (CAN, UBC, UA), plus no DAO specimens.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:39Z]

I removed the mention. There was no source anyway and I do not know why it was listed there anymore. Maybe it was as a result of BONAP, often with unsubstantiated reports.
Luc
