### ISSUE TITLE
change Oenothera fruticosa subsp. tetragona from Ephemeral to Absent for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2810]
http://data.canadensys.net/vascan/taxon/28435?lang=en

Considered native by Argus et al. (Ontario Rare Plant Atlas; attached) and NHIC (ranked SX), but no recent record, so Absent (native species) a better fit vs. Ephemeral (introduced species), though it is possible this species is also introduced in Ontario.

Mike Oldham
  
[Oenothera fruticosa ssp. glauca from Brunton et al 1987_Onagraceae ARVPO.pdf](https://github.com/Canadensys/vascan-data/files/1887829/Oenothera.fruticosa.ssp.glauca.from.Brunton.et.al.1987_Onagraceae.ARVPO.pdf)

**Comment by brouille** [comment]
Mike: was the species reported based on old specimens or is there ambiguity on the actual presence in the past of the taxon in Ont.? In other words, is the a case of wrong report (excluded based on absence of data) or is this a case of potential eradication from the province?
Luc

**Comment by brouille** [comment]
status changed to extirpated
