### ISSUE TITLE
recognition of Potamogeton berchtoldii ssp. berchtoldii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2811]
http://data.canadensys.net/vascan/taxon/30810?lang=en

Seems somewhat inconsistent to recognize P. gemmiparus at the species level, but not P. clystocarpus (endemic to TX, recognized at the species level by FNA and most other recent workers, including B. Hellquist [pers. comm. 2012)}.  If P. gemmiparus and P. clystocarpus (e.g. see attached) are recognized as full species, then no need for ssp. berchtoldii.

Mike Oldham
[Kaplan et al 2013_Revision of chromosome numbers of Potamogetonaceae, a new basis for taxonomic and evolutionary implications.pdf](https://github.com/Canadensys/vascan-data/files/1890318/Kaplan.et.al.2013_Revision.of.chromosome.numbers.of.Potamogetonaceae.a.new.basis.for.taxonomic.and.evolutionary.implications.pdf)
[Whittall et al 2004_Cryptic species in an endangered pondweed community (Potamogeton, Potamogetonaceae) revealed by AFLP markers.pdf](https://github.com/Canadensys/vascan-data/files/1890321/Whittall.et.al.2004_Cryptic.species.in.an.endangered.pondweed.community.Potamogeton.Potamogetonaceae.revealed.by.AFLP.markers.pdf)

**Comment by brouille** [comment]
Les et al 2009 (Syst. Bot.) placed gemmiparus as subsp. of berchtoldii, which molecular data support better than species status, even those of Kaplan. This is what VASCAN  is recognizing currently. I am not changing this.
Lux
