### ISSUE TITLE
Rosa x canadensis - remove ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2812]
http://data.canadensys.net/vascan/taxon/30359?lang=en

Lewis (2016) does not report Rosa x canadensis from ON and states only that the parental taxa both occur in ON.

Mike Oldham
[Lewis 2016_Nomenclatural Novelties in Rosa (Rosaceae) subgenus Rosa Recognized in North America.pdf](https://github.com/Canadensys/vascan-data/files/1895537/Lewis.2016_Nomenclatural.Novelties.in.Rosa.Rosaceae.subgenus.Rosa.Recognized.in.North.America.pdf)

**Comment by brouille** [comment]
correction made
