### ISSUE TITLE
change Rumex sanguineus from Ephemeral to Introduced for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2813]
http://data.canadensys.net/vascan/taxon/8222?lang=en

Listed as Ephemeral in VASCAN based on Newmaster et al. (1998), but there is nothing in this publication suggesting the species is ephemeral.  The species is locally established at several sites in SW Ontario and there are multiple specimens collected.  It does not seem to be ephemeral.

See also my comment on Rumex conglomeratus (to follow).

Mike Oldham

**Comment by brouille** [comment]
status changed to int
LB
