### ISSUE TITLE
Rumex conglomeratus change from Introduced to Doubtful for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2814]
http://data.canadensys.net/vascan/taxon/8207?lang=en

Reported from Ontario by Morton (1989), however specimens collected from the same site where R. conglomeratus was reported belong to R. sanguineus (det. A.A. Reznicek), leaving some doubt about the report of R. conglomeratus.  There is an earlier literature report of R. conglomeratus from Ontario [reportedly found at an orchard at Guelph, Wellington County, by W.H. Wright in 1918 (Montgomery 1957)] but if there is a supporting specimen I don't know if the identity has been checked vs. R. sanguineus.  The two species are quite similar.

Mike Oldham

[Morton 1989_The Clustered Dock, Rumex conglomeratus (Polygonaceae), in Canada..pdf](https://github.com/Canadensys/vascan-data/files/1895728/Morton.1989_The.Clustered.Dock.Rumex.conglomeratus.Polygonaceae.in.Canada.pdf)

**Comment by brouille** [comment]
Firstly, the old lit report would lead to exclusion unless there were more recent, credible reports.

The Morton 1989 paper has a photo of the specimen (deposited in JKM and therefore probably now at TRT). Did you or Tony look at the photo to determine whether it could be sanguineus? Or can we tell from this photo? There is a duplicate at DAO also that might be available for checking.

For the time being, I believe I will change the status to doubtful but change the source to Morton 89. Thanks for the pdf.

If you have more precise information, please let me know.
Luc
