### ISSUE TITLE
Trifolium incarnatum change from Excluded to Ephemeral for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2817]
http://data.canadensys.net/vascan/taxon/5922?lang=en

Multiple records, some recent.  "According to Montgomery (1957) this clover was at one time experimented as a pasture plant and for green manure, but it did not prove to be successful.  "A few plants are still found in fields and along roadsides" (Montgomery 1957).  Reported from Waterloo and Wellington Counties by Scoggan (1978-1979).  Collected from a roadside ditch in Durham Regional Municipality in May 2016 (M.J. Oldham #43290); possibly seeded or an impurity in grass seed.  Also known from Hamilton (Colin Chapman, pers. comm. 2016)." (NHIC database)

Mike Odlham

**Comment by brouille** [comment]
added
Luc
