### ISSUE TITLE
Yucca flaccida change from Excluded to Introduced for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2818]
http://data.canadensys.net/vascan/taxon/2458?lang=en

This is the only naturalized species of yucca in eastern Canada according to FNA Vol. 26 (2002) and most or all previous Ontario reports of Yucca filamentosa almost certainly belong here.  Occasionally escapes from cultivation in southern Ontario particularly in dry, sandy ground. Reported from 8 counties in the Carolinian Zone.

Mike Oldham

**Comment by brouille** [comment]
Mike
FOIBIS provides no positive information. Would there be a source to document introduction? And are the specimens established for good or are they ephemeral? I could put it as ephemeral recurrent also, if it is not self-perpetuating
Luc

**Comment by brouille** [comment]
still no source for flaccida in Ont.

**Comment by brouille** [comment]
Mike
I need a source for this. Herbaria?
Luc

**Comment by MichaelOldham** [comment]
You could use FNA as a source since they list it for ON. I'm sure there are specimens in herbaria though I don't have any specific specimen citations and haven't checked herbaria myself for this species (no specimens in NHIC herbarium).

mike

*********************************************************
Michael J. Oldham
Provincial Botanist
Ontario Natural Heritage Information Centre (NHIC)
Ministry of Natural Resources and Forestry
300 Water Street, 2nd Floor, North Tower
P.O. Box 7000 Peterborough, Ontario K9J 1C7, Canada
phone 705-755-2160; fax 705-755-2168
michael.oldham@ontario.ca<mailto:michael.oldham@ontario.ca>
NHIC requests: NHICrequests@ontario.ca<mailto:NHICrequests@ontario.ca>
NHIC web page: https://www.ontario.ca/page/natural-heritage-information-centre

________________________________

**Comment by brouille** [comment]
done
LB
