### ISSUE TITLE
Agropyron fragile - add as Introduced in ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2819]
http://data.canadensys.net/vascan/taxon/7369?lang=en

Catling et al. (2016) map Agropyron fragile from three southern Ontario sites, including Lambton and Simcoe Counties (P.M. Catling pers. comm. 2016).  A specimen from Port Arthur, Thunder Bay District (D. Lindsay 1230 in 1957, as A. sibiricum) is at DAO. Catling et al. (2016) also report putative hybrids with A. cristatum as occurring widely in Canada.

[Catling et al 2016_Major Invasive Alien Plants of Natural Habitats in Canada. 15. Agropyron cristatum.pdf](https://github.com/Canadensys/vascan-data/files/1898752/Catling.et.al.2016_Major.Invasive.Alien.Plants.of.Natural.Habitats.in.Canada.15.Agropyron.cristatum.pdf)

**Comment by brouille** [comment]
Agropyron fragile int Ont Catling et al. 2016

Will consider hybrid later
Luc

**Comment by brouille** [comment]
hybrid added
LB
