### ISSUE TITLE
Galium kamtschaticum in NWT (remove or doubtful)

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#282]
[Originally posted on GoogleCode (id 2553) on 2015-03-26]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9004?lang=en

<b>What data are incorrect or missing?</b>
NWT is listed for Galium kamtschaticum

<b>What data are you expecting instead?</b>
remove NWT or list as doubtful

<b>If applicable, please provide an authoritative source.</b>
I've found one revised specimen at DAO, previously listed as Galium kamtschaticum and revised to G. boreale. It was located at Franklin Mts.

However Porsild &amp; Cody 1980 map &amp; text indicate a location at the Mackenzie Delta. I've not been able to find any specimen (or revised specimen) I think this location is highly doubtful.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:38Z]

I left the record as doubtful until the remaining specimen can be dealt with, if ever. If it cannot be found out, we will have to exclude due to misidentification or lack of documentation.

Luc
