### ISSUE TITLE
Nom vernaculaire de Dianthus barbatus

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2820]
Bonjour

Je suis surpris que le nom Oeillet des poètes  ou oeillet de poète ne soit pas mentionné dans VASCAN.
J'ai vu dans Tela-Botanica que ce nom doit être évité, mais de nombreux ouvrages horticoles mentionnent ce nom commun.  Moi-même, c'est celui que j'utilise.

**Comment by MFavreau** [comment]
Normalement, ce nom devrait être réservé au _Dianthus plumarius_, également présent au Canada. Il ne devrait donc en aucun cas être utilisé comme nom accepté pour le _D. barbatus_. Cependant, pour éviter que l'information se perde, je l'ai ajouté aux deux espèces, comme synonyme.
