### ISSUE TITLE
Triodanis biflora (Ruiz & Pavon) Greene - addition à la flore du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2821]

**Comment by FredCoursol** [comment]
Salut
Addition selon FNAms pour l'Ontario.

**Comment by brouille** [comment]
Marilyn and Marc

Vernacular names in French and English required for Triodanis biflora. [FNA has Small Venus’s looking-glass]

Luc

**Comment by MFavreau** [comment]
French name added. I used « biflore » to have a simple traceable name, even though the name actually refers to the production of both cleistogamous and normal flowers (Fernald 1950)

**Comment by manions** [comment]
English vernacular added
