### ISSUE TITLE
Inula racemosa

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2823]
Marilyn and Marc

Inula racemosa is new to North America as an introduced (but apparently could be cultivated). It was found near Québec City by Dan Brunton. See Flora of China for a description.

It is reported from Europe, but sources do not provide vernacular names in English or French.

Luc

**Comment by MFavreau** [comment]
Noms français ajoutés.

Marc

**Comment by manions** [comment]
Hi - is Inula royaleana C.B. Clarke a synonym? as listed in the Flora of China. This would help with the English vernacular. Thanks
