### ISSUE TITLE
Smilax rotundifolia English common name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2825]
http://data.canadensys.net/vascan/taxon/9346?lang=en

Note that COSEWIC calls this Round-leaved Greenbrier (not greenbriar), a name I prefer for this species.  Generally the woody Smilax are called greenbriers and the herbaceous ones, carrionflowers.  Also VASCAN calls S. tamnoides, bristly greenbriar (more common spelling in my experience is greenbrier), so it seems odd to call one woody Smilax species a carrionflower and the other a greenbriar.  Also I think it is a good idea to be consistent with COSEWIC and SARA, as much as possible, for legally listed species.

Mike Oldham

**Comment by brouille** [comment]
I am reassigning this to Marilyn who curates English vernacular
Luc

**Comment by manions** [comment]
Hi, in this case the spelling can be either with an 'e' or an 'a' for this species. I have used the 'a' consistently, although I will change to the COSEWIC 'e' for that specific vernacular. I have tried to remain with more 'Canadian' spelling throughout, although in this case both the 'a' and 'e' are used in Canada for this species. Also to differentiate from 'brier' in curling.
