### ISSUE TITLE
Solidago petiolaris - variétés à modifier dans les synonymes.

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2826]
Salut
John reconnaît 3 variétés de Solidago petiolaris.  On ne devrait pas toutes les mettre en synonymie.

Semple, J.C., Y. Ma, U. Naik, N. Steenhof, and L. Tong.  2017.  A multivariate morphometric analysis of Solidago subsect. Thyrsiflorae (Asteraceae: Astereae).  Phytoneuron 2017-67: 1–35.

Voir aussi: https://uwaterloo.ca/astereae-lab/research/goldenrods/classification-and-illustrations/solidago-petiolaris

**Comment by brouille** [comment]
Var. petiolaris seule conservée avec les synonymes qui lui sont attribuables. Les autres noms ont été enlevés car non cités pour le Canada.
