### ISSUE TITLE
authority corrections in synonym of Brassica juncea

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2828]
re: Brassica juncea: http://data.canadensys.net/vascan/taxon/3921?lang=en

The synonym listed, Brassica integrifolia (West) O.E. Schulz, is a later isonym (1903) of Brassica integrifolia (H.West) Ruprecht (1860), which you could add.  Also, West's name needs his initial, H., as there are several Wests in IPNI authors.  See IPNI for more info.

**Comment by brouille** [comment]
corrected and added. There is inconsistency in TROPICOS with regard to synonymy of the legitimate synonym

Luc
