### ISSUE TITLE
correction in authority of Draba verna synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2829]
Re: Draba verna
http://data.canadensys.net/vascan/taxon/4034?lang=en

Draba boerhaavii (H.C.Hall) Dumort. – should be D. hoerhaavii (H.C.Hall) Raus (2014) – see IPNI
Dumort made his combination in Erophila: Erophila boerhaavii (H.C.Hall) Dumort. Florula Belgica 1827.
Hall also made the combination Draba boerhaavii in 1821, but did not accept the species name; this occurs in the same publication as his D. verna var. boerhaavii H.C.Hall, which is the basionym of other combinations of 'boerhaavii'.
IPNI lists the species combination as Draba boerhaavii H.C.Hall, nom. inval.

**Comment by brouille** [comment]
correction made
correction also suggested to FNA
L
