### ISSUE TITLE
Chrysosplenium iowense doubtful for NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#283]
[Originally posted on GoogleCode (id 2557) on 2015-03-27]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9228?lang=en

<b>What data are incorrect or missing?</b>
NWT is listed

<b>What data are you expecting instead?</b>
suggest to place NWT as doubtful

<b>If applicable, please provide an authoritative source.</b>
Kartesz 1999 included C. iowense for NWT based upon Moss 1959 (Flora of Alberta) followed by Packer 1983 (I don't have these documents to check).
Catling et al 2008 (BEN No. 400, 8Oct2008) mention that no specimens have been seen but the species occurs in northern Alberta. However accept the report for the species occurring in NT.
The closest AB location is south of Wood Buffalo NP, near Marguerite River Wildland.
I would suggest to place this species as doubtful for NWT, until a specimen is located. I've checked CAN, UA, CPNWH, and there isn't any DAO specimen.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-07 17:27Z]

I am wondering whether it would not be better to exclude it for lack of documentation. I have no source to cite whether I give it the doubtful status or the excluded one.

For now, I will exclude. When they find it, we will change it.

Luc
