### ISSUE TITLE
Correction in authority of synonym of Rorippa palustris subsp. hispidus

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2830]
Re: Nasturtium terrestre var. hispidum (Desvaux) B.L. Robinson

http://data.canadensys.net/vascan/taxon/4111?lang=en

This combination was made by Sereno Watson in 1895, not B.L. Rob., who made the combination Radicula palustris var. hispida (Desv.) B.L. Rob. in 1908.
See IPNI, Tropicis, and the Plant List.  
it should read:  ... var. hispidum (Desv.) S.Watson

**Comment by brouille** [comment]
corrected
L
