### ISSUE TITLE
Correction in authorities of synonyms of Rorippa palustris subsp. palustris

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2831]
Re: http://data.canadensys.net/vascan/taxon/4113

Re: Caroli-Gmelina palustris (Linnaeus) P. Gaertner, B. Meyer & Scherbius
The authorities should be: G. Gaertner, B. Meyer & Scherbius
(the P. initial was an error for Prof., not his first name; many others have been corrected, but this one was missed)

Re: Nasturtium palustre (Linnaeus) de Candolle (1821)
This is an illeg. homonym, as Crantz published this name in 1769.  IPNI notes that Crantz's name is a synonym of Subularia aquatica, but it's been overlooked in most database.
Here's the original description: http://bibdigital.rjb.csic.es/ing/Libro.php?Libro=4074

**Comment by brouille** [comment]
corrected 
L
