### ISSUE TITLE
Correction in authorities of synonym of Moehringia lateriflora

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2835]
Re: http://data.canadensys.net/vascan/taxon/4332

The authorities of the synonym: Arenaria lateriflora var. angustifolia H. St.John 
should be (Regel) H. St. John

This is based on Moehringia lateriflora (L.) Fenzl var. angustifolia Regel

See IPNI & Rhodora 19:260

**Comment by brouille** [comment]
correction done
L
