### ISSUE TITLE
Corrections in authorities of Sagina cespitosa and synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2836]
Re: http://data.canadensys.net/vascan/name/Sagina%20caespitosa?lang=en

Sagina caespitosa (J.Vahl) Lange  - should now be Sagina caespitosa Lange (1857)
Arenaria caespitosa J.Vahl (1840) - should be listed as a nom. illeg. homonym (earlier name Arenaria caespitosa Salisb. 1796).  
Sagina nivalis var. caespitosa (J.Vahl) B.Boivin  - should be S. nivalis var. caespitosa (Lange) B.Boivin
Spergella caespitosa (J.Vahl) Á.Löve & D.Löve - should be Spergula caespitosa (Lange) Á.Löve & D.Löve

Since J.Vahl's name is illegitimate and not available for use as a basionym, the next earliest name has priority, which is Lange's 1857 name.  So Lange replaces J.Vahl is all combinations made later than 1857. 

I e-mailed Kanchi Gandhi about this and he agrees with these changes.  I can forward you the e-mail if you like.

**Comment by brouille** [comment]
No need to.
I am surprized he did not have FNA corrected online. I will mention this to him.
Corrections done
L
