### ISSUE TITLE
Correction in authority of synonym of Viscaria alpina

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2837]
Re: http://data.canadensys.net/vascan/taxon/14466?lang=en 

Lychnis alpina subsp. americana (Fernald) J. Feilberg

There is only 1 Feilberg in IPNI authors, so the J. initial is unnecessary.  Official abbreviation is just Feilberg.

- should be Lychnis alpina subsp. americana (Fernald) Feilberg

**Comment by brouille** [comment]
correction done
L
