### ISSUE TITLE
recognize var. speciosa at the species level

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2840]
http://data.canadensys.net/vascan/taxon/3383?lang=en

The most recent taxonomic revision of the Rudbeckia fulgida complex (Campbell and Seymour 2013; attached) recognizes var. speciosa as a full species, R. speciosa.  They also cite an Ontario specimen at NY.
[Campbell & Seymour 2013_Towards a revision of the Rudbeckia fulgida complex (Asteraceae), with description of a new species from the southern USA.pdf](https://github.com/Canadensys/vascan-data/files/2166611/Campbell.Seymour.2013_Towards.a.revision.of.the.Rudbeckia.fulgida.complex.Asteraceae.with.description.of.a.new.species.from.the.southern.USA.pdf)

**Comment by brouille** [comment]
R. speciosa now recognized
