### ISSUE TITLE
Calamagrostis epigejos ou epigeios

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2841]
Voici le message envoyé à POWO
http://www.plantsoftheworldonline.org/taxon/urn:lsid:ipni.org:names:394433-1 
The correct name = Calamagrostis epigeios fide TROPICOS (replace the "j" with "i") 
The name Calamagrostis epigejos is illegitimate. 

Cependant, j'ai reçu la réponse suivante de Rafael Govaerts:
Dear Frédéric,

TROPICOS is clearly incorrect as you can see from the Linnaean typification project:

http://www.nhm.ac.uk/our-science/data/linnaean-typification/search/detail.dsml?ID=91500&listPageURL=list%2edsml%3fbeginIndex%3d2490%26Varqtype%3dstarts%2bwith
 
POWO is updated daily and therefore has the most up-to-date data.

Regards,
The POWO editors – Plant & Fungal Names
Biodiversity Informatics & Spatial Analysis 
Herbarium, Library Art & Archives
Royal Botanic Gardens, Kew
TW9 3AE, United Kingdom

J'ai été voir les Species plantarum et autres publications anciennes et on voit toujours avec un "j",

**Comment by brouille** [comment]
orthograph epigejos adopté ds IPNI
orthographe changé
LB
