### ISSUE TITLE
Poa compressa common name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2843]
http://data.canadensys.net/vascan/taxon/7856?lang=en

Since Poa compressa is not native to Canada, I think it would be nice if an English name other than Canada Bluegrass were used; Flat-stemmed Bluegrass seems more appropriate.

**Comment by brouille** [comment]
Marilyn
Please consider
Thanks
Luc

**Comment by manions** [comment]
English vernacular changed
