### ISSUE TITLE
Additions to Ontario introduced spp

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2844]
Marilyn and Marc

The paper attached below reports 3 additions to the flora of Ontario and Canada that have been added to VASCAN:

Allium tuberosum
Cercidiphyllum japonicum
Corydalis nobilis

VErnacular names are required - I already input a suggestion for the English vernaculars from the paper, but this can be changed

[Chapman & Pringle 2018_New and interesting introduced vascular plants for  Ontario and Canada.pdf](https://github.com/Canadensys/vascan-data/files/2275617/Chapman.Pringle.2018_New.and.interesting.introduced.vascular.plants.for.Ontario.and.Canada.pdf)

Please note that Cerciphyllum and Cercidiphyllaceae are also both additions and may require names

Luc

**Comment by MFavreau** [comment]
Noms français ajoutés.
I notice that English names were added. Close the issue?

**Comment by brouille** [comment]
Issue closed
