### ISSUE TITLE
Typo errors for Sisyrinchium montanum and S. montanum var montanum

### ISSUE THREAD

**Issue by AnneBarbourCoboconk** [Canadensys/vascan-data#2845]
http://data.canadensys.net/vascan/taxon/6209 
http://data.canadensys.net/vascan/taxon/6210 

On these two pages above, the accepted vernacular is missing the hyphen between "eyed-grass". 

It is correctly there in all of the synonyms and also correctly there in http://data.canadensys.net/vascan/taxon/6197 "narrow-leaved blue-eyed-grass".

Thank you very much,
Anne Barbour

CKL Flora Co-chair, Kawartha Field Naturalists,
60 Everett Rd.,
Coboconk, ON K0M 1K0
705-464-9096

**Comment by brouille** [comment]
Correction has been made
thank you
Luc Brouillet
