### ISSUE TITLE
Vernacular "tuberous grass pink" should have hyphen

### ISSUE THREAD

**Issue by AnneBarbourCoboconk** [Canadensys/vascan-data#2846]
Good day VASCAN staff,

I am working on the index for our imminent publication: “Flora of the Kawarthas: an illustrated checklist of the vascular plants of the City of Kawartha Lakes, ON”. We have used VASCAN as our authority for plant names and Mike Oldham has been our mentor for this project. As a retired librarian, I am sticky over little issues.
On these two pages your vernacular entries have no hyphen: "grass pink".
http://data.canadensys.net/vascan/taxon/6837  
http://data.canadensys.net/vascan/taxon/6836    

In an index, this would be properly filed as "grass, pink" which would make people think, incorrect, that these plants are members of the CARYOPHYLLACEAE or "PINK FAMILY".
These references correctly list this orchid as "grass-pink":
1.	Peterson Field Guide: Wildflowers. 1996 c1968
2.	Royal Ontario Museum. 2004. Wildflowers of Ontario.
3.	Whiting and Catling. 1986. Orchids of Ontario.
4.	Skelton and Skelton. 1991. Haliburton Flora. Royal Ontario Museum Life Sciences Pubn.

Although this reference spell it "Grass Pink", the name is listed in the Index under "G" in which case it SHOULD have a hyphen:
1.	Newcomb's Wildflower Guide. 1977.
My recommendation is to insert a hyphen, thereby changing your vernaculars on both pages to “tuberous grass-pink”.
Since your authority for using the vernacular “tuberous grass pink” is NHIC 2009, I will email this letter to Mike Oldham so he will also see my recommendation.
Thank you for providing this very important VASCAN service to the public for free.
Sincerely,
Anne Barbour,
CKL Flora Co-chair, Kawartha Field Naturalists,
60 Everett Rd.,
Coboconk, ON K0M 1K0
705-464-9096

**Comment by brouille** [comment]
Marilyn
Please act on this
Thanks
Luc

**Comment by manions** [comment]
Although this species has the name 'grass pink' (without a hyphen) throughout many references, I agree that a hyphen in this case is warranted. Thanks for your input and I apologize for the delay in responding
