### ISSUE TITLE
Carex lasiocarpa English name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2847]
http://data.canadensys.net/vascan/taxon/4933?lang=en

Change English common name to Woolly-fruited Sedge (from Woolly-fruit Sedge) to be consistent with most other English names used?

**Comment by brouille** [comment]
Marilyn
Please act upon this
Thanks
Luc

**Comment by manions** [comment]
good catch, I've tried to be quite consistent with this, corrected
