### ISSUE TITLE
Hieracium vulgatum vs. H. lachenalii subsp. cruentifolium

### ISSUE THREAD

**Issue by MFavreau** [Canadensys/vascan-data#2848]
Bonjour Luc,

In VasCan, these two taxa are treated as distinct, with distinct distributions. It is not clear to me that two distinct taxa are actually occurring in Canada. Could you please inform me on this? It has an impact on the use of several confusing vernacular names presently applied to H. lachenalii subsp. cruentifolium.

Merci,

Marc

**Comment by AlexBERGER0N** [comment]
J'ai les mêmes interrogations, et ai besoin d'une réponse pour une publication à venir. Il est possible que je fasse ce travail bibliographique et en herbier si Luc ne détient pas cette information. Avec la Covid-19, je crois cependant que l'herbier MT est inaccessible.

**Comment by brouille** [comment]
Problème réglé pour le moment
Luc
