### ISSUE TITLE
add French vernacular

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2850]
http://data.canadensys.net/vascan/taxon/3856

Add French vernacular botryche lunaire

**Comment by MFavreau** [comment]
Done

**Comment by MichaelOldham** [comment]
Hi Marc, the relevant article is attached.

Mike

[cid:image002.png@01D45A29.DF77DB00]

Michael J. Oldham
Provincial Botanist
Ontario Natural Heritage Information Centre
Ontario Ministry of Natural Resources and Forestry
300 Water St., 2nd Floor, North Tower
Peterborough, ON, CA, K9J 3C7
(705)755-2160 fax (705)755-2168
michael.oldham@ontario.ca<mailto:michael.oldham@ontario.ca>

**Comment by MFavreau** [comment]
Hi Mike,

 

I cannot find the paper. Would you please try again?

 

Thank you.

 

Marc

 

  _____  

De : MichaelOldham [mailto:notifications@github.com] 
Envoyé : 16 octobre 2018 15:10
À : Canadensys/vascan-data
Cc : MFavreau; State change
Objet : Re: [Canadensys/vascan-data] add French vernacular (#2850)

 

Hi Marc, the relevant article is attached.

Mike

[cid:image002.png@01D45A29.DF77DB00]

Michael J. Oldham
Provincial Botanist
Ontario Natural Heritage Information Centre
Ontario Ministry of Natural Resources and Forestry
300 Water St., 2nd Floor, North Tower
Peterborough, ON, CA, K9J 3C7
(705)755-2160 fax (705)755-2168
michael.oldham@ontario.ca<mailto:michael.oldham@ontario.ca>

**Comment by MichaelOldham** [comment]
Hi Marc,

Trying again.  If this doesn’t work, send me your personal email address and I’ll send it directly there.

mike
