### ISSUE TITLE
source for Calystegia spithamaea subsp. stans in Ontario?

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2851]
http://data.canadensys.net/vascan/taxon/31190

Source for including this subspecies for Ontario is FOIBIS, but there is no mention of it there.

**Comment by brouille** [comment]
FNA is the source but I do not know the documentation and you did not comment on this occurrence.
I am not sure how the author documented distributions in CAnada, and now we cannot ask because he passed away. 
I will put it as doubtful.
L
