### ISSUE TITLE
Dactylorhiza praetermissa subsp. praetermissa var. junialis English vernacular

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2853]
http://data.canadensys.net/vascan/taxon/30175?lang=en

"Timmins Orchid" seems like a poor English vernacular name for a plant of European origin (and it doesn't agree with the French vernacular name).  If vernacular names are to be standardized, wouldn't a more globally appropriate name be better?

**Comment by brouille** [comment]
Marilyn
Please consider
Luc

**Comment by manions** [comment]
English vernaculars reviewed. The names referring to locations, are placed as synonyms.
