### ISSUE TITLE
Juncus gerardii spelling of epithet

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2857]
http://data.canadensys.net/vascan/name/Juncus%20gerardii

According to Knapp (2016) - Our plants are ssp. gerardi. Routinely, the epithet is misspelled as “gerardii.”

(Knapp, W. M. 2016. Juncaceae, the Rush Family. R.F.C. Naczi, J. R. Abbott, and Collaborators, New Manual of Vascular Plants of Northeastern United States and Adjacent Canada, online edition of 2016. NYBG Press, New York. 28 pp.)

**Comment by brouille** [comment]
IPNI confirms : gerardii corrected in all instances
LB
