### ISSUE TITLE
Lespedeza frutescens vernacular names

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2858]
http://data.canadensys.net/vascan/name/Lespedeza%20frutescens

Since Lespedeza frutescens is the correct name for what was known as L. violacea, I suggest the common names violet bush-clover and lespédèze violacée for it.  Lespedeza violacea (formerly known as L. intermedia) could have the vernacular names wand bush-clover and lespédèze intermédiaire.

**Comment by MFavreau** [comment]
Thank you Michael, this is very useful.

I would use « lespédèze intermédiaire » for L. violacea as you suggested, but I believe maintaining « lespédèze violacée » as an accepted name for L. frutescens would be confusing since true L. violacea is a different species.

Would you kindly send me a copy of the source paper for this info?

Marc Favreau

**Comment by MFavreau** [comment]
Thank you Michael.

French names added.

Marc

**Comment by brouille** [comment]
Marilyn
Can you see to the English vernacular here please?
Luc

**Comment by manions** [comment]
I added the English vernacular of 'violet bush-clover' as a synonym to match with the SciName synonym, and that vernacular is still in use for L. frutescens. I didn't add 'wand bush-clover' as a synonym as it may also refer to L. virgata

**Comment by manions** [comment]
oops can't use 'violet bush-clover for L. frutescens as in use for L. violacea. I don't have the FNA manuscript to see if any changes to the relationships of these three species (frutescens, violacea, intermedia)

**Comment by brouille** [comment]
Marylin
Here is the FNA treatment.
Luc
[Lespedeza02rev_ECAN.pdf](https://github.com/Canadensys/vascan-data/files/4765894/Lespedeza02rev_ECAN.pdf)

**Comment by manions** [comment]
great, thanks, I'll review again

**Comment by manions** [comment]
finished reviewing the English vernaculars, thanks everyone for input and manuscript
