### ISSUE TITLE
Lonicera x bella vernaculars

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2859]
http://data.canadensys.net/vascan/taxon/4229?lang=en

Wondering whether Lonicera x bella was named after someone called Bell or because it was a beautiful honeysuckle hybrid.  VASCAN English vernacular is Bell's Honeysuckle and French vernacular is chèvrefeuille joli.  From an online search it seems that this hybrid was not named after someone called Bell, so Showy Honeysuckle or Beautiful Honeysuckle may be a more appropriate English vernacular.

**Comment by brouille** [comment]
Marilyn and Marc
Please verify this. I doubt it was named for Bell as bella in Latin is for beautiful, bellae would have been for Bell

Luc

**Comment by MFavreau** [comment]
This is confirmed in Gray's Manual (Fernald 1950) p. 1333, where the etymology is given as « pretty ».

No change required to accepted French name.

**Comment by brouille** [comment]
J'ai enlevé les deux noms référant à Bell (source : Darbyshire) car ils sont erronés.
J'ai choisi showy fly-honeysuckle comme nom acc en anglais
Luv
