### ISSUE TITLE
Lepidium virginicum (& subsp. virginicum) confirmed for NWT

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#286]
[Originally posted on GoogleCode (id 2567) on 2015-03-30]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4072?lang=en

<b>What data are incorrect or missing?</b>
NWT missing

<b>What data are you expecting instead?</b>
add NWT

<b>If applicable, please provide an authoritative source.</b>
Michael Oldham's 2006 survey in the NWT. Peter Ball at TRTE has confirmed as Lepidium virginicum (where the specimens are deposited).

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-04-02 20:52Z]

MArilyn

please provide status when you mention new taxa within provinces : I chose introduced for this one

Luc
