### ISSUE TITLE
Mentha x muelleriana French vernacular

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2860]
http://data.canadensys.net/vascan/taxon/6409?lang=en

If English vernacular is Mueller's mint, why is French vernacular menthe de Muller and not menthe de Mueller?

**Comment by brouille** [comment]
Marc
Peux-tu répondre svp?
Luc

**Comment by MFavreau** [comment]
I do not have access to the original source of the French name, but it was probably spelled « Müller », which is the modern spelling of « Mueller ».

To avoid any further mistakes, I will correct the spelling as per English.

Thank you.
