### ISSUE TITLE
Isoetes xbrittonii not in Canada

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2861]
http://data.canadensys.net/vascan/taxon/30563?lang=en

Isoetes x brittonii does not occur in Ontario or Canada despite its inclusion in Newmaster & Ragupathy, 2005 (Brunton and Taylor 1990; Daniel F. Brunton pers. comm. 31 September 2018).

**Comment by brouille** [comment]
SEcond issue on this topic, now solved
LB
