### ISSUE TITLE
Pluchea odorata var. succulenta English vernacular

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2862]
http://data.canadensys.net/vascan/taxon/3357

Seems a bit odd to call the full species a camphorweed and the variety a fleabane (usually reserved for Erigeron species).  There is no such distinction with the French vernacular.  Why not saltmarsh camphorweed for the English vernacular?

**Comment by brouille** [comment]
Marilyn
fleabane is not used in FNA (source of name) but camphor-weed
Please correct
Luc

**Comment by manions** [comment]
English name changed. FNA name of saltmarsh fleabane removed to avoid confusion with Erigeron
