### ISSUE TITLE
Prunus pumila var. susquehanae English vernacular

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2863]
http://data.canadensys.net/vascan/taxon/20280?lang=en

Presumably this plant is named after the Susquehanna River (spelled with two n's).  The French vernacular is  cerisier de la Susquehanna (two n's) while the English vernacular is Susquehana sand cherry (one n) - should it be Susquehanna sand cherry?

**Comment by brouille** [comment]
Marilyn 
please take this into consideration
Luc

**Comment by manions** [comment]
Thanks for this correction
