### ISSUE TITLE
Rubus allegheniensis vernaculars

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2864]
http://data.canadensys.net/vascan/name/Rubus%20allegheniensis

Presumably named after the Allegheny (not Alleghany) Mountains, so should English vernacular be Allegheny Blackberry (also French vernacular?).

Note also no author name following Rubus allegheniensis at top of page.

**Comment by brouille** [comment]
Marilyn and Marc
Please take this into account
no author names on some search results is standard - taxon page has author name
Luc

**Comment by MFavreau** [comment]
No change required in French names.
Allegheny Mountains are normally called « monts Alléghanys » in French, at least since the days of André Michaux, who wrote a book on them.

**Comment by manions** [comment]
corrected the spelling of Alleghany to Allegheny here and a few others, many thanks
