### ISSUE TITLE
Salix maccalliana English vernacular

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2865]
http://data.canadensys.net/vascan/name/Salix%20maccalliana

Salix maccalliana was named for the collector of the type specimen, W. McCalla (http://eol.org/pages/485199/details), so probably should have the English vernacular of McCalla's willow (not MacCalla's willow).  This would agree with the French vernacular saule de McCalla.

**Comment by brouille** [comment]
Marilyn
Please make the necessary correction
Luc

**Comment by manions** [comment]
Yes you are correct. I found the original article from 1907 where it's mentioned species named for W.C. McCalla. Many thanks
