### ISSUE TITLE
Spiranthes arcisepala not in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2866]
http://data.canadensys.net/vascan/taxon/31216?lang=en

Although mentioned from Ontario in Pace and Cameron (2017) and mapped from the south side of the St. Lawrence River in upstate New York, Matthew Pace (pers. comm.) never actually saw any Ontario material of   S. arcisepala during his study.  Based on its presence in adjacent New York state and Quebec, Matthew expects it likely does occur in Ontario, but to date he has not verified any specimens from Ontario (pers. comm.).  Suggest removing for Ontario until specimen evidence is obtained.

**Comment by brouille** [comment]
DAta and reference to the presence in Ontario has been removed
Thanks
Luc
