### ISSUE TITLE
subspecies in Veronica peregrina

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2867]
http://data.canadensys.net/vascan/taxon/7336?lang=en

FNA in prep. is given as the reference for accepting subspecies in Veronica peregrina (subsp. peregrina and subsp. xalapensis), however the draft FNA treatment for Veronica does not recognize infraspecific taxa in V. peregrina.

**Comment by brouille** [comment]
The FNA author mentions the infraspecies in his discussion. He apparently did not try to deal with the infrasp variation : "The importance of these characters needs further evaluation"
Luc
