### ISSUE TITLE
listed synonym of Juncus subtilis not actually published.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2868]
Re: synonym of Juncus subtilis: http://data.canadensys.net/vascan/taxon/6307?lang=en

Juncus fluitans Michaux nom. illeg. is listed as a synonym, but Michaux did not publish a new name, thus it could not be considered illegitimate; in his original publication  (1803:191) he cites Lamarck as the author of J. fluitans (Ency. 3(1): 270-271).  This is just an error in citation (by someone other than Michaux), not a nom. illeg., that was carried forward in the nomenclature.  
see: https://www.biodiversitylibrary.org/page/404960#page/220/mode/1up 

See Kirschner's (2002) discussion of this.

Also, The validly published name, Juncus fluitans Lam., is now listed as a synonym of Juncus bulbosus, not J. subtilis.  See WCSP (World Checklist of Selected Plant Families)
https://wcsp.science.kew.org/qsearch.do
You could all this J. fluitans Lam. and combinations based on this name in synonymy under J. bulbosus.

**Comment by brouille** [comment]
Juncus fluitans Lamarck moved to synonymy under Juncus bulbosys

Thanks
LB
