### ISSUE TITLE
Verbena bonariensis in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2869]
Known from two Ontario specimen records from outside cultivation.  First collected in Ontario in 2002 by Carl Rothfels from the Royal Botanical Gardens and reported new to Ontario by Rothfels (Rothfels, C. 2004. Significant vascular plant records from the Hamilton area, Ontario. Canadian Field-Naturalist 118(4): 612-615.)  Collected in 2018 from a disturbed beach at Presqu'ile Provincial Park, Northumberland County by David Bree.  Specimens documenting both records are in the NHIC herbarium and scans were recently confirmed as V. bonariensis and not the similar V. incompta by Guy Nesom.
--

**Comment by brouille** [comment]
status changed to introduced - NHIC cited as source
LB
