### ISSUE TITLE
Sorbus intermedia scientific name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2870]
http://data.canadensys.net/vascan/name/Sorbus%20intermedia

The genus Sorbus has been found to be polyphyletic and has been recently split into several genera (e.g. Sennikov and Kurtta 2017).  Sennikov (2018) proposed the name Scandosorbus intermedia (Ehrh.) Sennikov for S. intermedia to replace the illegitimate name Borkhausenia intermedia (Ehrh.) Sennikov & Kurtto published earlier by Sennikov and Kurrta (2017).

[Sennikov & Kurtto 2018_A phylogenetic checklist of Sorbus s.l. (Rosaceae) in Europe.pdf](https://github.com/Canadensys/vascan-data/files/2522800/Sennikov.Kurtto.2018_A.phylogenetic.checklist.of.Sorbus.s.l.Rosaceae.in.Europe.pdf)
[Sennikov 2018_Scandosorbus (Rosaceae), a New Generic Name for Sorbus intermedia and Its Hybrid.pdf](https://github.com/Canadensys/vascan-data/files/2522801/Sennikov.2018_Scandosorbus.Rosaceae.a.New.Generic.Name.for.Sorbus.intermedia.and.Its.Hybrid.pdf)

**Comment by brouille** [comment]
name of genus changed to Scandosorbus, etc.
LB
