### ISSUE TITLE
Crataegus xkingstonensis English vernacular

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2871]
http://data.canadensys.net/vascan/name/Crataegus%20%C3%97kingstonensis

Since this was named for the City of Kingston ("King's Town"), where the type specimen was collected, rather than after a person named Kingston, the English name Kingston hawthorn may be more appropriate than Kingston's hawthorn.

**Comment by brouille** [comment]
Marilyn please respond
Luc

**Comment by manions** [comment]
Gosh, good catch! I fixed the English vernacular. Many thanks
