### ISSUE TITLE
Isoetes x brittonii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2872]
http://data.canadensys.net/vascan/taxon/30563

Isoetes x brittonii is not known from Ontario.  Previous reports in error (see Brunton and Taylor 1990).

[Brunton & Taylor 1990_Isoëtes ×brittonii hyb. nov. (Isoëtaceae), A Naturally Occurring Hybrid (I. engelmannii × I. riparia).pdf](https://github.com/Canadensys/vascan-data/files/2523031/Brunton.Taylor.1990_Isoetes.xbrittonii.hyb.nov.Isoetaceae.A.Naturally.Occurring.Hybrid.I.engelmannii.x.I.riparia.pdf)

**Comment by brouille** [comment]
Taxon excluded from Ont. (and automatically Canada). Report was that of Newmaster & Ragupathy 2005, who place I. engelmannii in syn of the hybrid!
LB
