### ISSUE TITLE
Amaranthus powellii subsp. bouchonii French name

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2873]
http://data.canadensys.net/vascan/name/Amaranthus%20powellii%20subsp.%20bouchonii

Other Amaranthus are called amarante rather than amaranthe.

**Comment by MFavreau** [comment]
Thank you spotting this. I corrected the name.

You may wonder about the orthographical difference with the scientific name. Actually, the French name « amarante » traces back to 1544 and comes from the classical Latin _amarantus_, not from the Linnaean name _Amaranthus_.
