### ISSUE TITLE
Festuca brachyphylla subsp.

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2875]
http://data.canadensys.net/vascan/taxon/7648?lang=en

Subspecies are recognized in FNA and Catalogue of New World Grasses.  Canadian plants belong to ssp. brachyphylla.

**Comment by brouille** [comment]
According to FNA the three subsp are present in Canada (and in Ontario)
See http://beta.floranorthamerica.org/Festuca_brachyphylla
Note that the Kew databases do not recognize subspp., contra CNWG, which I tend to follow, however lack data on the distribution of the 3 subsp in Canada, as it appears that the FNA site cited above simply reproducing the sp distribution for each subsp [an issue with Grasses volumes in FNA]

**Comment by brouille** [comment]
Indeed, subsp. brachyphylla only in Canada. changed
LB
