### ISSUE TITLE
recognition of Campanula petiolata

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2877]

**Comment by MichaelOldham** [comment]
Wondering why Campanula petiolata A. DC. is not recognized for Canada?  Lammers (2007) is used as the authority for the occurrence of C. gieseckiana (note spelling difference in Lammers 2007 vs. VASCAN) and C. intercedens in Canada, but Lammers also considers C. petiolata (another C. rotundifolia segregate) native to Canada (NU, NT, YK, AB, BC, MB, SK).

**Comment by brouille** [comment]
Both TRO and IPNI use gieseckeana, not -iana, but indicate:  as "Giesekiana" - probably a correctible orgthograph

petiolata was missed - now added

I am not sure FNA author will follow this taxonomy and revert to s.l. rotundifolia
LB
