### ISSUE TITLE
Carex recta X Carex stricta, exclude for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2878]
http://data.canadensys.net/vascan/taxon/5053?lang=en

This hybrid is reported from Ontario in VASCAN based on Newmaster et al. (1998), who do not mention it.  FNA Vol. 23 (2002) states that "A specimen intermediate between C. recta and C. stricta is known from northwestern Quebec" (with no mention of the hybrid from anywhere else) and Cayouette and Catling (1992) state that "only one collection from N Quebec (James Bay) seems to represent this hybrid".

**Comment by brouille** [comment]
Mention removed. 
LB
