### ISSUE TITLE
add Cypripedium x herae for MB

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2879]
The hybrid Cypripedium x herae, described from Manitoba, is not in VASCAN.  Scan of article describing the hybrid is attached (note that it is missing the last page).
[Ewacha & Sheviak 2004_Cypripedium x herae, a natural Cypripedium hybrid from central Canada.pdf](https://github.com/Canadensys/vascan-data/files/2604622/Ewacha.Sheviak.2004_Cypripedium.x.herae.a.natural.Cypripedium.hybrid.from.central.Canada.pdf)

**Comment by brouille** [comment]
Taxon added. Thanks
LB
