### ISSUE TITLE
Sedum vs Petrosedum

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2880]
Voir Issue: Sedum rupestre #2332

Selon le même auteur, quelques années plus tard, il a transféré les Sedum de la section rupestre dans le genre Petrosedum.
https://www.tandfonline.com/doi/abs/10.1080/00837792.2017.1363978?journalCode=tweb20

**Comment by brouille** [comment]
Je n'ai pas accès à la revue même, cependant. 
Luc

**Comment by brouille** [comment]
Sedum rupestre (et autres) était déjà transféré à Petrosedum - il n'a pas encore été publié, tout simplement.
Merci pour la source
Luc

**Comment by MichaelOldham** [comment]
Oldham, Michael (MNRF) has shared a OneDrive for Business file with you. To view it, click the link below.


<https://ontariogov-my.sharepoint.com/:b:/g/personal/michael_oldham_ontario_ca/ERf8t8hbKkNKs4sQ1dQ7N1UBIlX9-TQfvE4T5T_W1lFDhg>
[https://r1.res.office365.com/owa/prem/images/dc-pdf_20.png]<https://ontariogov-my.sharepoint.com/:b:/g/personal/michael_oldham_ontario_ca/ERf8t8hbKkNKs4sQ1dQ7N1UBIlX9-TQfvE4T5T_W1lFDhg>

Niederle 2016_Co je doopravdy Sedum rupestre 2.pdf<https://ontariogov-my.sharepoint.com/:b:/g/personal/michael_oldham_ontario_ca/ERf8t8hbKkNKs4sQ1dQ7N1UBIlX9-TQfvE4T5T_W1lFDhg>




I think names for some other taxa in Section Rupestre do exist in Petrosedum (e.g. thartii, rupestre).  See attached, starting page 19 and in particular table on page 23.  See also http://www.crassulaceae.ch/de/home

International Crassulaceae Network<http://www.crassulaceae.ch/de/home>
www.crassulaceae.ch
The principal aim is to help preserve plants of the Crassulaceae family now existing in private as well as in public collections – most important in a time when plant imports have become almost impossible. This aim is best achieved by distributing plants and seeds among as many people as possible, by exchanging information on cultivation, origin, taxonomy etc. as well as by offering help in ...




mike


*********************************************************
Michael J. Oldham
Provincial Botanist
Ontario Natural Heritage Information Centre (NHIC)
Ministry of Natural Resources and Forestry
300 Water Street, 2nd Floor, North Tower
P.O. Box 7000 Peterborough, Ontario K9J 1C7, Canada
phone 705-755-2160; fax 705-755-2168
michael.oldham@ontario.ca<mailto:michael.oldham@ontario.ca>
NHIC requests: NHICrequests@ontario.ca<mailto:NHICrequests@ontario.ca>
NHIC web page: https://www.ontario.ca/page/natural-heritage-information-centre

________________________________
