### ISSUE TITLE
Trisetum flavescens - subsp.

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2881]
On reconnait une ssp. flavescens (probablement notre introduite) et une autre ssp.

Annals of the Missouri Botanical Garden 103(3)

Voir le PDF dans ce lien.
https://idus.us.es/xmlui/bitstream/handle/11441/78687/Trisetum-sect-Trisetum-Annals-103-350-392.pdf?sequence=1

**Comment by brouille** [comment]
subsp ajoutée et info transférée
