### ISSUE TITLE
Correcting typo in VASCAN ("C. aduennae")

### ISSUE THREAD

**Issue by TADatTRT** [Canadensys/vascan-data#2884]
issue: http://data.canadensys.net/vascan/search?q=Crataegus+aduennae (species not in IPNI)

authoritative source: Palmer EJ (1925) Synopsis of North American Crataegi. Journal of the Arnold Arboretum 6: 5-128. _Crataegus arduennae_ Sarg.
See http://labs.eeb.utoronto.ca/dickinson/VASCANcorrectionCrataegusarduennae.html

**Comment by brouille** [comment]
Thanks for having caught the typo
LB
