### ISSUE TITLE
Ammophila now Calamagrostis?

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2885]
https://data.canadensys.net/vascan/taxon/7400

Saarela et al. (2017), based on a molecular phylogenetics study, suggest that Ammophila belongs in Calamagrostis and make the necessary combinations. 

[Saarela et al 2017_Molecular phylogenetics of cool-season grasses in the subtribes Agrostidinae, Anthoxanthinae, Aveninae, Brizinae, Calothecinae, Koeleriinae and Phalaridinae (Poaceae).pdf](https://github.com/Canadensys/vascan-data/files/2807903/Saarela.et.al.2017_Molecular.phylogenetics.of.cool-season.grasses.in.the.subtribes.Agrostidinae.Anthoxanthinae.Aveninae.Brizinae.Calothecinae.Koeleriinae.and.Phalaridinae.Poaceae.pdf)

**Comment by brouille** [comment]
transfer of Ammophila breviligulata to Calamagrostis done
LB
