### ISSUE TITLE
Lupinus microcarpus Sims var. microcarpus

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2888]
C'est le nom accepté au lieu de Lupinus densiflorus Bentham subsp. densiflorus dans VASCAN (maintenant un synonyme)

**Comment by brouille** [comment]
En fait, les deux noms ne sont pas synonymes: densiflorus typique est syn de microcarpus var. densiflorus, qui n'est pas présent en BC selon FNA. Il semble qu'on ait utilisé le mauvais taxon en BC par le passé. Je vais devoir ajouter var. densiflorus pour l'exclure en disant mauvaise taxo.
Luc
