### ISSUE TITLE
Lupinus argenteus - problèmes avec les infraspécifiques

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2893]
Salut

1) subsp. argenteus var. laxiflorus - nom non retenu
Il semble être envoyé en synonymie de Lupinus argenteus var. argenteus 

2) subsp. argenteus
envoyé en synonymie de Lupinus argenteus var. argenteus

**Comment by brouille** [comment]
Fred

Je suis en train de passer systématiquement en revue toutes les entrées de Lupinus dans VASCAN car il y a des différences significatives pour de nombreux taxons, qu'il est parfois difficile de réconcilier. Merci de me signaler les cas, mais il y en a certains qui vont requérir des interactions avec les gens de BC car ce n'est pas toujours direct

argenteus fait
