### ISSUE TITLE
Lupinus arcticus subsp. subalpinus (Piper & B.L. Robinson) D.B. Dunn - synonyme dans FNAms

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2895]
Le nom latin dans FNAms est Lupinus latifolius   Lindley ex J. Agardh var. subalpinus   (Piper & B. L. Robinson) C. P. Smith

**Comment by brouille** [comment]
je suis en voie de réviser le ms entier pour harmoniser les différences entre FNA et BC, en particulier
L
