### ISSUE TITLE
Lycopus laurentianus

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#29]
[Originally posted on GoogleCode (id 1381) on 2012-06-18]

Salut

Aucun nom anglais pour ce taxon.

http://data.canadensys.net/vascan/taxon/6391?lang=fr

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-21 13:07Z]

Marilyn:

An English vernacular is requested for Lycopus laurentianus

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:21Z]

English vernacular added
