### ISSUE TITLE
Limnanthus: subsp. hookeri added

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2903]
Marilyn and Marc

Please review Linanthus vernacular names. The FNA ms arrived and added subsp. hookeri to L. pungens (no other subsp.) - the current vernaculars, designed for the sp, may not be appropriate for the subsp. I transferred the accepted vernaculars to the species also.

Thanks
Luc

**Comment by MFavreau** [comment]
French names corrected for both species and subspecies.

Marc

**Comment by MFavreau** [comment]
Marilyn,

Just a hint : the name is Linanthus, not "Limnanthus", and not to be confused with Limnanthes.

Marc

**Comment by manions** [comment]
Thanks, I started working on Limnanthes.
Finished the review of English vernaculars for Linanthus
