### ISSUE TITLE
Isoetes x robusta (G. Engelmann) D.F. Brunton

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2904]
Voir l'article dans Rhodora  120 (984)
https://www.researchgate.net/publication/330688253_Isoetes_Robusta_comb_nov_the_Appropriate_Name_for_I_echinospora_Septentrionalis_Isoetaceae

 Voici les synonymes rattachés à ce taxon
Isoetes echinospora var. robusta Engelmann
Isoetes x dodgei sensu Britton & Brunton (1989), non A.A. Eaton (1898), pro sp.
I. muricata Durieu x I. septentrionalis D.F. Brunton

A noter que l'autorité dans VASCAN pour I. echinospora var. robusta n'a pas l'initiale de l'auteur.  VASCAN devrait avoir G. Engelmann.  :-)

Pas de précision dans l'article sur la répartition mais probablement au Québec et on Ontario car le spécimen type est dans le lac Champlain, sur l'ile La Motte près du Québec.  Il parle de l'hybride au Québec et en Ontario.

**Comment by brouille** [comment]
changement de nom effectué, avec dodgei auct. non mis en synonymie de façon à ne pas perdre ce lien 
le G. ne doit pas être ajouté à Engelmann (voir IPNI et TROPICOS, basionyme)
Luc

**Comment by brouille** [comment]
MArilyn and MArc
Current vernacular have Dodge in it, but Brunton shows this is a name of ambiguous application. I believe it might be best to change the vernacular in both French and English. 
See Brunton paper in initial issue above.
Thanks
Luc

**Comment by MFavreau** [comment]
J'ai simplement éliminé le nom français isoète de Dodge, qui n'est pas nécessaire puisqu'il s'agit d'un hybride.
