### ISSUE TITLE
Asclepias tuberosa ssp. tuberosa in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2905]
https://data.canadensys.net/vascan/taxon/2713

Both ssp. tuberosa and ssp. interior are listed for Ontario in the FNA draft treatment (and by Woodson 1954), but only ssp. interior is included in VASCAN.

**Comment by brouille** [comment]
I added this taxon as per your request and following FNA. I still think that documentation is lacking.
Luc
