### ISSUE TITLE
Impatiente de l’hymalaya 

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2906]
Avec double m dans Hymmalaya

**Comment by MFavreau** [comment]
Bonjour Fred.

Je ne comprends pas bien ta question ou suggestion.

En français comme en anglais, Himalaya s'écrit avec un seul m (et un seul y).

J'ai fait la correction pour « balsamine de l'Himalaya », qui était écrit avec 2 m, mais je ne trouve pas le nom « impatiente de l'Hymmalaya ». De quelle espèce s'agit-il? Je ne sais pas comment trouver la fiche avec le numéro.

Merci

Marc

**Comment by FredCoursol** [comment]
Bonjour Marc

J'ai fait cela à partir de mon cellulaire et de mémoire.  C'était effectivement la balsamine qui avait le problème.

**Comment by MFavreau** [comment]
OK.

 

C’est toujours un plaisir de te lire.

 

Marc

 

De : FredCoursol <notifications@github.com> 
Envoyé : 24 avril 2019 10:49
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : MFavreau <marcotte.favreau@sympatico.ca>; Comment <comment@noreply.github.com>
Objet : Re: [Canadensys/vascan-data] Impatiente de l’hymalaya (#2906)

 

Bonjour Marc

J'ai fait cela à partir de mon cellulaire et de mémoire. C'était effectivement la balsamine qui avait le problème.
