### ISSUE TITLE
Conopodium majus - vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2907]
Peter Ball determined that Bunium was not present in Saint-Pierre-and-Miquelon but in fact had been misidentified. The plant present there is Conopodium majus (see manuscript attached).

Vernacular are needed, both English and French. The plant is native in France, among others.

Luc

[Conopodium02d.AP.docx](https://github.com/Canadensys/vascan-data/files/3113043/Conopodium02d.AP.docx)

**Comment by MFavreau** [comment]
French names added.

**Comment by manions** [comment]
English vernaculars added
