### ISSUE TITLE
synonyme mal placé

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2908]
Jeremy

L’éditeur de VASCAN ne  m’a pas permis de transférer un synonyme au bon endroit car il y avait deux noms semblables et la fenêtre d’assignation n’est jamais apparue.

Taxon 9629 Calamagrostis cinnoides auct. non W.P.C. Barton nom. illeg.

a été placé [je ne sais ni comment ni pourquoi] comme synonyme de :

927 Calamagrostis [un genre]

Il faut le placer sous le nom :

31896 Calamagrostis coarctata

Merci

Luc

**Comment by JeGoi** [comment]
UPDATE `taxonomy` SET `parentid` = `31896` WHERE childid = 9629;
UPDATE `lookup` SET parentid= 31896 WHERE taxonid = 9629;

Done. Need to be validated

**Comment by brouille** [comment]
OK
Luc
