### ISSUE TITLE
FNa volume 17 : Lamiales p.p.: some vernacular names required 

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2911]
Marilyn and Marc

I just finished checking data in VASCAN against the recently published FNA 17 volume data. It would be good to check vernacular names for species in this volume, when you have time. Most appear OK,but I note that several English vernaculars were not documented (in fact, many were synonyms). I added FNA 2019 to names where the data matched.

The following new taxa need vernacular names:
Eryhtranta decora, E. arvensis
Veronica argue-serrata
Euphrasia arctica subspecies
Euphrasia stricta subspecies
Castilleja miniata varieties

Thanks
Luc

**Comment by manions** [comment]
finished review of all English vernaculars in volume 17
