### ISSUE TITLE
new taxonomic status proposed for Isoetes acadiensis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2912]
https://data.canadensys.net/vascan/taxon/6213?lang=en

Recent paper (attached) suggesting that Isoetes acadiensis should be considered a subspecies of I. tuckermanii.

[Brunton 2018_Distribution and taxonomy of Isoetes tuckermanii subsp. acadiensis, comb. nov. (Isoetaceae) in North America.pdf](https://github.com/Canadensys/vascan-data/files/3397325/Brunton.2018_Distribution.and.taxonomy.of.Isoetes.tuckermanii.subsp.acadiensis.comb.nov.Isoetaceae.in.North.America.pdf)

**Comment by brouille** [comment]
modification to status accepted and entered
will appear at next publication of VASCAN
LB
