### ISSUE TITLE
Achyranthes japonica new to Canada

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2915]
Recent addition to the flora of ON and Canada.

[Kamstra 2019_Japanese Chaff-flower, Achyranthes japonica (Amaranthaceae), on the Erie islands, an invasive plant new to Canada.pdf](https://github.com/Canadensys/vascan-data/files/3642880/Kamstra.2019_Japanese.Chaff-flower.Achyranthes.japonica.Amaranthaceae.on.the.Erie.islands.an.invasive.plant.new.to.Canada.pdf)

**Comment by brouille** [comment]
Marilyn and Marc: vernaculars required
Thanks

**Comment by MFavreau** [comment]
French name added. Other species of Achyranthes are called "achyranthe" in France.

**Comment by manions** [comment]
English vernacular added
