### ISSUE TITLE
Allium carinatum and Anemone ranunculoides new to ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2916]
See attached article reporting Allium carinatum ssp. carinatum and Anemone ranunculoides (neither is in VASCAN for ON) for the first time in Ontario.
[Cecile 2019_Interesting and new species found in Guelph and along an abandoned railway.pdf](https://github.com/Canadensys/vascan-data/files/3643007/Cecile.2019_Interesting.and.new.species.found.in.Guelph.and.along.an.abandoned.railway.pdf)

**Comment by brouille** [comment]
does it have a URL
FBO = ? Federation of Biologists or Botanists?

**Comment by brouille** [comment]
Vernacular names required for Allium carinatum subsp. carinatum and sp.
Thanks
Luc

**Comment by MichaelOldham** [comment]
No URL. Newsletter currently published only in hard copy. FBO = Field Botanists of Ontario

mike

**Comment by MichaelOldham** [comment]
Keeled Garlic is a commonly used English name (e.g. https://michiganflora.net/species.aspx?id=2917)

mike

**Comment by MFavreau** [comment]
French names added.

**Comment by manions** [comment]
English vernaculars added
