### ISSUE TITLE
Astragalus laxmannii (and var. robustior) introduced in ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2918]
https://data.canadensys.net/vascan/taxon/27082?lang=en

The only Ontario record (C.E. Garton in 1950 at DAO, LKHD) is from railway ballast at Thunder Bay and is considered possibly introduced by Argus et al. (1982-1987). The species has never been recorded in a natural habitat in Ontario and the Ontario record is disjunct from the main range of the species which is further west.  Although considered native to Ontario by Morton and Venn (1990), it seems more likely that the species was a casual introduction via rail traffic from the west.

**Comment by brouille** [comment]
status changed to introduced
LB
