### ISSUE TITLE
Solidago flexicaulis - orthographic error in vernacular name

### ISSUE THREAD

**Issue by CaroleSinou** [Canadensys/vascan-data#2923]
https://data.canadensys.net/vascan/taxon/3447?lang=fr

The accepted vernacular name in french should be "verge d'or à tige zigzagante", and not "verge d'or à tige zigzaguante".
This error may appear in other names.

**Comment by MFavreau** [comment]
You are right! Correction made!

 

Interestingly, this orthographical error traces back to the original author of the name, frère Marie-Victorin (Flore laurentienne, p. 598).

 

Marc Favreau

 

De : CaroleSinou <notifications@github.com> 
Envoyé : 25 septembre 2019 11:54
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] Solidago flexicaulis - orthographic error in vernacular name (#2923)

 

https://data.canadensys.net/vascan/taxon/3447?lang=fr

The accepted vernacular name in french should be "verge d'or à tige zigzagante", and not "verge d'or à tige zigzaguante".
This error may appear in other names.

**Comment by CaroleSinou** [comment]
I'm just the messenger.
Jacques Ranger spotted the error.

Thanks for the correction Marc
