### ISSUE TITLE
Rorippa alpina new to BC and Canada

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2924]
Marilyn and Marc
Rorippa alpina new to BC and Canada
Need vernacular English and French (none in FNA)
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=250094614

Thanks
Luc

**Comment by MFavreau** [comment]
French name added,

Le nom « rorippe » est féminin.

**Comment by manions** [comment]
English vernacular added, sorry for the delay
