### ISSUE TITLE
Isoetes laurentiana : new for Canada

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2926]
Marilyn and Marc

Please add vernaculars for this new species. None is proposed in the paper attached.

Luc

[Isoetes laurentiana (2019).pdf](https://github.com/Canadensys/vascan-data/files/3758021/Isoetes.laurentiana.2019.pdf)

**Comment by MFavreau** [comment]
French name added.

**Comment by manions** [comment]
English vernacular added, I apologize for the delay
