### ISSUE TITLE
Changement d'orthographe Dryopteris goldieana

### ISSUE THREAD

**Issue by geoffreyhall** [Canadensys/vascan-data#2927]
Étienne Lacroix-Carignan, étudiant à l'U. de Sherbrooke, nous a signalé que Dryopteris goldiana est devenu Dryopteris goldieana.  Il nous a fourni à moi et à Étienne L.-B. les références suivantes:

<http://www.plantsoftheworldonline.org/taxon/urn:lsid:ipni.org:names:30147202-2>
<https://www.ipni.org/n/30147202-2>
<https://eol.org/pages/597458>
<https://www.gbif.org/fr/species/7319790>
<http://www.tropicos.org/Name/26600151>
<https://npgsweb.ars-grin.gov/gringlobal/taxonomydetail.aspx?403294>
<https://plants.usda.gov/core/profile?symbol=DRGO3>
<https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?lin=s&p=has_linkout&id=207840>
<https://www.biodiversitylibrary.org/item/116664#page/205/mode/1up>

Geoff

**Comment by brouille** [comment]
correction faite dans VASCAN
LB
