### ISSUE TITLE
Descurainia pinnata subsp. brachycarpa doubtful for NU

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#293]
[Originally posted on GoogleCode (id 2583) on 2015-04-08]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3981?lang=en

<b>What data are incorrect or missing?</b>
NU is doubtful for this taxon (similar to D. incana), although FNA lists for NU

<b>What data are you expecting instead?</b>
suggest to list as doubtful

<b>If applicable, please provide an authoritative source.</b>
No specimens found, not in any literature (except FNA); not listed by Warawick's Brassicaceae of Canada

**Comment by brouille** [comment]
Nunavut labeled doubtful, with FNA as source for report.
Eventually, it would be nice to be able to remove it altogether (i.e. exclude it).
LB
