### ISSUE TITLE
transfer of Trisetum sibiricum to Sibirotrisetum

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2930]
See attached

[Barbera et al 2019_Molecular phylogenetic analysis resolves Trisetum (Poaceae; Pooideae; Koeleriinae) polyphyletic; Evidence for a new genus, Sibirotrisetum and resurrection of Acrospelion.pdf]

**Comment by brouille** [comment]
The attached document does not download
Luc

**Comment by brouille** [comment]
Changes made, along with correction to some other taxa
LB
