### ISSUE TITLE
misspelling of varietal name in synonymy of Artemisia absinthium

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2931]
Re entry: http://data.canadensys.net/vascan/name/Artemisia%20absinthium%20var.%20inspida?lang=en

Under the synonymy for Artemisia absinthium, the following variety is listed:

Artemisia absinthium var. inspida Stechmann.

This should be spelled ver. insipida, with an 'i' between the 's' and 'p'

See IPNI for details

**Comment by brouille** [comment]
Correction done. It was obviously a typo
Thanks
