### ISSUE TITLE
Huperzia continentalis also in Northwest Territories

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#2932]
Testo et al 2016 also lists specimens verified for this species from the Northwest Territories.

**Comment by brouille** [comment]
M
Thanks.
I really documentation for eveything. Herbarium where specimen deposited or published paper.
Luc

De : manions <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : mercredi 13 novembre 2019 à 09:26
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] Huperzia continentalis also in Northwest Territories (#2932)


Testo et al 2016 also lists specimens verified for this species from the Northwest Territories.

**Comment by brouille** [comment]
NWT added
