### ISSUE TITLE
Assigner synonymes à espèce parente

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2935]
Carole
Svp assigner les 2 taxons suivants comme synonymes à l'espèce
Doellingeria paucicapitata
https://data.canadensys.net/vascan/taxon/32265

Aster engelmannii var. paucicapitatus B.L. Robinson
https://data.canadensys.net/vascan/taxon/11202
Aster paucicapitatus (B.L. Robinson) B.L. Robinson
https://data.canadensys.net/vascan/taxon/11203

Merci
Luc

**Comment by CaroleSinou** [comment]
The two synonym species had been erased from the database.
I've added them back in tables 'taxon' and 'taxonomy':

Aster engelmannii var. paucicapitatus B.L. Robinson
https://data.canadensys.net/vascan/taxon/11202
Aster paucicapitatus (B.L. Robinson) B.L. Robinson
https://data.canadensys.net/vascan/taxon/11203

Added Doellingeria paucicapitata (https://data.canadensys.net/vascan/taxon/32265) has parent to the previous species
