### ISSUE TITLE
Entrée de nouvelles références impossible

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2938]
Carole
L'ajout de nouvelles références est rejeté systématiquement dans l'éditeur VASCAN pour l'instant. La sauvegarde ne semble pas se faire correctement.
C'est un gros problème pour les mises à jour

Luc

**Comment by CaroleSinou** [comment]
Le problème semble ponctuel. À surveiller.
Les deux entrées en surplus ont été vidées (id 731 et 782).
