### ISSUE TITLE
Nom vernaculaire pour un hybride de bouleau

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2939]
Marc

Renée Gaudet du Jardin me faisait remarquer que l'hybride suivant n'a pas de vernaculaire français. Il y en a un en anglais.

Je te laisse libre d'en disposer. Je lui ai dit que nous ne donnions pas toujours des vernaculaires aux hybrides.

Luc

**Comment by MFavreau** [comment]
Dans le cas des hybrides, notre politique est de relever les noms français déjà existants, mais de ne pas en créer de nouveaux. Il est donc normal qu'un nom vernaculaire puisse être indiqué en anglais mais non en français.

C'est la même politique que dans le cas des taxons exclus ou présents seulement au Groenland.

Si Renée a relevé un nom français pour cet hybride, ou si elle souhaite en proposer ou demander un parce que cela répond à un besoin particulier, nous pouvons ajouter ce nom.

(Cependant, je n'arrive pas à identifier le taxon dont il s'agit.)

Je vais me charger de fermer ce point dans quelques jours s'il n'y a rien de neuf.

Marc
