### ISSUE TITLE
recognition of Cyperus engelmannii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2940]
https://data.canadensys.net/vascan/taxon/5218

Suggest recognizing Cyperus engelmannii as distinct from C. odoratus following following Fernald (1950), Swink and Wilhelm (1994), Mears and Libby (1995), Reznicek and Voss (2012), Werier (2017), and most recently Tucker and Gahdhi (2019; attached). The two seem quite distinct in southern Ontario. If recognized (e.g. following Tucker & Gandhi 2019) Canadian plants of C. odoratus belong to var. squarrosus.

[Tucker & Gandhi 2019_Nomenclatural Notes on Cyperus odoratus and Related Species (Cyperaceae).pdf](https://github.com/Canadensys/vascan-data/files/4168127/Tucker.Gandhi.2019_Nomenclatural.Notes.on.Cyperus.odoratus.and.Related.Species.Cyperaceae.pdf)

**Comment by brouille** [comment]
I am recognizing C. engelmannii. Stu Hay also agrees that it is distinct
And thanks for the var. assignement in odoratus.
My difficulty is how to assign pertinent synonyms from FNA. Being confined does not help.
Luc
