### ISSUE TITLE
Acer tataricum subsp. ginnala  - nom français

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2941]
Salut

J'ai toujours connu ce taxon sous le nom de l'érable de l'Amour. 

https://fr.wikipedia.org/wiki/Acer_tataricum_subsp._ginnala

Fred

**Comment by FredCoursol** [comment]
D'ailleurs, c'est le nom que je vais utiliser pour nos identifications au jardin botanique.

**Comment by MFavreau** [comment]
Le changement est fait.

Il n'y avait aucun obstacle (ambiguité, etc.) pour que j'inscrive « érable de l'Amour » comme nom français accepté de l'espèce. Merci beaucoup de m'avoir signalé ce nom, qui semble nettement être le plus utilisé.

J'ai conservé « érable ginnala » comme synonyme, parce que c'est le nom utilisé dans les _Arbres du Canada_et dans les _Noms communs et scienfiques de mauvaises herbes..._

Marc
