### ISSUE TITLE
Spinulum annotinum vs Lycopodium annotinum

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2943]
Salut

Petit problème avec ce nom: Lycopodium annotinum
Tu as mis Lycopodium annotinum ssp. annotinum comme un synonyme de Spinulum mais tu as oubié de le faire pour Lycopodium annotinum.
Bref, on se retrouve avec Spinulum annotinum et Lycopodium annotinum comme nom accepté.

Fred

**Comment by brouille** [comment]
correction effectuée
