### ISSUE TITLE
Lamiastrum galeobdolon - statut au Québec

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2945]
Salut

Je ne suis pas d'accord avec le statut "éphémère".  Je vois régulièrement cette plante qui persiste dans les sous-bois.  Le long de la piste cyclable du petit train du nord, je ne compte plus les endroits que je l'ai observé entre Saint-Jérôme et Prévost.
Bref, je crois que statut d'introduite au Québec et en Ontario est malheureusement mérité.

**Comment by MichaelOldham** [comment]
I agree with respect to Ontario. It seems to be well established at several places, spreading, and being reported at additional sites each year.

Mike

________________________________

**Comment by brouille** [comment]
updated both to introduced - note that both were reported from recent herbarium specimens initially, which may be why ephemeral was used
Luc
