### ISSUE TITLE
Echinocystis lobata

### ISSUE THREAD

**Issue by rosemary-curley** [Canadensys/vascan-data#2946]
_Echinocystis lobata_ is regarded as an introduced species (from central Canada for use as a trellis plant)  by David Erskine, PLants of Prince Edward Island,1960 and by Catling, Erskine and MacLaren. 1985, The Plants of Prince Edward Island  with new records... 

What information is available to show it as a native in the Canadensys map of the species? USDA also claims it is native but does not reference any PEI texts.

**Comment by brouille** [comment]
corrected to introduced for PEI
Thanks for reporting this Rosemary
Luc Brouillet

**Comment by rosemary-curley** [comment]
Luc, Thank you for your response.

Rosemary

 

Rosemary Curley 

9 Harlandview Drive

Stratford PE C1B 1W2

902-569-1209
