### ISSUE TITLE
Botrychium mormo new to Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2947]
recently documented in Ontario; see Brinker (2019)
[Brinker 2019_Botrychium mormo (Ophioglossaceae) a globally rare addition to the vascular flora of Ontario.pdf](https://github.com/Canadensys/vascan-data/files/4618172/Brinker.2019_Botrychium.mormo.Ophioglossaceae.a.globally.rare.addition.to.the.vascular.flora.of.Ontario.pdf)

**Comment by brouille** [comment]
Mike
It is already in the database. Maybe you had already informed me.
Luc

**Comment by MichaelOldham** [comment]
OK, sorry. just doing a comparison with current VASCAN list and our NHIC Ontario list.


________________________________
