### ISSUE TITLE
Amsinckia intermedia

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2948]
Salut

Enlever BC dans VASCAN
Le CDC de BC donne le statut SU (unrankable) pour A. intermedia.  Il semble que les mentions ont été réidentifiées à A. menziesii

**Comment by brouille** [comment]
Merci de cette information que je n’avais pas. Je vais aussi le noter pour FNA. Il semble que eFlora BC rapporte la var. intermedia de menziesii comme présente. Leur problème.

Luc

De : FredCoursol <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : vendredi 15 mai 2020 à 14:51
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] Amsinckia intermedia (#2948)


Salut

Enlever BC dans VASCAN
Le CDC de BC donne le statut SU (unrankable) pour A. intermedia. Il semble que les mentions ont été réidentifiées à A. menziesii
