### ISSUE TITLE
Rhus x borealis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2950]
Salut

Présent au Québec.  Jacques Labrecque et Benoit Tremblay l'ont découvert sur l'île aux Allumettes.
Le jardin botanique cultive encore des individus de cet endroit si je ne me trompe pas..
Moi même, j'ai un spécimen d'herbier de l'endroit.
Jacques Cayouette a aussi un spécimen.

Est-ce qu'un des spécimens a été déposé?  En tout cas, pas le mien.  Jacques L. pense que celui de B. Tremblay est encore dans son bureau.  Il sera déposé à QFA.

**Comment by brouille** [comment]
ajouté avec QFA
