### ISSUE TITLE
Calystegia spithamaea subsp. stans

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2951]
Salut

Belle et bien présent au Québec.  Je ne comprends pas ce qui se passe avec C. spithamaea dans VASCAN.  
Je l'ai chez moi dans ma cour (récolte de l'île aux Allumettes) et il est en fleurs.  La description colle très bien pour la subsp.

**Comment by brouille** [comment]
corrigé
LB
