### ISSUE TITLE
Drosera ×belezeana E.G. Camus est un synonyme de D. rotundifolia

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2953]
Salut

Selon un article récent paru dans Rhodora, le nom de l'hybride est Drosera × eloisiana T.S.Bailey.  Le spécimen type de belezeana correspond à rotundifolia.
https://doi.org/10.3119/20-08

**Comment by brouille** [comment]
J'ai utilisé une autre ref plus pertinente qui explique le problème: Cheek 2016
Modification faite
