### ISSUE TITLE
Campanula alternate names 

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2954]
Morin (2020) splits Campanula affecting some Canadian taxa, e.g. C. aparinoides, C. aparinoides var. grandiflora, C. uniflora.

mike
[Morin 2020_Taxonomic changes in North American Campanuloideae (Campanulaceae).pdf](https://github.com/Canadensys/vascan-data/files/5045895/Morin.2020_Taxonomic.changes.in.North.American.Campanuloideae.Campanulaceae.pdf)

**Comment by brouille** [comment]
Changes implemented in VASCAN. Will appear at next publication during the fall
Luc
