### ISSUE TITLE
misapplied common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2958]
Re: Armeria maritima (Miller) Willdenow subsp. maritima 
http://data.canadensys.net/vascan/taxon/7354?lang=en

The common name Labrador sea thrift should be applied only to subsp. siberica, not subsp. maritima, which does not have a range that includes Labrador.  See: Flora of Newfoundland and Labrador: 

https://newfoundland-labradorflora.ca/flora/view/?id=950

**Comment by brouille** [comment]
Marilyn

Please take into account this recommendation by Sue Meades and make the proper correction.
Thanks

Luc

**Comment by manions** [comment]
Many thanks for this correction. I'll be reviewing the other names (with references added) as well.
