### ISSUE TITLE
Deux synonymes à ajouter pour Thuja occidentalis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2960]
Salut

Présent dans Plants of the World Online, il faudrait bien les ajouter nous aussi.....
Thuja occidentalis f. gaspensis Vict. & J.Rousseau
Thuja occidentalis f. prostrata Vict. & J.Rousseau

**Comment by brouille** [comment]
Fred

Les formes ne sont pas inclues dans VASCAN. Je ne peux que les mettre en note dans la bd même,. ce qui n'est pas visible aux utilisateurs

Luc
