### ISSUE TITLE
Phytolacca americana

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2961]
Nom vernaculaire à ajouter
raisin d'Amérique, etc..
Voir l'article
https://jardinage.lemonde.fr/dossier-1104-raisin-amerique-phytolacca-americana-envahissant-tres-toxique.html

**Comment by MFavreau** [comment]
Merci Fred.

 

Je m’en suis tenu aux nombreux noms recensés dans le site de TelaBotanica. Plusieurs sont les mêmes, et je ne voulais pas surcharger.

 

Marc

 

De : FredCoursol <notifications@github.com> 
Envoyé : 5 septembre 2020 07:00
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] Phytolacca americana (#2961)

 

Nom vernaculaire à ajouter
raisin d'Amérique, etc..
Voir l'article
https://jardinage.lemonde.fr/dossier-1104-raisin-amerique-phytolacca-americana-envahissant-tres-toxique.html
