### ISSUE TITLE
incorrect subsp. listed from Nfld. for Tripleurospermum maritimum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2962]
Vascan has subsp. phaeocephalum (a native subsp. found on low arctic shores and beaches) reported from NL, but the FNA treatment states that subsp. maritimum (a subsp. from roadsides, field, and waste places) is introduced in NL and subsp. phaeocephalum is not present in NL.
See FNA range maps: http://data.canadensys.net/vascan/taxon/3640

Also, the few known reports from NL are all from harbours with lots of ship traffic (2 walking trails in St. John's, MUN campus; pole line at warden's station in Terra Nova NP, Harbour Grace), not natural areas.
Also, all of the ACCDC records are labelled as var. maritimum

**Comment by brouille** [comment]
Solved now in VASCAN
LB
