### ISSUE TITLE
incorrect authority for synonym of Baldellia ranunculoides subsp. repens

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2963]
http://data.canadensys.net/vascan/name/Baldellia%20ranunculoides%20subsp.%20repens?lang=en

Baldellia repens (Lamarck) Ooststroom ex Lawalrée (1973) is actually an illeg. isonym, since 
Ooststroom validated his original 1957 publication in 1959

IPNI lists:  
Baldellia repens (Lam.) Ooststr., in Heukels, Fl. Nederl., ed. 14 661 (1956), nom. inval.
Baldellia repens (Lam.) Ooststr., Bull. Jard. Bot. État Bruxelles 29(1): 7 (1959).
Baldellia repens (Lam.) Ooststr. ex Lawalrée, in Nouv. Fl. Belg., Luxemb., N. France etc. 759 (1973).

**Comment by brouille** [comment]
correction effected - E+M cited ex Lawalrée but recently changed it to Ooststr. 1956, which his also invalid - I am citing IPNI for this name, since they do indicate the 1959 validation
