### ISSUE TITLE
author citation incorrect in reference to new name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2964]
The basis for the elevation of Urtica dioica subsp. gracilis to species rank is listed as Tilo et al. 2014, but the primary author's first name is Tilo, his last name is Henning.

The citation should read Henning et al. 2014, for this entry and for Utrica dioica subsp. dioica.

See: https://ark-biodiversity.com/about/dr-tilo-henning-botanist/

**Comment by brouille** [comment]
The citation has been corrected.
Luc
