### ISSUE TITLE
Incorrect citation for basis of name change

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2965]
The basis for the elevation of Urtica dioica subsp. gracilis to species rank is listed as Tilo et al. 2014, but the primary author's first name is Tilo, his last name is Henning.

The citation should read Henning et al. 2014, for this entry and for Utrica dioica subsp. dioica.

See: https://ark-biodiversity.com/about/dr-tilo-henning-botanist/

**Comment by brouille** [comment]
This is the same correction as that of the citation. Citation corrected and thus, data entry corrected. 

Data are linked in a relational database. You need not correct all related entries, fortunately.
Luc
