### ISSUE TITLE
Luzula wahlenbergii in Labrador 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2966]
http://data.canadensys.net/vascan/taxon/6344

Labrador is excluded from the range of Luzula wahlenbergii, but in Flore Nordique (vol1, p. 419), there are 2 distribution dots in north-coastal Lab., and 1 from near Shefferville (not sure if it's in the border or not), so Labrador should be added to the range of L. wahlenbergii if these reports are correct.

**Comment by brouille** [comment]
entry corrected to native, Payette 2013+ as source
Luc
