### ISSUE TITLE
Erysimum hieraciifolium is in Labrador (HV-GB)

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2967]
http://data.canadensys.net/vascan/taxon/4045?lang=en

I sent Luc specimens of this _Erysimum_ from the Goose Bay area, collected in 2017; yet Labrador has not yet been added to the introduced range of this species.  Erysimum hieraciifolium was growing along many roadsides, esp. those in the base and along the highway between Goose Bay and Happy Valley; well established, often growing with Potentilla norvegica and Crepis tectorum (the Crepis was IDed by Luc).

**Comment by brouille** [comment]
entered
