### ISSUE TITLE
Euphrasia farlowii not reported from Labrador by Gussarova

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2968]
In Gussarova's 2017 paper on Euphrasia (page 290), she includes this sentence about the range of Euphraisa farlowii, which indicates she only reported it from the Island:

"Flowering mid summer–fall. Dry, grassy habitats on sandstone or limestone barrens, rocks, ledges, sand beaches; 0–300 m; N.B., **Nfld. and Labr. (Nfld.),** N.S., Ont., P.E.I.; Maine." 

Unless you have specimens of Euphrasia farlowii from Labrador, Labrador should be removed from its range.

**Comment by brouille** [comment]
LAbrador removed
