### ISSUE TITLE
Botrychium lineare and B. campestre taxonomy

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2969]
https://data.canadensys.net/vascan/taxon/3855

Farrar and Gilman (2017) suggest that Botrychium lineare should be considered a variety of B. campestre.

[Farrar & Gilman 2017_Relationships in the Botrychium campestre (Ophioglossaceae) complex.pdf](https://github.com/Canadensys/vascan-data/files/5501666/Farrar.Gilman.2017_Relationships.in.the.Botrychium.campestre.Ophioglossaceae.complex.pdf)

**Comment by brouille** [comment]
Change made
LB
