### ISSUE TITLE
Solanum physalifolium et Cyperus odoratus var. squarrosus sont des plantes herbacées!

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#2972]
Allô!

Les IDs 9382 (Solanum physalifolium) et 32304 (Cyperus odoratus var. squarrosus) n’ont pas de données indiquant que ce sont des « herb ».

https://data.canadensys.net/vascan/taxon/9382
https://data.canadensys.net/vascan/taxon/32304

En fait, les IDs n’apparaissent pas dans le fichier de métadonnées \dwca-vascan-v37.9\description

Pour quelqu’un qui ne fait pas attention, cela peut devenir une source d’erreurs lorsqu’on rassemble les fichiers individuels en un seul.

Merci de regarder ça Luc!

Alex

**Comment by brouille** [comment]
Merci de ce rapport. C'est maintenant corrigé.
LB
