### ISSUE TITLE
Palustricodon aparinoides var. grandiflorus

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2973]
https://data.canadensys.net/vascan/taxon/32524

Var. grandiflorus (=Campanula uliginosa) is recognized by Morin (2020) but is not in VASCAN, though var. aparinoides is. Var. grandiflorus occurs in SK, MB, ON, QC, NB (Scoggan 1979).

**Comment by brouille** [comment]
I simply missed this one. Thanks. Variety added with Scoggan as source.
L
