### ISSUE TITLE
accept Juncus biflorus for ON

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2975]
https://data.canadensys.net/vascan/taxon/16812

Although no Canadian specimens of Juncus biflorus are cited by Knapp & Naczi (2008), J. biflorus is well documented from Ontario, particularly in the Windsor prairie area with numerous specimens in herbaria (e.g. CAN, DAO, MICH, TRT, NHIC). Mapped from Ontario by Argus et al. (1987; attached
[Juncus biflorus  from Brownell et al 1987_Juncaceae ARVPO.pdf](https://github.com/Canadensys/vascan-data/files/5585663/Juncus.biflorus.from.Brownell.et.al.1987_Juncaceae.ARVPO.pdf)
).

**Comment by brouille** [comment]
native, Brownell & Catling 1987 cited as source
LB
