### ISSUE TITLE
Castilleja miniata introduced in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2977]
https://data.canadensys.net/vascan/taxon/6991

Although it has been considered native by some authors, we consider Castilleja minata (and var. miniata) introduced in Ontario since the sole Ontario record consists of a single clump along a railway right-of-way quite far east of the Manitoba border we are considering the species non-native to Ontario. It has not been seen in the province since 1963.

**Comment by brouille** [comment]
Mike
I believe you are correct it is not native. However, since a single clump was seen more than 50 years ago, if I apply the criteria used in VASCAN, I should exclude it as either ephemeral or old report not followed by more sightings. Do you agree?
Luc

**Comment by MichaelOldham** [comment]
Hi Luc,

Yes, I think it makes most sense to call this an ephemeral introduction since I don't know of any other Ontario records.

mike

*********************************************************
Michael J. Oldham
Provincial Botanist
Ontario Natural Heritage Information Centre (NHIC)
Ministry of Natural Resources and Forestry
300 Water Street, 2nd Floor, North Tower
P.O. Box 7000 Peterborough, Ontario K9J 3C7, Canada

michael.oldham@ontario.ca<mailto:michael.oldham@ontario.ca>
NHIC requests: NHICrequests@ontario.ca<mailto:NHICrequests@ontario.ca>
NHIC web page: https://www.ontario.ca/page/natural-heritage-information-centre


________________________________

**Comment by brouille** [comment]
done, will appear at next publication
