### ISSUE TITLE
add Magnolia kobus for Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2978]
Magnolia kobus has been documented as a naturalized introduced species in Hamilton (see Moesker 2019; attached).
[Moesker 2019_Magnolia kobus; a study of the popular horticultural species and its recent invasion of native ecosystems in Ontario, Canada.pdf](https://github.com/Canadensys/vascan-data/files/5590601/Moesker.2019_Magnolia.kobus.a.study.of.the.popular.horticultural.species.and.its.recent.invasion.of.native.ecosystems.in.Ontario.Canada.pdf)

**Comment by brouille** [comment]
Added. Thanks for raising this, particularly as it seems to have been also introduced recently in the USA and was not in FNA 3.

Marilyn and Marc: Add appropriate vernacular please
Luc

**Comment by MFavreau** [comment]
French name added.  The names «magnolia de Kobus» and «magnolia de Kobé» have been used in the past, but they are incorrect, since Kobus is the Japanese name of the plant, and not a place name or person's name.

**Comment by manions** [comment]
English vernaculars added. Many thanks for the pdf.

**Comment by MFavreau** [comment]
I changed the accepted Franch name, after receiving an interesting suggestion from Marie D'Aoûst, based on the meaning of the Japanese name
