### ISSUE TITLE
consider Mentha x gracilis for Mentha x gentilis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2979]
https://data.canadensys.net/vascan/taxon/6408?lang=en

According to Tucker and Naczi (2007; attached) the correct name for M. arvensis X M. spicata is M. x gracilis. Haines (2011; Flora Novae-Angliae) considers M. gentilis to be a pollen-sterile clone of M. arvensis.
[Tucker & Naczi 2007_Mentha - an overview of its classification and relationships.pdf](https://github.com/Canadensys/vascan-data/files/5590683/Tucker.Naczi.2007_Mentha.-.an.overview.of.its.classification.and.relationships.pdf)

**Comment by brouille** [comment]
Treatment by Tucker & Naczi considered for all Mentha in Canada. Several small corrections made, in addition to the one requested
LB
