### ISSUE TITLE
consider Nasturtium x sterilis introduced

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2980]
https://data.canadensys.net/vascan/taxon/4084

Nasturtium x sterilis is considered native in Ontario, though both parental species are considered introduced.

**Comment by brouille** [comment]
Mike
This is a complicated issue: both parents are introduced, but is the hybrid also introduced from its native range, or was it created de novo in Ontario, in a manner that could be qualified of native?
I do not have  a set answer for this. But I have seen others call such hybrids native. For instance, the famous allopolyploids of Tragopogon in the western US are considered native, while both parents are introduced.
Luc

**Comment by brouille** [comment]
done, but the question remains concerning whether the hybrid occurred in NA or came from Europe
