### ISSUE TITLE
author name for scientific name authority for Urtica gracilis

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2982]
https://data.canadensys.net/vascan/taxon/21468?lang=en

Senior author's name is Tilo Henning for recognizing the name Urtica gracilis, so should be Henning et al. 2014 rather than Tilo et al. 2014

**Comment by brouille** [comment]
Mike

This has already been taken care of, having been flagged by another collaborator. Thanks nonetheless, I appreciate your input. Will appear at the next publication (end of year).

Luc
