### ISSUE TITLE
names of Symphyotrichum laeve subsp. laeve varieties

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2983]
https://data.canadensys.net/vascan/taxon/31184

Why are S. laeve var. geyeri and S. laeve var. laeve not called S. laeve ssp. laeve var. geyeri and S. laeve ssp. laeve var. laeve as is done for varieties of S. lanceolatum ssp. lanceolatum?

**Comment by brouille** [comment]
adjustment made
LB
