### ISSUE TITLE
re: synonym of Ulmus glabra; author correction for Ulmus montana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2984]
Ulmus montana With. is listed as a synonym of Ulmus glabra in VASCAN.  While Withering did publish this name in the 1796 version of  _A Botanical Arrangement of British Plants._  (2nd edition, vol 2),  J. Stokes published this previously in the 1st volume, page. 259-260, published in 1787.  Withering's descriptions includes much of what Stokes had written in 1787.  See: https://www.biodiversitylibrary.org/item/254906#page/341/mode/1up

IPNI attributes Ulmus montana to Stokes (1787), Bot. Arr. Brit. Pl., ed. 2. 1: 259.
and also lists the later combination by Withering as published in  Bot. Arr. Brit. Pl. ed. III. ii. 279, no date given, 
but I found it in BHL, the 3rd edition of Bot. Arr. Brit. Pl. vol. 2: 279 (1796)
https://www.biodiversitylibrary.org/item/199820#page/305/mode/1up

Unless Stokes name is invalid for some reason, Withering]s combination is an isonym of Stokes 1787 name.

**Comment by brouille** [comment]
This needs correction in FNA also. I must consult K. Gandhi and provide him with the info on the date for Withering
I cannot remove a name by changing the authority (unless the other does not exist); thus I need to know what the status of the With. name is: illegitimate?
Luc

**Comment by brouille** [comment]
correction made - Stokes added, With. nom. illeg.

LB
