### ISSUE TITLE
Authority of Allium schoenoprasum var. sibiricum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#2985]
In most online publications, the author of var. sibiricum is listed as (L.) Hartm., but IPNI does not give a reference, so dates could not be compared to var. sibiricum (L.) Garcke (1849).  
 I looked at publications by C.J. Hartman and found his earlier publication (**1843**) in Handb. Skand. Fl. (ed. 4) 102-103. 

A pdf of this publication can found at: 
https://bibdigital.rjb.csic.es/en/records/item/15933-handbok-i-skandinaviens-flora-fjerde-4ordf-upplagan-rattad-och-forokad

Here is a screen shot of the entry on pages 102-103:
![image](https://user-images.githubusercontent.com/11757179/100644710-acb1fc80-3309-11eb-9992-c09a7d7854b9.png)

Unless Hartman's combination is illegitimate or invalid, Allium schoenoprasum var. sibiricum (L.) Hartm. (1843) should have priority over A. schoenoprasum var. sibiricum (L.) Garcke (1849).

**Comment by brouille** [comment]
Solved: authority corrected to Hartman
LB
