### ISSUE TITLE
Autorité de Lonicera canadensis

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#2987]
Salut!
Vascan inscrit:
Lonicera canadensis Bartram ex Marshall
https://data.canadensys.net/vascan/taxon/4205?lang=fr

Tropicos et IPNI inscrivent plutôt:
Lonicera canadensis Bartram & W.Bartram ex Marshall 
https://www.ipni.org/n/148665-1

**Comment by brouille** [comment]
corrigé
LB
