### ISSUE TITLE
Autorité de Utricularia vulgaris subsp. macrorhiza 

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#2988]
Salut!

Vascan inscrit:
Utricularia vulgaris subsp. macrorhiza (Leconte ex Torrey) R.T. Clausen
https://data.canadensys.net/vascan/taxon/6505 

Tropicos et IPNI inscrivent plutôt:
Utricularia vulgaris subsp. macrorhiza (Leconte) R.T. Clausen
https://www.tropicos.org/name/18300009
https://www.ipni.org/n/260872-2

À vérifier...

**Comment by brouille** [comment]
corrigé 
LB
