### ISSUE TITLE
Autorité de Parthenocissus quinquefolia

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#2989]
Salut!

VASCAN inscrit :
Parthenocissus quinquefolia (Linnaeus) Planchon ex de Candolle est un nom accepté d'espèce sensu FNA Ed. Comm., 2016.
https://data.canadensys.net/vascan/taxon/9539

Mais FNA Ed. Comm., 2016 reconnaît plutôt : 
Parthenocissus quinquefolia (Linnaeus) Planchon
http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=220009987

En fait, le nom est imputé à A. L. P. P. de Candolle and C. de Candolle, Monogr. Phan. 5: 448. 1887, mais n’est pas attribué à de Candolle (DC.; Augustin Pyrame de Candolle) qui était mort (1841) au moment de la publication. 

À vérifier ;)

**Comment by brouille** [comment]
corrigé
LB
