### ISSUE TITLE
Autorité de Zanthoxylum americanum

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#2990]
Salut!
Vascan inscrit: Zanthoxylum americanum P. Miller
https://data.canadensys.net/vascan/taxon/9041

Mais l’abréviation de Philip Miller habituellement utilisé dans FNA est : Miller
Par exemple, Abies balsamea (Linnaeus) Miller
https://data.canadensys.net/vascan/taxon/7159

Par soucis d’uniformité, il serait souhaitable d’inscrire : Zanthoxylum americanum Miller

À vérifier ;)

**Comment by brouille** [comment]
corrigé LB
