### ISSUE TITLE
Autorité de Uvularia grandiflora

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#2991]
Salut!

Vascan inscrit: Uvularia grandiflora J.E. Smith
https://data.canadensys.net/vascan/taxon/4597

Mais l’abréviation de James Edward Smith habituellement utilisé dans FNA est : Smith
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242102041

Ailleurs dans VASCAN, on trouve aussi ce conflit d’abréviations.
Par exemple, Poa flexuosa J.E. Smith et Populus ×canescens (Aiton) Smith proviennent tous deux du même auteur. 
https://data.canadensys.net/vascan/taxon/18731
https://data.canadensys.net/vascan/taxon/9058

Par soucis d’uniformité, il serait souhaitable de toujours utiliser la même abréviation, en l’occurrence : Smith

À vérifier ;)

**Comment by brouille** [comment]
au début de VASCAN, on utilisait les abbréviations des prénoms pour tous les auteurs. Nous avons changé depuis, mais tout n'a pas été attrapé car il n'y pas de façon de faire cela globalement

corrigé
LB

**Comment by AlexBERGER0N** [comment]
OK, merci Luc pour cette explication.  Au terme du travail que je réalise actuellement, sache qu'il y aura au moins 640 taxons du Québec dont les abréviations d'auteurs seront conformes.

Alex
