### ISSUE TITLE
Autorité de Prunus ×cistena

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#2992]
Salut!

Vascan inscrit: Prunus ×cistena (N. E. Hansen) Koehne
https://data.canadensys.net/vascan/taxon/28716

Ailleurs sur internet on trouve souvent cette graphie, mais peu de sources semblent fiables pour l’attester. 

IPNI n’a aucune entrée pour ce taxon.

Tropicos inscrit : Prunus × cistena N.E. Hansen
https://www.tropicos.org/name/100435815

The Plant List inscrit : Prunus × cistena N.E. Hansen ex Koehne
http://www.theplantlist.org/tpl1.1/record/rjp-40589

Ici, je suis d’avis que c’est the Plant List qui utilise la graphie la plus conforme au Code international de nomenclature.

Il semble que ce soit Koehne (un botaniste) qui a fait la première diagnose publiée du taxon et a attribué le nom à N.E. Hansen, lequel était l’horticulteur qui a créé cet hybride de cerisier. Il ne s’agit pas d’une nouvelle combinaison. Par conséquent, la parenthèse n’a pas sa place.

À vérifier ;)

Les sites de références des publications d’origines
https://www.biodiversitylibrary.org/item/49730#page/6/mode/1up
https://catalog.hathitrust.org/Record/100103065

La description très sommaire du nouvel hybride par N.E. Hansen
![Cistena](https://user-images.githubusercontent.com/74797447/102260137-04419200-3ede-11eb-84cf-a1ab68eb78c2.JPG)

La diagnose botanique par Koehne
![P  cistena](https://user-images.githubusercontent.com/74797447/102260176-14597180-3ede-11eb-9a7c-729f93351733.JPG)

**Comment by brouille** [comment]
Alex

Merci d'avoir souligné ceci. Le cas des plantes d'origine horticole est souvent compliqué. Je vais changer pour ex Koehne étant donné le protologue. J'avais suivi les auteurs qu'on m'avait fournis dans l'issue VASCAN.

Luc
