### ISSUE TITLE
Adoxaceae vs Viburnaceae

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#2993]
Salut Luc!

Je ne sais pas à quel point vous pouvez ajouter des références dans VASCAN, mais je dois admettre que je ne comprenais pas bien le choix d'utiliser le nom Viburnaceae qui va à l'encontre d'APG IV et de son désir de stabilité nomenclaturale. En grattant davantage, je suis tomber sur la recommandation du Nomenclature Committee for Vascular Plants qui a rejeté Adoxaceae par le vote: Wilson, K. L. (2016). Report of the General Committee: 15. Taxon, 65(5), 1150-1151.
Peut-être que cet ajout de référence serait souhaitable avant la sortie incertaine de Viburnaceae - FNA Ed. Comm., in prep. k.
À voir!

**Comment by brouille** [comment]
Alex
Ce n'est pas pcq APG adopte un nom pour un taxon qu'il est nécessairement correct. Peu de gens avaient considéré Viburnaceae auparavant. Ici, comme je suis FNA, je ne mettrai pas d'autre référence. Il est impossible de tout expliquer dans une base de données et cela deviendrait beaucoup trop difficile à maintenir.
Luc
