### ISSUE TITLE
Microgilia English vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2994]
Marylin
There is no reference to English vernaculars for Microgilia minutiflora
Also, the currently accepted name is not used or even mentioned in eFlora BC (small-flowered ipomopsis) nor FNA (Small-flowered gilia, littleflower ipomopsis, small-flowered standing-cypress). It seems doubtfully appropriate.
Thanks for taking care of this.
Luc

**Comment by manions** [comment]
reviewed English names for Microgilia, Gilia, and Ipomopsis with references
