### ISSUE TITLE
Autorité de Collomia heterophylla

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#2995]
Salut

FNAms a seulement Hooker comme autorité et non Douglas ex Hooker.

**Comment by brouille** [comment]
Merci Fred

J’avais manqué cela. Gandhi n’a pas encore réagi à ce manuscrit pour la nomenclature.

Luc

De : FredCoursol <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : mercredi 3 février 2021 à 14:28
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] Autorité de Collomia heterophylla (#2995)


Salut

FNAms a seulement Hooker comme autorité et non Douglas ex Hooker.

**Comment by brouille** [comment]
J’ai corrigé VASCAN. TROPICOS et IPNI ont Hooker.
Luc

De : FredCoursol <notifications@github.com>
Répondre à : Canadensys/vascan-data <reply@reply.github.com>
Date : mercredi 3 février 2021 à 14:28
À : Canadensys/vascan-data <vascan-data@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : [Canadensys/vascan-data] Autorité de Collomia heterophylla (#2995)


Salut

FNAms a seulement Hooker comme autorité et non Douglas ex Hooker.
