### ISSUE TITLE
Wrong classification in DwC-A of Checklist of Beetles (Coleoptera) of Canada and Alaska. Second Edition.

### ISSUE THREAD

**Issue by mdoering** [Canadensys/vascan-data#2996]
The classification of the [Canadian beetles checklist DwC-A](https://data.canadensys.net/ipt/resource.do?r=coleoptera-ca-ak) as interpreted by [GBIF](https://www.gbif.org/dataset/7a9bccd4-32fc-420e-a73b-352b92267571) seems dubious:

Major issues:
 - [Animalia](https://www.gbif.org/species/100149004) has Arthropoda twice
 - subfamilies and tribes of [Coccinellidae](https://www.gbif.org/species/100153515) are all empty, e.g. [Coccinellinae](https://www.gbif.org/species/100153574). Probably this applies to other families as well

**Comment by mdoering** [comment]
The meta.xml does use a flat rank format and is missing the dwc:parentNameUsageID term to establish a flexible hierarchy with more than just the major Linnean ranks. Subfamily and tribe for example is not usable like this.

Please use dwc:parentNameUsageID, dwc:acceptedNameUsageID & dwc:originalNameUsageID instead of kingdom, phylum, class, order, family, genus & subgenus.

**Comment by brouille** [comment]
I transferred the issue to Canadensys since this is not a VASCAN issue per se.

Thank you for having raised this.

Luc Brouillet
