### ISSUE TITLE
Palustricodon aparinoides var. grandiflorus : vernaculars needed

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#2997]
Colleagues, 
in preparation of her FNA treatment, Nancy Morin published numerous names in a recent paper, a few of which pertain to Canada.
Palustricodon aparinoides var. grandiflorus is an entity not previously recognized in VASCAN (though Scoggan mentions it). There are no vernaculars for it. As for P. a. var. aparinoides, I kept the original vernaculars from Campanula. You may wich to revise this also.
Luc

**Comment by MFavreau** [comment]
French names checked and/or added.

Marc

**Comment by manions** [comment]
completed English names review
