### ISSUE TITLE
Pyrola asarifolia X P. minor

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#2998]
Haber (1984) also cites specimens from ON, AB, BC, NT
[Haber 1984_A comparative study of Pyrola minor × Pyrola asarifolia (Ericaceae) and its parental species in North America.pdf](https://github.com/Canadensys/vascan-data/files/6022464/Haber.1984_A.comparative.study.of.Pyrola.minor.x.Pyrola.asarifolia.Ericaceae.and.its.parental.species.in.North.America.pdf)

**Comment by brouille** [comment]
Thanks Mike.
I was lacking a reference to the hybrid and to its distribution. Data added.
Luc
