### ISSUE TITLE
Clinopodium arkansanum 

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#30]
[Originally posted on GoogleCode (id 1420) on 2012-09-19]

Selon The Plant List 
Clinopodium arkansanum (Nutt.) House is a synonym of Clinopodium glabrum (Nutt.) Kuntze

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-09-19 19:53Z]

FNA accepte ce nom, l'un des syn. étant glabrum var. arkansanum - ce qui justifie sans doute la décision de PL
