### ISSUE TITLE
Isoetes minima : vernaculars required

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3000]
Marc and Marilyn:

Previously considered a syn of I. howellii, I. minima is now recognized as distinct. eFlora of BC has it in its list. Vernacular names are required. In English, eFlora BC suggested "midget quillwort", which I input. You may wish to change this Marilyn. No French, however.
Luc

**Comment by MFavreau** [comment]
Actually, _Isoetes minima_ had been an accepted name in a 20th century version of VasCan, as taxon 6804, before being synonymized to _I. howellii_.

So, welcome back « isoète minuscule ».  No English name had yet been chosen at the time.

**Comment by manions** [comment]
English vernacular checked, thanks
