### ISSUE TITLE
Isoetes ×blondeaui hyb. nov.

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3001]
https://cdnsciencepub.com/doi/abs/10.1139/cjb-2020-0065

**Comment by brouille** [comment]
déjà entré

**Comment by FredCoursol** [comment]
Salut

Quand une mise à jour est prévue?

Envoyé de mon iPhone

Le 2 avr. 2021 à 2:29 PM, brouille ***@***.***> a écrit :

﻿

déjà entré

**Comment by brouille** [comment]
Bientôt

De : FredCoursol ***@***.***>
Répondre à : Canadensys/vascan-data ***@***.***>
Date : vendredi 2 avril 2021 à 14:31
À : Canadensys/vascan-data ***@***.***>
Cc : Luc Brouillet ***@***.***>, State change ***@***.***>
Objet : Re: [Canadensys/vascan-data] Isoetes ×blondeaui hyb. nov. (#3001)

Salut

Quand une mise à jour est prévue?

Envoyé de mon iPhone

Le 2 avr. 2021 à 2:29 PM, brouille ***@***.***> a écrit :



déjà entré
