### ISSUE TITLE
Isoetes tenella supprimé par mégarde

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3002]
Carole
Pourrais-tu réinstituer le nom 16690 Isoetes tenella, supprimé par mégarde, svp?
Il était synonyme de I. echinospora auparavant, mais il faudrait le placer en synonymie de 6218 I. lacustris

Je pourrai ensuite faire les corrections qui s'imposent à ce nom

Merci
Luc

**Comment by CaroleSinou** [comment]
Isoetes tenella Léman (id=16690) a été ajouté à la table 'taxon' et à la table 'taxonomy' en tant que synonyme de Isoetes lacustris (id=6218).
