### ISSUE TITLE
check placement of synonym of Baptisia alba var. macrophylla

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3003]
Baptisia alba var. macrophylla is listed as a synonym of B. leucophaea, however isn't it a synonym of Baptisia lactea (or B. lactea var. lactea)?
I haven't see the FNA draft, but Weakley 2020 lists B. alba var. macrophylla with B. lactea.
Perhaps listed by mistake with B. leucophaea?
Thanks for checking, as working on the English vernaculars.

**Comment by brouille** [comment]
In the FNA treatment, it is a synonym of leucophaea. I do not know whether there have been modifications since.  Will know only when volume is published (soonish).
