### ISSUE TITLE
Family name change: Xanthorrhoeaceae to Asphodelaceae (APG IV, 2016).

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3004]
re:  Family Xanthorrhoeaceae:  http://data.canadensys.net/vascan/name/Xanthorrhoeaceae?lang=en 

In APG IV, the Family Xanthorrhoeaceae is now included within the Asphodelaceae, reduced in rank to: Xanthorrhoeoideae, along with .

See: http://www.mobot.org/MOBOT/Research/APweb/
Near the end of the family description, see this explanation: 
Classification. A.P.G. II (2003) suggested as an option the inclusion of Asphodelaceae, Xanthorrhoeaceae and Hemerocallidaceae in Xanthorrhoeaceae s.l., and this circumscription was adopted by A.P.G. III (2009), but because of nomenclatural issues the name of this clade has been changed to Asphodelaceae (A.P.G. IV 2016), otherwise, see Chase et al. (2009b). The recognition of an Alooideae (= Asphodeloideae-Aloeae) would make Asphodeloideae paraphyletic and necessitate the recognition of several other weakly characterized subfamilies.

**Comment by brouille** [comment]
Sue
Change made according to APG IV.
LB

**Comment by brouille** [comment]
Marc and Marilyn
I replaced the family name Xanthorrheaceae by Asphodelaceae. We need vernacular names for the latter (I had to remove those of the former to put it in synonymy)
Merci
Luc

**Comment by MFavreau** [comment]
Nom français ajouté.
Marc

**Comment by manions** [comment]
English name for family entered
