### ISSUE TITLE
remove Solidago arguta var. arguta

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#3005]
https://data.canadensys.net/vascan/taxon/23416?lang=en

Solidago arguta var. arguta no longer recognized in most recent revision of Section Argutae (Semple et al. 2021).
[Semple et al 2021_A multivariate study of Solidago sect. Argutae (Asteraceae; Astereae).pdf](https://github.com/Canadensys/vascan-data/files/6344582/Semple.et.al.2021_A.multivariate.study.of.Solidago.sect.Argutae.Asteraceae.Astereae.pdf)

**Comment by brouille** [comment]
taxonomy corrected acc to latest Semple account
