### ISSUE TITLE
recognition of Phacelia purshii var. purshii

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#3006]
https://data.canadensys.net/vascan/name/Phacelia%20purshii

Levy (2020) recently suggested that the southern Phacelia boykinii be recognized as a variety of Phacelia purshii making more northern plants such as those in Ontario, var. purshii.
[Levy 2020_Evaluation of the taxonomy of Phacelia purshii (Hydrophyllaceae).pdf](https://github.com/Canadensys/vascan-data/files/6384716/Levy.2020_Evaluation.of.the.taxonomy.of.Phacelia.purshii.Hydrophyllaceae.pdf)

**Comment by brouille** [comment]
variety added and database entry modified appropriately
Luc
