### ISSUE TITLE
Linnaea borealis - problème avec la répartition des sous-espèces

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3007]
Salut
Je crois qu'il y a eu l'inversion au niveau de la répartition des sous-espèces dans VASCAN.  
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0116485
À moins que c'est l'article qui soit dans l'erreur.  Je n'ai pas vérifié les manuscrits de FNA

**Comment by AlexBERGER0N** [comment]
Intéressant! Ça m'a donné le goût de fouiller un peu le sujet ce matin (j'suis en congé). C'est peut-être l'article qui est dans l'erreur ou, du moins, il a été écrit en 2015 avant l'article de Zika & Tucker (2017). Ces derniers auteurs ne reconnaissent pas la présence de trois rangs infraspécifiques au sein de Linnaea borealis. Ils incluent ssp. americana dans ssp. longiflora. Reste à savoir la position adoptée par FNA!    

Zika, P. F., & Tucker, G. C. (2017). Variation in Linnaea borealis (Linnaeaceae) across North America and Greenland. Journal of the Botanical Research Institute of Texas, 11(1), 67-79.

**Comment by brouille** [comment]
La répartition infrasp. de Linnaea a été un problème continu. Les concepts taxonomiques changent avec les auteurs, etc. En fait, j'attends la version de FNA. Je vais néanmoins tenir compte des articles mentionnés pour me faire un jugement.
LB

**Comment by brouille** [comment]
J'ai résolu le problème en excluant la subsp. borealis de BC comme "misidentification". La source est Zika & Tucker. La répartition canadienne devient entièrement subsp. longiflora.
Luc
