### ISSUE TITLE
incorrect spelling for authority of Equisetopsida C. Agardh

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3008]
On the Class name for all entries, the authority's name is spelled C. Ahgard, rather than the correct spelling: C. Agardh.

See IPNI authors: https://www.ipni.org/a/30668-1

**Comment by sjmeades** [comment]
Actually, it's spelled now as Aghard, nor Ahgard; that;s my typo in the comment above, but the spelling online should be corrected to C. Agardh.  See the IPNI author entry.

**Comment by brouille** [comment]
You are right, but curiously, the program for editing currently does not let me do it. I have to contact Canadensys to see that it be corrected directly in the database.

**Comment by brouille** [comment]
Carole

Lorsque je tente de corriger C. Aghard en C. Agardh (ce qui est d'ailleurs un nom inscrit dans la bd), le logiciel me retourne l'erreur: Erreur interne: Paramètre invalide, 1, nul, nul, Equisetopsida
Je suis donc incapable de faire le changement nécessaire.
Peux-tu le faire directement dans la base de données svp?
Luc

**Comment by CaroleSinou** [comment]
Le changement a été fait dans la base de données et est visible dans l'éditeur Vascan.
Il sera visible dans https://data.canadensys.net/vascan/ lors de la prochaine publication de Vascan.
