### ISSUE TITLE
Rhamnus dauurica vs davurica

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3009]
Salut

À corriger dans VASCAN.  Il faut utiliser le double u
http://www.plantsoftheworldonline.org/taxon/urn:lsid:ipni.org:names:718301-1

**Comment by brouille** [comment]
POWO a souvent des erreurs de taxonomie, graphie, distribution, etc.
Tant TROPICOS que IPNI écrivent: Rhamnus davurica publié sous "dauurica" , ce qui implique une correction orthographique de la graphie originale. Je ne suivrai pas POWO ici.
Luc

**Comment by MFavreau** [comment]
Article 60.5 du Code de Shenzhen s'applique ici et qu'il faut écrire _davurica_

60.5 Quand un nom a été publié dans un ouvrage où les lettres u, v ou i, j sont utilisées de manière
interchangeable ou de toute autre manière incompatible avec les pratiques typographiques modernes
(p. ex. une lettre d'une paire n'étant pas utilisée en majuscule, ou pas utilisée du tout),
ces lettres doivent être transcrites conformément à la pratique nomenclaturale moderne.
When a name has been published in a work where the letters u, v or i, j are used interchangeably
or in any other way incompatible with modern typographical practices (e.g. one letter of a pair
not being used in capitals, or not at all), those letters are to be transcribed in conformity with
modern nomenclatural usage.
Ex. 11. Curculigo Gaertn. (Fruct. Sem. Pl. 1 : 63. 1788), non pas 'Cvrcvligo' ; Taraxacum Zinn (Cat. Pl.
Hort. Gott. : 425. 1757), non pas 'Taraxacvm' ; Uenbachia Fabr. (Enum., ed. 2 : 21. 1763), non
pas 'Venbachia'.
Curculigo Gaertn. (Fruct. Sem. Pl. 1 : 63. 1788), not 'Cvrcvligo' ; Taraxacum Zinn (Cat. Pl.
Hort. Gott. : 425. 1757), not 'Taraxacvm' ; Uenbachia Fabr. (Enum., ed. 2 : 21. 1763), not
'Venbachia'.
Ex. 12. 'Geastrvm hygrometricvm' et 'Vredo pvstvlata' de Persoon (dans Syn. Meth. Fung. : 135, 219
1801) devraient être orthographiés respectivement Geastrum hygrometricum Pers. : Pers. et Uredo
pustulata Pers. : Pers.
'Geastrvm hygrometricvm' and 'Vredo pvstvlata' of Persoon (in Syn. Meth. Fung. : 135, 219 1801)
are spelled, respectively, Geastrum hygrometricum Pers. : Pers. and Uredo pustulata Pers. : Pers.
