### ISSUE TITLE
Carex ×exsalina, C. vacillans et problèmes avec les parents hybrides 

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#3010]
Salut Luc,

Selon VASCAN, Carex ×exsalina Lepage est l’hybride de :
Carex nigra (Linnaeus) Reichard et Carex paleacea Schreber ex Wahlenberg.
https://data.canadensys.net/vascan/taxon/5155?lang=fr

Mais selon Cayouette & Catling (1992) et FNA Ed. Comm. (2002), Carex ×exsalina Lepage est l’hybride de :
Carex bigelowii Torrey ex Schweinitz et Carex paleacea Schreber ex Wahlenberg.
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242357382

Et l’on peut continuer dans l’arborescence de la base de données…
Selon VASCAN, Carex vacillans Drejer (synonyme de Carex ×subnigra Lepage) est l’hybride fertile de Carex paleacea × Carex vacillans. 
https://data.canadensys.net/vascan/taxon/5133?lang=fr

Mais selon Cayouette & Catling (1992) et FNA Ed. Comm. (2002), C. vacillans Drejer est l’hybride de :
Carex nigra (Linnaeus) Reichard et Carex paleacea Schreber ex Wahlenberg.
http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242357382

En revanche, la page VASCAN de l’hybride introgressif Carex paleacea × Carex vacillans nomme adéquatement ses parents. 
https://data.canadensys.net/vascan/taxon/5016?lang=fr

Voilà!
Alex

**Comment by brouille** [comment]
exsalina corrigé

en ce qui concerne vacillans, ce qui est indiqué sur la page n'est pas que vacillans a les parents indiqués, mais qu'il est l'un des parents de l'hybride introgressif indiqué - je n'avais pas donné le parentage hybride dans ce cas précis car il s'agissait d'un taxon stabilisé selon Cayouette - indiquer les parents de l'hybride lui ayant donné naissance pourrait porter à confusion (hybride ou non?)

Luc
