### ISSUE TITLE
Query for elucidation on species Glyceria striata and its variety striata, Fowl Mannagrass

### ISSUE THREAD

**Issue by JohnBoydell** [Canadensys/vascan-data#3012]
Would someone be wiling to help a layperson?
I am unable to find any other source for _Glyceria striata_ and its variety _striata_ being Native to Ontario.
boydelljr@gmail.com

**Comment by brouille** [comment]
Glyceria striata is reported as S5 in Ontario by Newmaster & Ragupathy, 2005 in FOIBIS https://www.uoguelph.ca/foibis/search_db.cfm
The subsp. was determined from Soreng et al., Catalogue of New World Grasses, and authoritative source available through TROPICOS
Luc Brouillet
