### ISSUE TITLE
Tiarella stolonifera

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3014]
Salut

Il faut changer notre Tiarella cordifolia pour Tiarella stolonifera.
Voir l'article de Nesom (2021)
http://www.phytoneuron.net/2021Phytoneuron/31PhytoN-Tiarella.pdf

**Comment by AlexBERGER0N** [comment]
Bon! C'est ça qui est ça! Merci de l'info Fred!

**Comment by brouille** [comment]
Marc et Marilyn

A major change occurred in the species of Tiarella found in eastern Canada: Tiarella cordifolia is restricted to the southern US and a new species was described by Nesom 2021 (see ref above): T. stolonifera. Unfortunately, given that the cordifolia entity still exists, the vernaculars for it cannot simply be applied to stolonifera, in my opinion. We thus need new names for the species in Canada, both French and English

The data entry for cordifolia has been modified (excluded), and a new entry added for stolonifera.
Luc

**Comment by MFavreau** [comment]
J'ai inscrit le nom français « tiarelle stolonifère », qui me semble approprié. J'ai laissé les anciens noms faisant référence à la forme de la feuille dans la fiche portant sur le T. cordifolia sensu stricto, même si ce taxon est désormais exclu de la flore canadienne.

**Comment by manions** [comment]
English vernacular added for T. stolonifera. Many thanks for the pdf.
