### ISSUE TITLE
Streptopus lanceolatus var. longipes

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#302]
[Originally posted on GoogleCode (id 533) on 2011-06-10]

Streptopus lanceolatus:

Determine accepted var. of syn.:
S. lanceolatus var. longipes (Fernald) Reveal
S. longipes Fernald
S. roseus var. longipes (Fernald) Fassett

http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=242101973

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-07-03 12:45Z]

Marc et Marilyn:

J'ai ajouté la var. longipes (Fern.) Reveal aux taxons acceptés au Canada (Man, Ont).
Il manque des vernaculaires français et anglais.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-07-12 20:51Z]

French name added
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-07-25 20:05Z]

reviewed all the Streptopus lanceolatus and varieties for English vernaculars
