### ISSUE TITLE
Synonyme de Persicaria amphibia (Linnaeus) Delarbre

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#3028]
Allô Luc!

Peut-être ajouter Persicaria amphibia (Linnaeus) Gray comme synonyme de Persicaria amphibia (Linnaeus) Delarbre. 
Ce nom est invalide par principe d'antériorité, mais il figure dans FNA pour décrire l'espèce. 

Bonne semaine

Alexandre

**Comment by brouille** [comment]
J'ai ajouté le synonyme au nom d'espèce. J'ai aussi informé FNA qu'il fallait changer les autorités.
Luc
