### ISSUE TITLE
Nuphar xrubrodisca has not been found in NL for over 100 yrs - delete this report

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3030]
Unless you have a new record that hasn't been shared with NL, Nuphar x rubrodisca is no longer found in NL.  Here is the annotation for this species in the Appendix of the NL checklist:
[A confirmed specimen of N. ×rubrodisca was collected from Grand Falls (Fernald & Wiegand 1911, #5417, US), (D. Padgett, pers. comm. 1998). Given that the original specimen was collected from near the grounds of the Northcliffe estate in Grand Falls, it is likely that this report originated from a garden introduction (J. Maunder [former curator of the Rooms - the herbarium in St. John's, NL], pers. comm., May 29, 2015). Also, since the report is over 100 yrs. old and no new specimens have been observed, this report has been moved from the main checklist to this appendix.]  

See Appendix, as a PDF, in: https://newfoundland-labradorflora.ca/checklist/

**Comment by brouille** [comment]
excluded, old - the ref will have to wait
