### ISSUE TITLE
misapplication of common name - arctic eyebright, euphraise arctique  for Euphrasia frigida

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3031]
re: http://data.canadensys.net/vascan/taxon/7011?lang=en
The common name arctic eyebright and it's French equivalent were applied to Euphrasia frigida when there confusion about the status of Euphrasia arctica.  Since this species is now recognized in FNA, I have moved there common names in the Newfoundland and Labrador checklist to Euphrasia arctica subsp. arctica and am now using the common name frigid eyebright and it's French equivalent for Euphrasia frigida.  **Since there are no common names currently listed in VASCAN for Euphrasia arctica and subsp. arctic,** I suggest you might also consider this change.  If you retain the names as currently listed, do NOT attribute them to the NL checklist (Meades et al. 2000), as this has now been changed in the current checklist (Meades et al. 2021).

**Comment by brouille** [comment]
Marilyn and Marc
Please consider this comment by Sue on the vernacular above
Luc

**Comment by MFavreau** [comment]
I agree that the name euphraise arctique can no longer be used for E. frigida, and I corrected the French names accordingly.

I also added several missing French names in genus Euphrasia. This should also be done for English names.

**Comment by manions** [comment]
Many thanks for your input. I reviewed Euphrasia long ago before the IT issues, and thought I had entered the corrections. All entered now.
