### ISSUE TITLE
Juncus gerardi - il manque un "i"

### ISSUE THREAD

**Issue by KimDamboise** [Canadensys/vascan-data#3032]
Après vérification dans quelques sources, je pense qu'il manque un "i" à Juncus gerardi(i) Loiseleur-Deslongchamps dans vascan.

**Comment by brouille** [comment]
La graphie actuelle de VASCAN est correcte. Loiseleur a écrit gerardi originalement. De plus, IPNI, POWO, Euro+Med, etc. utilisent tous gerardi. FNA était malheureusement incorrect, puisque le i est ajouté à Gerard et que cela n'en prend qu'un.
Luc
