### ISSUE TITLE
Incorrect citation for Saxifraga tricuspidata var. subintegrifolia

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3033]
In: http://data.canadensys.net/vascan/taxon/9305

VASCAN lists _Saxifraga tricuspidata_ var. _subintegrifolia_ (Abromeit) Polunin,
but Polunin published this name at the rank of forma in 1938; the basionym, by Abromeit, was published as a variety in 1899; this is cited in Polunin's publication: Flora of the Southampton Island; J. Bot. vo. 76, pg. 100
See: http://archive.bsbi.org.uk/Journal_of_Botany_1938.pdf

**Comment by brouille** [comment]
The error came from the cited paper, DeChaine 2014: he interverted authorship for var. subintegrifolia Abrom. and f. sub. (Abrom.) Polunin. I have corrected authorship to Abromeit
Luc B.
