### ISSUE TITLE
Polygala verticillata - présent au Québec

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3036]
Salut

Découverte par moi-même au canal de Beauharnois.  Plusieurs milliers d'individus sur quelques kilomètres.
Photos confirmées par Jacques Labrecque et spécimen d'herbier.
Note: Bien différent du Polygala ambigua.

**Comment by brouille** [comment]
Spécimen déposé où? MT?

**Comment by brouille** [comment]
Est-ce que le taxon est indigène ou introduit au QC?
