### ISSUE TITLE
Blysmopsis rufa

### ISSUE THREAD

**Issue by elbourret** [Canadensys/vascan-data#3037]
Blysmopsis rufa est présent en Alberta, et considéré S2. Il y a quelques spécimens déjà numérisés sur GBIF.

**Comment by brouille** [comment]
Je ne trouve pas les spécimens sur GBIF pour Alberta. Pourrais-tu juste me préciser à quel herbier ils sont déposés (acronyme)? Je peux utiliser les herbiers comme source. Ou alors une citation pour le S2.
Luc

**Comment by elbourret** [comment]
Spécimen : https://www.gbif.org/occurrence/1988187462

Référence: https://www.google.com/url?sa=t&source=web&rct=j&url=https://anpc.ab.ca/wp-content/uploads/2019/03/ANPC-Rare-Plant-Photo-Wish-List-2019-03.pdf&ved=2ahUKEwj4m7qpkoL0AhWrVt8KHYklCCUQFnoECAQQAQ&usg=AOvVaw2lu30sCrHWInEcdD2Kilv3

**Comment by brouille** [comment]
Added B. rufa to Alta with reference UBC (specimen). 
Thanks
Luc B.
