### ISSUE TITLE
Picea x albertiana

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3040]
Salut

Cette publication de 2006 dans le Canadian Journal of Botany montre la carte de répartition.
https://cdnsciencepub.com/doi/pdf/10.1139/b06-071

On mentione aussi des sous-espèces de cet hybride.
POWO reconnait l'hybride: P x albertiana alors que Can. J. Bot n'utilise pas le X (hybride) dans son nom.

**Comment by brouille** [comment]
P. xalbertiana séparé de glauca avec les synonymes associés. Hybride engelmannii x glauca placé en syn de ce taxon. Les subspp. et var. reconnues sont mises en synonymie pour l'instant
Luc B.
