### ISSUE TITLE
Changement au niveau variétal de Juniperus communis (var. kelleyi)

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3042]
Salut

Nouvelle taxonomie pour le var. saxatilis
https://bioone.org/journals/lundellia/volume-21/issue-1/1097-993X-21.1/Juniperus-of-Canada-and-the-United-States--Taxonomy-Key/10.25224/1097-993X-21.1.full?fbclid=IwAR3iuTlHVOHFLghqqhph7Krtfse9xoz5Yp5Fr_PmM1wM_36lgkjiWC1Fosg

**Comment by brouille** [comment]
Changement fait. La var. saxatilis et ses syn. ne sont pas en Amérique du Nord ms en Eurasie.

Marc and Marilyn:
Vernacular names: The current vernaculars in VASCAN are all inadequate, associated with saxatilis from Eurasia. They would only be valid for Greenland I guess (not specified by Adams)
Please provide new names for var. kelleyi of W Canada. The link to the paper above works.
Thanks Luc

**Comment by MFavreau** [comment]
French name added.

Marc

**Comment by manions** [comment]
English name added as per Adams 2013 publication. 
Many thanks for the new Adams publication on Juniperus, however I noticed that the reference entry into the VASCAN database was dated 2021 (the download date) instead of the publication date of 2018. Is it ok that I correct this reference date?

**Comment by brouille** [comment]
MArilyn

Normally, you could. I changed the date, however. Thanks.
LB
