### ISSUE TITLE
Chrysanthemum arcticum

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3043]
Bonne Année Carole

Avant Noël, j'ai tenté de changer la taxonomie du taxon 2845 Arctanthemum arcticum pour le transférer au genre Chrysanthemum sous le nom Chrysanthemum arcticum (23265)

Mon erreur: n'ayant pas vérifié que C. arcticum existait déjà dans la bd, j'ai voulu le créer à nouveau. Le logiciel m'a indiqué qu'il s'agissait d'un double et quand j'ai voulu annuler, la flèche a bougé et a créé le nom (évidemment). Comme il existait un nom antérieur, j'ai tenté d'effacer le nom créé. Rien à faire, il demeure. Je le vois dans l'éditeur mais ne peut rien faire. Cela s'est déjà produit.

Ce que j'aimerais faire est d'effacer le nom récemment créé et de déplacer Chrysanthemum arcticum (23265) sous le genre Chrysanthemum (991), présentement vide (le taxon qui y résidait appartient maintenant à Tanacetum).

Une fois cela fait, je pourrai effectuer le reste du transfert.

Bonne Année à Mariannick et à toute la famille!

Luc

**Comment by CaroleSinou** [comment]
J'ai supprimé le taxon 32868 (nouveau Chrysanthemum arcticum sans aucune information) et défini le taxon 23265 dans le genre Chrysanthemum comme une espèce acceptée.

Je te laisse le soin de vérifier si tout fonctionne comme tu le souhaites.
