### ISSUE TITLE
Spiraea densiflora - association avec le mauvais nom

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3045]
Salut

Voir http://efloras.org/florataxon.aspx?flora_id=1&taxon_id=250065734
Spiraea densiflora devrait être associé avec var. rosea et non var. splendens.
POWO envoie S. densiflora à la var. rosea.

**Comment by brouille** [comment]
J'ai corrigé l'attribution, probablement faite avant FNA 9, qui dit aussi qu'il s'agit d'un nom. illeg. (corrigé également)
LB
