### ISSUE TITLE
Lloydia serotina and varieties moved to Gagea serotina

### ISSUE THREAD

**Issue by cmrobillard** [Canadensys/vascan-data#3049]
Lloydia has been lumped into Gagea based on molecular work. Lloydia serotina and varieties are now therefore being published by aggregators as Gagea serotina. To my knowledge, no combination of Gagea with varieties has been published. 

VASCAN URL:
https://data.canadensys.net/vascan/name/Lloydia%20serotina
https://data.canadensys.net/vascan/taxon/6535
https://data.canadensys.net/vascan/taxon/6537

Authoritative source: 
Zarrei et al. 2009 (https://doi.org/10.1093/aob/mcp103)

**Comment by brouille** [comment]
Cassandra

I will change Lloydia to Gagea. There is one caveat, however: taxonomists have not made all name changes at the varietal level, notably for the one variety endemic to the Queen Charlotte Island in Canada. This is a third instance I have of a Canadian endemic without proper nomenclatural adaptation following a taxonomic change at the species level. It is bothering.

Luc

De : cmrobillard ***@***.***>
Répondre à : Canadensys/vascan-data ***@***.***>
Date : jeudi 3 mars 2022 à 09:54
À : Canadensys/vascan-data ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [Canadensys/vascan-data] Lloydia serotina and varieties moved to Gagea serotina (Issue #3049)


Lloydia has been lumped into Gagea based on molecular work. Lloydia serotina and varieties are now therefore being published by aggregators as Gagea serotina. To my knowledge, no combination of Gagea with varieties has been published.

VASCAN URL:
https://data.canadensys.net/vascan/name/Lloydia%20serotina<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.canadensys.net%2Fvascan%2Fname%2FLloydia%2520serotina&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C2643fdb0854546bf19b208d9fd25afe4%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637819160568810106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=883zt2%2BS6R1YhUrmvOz93RsIsoftQ1MmBdsn6qjTk3A%3D&reserved=0>
https://data.canadensys.net/vascan/taxon/6535<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.canadensys.net%2Fvascan%2Ftaxon%2F6535&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C2643fdb0854546bf19b208d9fd25afe4%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637819160568810106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=trOVSD4xBsZDAlEdJQHLDxAAK0p1z0iNVTBysaJp36M%3D&reserved=0>
https://data.canadensys.net/vascan/taxon/6537<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdata.canadensys.net%2Fvascan%2Ftaxon%2F6537&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C2643fdb0854546bf19b208d9fd25afe4%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637819160568810106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZXbzkTWgck7xVAj5WTtX9%2B2x%2BEZ5oO9lFSjJJv9NmtU%3D&reserved=0>

Authoritative source:
Zarrei et al. 2009 (https://doi.org/10.1093/aob/mcp103<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1093%2Faob%2Fmcp103&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C2643fdb0854546bf19b208d9fd25afe4%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637819160568966350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jg2U%2BQyiHJT%2Febp7gteQBWZ8YE1wqiQ45KP45N2u%2B%2FY%3D&reserved=0>)

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCanadensys%2Fvascan-data%2Fissues%2F3049&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C2643fdb0854546bf19b208d9fd25afe4%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637819160568966350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ffA2dYjyK8UYIKf%2FRbYET9C%2BbOXe3Ku%2FcUxYOxmi0m8%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACZV5Y4CAGDEZODWBOGGCN3U6DHBPANCNFSM5P2WUFUA&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C2643fdb0854546bf19b208d9fd25afe4%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637819160568966350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hbep8SApCnXaGJ9uAav%2F0srEk9o3%2BCayswJScZVWjsQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C2643fdb0854546bf19b208d9fd25afe4%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637819160568966350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wUGIAMIK8GjRBm1Kk0sS5VjqjI0pEQx67WOQWfeAn3k%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cluc.brouillet%40umontreal.ca%7C2643fdb0854546bf19b208d9fd25afe4%7Cd27eefec2a474be7981e0f8977fa31d8%7C1%7C0%7C637819160568966350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=T%2BicmHBjEck3W3AdGth%2FQ0ZlDDivaFPhnp1SFDXUP9E%3D&reserved=0>.

**Comment by cmrobillard** [comment]
Yes, I noticed that too, and I agree it's bothersome! I hope someone can resolve it so that the infraspecific variation can be treated accordingly. 
Thank you!

**Comment by brouille** [comment]
Lloydia transferred in part to Gagea
Had to leave var. flava in Lloydia because it could not be transferred technically. To indicate this, added ** to Lloydia
LB
