### ISSUE TITLE
Plusieurs additions à la flore de Saint-Pierre et Miquelon

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3050]
Salut

http://www.naturespm.com/xxxcl.php?code=flecl&mv=10&debut=0&page=0
En faisant le tri par année de d'observation, on peut voir les plus récentes avec le nom de l'observateur.
Typha latifolia
Anthriscus sylvestris
Verbascum thapsus
Epipactis helleborine
Cardamine hirsuta
Ulmus glabra
Alchemilla mollis
Fraxinus excelsior
Salix alba
Lychnis flos-cuculi
Hesperis matronalis
Eupatorium cannabinum
Epilobium hirsutum
Galium aparine
Daucus carota
Ambrosia artemisiifolia
Amaranthus retroflexus
Arctium lappa
Crepis capillaris
Medicago sativa
Angelica atropurpurea
Carex pellita
Potamogeton berchtoldii
Solanum dulcamara
Erysimum cheiranthoides
Papaver dubium
Brassica rapa
Silene cucubalus
Puccinellia maritima
Solidago canadensis
Scirpus cyperinus
On mentionne aussi un Malva sp....

J'ai arrêté les vérifications à partir de 1981 mais malgré tout, je continuais à trouver quelques additions dans les années qui semblaient couvertes par VASCAN  (les découvertes récentes n'étaient surement pas documentées dans VASCAN, mais bizarrement, j'en retrouvais quand même quand je reculais dans les années).

**Comment by brouille** [comment]
Je ne peux rien faire pour Solidago canadensis : c'est probablement brendae ou un autre taxon dans ce coin. Je vais demander à Roger et vérifier à MT.
Je ne peux rien faire avec Malva sp.

**Comment by brouille** [comment]
Toute la liste fournie par NatureSPM a été vérifiée et les changements inclus. Par ailleurs, Nature SPM est maintenant la citation principale pour SPM étant donné que la liste est en ligne.
LB
