### ISSUE TITLE
Salix × pendulina nothof. tristis (Gaudin) I.V.Belyaeva

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3052]
Salut

Voici le bon nom du saule pleureur.
Voir DOI:10.51776/2309-6500_2021_7_3_15
Bien entendu, le nom est déjà adopté par Kew car il y a un des auteurs de l'article est de Kew.

Il y a un autre article de l'auteur en 2018 qui modifie bon nombre de Salix.  On va uniformiser au jardin en fonction des 2 articles.

Fred

**Comment by brouille** [comment]
Malheureusement, VASCAN ne peut accepter des formes ou nothoformes: nous devions nous limiter sur le nombre de niveaux taxonomiques, et les formes peuvent être considérées comme de la variation génétique populationnelle. Je vais tout de même voir que faire

**Comment by brouille** [comment]
VASCAN ne pouvant inclure les formes, les données sont conservées telles quelles.
Luc B.
