### ISSUE TITLE
Notes on the nomenclature and taxonomy of Salix fragilis (Salicaceae)

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#3053]
Allô!
Si l'article vous a échappé: 
https://doi.org/10.1002/tax.12685
We propose continuing to use S. fragilis as the name for a glabrous crack willow and S. ×rubens for its hybrid with S. alba.

Alexandre

**Comment by brouille** [comment]
as per article de Marchenko & Kuzovkina:
Salix euxina syn de S. alba
Salix fragilis acc comme sp en lieu de euxina FNA
Salix xrubra acc comme nothotaxon en lieu de xfragilis FNA
Luc
