### ISSUE TITLE
Addition of Gunneraceae - Gunnera - G. tinctoria to VASCAN - vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3054]
Dear colleagues

Following FNA 10 and eFlora BC, I added Gunnera tinctoria to VASCAN. This requires vernaculars for the family and genus also.

Note that eFlora uses Chilean rhubarb as vernacular (https://linnet.geog.ubc.ca/Atlas/Atlas.aspx?sciname=Gunnera tinctoria), while FNA 10 (printed, not on web yet), uses Giant Rhubarb, dinosaur food, nalca, panque [the last two probably Chilean names). AS the plant is ephemeral, I suggest not to add many vernaculars.

I leave Marc to choose the French name. This is a frequently cultivated plant.

Luc

**Comment by MFavreau** [comment]
French names added.

Marc

**Comment by manions** [comment]
English vernaculars added
