### ISSUE TITLE
Galéopside intermédiaire - nom français à ajouter pour Galeopsis ladanum

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3056]
Voir Wikipedia et FNAms

**Comment by MFavreau** [comment]
Bonjour Fred,

Nom français ajouté avec comme source « FNA Ed Comm. in prep. i  »  (volume 16).

Marc

De : FredCoursol ***@***.***>
Envoyé : 26 mai 2022 14:33
À : Canadensys/vascan-data ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [Canadensys/vascan-data] Galéopside intermédiaire - nom français à ajouter pour Galeopsis ladanum (Issue #3056)


Voir Wikipedia et FNAms
