### ISSUE TITLE
Non-disponibilité du nom Viola incognita après malfonction de VASCAN editeur

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3058]
Carole
Le nom Viola incognita a disparu à cause d'une malfonction de VASCAN editeur. Je crois qu'il est encore ds la bd, mais je ne peux plus y accéder. Je tentais de le rendre "accepté" sous Viola.
https://data.canadensys.net/vascan/taxon/21519

à mettre sous data.canadensys.net/vascan/taxon/33156 (subsect. Stolonosae)

Lorsque fait, je pourrai terminer le travail de séparer les noms des synonymes de son ancien parent.

erci
Luc

**Comment by brouille** [comment]
erreur technique de ma part:
changer le rang du taxon de Species à Variety
Taxon 11365 Viola cucculata var. glaberrima
Merci
L

**Comment by CaroleSinou** [comment]
1) Viola incognita (taxonid = 21519) est maintenant dans la taxonomie sous  Viola subg. Stolonosae, et est reconnu comme un taxon accepté et non un synonyme.

2) Viola cucullata var. glaberrima repassé de Species à Variety.
@brouille est-ce normal qu'il soit synonyme de Viola nephrophylla et non de Viola cucullata ?

**Comment by brouille** [comment]
Oui c'est normal; erreur du taxonomiste et du concept adopté
Luc
