### ISSUE TITLE
Malfonctionnement de VASCAN editor en faisant un changement

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3059]
Carole

Décidément, VASCAN editor me cause des problèmes. C'est un cas identique à celui rapporté vendredi:
Changement du statut de synonyme à accepté : le taxon disparaît.
Taxon: Viola rafinesquei data.canadensys.net/vascan/taxon/21515
Svp placer sous: subsect. Melanium data.canadensys.net/vascan/taxon/33176

Comme c'est récurrent, je me demande ce qui se passe.

Luc

**Comment by CaroleSinou** [comment]
Les corrections ont été appliquées directement dans la base de données.
Viola rafinesquei (21515) maintenant sous Viola subsect. Cleistogamae (33176), en tant que taxon accepté.
