### ISSUE TITLE
new Draba described by Mulligan 2021

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3060]
Just wondering if there is consideration for the new draba described by Gerald Mulligan in 2021.
https://huh.harvard.edu/files/herbaria/files/26_1_189_mulligan.pdf?m=1624980348 

Sadly he has passed away in June.
https://ottawacitizen.remembering.ca/obituary/gerald-mulligan-1085564400

**Comment by brouille** [comment]
Added to VASCAN, though I am curious to see what will be made of them eventually, as they are not yet in Brassibase. Also, I do not know how to deal with his comments on other spp, which he considers differently from Al-Shehbaz in FNA. More to do.

Thanks for the heads up on his death. A great loss.
Luc

**Comment by manions** [comment]
English vernaculars added

**Comment by manions** [comment]
Hi
I realized that these taxa also need French vernaculars.

**Comment by MFavreau** [comment]
French names added, Theze were easy...
