### ISSUE TITLE
authority in synonyms misspelled

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3063]
Authority in synonyms misspelled: http://data.canadensys.net/vascan/taxon/9503?lang=en

[Viola macloskeyi subsp. pallens (Banks ex Gingis) M.S. Baker](http://data.canadensys.net/vascan/taxon/21539)
[Viola macloskeyi var. pallens (Banks ex Gingis) C.L. Hitchcock](http://data.canadensys.net/vascan/taxon/21534)
[Viola pallens (Banks ex Gingis) Brainerd](http://data.canadensys.net/vascan/taxon/21535)
[Viola pallens (Banks ex Gingis) Brainerd subsp. pallens](http://data.canadensys.net/vascan/taxon/21542)

Banks ex Gingis should be Banks ex Gingins in all these names, as per IPNI.

**Comment by brouille** [comment]
corrections done LB
