### ISSUE TITLE
Viola vernaculars to be revised

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3066]
Marc and Marilyn

Thanks in large parts to the work of Harvey Ballard <https://people.ohio.edu/ballardh/vgpena/> (based on phylogenetic data)
I revised extensively the taxonomy of the Canadian Viola species, reverting several names placed in syn by FNA to accepted, and thus also excluding some taxa from the Canadian flora. Because of this, a number of vernacular names need to be revised. 
I do not have too many means of helping out here, but please follow closely VASCAN, since some elements in Ballard have been changed recently and are correct in VASCAN.

Please note the species are now placed into new sections based no the molecular work.
Luc

**Comment by manions** [comment]
English vernaculars for Violaceae reviewed and added

**Comment by MFavreau** [comment]
French names added.

Marilyn : I happen to notice that English names are still lacking for the varieties of Viola palmata.

**Comment by manions** [comment]
Many thanks! I added these now.
