### ISSUE TITLE
new taxa added to the flora of Canada (Ontario)

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3067]
The following 7 species were added to the flora of Ontario, and in 6 cases to that of Canada, and are in need of vernacular names. I provisionally input vernacular English names used by Oldham et al. and by FNA. You are free to revisit those or their status.
Acalypha gracilens 
Ajuga chamaepitys 
Hydrocotyle ranunculoides 
Ludwigia peploides 
Oenanthe javanica 
Rumex cristatus 

Schoenoplectiella mucronata was already in VASCAN

If you would like to have the draft paper by Oldham et al., please ask me. I cannot put it here as it is under review.
Luc

**Comment by MFavreau** [comment]
French names added

**Comment by manions** [comment]
English names reviewed and added
