### ISSUE TITLE
New taxa for Manitoba

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3068]
New taxa for Manitoba reported by Staniforth and Brunton 2022, Can Field Nat. 136(2): 107-121
Diphasiastrum x zeilleri
Huperzia x buttersii
Isoetes x hickeyi

I'll try to attach over the document. https://doi.org/10.22621/cfn.v136i2.2669
Marilyn
(getting at other taxa soon!)
[Staniforth & Brunton MB Lycophytes 2022.pdf](https://github.com/Canadensys/vascan-data/files/9993689/Staniforth.Brunton.MB.Lycophytes.2022.pdf)

**Comment by brouille** [comment]
All Manitoba lycophytes updated using this reference because of specimen documentation, etc.
Thanks for the nads up
LB
