### ISSUE TITLE
Crepidomanes intricatum ajouté au Québec

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3069]
MArc et Marilyn: 
The fern Crepidomanes intricatum (Hymenophyllaceae) has recently been found in southern Québec. It is an addition to Canada. There is no vernacular names for it.
English vernaculars from FNA: Appalachian trichomanes, weft fern  [the latter used in the World Checklist of ferns]

Luc

**Comment by MFavreau** [comment]
French name added ; crépidomane des Appalaches. Crepidomanes minutum, from Oceania, is called crépidomane menu in French
