### ISSUE TITLE
Synonyme de Viola à transférer d'espèce

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3070]
Carole
Quand je veux transférer des synonymes d'une sp à une autre, je dois utiliser le bouton "transférer des synonymes". Une fenêtre apparaît avec la liste des synonymes présents sous le taxon A, dont certains sont à transférer au taxon B. Tout va bien lorsque la liste de synonymes comporte 11 noms ou moins. Mais lorsqu'il y en a plus, les noms suivants ne paraissent pas car la fenêtre n'est pas déroulante. Il est alors impossible de transférer ces noms.
J'aimerais transférer le nom 29315 Viola prionosepala du taxon 9496 Viola nephrophylla où il se trouve vers le taxon 9486 Viola cucullata
Merci de faire le transfert via la bd
Luc

**Comment by CaroleSinou** [comment]
Luc, 
je viens de faire la modification pour Viola. Je n'avais pas reçu de notification pour cette issue. Il est mieux de m'assigner les issue plutôt que d'assigner canadensys. 
Je vais voir ce que je peux faire pour que tu puisses rentrer plus de 11 synonymes dans l'éditeur.

**Comment by brouille** [comment]
MErci
Ce n'est pas le nombre de synonymes qui fait problème. C'est qu'il n'y a pas moyen de faire défiler la liste dans la minuscule fenêtre. Ni par curseur, ni par des flèches.
Luc
