### ISSUE TITLE
incorrect spelling of Gingins (as Gingis) in 4 synonyms of Viola palustris

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3074]
page: https://data.canadensys.net/vascan/taxon/9503?lang=en

The correct spelling of [Banks ex] Gingis is Gingins
This misspelling occurs in the first 4 synonyms of Viola palustris

check IPNI authors

**Comment by brouille** [comment]
already corrected. Corrections appear only at new publication, which are quarterly usually.
LB
