### ISSUE TITLE
Incorrect spelling of authority Gingins, as Gingis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3075]
page: https://data.canadensys.net/vascan/taxon/33089?lang=en

In the 2nd synonym in the list, 
The correct spelling is (Banks ex Gingins), not Gingis

IPNI authors has:  Ging. – Frédéric Charles Jean Gingins de la Sarraz (1790-1863)

**Comment by brouille** [comment]
this was a typo - already  corrected
LB
