### ISSUE TITLE
Perideridia montana

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3076]
Marilyn and Marc

Perideridia gairdneri is now excluded from Canada - this was a case of mistaken taxonomy. Authors sometimes used subsp. borealis, a syn. of P. montana, but did not always include the subsp. (or var. montanum Boivin). 

Vernaculars are needed for P. montana. I transferred one name from gairdneri since it is the vernacular used in FNA. Your call Marilyn.

Luc

**Comment by manions** [comment]
English vernaculars added

**Comment by MFavreau** [comment]
French name added.
