### ISSUE TITLE
Lepidium virginicum subsp. virginicum remove from NWT

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#3079]
https://data.canadensys.net/vascan/taxon/4072

I presume that the inclusion of Lepidium virginicum subsp. virginicum (and L. virginicum) for NWT is based solely on my collections at TRTE. The identities of both my two NWT specimens initially called L. virginicum have been revised to L. ramosissimum by Dr. Peter W. Ball (University of Toronto).

Mike Oldham

**Comment by brouille** [comment]
The taxon is now excluded as misidentified with source TRTE.
Thanks
