### ISSUE TITLE
Capsella rubella

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3080]
Carole
VASCAN me dit que le nom Capsella rubella est dans la base de données, mais je suis incapable de le voir. Est-il possible de le ressusciter sous Capsella afin que je puisse l'exclure de certaines provinces?
Merci
Luc

**Comment by CaroleSinou** [comment]
Luc, 
je viens de réintégrer Capsella rubella dans les tables taxon et taxonomy, ainsi que de mettre à jour la table lookup.
Il y a peut-être des éléments à modifier ou à ajouter dans l'une de ces tables, mais je pense que tu pourras maintenant le faire directement dans Vascan Editor.
Si ce n'est le cas, je pourrais les intégrer directement dans les tables (il faudra donc me fournir les détails à modifier ou ajouter).

Carole

**Comment by brouille** [comment]
MErci. J'ai ce que je voulais: exclure le taxon.
L
