### ISSUE TITLE
Utricularia radiata - présente dans plusieurs lacs au Québec

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3083]
Salut
Peut-être que MT n'a pas de spécimen, mais l'espèce est maintenant documentée dans plusieurs lacs.
L'espèce est même sur la liste des espèces susceptibles d'être désignées menacées ou vulnérables..... Voir décret de 2020

**Comment by brouille** [comment]
Je n'ai pas besoin de spécimen à MT, simplement que quelqu'un ait documenté la plante par un spécimen déposé dans un herbier officiel, que ce soit QFA, QUE, MTMG, DAO ou CAN, etc.
Les données du ministère c'est bien beau, les photos aussi, mais une documentation physique assure la validité et la pérennité du rapport. Je veux bien ajouter la plante, mais je n'aurai aucune source. Je ne vais pas citer un décret.
Luc
