### ISSUE TITLE
error in authority of Rumex graminfolius

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3086]
Re: https://data.canadensys.net/vascan/taxon/8211?lang=en

Authorship should be Georgi _ex_ Lambert.

See: https://www.biodiversitylibrary.org/page/757433#page/279/mode/1up

Tropicos lists Rudolph ex Lambert, while IPNI lists Georgi ex Lambert, both cited from the same publication.
In Lambert's publication, he attributes the authorship to Georgi (at bottom pf page), but notes that the specimen was collected by Rudolph (top of page).

**Comment by brouille** [comment]
correction made. Also sent correction to FNA
VASCAN entry also corrected to excluded old
Luc
