### ISSUE TITLE
Incapacité d'ajouter les parents d'hybride

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3087]
Il m'est présentement impossible d'ajouter les parents d'hybrides à la base de données. C'est gênant car je ne peux pas toujours me rappeler lesquels manquent
Luc

**Comment by CaroleSinou** [comment]
Luc, peux-tu me donner un exemple de taxon ? Cela sera utile pour trouver la source du problème. Depuis quand le problème est-il apparu ?

**Comment by brouille** [comment]
Le dernier exemple est Jacobaea albescens 33414 et le taxon fait juste avant.

Cela arrive de façon épisodique et c'est particulièrement irritant car je ne me souviens pas toujours de retourner faire les hybrides plus tard.

Merci
Luc

**Comment by CaroleSinou** [comment]
J'ai fait des modifications dans le type de variables pour la table taxonhybridparent (smallint(5) à int(5)). Je ne sais pas si cela peut avoir réglé le problème. Peux-tu tester ?

**Comment by brouille** [comment]
Carole
Cela semble avoir réglé le problème
Merci
Luc
PS: As tu pu faire la correction demandée sur Viola ? La taille de la fenêtre des synonymes m'empêche de déplacer des noms. L.
PPS : Bonne Année à toute la famille
