### ISSUE TITLE
Amelanchier x lamarckii

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3088]
Salut

VASCAN indique cet hybride comme espèce.  Il faut ajouter le x
Voir POWO.  C'est une horticole qui s'appelait anciennement x grandiflora (A. laevis x A. arborea)

**Comment by brouille** [comment]
L'origine du taxon, selon Campbell et al., est plus obscure et les espèces NA lui ayant donnée naissance sont ambigues. Pour l'instant, je vais ajouter le x
Luc
