### ISSUE TITLE
authority for Cuscuta gronovii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3089]
re: https://data.canadensys.net/vascan/taxon/4628

Tropicos lists only Willd. as the authority for Cuscuta gronovii, giving the publication sources as Syst. Veg. ed. 15 bis 6: 205 (1820).

But this edition appears to be authored just by Schultes; which would make the authority Willd. _ex_ Schult. (which is what appears in POWO). An illustration of of Roemer appears before the title page, but he's not listed in the authorship.  See: 
https://www.biodiversitylibrary.org/page/731962#page/2/mode/1up
https://www.biodiversitylibrary.org/page/731962#page/284/mode/1up
 
Might need to check with Kanchi Gandhi on this.

**Comment by brouille** [comment]
Sue

According to FNA 14, which was reviewed by Kanchi for nomenclature, the citation for C. gronovii is Willdenow ex Roemer & Schultes in J. J. Roemer et al., Syst. Veg. 6: 205.  1820   

I am not sure what the technicalities would be here. Maybe you could ask him directly. For the time being, I am waiting publication in case changes were made during later review stages.
Luc

**Comment by sjmeades** [comment]
Hi Luc,

 

Thanks, Luc.  I might ask him, just because if it is just Schultes, then that might cause other changes.  But there might be a technical reason for using both authors.

 

I did want to ask you too if you think this sp. is native in Nfld.  It’s only been reported once, and that by John Maunder.  Seems odd that no one would have found it previously if it was native.  But maybe you have other records.  The only one I know of are John’s posted photos from Gambo saltmarsh from 2006.  There are no collections listed in the ACCDC data.

https://www.digitalnaturalhistory.com/flora_convolvulaceae_index.htm#cuscutagronovii

 

Given it’s the only location, it seems possible that seeds could have been transported by waterfowl that stopped off at this saltmarsh.

 

Take care, Sue.
