### ISSUE TITLE
Dichanthelium leibergii synonym

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#3090]
According to FNA Vol. 25 Panicum leibergii var. baldwinii is a synonym of Dichanthelium xanthophysum; in VASCAN it is listed as a synonym of D. leibergii.

https://data.canadensys.net/vascan/name/Panicum%20leibergii%20var.%20baldwinii

Mike Oldham

**Comment by brouille** [comment]
Mike
On this synonymy, I am not following FNA 25. All other sources I consulted, including New World Grasses, POWO, and others synonymize var. baldwinii under leibergii.
I general, I followed NWG because in many cases, their decisions were better founded in phylogeny, etc.
Luc
