### ISSUE TITLE
Crataegus curvisepala = Crataegus rhipidophylla var. rhipidophylla

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3091]
Salut

Crataegus rhipidophylla var. rhipidophylla serait le nom approprié selon Plants of the World Online
Pour une espèce introduite très localement en Amérique du Nord, je pense que nous devrions utilsier les noms recommandés en Europe.

**Comment by brouille** [comment]
Fred
Je ne suis même pas certain que le taxon se trouve au NB. Il semble y avoir confusion et je dois revoir le cas. 
Luc

**Comment by brouille** [comment]
Le taxon n'a pas été retenu dans Hinds 2000 (NB) et il n'y a aucune auytre documentation. J'ai décidé de le retirer tout simplement de la bd
Luc
