### ISSUE TITLE
Cotoneaster horizontalis in Ontario

### ISSUE THREAD

**Issue by MichaelOldham** [Canadensys/vascan-data#3092]
Peter F. Zika has identified a specimen of this species from Ontario which did not come from a cultivated plant. This was subsequent to the FNA treatment. Images of the specimen can be found at https://inaturalist.ca/observations/101196726

Collection details are:

M.J. Oldham & S.R. Brinker # 34752, specimen record, replicates at WTU, NHIC# 04066; 
Canada, Ontario, NIAGARA County, open weedy roadside bank, south side of York Street, east of Niagara Parkway, Queenston, 43.16163314, -79.05423006; 13 July 2007; identified as Cotoneaster horizontalis by P.F. Zika March 2008; several plants; appearing non-planted; new to Ontario, no correct specimens seen during FNA work (P. Zika pers. comm. 2008)

**Comment by brouille** [comment]
Entry for this taxon modified to introduced, source : NHIC
