### ISSUE TITLE
Ajouts pour le Québec et Juglans ailanthifolia = J. Juglans mandshurica var. cordiformis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3093]
Gentianella quinquefolia: Jacques Cayouette cite Sorel comme répartition au Québec (2 spécimens : 1 à Ottawa et 1 à Edinburgh)
Dactylorhiza praetermissa subsp. praetermissa var. junialis: Spécimen du Québec et étiquette déposé à MT
Platanthera shriveri: Spécimen du Québec et étiquette déposé à MT

**Comment by brouille** [comment]
Nom du Juglans changé pour la variété sachalinensis (et non cordiformis)
Dactylorhiza praetermissa MT ajouté
Platanthera shriveri MT déjà ds bd

Gentianella quinquefolia : de quelle subsp s'agit-il? considéré introduit ou indigène?
