### ISSUE TITLE
Prunus emarginata (Douglas ex Hook.) Eaton - autorité divergente

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3096]
Autorité divergente entre POWO et FNA-VASCAN
POWO: Prunus emarginata (Douglas ex Hook.) Eaton
VASCAN: Prunus emarginata (Douglas) Eaton

**Comment by brouille** [comment]
TROPICOS, IPNI, FNA ont tous (Douglas) Eaton ; POWO est seul à avoir (Douglas ex Hook.) Eaton. Pourtant POWO suit habituellement IPNI. Or l'entrée correspondante de IPNI diffère. Je ne vais pas suivre POWO car il y a souvent des erreurs. Je soupçonne ici que c'est Douglas in Hooker. Je vérifierai tout de même avec K. Gandhi.
Luc B.

**Comment by brouille** [comment]
email from K. Gandhi: NO “ex” is needed.
 We already checked it.  The IPNI shows the remark as:
 Remarks: The species name and the description are ascribed simultaneously in a paragraph ending with Douglas, MSS (Vienna Code Art. 46 ex 14 applies).

POWO est incorrect ici
