### ISSUE TITLE
Autorité de Ribes glandulosum

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3097]
Salut
Conflit entre IPNI (POWO) et TROPICOS - VASCAN
Ribes glandulosum Weber (https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:792704-1)
vs 
Ribes glandulosum Grauer

**Comment by brouille** [comment]
VASCAN, TROPICOS et FNA sont corrects selon K. Gandhi.
IPNI sera corrigé.
Grauer était l'étudiant de Weber et dans le passé on attribuait souvent l'autorité au prof. Mais Grauer a bien écrit l'introduction à la thèse et est donc auteur du nom.
Luc
