### ISSUE TITLE
Rubus parviflorus est un nom illegitime selon IPNI

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3099]
Salut

GRIN, IPNI et Tropicos utilse Rubus nutkanus Moc. ex Ser. comme étant le nom valide du R. parviflorus.

**Comment by brouille** [comment]
TROPICOS mentionne, avec raison, que le nom est proposé pour conserv ation. Cela ne veut pas dire que ça va se produire, mais en attendant, je ne bouge pas. En fait, nous avons eu une discussion FNA et GRIN à ce sujet dans les dernières années, postadant 2018 (date de l'entrée dans GRIN). IPNI est correct, mais Kanchi est aussi impliqué.
Luc

**Comment by FredCoursol** [comment]
On a réglé le problème dans le dernier taxon.  C'est maintenant un nom conservé après le vote.  On reste donc avec Rubus parviflorus.
