### ISSUE TITLE
Nom anglais de Clinopodium arkansanum

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#31]
[Originally posted on GoogleCode (id 1421) on 2012-09-19]

limestone calamint (selon Plants.usda.gov)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-09-19 19:54Z]

Marilyn: a missing EN vernacular with a suggestion from Fred Coursol
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:24Z]

the name 'low calamint' in use by Ontario, plus as in Britton & Brown. other name as synonym
