### ISSUE TITLE
Draba pilosa - addition pour le Québec

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3100]
Espèce est présente au Québec, mais connue d'une seule station: Environs d'Ivujivik. 23 juillet 1984. Terrasse de roches. Abrité. Avec Juncus arcticus, Carex maritima et Salix lanata var. calcicola. Blondeau 84332 (QFA). Det. Michelle Garneau.

**Comment by brouille** [comment]
ajout fait avec QFA comme source
LB
