### ISSUE TITLE
Sabulina rossii - présent au Québec

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3101]
Salut

Benoit Tremblay du CDPNQ m'envoie ceci:
Il existe deux récoltes de Sabulina rossii réalisées par Derek Lynch dans le secteur de Raglan en 2008 et confirmées par Lynn Gillespie de CAN. Aucune donnée sur la démographie ou la répartition locale. Donc présente au Québec, mais très rare

**Comment by brouille** [comment]
Donnée corrigée - ai présumé que CAN est l''herbier de dépôt
LB
