### ISSUE TITLE
English vernaculars with "Indian" in the name

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3102]
This concerns Marilyn primarily but may be of interest to Marc also (though I do not know of French names with Indien in them).

A few years ago, Sean Blaney of the AC-CDEC had raised the same issue with me concerning English vernacular with Indian in them. This is apparently becoming problematic.

 I received an email from Dale Leadbeater concerning such names in Ontario (project Kawartha Lakes)  (dated Apr 30 but sent me May 17). I will reply to him that such names are being curated by you, Marilyn, who will consider his comments. I will cc you on my answer to him, so you have a full copy of the message with attachments.

Maybe the issue should be addressed globally for all such names in Canada. They are not so numerous. Granted, VASCAN will not be able to erase them as synonyms because they have been in use a long time.

Luc

**Comment by manions** [comment]
review of accepted English vernaculars with the name 'Indian' reviewed and changed.
