### ISSUE TITLE
Coreopsis lanceolata - ajout QC

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#3104]
Salut

Ajout pour le Québec.  Les gens de l'Outaouais m'ont fait remarqué que VASCAN ne comportait pas cette espèce.
Ils m'ont donc amené sous une ligne de haute-tension à Gatineau ou l'ouverture était dominée par cette espèce.
J'ai donc fait un spécimen d'herbier qui est dans le séchoir actuellement.  On me mentionne que l'espèce est aussi visible dans la région de Lachute dans une bretelle d'autoroute.

**Comment by brouille** [comment]
Je l'ajouterai quand je verrai le spécimen. Je viens de terminer la révision des spécimens der Coreopsis à l'herbier.
Luc

**Comment by brouille** [comment]
ajout avec MT. SVP remettre spécimen illico
