### ISSUE TITLE
Achillea borealis taxonomy

### ISSUE THREAD

**Issue by CDeduke** [Canadensys/vascan-data#3107]
Hello,
I was looking at the Achillea borealis classification and it appears there is an error:
https://data.canadensys.net/vascan/taxon/10242

The varieties for Achillea borealis are:
Achillea borealis var. borealis
Achillea millefolium var. megacephala

Should this be:
Achillea borealis

and 

Achillea millefolium 
having varieties:
Achillea millefolium var. megacephala
Achillea millefolium var. millefolium
?

There is no recorded combination for A. millefolium var. megacephala under the A. borealis classification. 

Thanks!
Chris

**Comment by brouille** [comment]
Chris

This is a know issue. The difficulty for me here is that no one has made the combination for var. megacephala under A. borealis, where it belongs, as you comment. Until it is done, there is not much I can do. Perhaps I should do it. There is another similar comb. that needs to be done for a Canadian endemic. Often an issue.

Thanks

Luc
