### ISSUE TITLE
Basionym authority for Amaranthus emarginatus changed

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3108]
For all combinations of Amaranthus emarginatus Salzmann ex Moquin-Tandon under Amaranthus blitum, IPNI now list this name as invalid (pro syn.), the new authors, according to IPNI are Salzmann ex Uline & W.L.Bray 

See IPNI: https://www.ipni.org/n/59497-1
and: https://www.ipni.org/n/30387746-2

**Comment by brouille** [comment]
Correction done - originally entered name now nom. inval. and second added
LB
