### ISSUE TITLE
Synonym of Amaranthus caudatus an illeg. hom.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3109]
[Amaranthus edulis Spegazzini] (https://data.canadensys.net/vascan/taxon/27770)
was published in 1917.  Amaranthus edulis Michx. ex Moq. is a synonymy of Amaranthus cannabinus; it was published in 1849, making Speg.'s combination illegitimate.

**Comment by brouille** [comment]
edulis in VASCAN now nom. illeg.
LB
