### ISSUE TITLE
Correction of status

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#311]
[Originally posted on GoogleCode (id 543) on 2011-06-18]

Senecio exaltatus Nuttall var. ochraceus Piper
syn of S. integerrimus var. ochroleucus

change status to subsp.
http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=250068729

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-06-19 20:15Z]

http://dev-data.canadensys.net/vascan/name/Senecio%20exaltatus%20subsp.%20ochraceus
