### ISSUE TITLE
Authority of Atriplex micrantha (syn. of Atriplex heterosperma)

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3110]
Vascan lists Atriplex micrantha C.A.Meyer as a synonym, but Meyer's name was published in 1833. Ledebour published the same name in 1829.  

Both authors spelled the name Atriplex micranthum.  
See the links in IPNI: https://www.ipni.org/?q=Atriplex%20micrantha

**Comment by brouille** [comment]
Upon examination, it appears that the situation is a bit more complex. In fact, the FNA accepted name, A. heterosperma Bunge (1852), is a synonym of A. micrantha Ledebour (1829), and that A. micrantha C.A. Meyer (1833) is a later homonym and synonym of the Ledeb. name. Both Euro+Med and GBIF agree on this, as well as GBIF. POWO segregate these taxa, but I do not believe this is coherent.
L
