### ISSUE TITLE
correction in authoriyy of synonym of Atriplex prostrata

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3111]
For the synonym: [Atriplex patula var. hastata (Linnaeus) Gray](https://data.canadensys.net/vascan/taxon/14679)

the final authority should be (L.) A.Gray (Not Gray, which is S.F.Gray)

See IPNI: [Atriplex patula var. hastata (Linnaeus) Gray](https://data.canadensys.net/vascan/taxon/14679)

**Comment by brouille** [comment]
correction done
LB
