### ISSUE TITLE
change status from var to subsp in taxon 26759

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3115]
Gentianella tenella var. pribilofii devrait être subsp. pribilofii

svp changer status à subsp

Merci
Luc

**Comment by brouille** [comment]
conserver celui qui a plus de 1 synonyme
Luc

**Comment by CaroleSinou** [comment]
Je viens de passer Gentianella tenella var. pribilofii à Gentianella tenella subsp. pribilofii

Je ne comprends pas vraiment ton 2nd commentaire.
