### ISSUE TITLE
authority of Asplenium scolopendrium subsp. americanum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3117]
Currently this subspecies appears as: Asplenium scolopendrium subsp. americanum Linnaeus

but the basionym of 'americanum' is Phyllitis scolopendrium var. americana Fernald: Rhodora 37:220 (1935),

and the correct authors for Aspleniuim scolopendrium subsp. americanum are (Fernald) N.Heo.

See IPNI: Taxon 72(2): 155 (2023).

**Comment by brouille** [comment]
mistake corrected - probably failed to replace sp author by that of subsp

LB
