### ISSUE TITLE
Lupinus : synonyme ss mauvais nom accepté : déplacer

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3119]
Carole
Le nom Lupinus donnelyensis (31606), présentement sous Lupinus arbutus (5790), avait été erronément inscrit sous celui-ci.

Il faut le déplacer sous Lupinus arcticus (5793)

Je ne peux déplacer moi-même le nom car la liste est trop longue et la fenêtre ne déroule pas

Merci
Luc

**Comment by brouille** [comment]
J'ai effacé Lupinus rubro-soli Eastwood car il était mal placé. Finalement, j'aurais dû le conserver car il appartient au taxon L. lepidus var. lobbii (16321).

Est-il possible de le récupérer et de le placer au bon endroit svp?

Luc

**Comment by CaroleSinou** [comment]
Lupinus donnelyensis (31606) déplacé sous Lupinus arcticus (5793).
Lupinus rubro-soli (31732) rajouté aux tables taxon et taxonomy, sous L. lepidus var. lobbii (16321).
