### ISSUE TITLE
Vernacular in Cytisus

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3120]
Marc and Marilyn 

Some Cytisus spp were added recently following FNA/eFlora BC

MArc, ajouter vernaculaires français au besoin
Marilyn please verify the English names I input from the sources above - you may wish to remove or change them

I have been inputing corrections from FNA volume 14 (Solanaceae, etc.) and FNA 11 parts 1 and 2 (Fabaceae). It might be worth checking vernaculars. Missing vernaculars are indicated in our VASCAN lists: TAxon à vérifier

Luc

**Comment by manions** [comment]
completed review of English vernaculars, will be working on others

**Comment by manions** [comment]
Hi, just wondering how to find VASCAN Lists : Taxon à vérifier. perhaps send in an email?

**Comment by MFavreau** [comment]
Noms français révisés et complétés pour tout le genre Cytisus.

Marc
