### ISSUE TITLE
incorrect basionym author in synonyms of Lomatium nudicaule (Nutt.) J.M.Coult. & Rose

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3121]
https://data.canadensys.net/vascan/taxon/2610

Since Pursh's name, _Smyrnium nudicaule_, is an illegitimate homonym, Nuttall, who described _Ferula nudicaulis_ in 1818, should be listed as the basionym author for all combinations described after 1818.

**Comment by brouille** [comment]
corrected
