### ISSUE TITLE
vernacular names of Leguminosae

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3122]
Please verify vernaculars of Trifolium - many do not have references, or, for that matter, any vernacular

Vicia cracca : species was divided into two varieties - please transfer appropriate vernaculars to each variety - only two accepted vernaculars should remain with the sp
Check other Vicia also

Please note that I am including Lens within Vicia (Vicia lens) despite FNA, following Legume database and POWO

Luc

**Comment by MFavreau** [comment]
Trifolium  : all is in order for French vernaculars. No vernaculars are required for Trifolium bifidum and T. fucatum because those species are excluded from the Canadian flora.

Vicia : all French vernaculars verified or completed as needed.

**Comment by manions** [comment]
finished review of all English vernaculars in Vol 11, Fabaceae
