### ISSUE TITLE
incoirrect authorities for Rudbeckia grandiflora var. grandiflora

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3127]
See: https://www.ipni.org/?q=Rudbeckia%20subtomentosa

The correct authorities, as per IPNI and POWO are:
Rudbeckia grandiflora (Sweet) C.C.Gmelin ex de Candolle var. grandiflora, as listed in the species name, but the variety authorities are given in VASCAN as (D.Don) J.F. Gmelin ex de Candolle var. grandiflora

**Comment by brouille** [comment]
correction done
LB
