### ISSUE TITLE
misplaced synonym, as per IPNI

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3128]
Senecio lyallii Klatt is listed here as a synonym of Packera contermina, but IPNI places  it as a synonym of Packera hyperborealis

See: https://www.ipni.org/?q=Senecio%20lyallii

**Comment by brouille** [comment]
IPNI does no such thing: it mentions : later homonym (non Hook. f. 1852); replaced by S. conterminus Greenm. 1916.

LB
