### ISSUE TITLE
illeg. homonym not noted in synonym of Packera macounii

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3129]
In synonymy, under Packera macounii, the first synonym listed is an illegitimate homonym, according to IPNI.  The earlier  Schwein. ex Elliott's name is listed as a synonym of Packera aurea in IPNI and POWO

Senecio fastigiatus Nutt. 1841, nom. illeg. hom., non Schwein. ex Elliott 1823]

**Comment by brouille** [comment]
correction made
LB
