### ISSUE TITLE
typo in synonym of Packera subnuda var. moresbiensis

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3131]
The correct basionym, as in IPNI and POWO is:
[Senecio cymbalarioides subsp. moresbiensis Calder & Roy L. Taylor](https://data.canadensys.net/vascan/taxon/11851)

But also listed is, likely a typo, which should be deleted: 
[Senecio cymbalarioides var. moresbiensis Calder & Roy L. Taylor](https://data.canadensys.net/vascan/taxon/11849)
The variety was described by C.C.Freenman in the line above:
[Senecio cymbalarioides var. moresbiensis (Calder & Roy L. Taylor) C.C. Freeman](https://data.canadensys.net/vascan/taxon/11850)

**Comment by brouille** [comment]
There was one too many entry, incorrect, which I remove
Thanks
