### ISSUE TITLE
missing basionym authority in synonym of Packera cana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#3132]
[Senecio canus var. purshianus A. Nelson](https://data.canadensys.net/vascan/taxon/11757)

should be Senecio canus var. purshianus (Nuttall) A. Nelson
as Nelson's original publication lists in BHL: 
o	[New manual of botany of the central Rocky mountains (vascular plants) - Biodiversity Heritage Library (biodiversitylibrary.org)](https://www.biodiversitylibrary.org/item/116743#page/585/mode/1up)

**Comment by brouille** [comment]
basionym author added - had been added to FNA and was in TROPICOS (but not IPNI)

LB
