### ISSUE TITLE
Cucumis melo subsp. agrestis in Ontario

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3133]
FNA 2015 vol 16 page 36 lists this subspecies for Ontario. The Ontario Natural Information Centre is including this taxon in its 2023 list of vascular plants.
English vernacular: Gulf Coast melon

**Comment by brouille** [comment]
added

Marc
svp ajouter vernacular français
merci 
Luc

**Comment by MFavreau** [comment]
French name added.
