### ISSUE TITLE
Vernaculars for Arisaema stewardsonii

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3134]
Bonjour 
Recent review of Arisaema in eNA has shown the distinction of what were previously called var. or subspp. with the A. triphyllum complex. We now have A. stewardsonii as a distinct species in easteran Canada.

It needs vernacular names in French and English. It may be that some current names in triphyllum apply, but I am uncertain as people were not distinguishing them.

Merci

Luc

**Comment by manions** [comment]
English vernacular added

**Comment by MFavreau** [comment]
French names had been selected for subsp. stewardsonii and are adequate for species level. Reentered.
