### ISSUE TITLE
Centaurea ×moncktonii syn de Centaurea ×gerstlaueri

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3135]
Vernacular names for Centaurea ×gerstlaueri area currently inappropriate. See INPN for French, notably
This is a purely nomenclatural change, but it cleaned the synonyms quite a bit. Many that were listed by FNA are NOT syn of this hybrid- thus I removed them
data.canadensys.net/vascan/taxon/2975
data.canadensys.net/vascan/taxon/34007
Luc

**Comment by MFavreau** [comment]
Normally we do not coin new vernaculars for hybrids, but we do mention already existing vernaculars.

So, I entered the French name provided by IPNI.

Marc
