### ISSUE TITLE
Solidago brendae distribution

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3137]
There needs to be distribution listed for Solidago brendae as per Semple 2013 (already listed in the references).
LB, NF, NB, NS, PEI, QC, ON
Semple, J.C. 2013. A new species of Triplinerviae goldenrod in eastern Canada (Asteraceae: Astereae): Solidago brendiae.
Phytoneuron 2013-57: 1–9.
Brenda's goldenrod (Semple 2013)

**Comment by brouille** [comment]
Solidago brendae is a synonym of S. bartramiana now. But there seems to be a system error when I try to access the latter in the editor.

Anywaym, no more brendae.

Luc
