### ISSUE TITLE
Solidago bartramiana : error AJAX

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3138]
Carole
Solidago bartramiana, la dernière correction que j'ai faite dans ce genre, n'a aucune donnée visible, alors même qu'on indique des données. J'obtiens une erreur AJAX pour ce seul taxon. Cela m'empêche de placer Solidago brendae en synonymie. Je crois que cela empêche aussi une publication corrected des données.

Luc

**Comment by brouille** [comment]
Carole
J'ai toujours une erreur AJAX sur ce taxon - je ne peux corriger les données que j'ai besoin de changer.
Luc

**Comment by CaroleSinou** [comment]
Erreur AJAX due à une redondance dans la table taxonhybridparent.
Solidago bartramiana (id=3503) était hybride de lui même:

```
select * from taxonhybridparent where childid=parentid;
+------+---------+----------+------+---------------------+---------------------+
| id   | childid | parentid | sort | cdate               | mdate               |
+------+---------+----------+------+---------------------+---------------------+
| 1746 |    3503 |     3503 |    1 | 2023-09-20 14:12:06 | 2023-09-20 14:12:06 |
+------+---------+----------+------+---------------------+---------------------+
```

La suppression de la ligne a réglé le problème.
`delete from taxonhybridparent where id='1746';`
