### ISSUE TITLE
Achillea millefolium var. megacephala (Raup) B. 

### ISSUE THREAD

**Issue by AlexBERGER0N** [Canadensys/vascan-data#3139]
Bonjour Luc,

Dans Vascan, Achillea millefolium var. megacephala est intégré dans la page d'A. borealis (https://data.canadensys.net/vascan/taxon/10242?lang=fr) au lieu de celle d'A. millefolium (https://data.canadensys.net/vascan/taxon/2768?lang=fr).

Merci de regarder cela!
Bon dimanche

Alex

**Comment by brouille** [comment]
Alex
Il s'agit d'un probkème connu et d'une action délibérée: le nom de la var. n'a pas été transféré sous borealis. Je ne peux créer de nouveaux noms dans VASCAN. Donc, en attendant, une curiosité
LB
