### ISSUE TITLE
Solidago arguta

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#314]
[Originally posted on GoogleCode (id 547) on 2011-06-21]

move var. arguta as child of S. arguta
make subsp. arguta a syn of var. arguta

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-06-21 17:59Z]

further: remove subsp. in var. name - cannot do it currently for obscure reason

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2011-09-14 17:43Z]

The moving should now works.
I did a first release of fix for Issue 721 that should fix that bug.

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2011-09-15 15:53Z]

Luc, j'ai appliqué des nouveaux correctifs qui devraient faire avancer ce problème. Par contre, l'erreur qui disait que 'Solidago arguta var. arguta' existait déjà est véridique. Il s'agit d'un synonyme de 'Solidago arguta'.
