### ISSUE TITLE
changement de rang nécessaire

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3140]
Carole

Taxon 21662 Silene soczavana subsp. macrosperma
le rang devrait être var. et non subsp. avec ce taxon (et considérant les auteurs)
Svp changer le rang dans la base de données

Merci
Luc

**Comment by CaroleSinou** [comment]
Rang du taxon 21662 modifié dans la table taxon (15 à 16)
Information modifiées dans la table lookup : 
- Rank
- calname
- calnameauthor
- calnamehtml
- calnamehtmlauthor
