### ISSUE TITLE
Modification nécessaire à un vernaculaire français ; vérifier Mutarda

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3141]
j'ai ajouté le nouveau taxon data.canadensys.net/vascan/taxon/34082
Odontarrhena americana

L'auteur russe sépare les éléments de l'est russe et de l'Amérique du Nord adjacente au sein de O. obovatum en une sp séparée, O. americana. 

Présentement, le nom vernaculaire français est alysson obové, qui s'applique à un taxon eurasiatique non présent en Amérique. Il faut un nom pour O. americana (le plus évident serait "alysson américain").

Also, the genus Mutarda (yes, mustard!) was re-established to accomodate a small, distinct clade including 2 spp present in Canada: nigra and arvensis. Please check that the vernaculars are still appropriate.

Merci
Luc

**Comment by manions** [comment]
reviewed English vernaculars for Odontarrhena and Mutarda

**Comment by MFavreau** [comment]
Nom français corrigé pour l'Odontarrhena americana. Ce sera « moutarde d'Amérique ». L'adjectif « américain » a un sens ambigu, et nous avons jusqu'ici privilégié les formes telles que « du Canada », « d'Alaska », , etc.,

Les noms français sont corrects pour les deux _Mutarda_.
