### ISSUE TITLE
add Platanthera ephemerantha R.M. Bateman

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3142]
Several jurisdictions (including BC eFlora and BC Conservation Data Centre) are listing Platanthera ephemerantha R.M. Bateman instead of Platanthera candida/Piperia candida. Ann. Bot. (Oxford) 104(3) 2009
Could you review and add as a synonym or revise please?
I apologize if already in the database, I haven't been able to access the database online in a while but hopefully soon to continue on the English vernacular review.
Marilyn

**Comment by brouille** [comment]
Marilyn
I warned Carole about the inaccessibility of the VASCAN editor. I had the same trouble.
Luc

**Comment by brouille** [comment]
This change is required. Platanthera candida already existed (Lindl., also nom. illeg. but prior anyway).

I will do it as soon as I can access the database.

**Comment by brouille** [comment]
Marilyn and MArc
I now replaced  P. candida by P. ephemeranthera
Though Klinkenberg kept the English vernacular as is, I find this potentially misleading given that may P. candida exists elsewhere as a valid name. I leave you to consider this. You are free to keep as is, of course. I moved the current vernaculars.

Luc

**Comment by manions** [comment]
Hi, would it be possible to send Bateman's paper on this species please? The description might be helpful. Thanks

**Comment by manions** [comment]
many thanks!

**Comment by MFavreau** [comment]
I entered a more specific accepted French vernacular and retained the previous one as a synonym.

**Comment by manions** [comment]
Likewise, English vernacular added and kept the synonyms
