### ISSUE TITLE
Rumex rugosus or Rumex rugosa

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3143]
FNA (2005 page 490) uses Rumex rugosus, whereas it's listed as Rumex rugosa in the VASCAN database.
Just wondering which is correct?
Thanks

**Comment by MFavreau** [comment]
Rumex is clearly a masculine noun, so the correct name should be Rumex rugosus.

Marc

(depuis mon téléphone)
________________________________
From: manions ***@***.***>
Sent: Thursday, August 8, 2024 11:55:08 AM
To: Canadensys/vascan-data ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Canadensys/vascan-data] Rumex rugosus or Rumex rugosa (Issue #3143)


FNA (2005 page 490) uses Rumex rugosus, whereas it's listed as Rumex rugosa in the VASCAN database.
Just wondering which is correct?
Thanks

**Comment by brouille** [comment]
correction done
Thanks
Luc
