### ISSUE TITLE
Muhlenbergia uniflora in PEI

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3144]
Please add PEI for the distribution of Muhlenbergia uniflora.
"During recent fieldwork near Beaton Road in western Prince Edward Island, our Botanist Burke Korol discovered One-flowered Muhly Grass (Muhlenbergia uniflora)"
"The record is documented on iNaturalist (link below), and specimens have been collected for permanent deposition at the E.C. Smith Herbarium at Acadia University"
https://www.inaturalist.org/observations/233555633?fbclid=IwY2xjawEpkk5leHRuA2FlbQIxMAABHenxV__D9YwtoggABvrH45xKO2uSQCuCGUK18yzLDk6Jy4hWXfCaF_UUMQ_aem_7L2DSoGFb30SpWrF6R6OYg

**Comment by brouille** [comment]
Thanks Marilyn
I was unaware of this addition. I am pleased that a specimen was collected for ACAD. I can cite this.
Luc
