### ISSUE TITLE
BC Additions, Deletions and Taxonomic Changes 2024

### ISSUE THREAD

**Issue by manions** [Canadensys/vascan-data#3149]
BC Conservation Data Centre has produced an Excel file with BC additions, deletions and taxonomic changes for 2024 (see link for excel file).
For your review.
If some new species added, please let Marc and I know for the vernaculars. Thanks

https://www2.gov.bc.ca/gov/content/environment/plants-animals-ecosystems/conservation-data-centre/explore-cdc-data/conservation-data-centre-updates/2024-plant-changes

**Comment by manions** [comment]
here is BC's excel file with the additions, deletions etc. Some new species for Canada (if accepted). Frank Lomer would be the person to connect with, if there are questions.
[BC 2024_vascular_plant_changes.xlsx](https://github.com/user-attachments/files/16893797/BC.2024_vascular_plant_changes.xlsx)

**Comment by brouille** [comment]
Additions to BC requiring vernaculars in both languages:

Aquilegia xminiana - hybrid columbine [in BC-CDC 2024] - but this is meaningless in many ways
Chenopodium pedunculare - spreading goosefoot

**Comment by brouille** [comment]
Additions (Cont'd) [NB: I am not mentioning here addition that were already in VASCAN]

Elatine orthosperma - straight-seed mudwort
Phleum bertolonii - diploid timothy [using ploidy level in a vernacular name seems odd to me]
Trifolium micranthum - slender trefoil
Verbena officinalis var. officinalis - European vervain

Fin des additions

**Comment by brouille** [comment]
Marilyn 
See also suggestions of En vernacular name change done by BC in the list

**Comment by manions** [comment]
reviewed/added English vernaculars, including review of BC name changes.
Added Cronk's paper on Aquilegia x miniana in references

**Comment by MFavreau** [comment]
French names added for all additions except Aquilegia xminiana (hybrid).

In the case of hybrids, any existing French name can be recorded, but no new French name is coined. Same policy as for species occurring in Greenland but not in Canada.
