### ISSUE TITLE
Ajout syn à Solidago caesia

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#315]
[Originally posted on GoogleCode (id 548) on 2011-06-21]

Ajouter: S. lateriflora Rafinesque ex de Candolle
http://www.efloras.org/florataxon.aspx?flora_id=1&amp;taxon_id=250068757

re: homonyme

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-09-15 19:47Z]

Homonym problem solved and synonym has been added. Please add the correct taxonconcept (FNA something).

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-15 20:01Z]

source ajoutée
