### ISSUE TITLE
Addition to Ontario

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#3151]
Require vernacular names

34156 Veronica dillenii 
Dillenius speedwell FNA

Luc

**Comment by brouille** [comment]
34159 Akebia quinata
Chocolate-vine, five-leaf FNA
Five-leaf Akebia OMNR

**Comment by brouille** [comment]
34166 
Rubus ulmifolius var. anoplothyrsus
Elm-leaf blackberry [sp] FNA - var inerme

**Comment by brouille** [comment]
34168
Liquidambar styraciflua
FNA: Sweetgum, redgum

**Comment by brouille** [comment]
34173
Viola latiuscula
Broad-leaved wood violet 
(Ballard et al 2023)

**Comment by manions** [comment]
Added English vernaculars for the 5 taxa listed so far

**Comment by MFavreau** [comment]
French names added for all five.
