### ISSUE TITLE
Solidago : corrections aux sections

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#317]
[Originally posted on GoogleCode (id 550) on 2011-06-22]

Enlever sous-genre Solidago et conserver sect. Solidago
Transférer espèces de sous-sect. Corymbosae à sect. Ptarmicoidei et éliminer la sous-section après avoir transféré les spp

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-09-15 19:48Z]

First part of the task has been done.
