### ISSUE TITLE
Add ref Elven 2007 http://www.binran.ru/infsys/paflist/taxon/pteridophytes.htm

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#319]
[Originally posted on GoogleCode (id 556) on 2011-06-29]

Ajouter réf. 
Elven, R. (Ed) (2007 +). Checklist of the Panarctic Flora (PAF) Vascular Plants. Version: May 2007. http://www.binran.ru/infsys/paflist/index.htm

re: Huperzia selago pres GR

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-30 15:52Z]

Elven, R. (Ed) (2007 +). Checklist of the Panarctic Flora (PAF) Vascular Plants. Version: May 2007. http://www.binran.ru/infsys/paflist/index.htm

This reference has now been added to the database. Luc, could you check if this makes sense (I have adapted the reference slightly):

Ref: Elven, R. (Ed). 2007+. Checklist of the Panarctic Flora (PAF) Vascular Plants. http://www.binran.ru/infsys/paflist/index.htm (consulted 2007-05)
Shortref: Elven, 2007
URL: http://www.binran.ru/infsys/paflist/taxon/pteridophytes.htm (!different url from above?)

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-09-09 15:26Z]

Reference added to list. Needs to be added to the taxon.
