### ISSUE TITLE
Carex arctogena

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#32]
[Originally posted on GoogleCode (id 1429) on 2012-10-06]

Salut Luc

Il semble que cette espèce soit valide selon Jacques Cayouette et Benoît Tremblay.

Tous mes spécimens de Carex capitata ont été revisé par eux à cette espèce.

Peux-tu vérifier avec Jacques pour sa source?

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-29 13:24Z]

Fred

Il semblerait que Cayouette et Tremblay ne suivent pas FNA...

Je ne sais pas la raison de ces annotations: est-ce qu'ils ne se sont pas soucié du nom prioritaire ou séparent-ils les deux? 

Il faudrait leur demander.

Luc

**Comment by FredCoursol** [comment]
[Originally posted on GoogleCode on 2012-11-19 22:07Z]

Ils séparent les deux

Envoyé de mon iPhone
Frederic
