### ISSUE TITLE
ajout source vernaculaire anglais Draba glabella var. glabella

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#326]
[Originally posted on GoogleCode (id 663) on 2011-08-08]

smooth whitlowgrass (Canadian Forest Service - I think this is what you are referring to for the Plant Hardiness website of Sue Meades)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-05 13:22Z]

Marilyn

Could you check this so that I can close this issue, please?

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-18 13:04Z]

completed
