### ISSUE TITLE
Bulk-add ref for Manitoba

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#329]
[Originally posted on GoogleCode (id 667) on 2011-08-08]

we need to add the proper ref to Manitoba reports, which are currently empty

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-09-09 15:47Z]

First we need the correct reference.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-01-17 17:36Z]

What do you mean by "done"?
1) The correct reference has been found?
2) It has been added (manually?) to all distributions for Manitoba?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-17 19:04Z]

It has been added automatically to all references and I am adding it
manually as I go and find missing ones.

I still have to find the proper citation, but there is a minimal one.

I wanted to eliminate some of the issues that stay there for nothing.

Luc
