### ISSUE TITLE
Mimulus sookensis B.G. Benedict, Modliszewski, Sweigart, N.H. Martin, Ganders & John H. Willis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#33]
[Originally posted on GoogleCode (id 1453) on 2012-10-18]

Salut

Addition à la flore de B.C.
Mimulus sookensis_ B.G. Benedict, Modliszewski, Sweigart, N.H. Martin, Ganders &amp; John H. Willis

Quelques sources.
Beardsley,  P.M., S.E. Schoenig , J.B. Whittall, &amp; R.G. Olmstead. 2004. Patterns of evolution in western North American Mimulus (Phrymaceae). American Journal of Botany_ 91, 474-489.
Benedict,  B.G. 1993. Biosystematics of the Mimulus guttatus species complex. Master’s thesis. University of B.C., Vancouver, BC. 
Benedict,  B.G., J.L. Modliszewski , A.L. Sweigart, N.H. Martin, F.R.  Ganders, &amp; J.H. Willis. 2012. Mimulus sookensis (Phrymaceae), a new allotetraploid species derived from Mimulus guttatus and Mimulus nasutus. Madroño 59, 29–43. 
Modliszewski,  J.L. &amp; J.H. Willis. 2012. Allotetraploid Mimulus sookensis_ are highly interfertile despite independent origins. Molecular Ecology  doi:10.1111/j.1365-294X.2012.05706.x

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-19 18:07Z]

Fred

Ne me disais tu pas qu'il y avait un BEN le citant? J'ai besoin d'une source pour B.C.

Luc
