### ISSUE TITLE
Vernaculaire pour Syringa reticulata

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#331]
[Originally posted on GoogleCode (id 688) on 2011-08-19]

Je viens d'ajouter 
Syringa reticulata subsp. reticulata int Ont.

Pringle (FNA ms) a les vernaculaires suivants: Japanese tree lilac, lilas japonais

Il faut noter que la subsp. amurensis est reconnue (cultivée mais non introduite).

Noms vernaculaires français et English svp.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2011-08-22 15:17Z]

yes I'm in agreement with the proposed vernaculars.
For the English name, you can use FNA ms or USDA PLANTS as the reference.
Cheers
Marilyn

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-22 17:32Z]

I entered the English vernacular

Marc: français?

Would this vernacular be OK for the species also?

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-08-22 20:33Z]

Oui Luc, le nom « lilas japonais » est nettement le plus courant. Tu peux utiliser la source 246 (Macura, 1979).

De plus, le nom peut être appliqué à la fois à l'espèce et à la sous-espèce reticulata.

Marc
