### ISSUE TITLE
Pimpinella saxifraga : noms vernaculaires

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#332]
[Originally posted on GoogleCode (id 699) on 2011-08-22]

Pimpinella saxifraga

À la suggestion de Fred et suite au traitement de FNA, j'ai ajouté la susbp. saxifraga à cette espèce.

Comme elle est autonyme, j'ai transféré toutes les données à la subsp., incluant les noms vernaculaires.

Cependant, cela nous laisse sans vernaculaires pour l'espèce. Devrais-je simplement utiliser les noms acceptés de la sous-espèce (noms vernaculaires originaux de l'espèce)? Devrais-je recopier aussi les noms secondaires?

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-08-22 13:20Z]

Oui, Luc,

Dans ce cas-ci, tous les noms vernaculaires français s'appliquent à la fois à l'espèce et à la sous-espèce typique.

Les sources ne donnent ces noms français que pour l'espèce, mais je ne fais pas cette distinction et j'applique indifféremment les noms recensés à la fois à l'espèce et aux taxons infraspécifiques autonymes, sauf si la distinction est faite explicitement dans une des sources, ce qui n'est pas le cas cette fois-ci. Je mentionnerai cette politique dans l'énoncé des règles suivies.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-22 14:25Z]

Merci Marc

Je vais les copier car je ne peux simplement les transf�rer: cela les enl�ve
du taxon de provenance.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-08-22 14:35Z]

OK. Une de faite!
Merci,

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-22 17:18Z]

Here is Marilyn answer:
yes I'm in agreement with the proposed vernaculars.
For the English name, you can use FNA ms or USDA PLANTS as the reference.
Cheers
Marilyn
(M: pls respond through the Google Code page)

En examinant la situation des noms vernaculaires pour espèces ayant des infraspecies, je suggère la politique suivante:

les espèces avec infraspecies ne recevront que des noms vernaculaires acceptés, à moins qu'il y ait une raison majeure d'ajouter un "synonyme"

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-08-22 17:23Z]

Luc,

Je suis bien d'accord avec toi pour conserver seulement un nom accepté pour les taxons infraspécifiques, d'autant plus que je me demandais au début s'il valait même la peine de donner un nom français à ces taxons.

Une exception notable sera le cas où une variété est désignée par le gouvernement du Québec sous un nom qui ne respecte pas nos conventions, style « charme de Caroline variété de Virginie». En pareil cas, il faudra donner le synonyme.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-22 17:26Z]

Marc

Tu donnes un excellent exemple d'exception nécessaire.

Luc
