### ISSUE TITLE
Spiraea septentrionalis syn de S. latifolia

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#334]
[Originally posted on GoogleCode (id 710) on 2011-08-24]

Dans la version corrigée de son manuscrit FNA 9, R. Lis, auteur de Spiraea, suivant les recommandations de plusieurs réviseurs régionaux, a mis S. septentrionalis en syn du S. latifolia

Or les noms vernaculaires pour septemtrionalis devraient être transférés au S. latifolia

Cependant, dans les deux cas (l'un des noms était identique à un nom vern. de latifolia), il semble que les noms vernaculaires fr et en soient des noms nouveaux, l'un créé par Marc et l'autre sans source

Je propose de tout simplement éliminer ces deux noms puisqu'ils n'ont pas eu cours.

D'accord?
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-24 13:06Z]

agree, please use the English vernacular for both the subsp and the species.
now in Saskatoon at the COSEWIC SSC vascular plant meeting, so tied up for a few days!
Cheers
Marilyn

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-08-24 13:23Z]

Oui, tu peux éliminer ces deux noms. C'est exactement ainsi que je procède, en m'assurant que le nom créé précédemment n'est pas entré en usage. Ce n'est certainement pas le cas cette fois-ci.
Marc
