### ISSUE TITLE
Trifolium glomeratum added to BC

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#338]
[Originally posted on GoogleCode (id 768) on 2011-09-14]

Marc et Marilyn

J'ai besoin de vernaculaires pour ce taxon récemment ajouté à VASCAN pour BC

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-09-15 13:24Z]

Bonjour Luc et Marilyn,

L'espèce est présente en France. J'ai donc inscrit dans la base les deux noms français retenus par TelaBotanica, dont un accepté et un comme synonyme.

Luc, je ne sais pas comment spécifier qu'il s'agit de noms vernaculaires français. Peux-tu me l'expliquer? Je ne vois pas comment le système pourrait reconnaître les deux langues.

Merci,

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-15 19:04Z]

Marc

Est-ce que ton écran te fais voir tous les champs? Si tu es incertain, svp envoyer un "screenshot" à Peter.

Cependant, tu devrais voir à la droite (sous "importer des noms vernaculaires"), un tab intitulé "Langue". Il est à fr par défaut. Cependant, si tu cliques, un choix s'offre à toi entre fr et en.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-09-15 19:25Z]

Effectivement, en écrapoutissant la colonne de recherche, je récupère deux colonnes à droite : le choix de la langue, et les X servant à éliminer un nom. Je crois cependant qu'il y a quelque chose encore plus à droite, mais je n'arrive pas à l'atteindre. Est-ce qu'il y a quelque chose d'important pour moi?

Si oui, je vais demander à Peter de m'aider.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-15 19:31Z]

MArc

Il n'y a rien de plus � droite, sinon une barre de d�filement.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-09-15 19:34Z]

Merci Luc. Case closed.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2011-09-21 20:32Z]

added english vernacular 'clustered clover' into database, hopefully added correctly...
Marilyn

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-09-21 20:36Z]

This looks fine to me.
Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-22 12:37Z]

Vernacular names fine.
Thanks.
