### ISSUE TITLE
Taxon avec un ou des noms vernaculaires synonymes, mais aucuns acceptés

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#339]
[Originally posted on GoogleCode (id 779) on 2011-09-22]

Marc

Dans le back-end, pourrais tu svp vérifier les noms vernaculaires français sous les taxons listés dans la rubrique ci-dessus. Pour en trouver la liste, aller dans:
Tâches administratives &gt; Taxons à vérifier et sélectionner la bonne rubrique.

Il reste trois taxons avec des vernaculaires français, mais synonymes, aucun accepté. Serait-il possible de vérifier ces noms, s'ils doivent même demeurer? (Les cardamines ont le même nom, utilisé ailleurs)

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-09-23 12:41Z]

Voilà Luc, c'est fait.
Je me rappelle le cas de la lysimaque hybride. J'avais relevé un nom français dans la Flore-Manuel, mais il n'était pas satisfaisant, alors je l'avais conservé comme synonyme, mais je n'ai pas désigné de nom accepté parce qu'il s'agit d'un hybride. J'ai éliminé ce nom synonyme dans vasCan; pas une grosse perte.

J'ai aussi éliminé les deux synonymes de cardamine, car ce nom désigne une autre espèce, le C. flexuosa, où il est correctement retenu comme synonyme.

Le C. occulta, le C. corymbosa et peut-être d'autres cardamines demeurent sans nom français. Je vais faire le ménage là dedans bientôt et combler les trous.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-12 14:16Z]

Merci
