### ISSUE TITLE
Sedum album

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#34]
[Originally posted on GoogleCode (id 1577) on 2012-11-15]

Salut

L'espèce est très abondante sur des sites calcaires qui ont été décapés à Laval.  

J'ai des photos pour documenter.....

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-12-12 21:51Z]

Avons nous un spécimen à MT? Des photos c'est bien, mais cela ne me donne pas une source. Pour l'instant je vais ajouter Coursol... mais ce serait bien éventuellement de documenter de façon appropriée. À moins que tu connaisses une référence?

Lavoie et al. 2012 ne le listent pas parmi les introduites du Qc.

Luc
