### ISSUE TITLE
Amelanchier canadensis var. pumila

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#340]
[Originally posted on GoogleCode (id 780) on 2011-09-23]

Peter

While modifying data, I forgot to change the rank for Amelanchier canadensis var. pumila, a syn. of A. alnifolia var. pumila. 

I cannot change the rank now that it is saved. Could you change the rank of this taxon from species to var., please?

Thanks
Luc

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-09-23 17:58Z]

Fixed. Currently, if you create a child (synonym or accepted), the rank field is populated with a value. Would their be less errors if this field was empty?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-23 18:03Z]

Peter

Yes, if there were a warning if it is not filled.

Luc
