### ISSUE TITLE
Rosa rubiginosa var. nemoralis

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#342]
[Originally posted on GoogleCode (id 792) on 2011-10-14]

En accord avec Lewis &amp; Ertter ds FNA 9, je viens de mettre Rosa micrantha en synonymie de Rosa rubiginosa var. nemoralis. J'y ai transféré toutes les données, y inclus les vernaculaires anglais et français de micrantha.

Il se peut que ces vernaculaires ne soient pas adéquats pour la var. nemoralis. Svp vérifier et corriger au besoin.

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-25 19:33Z]

Le nom vernaculaire français « rosier à petites fleurs » peut suivre sans problème. À ma connaissance, il n'existe pas de nom français plus spécifiquement relié au nom nemoralis, et il y aurait risque de confusion avec le taxon différent désigné par l'épithète nemorosa.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-28 13:12Z]

Merci.

Marilyn, I also removed a duplicate English vernacular in the synonyms.
