### ISSUE TITLE
Rosa rubrifolia syn de R. glauca

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#343]
[Originally posted on GoogleCode (id 793) on 2011-10-14]

Dans le ms FNA9 de Lewis &amp; Ertter Rosa rubrifolia est synonyme de R. glauca et non l'inverse comme VASCAN l'avait.

J'ai transféré l'information de rubrifolia à glauca, mais encore une fois, les vernaculaires pourraient ne plus être appropriés comme tels. En particulier, un vernaculaire anglais syn est glaucous rose, qui semble plus approprié comme accepté.

Pourriez vous svp vérifier? Les données sont sous R. glauca

Merci

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-25 19:43Z]

Le nom français « rosier glauque » figure dans TelaBotanica pour le R. glauca. Je l'ai choisi comme nom accepté, et j'ai laissé l'autre nom comme synonyme.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:16Z]

completed
