### ISSUE TITLE
Noms vernaculaires pour Thinopyrum intermedium subsp barbulatum

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#346]
[Originally posted on GoogleCode (id 801) on 2011-10-20]

Considérant que FNA 24 divise Thinopyrum intermedium en deux subsp et que la subsp barbulatum a récemment été confirmée en BC, j'ai été obligé de séparer T. intermedium en deux subspp.: intermedium et barbulatum.

Les données de l'espèce ont été transférées à la subsp. intermedium (vernaculaires, etc.)

Il n'y a pas de vernaculaire pour la subsp. barbulatum.

Svp ajouter un vernaculaire accepté FR ou EN

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-25 19:55Z]

French name added.

Marilyn, you may want to consider the name "hairy wheatgrass" used in FNA24 p. 376.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:17Z]

completed
