### ISSUE TITLE
Integration du nom Bromus rigidus en synonymie de B. diandrus

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#347]
[Originally posted on GoogleCode (id 806) on 2011-10-24]

Selon FNA 2007, B. rigidus est syn. de B. diandrus. Les deux taxons étaient originalement séparés dans VASCAN. La fusion des deux noms a pour implication que les vernaculaires de B. rigidus sont maintenant sous B. diandrus, avec pour conséquence qu'il y a des doublons et que peut-être il faudrait sélectionner.

J'apprécierais que vous vérifiiez les noms vernaculaires sous B. diandrus.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-25 19:59Z]

Nettoyage fait pour les noms français.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:18Z]

completed
