### ISSUE TITLE
inclusion de Elymus calderi dans E. hirsutus

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#348]
[Originally posted on GoogleCode (id 815) on 2011-10-25]

Dans FNA 24, Elymus calderi est placé en synonymie de E. hirsutus

Svp réviser les noms vernaculaires que j'ai déménagé sous hirsutus: est-il pertinent de les maintenir tous?

MErci
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-25 13:40Z]

Désolé: dans lanceolatus subsp. psammophilus, pas hirsutus

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-26 19:29Z]

C'est fait pour les noms français. M.F.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:20Z]

completed
