### ISSUE TITLE
Elymus villosus: variétés non reconnues

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#349]
[Originally posted on GoogleCode (id 817) on 2011-10-25]

Dans FNA 24, les variétés E. villosus var. villosus et var. arkansanus sont considérées syn. de E. villosus.

J'ai donc fusionné les noms vernaculaires. Les noms pour la var. arkansanus avaient été imaginés par Marc et Marilyn: peut-on les abolir? Ils me semblent maintenant superflus.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-26 19:34Z]

J'ai effectivement éliminé le nom "élyme d'Arkansas".
Marilyn, I leave it to you to determine if a similar change is required in English.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:20Z]

completed
