### ISSUE TITLE
Lechea intermedia var. intermedia    (autorité et répartition)

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#35]
[Originally posted on GoogleCode (id 1581) on 2012-11-16]

Salut

Les provinces dans FNAms ne concordent pas avec VASCAN.
Il faut ajouter Terre-Neuve dans VASCAN.

L'auteur selon FNAms est Leggett ex Britton

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-12-14 20:14Z]

autorité correcte ds VASCAN
pas à Nfld. selon toutes mes données - FNA ms est erroné
