### ISSUE TITLE
wrong rank for Poa nervosa subsp. wheeleri 

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#350]
[Originally posted on GoogleCode (id 822) on 2011-10-27]

The rank of Poa nervosa wheeleri was initially entered as subsp., but this name with this rank does not exist.

The proper rank should be var. wheeleri.

Please correct the rank.

Thanks.
Luc

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-10-28 18:55Z]

Corrected.
