### ISSUE TITLE
Crataegus gaylussacia

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#351]
[Originally posted on GoogleCode (id 825) on 2011-10-28]

Les noms vernaculaires ont été transférés de C. suksdorfii - sont ils adéquats pour C. gaylussacia?
Ceci suit les dernières corrections de FNA9

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-28 20:01Z]

Également: les deux vernaculaires sont présentement indiqués comme synonymes - il n'y a pas de vernaculaire accepté. Il faudrait changer cet indicateur une fois la décision prise sur le bon nom.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-10-28 20:32Z]

Better French name added, as accepted name. I corrected the spelling of the synonym but chose to keep it.

Marilyn : I was able to see the original description (Heller, A.A. 1903. Bulletin of the Southern California Academy of Sciences 2(6): 69.) : "fruit [...] much resembling the common black huckleberry of the east, whence the specific name."

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:18Z]

completed
