### ISSUE TITLE
Ajout espèce: Geranium aequale

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#352]
[Originally posted on GoogleCode (id 850) on 2011-11-11]

En révisant le ms de FNA, J. Cayouette (DAO) a identifié une collection du Québec comme G. aequale plutôt que G. molle (identification initiale).

Cela ajoute une espèce à VASCAN. Il faut donc des noms vernaculaires anglais et français pour celui-ci.

Merci

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-11-16 15:02Z]

J'ai ajouté le nom français « géranium à fruits lisses » après consultation de Jacques Cayouette et de la description originale du taxon.

Marilyn, this excerpt from Jacques' e-mail may be useful to you :
« Au sujet du nom « aequale », de sa signification et d’une possible application à LA caractéristique de cette espèce, je pense qu’on peut arriver à ceci. Selon mon Gaffiot (Latin-Français), un des sens d’aequale est « uni », comme un terrain uni. Le caractère principal du Geranium aequale est d’avoir des méricarpes à surface lisse, tandis qu’ils sont fortement ridés chez le G. molle. Selon l’expert mondial, Aedo, qui est aussi l’auteur du ms de FNA, il n’y a pas de conditions intermédiaires entre les méricarpes de molle et d’aequale. En passant, dans tous les travaux d’Aedo où il est question du Geranium aequale, il ne propose aucun nom vernaculaire. »
In the original description, the mericarps are referred to as "carp.", i.e. carpels, but Jacques and I agreed that it was better to refer to them as "fruits" for the purpose of a common name.
Of course, all of this is of no importance I you manage to find an already existing acceptable English name.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:22Z]

yes Jacques suggestion is good. Difficult one to research. I found 'glatter storchschnabel' in Austria for this species (smooth cranesbill)
