### ISSUE TITLE
Achillea pannonica syn de A. millefolium

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#353]
[Originally posted on GoogleCode (id 852) on 2011-11-17]

Suite à des vérifications, je viens de placer Achillea pannonica en synonymie de A. millefolium (l'espèce même, pas lanulosa). Plusieurs sources le mettent en synonymie.

J'ai transféré trois vernaculaires du premier vers le ssecond, mais je ne suis pas certain que cela vaille la peine de les maintenir. Ils sont sous Achillea millefolium. J'ai enlevé les noms acceptés pour les mettre en synonymie.

Ma recommandation serait de retirer les deux noms français et le nom anglais.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-11-17 14:58Z]

Luc,

Je pense que tu faisais plutôt référence à 1 nom français et 2 noms anglais. Je suis d'accord avec toi, et j'ai annulé le nom « achillée de Hongrie ».

Marilyn, I will leave to you the two English vernaculars that seem to apply only to A. pannonica.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-11-17 21:16Z]

Oui
Merci
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:22Z]

completed
