### ISSUE TITLE
Helianthemum transféré à Crocanthemum en Amérique du Nord

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#355]
[Originally posted on GoogleCode (id 916) on 2012-01-13]

Marc et Marilyn:

Les espèces nord-américaines du genre Helianthemum ont été tranférées au genre Crocanthemum suite à des travaux phylogénétiques (le traitement FNA réflétera cela). Ces espèces n'ont pas de relation avec Helianthemum européen, mais plutôt avec Hudsonia d'AN. J'ai fait le transfert des espèces dans VASCAN, ainsi que des vernaculaires. 

Svp, vérifiez que vous êtes toujours satisfaits des vernaculaires tels qu'ils sont.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-01-13 22:44Z]

Nous pourrions utiliser le générique « crocanthème » qui a déjà été utilisé pour deux espèces américaines non présentes au Canada mais certainement apparentées.
Cependant, comme le nom « hélianthème du Canada » est déjà employé au Québec aux fins de la protection de cette espèce rare (trois sources importantes), je crois que nous perdrions au change. Il vaut mieux favoriser l'efficacité de la communication et ainsi aider à la protection de l'espèce, même si c'est aux dépens de la rectitude taxonomique.

Je suggère donc que nous conservions les noms français actuels.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-16 16:47Z]

Aucun problème Marc
cependant, puisque crocanthème a été utilisé ailleurs, serait-il bon de l'ajouter?

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-01-16 17:34Z]

Bonne idée.

C'est inhabituel de créer des synonymes, mais je pense que c'est pertinent dans ce cas. Je vais donc créer les deux synonymes nouveaux, qui seront prêts si jamais certaines personnes jugent préférables de les employer.

Je pourrais même employer « crocanthème » comme nom accepté au niveau du genre, parce que j'ai une source à ce niveau.

As-tu une objection à ce que le nom accepté au niveau du genre soit « crocanthème » et que les noms acceptés au niveau des espèces soient « hélianthème x » et « hélianthème y »? Il y a d'autres cas semblables ,comme les huperzies, qui sont individuellement appelées « lycopodes ». Je pense que c'est une manière acceptable de respecter l'usage, même si ça paraît à première vue paradoxal.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-01-26 15:23Z]

Marc

Je n'ai aucune objection à tes changements.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:24Z]

completed review with English vernaculars
