### ISSUE TITLE
Luzula pallida synonyme de L. pallescens

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#356]
[Originally posted on GoogleCode (id 1039) on 2012-02-02]

Après vérification dans une source fiable, il appert que Luzula pallida (utilisé dans FNA et donc dans VASCAN jusqu'ici) est synonyme de L. pallescens Sw.

Les noms latins sont semblables, donc je présume que les noms vernaculaires le seront aussi.

Svp vérifier que les vernaculaires anglais et français sont corrects pour L. pallescens.

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-02-02 15:36Z]

Le nom français convient tout à fait au nouveau nom scientifique.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-02-02 21:12Z]

yes english vernaculars are still suitable, many thanks
Marilyn
