### ISSUE TITLE
Juncus arcticus, J. balticus, J. haenkei - nouveaux vernaculaires requis

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#358]
[Originally posted on GoogleCode (id 1080) on 2012-02-10]

En harmonisant VASCAN avec Kirschner et al. 2002 pour Juncus, des changements taxonomiques ont amené l'introduction de nouveaux taxons, dont certains nécessitent des noms ou la révision des noms existants:

J. arcticus subsp. alaskanus

J. balticus: il faut réviser les acceptés et synonymes pour ne conserver qu'un vernaculaire accepté EN et FR
les subsp. nécessitent des noms, dont certains sont peut-être des syn. de balticus
J. b. subsp. littoralis
J. b. subsp. ater

J. haenkei

Merci

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-02-10 22:06Z]

Il n'y a pas de problème pour le J. arcticus subsp. alaskanus, car un nom existait déjà. Cependant, il y a des problèmes avec le J. balticus subsp. littoralis, car il existe déjà un autre J. littoralis en France qui est un taxon différent. Il faudra que j'étudie attentivement l'article pour choisir des noms français adéquats.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-02-15 21:04Z]

Pour la subsp. littoralis, j'ai choisi "jonc des rivages" qui évite la confusion et semble correspondre à l'habitat de l'espèce.
Pour la subsp. ater, j'ai pu consulter la description originale de Rydberg, et il semble faire allusion à la couleur des gaines. Ce caractère n'est peut-être caractéristique de la sous-espèce au sens moderne, mais il s'agit de toute manière d'un assemblage disparate de formes à étudier, provisoirement réuni sous le nom ater.

Qu'en est-il du Juncus hesperius, nouvelle combinaison que les auteurs de l'article (Snogerup et al. 2002, p. 263) mentionnent pour îles de la Reine-Charlotte? Selon ces auteurs, un des synonymes de l'espèce est Juncus effusus var. bruneus Engelmann, alors qu'un J. effusus var. brunneus Engelmann (avec 2 n) figure comme synonyme de J. effusus dans VasCan. Il faudrait soit accepter la nouvelle espèce, soit inscrire ce nom comme synonyme, probablement du J. effusus.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-15 21:11Z]

Merci pour la mentione du J. hesperius.

JE vais voir ce dont il en est.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-02-29 14:59Z]

J. arcticus alaskanus, J. balticus, J. haenkei completed.
Was J. hesperius added?
I'm wondering about J. balticus subsp. littoralis EN vernacular yet. There are so many 'shore, coast, shoreline' names for rushes already in existance. (H. hesperius is also known as coast rush or coastal rush, however this could also be named 'Pacific coastal rush').
Would 'eastern Baltic rush' be considered suitable? As separated from ater by its distribution, however littoralis is as far as Great Lakes which is more central.
I appreciate your thoughts
Marilyn

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-03-05 16:42Z]

I placed 'shoreline rush' as the name for J. balticus subsp. littoralis
