### ISSUE TITLE
Luzula parviflora subsp. fastigiata

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#359]
[Originally posted on GoogleCode (id 1117) on 2012-02-14]

English vernacular required
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-02-29 14:52Z]

I'm having a bit of trouble with this one. Can I have your thoughts please?
Absolutely nothing I can find existing on this subspecies for an English vernacular.
Some possibilities:
erect small-flowered woodrush (based upon the word meaning and how 'fastigiata' has been used with other taxon)
reddish small-flowered woodrush (based upon Kirschner pg 49 "conspicuously reddish at base).
Many thanks
Marilyn

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-03-05 16:42Z]

I placed 'erect small-flowered woodrush' as the vernacular
