### ISSUE TITLE
Luzula parviflora subsp. melanocarpa

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#360]
[Originally posted on GoogleCode (id 1118) on 2012-02-14]

Cette sous-espèce, reconnue par Kirschner et al. 2002, n'a pas de vernaculaire français ou anglais - il faut en déterminer un accepté pour chaque

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-02-16 21:56Z]

J'ai retrouvé le nom « luzule à fruits noirs » dans une vieille note floristique sur Saint-Pierre-et-Miquelon mise en ligne par notre ami Roger Etcheberry. (http://www.grandcolombier.com/wp-content/uploads/pdf/Gautier_these_SPM_1866-67.pdf) Je me suis cité moi-même comme source, uniquement parce que cette référence ne figure pas dans notre liste actuelle.

Luc, crois-tu qu'il me serait possible dans l'avenir d'ajouter des références à cette liste? C'est toujours mieux d'avoir une source externe pour les noms.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-02-17 13:17Z]

Marc

Théoriquement, tu peux ajouter des références. 

Cela se fait sous Tâches administratives > Liste des références (sous le panneau navigation) > Ajouter une référence
Dans le rectangle Référence, ajouter la référence complète (aucun double espace)
Dans le rectangle Référence courte ajouter la citation courte
Dans le rectangle URL ajouter l'adresse URL (si elle existe)
Cliquer Mettre à jour - le no de référence s'ajoute automatiquement

Cependant, il faut bien respecter le format choisi.

Si tu n'es pas certain, envoies moi la référence complète et je l'ajouterai.

Il faut ajouter une référence avant de faire une nouvelle entrée car cela simplifie l'ajout de la référence ensuite.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-02-17 21:54Z]

Merci Luc, ça fonctionne. J'ai pu utiliser Gautier comme source.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-02-29 14:48Z]

completed
