### ISSUE TITLE
Anemone nemorosa ajouté à VASCAN

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#361]
[Originally posted on GoogleCode (id 1126) on 2012-02-17]

Suite à la découverte de spécimens de Anemone nemorosa (int. QC, excl. NF), j'ai créé une nouvelle entrée dans VASCAN.

Des noms vernaculaires acceptés sont nécessaires, English et Français, svp.

Je ne crois pas qu'il faille avoir de synonymes, etc.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-02-17 22:00Z]

L'espèce est présente en France, j'ai donc inscrit les noms français employés là-bas. Je me suis permis un synonyme en plus du nom accepté.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-02-29 14:48Z]

completed
