### ISSUE TITLE
Onosmodium réduit en synonymie de Lithospermum: vérifier les vernaculaires

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#363]
[Originally posted on GoogleCode (id 1196) on 2012-02-29]

Following recently published papers (and FNA too, apparently) Onosmodium has been included within Lithospermum (Boraginaceae).

Two new taxa in Lithospermum were created:
Lithospermum occidentale
Lithospermum parviflorum (see synonyms and vernaculars)

J'ai transféré les vernaculaires, mais ceux-ci ne sont peut-être plus appropriés dans Lithospermum, notamment les français acceptés.

Svp vérifier et corriger.

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-04-13 20:43Z]

Effectivement, le nom français « onosmodie » est peu usité et certainement moins fréquent que le nom « grémil » désignant les Lithospermum s.s. Cependant, comme le nom « onosmodie hispide » est actuellement employé par le gouvernement du Québec aux fins de la protection de cette espèce rare, je pense qu'il vaut mieux conserver les deux  onosmodies pour le moment, même si ces plantes appartiennent maintenant au genre Lithospermum.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 12:38Z]

Marilyn

What is your take on this?

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 18:58Z]

both English vernaculars are fine with this transfer.
