### ISSUE TITLE
Autre changement de taxonomie: Panicum rigidulum subsp. rigidulum devient Coleataenia rigidula subsp. rigidula

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#364]
[Originally posted on GoogleCode (id 1197) on 2012-02-29]

Dans le même article, et suivant un article antérieur de Soreng, Weakley et al. sortent la sect. Agrostoidea du genre Panicum (P. rigidulum dans notre flore).

J'ai transféré les noms vernaculaire à cette entité. Svp vérifier que tout est Ok pour vous.

Il me reste à déterminer que faire de la subsp. pubescens, non mentionnée dans l'article (autre papier, sans doute)...
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 12:39Z]

J'ai maintenant résolu la question complète pour ce genre.

Noms vernaculaires?

Merci

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-06-28 20:33Z]

Les noms français attribués à la sous-espèce sous Panicum peuvent être maintenus sous Coleataenia. Aucun changement n'est requis. J'ai ajouté les noms français requis pour l'espèce.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 18:59Z]

English vernaculars ok
