### ISSUE TITLE
change var. to subsp.

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#365]
[Originally posted on GoogleCode (id 1205) on 2012-03-05]

http://data.canadensys.net/vascan/taxon/18553
Hordeum jubatum var. breviaristatum

should be subsp. breviaristatum - there is no var. breviaristatum

Please change var. to subsp.

Thanks
Luc

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2012-03-05 20:53Z]

Done.
