### ISSUE TITLE
Vernaculars of Symphoricarpos rotundifolia var. oreophilus

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#366]
[Originally posted on GoogleCode (id 1284) on 2012-04-03]

FNA transfère S. oreophilus var. utahensis au S. rotundifolius var. oreophilus

J'y ai mis tous les vernaculaires - il faut les évaluer pour leur pertinence. 

Il faut aussi un vernaculaire accepté (fr et en) pour S. rotundifolius

Merci
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-04-03 13:59Z]

Correction:

Je suis allé trop vite. En fait, le taxon est transféré au nom suivant:
Symphoricarpos rotundifolius   A. Gray var. vaccinioides   (Rydberg) A. Nelson 

Voici ce que disent les auteurs: Variety vaccinioides is very often labeled Symphoricarpos oreophilus var. utahensis in herbaria and in floristic literature; however, the type of the latter name is referable to S. rotundifolius var. oreophilus.

Donc il faut de nouveaux vernaculaires pour ce taxon

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 12:56Z]

Progrès concernant ce problème?

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-06-28 20:26Z]

I used "symphorine des montagnes" for the species as a whole, because the English name "mountain snowberry" is used in CalFlora, and anything with "roundleaf" would risk confusion with the eastern S. orbiculatus, which is already called "symphorine à feuilles rondes".

I used "symphorine fausse-airelle" for the var. myrtilloides.

French names done.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:03Z]

agree with using round-leaved snowberry for S. rotundifolia. Var. vaccinioides as 'mountain snowberry'.
agreed with change for S. orbiculatus as 'coralberry'. Found also FR vernacular as 'symphorine à baies-de-corail' on GRIN if suitable to list?

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-11-20 21:28Z]

I added « symphorine à baies de corail » as a French synonym (I removed the hyphens, which are incorrect in this case). Thank you Marilyn.

End of story.
