### ISSUE TITLE
Potentilla hyparctica subsp elatior & P nana: même vernaculaire

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#367]
[Originally posted on GoogleCode (id 1285) on 2012-04-03]

Marc:

Barb Ertter a noté que P. nana et P. hyperarctica subsp. elatior ont toutes deux comme nom français Potentille naine

Elle se demande si ce nom ne devrait pas être restreint à P. nana.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-06-28 20:56Z]

Effectivement, maintenant que les deux taxons sont jugés distincts, le nom "potentille naine" doit être réservé au P. nana. J'ai renommé le P. hyparctica et ses deux sous-espèces, en me fondant sur le manuscrit FNA.
