### ISSUE TITLE
Hypericum hirsutum

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#368]
[Originally posted on GoogleCode (id 1349) on 2012-05-16]

Marc et Marilyn

DAns l'article suivant:
Heydon, P.A., G.C. Miller &amp; M.J. Oldham. 2011. Hairy St.John's-wort (Hypericum hirsutum L.) in the Toronto area, new to North America. Canadian Field-Naturalist 125 (3): 248-251.

Heydon et al. ont ajouté une nouvelle espèce à la flore du Canada: 
Hypericum hirsutum L.

J'ai déjà ajouté le nom vernaculaire anglais suggéré par les auteurs. Marilyn, svp confirmer que c'est OK et ajouter des syn. s'il en existe (je doute que ce soit utile).

Marc, svp ajouter un vernaculaire français. La plante est eurasiatique.

Merci
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-06-22 13:00Z]

Progrès sur ce problème?

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-06-28 21:01Z]

Comme l'espèce est présente en France, j'ai inscrit les noms proposés dans TelaBotanica.
Vernaculaire français réglé.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:15Z]

english vernacular as 'hairy St. John's-wort'
