### ISSUE TITLE
Modifications au genre Dryas et à Elymus innovatus

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#369]
[Originally posted on GoogleCode (id 1407) on 2012-07-31]

Marc et Marylin:

Suite à la révision du genre Dryas ds FNA, j'ai modifié les espèces et certaines n'ont pas de vernaculaires. Svp vérifier tous les vernaculaires.

Elymus innovatus: j'ai séparé en subsp. innovatus et subsp. velutinus. La dernière n'a pas de vernaculaires. La première en a 2, mais l'espèce en a 6 (anglais surtout). Svp, vérifier les vernaculaires et les assigner au bon enroit.

Merci

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-07-31 21:02Z]

Les noms français requis ont été ajoutés pour les deux genres. Dans le cas de l'Elymus innovatus, le nom scientifique accepté dans la base est plutôt Leymus innovatus.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-12-11 15:59Z]

finished Leymus, working on Dryas. Any ideas for Dryas punctata and D. x wyssiana? I'll look up the papers though...

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-12-14 12:39Z]

all EN vernaculars finished for Dryas, except D. x wyssiana. I'll wait to see if changing to D. x lewinii first.
Marc, thanks for your opinions on D. punctata.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-01-25 21:28Z]

I believe all vernaculars are finished now. Marc are you finished as well?
Then this issue can be closed.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-02-04 22:06Z]

Yes, French names done.

Marc
