### ISSUE TITLE
Polygonum aviculare subsp. boreale ajouté

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#370]
[Originally posted on GoogleCode (id 1412) on 2012-08-16]

VASCAN: espèce ajoutée

http://data.canadensys.net/vascan/taxon/26456
Polygonum aviculare subsp. boreale

svp, ajouter les noms vernaculaires

Merci

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-12-10 17:31Z]

English vernacular entered

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-12-10 17:52Z]

J'ai ajouté le nom français, qui avait déjà été présent dans une version antérieure (Excel) de VasCan mais avait curieusement été perdu en cours de route.
