### ISSUE TITLE
Packera glabella vernacular name

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#371]
[Originally posted on GoogleCode (id 1424) on 2012-10-01]

Marilyn:

Here is a comment from Mike Oldham concerning the English vernacular of Packera glabella (http://data.canadensys.net/vascan/taxon/3327) in VASCAN:

I notice that in VASCAN the species has the English common name “Grass-leaved Ragwort”, which doesn’t seem particularly appropriate since the leaves are certainly not at all grass-like.  The U.S. literature I checked most commonly uses “Butterweed” or “Yellowtop” (e.g. FNA, Voss &amp; Reznicek 2012), both of which seem more appropriate common names

I would appreciate that you correct this immediately, if you fell it needs correcting.

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-10-01 13:55Z]

completed
