### ISSUE TITLE
Changements au genre Impatiens

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#372]
[Originally posted on GoogleCode (id 1426) on 2012-10-03]

Les changements suivants ont été faits au genre Impatiens dans VASCAN:

1) ajout de I. balfourii (présent au QC) - spécimen à MT - j'ai ajouté le nom vernaculaire anglais selon FNA 13 mais il n'y a pas de vernaculaire français (impatiente de Balfour vient à l'esprit mais il y a sans doute un nom puisque la plante est horticole).

Marc: ajouter vern. fr.
Marilyn: valider le vern. angl.

2) le nom I. ecalcarata Blank. nom. illeg. est maintenant synonyme de de I. ecornuta, nouvellement publié et accepté ds FNA - j'ai transféré les noms vernaculaires depuis ecalcarata à ecornuta, mais ceux-ci ne sont peut-être plus adéquats (particulièrement le nom français). Les épithètes veulent dire la même chose.

svp, valider les vern. fr. et angl. au plus tôt. J'aimerais que cela ne traîne pas.

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-10-03 20:50Z]

1. J'ai ajouté les noms français pour I. balfourii fournis par Tela Botanica

2. Le nom français créé par Alain C. pour I. ecalcarata peut être conservé pour I. ecornuta.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-29 13:24Z]

Marilyn

I would appreciate your input to close this issue. Please validate the English vernacular.

Thanks

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:25Z]

ok for vernacular name transfers to I. ecornuta.
Added 'Balfour's jewelweed' to be consistent with other names in genus
