### ISSUE TITLE
Thermopsis montana var. ovata

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#373]
[Originally posted on GoogleCode (id 1428) on 2012-10-05]

Suite au traitement FNA de Thermopsis, j'ai dû faire des modifications aux espèces de Thermopsis ds VASCAN.

T. montana var. ovata est ajouté et T. gracilis var. ovata est devenu syn.
Il y avait déjà un vernaculaire fr de T. montana.

Il faudrait valider les vernaculaires fr et en de T. montana var. ovata.

SVP FAIRE LES PETITES CORRECTIONS RAPIDEMENT _ LES CHANGEMENTS S'ACCUMULENT SANS QUE LES PROBLÈMES SOIENT RÉSOLUS (SURTOUT ENGLISH)

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-10-05 20:56Z]

OK pour les noms français de T. montana et T. montana var. ovata

Je remarque que T. gracilis est toujours dans la base au niveau de l'espèce. Je suppose qu'il faudrait supprimer cette entrée.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-05 21:02Z]

MArc

Merci d'avoir souligné mon oubli. Le nom a été aboli de VASCAN

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-10-29 13:25Z]

Marilyn

Could you validate the English vernaculars of this taxon, so that I may close the issue, please?

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 19:25Z]

finished
