### ISSUE TITLE
Lechea intermedia: nouvelles variétés ds FNA

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#376]
[Originally posted on GoogleCode (id 1602) on 2012-12-14]

Le ms FNA a accepté plusieurs variétés dans Lechea intermedia

Pourriez vous tous deux vérifier les noms vernaculaires F et E dans toutes les var. et ajouter les manquants.

depauperata: impoverished pinwhell is used by FNA so it is OK as is Marilyn

Merci

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-12-20 21:57Z]

French names added for the varieties and the species as a whole.

Marilyn, concerning var. laurentiana, I used « léchéa de la vallée du Saint-Laurent », referring to the St. Lawrence valley as per Gray's Manual 1950, to avoid any confusion with Lechea maritima var. subcylindrica, léchéa du golfe Saint-Laurent. I believe the two taxa do not have overlapping ranges.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-01-25 21:35Z]

completed. I used 'Laurentian' which is commonly used for 'laurentiana'. I think the 'St. Lawrence Valley' is too confusing also with the other name 'Gulf of St. Lawrence'.
Other varieties completed as well.
