### ISSUE TITLE
ISSUES FROM MARILYN

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#378]
[Originally posted on GoogleCode (id 1608) on 2012-12-17]

Hi
Once again, I greatly appreciate BC's input into these names. Please don't hestiate at any time. At least I focus on a subset of the huge list!
We try to add vernaculars with a reference, so many of yours below, currently aren't available either with the BC CDC Explorer or on EFlora BC, hence were not added. Other names weren't added (such as Arabidopsis and Scrophularia), as it was just creating a new variation on an already well-established and suitable name.

For the ones below…

Luc - Agrostis castellana needs to be added to VASCAN. It is now recorded in BC. Then I'll add English vernaculars.

Arabidopsis - name not added, currently there is no such name published or available on any website

Botrychium tunux - is this new to BC? if so, please let Luc know as needs to be added to VASCAN map; common name not added

Genista tinctoria - name already present

Anthoxanthum hirtum - name already present, although I switched to 'hairy sweetgrass' which is a better vernacular

Ranunculus occidentalis var. hexasepalus - I'd like to add Haida buttercup as a vernacular once it is available either at BC CDC or EFlora BC.

Scrophularia nodosa - common name not added, is this now present in BC? If so please let Luc know as needs to be added to VASCAN map.

Cheers
Marilyn

cc: Jenifer.Penny@gov.bc.ca

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-12 19:26Z]

Agrostis castellana: added
Marilyn: you may add vernaculars

Marc: svp, ajouter vernaculaire français.

I have written to S. F. Lomer for other cases.
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-06-12 21:08Z]

J'ai inscrit le nom français recommandé par TelaBotanica.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 19:27Z]

Added English vernaculars for Agrostis and Ranunculus. The other EN names reviewed previously.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-21 13:07Z]

Following email with S.F. Lomer (last dated 2013-06-12):
Genista added source UBC
Scrophularia added source UBC
Botrychium tunux added source to come

Ranunculus occidentalis var. hexasepalus: in VASCAN but there seems to be uncertainty as to status - check Jennifer Penny

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-21 19:34Z]

Botrychium tunux source added V
RAnunculus occ. var. h. acc in BC
