### ISSUE TITLE
Lechea maritima   Leggett ex Britton var. subcylindrica

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#38]
[Originally posted on GoogleCode (id 1584) on 2012-11-16]

Salut

Variété reconnue dans FNAms. 
Une seule variété au Canada pour Lechea maritima.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-12-14 19:38Z]

Marc et Marilyn

Vernaculars are needed for the var. now recognized (the only taxon in Canada)
http://data.canadensys.net/vascan/taxon/14807

For the English, FNA ms has : Gulf of St. Lawrence pinweed (it is endemic to the two provinces, so I guess this suggestion is as good as any)

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-12-14 19:46Z]

The name "léchéa du golfe Saint-Laurent" is used for var. subcylindrica in the French version of the COSEWIC Status Report (2008). I will enter it as an accepted French name.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-01-25 21:31Z]

completed, thanks for the suggestion
