### ISSUE TITLE
Lechea pulchella var. moniliformis

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#380]
[Originally posted on GoogleCode (id 1610) on 2012-12-21]

Suivant FNA ms et M. Oldham, Lechea pulchella est représenté en Ont. par la var. moniliformis

Il y a des vernaculaires pour l'espèce mais pas pour la variété dans VASCAN.

Svp ajouter ceux-ci, FR et EN.

English in FNA ms: Bead pinweed (FNA in prep. a)

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-12-21 21:44Z]

Nom français ajouté pour la variété, selon l'explication donnée par Fernald (1950) pour le L. leggettii var. moniliformis : « resembling a chain of beads ».

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-01-25 21:35Z]

thanks for the name in FNA
