### ISSUE TITLE
Nom vernaculaire requis pour Verbena incompta

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#381]
[Originally posted on GoogleCode (id 1611) on 2013-01-08]

Marc et Marilyn:

Des noms vernaculaires sont requis pour V. incompta qui, selon FNA ms, est le nom correct pour l'entité retrouvée au Canada (V. bonariensis est une identification erronée pour le taxon rencontré ici).

English vernacular in FNA in press i: Common clasping vervain

Bonne Année

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-01-15 19:57Z]

Aucun nom français préexistant.
Nom français créé par traduction du nom latin.
Incomptus (-a, -um) : échevelé, peu soigné, dépeigné, anglais "unkempt".

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-01-25 21:37Z]

many thanks for the vernacular used in FNA prep
