### ISSUE TITLE
Gentianaceae: vernaculaires nécessaires

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#382]
[Originally posted on GoogleCode (id 1612) on 2013-01-11]

Marc et Marilyn:

Je viens de valider VASCAN avec le ms FNA de Pringle pour les Gentianaceae. Cela a résulté dans la création de plusieurs taxons (parfois en remplaçant d'autres). Cela nécessite de valider ou de créer des noms vernaculaires. Voici la liste:

Zeltnera exaltata et Z. muehlenbergii: anciens Centaurium, transférés - les vernaculaires F et E sont-ils toujours adéquats?

Gentianella quinquefolia v. occidentalis: aucun vern. E (Marilyn)

Gentiana: noms E et F
G. andrewsii: 2 vars.
G. affinis v. affinis
G. prostrata v. prostrata

Merci
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-02-04 11:52Z]

finished review of English vernaculars for most taxa in Gentianaceae, just missing a very few yet which need more thought

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-02-04 22:04Z]

Dans le cas des Zeltnera, nous pouvons continuer de les appeler en français « petite-centaurée », conformément à notre politique sur les changements de genre (comme dans le cas des asters). Les deux genres sont sûrement apparentés, puisqu'ils appartiennent à la même tribu. Un seul générique français peut donc suffire pour les Centaurium et les Zeltnera.

Gentiana andrewsii var. dakotica - Marilyn, you may want to add as a synonym the name used in USDA Plants database - Dakota gentian

French names completed for other varieties.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-02-05 14:11Z]

Many thanks for that suggestion (don't know how I missed it!)
I think we can close this issue, I've noted a couple yet I need to work on.
