### ISSUE TITLE
Mimulus modifié

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#383]
[Originally posted on GoogleCode (id 1616) on 2013-01-23]

Suite à une modification taxonomique majeure, le genre Mimulus a été divisié en plusieurs genres, dont un est présent au Canada. Il ne reste que 2 spp. de Mimulus au Canada (une espèce, sookensis, est trop récente pour avoir été transférée).

Les autres spp. ont été transférées au genre Erythranthe. Svp, vérifier les noms vernaculaires de toutes les espèces.

En particulier, Mimulus glabratus n'est pas au Canada. La var. jamesii est transférée à E. geyeri. Les noms vernaculaires de M. gl. ne sont pas adéquats pour ce taxon et je ne les ai pas transférés. Il faut donc en assigner de nouveaux.

J'imagine que Marc conservera Mimulus et Marilyn monkeyflower, mais il faut néanmoins tout valider.

Merci
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-01-27 14:50Z]

finished reviewing all the english vernaculars for Mimulus, Erythranthe and Phryma

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-02 20:26Z]

Noms français validés. Mimule pour tous les Mimulus et les Erythranthe. Je pense que c'est « Status Done ».
