### ISSUE TITLE
Paspalum distichum ajouté à la flore du Canada

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#384]
[Originally posted on GoogleCode (id 1622) on 2013-01-28]

Lomer 2013 dans http://www.ou.edu/cas/botany-micro/ben/ben463.html
vient d'ajouter Paspalum distichum à la flore de BC et du Canada

Il conviendrait d'ajouter les noms vernaculaires FR et EN.

Pour l'anglais, FNA 25 Suggère:
Knotgrass, Thompsongrass

Merci

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-01-28 21:24Z]

English vernaculars added

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-05 20:37Z]

French name added.
