### ISSUE TITLE
Heracleum sphondylium vs H. sibiricum

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#388]
[Originally posted on GoogleCode (id 1626) on 2013-02-08]

Following the FNA ms and other data, we have a slight situation with Heracleum

In VASCAN, we currently have H. sphondylium subsp. sibiricum as present in eastern Canada. However, this should be sphondylium sensu stricto.

We have H. sibiricum in Yukon (introduced), confirmed by Bruce Bennett, which in fact has as a syn. H. s. subsp. sib.!

I added H. sibiricum to VASCAN, and updated H. sphondylium with data from the subsp. However, this does not solve all issues.

The difficulty concerns the French and English vernaculars: the accepted vernaculars, both in FR and EN, appear to apply to H. sibiricum. Other vernaculars may apply only to sphonlylium, but I am uncertain.

Before I make H. sphondylium subsp. sibiricum a synonym of H. sibiricum, I need for both of you to clean (immediately if possible - I would like to clear this before the next compilation and it does not take long to do) the vernacular, attributing the proper vernaculars to sibiricum. Note that sphondylium also may need cleaning, but there are vernaculars there currently.

Once the vernaculars are removed from the subsp., I will be able to synonymize it with sibiricum and close this particular issue.

Thanks for acting promptly.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-02-11 15:30Z]

Many thanks, one name I had was quite inappropriate for H. sphondylium. Review finished for Heracleum

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-05 20:53Z]

Mille excuses, je n'avais pas remarqué l'urgence de ce changement, car je remettais systématiquement à avril toutes les demandes.

Tous les vernaculaires qui étaient sous l'Heracleum sphondylium subsp. sibiricum sont maintenant éliminés ou déplacés vers d'autres taxons. Cette sous-espèce peut maintenant être placée en synonymie de l'H. sibiricum.
