### ISSUE TITLE
Myriophyllum spicatum subsp. squarrosum  = var. squarrosum

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#389]
[Originally posted on GoogleCode (id 1641) on 2013-02-19]

Christian:

Quand les données ont été entrées, on a mis le taxon ci-haut (http://data.canadensys.net/vascan/taxon/16550) sous le rang de subsp.

Or le rang correct de ce taxon est variety.

Pourrais tu svp modifier le rang dans la base de données (car je ne peux pas dans admin).

Merci
Luc

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2013-02-21 18:15Z]

Corrigé, sera disponible lors de la prochaine compilation.

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2013-03-08 19:07Z]

Fait
