### ISSUE TITLE
Corriger statut de l'entrée 27026 dans VASCAN

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#390]
[Originally posted on GoogleCode (id 1643) on 2013-02-26]

En entrant le taxon Astragalus speirocarpus var. falciformis A. Gray (27026) dans VASCAN, j'ai malencontreusement oublié de changer le statut de species à
 variety

Svp changer species à variety

Merci
Luc

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2013-03-08 19:05Z]

Fait
http://data.canadensys.net/vascan/taxon/27026
