### ISSUE TITLE
Mauvais rang pour taxon Tragacantha mortonii

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#391]
[Originally posted on GoogleCode (id 1645) on 2013-03-07]

En entrant le taxon Tragacantha mortonii, j'ai mal corrigé le rang.

Rang présent: variety
Rang désiré: species

svp faire le changement

taxon no 27080

merci 
Luc

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2013-03-08 19:06Z]

Fait
http://data.canadensys.net/vascan/taxon/27080
