### ISSUE TITLE
Polemonium villosissiumum in Yukon

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#392]
[Originally posted on GoogleCode (id 1661) on 2013-03-22]

Hi Luc:
 
I tried to enter feedback from the feedback tab on VASCAN, but it sent me to a Google site, which does not allow me to sign in.
 
Sorry.
 
Polemonium villosissimum is a recently described species of Alaska and Yukon. I have used the common name Hairy Polemonium as I can find no other.
 
It is known from Alaska and Yukon.
 
http://www.brit.org/sites/default/files/public/BRIT%20Press/JBRIT5(1)/019-24_Murray_Elven_Polemonium_JBRIT5(1)19-24_3.pdf 
 
Hope all is well.
Bruce
 
Bruce Bennett, coordinator
Yukon Conservation Data Centre
www.env.gov.yk.ca/cdc &lt;http://www.env.gov.yk.ca/cdc&gt;  
Your Trusted Source For Conservation Data

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-03-22 19:25Z]

Marilyn: can you see whether the name suggested by Bruce is OK for Canada?

Marc: vernaculaire français svp

Il y a une entrée ds VASCAN - admin maintenant.

Merci

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-22 20:35Z]

French name "polémoine velue" added. It is not used for any other species.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-19 11:43Z]

Discussed this with Bruce Bennett (YT) and Matt Carlson (AK). Together we choose the English vernacular as Alaska Jacob's-ladder. It only occurs in AK and YT. Also 'hairy Jacob's-ladder' seems applied to P. reptans var. villosum (in the U.S.), so wanted to avoid. 
Marc - I'm not sure if you want to review the French vernacular or not.
Then we can set this one as 'done'.
