### ISSUE TITLE
Rubus hybrids

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#393]
[Originally posted on GoogleCode (id 1733) on 2013-04-08]

Sue:

These names all apply to hybrid taxa, which I have not always added to VASCAN yet.

Rubus wisconsinensis = pensylvanicus x setosus (maybe) - what is the (full unless already in VASCAN) ref for report ?

Rubus recurvans : name of uncertain application, may refer to plants of hybrid origin – I cannot add such a name, unfortunately – the specimen will need to be verified as to current identity

Rubus xtardatus = hispidus x setosus – will add for QC, eventually
Rubus xtrifrons = hispidus x setosus
Given that the last two are hybrid combs. between the same species and that others are this same combination, the earlier name will need to be ascertained.

Rubus subg. Batidea (see TROPICOS). Batidaea is a mispelling

Luc
￼
De : Sue Meades &lt;sjmeades@sympatico.ca&gt;
Date : Sun, 7 Apr 2013 13:09:29 -0400
À : Luc Brouillet &lt;luc.brouillet@umontreal.ca&gt;
Objet : Rubus questions

   Hi Luc,
 
 There are 4 Rubus species that aren't listed in Vascan that I have as occurring in Canada: 
 
 Rubus wisconsinensis L.H.Bailey - is this a syn. of Rubus pensilvanicus Poir.?
 
 Rubus recurvans Blanchard - GRIN has this listed and distinct and from sQue.
 
 Rubus xtardatus Blancard - EOL &amp; FLore Laurentienne website have this listed from sQue.  Also, this is listed in ITIS as a hybrid, but no parents are given.  Is this a hybrid or true species?
  

      &lt;http://www.florelaurentienne.com/flore/Groupes/Spermatophytes/Angiospermes/Dicotyles/050_Rosacees/11_Rubus/tardatus.htm&gt; 
 
      &lt;http://eol.org/pages/244362/overview&gt; 
 
 

 Rubus xtrifrons Blanchard - EOL has this listed from Quebec; also no parents are given.
 
            &lt;http://eol.org/pages/631470/overview&gt;
 
 Also, the genus Batidea is spelled 2 different ways in different entries:
 Batidea for syns of Rubus idaeus subsp. strigosus
 Batidaea for syn of Rubus leucodermis
 
 Which spelling is correct?
 
 Thanks, Sue.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-08 12:32Z]

R. x\adjacens Fernald = Rubus hispidus x R. setosus
R. x\jacens Blanchard = R. hispidus x R. setosus
R. x\parlinii L. H. Bailey = R. hispidus x R. setosus
R. x\spiculosus Fernald = R. hispidus x R. setosus
R. x\tardatus Blanchard = R. hispidus x R. setosus
R. x\tholiformis Fernald = R. hispidus x R. setosus
R. x\trifrons Blanchard = R. hispidus
R. x\zaplutus L. H. Bailey = R. hispidus x R. setosus

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2013-04-09 01:24Z]



ITIS was the source I had that synonymized R. wisconsinensis with R. pensilvanicus, although I don't know reliable they are.
http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=25085

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-04-16 18:47Z]

R. x\adjacens Fernald = Rubus hispidus x R. setosus Rhodora 42(500): 290–293, pl. 616–618	1940
R. x\jacens Blanchard = R. hispidus x R. setosus Torreya 6(7): 147–148. 1906
R. x\parlinii L. H. Bailey = R. hispidus x R. setosus Gentes Herb. 7: 210, fig. 62. 1947
R. x\spiculosus Fernald = R. hispidus x R. setosus Rhodora 42(500): 284–287, pl. 608–609. 1940
R. x\tardatus Blanchard = R. hispidus x R. setosus Rhodora 8(95): 214–215. 1906
R. x\tholiformis Fernald = R. hispidus x R. setosus Rhodora 42(500): 283–284, pl. 606–607	1940
R. x\trifrons Blanchard = R. hispidus x R. setosus Amer. Bot. (Binghamton) 11(1): 11–13	1906
R. x\zaplutus L. H. Bailey = R. hispidus x R. setosus Gentes Herb. vii. 213 (1947)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 12:18Z]

Ordre de date:
R. x\trifrons Blanchard = R. hispidus x R. setosus Amer. Bot. (Binghamton) 11(1): 11–13	1906
R. x\jacens Blanchard = R. hispidus x R. setosus Torreya 6(7): 147–148. 1906
R. x\tardatus Blanchard = R. hispidus x R. setosus Rhodora 8(95): 214–215. 1906
R. x\adjacens Fernald = Rubus hispidus x R. setosus Rhodora 42(500): 290–293, pl. 616–618	1940
R. x\spiculosus Fernald = R. hispidus x R. setosus Rhodora 42(500): 284–287, pl. 608–609. 1940

Rubus angustifoliatus L. H. Bailey, R. gnarus L. H. Bailey, and R. wisconsinensis L. H. Bailey may be hybrids between R. pensilvanicus and R. setosus
R. x\parlinii L. H. Bailey = R. hispidus x R. setosus Gentes Herb. 7: 210, fig. 62. 1947
R. x\zaplutus L. H. Bailey = R. hispidus x R. setosus Gentes Herb. vii. 213 (1947)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 13:04Z]

R. x\jacens Blanchard = R. hispidus x R. setosus Torreya 6(7): 147–148. 1906 issued July 25, 1906
R. x\tardatus Blanchard = R. hispidus x R. setosus Rhodora 8(95): 214–215. 1906 issued 26 nov 1906
R. x\trifrons Blanchard = R. hispidus x R. setosus Amer. Bot. (Binghamton) 11(1): 11–13	1906 <query sent to Kanchi>

Rubus wisconsinensis L.H. Bailey Gentes Herbarum; Occasional Papers on the Kinds of Plants 2: 414. 1932 
Rubus gnarus L.H. Bailey Gentes Herbarum; Occasional Papers on the Kinds of Plants 5(8): 556–558, f. 253. 1944
Rubus angustifoliatus L.H. Bailey Gentes Herbarum; Occasional Papers on the Kinds of Plants 7: 233, f. 75. 1947

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-13 13:06Z]

Sue

What is the source for the mention of R. wisconsinensis in Canada? Reported in what province? It is not in Scoggan.

See information above on this hybrid taxon (the hyp. is as good as any, made by the FNA authors).

Before it is included, I need this basic info.

Thanks
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-14 12:19Z]

R. x trifrons Blanchard, Amer. Bot. (Binghamton) 11(1): 11–13. September 1906
= R. hispidus x R. setosus
Seen at: http://books.google.com/books?id=RKpLAAAAMAAJ&printsec=frontcover#v=onepage&q&f=false
Kanchi

Therefore, the earliest name for the hybrid R. hispidus x R. setosus is R. x jacens Blanchard

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-14 12:29Z]

Rubus xjacens added with syns

R.recurvans of uncertain application - not entered

R. wisconsinensis: waiting response from Sue

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-25 13:01Z]

Sue

Repeating a query :
What is the source for the mention of R. wisconsinensis in Canada? Reported in what province?

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-21 12:56Z]

Sue

I never got an answer to my last query:
What is the source for the mention of R. wisconsinensis in Canada? Reported in what province?


Thanks
Luc
