### ISSUE TITLE
Nom "perdu" en tentant de mettre en synonymie

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#394]
[Originally posted on GoogleCode (id 1753) on 2013-04-11]

Christian:

En tentant de placer en synonymie le nom Potentilla anserina subsp. egedei (taxon 8635), je l'ai placé en synonymie ... de lui-même (fausse manoeuvre). Le nom est toujours là mais je n'y ai plus accès.

Je voudrais le placer en synonymie du nom P. anserina subsp. groenlandica (taxon 8634).

Merci

Luc

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2013-04-12 13:38Z]

Donnée corrigée.
Ajout d'une validation pour empêcher un taxon de devenir son propre synonyme.
