### ISSUE TITLE
Gentiana lutea : addition à VASCAN

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#395]
[Originally posted on GoogleCode (id 1778) on 2013-05-08]

Marilyn rapporte l'addition suivante: 
Here is a new record for Canada at Alberta.

I'll get at all the English name issues soon (was on vacation).

Regards
Marilyn

http://www.anpc.ab.ca/wiki/index.php/Gentiana_lutea 

SVP: 
vernaculaire français et anglais

J'ai écrit à J. S. Pringle, auteur FNA, qui ne l'avais pas dans son manuscrit.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-05-08 18:39Z]

French names added, from Tela Botanica
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 16:20Z]

English names entered.
