### ISSUE TITLE
Scheddonardus paniculatus devient Muhlembergia paniculata

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#396]
[Originally posted on GoogleCode (id 1779) on 2013-05-09]

Marc et Marilyn:

Suite à une révision taxonomique, Scheddonardus paniculatus devient Muhlembergia paniculata

Je viens de faire le changement dans VASCAN

Il faudrait valider les vernaculaires, particulièrement le français.

Merci

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-05-09 14:58Z]

Nom français ajouté : muhlenbergie paniculée était disponible. Je suis heureux de me débarrasser de « schédonnard paniculé » comme nom accepté, mais je l'ai conservé comme synonyme car il a eu le temps d'être utilisé dans quelques rapports.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 15:49Z]

English vernacular remains the same. I added another EN name which is in use for SK.
