### ISSUE TITLE
Lindernia dubia - variétés mises en synonymie

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#397]
[Originally posted on GoogleCode (id 1782) on 2013-05-14]

Marc et Marilyn:

Le traitement FNA de Lindernia met les variétés de L. dubia en synonymie de l'espèce car la variation ne justifie pas cette séparation.

Comme il y avait de multiples noms acceptés, je les ai transférés sous l'espèce. Cependant, tous ne sont peut-être plus valables (noms de var.) et certains devraient devenir synonyme plutôt que accepté.

Pourriez vous faire le ménage, svp?

Marilyn: the accepted name for the species is cited in FNA. I put the ref. there since there was none for that name. You may wish to choose another one.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 15:47Z]

Many thanks for the document. I've adjusted names and also added NY Flora Atlas as a reference. 
I believe L. attenuata Muhl. is also a synonym?

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-06-07 20:03Z]

Ménage fait pour les noms français.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-07 20:31Z]

Why would I add L. attenuata? I do not see it listed anywhere. Has it been used in Canada?
Luc
