### ISSUE TITLE
New species: Thesium arvense

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#398]
[Originally posted on GoogleCode (id 1784) on 2013-05-31]

Thesium arvense has just been added to the flora of Alberta and it is now in VASCAN.
SEe: http://www.anpc.ab.ca/wiki/index.php/Thesium_arvense

No vernacular is suggested in English.

I need vernaculars in French and English

asap please

Marilyn, I note that the number of issues concerning English vernaculars increases steadily. The danger is to let it accumulate too much. is there any way you can see to facilitate the process or any means of getting help?

Best
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-02 15:44Z]

Only English vernacular that seems to be in usage is 'thesium', which is entered.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-06-07 20:14Z]

Was "done" but still needed a French name...

Now it is really done.

Marc
