### ISSUE TITLE
Rubus phoenicolasius ajouté

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#399]
[Originally posted on GoogleCode (id 1786) on 2013-06-13]

Rubus phoenicolasius, int, ajouté car mentionné ds Scoggan (avec réserves), eFlora of BC et FNA ms. Cependant, plus. spécimens se trouvent à UBC

ce taxon asiatique d'origine avait été négligé par nous

Besoin de noms vernaculaires.

Marilyn: FNA ms has: wineberry
eFlora BC has: Japanese wineberry; Wine raspberry

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-06-13 18:20Z]

J'ai trouvé un nom français dans INPN 2005 - framboisier rouge

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-17 19:11Z]

completed
