### ISSUE TITLE
Hybrids with at least one synonym as parent

### ISSUE THREAD

**Issue by cgendreau** [Canadensys/vascan-data#4]
Originally posted on GoogleCode (id 2367) on 2014-12-19
Solidago ×asperula Desfontaines
http://data.canadensys.net/vascan/taxon/3502

Solidago ×erskinei B. Boivin
http://data.canadensys.net/vascan/taxon/3506

Carex bigelowii subsp. bigelowii × Carex rariflora
http://data.canadensys.net/vascan/taxon/4778

Carex foenea × Carex tenera var. tenera
http://data.canadensys.net/vascan/taxon/4871

Carex ×firmior (Norman) Holmberg
http://data.canadensys.net/vascan/taxon/5156

Carex ×soerensenii Lepage
http://data.canadensys.net/vascan/taxon/5190

Carex ×zahnii Kneucker
http://data.canadensys.net/vascan/taxon/5201

Dryas ×sundermannii Kellerer ex Sundermann
http://data.canadensys.net/vascan/taxon/8744

Verbena ×rydbergii Moldenke
http://data.canadensys.net/vascan/taxon/9471

Solidago sempervirens subsp. sempervirens × Solidago uliginosa
http://data.canadensys.net/vascan/taxon/26576

Verbena ×engelmannii Moldenke
http://data.canadensys.net/vascan/taxon/9469

Merci

**Comment by brouille** [comment]
cas corrigés: 
Solidago ×asperula 
Solidago ×erskinei
Carex bigelowii subsp. bigelowii × Carex rariflora
Carex foenea × Carex tenera var. tenera
Carex ×firmior
Carex ×soerensenii
Carex ×zahnii
Dryas ×sundermannii
Verbena ×rydbergii
Solidago sempervirens subsp. sempervirens × Solidago uliginosa
Verbena ×engelmannii
