### ISSUE TITLE
Lechea pulchella   Rafinesque var. moniliformis   (E. P. Bicknell) Mohlenbrock

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#40]
[Originally posted on GoogleCode (id 1586) on 2012-11-16]

Salut

Variété non précisée dans VASCAN.
Une seule selon FNAms pour le Canada.
Synonyme selon FNAms: Lechea moniliformis E. P. Bickness; L. leggettii Britton &amp; Hollick var. moniliformis (E. P. Bicknell) Hodgdon

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-12-14 19:43Z]

Oldham avait dit var. pulchella, ms FNa dit moniliformis - à éclaircir avec Mike
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-01-28 18:44Z]

Le nom de var. est déjà ajouté et corrigé sur la version à  compiler prochainement, après consultation de Mike
