### ISSUE TITLE
http://data.canadensys.net/vascan/taxon/26883

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#401]
[Originally posted on GoogleCode (id 1792) on 2013-06-18]

Kopsiopsis hookeri: le ms FNA (ci-attaché) vient d'être envoyé pour révision régionale

Marilyn: the ms provides a source for two of the vernaculars you have as synonyms

Marc: le nom vernaculaire accepté boschniakie de Hooker, cuisiné par Alain Cuerrier, me semble inapproprié, d'autant que c'est un nom créé. L'espèce a parfois été traitée dans ce genre (que nous avons par ailleurs dans la flore), mais selon les données phylogénétiques, le genre est distinct. Conviendrait-il de revoir ce nom?

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-06-18 21:01Z]

Je pense que nous pouvons conserver le nom français actuel « boschniakie de Hooker" pour le Kopsiopsis hookeri. Le nom "boschniakie de Russie" était effectivement une création d'Alain Cuerrier, mais le générique "boschniakie" existait déjà dans certains dictionnaires et est employé dans certains textes de pharmacopée.

Comme les deux genres sont apparentés et que leurs espèces respectives présentes dans l'Ouest canadien ont un aspect semblable, je pense qu'il vaut mieux éviter d'introduire le mot "kopsiopsis" comme nom français, d'autant plus qu'il est difficile à prononcer.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-24 16:49Z]

English vernaculars reviewed with sources added/adjusted. Is this issue finished now?

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-06-26 20:41Z]

As far as I am concerned, this can be considered « done ».
