### ISSUE TITLE
Digitalis EN varnaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#402]
[Originally posted on GoogleCode (id 1794) on 2013-06-19]

Marilyn:

Attached is the FNA treatment, where EN vernaculars are mentioned for the Digitalis spp. that currently do not have sources. For D. purpurea, could we use the same source as for the Fr vernacular (Darbyshire et al.?)

Lu

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-24 16:52Z]

finished review of English vernaculars with sources. Greatly appreciate the documents also, as the descriptions help (especially if a vernacular isn't provided).
