### ISSUE TITLE
Callitropsis - EN vernacular

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#403]
[Originally posted on GoogleCode (id 1795) on 2013-06-19]

Marilyn: I got this email from Stéphane Bailleul at the Jardin botanique. His email is Stéphane Bailleul &lt;stephane_bailleul@ville.montreal.qc.ca&gt; (if ever you want to respond, since he did not put it on our Google-Code)

&quot;Luc : Je vais mettre à Callitropsis nootkatensis nos accessions de Xanthocyparis dans BGBASE. J'espère que cette taxonomie est maintenant résolue ! J'ai remarqué dans Vascan les noms vernaculaires cyprès jaune en français et yellow-cedar (!?) en anglais. Callitropsis étant plus allié aux cyprès ne serait-il pas plus logique de recommander plutôt Yellow-cypress comme on le fait en français. Je pense privilégier yellow-cypress dans BGBase.&quot;

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-23 11:34Z]

Yes I received a direct email and I replied (with my new gmail address) that I'll be reviewing this. I agree with the change however would like to review what still might be in use in Canada, also with some BC foresters on their thoughts.
Many thanks

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-24 16:48Z]

I agree with the change to yellow-cypress as the accepted name for VASCAN, although still lots of other names in wide use. I'll email Stéphane also. Great to have this input!
