### ISSUE TITLE
Leucospora multifida - English vernacular

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#405]
[Originally posted on GoogleCode (id 1807) on 2013-07-02]

Marilyn

Attached is the FNA ms of Leucospora. In it, the vernacular is provided as &quot;narrow-leaf paleseed&quot;

You have this name as one of the synonymous vernacular but as &quot;narrowleaved&quot; - and without source.

I let you mull over this. You decide how to write this one.

Marc: no French needed in the FNA ms. For information.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-07-23 20:51Z]

Many thanks (yes the Canadian usage is -leaved)
