### ISSUE TITLE
Misopates orontium vernaculars

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#406]
[Originally posted on GoogleCode (id 1808) on 2013-07-02]

Marilyn:

attached here is the FNA ms of Misopates. It provides a source for two of the syn names you have in VASCAN, one of which without source.

Please note that the taxon is now a subsp., fide FNA ms.

Marc: pour info. - j'ai ajouté le nom français choisi dans le ms FNA

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-07-23 18:19Z]

Many thanks
