### ISSUE TITLE
Limosella aquatica vs acaulis

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#408]
[Originally posted on GoogleCode (id 1810) on 2013-07-02]

Marilyn: 

FNA does not segregate the two taxa mentioned above (see attached text). I am waiting a bit on this one. The author may be right but explanation is minimal.

However, you suggested southern mudwort for L. australis, while this name is systematically applied to L. acaulis in web sites from the area where the taxon is reported. Using this name for australis may cause confusion.

Marc: pour information seulement.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-07-23 17:59Z]

Reviewed all the Limosella species in Canada. Interesting that L. acaulis would be now included with L. australis (please let me know on further developments).
I've checked quite a bit... 'southern' is in use for both species currently. L. acaulis if remaining separate, is known specifically as 'Owyhee mudwort'. If considered together as one species, then 'southern' would be apply as the one-taxon name.
