### ISSUE TITLE
Agalinis révisé suivant FNA

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#410]
[Originally posted on GoogleCode (id 1818) on 2013-07-24]

Marc et Marilyn:

Le manuscrit FNA de Agalinis m'est enfin parvenu (ci-attaché) et cela a entraîné des changements significatifs au niveau taxonomique. Notamment, voir A. purpurea (incluant A. paupercula et ses vars.) et A. tenuifolia (plus de vars distinctes).

J'ai enlevé les vernaculaires redondants, mais il faut faire le ménage.

En particulier, le vernaculaire français de purpurea var. parviflora, hérité de paupercula, paraît inapproprié. Le nom le plus approprié, cependant, était déjà utilisé avec la var. parviflora de tenuifolia (plus reconnue). Je te laisses juger, Marc. Gérardie me bâdre toujours, quoique je comprenne ton raisonnement. Il existe bien, cependant, un Gerardia valide dans une flore étrangère...

Marilyn: you may find in the document a source for several names.

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-07-24 17:18Z]

J'ai vérifié tous les noms français et en ai éliminé quelques-uns, des créations de Favreau ou Cuerrier, qui s'appliquaient uniquement à des taxons infraspécifiques qui ne sont plus reconnus.

Un des noms éliminés est "gérardie à petits fleurs" qui était appliqué à l'Agalinis tenuifolia var. parviflora.

Il y a évidemment risque de confusion avec l'A. purpurea var. parviflora. Pour cette espèce, j'ai finalement conservé le nom « gérardie appauvrie », parce que c'est le nom employé dans la Flore laurentienne et parce que j'hésite à ressusciter si vite le nom « gérardie à petites fleurs » pour un taxon différent.

En ce qui concerne le nom générique "gérardie", c'est vraiment celui qui est employé dans tous les ouvrages en français consultés. S'il existe vraiment un genre Gerardia valide quelque part dans le monde, ce n'est pas en Europe ni en Amérique du Nord, ni même en Chine ou en Australie, et je ne crois pas qu'il y ait risque de confusion. Le passage suivant (1996) est tiré d'une flore web du Michigan : « The genus Gerardia, to which Michigan’s Agalinis species were referred prior to 1959, was found to be an illegitimate generic name for any taxon placed under its concept and thus can only be used as a common name (Voss 1996). »

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-07-28 13:34Z]

finished the review of the English vernaculars for Agalinis and Aureolaria.
Marc - just to let you know there are 3 currently-accepted French vernaculars for Agalinis tenuifolia.
