### ISSUE TITLE
Viola vallicola http://data.canadensys.net/vascan/taxon/9529

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#411]
[Originally posted on GoogleCode (id 1819) on 2013-07-24]

Je viens de modifier la taxonomie de Viola vallicola pour diviser l'espèce en deux variétés, var. vallicola et var. major.

Les noms vernaculaires ont été transférés à la var. vallicola. Il n'y a pas de nom pour var. major.

Vérifier et ajouter svp.

Merci
Luc

PS: je n'ai pas la dernière version, très remaniée, du traitement FNA de Viola

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-07-24 20:50Z]

Nom vernaculaire français ajouté. La variété figurait dans une version préhistorique de VasCan, et Alain Cuerrier avait proposé "grande violette". Je constate cependant que cette variété n'est grande que par rapport aux autres variétés de l'espèce, et non par rapport aux autres espèces de violettes. J'ai donc proposé "grande violette vallicole" comme nom français.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-07-27 10:53Z]

English vernaculars reviewed for the species and 2 varieties. When the Viola treatment is available, it would be great to see as lots of other EN names need some work! I'll sort them all out then.
