### ISSUE TITLE
Kolkwitzia amabilis : Ont.

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#412]
[Originally posted on GoogleCode (id 1868) on 2013-09-24]

Kolkwitzia amabilis a été ajouté à VASCAN (Ont.)
Il manque les vernaculaires
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-09-24 20:50Z]

J'ai inscrit le seul nom français figurant dans nos sources habituelles, « buisson de beauté ».

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-09-24 20:51Z]

J'ai inscrit le seul nom français figurant dans nos sources habituelles, « buisson de beauté ». Je crois que le nom « kolkwitzia » est davantage employé par les jardiniers, mais j'aurais besoin d'une source pour ce nom.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-09-25 12:57Z]

Je crois que kolkwitzia est utilisé en anglais - je ne l'ai pas trouvé en français sur Google
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-10-02 21:01Z]

Merci Luc. J'ai cependant trouvé de nombreuses occurrences de "le kolkwitzia", donc en français, sur Google, ainsi que le nom "kolkwitzia ravissant", qui satisfait à nos besoins, dans un bulletin du jardin botanique de l'université Laval (http://www.jardin.ulaval.ca/fileadmin/fichiers/fichiersSOCIETEAMIS/pdf/Versicolore___7.pdf). Je pense que nous pouvons accepter ce nom et ainsi éviter d'en créer un inutilement.

J'ai fait les corrections requises dans la base.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 00:31Z]

English name added
