### ISSUE TITLE
Leptochloa fusca = Diplachne fusca

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#413]
[Originally posted on GoogleCode (id 1871) on 2013-09-26]

Marc

Je viens d'effectuer le transfert de Leptochloa fusca subp. fascicularis au genre Diplachne (seule espèce).

Tu avais imaginé un vernaculaire français. Comme c'est récent, peux tu déterminer si tu veux le modifier ou non?

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-10-09 20:51Z]

Bonjour Luc,

C'est vrai que j'ai créé ce nom il y a plusieurs années et que j'en aurais créé un différent si l'espèce avait alors été rangée dans le genre Diplachne.

Cependant, au moins deux sites canadiens répertorient actuellement l'espèce sous ce nom français, alors j'hésite à créer un nouveau synonyme. Je pense donc que nous pouvons conserver le nom. Ça évitera un va et vient inutile si jamais l'espèce est un jour ramenée sous Leptochloe.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-09 20:55Z]

Aucune chance que le retour se fasse car les genres ne sont pas adjacents
dans les phylog�nies.

Un peu malheureux.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-10-10 13:08Z]

Tu as bien fait de revenir à la charge. Tes arguments m'ont convaincu.
J'ai gardé le nom « leptochloé fasciculée » comme synonyme, en citant comme source un des sites qui l'a adopté, et j'ai créé des noms avec « diplachné » pour l'espèce et la sous-espèce.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-10 18:16Z]

bonne solution
merci
Luc
