### ISSUE TITLE
Référence répétée ds VASCAN

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#414]
[Originally posted on GoogleCode (id 1873) on 2013-09-27]

Christian:

En entrant une référence, je me suis rendu compte qu'une réf. est répétée dans la base de données:
Cody &amp; Britton, 1989
réf. # 72 et # 114

Avant d'éliminer la réf. 114, il faut s'assurer que toute réf. à celle-ci (114) comme source dans la bd soit changée pour 72.

Merci
Luc

**Comment by cgendreau** [comment]
J'ai changé la référence du taxon 5405 et des noms vernaculaires 1645 et 27608.
Aussi la référence pour la distribution des taxons 5405(QC), 5426(NL_L) et 5438(NS et QC).

**Comment by cgendreau** [comment]
Est-ce qu'il y a une raison pourquoi la référence # 114 indique 452 pages et la référence # 72, 430 pages?

**Comment by brouille** [comment]
Une réf. donnait le nombre de pages du document français tout en donnant la réf. française. Le bon nombre est celui du 72, 430 pages.
Tous les vernaculaires sont anglais, donc il n'y a aucun problème a éliminer la réf. 114, ce que je fais immédiatement.
Luc

**Comment by brouille** [comment]
Apparemment, je ne peux éliminer de réf.

Peux tu l'enlever svp.

Merci, Luc

**Comment by cgendreau** [comment]
Référence 114 supprimée
