### ISSUE TITLE
Citrullus lanatus in Ont.

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#415]
[Originally posted on GoogleCode (id 1874) on 2013-09-27]

Marc et Marylin:

Citrullus lanatus subsp lanatus est connu comme éphémère en Ont. selon Oldham. Il faut des vernaculaires en et fr.

Merci
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 00:31Z]

English names added

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-04 15:30Z]

will list this one as finished
