### ISSUE TITLE
Huperzia porophila  ajouté pour Ont.

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#416]
[Originally posted on GoogleCode (id 1875) on 2013-09-30]

Marc et Marilyn:

Huperzia porophila a été ajouté pour l'Ontario.

Il lui manque les vernaculaires. Aucun vernaculaire anglais ds FNA 2.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-11-14 21:50Z]

J'ai importé le nom « lycopode porophile » que nous avions adopté pour le H. Xprotoporophila à une époque où nous considérions les deux taxons comme synonymes.

Voici ce qui était alors noté sous H. Xprotoporophila = H. porophila : « syn de lucidulum in Scoggan; Ont ds Morton citing Soper et al 89 ms pas FNA2; confirmed by Oldham (email pc 2002, det. Preston - Thunder Bay area)»

Cela soulève des doutes quant à la présence réelle de deux taxons distincts en Ontario. Je pense qu'il faudrait réévaluer la situation du H. Xprotoporophila dans cette province.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 00:32Z]

English names added and proposed names for the hybrid added.
