### ISSUE TITLE
Nouveaux taxons ajoutés dans Amaranthus

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#417]
[Originally posted on GoogleCode (id 1877) on 2013-10-01]

Marc et Marilyn:

À la suggestion de Mike Oldham, j'ai ajouté les taxons suivants à VASCAN, qui requièrent des vernaculaires:

Amaranthus hybridus subsp. quitensis [je me demande si on doit s'en soucier étant donné que je l'exclut - à vous de déterminer si cela est valable]

A. caudatus

A. hypochondriacus

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-10-04 21:05Z]

Noms français ajoutés, tous disponibles dans TelaBotanica.

Dans le cas d'une espèce exclue de la flore canadienne, comme l'Amarantus hybridus subsp. quitensis, il n'est pas utile de créer un nom français s'il n'en existe aucun, mais on peut répertorier les noms français déjà existants. C'est souvent le cas d'espèces originaires d'Europe.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-09 13:22Z]

Marc

Je suis d'accord pour les exclusions. Jusqu'au jour où l'une ou l'autre réapparaît
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-21 17:54Z]

English vernaculars added
