### ISSUE TITLE
Taxon ajouté: Amaranthus powellii subsp. bouchonii

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#418]
[Originally posted on GoogleCode (id 1879) on 2013-10-02]

Il faut ajouter les vernaculaires svp

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-10-04 20:48Z]

Nom français de TelaBotanica ajouté.
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-21 17:17Z]

English name added
