### ISSUE TITLE
Sorbus intermedia in Ont.

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#419]
[Originally posted on GoogleCode (id 1881) on 2013-10-09]

Mike Oldham added Sorbus intermedia as introduced in Ont.

Vernacular are required.

The FNA ms has Swedish whitebeam as vernacular.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-11-15 21:42Z]

Noms français ajoutés!
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-21 16:56Z]

English name added
