### ISSUE TITLE
nom français de Silene flos-cuculi (Linnaeus) Clairville subsp. flos-cuculi

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#42]
[Originally posted on GoogleCode (id 1606) on 2012-12-16]

Tela-Botanica recommande l'utilisation de silène fleur-de-coucou.
J'avoue que je suis bien d'accord.

lychnide fleur-de-coucou Darbyshire et al., 2000 
silène fleur-de-coucou Centre du réseau suisse de floristique, 2010 

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-12-19 13:37Z]

Marc

Svp répondre à cette suggestion de Fred.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2012-12-20 22:12Z]

Bonjour Fred et Luc.

Il n'est pas nécessaire de toujours suivre TelaBotanica, car on se retrouverait avec des épicéas et d'autres noms qui ne passent pas de ce côté de l'Atlantique. Cependant, dans ce cas-ci, on pourrait sans doute utiliser le générique "silène" pour tous les Silene s.l. qui sont encore appelés "lychnide" dans la base, même si la plupart des ouvrages canadiens, y compris ceux de Fleurbec, les appellent encore des lychnides. Cependant, avant de commencer ce changement, je devrai faire des vérifications pour ne pas créer des homonymes qui compliqueraient la situation. Je dois reporter ce travail à plus tard, en janvier sans doute.

Joyeux Noël à tous.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-01-14 22:08Z]

Bonjour Fred,

J'ai passé en revue tous les Silene, et l'utilisation du générique "lychnide" pour 4 des espèces n'était fondée sur aucune caractéristique particulière, et des noms acceptables commençant par "silène" étaient déjà disponibles pour 3 de ces espèces. Il m'a fallu créer un nouveau nom pour le Silene chalcedonica, mais je ne pense pas que ça pose problème, car les noms antérieurs étaient régionaux et souvent européens, et au moins un était ambigu.

Donc, tous les Silene sont désormais des silènes.

Merci pour ta suggestion, qui simplifie grandement la situation.
