### ISSUE TITLE
Scilla luciliae in Ont.

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#420]
[Originally posted on GoogleCode (id 1882) on 2013-10-09]

Mike oldham added Scilla luciliae to the flora of Ont. and Canada

Vernacular names are needed. Not in FNA.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-11-15 21:46Z]

French names added.
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-20 21:39Z]

English names added
