### ISSUE TITLE
Scilla forbesii in Ont.

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#421]
[Originally posted on GoogleCode (id 1883) on 2013-10-09]

Mike Oldham reported this sp. as new to Ont. and Canada.

Vernaculars are required

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-11-15 21:57Z]

French name added.
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-20 21:39Z]

English names added
