### ISSUE TITLE
Actinidia arguta in Ont.

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#422]
[Originally posted on GoogleCode (id 1884) on 2013-10-09]

Mike Oldham is reporting Actinidia arguta in Ont. - a new report of fam., genus and sp. for Canada and Ont.

Vernaculars are required. 
FNA has EN vernacular: Tara vine, Hardy kiwi

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-11-20 21:41Z]

French names added.
Marilyn, you may want to mention the 2 English names given in Macura, 1979 :
bower actinidia
tara vine

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-20 22:45Z]

English names entered
