### ISSUE TITLE
Poa bulbosa subsp. bulbosa

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#423]
[Originally posted on GoogleCode (id 1885) on 2013-10-09]

Mike Oldham ajoute cette subsp. bulbosa à la flore du Canada et Ont.

IL manque un vernaculaire français à la subsp. et à l'espèce (même).

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-10-10 20:39Z]

OK, noms français ajoutés et corrigés au besoin.

Marc
