### ISSUE TITLE
Puschkinia scilloides in Ont.

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#424]
[Originally posted on GoogleCode (id 1886) on 2013-10-09]

Mike Oldham has added this genus and sp. to Canada and Ont.

It was not in FNA.

Vernaculars are needed.

Thanks
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-10-10 20:45Z]

Nom français ajouté.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-20 22:18Z]

English name entered
