### ISSUE TITLE
Stratiotes aloides

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#425]
[Originally posted on GoogleCode (id 1887) on 2013-10-09]

Oldham is reporting this species (Hydrocharitaceae) as new to Canada and Ont. (in fact, apparently new to NA since not in FNA)

Vernaculars please.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-10-10 20:52Z]

Noms français ajoutés
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-20 22:16Z]

English vernacular added
