### ISSUE TITLE
Juncus biflorus distinguished from marginatus

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#426]
[Originally posted on GoogleCode (id 1888) on 2013-10-09]

Recent treatments distinguished Juncus biflorus from J. marginatus. This taxon is reported by Oldham for Ont.

Vernaculars are needed.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-10-10 20:58Z]

Nom français ajouté (déjà existant).

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-20 23:01Z]

English name added
