### ISSUE TITLE
Lentibulariaceae names

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#428]
[Originally posted on GoogleCode (id 1891) on 2013-10-16]

J’utilise VASCAN ce matin et je remarque que la page pour Utricularia vulgaris subsp. macrorhiza (Leconte ex Torrey) Clausen &lt;http://data.canadensys.net/vascan/taxon/6505&gt;  n’a pas le nom vernaculaire anglais. Même chose pour Pinguicula vulgaris Linnaeus subsp. vulgaris &lt;http://data.canadensys.net/vascan/taxon/6499&gt; , quoique le vernaculaire anglais est sur la page de l’espèce dans ce cas.
Nathalie Djan-Chekar

Marilyn:

Could you add these when you have time, please?

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-24 01:03Z]

finished a review of Lentibulariaceae English names
