### ISSUE TITLE
Salix matsudana en Ont: vernaculaires requis

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#429]
[Originally posted on GoogleCode (id 1906) on 2013-10-18]

Marc et Marilyn:

M. Oldham a ajouté Salix matsudana à l'Ont. (et au CAnada, Amérique du Nord)
C'est une espèce fréquemment cultivée pour la biomasse, etc.

Pas ds FNA

Noms vernaculaires requis

merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-11-20 21:55Z]

J'ai inscrit le nom français.

Selon ma source (Burte, 1992), l'espèce aurait déjà été appelée 
Salix babylonica var. pekinensis Henry
mais je ne sais pas s'il vaut la peine de mentionner ce synonyme.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 17:51Z]

English names added for species concept and cultivar concept
