### ISSUE TITLE
Pistia stratiotes: vernaculaires requis

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#430]
[Originally posted on GoogleCode (id 1907) on 2013-10-18]

Pistia stratiotes a été ajouté à la flore du Canada/Ont.

Des vernaculaires sont requis.

English: I added the FNA vernacular name as acc with source, which is iphenated. However, Abedayo et al. 2011, who reported it for Ont., do not iphenate. You can accept another spelling of the name (non iphenated) with a different source, reducing this one to syn.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-11-20 22:06Z]

Nom français ajouté.
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 18:33Z]

Many thanks Luc. I used the non-hypenated form of the name for the accepted name for this species. The majority of references I checked used this format.
