### ISSUE TITLE
Nouveaux taxons de Draba pour le Canada

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#431]
[Originally posted on GoogleCode (id 2026) on 2014-01-10]

Marc et Marilyn:

De nouveaux taxons viennent d'être publiés pour le Canada par Al-Shehbaz et Mulligan dans le genre Draba (document attaché).

Des noms vernaculaires sont nécessaires pour les taxons suivants dans VASCAN; cela ne devrait pas trop poser de problème car plusieurs sont nommés pour des botanistes canadiens:
Draba bennettii
Draba caswellii
Draba cayouettei
Draba franktonii
Draba puvirnituqii
Draba taylori
Draba thompsonii
Draba mulliganii

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-23 19:19Z]

Many thanks for the paper, interesting read. English names added.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-02-27 17:28Z]

Noms français ajoutés.
Curieusement, je n'avais reçu aucun courriel, et je suis tombé par hasard sur ce forum Google.

Marc
