### ISSUE TITLE
Vernacular names in Papaver

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#432]
[Originally posted on GoogleCode (id 2039) on 2014-01-16]

MArc et Marilyn:

J'ai fait certaines corrections à Papaver sect. Meconella après révision de la taxonomie.

Des vernaculaires manquent pour Papaver hultenii, 

Vernaculaires EN manquent pour P. lapponicum subsp. occidentale (je ne sais si le Fr pour ce taxon est appropiré Marc), P. labradoricum, P. cornwallisensis

Les vernaculaires pour P. croceum sont à revoir: ce taxon est plutôt appelé Siberian poppy dans le commerce. On avait erronément placé ce taxon en AN sous P. nudicaule, qui est sans doute le Icelandic poppy. Voir Panarctic Flora.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-01-22 18:31Z]

Pour le Papaver lapponicum subsp. occidentale, j'ai choisi le nom français "pavot de Porsild" fondé sur le synonyme P. lapponicum subsp. porsildii, parce que le nom "pavot occidental" désigne déjà un autre taxon en Europe (P. alpinum var. occidentale Markgr.).

En ce qui concerne le P. nudicaulis et le P. croceum, TelaBotanica ainsi que l'INPN assimilent le P. nudicaulis hort. (P. nudicaulis auct. non Linné) au P. croceum et appellent cette espèce "pavot d'Islande", nom qui est d'ailleurs couramment employé par les jardiniers, même si l'espèce ne semble pas indigène d'Islande. TelaBotanica et l'INPN placent tous deux le P. nudicaulis Linné en synonymie du P. alpinum, et je ne crois pas que cette espèce ait été signalée en Amérique du Nord. Je me demande donc où se situe réellement le P. nudicaulis var. americanum. Pourrais-tu me sur quel article tu te fondes pour établir la validité de ce taxon. Le P. nudicaulis L. n'est pas traité dans Panarctic flora. J'ai provisoirement appelé le P. nudicaulis « pavot multicaule » au niveau de l'espèce.

Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-23 15:20Z]

Solstad, 2009 une thèse PhD que nous avons à MT, est la source de la distinction de croceum - il semble qu'il y ait eu grande confusion entre nudicaulis et croceum etc. et cette confusion est réflétée dans les sources françaises

Je vais voir si les articles publiés de Solstad (la thèse est une compilation d'articles) sont accessibles et lequel traite croceum - il y avait des infos sur le nom vernaculaire anglais Islande vs Sibérien

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-24 23:30Z]

reviewed all of the English names with changes. Still thinking about Papaver radicatum subsp. radicatum might be better not to have the name specifically as 'arctic poppy'... when it is 'North Atlantic' or 'Icelandic-Scandinavian' only, according to PanArctic Flora.
Marilyn

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 19:28Z]

Is this issue closed?
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-02-04 15:27Z]

yes
