### ISSUE TITLE
Vernaculaires pour Potentilla hookeriana

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#433]
[Originally posted on GoogleCode (id 2126) on 2014-02-11]

Le ms FNA sépare Potentilla rubricaulis et P. hookeriana.

J'ai transféré un vernaculaire EN de l'un vers l'autre. Svp valider.

Par ailleurs, le taxon est sans vernaculaire FR.

Vérifier aussi les vernaculaires de rubricaulis, svp

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-02-14 21:15Z]

Noms français corrigés.
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-03-02 17:06Z]

English vernaculars reviewed
