### ISSUE TITLE
Minuartia redéfini

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#434]
[Originally posted on GoogleCode (id 2150) on 2014-03-13]

Marc et Marilyn:

Dillenberger &amp; Kadereit (2014, Taxon 63:64-88) ont redéfini le genre Minuartia après étude de phylogénie moléculaire. Il reste un résidu d'espèces dans VASCAN laissées sous Minuartia pcq les auteurs n'avaient pas fait les combinaisons dans Cherleria pour les taxons impliqués.

Autrement, toutes les espèces ont été transférées aux genres suivants:
Mononeuria
Pseudocherleria
Sabulina

Plusieurs noms français ont en fait été créés de toute pièce dans Minuartia. Il faut valider et possiblement considérer changer.

Please validate English vernaculars, though I do not believe names need to change since they had more common names.

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-04-04 20:36Z]

Noms français corrigés.
J'ai conservé le générique « minuartie » pour les genres les plus étroitement apparentés au genre Minuartia (Mononeuria et Pseudocherleria)
J'ai employé le bon vieux nom « sabline » pour les Sabulina, à cause de la parenté des noms, même si les Arenaria sont relativement éloignés au sein de la famille.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-05-13 20:51Z]

I reviewed all the English vernaculars for Minuartia, Mononeuria, Pseudocherleria and Sabulina. Just a couple of changes for clarity and accuracy of source.
