### ISSUE TITLE
New var. for Canada: Salix exigua var. hindsiana

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#435]
[Originally posted on GoogleCode (id 2183) on 2014-04-25]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

<b>What data are incorrect or missing?</b>

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-04-25 17:46Z]

Sorry, this went off before I wall able to finish even the title

New var. for Canada: Salix exigua var. hindsiana
source: http://www.efloras.org/florataxon.aspx?flora_id=1&taxon_id=242445712

French vernacular required
EN vern: FNA suggests Hind’s willow

Thanks
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-05-06 16:47Z]

Luc & Marilyn:
Salix hindsiana was named « after Richard Brindsley Hinds, 
surgeon in the British royal Navy and naturalist on HMS Sulpher 1836-1842. » (http://corelectronics.com/DERUFF/Salix%20exigua.htm), so the English name, if coined from the scientific epithet, should be « Hinds' willow », not « Hind's willow » (error in FNA).

Nom français : saule de Hinds

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-05-12 23:06Z]

English name entered. Thanks for noticing the FNA error Marc
