### ISSUE TITLE
Espèces NA de Cheilanthes transférées à Myriopteris

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#436]
[Originally posted on GoogleCode (id 2207) on 2014-05-27]

Grusz &amp; Windham 2013 (attaché) ont récemment transféré les spp. nord-américaines de Cheilanthes (2 au Canada seulement) au genre ressuscité Myriopteris (Pteridaceae). Cheilanthes n'existe plus sur le continent et au Canada. Cheilanthes est sud-américain et ancien monde et donc existe toujours dans un sens plus étroit.

Pourriez vous vérifier les noms des deux espèces (M. gracillima et M. gracilis) pour les vernaculaires attribués antérieurement sous Cheilanthes? En particulier, la seconde sp. est l'ancien Cheilanthes feei. Le changement d'épithète est dû à la nomenclature (voir article joint).

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-06-25 20:55Z]

J'ai créé des noms fondés sur un nouveau générique « myrioptère », mais j'ai conservé les noms en « chéilanthe » comme synonymes parce qu'ils sont déjà en usage.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-06-26 14:07Z]

MErci Marc.

MArilyn, please verify. Thanks.
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-07-17 17:30Z]

checked the English names, they are still suitable. Thanks for the article
