### ISSUE TITLE
Phalaris arundinaceae : variétés

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#437]
[Originally posted on GoogleCode (id 2235) on 2014-07-09]

http://data.canadensys.net/vascan/taxon/7818

Phalaris arundinacea: suivant l'article de Catling et al. 2014 (ci-attaché), j'ai divisé ce taxon en 2 variétés. Il existe de nombreux noms pour la var. typique, mais aucun pour la var. picta.

svp ajouter le vernaculaires

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-07-09 17:45Z]

Noms français ajoutés.

Le nom « alpiste .panaché » est parfois employé, mais il est déjà utilisé par TelaBotanica pour la subsp. oeleri

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-07-17 18:06Z]

English names reviewed/added.
