### ISSUE TITLE
Nouveaux Sedum au Canada, en remplacement de S. rupestre

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#438]
[Originally posted on GoogleCode (id 2345) on 2014-11-03]

Marc et Marilyn:

Dans un article récent, Gallo et Zika 2014 ont montré que le S. rupestre en Amérique du Nord est en fait deux taxons: Sedum forsterianum (rapporté ds eFlora of BC) et S. thartii. Il manque les vernaculaires anglais et français pour les deux.

S. rupestre est maintenant exclu du Canada.

Merci
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-11-05 17:50Z]

Is it possible to attach the article please?

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-11-06 22:07Z]

Many thanks for the article, English vernaculars completed.
Would ['t Hart's stonecrop] be suitable (named after 't Hart, as it is written for the person's name) for Sedum thartii, or does this become as [Thart's] as how the Oregon Flora has it written?

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-11-12 21:37Z]

Marilyn,

I am unfamiliar with the use of 't in certain names. It seems similar to our « de » and your Mc, Mac and O' It does seem awkward, but « 't Hart » is certainly better than « Thart ». I would go for either « 't Hart » or just « Hart ». In bibliographies, the name is often given as « Hart, H. 't » or « Hart, Henk 't ».

No problem in French : there is already a name used in France : orpin dressé (TelaBotanica).

French names completed for the 2 species.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-11-12 21:39Z]

It is best to use t�Hart.
This is what was done in FNA bibliographies.

Luc

Le 2014-11-12 16:37, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-11-13 13:54Z]

Je viens de me rendre compte que le nom « orpin dressé » utilisé par TelaBotanica pour le S. thartii  est fondé sur une acceptation du Sedum rupestre subsp. erectum 't Hart comme synonyme. Or, vérification faite (http://www.crassulaceae.ch/de/artikel?akID=157&aaID=2&aiID=T&aID=290), cette synonymie est inexacte, le S. rupestre subsp. erectum étant seulement une des deux espèces parentes du S. thartii, si celui-ci est considéré comme un allopolyploïde. J'ai donc finalement préféré « orpin de 't Hart » comme nom français accepté de l'espèce.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-11-13 14:34Z]

Many thanks for your input, this is greatly appreciated! I removed Oregon's name of 'Thart' as it's best not to have this inappropriate name available for possible usage.
