### ISSUE TITLE
RÉINSTITUER UN SYNONYME EFFACÉ ERRONÉMENT

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#439]
[Originally posted on GoogleCode (id 2473) on 2015-02-03]

Christian:

Pourrais tu ré-instituer le nom suivant à partir du backup de la base de données de VASCAN:

http://data.canadensys.net/vascan/taxon/24210
Agrostis glauca

synonyme de 9629 Calamagrostis cinnoides auct. non W.P.C. Barton nom. illeg.

[note que les autorités ont changé dans ce dernier et je ne veux pas reconstituer les anciennes)

MErci
Luc

**Comment by cgendreau** [comment]
[Originally posted on GoogleCode on 2015-02-03 21:34Z]

Il devrait être comme avant mais sans la référence.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-02-03 21:37Z]

Tout est OK

Je ferme le point.
Luc
