### ISSUE TITLE
Silene coronaria

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#44]
[Originally posted on GoogleCode (id 1617) on 2013-01-23]

Bonjour Marc

Tela-Botanica préfère le nom vernaculaire Silène coronaire que lychnide coronaire.

Ne devrait-on pas faire le &quot;switch&quot; de tous nos lychnides vers silène....

Frédéric

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-01-28 18:49Z]

Marc
je te retransmets car je ne crois pas que le message t'ait rejoint.
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-04-02 20:32Z]

Oui, j'ai corrigé tous les Silene dans ce sens.

Merci, Marc.
