### ISSUE TITLE
Lotus krylovii 28752 added to VASCAN

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#440]
[Originally posted on GoogleCode (id 2527) on 2015-03-13]

Marc and Marilyn:

Lotus krylovii 28752 added to VASCAN for BC

Please add vernacular names

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-03-13 20:09Z]

nom français ajouté.
Marc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-13 20:12Z]

merci
L

Le 2015-03-13 16:09, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-14 15:28Z]

English name added as well
