### ISSUE TITLE
Bolboschoenus glaucus 28762 added to VASCAN

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#441]
[Originally posted on GoogleCode (id 2528) on 2015-03-13]

Marc and Mrilyn:

Bolboschoenus glaucus 28762 added to VASCAN

Please add vernacular names

Merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-03-13 20:43Z]

nom français ajouté.
Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-14 15:28Z]

English names added as well
