### ISSUE TITLE
Festuca heterophylla 28781

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#442]
[Originally posted on GoogleCode (id 2531) on 2015-03-17]

MArc et Marilyn:

Festuca heterophylla 28781 added to BC

Vernaculars provided by WildSpecies: 
Various-leaved Fescue
Fétuque à feuilles variables

Please check and add adequate vernaculars.

The species comes from Eurasia.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-17 15:53Z]

English names added

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-03-26 16:52Z]

Noms français ajoutés.
« Done »
Marc
