### ISSUE TITLE
Bromus riparius 28785

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#443]
[Originally posted on GoogleCode (id 2532) on 2015-03-17]

Marc et Marilyn:

Bromus riparius 28785 introduced BC

WildSpecies provided following vernaculars:
Asian Meadow Brome
Brome des rivages

Please validate and add
Origin: Asia

MErci
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-17 15:53Z]

Hi - please don't use Wild Species as a source of vernaculars. These all on my names from other sources or created (as I did the national rollp for the vascular plants for Wild Species in 2005 and 2010).
English names added.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-17 15:55Z]

I am not, as you could see
Just provided for info.

Luc

Le 2015-03-17 11:53, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-03-26 17:04Z]

French names added.
Done
Marc
