### ISSUE TITLE
Linum compactum 28788

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#444]
[Originally posted on GoogleCode (id 2533) on 2015-03-17]

Linum compactum 28788 added to Sask &amp; Alta

MArilyn and Marc

The species above was added to VASCAN following verification of WildSpecies 2010 data.

Please validate the following vernaculars and add them to VASCAN:
Compact Yellow Flax
Lin dense

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-17 15:56Z]

ok I'll check on how this was added. fyi - Wild Species 2015 is currently underway. I'm doing NT and NU - lots of changes. Hence I would wait for the 2015 data and don't add based upon Wild Species I think a specific source is better.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-17 16:01Z]

Marilyn

I do not have a choice for 2015 since Environment Canada asked us to
provide a list of species for Canada.

I am just attempting to determine what happened with 2010 names, as per
our contract.

Luc

Le 2015-03-17 11:56, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-17 16:10Z]

There are a lot of mistakes Luc. I'm documenting them for NU and NT. OK I guess you can provide a list and they'll deal with it but the person doing the national rollup this year isn't a botanist. One good thing is they are using VASCAN this year, instead of a mix of treatments as dictated for the other years.
SK is reporting Linum compactum as of March 15 data but Alberta isn't quite yet (as of May 2014 data).
English names added.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-17 17:09Z]

I am not interested in distributions currently.

Luc

Le 2015-03-17 12:10, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-03-17 22:01Z]

Luc, pourrais-tu me donner le code sous lequel Wildspecies figure dans la liste de références de VasCan? S'agit-il d'une nouvelle référence? J'aimerais la citer pour le nom français « lin dense » qui me paraît acceptable, mais je n'arrive pas à la trouver.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-18 14:42Z]

Hi Marc - you can put yours or my name with 'lin dense' as I created it.

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2015-03-18 14:54Z]

OK, French name added.
