### ISSUE TITLE
Potentilla multisecta 28792

### ISSUE THREAD

**Issue by brouille** [Canadensys/vascan-data#445]
[Originally posted on GoogleCode (id 2534) on 2015-03-17]

Potentilla multisecta 28792 added to Alta.

Marc and Marilyn

Please add vernaculars

WildSpecies 2010 had:
Feather-leaved Cinquefoil
Potentille à feuilles laciniée

Thanks
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2015-03-17 16:26Z]

English names added. Maybe the Alberta material is something else? with the Potentilla revisions as FNA isn't reporting for Canada.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2015-03-17 17:09Z]

FNA probably missed Alta. because VASCAN did not have it and the Alta.
reviewer did not point it out. There have been lacks.

Luc

Le 2015-03-17 12:27, � canadensys@googlecode.com �
<canadensys@googlecode.com> a �crit :
