### ISSUE TITLE
Poa abbreviata subsp. pattersonii

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#45]
[Originally posted on GoogleCode (id 1620) on 2013-01-27]

Salut

En vérifiant une vieille carte de FNAms sur Poa, je remarque qu'il manque le Nunavut pour Poa abbreviata subsp. patersonii.
Tu verras un seul point sur le fichier joint.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-01-28 18:48Z]

Fred

Quel point au Nunavut? Tous les points sont aux N.W.T. VASCAN a déjà ce territoire.

Luc
