### ISSUE TITLE
misspelling of epithet

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#456]
[Originally posted on GoogleCode (id 18) on 2010-11-18]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5672

<b>What data are incorrect or missing?</b>
Phaca pecctinatus

<b>What data are you expecting instead?</b>
- should be Phaca pectinata

<b>If applicable, please provide an authoritative source.</b>
ipni, Tropicos

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-10-26 18:35Z]

The ending was corrected, but there are still two 'c's in the epithet.

It should be Phaca pectinata

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-26 19:27Z]

correction made - will show only at next compilation

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-26 19:27Z]

correction made - will show only at next compilation
