### ISSUE TITLE
accepted species listed as synonym of this species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#467]
[Originally posted on GoogleCode (id 29) on 2010-11-24]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5838

<b>What data are incorrect or missing?</b>
Melilotis alba is listed as a synonym of Melilotis officinalis, but it is also listed as an accepted species.

<b>What data are you expecting instead?</b>
a correction

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-11-24 15:21Z]

Melilotus albus Medikus is ACC
Melilotus albus Desrousseaux nom. illeg. is SYN of Melilotus officinalis (Linnaeus) Pallas ACC
No correction is required
