### ISSUE TITLE
Phaca frigida var. americana Hooker

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#47]
[Originally posted on GoogleCode (id 1627) on 2013-02-12]

Salut

Il manque l'autorité de Phaca frigida.
Linnaeus selon Plant List et FNAms

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-19 21:26Z]

Le taxon Phaca frigida n'est pas dans VASCAN comme tel, seulement la var. americana. Alors où devrais-je mettre l'autorité, puiqu'on ne donne que l'autorité finale des taxons?
