### ISSUE TITLE
synonym authorities

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#493]
[Originally posted on GoogleCode (id 55) on 2010-12-04]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2733

<b>What data are incorrect or missing?</b>
Camassia hyacinthina Palmer &amp; Steyermark

<b>What data are you expecting instead?</b>
– should be Camassia hyacinthina (Raf.) E.J. Palmer &amp; Steyermark

<b>If applicable, please provide an authoritative source.</b>
IPNI,Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-05 19:23Z]

Note that source IPNI has same error as original VASCAN. A note has been sent.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-05-10 12:33Z]

The initials E.J. should also be added in front of Palmer's name.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-10-26 16:13Z]

while the basionym authority has been added, Palmer's initials have not yet been added:

Camassia hyacinthina (Rafinesque) Palmer & Steyermark
should be
Camassia hyacinthina (Rafinesque) E.J. Palmer & Steyermark

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-28 19:22Z]

initials added, finally... will be visible at next updating
