### ISSUE TITLE
synonym authorites & duplication

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#495]
[Originally posted on GoogleCode (id 57) on 2010-12-04]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2733

<b>What data are incorrect or missing?</b>
Quamasia esculenta Rafinesue (which appears twice in the display in this form)

<b>What data are you expecting instead?</b>
- should be (KerGawler) Coville, nom. illeg. hom, non Rafinesque  

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-05 19:25Z]

It is not repeated. The authority under second accepted name is distinct.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2010-12-05 20:09Z]

Hi Luc,  The name Quamasia esculenta Rafinesque many not be repeated in synonymy in your files, but online this is what the viewer sees for synonymy.  A repetition of Q. esculenta does appear.  - Sue.


								Camassia esculenta Lindley
								
								
								
							
								Cyanotris scilloides Rafinesque
								
								
								
							
								Camassia fraseri Torrey
								
								
								
							
								Camassia hyacinthina Palmer & Steyermark
								
								
								
							
								Phalangium esculentum Nuttall
								
								
								
							
								Lemotrys hyacinthina Rafinesque
								
								
								
							
								Quamasia esculenta Rafinesque
								
								
								
							
								Quamasia esculenta Rafinesque
								
								
								
							
								Quamasia hyacinthina Britton ex Britton & Brown
								
								
								
							
								Scilla esculenta Ker-Gawl
								
								
								
							
								Silcodium esculentum Salisbury

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-06 19:38Z]

Well then, it must be removed because I do not have it in my working
database. But it will not show immediately, again (we plan on another upload
later this month).

Luc
