### ISSUE TITLE
synonym authorites: Quamasia hyacinthina

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#496]
[Originally posted on GoogleCode (id 58) on 2010-12-04]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2733

<b>What data are incorrect or missing?</b>
Quamasia hyacinthina Britton ex Britton &amp; Brown 

<b>What data are you expecting instead?</b>
– should be Q. hyacinthina (Raf.) Britton ex Britton &amp; A.Brown

<b>If applicable, please provide an authoritative source.</b>
FNA

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-10-26 16:26Z]

This was not fixed (Britton and Brown should be Britton & A.Brown, re: IPNI authors), but upon looking at Tropicos, it seems that the citation should be:

Quamasia hyacinthina Britton  [in Britton & A.Brown is not needed]

see IPNI and Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-26 17:16Z]

Not fixed because there are other issues. All is not clear in the taxonomy
of Camassias.

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-10-26 17:30Z]

OK, thanks for the update.  - Sue.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-10-28 19:20Z]

Finally, this is not such a big deal. The issues were with another item. Correction made (will have to wait next compilation, however, as I just did one, with lots of changes).
