### ISSUE TITLE
synonym authoriyt: Scilla esculenta

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#497]
[Originally posted on GoogleCode (id 59) on 2010-12-04]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2733

<b>What data are incorrect or missing?</b>
Scilla esculenta Ker-Gawl 

<b>What data are you expecting instead?</b>
should be Ker-Gawler (or Ker Gawl.)

<b>If applicable, please provide an authoritative source.</b>
IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-05 19:27Z]

Ker Gawler is the form provided by IPNI. All corrected to this.
