### ISSUE TITLE
missing parenthetical author

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#504]
[Originally posted on GoogleCode (id 68) on 2010-12-08]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7358

<b>What data are incorrect or missing?</b>
Armerica arctica F.W.Wallroth 

<b>What data are you expecting instead?</b>
– should be (Chamisso) F.W.Wallroth
also A. arctia subsp. arctica F.W.Wallroth – should be (Chamisso) F.W.Wallroth; 
basionym of these spp. is: Armeria vulgaris Willdenow forma arctica Chamisso   

<b>If applicable, please provide an authoritative source.</b>

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2010-12-08 00:40Z]

See Tropicos  <http://www.tropicos.org/Name/25400028>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-08 19:55Z]

Armeria arctica (Chamisso) Wallroth
