### ISSUE TITLE
Exclusion à ajouter dans la flore du Canada

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#51]
[Originally posted on GoogleCode (id 1631) on 2013-02-12]

Salut

Astragalus curvicarpus (A.Heller) I.F. Macbr. 
“Cited by Henry (1915) (as Astragalus speirocarpus A. Gray var. falciformis A. Gray) but no BC material available.” - IFBC.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-26 19:32Z]

Problème nomenclatural avec les autorités - FNA, IPNI & GRIN vs TROPICOS
Cependant, comme le basionyme est nom. illeg. superfl., il est possible que la combinaison de Heller soit un nom. nov.

J'ajoute avec la nomenclature de IPNI
