### ISSUE TITLE
typo in accepted name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#518]
[Originally posted on GoogleCode (id 85) on 2010-12-16]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5455

<b>What data are incorrect or missing?</b>
The x in Woodsia ×maxonii was replaced by a hybrid symbol.

<b>What data are you expecting instead?</b>
Woodsia ×maxonii

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-16 16:25Z]

Thanks for this one. It was hardly visible. Result of a global change that was too sweeping.
