### ISSUE TITLE
authorities in synonyns; spelling of one epithet

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#527]
[Originally posted on GoogleCode (id 94) on 2010-12-18]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2838

<b>What data are incorrect or missing?</b>
Antennaria angustifolia E.Ekman  
Antennaria brevistyla Greene
Antennaria leuchippi 

<b>What data are you expecting instead?</b>
Antennaria angustifolia Rydb.
Antennaria brevistyla Fernald
Antennaria leuchippii 

<b>If applicable, please provide an authoritative source.</b>
Tropicos and IPNI.  A. angustifolia E.Ekman is a later homonym that = A.ekmaniana A.E.Porsild.  I can't find any source for A. brevistyla Greene.
Tropicos spells the last name as leuchippii, but IPNI uses leuchippi. The original publication may be needed to resolve this, but maybe there is a rule it was changed.  See: Canad. Field-Naturalist 60: 85. 1947

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-20 18:47Z]

Antennaria angustifolia E. Ekman is a syn. of A. friesiana.
Antennaria angustifolia Rydberg is a syn. of A. rosea subsp. confinis
The two are not the same; that by E. Ekman is obviously a later homonym, but still that does not mean E. Ekman should be replaced by Rydberg in this case.

The name Antennaria brevistylis Greene is being investigated. It is not recorded in databases and came from FNA 19: 414.

The spelling of leuchippi vs leuchippii is being investigated.
