### ISSUE TITLE
Myriophyllum aquaticum (Vellozo) Verdcourt

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#53]
[Originally posted on GoogleCode (id 1633) on 2013-02-13]

Pas de nom anglais

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-19 21:32Z]

MArilyn

Could you see to this pls?

Tx
Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2013-06-18 12:49Z]

completed
