### ISSUE TITLE
question about synonym authority abbreviation

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#536]
[Originally posted on GoogleCode (id 103) on 2010-12-19]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3264

<b>What data are incorrect or missing?</b>
Lactuca spicata (Lam.) Hitchcock

<b>What data are you expecting instead?</b>
If you are using initials for all the names with more than one authority, this synonym would be: Lactuca spicata (Lam.) A.S.Hitchcock, but if you're just using initials for authorities for those other than the original Hitchcock, this is not an issue.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-20 19:38Z]

Hitchcock here is indeed A.S. Hitchcock, but the authority does not require initials here since it is abbreviated without initials. I only use initials for names that have them in abbreviations, according to IPNI, etc.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-31 13:52Z]

This taxon appears as "Lactuca spicata (Lamarck) Hitchcock" in the database: http://data.canadensys.net/vascan/taxon/11618

Is this issue resolved?
