### ISSUE TITLE
Myriophyllum aquaticum - répartition manquante dans VASCAN

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#54]
[Originally posted on GoogleCode (id 1634) on 2013-02-13]

Selon FNAms, l'espèce est introduit dans toutes ces régions.

Alta., B.C., Man., N.B., Nfld. and Labr., N.W.T., N.S., Nunavut, Ont., P.E.I., Que., Sask., Yukon

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-19 21:33Z]

Le problème est que les réviseurs ne semblent pas y croire. Je me demande où il a pris sa répartition

Luc
