### ISSUE TITLE
incorrect parent listed in cross

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#546]
[Originally posted on GoogleCode (id 113) on 2010-12-20]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9832

<b>What data are incorrect or missing?</b>
Nabalus racemosus x Pyrola chlorantha

<b>What data are you expecting instead?</b>
Nabalus racemosus × Nabalus trifoliolatus

<b>If applicable, please provide an authoritative source.</b>
USDA Plants database

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-20 19:59Z]

Wrong numbering in original database. Now fixed.
