### ISSUE TITLE
no English common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#548]
[Originally posted on GoogleCode (id 115) on 2010-12-20]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3224

<b>What data are incorrect or missing?</b>
no English common name listed

<b>What data are you expecting instead?</b>
field hawkweed, meadow hawkweed, or yellow king devil 

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-02-02 20:12Z]

Vernacular names are now provided.
