### ISSUE TITLE
species listed in synonymy under subspecies

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#555]
[Originally posted on GoogleCode (id 123) on 2010-12-21]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2828

<b>What data are incorrect or missing?</b>
# Antennaria parlinii Fernald

<b>What data are you expecting instead?</b>
Don't understand why the species is listed in synonymy under the subspecies, unless this is just a software error.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2010-12-21 20:59Z]

In the original database the species is not syn. of subsp. - these are var. 

May have to check whether there is an importation problem (due to the data).

Thanks
