### ISSUE TITLE
authority abbreviation

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#559]
[Originally posted on GoogleCode (id 128) on 2010-12-21]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2856

<b>What data are incorrect or missing?</b>
Arnica angustifolia subsp. tomentosa (J.M. Macoun) G.W. Douglas &amp; G. Ruyle-Douglas

<b>What data are you expecting instead?</b>
Arnica angustifolia subsp. tomentosa (J.M. Macoun) G.W. Douglas &amp; Ruyle-Douglas
Only 1 Ruyle-Douglas, so G. insn't needed

<b>If applicable, please provide an authoritative source.</b>
IPNI Authors:      Ruyle-Dougl. - Gloria Ruyle-Douglas fl. 1978

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-03 21:34Z]

All other instances of Ruyle-Douglas have been corrected.
