### ISSUE TITLE
typo in authority

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#561]
[Originally posted on GoogleCode (id 130) on 2010-12-21]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2854

<b>What data are incorrect or missing?</b>
Arnica alpina subsp. sornborgeri (Fernald) ald) Maguire

<b>What data are you expecting instead?</b>
Arnica alpina subsp. sornborgeri (Fernald) Maguire
extra ald) to be deleted.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-03 21:50Z]

Already corrected in the original database. We have been and still are in the process of catching typos like this. 

Thanks nonetheless. This is very helpful to all.
