### ISSUE TITLE
typo in spelling of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#564]
[Originally posted on GoogleCode (id 133) on 2010-12-21]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2868

<b>What data are incorrect or missing?</b>
Arnica porsilidorum B. Boivin

<b>What data are you expecting instead?</b>
Arnica porsildorum B. Boivin

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-03 21:59Z]

corrected porsildiorum fide IPNI and TROPICOS
