### ISSUE TITLE
authorities of syonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#574]
[Originally posted on GoogleCode (id 146) on 2010-12-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3191

<b>What data are incorrect or missing?</b>
Helianthus annuus var. lenticularis (Douglas) Steyermark

<b>What data are you expecting instead?</b>
Helianthus annuus [unranked] ?var. lenticularis (Douglas) Cockerell (1908)
Helianthus annuus subsp. lenticularis (Douglas) Cockerell (1914)

IPNI shows Cockerell's 1908 combination as unranked and his 1914 publication as subsp., but Tropicos cites the 1908 publication as subsp. GRIN has Cockerell as the author of the var. (1908) and subspecies (Cockerell) Cockerell (1914).  Steyermark would be a later isonym at varietal status.

<b>If applicable, please provide an authoritative source.</b>

IPNI: Cockerell first published a combination without rank in 1908, but then in 1914 published the same name at subspecies rank.  

Original publication (1/2 page): 
T.D.A.Cockerell. Variation in Helianthus  Bot. Gazette. 1908 (45) pg.338: 
&quot;In a recent number of this journal, Dr. George H. Shull calls attention to the dark disk found in the wild sunflower of the prairie region, but shows that certain material received from that region was heterozygous with a yellow disk recessive.  It may be worthwhile to report that this wild plant does actually produce a yellow-disked variety, which I have observed both in Colorado and New Mexico.  The western sunflower, according to Rydberg, is separable as a distinct species, Helianthus lenticularis Douglas.  This seems to be going too far, and I think it should be called Helianthus annuus lenticularis.  The colour of the disk is considered a specific character in Helianthus; but it certainly varies within specific limits, not only in H. annuus, but in H. petiolaris also, as I have shown in Nature June 19, 1902p. p. 174.&quot;

Grin has var. lenticularis Cockerell (1908), with the same publication data that Tropicos has for subsp. lenticularis (Douglas ex Lindl.) Cockerell (1908). See also Science 4040: 284. 1914.

I can't access the 1914 Science article (subsp. lenticularis) online for free at home, but here is the link:
http://www.sciencemag.org/content/40/1025/283.extract
This may give some explanation of his intended rank for his 1908 publication.

One last comment on this taxon - GRIN and IPNI list Helianthus lenticular Douglas as the basionym (in Lindley 1829), while Tropicos and list Douglas ex Lindley

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-02-11 18:42Z]

response from K. Gandhi:
What is given in IPNI is correct.

I provide an important info below:

1) Helianthus annuus L. [infrasp.unranked] lenticularis (Douglas) 
Cockerell Bot. Gaz. 45: 338. 1908

I quote the protologue below:

Protologue (1908): "... The western sunflower, according to Rydberg, 
is separable as a distinct species, Helianthus lentictdaris Dougl. 
This seems to be going too far, and I think it should be called H. 
annuus lentcularis ...-T. D. A. Cockerell"

As you can see above, Cockerell did not assign any infraspecific rank 
to this name ("H. annuus lenticularis").  And his new combination on 
H. lenticularis Douglas.

2) The varietal rank was made by Steyermark in 1960.

3) The subspecific rank was made by Cockerell in 1914.
