### ISSUE TITLE
common name question

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#577]
[Originally posted on GoogleCode (id 149) on 2011-01-02]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3602

<b>What data are incorrect or missing?</b>
problem with common name: Lake Huron tansy

<b>What data are you expecting instead?</b>
since T. huronense is back as a recognized species, the common name Lake Huron tansy should stay with that taxon, especially since you show only the Yukon for the range of T. bipinnatum.  Cody's Yukon flora doesn't list a common name for T. bipinnatum, but Hitchcock &amp; Cronquist (Flora of the Pacific Northwest) list 'northern dune tansy' and 'western tansy' as common names for T. douglasii, a synonym of T. bipinnatum.  Either of these common names seem more appropriate if no one has coined the name bipinnate tansy or Yukon tansy.  Also, the name floccose tansy seems best associated with T. huronense var. floccosum.

<b>If applicable, please provide an authoritative source.</b>
Hitchcock and Cronquist's Flora of the Pacific Northwest

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-03 22:35Z]

Tanacetum huronense is only recognized temporarily to be able to accomodate the rare var. floccosum, for which there is currently no combination under T. bipinnatum. Until such a combination is made, I will keep the temporary taxonomy. I aknowledge this causes problems for the time being, but it is not possible to make new combinations online. Therefore, I will wait resolution of the issue before making changes to the vernacular.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-01-04 15:43Z]

So, you still see T. huronense as a variety of T. bipinnatum then?

Thanks, Sue.
