### ISSUE TITLE
Autorité erroné dans VASCAN

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#6]
[Originally posted on GoogleCode (id 336) on 2011-04-08]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

<b>What data are incorrect or missing?</b>
Oryzopsis canadensis (Poiret) Trinius

<b>What data are you expecting instead?</b>
Oryzopsis canadensis (Poiret) Torrey ex A. Gray

<b>If applicable, please provide an authoritative source.</b>
IPNI
Poaceae Oryzopsis canadensis (Poir.) Torr. -- Fl. New York 2: 433. 1843 (GCI) 
Poaceae Oryzopsis canadensis Torr. ex A.Gray -- Manual (Gray) 583. 1848 (IK) 

TROPICOS
Poaceae  Oryzopsis canadensis(Poir.) Torr. Fl. New York 2: 433 1843

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-27 20:37Z]

(Poiret) Torrey est la bonne autorité - modification faite
