### ISSUE TITLE
authority of species, synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#600]
[Originally posted on GoogleCode (id 176) on 2011-01-29]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3248

<b>What data are incorrect or missing?</b>
Hymenopappus filifolius Hook. subsp. polycephalus (Ostenhout) B.L.Turner  

<b>What data are you expecting instead?</b>
Hymenopappus filifolius Hook. var. polycephalus (Ostenhout) B.L.Turner  

<b>If applicable, please provide an authoritative source.</b>
FNA, Tropicos, IPNI
This may be a taxon that doesn't have a published name yet, but I can't find any subsp. combination.

Also, synonym: Hymenopappus filifolius Hook. var. polycephalus Ostenhout
...should be Hymenopappus filifolius Hook. var. polycephalus (Ostenhout) B.L.Turner

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-31 21:33Z]

The syn. was removed - it repeats the main name - there is no subsp.
