### ISSUE TITLE
rank and authoities of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#604]
[Originally posted on GoogleCode (id 180) on 2011-01-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3332

<b>What data are incorrect or missing?</b>
Senecio fastigiatus var. macounii Greenman

<b>What data are you expecting instead?</b>
Senecio fastigiatus subsp. macounii (Greene) Greenman - 1906

<b>If applicable, please provide an authoritative source.</b>
IPNI lists no information for this rank, but IPNI and Tropicos list subsp. macounii (Greene) Greenm.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-02-02 20:09Z]

I contacted Kanchi Gandhi concerning this issue. There is no var. macounii. The entry has been removed from IPNI.
