### ISSUE TITLE
authoritiesof synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#606]
[Originally posted on GoogleCode (id 182) on 2011-01-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3335

<b>What data are incorrect or missing?</b>
Senecio discoideus Britton

<b>What data are you expecting instead?</b>
Senecio discoideus (Hooker) Britton

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-31 21:56Z]

This is already corrected in the database, but not published yet.

It is also a nom. illeg.
