### ISSUE TITLE
authorities of var. and synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#607]
[Originally posted on GoogleCode (id 183) on 2011-01-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3342

<b>What data are incorrect or missing?</b>
var. borealis (Torrey &amp; A. Gray) Bain
and 
Senecio cymbalarioides var. borealis Greenman 

<b>What data are you expecting instead?</b>
var. borealis (Torrey &amp; A. Gray) J.F.Bain
– should be (Torr. &amp; A.Gray) Greenman

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-31 22:02Z]

Packera streptanthifolia var. borealis (Torrey & A. GRay) Trock <IPNI, TROPICOS - this has been corrected in database now>

Senecio cymbalarioides H. Buek var. borealis (Torrey & A. Gray) Greenman now corrected
