### ISSUE TITLE
spelling of synonym and authorities

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#609]
[Originally posted on GoogleCode (id 185) on 2011-01-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3345

<b>What data are incorrect or missing?</b>
Packera moresbiensis (Calder &amp; Roy L. Taylor) Bain
a\nd 
Senecio residifolius  ...

<b>What data are you expecting instead?</b>
should be .... J.F.Bain
and 
Senecio resedifolius

also, G.Ruyle-Douglas doesn't need the G.

<b>If applicable, please provide an authoritative source.</b>
Tropicos has resedifolius spelled as residifolis only for var. moresbiensis, an error there, since they list Senecio resedifolius Less. as the species.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-31 22:05Z]

correction to Ruyle-Douglas already done
