### ISSUE TITLE
Melampyrum lineare Desrousseaux - autorité des variétés ne concorde pas avec FNAms

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#61]
[Originally posted on GoogleCode (id 1821) on 2013-08-05]

Salut

Dans VASCAN: Melampyrum lineare var. latifolium W. Barton 
Dans FNAms: M. lineare var. latifolium (Muhlenberg ex Britton) Beauverd

Ajouter dans VASCAN le synonyme: Melampyrum latifolium Muhlenberg ex Britton
Ainsi que le synonyme : M. lineare var. pectinatum (Pennell) Fernald
Ainsi que le synonyme : M. lineare var. americanum (Michaux) Beauverd

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-05 12:07Z]

Fred

Ces changements sont déjà effectués dans l'éditeur.

Luc
