### ISSUE TITLE
incorrect authorities in synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#610]
[Originally posted on GoogleCode (id 186) on 2011-01-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3347

<b>What data are incorrect or missing?</b>
Senecio cymbalarioides Nuttall
and 
Senecio aureus var. subnudus A.Gray 

<b>What data are you expecting instead?</b>
Senecio cymbalarioides H.Buek; Nuttall's name, a later homonym is a synonym of Packera streptanthifolia var. streptanthifolia
and
Senecio aureus var. subnudus (DC.) A.Gray

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-01-31 22:07Z]

Senecio cymbalarioides H. Buek already in database
