### ISSUE TITLE
authority/rank of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#632]
[Originally posted on GoogleCode (id 210) on 2011-02-06]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3357

<b>What data are incorrect or missing?</b>
Picris hieracioides var. kamtschatica (Ledebour) Hultén

<b>What data are you expecting instead?</b>
Picris hieracioides var. kamtschatica (Ledebour) B.Boivin
Picris hieracioides subsp. kamtschatica (Ledebour) Hultén

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-02-11 13:29Z]

Was already corrected in database.
