### ISSUE TITLE
spelling of authority in synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#634]
[Originally posted on GoogleCode (id 212) on 2011-02-06]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3608

<b>What data are incorrect or missing?</b>
Taraxacum pseudo-kamtschaticum B.A. Yurtsev

<b>What data are you expecting instead?</b>
Taraxacum pseudo-kamtschaticum Jurtzev

<b>If applicable, please provide an authoritative source.</b>
IPNI authors; B.A. Yurtsev is an alternate spelling of the accepted Jurtzev; no intials needed for this name, nor for Dahlstadt, who is the authority of the other 2 synonyms on this page.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-02-11 13:37Z]

Corrected through database.
