### ISSUE TITLE
typo in spelling of variety name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#637]
[Originally posted on GoogleCode (id 215) on 2011-02-07]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4151

<b>What data are incorrect or missing?</b>
Opuntia erinacea var. columbinana (Griffiths) L.D. Benson

<b>What data are you expecting instead?</b>
Opuntia erinacea var. columbiana (Griffiths) L.D. Benson

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-02-11 13:46Z]

I am not certain what you want done here: do you want me to include (pro sp.) after Griffiths in the parens, as done in TROPICOS? IPNI does not do it and I am uncertain that it is necessary.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-02-11 15:27Z]

Hi Luc, The epithet is spelled columbi*_n_*ana online, while it should 
be columbiana
