### ISSUE TITLE
inversion des autorités dans les variétés des synonymes de Agalinis neoscotica

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#64]
[Originally posted on GoogleCode (id 1824) on 2013-08-05]

Salut

VASCAN:
Agalinis purpurea var. neoscotica (Greene) Pennell &amp; H. St.John
Agalinis paupercula var. neoscotica (Greene) Boivin 

FNAms
Agalinis paupercula var. neoscotica (Greene) Pennell &amp; H. St. John; 
Agalinis purpurea var. neoscotica (Greene) B. Boivin

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-05 12:10Z]

Déjà fait

Luc
