### ISSUE TITLE
spelling of Sargent; Hicoria or Hicorius?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#649]
[Originally posted on GoogleCode (id 228) on 2011-02-24]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6236

<b>What data are incorrect or missing?</b>
Carya ovalis var. odorata (Marshall) Sergent

<b>What data are you expecting instead?</b>
Carya ovalis var. odorata (Marshall) Sargent

Also, on checking the Hicoria names, IPNI uses Hicorius (1817, but a nom. rej., while Tropicos uses Hicoria (1839).  
Which of these two orthographic versions should be used in all cases?

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-01 14:17Z]

Sent a query concerning Hicorius vs Hicoria.
