### ISSUE TITLE
incorrect authorities for species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#651]
[Originally posted on GoogleCode (id 230) on 2011-02-24]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9800

<b>What data are incorrect or missing?</b>
Carya tomentosa (Miller) Sweet

<b>What data are you expecting instead?</b>
Carya tomentosa (Poiret) Nuttall
basionym: Juglans tomentosa Poiret in Lamarck

<b>If applicable, please provide an authoritative source.</b>
FNA, Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-06 14:00Z]

The basionym author is Lam., NOT Poir.

FNA and TROPICOS are incorrect!  [This was before my time and Jim’s time in FNA.]

IPNI is correct
