### ISSUE TITLE
spelling of epithet

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#652]
[Originally posted on GoogleCode (id 231) on 2011-02-24]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6241

<b>What data are incorrect or missing?</b>
Juglans ailanthifolia

<b>What data are you expecting instead?</b>
Some databases spell the epithet without the 'h', but I don't know which is correct.

<b>If applicable, please provide an authoritative source.</b>
GRIN &amp; Mansfeld's: Juglans ailantifolia
IPNI: Juglans ailantifolia

Tropicos: Juglans ailanthifolia
Plant List: Juglans ailanthifolia

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-14 14:28Z]

ailantifolius is the spelling to be used currently fide Dr. Gandhi:
“ailantifolia” is the original spelling.
The stem of the 1st term can be “ailant-” or “ailanth-”.
The author chose “ailant-”.
We cannot correct it without a proposal.
