### ISSUE TITLE
common name mistake

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#653]
[Originally posted on GoogleCode (id 232) on 2011-02-25]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6154

<b>What data are incorrect or missing?</b>
you have &quot;false St. John's-wort&quot; listed for Hypericum gentianoides

<b>What data are you expecting instead?</b>
this is a true Hypericum, so shouldn't the common name read &quot;false gentian&quot;?

Also, you list &quot;pinweed St. John's-wort&quot; as another common name. When I lived in Connecticut, we called this pineweed, not pinweed, which I think is a misspelling that was copied on in other sites.  So I think this is a spelling mistake.  The plants do look like pine seedlings.  Orangeweed was the other common name we used.  Either one of these would be a better choice for the accepted name, since I can find no resources that call this false St. Johnswort (or false gentian).
See:
&lt;http://www.ct-botanical-society.org/galleries/hypericumgent.html&gt; 
&lt;http://web4.msue.msu.edu/mnfi/abstracts/botany/Hypericum_gentianoides.pdf&gt; 
&lt;http://www.southeasternflora.com/view_flora.asp?plantid=932&gt; 

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-06 13:21Z]

Marilyn:

Any input on this issue?

Thanks
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-06 14:36Z]

Marilyn answered on April 07 (sorry for the reminder, I was doing it automatically):
I've reviewed this carefully and propose the following (in order of best name choice):
1. gentian-leaved St. John's-wort 
New Source: Michigan Natural Features Inventory http://web4.msue.msu.edu/mnfi/data/specialplants.cfm

2. orangegrass
Source: USDA PLANTS

3. pineweed
New Source: Zinck, M. 1998. Roland's Flora of Nova Scotia. Nimbus Publishing and Nova Scotia Museum.  2 volumes. 1297 p.

I currently cannot add new sources. This will have to wait. But I will enter sources that are already in the db.
