### ISSUE TITLE
synonym placed under wrong subsp.; authorities of synonym incorrect

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#661]
[Originally posted on GoogleCode (id 240) on 2011-02-27]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6016

<b>What data are incorrect or missing?</b>
Gentiana occidentalis (Gray) Small

<b>What data are you expecting instead?</b>
This synonym is placed under Gentianaella quinquefolia subsp. quinquefolia, but it should be under subsp. occidentalis, and the authorities are (A.Gray) Greene (1904). It is an illeg. homonym (non Jakow. 1899), but there is also a later isonym by T.J.Fitzpatrick (1906), but his name does not appear in IPNI authors.

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-01 20:36Z]

I queried TROPICOS and IPNI due to the differences between the databases on the status of names, etc.
