### ISSUE TITLE
authority of synonym and spelling of taxon

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#664]
[Originally posted on GoogleCode (id 243) on 2011-03-01]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6409

<b>What data are incorrect or missing?</b>
Mentha ×mullerana F. Schultz

<b>What data are you expecting instead?</b>
Mentha ×muellerana F.W. Schultz

<b>If applicable, please provide an authoritative source.</b>
Tropicos and Grin

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-12 21:05Z]

muelleriana
authority problem between IPNI and TROPICOS

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-06 14:03Z]

Gandhi: It is F.W.Schultz
