### ISSUE TITLE
Question about status

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#677]
[Originally posted on GoogleCode (id 256) on 2011-03-07]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6479

<b>What data are incorrect or missing?</b>
? status of Thymus drucei as a distinct species:

<b>What data are you expecting instead?</b>
Just wondering why the variation in treatments.  Has this been discussed in FNA ms?
The plant list includes T. drucei, Thymus praecox subsp. brittanicus (of GRIN) and T. praecox subsp. arcticus as synonyms of T. praecox subsp. ligusticus.  

<b>If applicable, please provide an authoritative source.</b>
http://www.theplantlist.org/tpl/record/kew-205274

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-14 15:55Z]

The Plant List is full of errors and peculiar choices. Though it may be right. I just do not know. 
I will not modify this until there is more definite treatments. The FNA treatment has not been submitted.
