### ISSUE TITLE
minor typo in common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#678]
[Originally posted on GoogleCode (id 257) on 2011-03-08]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6483

<b>What data are incorrect or missing?</b>
branched blue-curls

<b>What data are you expecting instead?</b>
branched bluecurls (without hyphen)

<b>If applicable, please provide an authoritative source.</b>
Uses of this common name with other Trichstema spp. do not include the hyphen.  To be consistent, delete the hyphen here.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-14 15:57Z]

bluecurls was also corrected to harmonize with other names
