### ISSUE TITLE
Question about status

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#682]
[Originally posted on GoogleCode (id 261) on 2011-03-08]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6562

<b>What data are incorrect or missing?</b>
accepted name? Millegrana radiola (Linnaeus) Druce

<b>What data are you expecting instead?</b>
Radiola linoides Roth

<b>If applicable, please provide an authoritative source.</b>
GRIN, Tropicos, and Plant List all use Radiola linoides Roth as the accepted name, but they may not be up to date.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-15 15:53Z]

I will change to Radiola since it is the genus name currently in FNA.
Change not made yet because of technical issues.
