### ISSUE TITLE
gender of basionym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#683]
[Originally posted on GoogleCode (id 262) on 2011-03-10]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6353

<b>What data are incorrect or missing?</b>
Hyssopus scrophulariifolia Willdenow

<b>What data are you expecting instead?</b>
Hyssopus scrophulariifolius Willdenow

<b>If applicable, please provide an authoritative source.</b>
Tropicos; didn't notice the gender disagreement until you corrected 
the Lophanthus name. Same situation exists for Agastache urticifolia - basionym should be Lophanthus urticifolius Benth. (re Tropics again)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-15 15:56Z]

Typo corrected.

Pending: adding basionym to Agastache urticifolia.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-05 21:03Z]

Basionym added.
