### ISSUE TITLE
confusion over species authorities

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#705]
[Originally posted on GoogleCode (id 284) on 2011-03-13]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3386

<b>What data are incorrect or missing?</b>
Rudbeckia grandiflora (D. Don) J.F. Gmelin ex de Candolle

<b>What data are you expecting instead?</b>
 
confusion over correct authorities:

It looks like D.Don and Sweet are the same publication, but I don't know if it's D.Don in Sweet, or D.Don ex Sweet.  You may need to check the original publication to see if it should be C.C. or J.F. Gmelin, since the same publication info is given for both.  See:

FNA and IPNI have (Sweet) C.C.Gmelin ex DC., Prodr. (DC.) 5: 556. 1836 [1-10 Oct 1836] (IK)

GRIN has (Sweet) DC.
basionym:Centrocarpha grandiflora Sweet, Brit. Fl. Gard., ser. 2, 1: plate 87. 1831

The Plant List has the basionym listed as:
Centrocarpha grandiflora D.Don, Brit. Fl. Gard. 4: t. 87 (1830) t. 87 1830.  AND
Centrocarpha grandiflora Sweet, Brit. Fl. Gard. 4(ser. 2, 1): 87. 1831 [Mar 1831].
and the accepted name as: Rudbeckia grandiflora (Sweet) DC., Prodr. (DC.) 5: 556 556 1836.

Tropicos has (Sweet) J.F.Gmelin ex DC, Prodromus Systematis Naturalis Regni Vegetabilis 5: 556. 1836.
<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-06 13:29Z]

K. Gandhi: Rudbeckia grandiflora (D. Don) C.C.Gmelin ex DC., Prodr. (DC.) 5: 556. 1836 [1-10 Oct 1836]” is correct.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-06 13:48Z]

Gandhi revised his decision. Here is the comment:
“Rudbeckia grandiflora (Sweet) C.C.Gmelin ex DC., Prodr. (DC.) 5: 556. 1836 [1-10 Oct 1836]” is correct.

D. Don is the author of the basionym genus Centrocarpha, but he is NOT the author of the basionym species C. grandiflora for which Sweet is the author.
