### ISSUE TITLE
Ajout de synonymes sous Pedicularis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#72]
[Originally posted on GoogleCode (id 1833) on 2013-08-05]

Sous Pedicularis capitata: Pedicularis nelsonii R. Brown
Sous Pedicularis groenlandica: Pedicularis groenlandica var. surrecta (Bentham) A. Gray; P. surrecta Bentham
Sous Pedicularis labradocira : P. euphrasioides var. labradorica (Wirsing) Willdenow
Sous Pedicularis lanceolata :Pedicularis auriculata Smith; P. lanceolata var. hirsuta Farwell; P. virginica Poiret
Sous Pedicularis langsdorffii subsp. arctica : P. hians Eastwood
Sous Pedicularis oederi   : Pedicularis versicolor Wahlenberg

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-06 13:56Z]

syn groenlandica ajouts

ts autres déjà présents
