### ISSUE TITLE
question about species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#722]
[Originally posted on GoogleCode (id 301) on 2011-03-25]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9410

<b>What data are incorrect or missing?</b>
Samolus floribundus Humboldt, Bonpland &amp; Kunth

<b>What data are you expecting instead?</b>
Samolus parviflorus Raf.
FNA NOTES: The name Samolus floribundus has sometimes been applied to this taxon. The publication date for S. floribundus is February 1818, making it later than S. parviflorus, published in January of that same year. 

FNA also notes that Samolus valerandi is a European species that does not occur in NAm, so is there a reason to include these two common names:
# Valerand's brookweed
# Valerand's water pimpernel

In most NAm websites, just brookweed or water pimpernel are used.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-20 19:07Z]

Marilyn: 
I believe Sue is right in recommending to remove the names linked to Valerand. See comment above.
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-26 14:24Z]

New name in VASCAN: S. parviflorus

The change will appear on the published VASCAN page only when we can solve our informatics problems.

Answer from Marilyn: Yes please remove the 2 common names: Valerand's brookweed and Valerand's water pimpernel
