### ISSUE TITLE
note about authority of species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#735]
[Originally posted on GoogleCode (id 314) on 2011-03-27]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6807

Ludwigia polycarpa Short &amp; R.Peter is correct, but I just wanted to let you know that Short &amp; Peter is listed in Tropicos and some of IPNI's entries.  They both include the right citation (dated 1835), but R.Peter has to be author because his name was published before 'Peter' was born.

•  Peter - Albert Peter 1853-1937 
•  R.Peter - Robert Peter 1805-1894

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-16 18:24Z]

Correction transmitted to databases.
