### ISSUE TITLE
authorities of synonyms & typo in 1 synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#736]
[Originally posted on GoogleCode (id 315) on 2011-03-27]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6808

<b>What data are incorrect or missing?</b>
Oenothera victorinii Gates &amp; Catcheside
Oenothera perangustata Gates
Oenothera eriensis Gates

<b>What data are you expecting instead?</b>
Oenothera victorinii R.R.Gates &amp; Catcheside
Oenothera perangusta R.R.Gates
Oenothera eriensis R.R.Gates

<b>If applicable, please provide an authoritative source.</b>
Tropicos and IPNI; note correction in spelling of perangustata - it should be perangusta.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-16 18:29Z]

O. victorinii not in TROPICOS - notified database.
