### ISSUE TITLE
question about range.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#741]
[Originally posted on GoogleCode (id 320) on 2011-03-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6595

<b>What data are incorrect or missing?</b>
native status in Labrador

<b>What data are you expecting instead?</b>
Are you certain this is confirmed from Labrador?  Our raw data from Statec in 2006 showed a specimen of L. clavatum, but when the specimen was checked, it proved to be L. lagopus.  There are occasional specimens that have 2 strobili, but if the other traits in the FNA key are checked, the difference is obvious.

If you don't have the specimens, it might be good to check their IDs.
<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-27 17:40Z]

Sue: I believe John Maunders is the one that insisted on adding Labr. for this taxon. I have not seen the specimen at NFM that supports this claim. It may be worth checking. I am leaving the data as is until this can be done.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-04-27 17:54Z]

Hi Luc,

I'll check with John.  If he's only going by the 1 cone vs. 2 or more 
cones, he may have overlooked the other traits.

Thanks, Sue.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-27 17:57Z]

Great. And thanks. I am not sure I can argue this one with John.

I had an interruption in corrections because of problems with the back end
that seem fixed now. But I can only do so much due to many deadlines (Flora
of China and FNA being chiefest currently).

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-04-27 18:48Z]

No problem.  I know you're very busy.  I'll let you know what happens 
with John.  Good luck with the deadlines.  Am looking forward to the 
next FNA volume.

Take care, Sue.
