### ISSUE TITLE
issue with synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#758]
[Originally posted on GoogleCode (id 343) on 2011-04-09]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2446

<b>What data are incorrect or missing?</b>
Viburnum alnifolium Marshall

<b>What data are you expecting instead?</b>
Viburnum alnifolium auct. non Marshall

<b>If applicable, please provide an authoritative source.</b>
GRIN states that Marshall's Viburnum alnifolium is a mixed sample, most of which is actually Hydrangea arborescens L., so this name should be considered an equal synonym.  See:
http://www.ars-grin.gov/cgi-bin/npgs/html/taxon.pl?316311

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-27 20:53Z]

I sent a comment to IPNI and TROPICOS since neither raise this issue.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-04-27 23:18Z]

HI Lic,

In my comment, I said: 
GRIN states that Marshall's Viburnum alnifolium is 
a mixed sample, most of which is actually Hydrangea 
arborescens L., so this name should be considered 
an equal synonym. 

I MEANT to say "should NOT be considered an equal synonym," but you figured that out.
Thanks, Sue.
