### ISSUE TITLE
authorities of synony

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#767]
[Originally posted on GoogleCode (id 352) on 2011-04-11]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2603

<b>What data are incorrect or missing?</b>
Cogswellia villosa (Rafinesque) Schultes

<b>What data are you expecting instead?</b>
Cogswellia villosa (Rafinesque) Sprengel

<b>If applicable, please provide an authoritative source.</b>
Tropicos has Sprengel (1820) and M.E.Jones (1908). IPNI has Schultes. From this note in IPNI,it seems the author should be lised as Sprengel.
IPNI: vols. 5-6 by J. A. Schultes; Apiaceae by C. Sprengel; vol. 7 by J. A. &amp; J. H. Schultes; TL2 (4: 847.1983) suggests that Roemer &amp; Schultes's edition may treated as &quot;ed. 16&quot;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-28 12:52Z]

Change made but I am awaiting confirmation from K. Gandhi
