### ISSUE TITLE
Question about basionym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#768]
[Originally posted on GoogleCode (id 353) on 2011-04-11]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2608

<b>What data are incorrect or missing?</b>
Lomatium macrocarpum (Nuttall ex Torrey &amp; A. Gray) J.M. Coulter &amp; Rose

<b>What data are you expecting instead?</b>
?Lomatium macrocarpum (Hooker &amp; Arnott) J.M. Coulter &amp; Rose

<b>If applicable, please provide an authoritative source.</b>
IPNI &amp; Tropicos disagree as to the basionym: 
IPNI Remarks: For Peucedanum macrocarpum, Torr. &amp; A. Gray referred to &quot;Ferula macrocarpa, Hook. &amp; Arn. bot. Beechey, Suppl. p. 348 ?&quot; and remarked that their &quot;P. macrocarpum may not be identical with Ferula macrocarpa, Hook. &amp; Arn.&quot; Because of the &quot;?&quot; sign (an expression of doubt), P. macrocarpum is treated as a sp. nov. (not a comb. nov.); Vienna Code Art. 33.3 does not apply.
Tropicos Remarks: Coulter &amp; Rose erroneously cited Nuttall as the basis for the combination Lomatium macrocarpum.

Since they're all considered synonymous now, despite Torrey and A.Gray's uncertainty, it seems that the earlier name should be used as the basionym: Hooker &amp; Arnott's name has priority (1839) over Nuttall ex Torrey &amp; A.Gray (1840)

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-05-03 15:32Z]

request sent to Gandhi (IPNI) and Zarucchi (TROPICOS)

**Comment by brouille** [comment]
Kanchi Gandhi 2015: 
As given by GCI & GRIN, "Lomatium macrocarpum (Nutt. ex Torr. & A. Gray) J. M. Coult. & Rose" is correct.
