### ISSUE TITLE
Pedicularis parviflora var. macrodonta (Richardson) S.L. Welsh -  désaccord complet avec FNAms

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#77]
[Originally posted on GoogleCode (id 1838) on 2013-08-05]

Salut

Ce nom ne comporte pas de variétés dans FNAms.  Pedicularis macrodonta est donc envoyé en synonymie de P. parviflora

La répartition de FNAms est seulement Yukon et Alaska alors que VASCAN a pratiquement toutes les provinces et territoires.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-06 13:51Z]

Il semble que ce soit FNa qui ait manqué la répartition - ou alors l'auteur doit expliquer ce qu'il advient des macrodonta du reste du Canada - la question a été posée

synonymie faite
