### ISSUE TITLE
Question about common name

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#785]
[Originally posted on GoogleCode (id 370) on 2011-04-14]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4509

<b>What data are incorrect or missing?</b>
saline goosefoot associated with subsp. glaucum,

<b>What data are you expecting instead?</b>
saline goosefoot associated with subsp. salinum

<b>If applicable, please provide an authoritative source.</b>
The only time I've seen saline goosefoot associated with Chenopodium glaucum is when C. salinum is included as a synonym.  It makes
more sense to use it for subsp. salinum.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-04-14 23:04Z]

Forgot to add, saline goosefoot would be in addition to Rocky Mountain goosefoot, 
not replacing it as the accepted name, just another common name.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-05 21:12Z]

Marilyn:
What is your opinion on this, please?
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-19 18:32Z]

Transfer of vernacular is done.
