### ISSUE TITLE
typ in genus of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#786]
[Originally posted on GoogleCode (id 371) on 2011-04-14]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4502

<b>What data are incorrect or missing?</b>
Blinum chenopodioides Linnaeus

<b>What data are you expecting instead?</b>
Blitum chenopodioides Linnaeus

<b>If applicable, please provide an authoritative source.</b>
Tropicos

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-28 18:32Z]

Sigh
