### ISSUE TITLE
common name 

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#787]
[Originally posted on GoogleCode (id 372) on 2011-04-15]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4493

<b>What data are incorrect or missing?</b>
fat-hen should also be listed as an English common name, particularly since you have the same common name in French for this species.  See links below

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>
&lt;http://www.ukwildflowers.com/Web_pages/chenopodium_album_fat_hen.htm&gt; 
&lt;http://www.plant-identification.co.uk/skye/chenopodiaceae/chenopodium-album.htm&gt;  
&lt;http://www.wildflowersofireland.net/plant_detail.php?id_flower=465&amp;wildflower=Fat-hen&gt; 
&lt;http://www.pfaf.org/user/Plant.aspx?LatinName=Chenopodium%20album&gt; 
&lt;http://www.ars-grin.gov/cgi-bin/npgs/html/taxon.pl?10178 &gt;

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-05 21:13Z]

Marilyn:
What is you opinion on this, pleae?
Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-19 18:35Z]

I will need a citation that is pertinent for Canada, if possible. ANyway, I could not add a new source currently, as you know. Will have to come later.
