### ISSUE TITLE
typo in authoriy of species; HWR, Tropicos lists this as a later homonym.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#804]
[Originally posted on GoogleCode (id 389) on 2011-04-26]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3656

<b>What data are incorrect or missing?</b>
Impatiens ecalcarata Blank
Impatiens biflora var. ecalcarata (Blank) M.E. Jones

<b>What data are you expecting instead?</b>
Impatiens ecalcarata Blankenship
Impatiens biflora var. ecalcarata (Blankenship) M.E. Jones

<b>If applicable, please provide an authoritative source.</b>
Tropicos; however, Tropicos lists Collett &amp; Hemsley (1890) as an earlier name, and the Blankenship name (1905) as a later homonym. I don't know if these are the same plant or not, since Collett &amp; Hemsley's plant is form Burma, while Blankenship's plant is from nwUS.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-29 12:59Z]

Do not know why this is as is... embarassing

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-06-14 12:08Z]

Hi Luc,  Have you found a new name for the later homonym: Impatiens ecalcarata Blankenship?  See comments above under authoritative source.
