### ISSUE TITLE
nativity of hybrid

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#807]
[Originally posted on GoogleCode (id 392) on 2011-04-26]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3668

<b>What data are incorrect or missing?</b>
Native in Ontario

<b>What data are you expecting instead?</b>
Introduced in Ontario.  Since both parents are introduced, the hybrid should be also listed as introduced.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-04-29 13:04Z]

Well, this is a nice issue: the hybrid was produced in loco, not brought as a hybrid from abroad. So your argument is not so absolute as it seems.

I am uncertain how best to treat this. I will leave it as is for now. This is a matter of policy that needs to be addressed.
