### ISSUE TITLE
Question about varieties of Ostrya virginiana

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#815]
[Originally posted on GoogleCode (id 400) on 2011-04-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3726

<b>What data are incorrect or missing?</b>
n/a

<b>What data are you expecting instead?</b>
Just curious, what other varieties are recognized for Ostrya virginiana? Dan has 2 other species in his PHZdB: O. chisosensis and O. knowltonii; are either/both of these now reduced to varietal status under O. virginiana?  Or is O.v. var. lasia considered a separate variety now?

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-01 21:39Z]

Ostrya virginiana (Mill.) K. Koch var. chisosensis (Correll) Henrickson, ined.
var. lasia is syn. of var. virginiana
