### ISSUE TITLE
synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#823]
[Originally posted on GoogleCode (id 419) on 2011-05-09]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2483

<b>What data are incorrect or missing?</b>
Allium tenerum Jones

<b>What data are you expecting instead?</b>
Allium geyeri S.Watson forma tenerum (M.E.Jones) B.Boivin
OR
Allium geyeri S.Watson subsp. tenerum (M.E.Jones) Traub &amp; Ownbey
but there is no combination for Allium tenerum that I can find.

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-18 13:24Z]

Removed A. tenerum
Added subsp. tenerum as syn (VASCAN cannot handle forms)
