### ISSUE TITLE
Limosella - retrait de L. acaulis selon FNAms et synonymie 

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#83]
[Originally posted on GoogleCode (id 1844) on 2013-08-05]

Dans FNAms, Limosella acaulis est envoyé en synonymie de L. aquatilis

Il faut ajouter L. tenuifolia Wolfgang ex Hoffmann dans les synonymes de L. australis

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-06 13:46Z]

l'auteur ne place pas tous les noms requis en synonymie: acaulis est utilisé dans de nombreuses flores récentes et il en parle seulement en discussion - c'est un problème pour VASCAN car eFlora le reconnaît
Mis en synonymie
synonymes ajoutés
