### ISSUE TITLE
status in NF

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#840]
[Originally posted on GoogleCode (id 453) on 2011-05-12]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2617

<b>What data are incorrect or missing?</b>
introduced in NF

<b>What data are you expecting instead?</b>
?excluded from NF

<b>If applicable, please provide an authoritative source.</b>
In our NL checklist, we had this listed in Appendix II (garden cultivars and ephemerals that have not naturalized).  Do you have any reports of this being naturalized in NF?

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-05-13 22:54Z]

I checked with John Maunder, and he says there is one persistent population in a St. John's city park, so you're correct in listing it as introduced. Disregard my comment above.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-18 18:27Z]

I believe this is how I got it in.L.
