### ISSUE TITLE
authority and status of synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#846]
[Originally posted on GoogleCode (id 460) on 2011-05-13]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/2799

<b>What data are incorrect or missing?</b>
Antennaria brevistyla Greene

<b>What data are you expecting instead?</b>
? Antennaria brevistyla Greene is not listed in Tropicos, IPNI, or GRIN, and A. brevistyla Fernald is listed as a synonym of Antennaria rosea subsp. confinis, not A. alpina.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-06-30 13:52Z]

The two names are not synonym of the same taxon. They are both listed in VASCAN under the proper acc. name, fide BAyer, supposedly the expert. I am not changing this because there is no basis to do so currently.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-09-13 14:33Z]

I didn't realize they were two separate names (thought it was a typo), but I can't find any reference to A. brevistyla Greene in IPNI, Tropicos, or GRIN.  One of these names must be a homonym, but I only have the date for Fernald's publication: 1931.
Do you know when Greene's combination was published?
