### ISSUE TITLE
status of species in Labrador

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#848]
[Originally posted on GoogleCode (id 462) on 2011-05-13]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3621

<b>What data are incorrect or missing?</b>
Tephroseris palustris 

<b>What data are you expecting instead?</b>
Tephroseris palustris is still present on Battle Harbour Island, south coast of Labrador.  See pix on John Maunder's Digital Flora of NL.  The plants pictured are pretty depauperate compared to the ones I've seen at James Bay.

<b>If applicable, please provide an authoritative source.</b>
See: http://www.digitalnaturalhistory.com/flora_asteraceae_index.htm#tephroserispalustris

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-18 18:50Z]

I will need to add the reference later. The tool has a problem with adding refs (in fact, with the short ref.)
