### ISSUE TITLE
Misopates orontium (L.) Raf. - nom français

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#85]
[Originally posted on GoogleCode (id 1846) on 2013-08-05]

Le nom suggéré dans Wikipedia et Tela-Botanica est muflier des champs.

Je trouve désagréable de voir que Darbyshire et al., 2000 semble être la source de plusieurs noms français corrects mais qui ne sont pas fréquemment employés.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-06 13:38Z]

N'oublie pas que la source est européenne alors que Darbyshire et al. (en fait, Marc) est canadienne. Cela explique sans doute la différence.

Je transmets à Marc: il vaut peut-être la peine d'ajouter le second nom.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-08-16 20:08Z]

Je ne suis pas en mesure de dire quel nom est le plus fréquemment employé au Canada, mais le nom "muflier rubicond" est celui qui est recommandé au Canada aux fins de la lutte contre les mauvaises herbes, et il figure en outre dans de nombreuses flores européennes ainsi que, comme deuxième choix, dans TelaBotanica. Je pense donc qu'il faut le conserver comme nom accepté dans VasCan. Peut-être les gens de TelaBotanica choisiront-ils un jour de le recommander comme premier choix « parce que c'est le nom accepté dans VasCan ».

J'ai profité de l'occasion pour faire un peu de ménage dans les noms français de la sous-espèce typique.
