### ISSUE TITLE
status of Hieracium plicatum

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#850]
[Originally posted on GoogleCode (id 464) on 2011-05-13]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3241

<b>What data are incorrect or missing?</b>
should Hieracium plicatum Lindeberg be placed in synonym here?  We've got it included in our NF checklist as a distinct species, with a range in northern Labrador. It has 3 subsp./var. that are now included in H. vulgatum: H.p. subsp. amitsokense, H.p. subsp. groenlandicum, and H.p. var. ivigtutense, so I'm not sure if the species or just it's subordinate taxa should be include in synonymy.

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>
NF checklist; IPNI.  Tropicos does not list H. plicatum.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-06-30 13:55Z]

The FNA Hieracium treatment used a broad taxonomic concept for this complex and I am uncertain as to what is best done for Canada now. Also, one would have to determine whether plicatum is the proper name or groenlandicum. I very much doubt that there are 3 entities here.

**Comment by brouille** [comment]
I checked the following for plicatum: http://cichorieae.e-taxonomy.net/portal/cdm_dataportal/taxon/715c889e-a07f-4410-abf6-4487ffc6b886
It is only known in Europe
I suspect that what is called plicatum in n Labrador is in fact plicatum var. groenlandicum = Hieracium groenlandicum (in the Flore nordique du Québec-Labrador, I am recognizing it as distinct from H. vulgatum - they are distinct morphologically/anatomically and ecologically).
