### ISSUE TITLE
status of Lactuca canadensis in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#851]
[Originally posted on GoogleCode (id 465) on 2011-05-13]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3263

<b>What data are incorrect or missing?</b>
Lactuca canadensis is listed from Nfld. and Labrador, but I know of no verified specimens.  This sp. was listed in Day (1999) from Goose Bay area, but FNA shows the nearest distribution in southern Quebec and Nova Scotia, so this is probably a misidentification.  

<b>What data are you expecting instead?</b>
delete from NF &amp; LB, unless you have more up to date info and verified specimens.

If applicable, please provide an authoritative source. FNA does not show a NF or LB range for Lactuca canadensis.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-18 18:56Z]

There was no ref. for the distribution in Nfld. & Labr. I wonder why it was put there.
