### ISSUE TITLE
status in Labrador, and missing synonym?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#853]
[Originally posted on GoogleCode (id 467) on 2011-05-13]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

<b>What data are incorrect or missing?</b>
should Taraxacum lyratum (Ledeb.) DC. be listed in synonymy?
You've carried over the common names, harp dandelion &amp; pissenlit en lyre, from this species, but don't list the species in synonymy.

You also list this species as occurring in NF and LB, but FNA only lists NF (N.Peninsula) in its range.  Do you have new reports of this sp. from Labrador?

<b>If applicable, please provide an authoritative source.</b>
FNA only lists NF in the range.
John Maunder has some pix, tenatively IDed as T. phymatocarpum, from Big Brook, Northern Peninsula: 
http://www.digitalnaturalhistory.com/genus_taraxacum_index.htm#taraxacumcfphymatocarpum

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-20 18:58Z]

What species of Taraxacum are you referring to, please?

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-05-20 19:35Z]

Sorry,

Taraxacum phymatocarpum

http://data.canadensys.net/vascan/taxon/3617

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-02-12 13:35Z]

Sue

The issue with the name T. lyratum is that it is not a stict syn. of T. phymatocarpum but a misapplied name in eNA. T. lyratum is apparently an acc taxon is Siberia and adjacent areas. I am adding it as "auct. non"

I am removing the Labr. distribution: there is no firm data that it is present there (though a potential sight report, not documented by a specimen, has been mentioned to me recently by A. Cuerrier - but let us wait).

Thanks

Luc
