### ISSUE TITLE
Solidago simplex

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#86]
[Originally posted on GoogleCode (id 1847) on 2013-08-09]

Salut

As-tu vu la nouvelle nomenclature selon Semple 2013?
http://www.phytoneuron.net/2013Phytoneuron/41PhytoN-Solidagosimplex.pdf

On renvoie les variétés au rang d'espèce.

Fred

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-09 13:47Z]

C'est d�j� fait ds VASCAN, � para�tre avec la prochaine compilation.
Luc
