### ISSUE TITLE
Erigeron pacalis Björk

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#87]
[Originally posted on GoogleCode (id 1859) on 2013-08-22]

<b>(This is the template to report a data issue for Vascan. If you want to</b>
<b>report another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

<b>What data are incorrect or missing?</b>

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by FredCoursol** [comment]
[Originally posted on GoogleCode on 2013-08-22 15:16Z]

Nouvelle espèce pour BC fide Björk, C.R. 2013. Erigeron pacalis (Asteraceae), a New Species from Western Canadian Boreal Grasslands. NOVON 22(3) : 271-275

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-08-23 19:08Z]

Marc et Marilyn:

Nouevlle espèce ajoutée à VASCAN: Erigeron pacalis

Etymology. The species name comes from the
Latin for ‘‘peace’’ or ‘‘peaceful,’’ named after the
Peace River Valley, where the type of the species was
collected.

L'auteur ne suggère pas de vernaculaire anglais...

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2013-08-23 20:45Z]

Ce sera bien sûr la « vergerette de la rivière de la Paix ».

Le vernaculaire anglais ne fait aucun doute, mais je laisse à Marilyn le soin de s'en occuper.

Marc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2014-01-22 00:55Z]

many thanks for the suggestion, English names added
