### ISSUE TITLE
authority of species name & synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#880]
[Originally posted on GoogleCode (id 494) on 2011-05-16]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4329

<b>What data are incorrect or missing?</b>
Minuartia stricta (Swartz) Hieronymus
Arenaria stricta var. uliginosa (Schleicher) B. Boivin

<b>What data are you expecting instead?</b>
Minuartia stricta (Swartz) Hieron
Arenaria stricta var. uliginosa (Schleicher ex de Candolle) B. Boivin

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-20 12:26Z]

Hieronymus, a correct name, will not be changed to Hieron, an abbreviation
Schleicher ex Lamarck & de Candolle

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-09-13 16:29Z]

Same problem as in M. rubella, my typo - it should be Minuartia stricta (Swartz) Hiern [without the 'o', and not Hieronymus]
See Tropicos, IPNI, and FNA.
