### ISSUE TITLE
authority of species name & synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#882]
[Originally posted on GoogleCode (id 496) on 2011-05-16]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4388

<b>What data are incorrect or missing?</b>
Silene involucrata subsp. tenella (Tolmie) Bocquet
Melandrium taylorae (B.L. Robinson) Tolmie
Melandrium tenellum (Chamisso &amp; Schlechtendal) Tolmie

<b>What data are you expecting instead?</b>
Silene involucrata subsp. tenella (Tolmatchew) Bocquet
Melandrium taylorae (B.L. Robinson) Tolmatchew
Melandrium tenellum (Chamisso &amp; Schlechtendal) Tolmatchew

<b>If applicable, please provide an authoritative source.</b>
Tropicos, IPNI, although Tropicos spells the 2nd name M.tayloriae.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-19 16:03Z]

tayloriae was used in FNA and this was checked by K. Gandhi, so I presume the spelling is tayloriae

**Comment by brouille** [comment]
confirmed: spelling

**Comment by brouille** [comment]
confirmed : spellling is tayloriae
this is the second issue on same topic
Luc
