### ISSUE TITLE
typo in authority abbreviations

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#883]
[Originally posted on GoogleCode (id 497) on 2011-05-16]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4389

<b>What data are incorrect or missing?</b>
Lychnis alba P. Miller
Melandrium album (P. Miller) Garcke
Silene alba (P. Miller) Krause
Silene latifolia subsp. alba (P. Miller) Greuter &amp; Burdet

<b>What data are you expecting instead?</b>
Lychnis alba Miller
Melandrium album (Miller) Garcke
Silene alba (Miller) Krause
Silene latifolia subsp. alba (Miller) Greuter &amp; Burdet

<b>If applicable, please provide an authoritative source.</b>
IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-20 12:44Z]

E.H.L. Krause
