### ISSUE TITLE
typo in authority of species & synonym; status of 1 synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#884]
[Originally posted on GoogleCode (id 498) on 2011-05-16]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4403

<b>What data are incorrect or missing?</b>
Silene suecica (Loddiges) Greuter &amp; Burdot
Lychnis alpina subsp. americana (Fernald) J. Feilberg
Silene suecica subsp. americana (Fernald) Feilberg

<b>What data are you expecting instead?</b>
Silene suecica (Loddiges) Greuter &amp; Burdet  {-et, not -ot)
Lychnis alpina subsp. americana (Fernald) Feilberg
cant find the combination: Silene suecica subsp. americana (Fernald) Feilberg

<b>If applicable, please provide an authoritative source.</b>
IPNI, Tropicos; IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-20 12:52Z]

Removed both infraspecies of S. suecica
