### ISSUE TITLE
status of subsp. americana and subsp. sepium in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#885]
[Originally posted on GoogleCode (id 499) on 2011-05-16]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/4610

<b>What data are incorrect or missing?</b>
status of Calystegia sepium subsp. sepium

<b>What data are you expecting instead?</b>
Calystegia sepium subsp. sepium as introduced in NF
Calystegia sepium subsp. americana as native in NF.

I can understand both subsp. as being introduced in NF., but John Maunder identified 2 specimens of subsp. sepium from the Burin and Avalon Peninsulas. See note below.

<b>If applicable, please provide an authoritative source.</b>
From our NL checklist: 
Not all NF material of Calystegia sepium have been annotated, but verified specimens of subsp. sepium have been found from St. John's, eNfld., and Grand Beach Barasway, near Grand Bank, sNfld. (J. Maunder, pers. comm., NFM.
Also, for subsp. americana, we had this note: NF reports of Calystegia sepium include both the native subsp. americana and the introduced European subsp. sepium.  E.G.Voss (1996, Michigan Flora, vol 3: 99) indicates that subsp. americana can be identified by it's pink flowers, while the European subsp. sepium has white flowers

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-05-16 17:00Z]

Since we wrote the NL checklist, John has found other pops of C. sepium subsp. sepium:
see: http://www.digitalnaturalhistory.com/flora_convolvulaceae_index.htm#calystegiasepiumamericana

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-20 12:54Z]

I am uncertain what you are suggesting here: that we change the status of var. americana to introduced? What would the basis be for this?

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-05-20 19:20Z]

Calystegia sepium subsp. sepium, which is reported from NF in our NF Cklst and pictured on John's website,
it NOT listed in VASCAN at all.  I'm suggesting you_add_  this subsp. to Vascan and list it as introduced in NF.

As far as subsp. americanum goes, Voss considered it native, as well as Scoggan, but I don't know if they're right.
So, I don't care if you list subsp. americanum as native or introduced (whichever is correct should be listed),
but subsp. sepium should be added.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-17 12:02Z]

Vérifier la taxonomie de Calystegia sepium en entier

**Comment by brouille** [comment]
Calystegia has been corrected following Brummit, FNA ms. C. sepium subsp. sepium added to NF as introduced (since more populations are found, it cannot be merely ephemeral).
LB
