### ISSUE TITLE
correction to EN vernacular placement

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#906]
[Originally posted on GoogleCode (id 520) on 2011-05-17]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5859

<b>What data are incorrect or missing?</b>
Oxytropis terrae-novae Fernald is listed as a synonym of Oxytropis campestris var. johannensis rather than O.c. var. minor, yet you've still got the common name, Newfoundland oxytrope, listed under var. minor.  

<b>What data are you expecting instead?</b>
Is the placement of O. terrae-novae correct?  If so, the common name should go with it.

<b>If applicable, please provide an authoritative source.</b>

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-06-16 13:12Z]

Luc, I'm not sure what the result here was.  In our last NL checklist, we had Oxytropis campestris var. johannensis as the field oxytrope and O. campestris var. minor [=O. terrae-novae] as the Newfoundland oxytrope.  Will you be moving the names O. terrae-novae and O. campestris var. terrae-novae to synonymy under var. minor?  If not, is there a new publication by Stan Welsh that explains this change? Is he still the author of this genus treatment?

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-19 18:55Z]

English vernaculars (referring to Newfoundland) moved from var. minor to var. johannensis.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2012-11-19 20:11Z]

Marilyn, You might want to check out my comments in issue # 1574 before 
you make this change.  There are two varieties of Oxytropis campestris 
listed for Nfld. -  var. johannensis and var. minor. These correspond 
with Fernald's  O. johannensis and the smaller O. terrae novae, with his 
description for the latter probably coinciding with var. minor.  I think 
that the synonym var. terrae-novae should be moved to var. minor, not 
the common names move to var. johannensis.  If both names are 
synonymized under var. johannensis, what would be Fernald's equivalent 
to var. minor?  Luc will have to check with the FNA Oxytropis authors on 
this though, since I haven't seen the treatment.

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-11-20 13:45Z]

ok, I'll have to wait for what is happening with these varieties and synonymy - then I'll fix the common names. I didn't see issue 1574. Make sure to mark also as EN vernacular issue. Thanks for pointing this out.

**Comment by brouille** [comment]
Marylin
Oxytropis has been corrected with the FNA ms. I presumed you have seen the vernaculars. If this is fixed, please close issue.
Luc

**Comment by manions** [comment]
Review of Oxytropis English veranculars completed
