### ISSUE TITLE
typo in spelling of epithet in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#907]
[Originally posted on GoogleCode (id 521) on 2011-05-17]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>

<b>What data are incorrect or missing?</b>
Oxytropis terrae-novea Fernald {last 2 letters are reversed in epithet}
Johann's locoweed

<b>What data are you expecting instead?</b>
Oxytropis terrae-novae Fernald 
Saint John River locoweed or Saint John locoweed

<b>If applicable, please provide an authoritative source.</b>
In Gray's manual, they give the meaning of the epithet as: of the &quot;St. John River, Me. &amp; N.B.&quot;, so it is incorrect to call it Johann's locoweed, as the taxon was not named after someone named Johann, but after the St. John River.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-05-17 15:13Z]

forgot to include the URL: http://data.canadensys.net/vascan/taxon/5857

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-05-26 14:28Z]

From Marilyn: Yes, please remove the common name 'Johann's locoweed' and place as 'Saint John River locoweed' and 'Saint John River oxytrope'

Typo corrected
