### ISSUE TITLE
missing Lab. range for Tephroseris palustris

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#914]
[Originally posted on GoogleCode (id 554) on 2011-06-29]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/3621

<b>What data are incorrect or missing?</b>
Range does not include Labrador.

<b>What data are you expecting instead?</b>
This sp. is known from Indian Harbour,Labrador (historical record), and we've seen it on Battle Harbour Island off the Lab. south coast.  See pix in John Maunder's digital flora, link below.

<b>If applicable, please provide an authoritative source.</b>
http://www.digitalnaturalhistory.com/flora_asteraceae_index.htm#tephroserispalustris
FNA also lists it from Labrador.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-06-29 19:18Z]

There is something odd here: the data I see in VASCAN through the back-end indicate that it is native, but without ref.
The VASCAN published data indicate it is excluded for lack of documentation, citing Meades et al. 2000, but when I check, it states present (Indian Harbour)

The data appearing should be native, not excluded.

I am uncertain as to what is happening here. I am adding a ref through the back end, but the mystery of why the difference between the data and what is shown must be investigated.

**Comment by peterdesmet** [comment]
[Originally posted on GoogleCode on 2011-08-02 15:19Z]

Once we get the updates working again, we need to verify that this issue has been solved.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-12 15:15Z]

Issue now solved - data are OK in VASCAN

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-12 15:15Z]

Issue now solved - data are OK in VASCAN

**Comment by cgendreau** [comment]
This issue should be closed
