### ISSUE TITLE
spelling of genus; authority of synonyms

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#920]
[Originally posted on GoogleCode (id 561) on 2011-07-01]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/1277
http://data.canadensys.net/vascan/taxon/5527

<b>What data are incorrect or missing?</b>
Hypopithys 
Hypopithys monotropa Crantz
Hypopithys Americana Small
Hypopithys fimbriata (A. Gray) Howell
Hypopithys lanuginosa (Michaux) Nuttall
Monotropa hypopithys Linnaeus

<b>What data are you expecting instead?</b>
Hypopitys [with no 'h' after the 't']
Hypopitys monotropa Crantz
Hypopitys americana (deCandolle) Nuttall (1843), non (deCandolle) Small {1903) [and with lower case 'a' in americana - basionym of this name: Hypopitys multiflora var. americana deCandolle]
Hypopitys fimbriata (A. Gray) Howell
Hypopitys lanuginosa (Michaux) Rafinesque {1810) non (Michaux) Nuttall (1818)
Monotropa hypopitys Linnaeus

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-07 19:21Z]

already done
basionym added
