### ISSUE TITLE
authority of species & synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#925]
[Originally posted on GoogleCode (id 566) on 2011-07-01]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5549 

<b>What data are incorrect or missing?</b>
Pyrola chlorantha O. Swartz
Pyrola virens Schweigger 

<b>What data are you expecting instead?</b>
Pyrola chlorantha Swartz
?Pyrola virens Schweigger &amp; Körte

<b>If applicable, please provide an authoritative source.</b>
FNA, Tropicos; IPNI has Schweigger &amp; Körte

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-07 19:08Z]

Both ditto.
