### ISSUE TITLE
authority abbreviations of species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#927]
[Originally posted on GoogleCode (id 568) on 2011-07-01]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5557

<b>What data are incorrect or missing?</b>
Rhododendron groenlandicum (Oeder) K.A. Kron &amp; W.S. Judd

<b>What data are you expecting instead?</b>
Rhododendron groenlandicum (Oeder) Kron &amp; Judd

<b>If applicable, please provide an authoritative source.</b>
IPNI authors

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-07 19:06Z]

Already corrected.

I recently checked all synonyms against the FNA data to ensure that all was correct and a large number of corrections and additions were made, as well as the addition of sources for synonyms when they came from FNA.
