### ISSUE TITLE
spelling of specific epithet in synonym?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#929]
[Originally posted on GoogleCode (id 570) on 2011-07-04]

<b>(This is the template to report a data issue. If you want to report</b>
<b>an interface issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/5577

<b>What data are incorrect or missing?</b>
Oxycoccus microcarpos Turczaninow ex Ruprecht

<b>What data are you expecting instead?</b>
Oxycoccus microcarpus Turczaninow ex Ruprecht

<b>If applicable, please provide an authoritative source.</b>
Tropicos has 'microcarpus', even though they use 'oxycoccos'.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-07 19:01Z]

TROPICOS has Oxycoccus microcarpus... may have been corrected recently; So does IPNI.
