### ISSUE TITLE
missing common name use in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#937]
[Originally posted on GoogleCode (id 583) on 2011-07-19]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8921

<b>What data are incorrect or missing?</b>
missing common name used in Nfld.

<b>What data are you expecting instead?</b>
plumboy

<b>If applicable, please provide an authoritative source.</b>
Our NF checklist: Meades, Hay, &amp; Brouillet. 2000.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-20 14:27Z]

Marylin:

Do you agree to add this vernacular? I believe it would be appropriate.

Luc

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2011-07-20 15:02Z]

Hi
Yes it would be quite appropriate to add 'plumboy'.
Marilyn

-- 
--------------------
Marilyn Anions
Director of Science
NatureServe Canada
960 Carling Avenue
KW Neatby Building, Room 2091
Ottawa, Ontario, K1A 0C6

613-759-1942
