### ISSUE TITLE
abbrev. of synonym authority

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#939]
[Originally posted on GoogleCode (id 585) on 2011-07-19]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6247

<b>What data are incorrect or missing?</b>
Juncus alpinus D. Villars

<b>What data are you expecting instead?</b>
Juncus alpinus Villars

<b>If applicable, please provide an authoritative source.</b>
IPNI authors; no need to use the D.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-20 14:25Z]

Was already corrected
