### ISSUE TITLE
accepted name for Euphrasia frigida auct. non Pugsley.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#948]
[Originally posted on GoogleCode (id 594) on 2011-07-23]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9820

<b>What data are incorrect or missing?</b>
Add Euphrasia frigida auct. non Pugsley as a synonym for E. wettsteinii

<b>If applicable, please provide an authoritative source.</b>
Flora of the Canadian Arctic Archipelago lists E. frigida auct., non Pugsley and Euphrasia arctica auct., non Lange ex Rostr., as synonyms of Euphrasia wettsteinii, which has a range in Labrador.  If correct/accepted, this would solve the problem we had for the report of E. frigida from Labrador.
See: http://nature.ca/aaflora/data/www/sceual.htm

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-26 13:16Z]

I will have to wait until I can add homonyms to the database (technical problem). Problem noted.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-09-23 12:37Z]

I also excluded E. frigida from Labrador
