### ISSUE TITLE
typo in species name and authority abbreviation

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#949]
[Originally posted on GoogleCode (id 595) on 2011-07-23]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7104

<b>What data are incorrect or missing?</b>
Fumaria officinalis subsp. wirtgeni (Koch) P.D. Sell

<b>What data are you expecting instead?</b>
Fumaria officinalis subsp. wirtgenii (W.D.J.Koch) Arcangeli 1882, non P.D.Sell (no date given in IPNI, but he was born in 1929)
basionym: Fumaria wirtgenii W.D.J.Koch
Also, note here are 2 ii's at the end of wirtgenii in online dBs.

<b>If applicable, please provide an authoritative source.</b>
Index Synonymique, Tropicos, and IPNI
Flora Europea: http://193.62.154.38/cgi-bin/nph-readbtree.pl/feout?FAMILY_XREF=&amp;GENUS_XREF=Fumaria&amp;SPECIES_XREF=officinalis&amp;TAXON_NAME_XREF=&amp;RANK=

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-26 13:14Z]

added basio subsp.
