### ISSUE TITLE
status of Papaver nudicaule in NF

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#951]
[Originally posted on GoogleCode (id 597) on 2011-07-23]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/7117

<b>What data are incorrect or missing?</b>
Papaver nudicaule is listed as excluded from insular NF

<b>What data are you expecting instead?</b>
it is naturalized in Raleigh, Griguet, and Ship Cove, northern Peninsula, so should be listed as introduced in insular NF rather than excluded.

<b>If applicable, please provide an authoritative source.</b>
Info in our NL checklist.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-26 13:05Z]

Are the reports recent for this species? The reason for exclusion is not merely the absaence of reports, but also the absence of reports for more than 50 years. My impression was that all reports of this taxon were old.

Please confirm recent collections.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-07-26 19:09Z]

Yes, Michael and Anne and I saw lot naturalized in Ship Cove a few year's back and this year I saw some on the Taylor's property, which they say just keep popping up on their own.
