### ISSUE TITLE
Plantago patagonica var. spinulosa (de Candolle) A. Gray

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#96]
[Originally posted on GoogleCode (id 1905) on 2013-10-18]

Autorité mauvaise:
Plantago patagonica var. spinulosa (Decaisne) A. Gray selon IPNI, FNAms

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-10-18 15:38Z]

déjà corrigé
