### ISSUE TITLE
report from Labrador?

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#961]
[Originally posted on GoogleCode (id 612) on 2011-07-28]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8208

<b>What data are incorrect or missing?</b>
reported from Labrador

<b>What data are you expecting instead?</b>
Have you received a recent confirmation of this species from Labrador?  The report I made to you a while ago was an error, which I corrected back in 2008. 

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-28 18:05Z]

No, no recent report. I guess we missed your 2008 correction. Removed.
