### ISSUE TITLE
status of Lysimachia nummularia in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#962]
[Originally posted on GoogleCode (id 613) on 2011-07-28]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/6689

<b>What data are incorrect or missing?</b>
native in insular Newfoundland

<b>What data are you expecting instead?</b>
introduced in insular Newfoundland

<b>If applicable, please provide an authoritative source.</b>
Report refers to an escaped population in the Anglican Cemetery in St. John's, which has persisted for a while; specimen in GH:
http://www.digitalnaturalhistory.com/flora_myrsinaceae_index.htm#lysimachianummularia
See Appendix II of our checklist.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-28 18:01Z]

This has already been corrected.
