### ISSUE TITLE
missing common names

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#969]
[Originally posted on GoogleCode (id 620) on 2011-07-29]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8841

<b>What data are incorrect or missing?</b>
missing common names used consistently in Newfoundland

<b>What data are you expecting instead?</b>
En: Burnt Cape cinquefoil 
Fr: potentille du cap Brûlé 

<b>If applicable, please provide an authoritative source.</b>
our Nfld. checklist.  These common names are used extensively in Nfld. tourism lit, tied in with the interprestion value of Burnt Cape.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-07-29 13:22Z]

Marylin:

I have no objection to adding this alternate vernacular.

OK?

Luc

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-04 19:07Z]

from M. Anions (email)
"Hi Luc
Yes please add Burnt Cape cinquefoil as an alternate common name please.
Sorry for the delay but was away last week.
Cheers
Marilyn"

However, I do not see why a vernacular should be added in French. Is it also used by Nfld. tourism? Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-08-04 22:06Z]

I think they use both common names at Burnt Cape, but I don't think it matters if you want to leave out the French translation of Burnt Cape cinquefoil.  Not too many people will even notice, since outside of Nfld., no one is familiar with Fernald's name.

Thanks, Sue.

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2014-02-05 14:05Z]

http://data.canadensys.net/vascan/taxon/8841

As per the above change in authority from R.Brown ex Ross to R.Brown, the synonym 
Potentilla pulchella R. Brown ex Ross var. pulchella

should be: Potentilla pulchella R. Brown var. pulchella
