### ISSUE TITLE
Tsuga canadensis

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#97]
[Originally posted on GoogleCode (id 1921) on 2013-11-02]

Le MRN du Québec utilise pruche de l'Est comme nom commun.
À ajouter dans VASCAN

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-14 20:27Z]

Marc
svp faire ajout
merci
Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2014-01-14 20:31Z]

J'ai ajouté le nom, qui figurait d'ailleurs comme synonyme dans Les Arbres du Canada.
