### ISSUE TITLE
duplicate synonym for 2 species

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#971]
[Originally posted on GoogleCode (id 622) on 2011-07-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8927
http://data.canadensys.net/vascan/taxon/8944

<b>What data are incorrect or missing?</b>
Rubus pergratus var. terrae-novae Fernald is listed as a synonym for both of these species. HWR, Rubus pergratus Blanchard is only lsited as synonym of Rubus canadensis.

<b>What data are you expecting instead?</b>
list synonyms under the correct species

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-01 13:26Z]

I do not know why it is repeated - it is not in the FNA ms, so no help there. I will have to determine which is the proper parent

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-05 12:48Z]

I removed the syn from under R. pensylvanicus
