### ISSUE TITLE
status of some Rosa spp. in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#972]
[Originally posted on GoogleCode (id 623) on 2011-07-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/1627

<b>What data are incorrect or missing?</b>
The following Rosa species are listed as introduced in Nfld.  Do you have new reports for these?
Rosa blanda 
Rosa cinnamomea 
Rosa rubiginosa 
Rosa rubrifolia 
Rosa rugosa  
 

<b>What data are you expecting instead?</b>
Rosa blanda – was listed as excluded in our NL flora; 
Rosa cinnamomea – a new report, not listed in our NL flora; 
Rosa rubiginosa – cultivated in wNfld., but not know to escape
Rosa rubrifolia - cultivated; often persists around old homesteads, but does not spread into new areas
None of the above species have any entries in John's digital flora.

The following species is sold in nurseries, but I don't have any reports of it occurring outside of sites that were planted. John has one set of pix from Rennies River, a trail on former private property in the centre of St. John's; I doubt it is naturalized there.
Rosa rugosa – cultivated – introduced thr. Nfld.

Do you have details of any new reports for these species to move them from the cultivated or excluded Appendices in our checklist?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2012-05-29 13:33Z]

All changes to Rosa statuses resulted from communication from J. Maunders in 2009, who had serious arguments about them.

Rosa rugosa: MT specimen is being checked
