### ISSUE TITLE
status of Rubus setosus in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#973]
[Originally posted on GoogleCode (id 624) on 2011-07-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8947

<b>What data are incorrect or missing?</b>
Rubus setosus is listed as native in Nfld.

<b>What data are you expecting instead?</b>
...we had it listed as excluded in our Nfld. checklist

Do you have details of new reports?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-01 13:22Z]

In the FNA treatment of Rubus by Alice et al., R. setosus is listed - the list of synonyms of this species is long and includes R. vermontanus (we had it the other way around: setosus syn of vermontanus)

R. setosus Bigelow 1824 is older than vermontanus Blanchard...

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-08-02 18:55Z]

Hi Luc,

Yes, we had /Rubus vermontanus/ listed as a synonym of /R. setosus/, but 
we also included this note under /Rubus canadensis/:

"Rouleau & Lamoureux (1992) indicate two locations for /Rubus 
vermontanus/ in Nfld.; one specimen has been referred to /Rubus 
canadensis/, the other to /Rubus hispidus/, annotated by S.G.Hay."

As far as I know, we have no verified specimens of either /Rubus 
setosus/ or /Rubus vermontanus /from Newfoundland.  Unless you have new 
reports?

Thanks, Sue.
