### ISSUE TITLE
status of balsam poplar in NL

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#977]
[Originally posted on GoogleCode (id 628) on 2011-07-30]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9044

<b>What data are incorrect or missing?</b>
Populus balsamifera is listed as excluded from insular Newfoundland.

<b>What data are you expecting instead?</b>
This is definitely native in Newfoundland.  

<b>If applicable, please provide an authoritative source.</b>
I've seen it on Burnt Cape and other places on the Northern Peninsula (including this past trip); John Maunder has pix of it from Eddie's Cove East, also the Northern Peninsula in his digital flora.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-01 13:05Z]

I do not understand why it was listed as it was.
