### ISSUE TITLE
status in Labrador

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#980]
[Originally posted on GoogleCode (id 631) on 2011-08-01]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/8035

<b>What data are incorrect or missing?</b>
Collomia linearis isn't listed from Labrador

<b>What data are you expecting instead?</b>
Collomia linearis is found in Goose Bay, Labrador, as an introduced species.

<b>If applicable, please provide an authoritative source.</b>
Since 2006, this speices has been collected from various locations around the Goose Bay airport by Mike MacDonald, then Marion Sensens, and me, with Mike Crowell and Sean Bennet in 2010.  Our spccimens will go to the NFM, but I'm not sure where Marion's are, as she is working for Agra.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-01 12:41Z]

it was labeled as doubtful - but there is confirmation in the number of collections. I have it as being referenced at NFM...

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-01 12:41Z]

it was labeled as doubtful - but there is confirmation in the number of collections. I have it as being referenced at NFM...
