### ISSUE TITLE
status of Salix ×laurentiana  in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#983]
[Originally posted on GoogleCode (id 643) on 2011-08-02]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9180

<b>What data are incorrect or missing?</b>
Salix ×laurentiana is listed as native in insular Nfld.

<b>What data are you expecting instead?</b>

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-04 19:00Z]

Sue

What is the expected outcome?

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-08-04 21:32Z]

Sorry, I guess I hit the 'Submit' too quickly.   I wanted to know if you had any information confirming it's presence in Nfld.  We had excluded it from our NL checklist, but you may have more recent info.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-05 12:38Z]

Sue

In the NL checklist, only Labrador is specifically excluded - Nfld is not mentioned.

Scoggan mentions the entity for Nfld., but I do not know whether this was confirmed by Argus - I have no note to this effect

More to check

Luc

**Comment by sjmeades** [comment]
[Originally posted on GoogleCode on 2011-08-08 03:08Z]

I noticed you don't include common names for this hybrid, which is the usual practice, I think. But the USDA dB and other online tax dBs list the common name as Laurent's willow.  Since I assume this hybrid was named for either the Gulf of St. Lawrence or the Laurentian area and not for someone name Laurent, you may want to add the common name Laurentian willow, primarily to correct the misconception that the USDA dB started with their arbitrary common name.  I also found this French common name on a French Wikipedia site: saule de larentides.

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-11-21 20:01Z]

Sue

I am forwarding your last comment to Marilyn and Marc. Both these names seem misconstrued. I doubt that the willow has anything to do with Laurentian hills... more with the St. Lawrence, where Fernald made many studies.

Luc

**Comment by MFavreau** [comment]
[Originally posted on GoogleCode on 2011-11-21 21:12Z]

In Gray's Manual (1950, p. 512), Fernald states that the taxon is named after "the River and Gulf of St. Lawrence", but his description of the distribution seems to refer more to the Gulf than to the River.

We usually do not bother coining new French names for hybrids, but there this can be done when it serves a purpose. I will enter the French name "saule du golfe Saint-Laurent".

**Comment by manions** [comment]
[Originally posted on GoogleCode on 2012-01-30 17:11Z]

good suggestion, english vernacular provided as Gulf of St. Lawrence willow
