### ISSUE TITLE
typo and duplication in synonym

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#985]
[Originally posted on GoogleCode (id 645) on 2011-08-02]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9212

<b>What data are incorrect or missing?</b>
Acer rubrum var. tribolubm K. Koch

<b>What data are you expecting instead?</b>
Acer rubrum var. trilobum K. Koch, but I assume this is the same as:
Acer rubrum var. trilobum Torrey &amp; A. Gray ex K. Koch, which you already have, so you can just delete the misspelled name.

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-04 18:58Z]

We currently have var. trilobum K. Koch.
The typo is now corrected. TX
