### ISSUE TITLE
Port manquant

### ISSUE THREAD

**Issue by FredCoursol** [Canadensys/vascan-data#99]
[Originally posted on GoogleCode (id 1993) on 2013-12-22]

Salut Luc

Je viens de faire l'extraction des plantes mentionnées pour le Québec dans VASCAN (incluant les douteuses et les mentions exclues).

Pour la liste suivante, il manque le port (herbacée, arbre, etc..)

Acer nigrum × Acer saccharum
Agalinis purpurea var. parviflora
Betula ×borggreveana
Botrychium tenebrosum
Carex saxatilis × Carex vesicaria
Juncus ×stuckeyi
Juncus alpinoarticulatus
Pyrola asarifolia × Pyrola minor
Amaranthus blitum subsp. emarginatus
Lycopus americanus × Lycopus europaeus
Geranium aequale
Stachys tenuifolia

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2014-01-10 17:00Z]

merci!
