### ISSUE TITLE
status of Solanum nigrum in insular Nfd.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#995]
[Originally posted on GoogleCode (id 655) on 2011-08-03]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9381

<b>What data are incorrect or missing?</b>
Solanum nigrum is not listed for insular Nfld.

<b>What data are you expecting instead?</b>
Solanum nigrum should be listed as ephemeral in Nfld.

<b>If applicable, please provide an authoritative source.</b>
Our NL checklist includes this note under Solanum nigrum:
[Bassett and Munro (1985) discuss Solanum species easily confused with Solanum nigrum; they have revised one specimen, from near St. John's, to Solanum sarrachoides Sendt.  H. Mann reports two specimens at SWGC: Grand Falls (E. Kayler, 1981) and Port aux Basques (I.J. Green, 1974, ballast).; M. Anions also reports plants at Norris Point (dump), wNfld. (pers. comm., 2000).]

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2013-06-17 12:25Z]

Solanum sarrachoides Sendt., one of the species in the S. nigrum complex, IS reported as eph in Nfld.

There is no need therefore to add S. nigrum, since it is not this species in the area.

Luc
