### ISSUE TITLE
status of Viola melissaefolia in Nfld.

### ISSUE THREAD

**Issue by sjmeades** [Canadensys/vascan-data#998]
[Originally posted on GoogleCode (id 658) on 2011-08-03]

<b>(This is the template to report a data issue. If you want to report</b>
<b>another issue, please change the template above.)</b>

<b>What is the URL of the page where the problem occurs?</b>
http://data.canadensys.net/vascan/taxon/9534

<b>What data are incorrect or missing?</b>
status of Viola melissaefolia in Nfld.

<b>What data are you expecting instead?</b>
I don't understand how this can be in Nfld. if we only have one of the parent species (V. septentrionalis)?   That said, the pix that John Maunder has on his digital flora of Viola septentrionalis clarely have cilate sepals, which is one of the most reliable traits I use to ID Viola sororia.  Are you sure we have V. septentrionalis and not V. sororia?  Or probably the more relevant question is are you satisfied that they are indeed two separate species?

<b>If applicable, please provide an authoritative source.</b>

**Comment by brouille** [comment]
[Originally posted on GoogleCode on 2011-08-04 14:14Z]

This appears to be a mistake. I cannot find a source for this report and I do not particularly recall this hybrid in Nfld either.
I am removing the report.

This also showed me that I had neglected to add the parents of the hybrid. Corrected now. Thanks for attracting my attention.
